objects/Account.object
<CustomObject>
    <fields>
        <fullName>Allocated_Partner_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Partner Allocated to the End Customer Account</description>
        <label>Allocated Partner 1</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Allocated Partner 1</relationshipLabel>
        <relationshipName>AllocatedPartner1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Allocated_Partner_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Partner Allocated to the End Customer Account</description>
        <label>Allocated Partner 2</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Allocated Partner 2</relationshipLabel>
        <relationshipName>AllocatedPartner2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Allocated_Partner_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Partner Allocated to the End Customer Account</description>
        <label>Allocated Partner 3</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Allocated Partner 3</relationshipLabel>
        <relationshipName>AllocatedPartner3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Allocated_Partner_4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Partner Allocated to the End Customer Account</description>
        <label>Allocated Partner 4</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Allocated Partner 4</relationshipLabel>
        <relationshipName>AllocatedPartner4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRName__c</fullName>
        <label>CR Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
                <value>
                    <fullName>BRAZIL</fullName>
                </value>
                <value>
                    <fullName>INDIA</fullName>
                </value>
                <value>
                    <fullName>UNITED STATES</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Expected_Booking_Other__c</fullName>
        <label>Expected Booking Other</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expected_Bookings_Collab_App_000__c</fullName>
        <label>Potential Bookings-Collab App ($000)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expected_Bookings_Collab_Voice_000__c</fullName>
        <label>Potential Bookings-Collab Voice ($000)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expected_Bookings_Data_Center_UCS_000__c</fullName>
        <label>Potential Bookings-Data Center UCS $000</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expected_Bookings_Routing_000__c</fullName>
        <label>Potential Bookings-Routing ($000)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expected_Bookings_Security_000__c</fullName>
        <label>Potential Bookings-Security ($000)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expected_Bookings_Services_000__c</fullName>
        <label>Potential Bookings-Services ($000)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expected_Bookings_Switching_000__c</fullName>
        <label>Potential Bookings-Switching ($000)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expected_Bookings_Telepresence_000__c</fullName>
        <label>Potential Bookings-Telepresence ($000)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expected_Bookings_Wireless_000__c</fullName>
        <label>Potential Bookings-Wireless ($000)</label>
        <precision>16</precision>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Release_to_Unallocated_Pool__c</fullName>
        <description>Flags end customer accounts which can be released to uncovered pool (Shark Pool)</description>
        <label>Release to Unallocated Pool</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                    <color>#FF0000</color>
                    <label>Yes</label>
                </value>
                <value>
                    <fullName>No</fullName>
                    <color>#78C953</color>
                    <label>No</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Show_Account_in_Unallocated_Pool__c</fullName>
        <formula>IF( 
ISPICKVAL(Unallocated_Account__c ,'Yes') &amp;&amp; 
ISPICKVAL( Release_to_Unallocated_Pool__c,'Yes') &amp;&amp; 
ISBLANK( Allocated_Partner_1__c ) &amp;&amp; 
ISBLANK( Allocated_Partner_2__c ) &amp;&amp; 
ISBLANK( Allocated_Partner_3__c ) &amp;&amp; 
ISBLANK( Allocated_Partner_4__c ), 
'TRUE','FALSE' 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Show Account in Unallocated Pool</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unallocated_Account__c</fullName>
        <description>Flags end customer accounts that are not allocated to any partner.</description>
        <label>Unallocated Account</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                    <color>#FF0000</color>
                    <label>Yes</label>
                </value>
                <value>
                    <fullName>No</fullName>
                    <color>#78C953</color>
                    <label>No</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Wallet_Collab_Applications__c</fullName>
        <label>Wallet-Collab Applications ($000)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Wallet_Data_Center_UCS_000__c</fullName>
        <description>Current Fiscal Year Data Center UCS  wallet in thousands per Customer Intelligence data source for the end customer</description>
        <label>Wallet-Data Center UCS ($000)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Wallet_Other_000__c</fullName>
        <description>Current Fiscal Year Other wallet in thousands per Customer Intelligence data source for the end customer</description>
        <label>Wallet-Other ($000)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Wallet_Routing_000__c</fullName>
        <description>Current Fiscal Year Routing  wallet in thousands per Customer Intelligence data source for the end customer</description>
        <label>Wallet-Routing ($000)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Wallet_Security_000__c</fullName>
        <description>Current Fiscal Year Security  wallet in thousands per Customer Intelligence data source for the end customer</description>
        <label>Wallet-Security ($000)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Wallet_Services_000__c</fullName>
        <label>Wallet-Services ($000)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Wallet_Switching_000__c</fullName>
        <description>Current Fiscal Year Switching  wallet in thousands per Customer Intelligence data source for the end customer</description>
        <label>Wallet-Switching ($000)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Wallet_Unified_Communications_000__c</fullName>
        <description>Current Fiscal Year Unified Communications  wallet in thousands per Customer Intelligence data source for the end customer</description>
        <label>Wallet-Collab Voice ($000)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Wallet_Video_000__c</fullName>
        <description>Current Fiscal Year Video wallet in thousands per Customer Intelligence data source for the end customer</description>
        <label>Wallet-Telepresence ($000)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Wallet_Wireless_000__c</fullName>
        <description>Current Fiscal Year Wireless  wallet in thousands per Customer Intelligence data source for the end customer</description>
        <label>Wallet-Wireless ($000)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer recordtype for C360</description>
        <label>Customer</label>
    </recordTypes>
</CustomObject>

objects/Assigned_Partner__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Partner Account assigned to this target account.</description>
        <label>Assigned Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Assigned_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Marketing_Play_Name__c</fullName>
        <description>Nov 13 Release: Field is to store marketing campaign name</description>
        <label>Marketing Play Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Architecture__c</fullName>
        <label>Target Architecture</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Any/All Technologies</fullName>
                </value>
                <value>
                    <fullName>Collaboration-Unified Communications (UC)</fullName>
                </value>
                <value>
                    <fullName>Core-Routing Switching &amp; Services</fullName>
                </value>
                <value>
                    <fullName>Data Center-Unified Computing Systems (UCS)</fullName>
                </value>
                <value>
                    <fullName>Video-TelePresence &amp; Conferencing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Target_Description__c</fullName>
        <label>Target Description</label>
        <type>TextArea</type>
    </fields>
    <description>Partner assignments of End User Accounts are stored in this object.</description>
    <label>zzTarget Prospect</label>
    <nameField>
        <label>Target Prospect Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Target Prospects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SCP_Communities_TPFilter_CT_Test.cls
@isTest(SeeAllData = false)
private class SCP_Communities_TPFilter_CT_Test {
    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        // Create Org_Constant_CS__c custom settings data
        String timestamp = String.valueOf(Datetime.now().getTime());
        UtilUnitTest.loadAllStaticData();
        // Get PA record
        
        user pauser1 = GenericStaticTestData.gettestPAUserRecord();
        string roleName = pauser1.UserRole.name;
        //System.assertEquals('Partner Executive',roleName);
        System.assertEquals(1,[select COUNT() from userrole where portalaccountid =:GenericStaticTestData.gettestChannelAccountRecord1().id and Name like '%Partner Executive' limit 1]);
        //System.assert(roleName.endsWith('Partner Executive'));
        
        user psruser1 = GenericStaticTestData.gettestPSRUserRecord();
        
       // System.assertEquals(1, [SELECT COUNT() FROM USER WHERE username = 'testpa@cisco.com.sales.test']);
        
        // Get End customer account
        Account eca =new Account();
        eca = GenericStaticTestData.getTestEndUserAccountRecordRed();
        eca.Name = 'testec'+timestamp;
        eca.Unallocated_Account__c = 'Yes';
        eca.Release_to_Unallocated_Pool__c = 'Yes';
        eca.RecordTypeId = '0123000000004aUAAQ';
        eca.CRName__c = 'testec CRName'+timestamp;
        eca.Country__c='UNITED STATES';
        eca.Industry = 'Center/ISPs';
        eca.Wallet_Wireless_000__c = 20 ;
        eca.Wallet_Video_000__c = 20 ;
        eca.Wallet_Unified_Communications_000__c = 20 ;
        eca.Wallet_Switching_000__c = 20 ;
        eca.Wallet_Services_000__c = 20 ;
        eca.Wallet_Security_000__c = 20 ;
        eca.Wallet_Routing_000__c = 20 ;
        eca.Wallet_Other_000__c = 20 ;
        eca.Wallet_Data_Center_UCS_000__c = 20 ;
        eca.Wallet_Collab_Applications__c = 20 ;
        eca.Wallet_Unified_Communications_000__c = 20 ;
        eca.Wallet_Wireless_000__c = 20 ;
        eca.Expected_Bookings_Wireless_000__c = 40 ;
        eca.Expected_Bookings_Telepresence_000__c = 40 ;
        eca.Expected_Bookings_Switching_000__c = 40 ;
        eca.Expected_Bookings_Services_000__c = 40 ;
        eca.Expected_Bookings_Security_000__c = 40 ;
        eca.Expected_Bookings_Routing_000__c = 40 ;
        eca.Expected_Bookings_Data_Center_UCS_000__c = 40 ;
        eca.Expected_Bookings_Collab_Voice_000__c = 40 ;
        eca.Expected_Bookings_Collab_App_000__c = 40 ;
        eca.Expected_Booking_Other__c = 40 ;
        eca.Allocated_Partner_1__c = null;
        eca.Allocated_Partner_2__c = null;
        eca.Allocated_Partner_3__c = null;
        eca.Allocated_Partner_4__c = null;
        //eca.OwnerId = pauser1.Id;
        update eca;
        
        System.assertEquals('TRUE', [Select Show_Account_in_Unallocated_Pool__c FROM Account Where Id = :eca.Id].Show_Account_in_Unallocated_Pool__c);
        Assigned_Partner__c tp = new Assigned_Partner__c ();
        tp.Target_Architecture__c = 'Any/All Technologies';
        tp.Target_Description__c = 'test target';
        tp.Marketing_Play_Name__c = 'testtpmarketingname';
        tp.Cisco_Recomended_Partner_Sales_Rep__c =  psruser1.Id;
        tp.Customer_Account__c = eca.Id;
        tp.Assigned_Partner__c = GenericStaticTestData.gettestChannelAccountRecord1().Id;
        insert tp;
        
        Contact c = GenericStaticTestData.gettestPartnerProvidedPAContactRecord();
        c.Partner_Admin_Roles__c = 'PARTNER_LED_APP_ADMIN,PARTNER_LED_APP_USER';
        update c;
        
        System.runAs(pauser1) {
            Test.startTest();
           // System.assertEquals(1, [Select COUNT() FROM Account Where Account.Show_Account_in_Unallocated_Pool__c = 'TRUE']);
            // Crate TP Records
            /*
            Select a.Technology_Filter__c, a.Target_Description__c, 
            a.Target_Architecture__c, a.Name, a.Marketing_Play_Name__c, 
            a.Assigned_Partner__c, a.Assigned_Partner_Sales_Rep__c 
            From Assigned_Partner__c a
            */
            
            SCP_Communities_TPFilter_CT con = new SCP_Communities_TPFilter_CT();
            PageReference pageRef = Page.SCP_Communities_targetprospectfilter;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('view', 'newprospects');
            ApexPages.currentPage().getparameters().put('tpc','1');
            String msg = con.uncoveredProspectsMsg;
            List<SelectOption> views = con.viewOptions;
            con.marketingPlay = 'testtpmarketingname';
            con.customername = 'Test End';
            con.selectedTagetArchitecture =  new String[]{'Any/All Technologies'};
            con.ciscoRecommendedPSR =  psruser1.Id;
            con.selectedIndustry =  new String[] {'Center/ISPs'};
            con.selectedTechnology = 'Collab Applications';
            con.selectedCountry = new String [] {'UNITED STATES','INDIA'};
            con.city = 'San Jose';
            con.stateorProvince ='CA';                
            con.doSearch();
            con.getSearchPageUrl();
            con.getPsr();
            system.assert(con.isNewlyAssignedProspect);
            //system.assert(con.pageRecords.size() > 0);

            System.debug(con.pageRecords);
            con.clearfields();
            
            con.selectedView = views[3].getValue();
            con.doSearch();
            con.marketingPlay = 'testtpmarketingname';
            con.customername = 'Test';
            con.selectedTagetArchitecture =  new String[]{'Any/All Technologies'};
            con.ciscoRecommendedPSR =  psruser1.Id;
            con.selectedIndustry =  new String[] {'Center/ISPs'};
            con.selectedTechnology = 'Collab Applications';
            con.selectedCountry = new String [] {'UNITED STATES','INDIA'};
            con.city = 'San Jose';
            con.stateorProvince ='CA';                
            con.myPg = null;
            con.doSearch();
            
            con.clearFields();
            con.selectedView = views[3].getValue();
            con.doSearch();
            //system.assert(con.pageRecords.size() > 0);
            if(con.pageRecords != null && con.pageRecords.size() >0 ) {
                con.pageRecords[0].isSelected = true;
            }
            Pagereference pg = con.openWorkProspectPage();
            con.getViewListComponent();
            
            Map<String, SCP_Communities_ComponentControllerBase> ccbmap = con.getComponentControllerMap();
            SCP_Communities_PSRBulk_CT psrbulkcon = con.getPsr();
            psrbulkcon.setKey(con.psrKey);
            psrbulkcon.setPageController(con.getThis());
            psrbulkcon.psr1_Id = pauser1.Id;
            psrbulkcon.assignPSRs();
           // System.assert(con.isPA);
            Test.stopTest();
        }
        
    }
}