objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer recordtype for C360</description>
        <label>Customer</label>
    </recordTypes>
</CustomObject>

objects/C360HealthScore__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <description>Customer or BU Account Numbers</description>
        <externalId>true</externalId>
        <label>Account Number</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_hi__c</fullName>
        <description>Overall Health Score values</description>
        <label>Customer_hi</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Finance_Score__c</fullName>
        <label>Finance Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Index__c</fullName>
        <label>Index</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quality_Score__c</fullName>
        <label>Quality Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sentiment_Score__c</fullName>
        <label>Sentiment Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Utilization__c</fullName>
        <label>Utilization</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Wow_Status__c</fullName>
        <label>Wow Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Up</fullName>
                </value>
                <value>
                    <fullName>Down</fullName>
                </value>
                <value>
                    <fullName>No Change</fullName>
                </value>
                <value>
                    <fullName>Null</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>C360HealthScore</label>
    <nameField>
        <label>C360HealthScore Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>C360HealthScores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ObjectRecordTypeIds__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is used to store the record type ids of account and contact objects.</description>
    <label>Object Record Type Ids</label>
</CustomObject>

classes/C360_HealthScoreController.cls
/************************************************************************************************************************************
Name    : C360_HealthScoreController
Author  : C360 Dev team
Purpose : Getting data from C360HealthScore__c object to display in customer/BU view
Date    : 28/06/2019
Change History : NA
*************************************************************************************************************************************/
public class C360_HealthScoreController {
    
    @AuraEnabled
    public static String gethealthScores(Id customerId){
        Map<String,String> resultMap = new Map<String,String>();
        String custAccNumber ='';
        Boolean isCustomerRT = false;
        ObjectRecordTypeIds__c accRTId = ObjectRecordTypeIds__c.getOrgDefaults();
        Account accRec = new Account();
        accRec  = [SELECT Id,Name,AccountNumber,RecordTypeId FROM Account WHERE Id =:customerId and RecordType.Name IN ('Customer','Business Unit') limit 1];
        if(accRec!= null && accRec.AccountNumber != null ){
            custAccNumber = accRec.AccountNumber;
        }
        
        C360HealthScore__c healthScore =  new C360HealthScore__c();
        healthScore  = [SELECT Id,Account_Number__c,Index__c,Utilization__c,Quality_Score__c,Sentiment_Score__c,Finance_Score__c,Wow_Status__c,Customer_hi__c FROM C360HealthScore__c WHERE Account_Number__c =: custAccNumber limit 1];        
        if(healthScore !=null){
            return JSON.serialize(healthScore);
        }else{
            return 'error';          
        } 
        
    }
    
}