objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_ID__c</fullName>
        <label>TO BE DELETED Account ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AddressLine1__c</fullName>
        <label>Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSCSiteID__c</fullName>
        <description>Previously CSC Site ID</description>
        <externalId>true</externalId>
        <label>Party ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
                <value>
                    <fullName>BRAZIL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DUNSNumber__c</fullName>
        <label>zzD&amp;B Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HQ_Party_ID__c</fullName>
        <description>HQ_Party_Id is an identifier coming from CR for an Account.</description>
        <label>HQ Party ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State/Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Overlay_Acct_SuperGroup_Rel__c.object
<CustomObject>
    <fields>
        <fullName>Account_ID__c</fullName>
        <description>Master Detail Field relating to Account Object</description>
        <label>Account ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Super Groups</relationshipLabel>
        <relationshipName>Overlay_Acct_Super_Group_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Super_Group__c</fullName>
        <description>Master Detail Field relating to Super Group Object</description>
        <label>Super Group</label>
        <referenceTo>Super_Group__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Overlay_Acct_Super_Group_Relationships</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <description>This object is to create many to many relationship between Overlay Super Group Object and Account object</description>
    <label>Overlay Acct Super Group Relationship</label>
    <nameField>
        <displayFormat>OASG-{0}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Overlay Acct Super Group Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Super_Group__c.object
<CustomObject>
    <description>This object will store the FDEV super group information from FDEV</description>
    <label>Super Group</label>
    <nameField>
        <label>Super Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Super Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Super_Group_Overlay_Acct_CTE.cls
// This class acts as Controller Class for Super_Group_Overlay_Acct VF
// Release -- FY'13 Year End Rel 

public with sharing class Super_Group_Overlay_Acct_CTE {
  
    private Integer pagesize = 5;
    private String  SuperGroupId;
    private String query;
    public  Integer totalPages {get; set;}
    public  String  navigateToAccount {get; set;}
    
    private String sortOrderOld = 'ASC';
    private String sortColumnNameOld = 'Name';
    public  String sortOrderNew {get; set;}
    public  String sortColumnNameNew {get; set;}
    
    public Super_Group_Overlay_Acct_CTE (ApexPages.StandardController controller) {
        navigateToAccount = Utilities.getSuperGroupOverlayAccountRelatedListId();
        SuperGroupId = ApexPages.currentpage().getparameters().get('Id');
    }
    
        
    public ApexPages.StandardSetController ACCTCON {
        get {
         try{
                if(ACCTCON == null) {
                
                String query = 'Select Id, Name,Owner.Name,HQ_Party_ID__c,CSCSiteID__c,DUNSNumber__c,AddressLine1__c,'+
                               'City__c,State__c,Country__c from Account where Id IN' +
                               '(Select Account_ID__c from Overlay_Acct_SuperGroup_Rel__c where Super_Group__c = :SuperGroupId)' +
                               'ORDER BY Name ASC limit 10000';                        
                Paging(query); 
                
                if(Utilities.getIsTestMethod()== true){                 
                    String str = null;    
                    str.tolowercase();                             
                 }                
              }
             return ACCTCON;
            }
            catch(Exception e){
                ApexPages.addMessages(e);
                System.debug('Super_Group_Overlay_Acct_CTE ## ACCTCON ## Exception ## ' + e);
                return null;
            }
        }
        set;
        }

//This method is used for Pagination on Visualforce Page, for a given Super Group Record
                  
    public void Paging(String query){
        try{
            ACCTCON = new ApexPages.StandardSetController(Database.getQueryLocator(query));  
            // sets the number of records in each page set
            ACCTCON.setPageSize(pagesize);
            // total page count
            if(Math.Mod(ACCTCON.getResultSize(),pagesize) == 0){
                totalPages = ACCTCON.getResultSize()/pagesize;
            }
            else {
                totalPages = ACCTCON.getResultSize()/pagesize + 1;
            }
            
            if(Utilities.getIsTestMethod()== true){                 
                    String str = null;    
                    str.tolowercase();                             
              }      
          }
        catch(Exception e){
            ApexPages.addMessages(e);
            System.debug('Super_Group_Overlay_Acct_CTE ## Paging ## Exception ## ' + e);
        }    
    }

//This method is used to get Account Records on Visualforce Page, for a given Super Group Record 
 
   public List<Account> getAccountRecords(){
     try{         
        if(ACCTCON != null){
            return (List<Account>) ACCTCON.getRecords();
            }
        
        if(Utilities.getIsTestMethod()== true){                 
                    String str = null;    
                    str.tolowercase();                             
            }      
        }  
       catch(Exception e){
            ApexPages.addMessages(e);
            System.debug('Super_Group_Overlay_Acct_CTE  ## getAccountGroupRecords ## Exception ## ' + e);
            return null;
        }    
        return null;
    } 

//This method is used for Sorting Account Name & Account Owner on Visualforce Page, for a given Super Group Record
    
    public PageReference OrderData (){
       try{
            String orderByExp = '';
      
            if(sortColumnNameNew != sortColumnNameOld){   
                sortOrderNew  = 'ASC';
            }
        
            if(sortColumnNameNew == sortColumnNameOld){   
                if(sortOrderOld == 'ASC')  
                    sortOrderNew = 'DESC';
                else     
                    sortOrderNew = 'ASC'; 
            }      
        
            sortColumnNameOld = sortColumnNameNew;
            sortOrderOld = sortOrderNew;
        
            orderByExp  =  'order by' + ' ' + sortColumnNameNew + ' ' + sortOrderNew;
    
            query = 'Select Id, Name,Owner.Name,HQ_Party_ID__c,CSCSiteID__c,DUNSNumber__c,AddressLine1__c,'+
                    'City__c,State__c,Country__c from Account where Id IN' +
                    '(Select Account_ID__c from Overlay_Acct_SuperGroup_Rel__c where Super_Group__c = :SuperGroupId)' +
                    ' ' + orderByExp + ' ' + 'LIMIT 10000'; 
            
            Paging(query);
            
            if(Utilities.getIsTestMethod()== true){                 
                    String str = null;    
                    str.tolowercase();                             
              }      
         }              
         catch(Exception e){
            ApexPages.addMessages(e);
            System.debug('Super_Group_Overlay_Acct_CTE ## OrderData ## Exception ## ' + e);
            return null;
         }    
        return null;
    }
    
    // This method redirects Excel Export Link Page to Excel Export Page for Ovelay Account data
    public PageReference exportOverlayAcctLink() {
        try{
            PageReference redirect = new PageReference('/apex/Super_Group_Overlay_Acct_Export'); 
            redirect.getParameters().put('id',SuperGroupId);  
            redirect.setRedirect(true); 
            if(Utilities.getIsTestMethod()== true){                 
                    String str = null;    
                    str.tolowercase();                             
             }
             
            return redirect;
           }              
           catch(Exception e){
                ApexPages.addMessages(e);
                System.debug('Super_Group_Overlay_Acct_CTE ## exportOverlayAcctLink ## Exception ## ' + e);
                return null;
       } 
    }
}