objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer recordtype for C360</description>
        <label>Customer</label>
    </recordTypes>
</CustomObject>

objects/CEE__c.object
<CustomObject>
    <fields>
        <fullName>Jiffle_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>JiffleNow Re-design: To create relationship of Events with CEE-Lookup Relationship</description>
        <label>Global Event</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Jiffle_Event__c.Event_Start_Date__c</field>
                <operation>greaterOrEqual</operation>
                <valueField>Jiffle_Event__c.Jiffle_Today_Date__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Jiffle_Event__c</referenceTo>
        <relationshipLabel>Customer Engagements &amp; Events</relationshipLabel>
        <relationshipName>Customer_Engagements_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Engagements &amp; Events</relationshipLabel>
        <relationshipName>Primary_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <description>Briefing Request Status and it is related to CPOC lab request.</description>
        <inlineHelpText>Current stage of an Engagement Request</inlineHelpText>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Returned (all resources released)</fullName>
                </value>
                <value>
                    <fullName>Cancelled (all resources released)</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Saved, not Submitted</fullName>
                </value>
                <value>
                    <fullName>Assigned to PM</fullName>
                </value>
                <value>
                    <fullName>Submitted by Requester</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Lab Redirect</fullName>
                </value>
                <value>
                    <fullName>Returned by Scheduler</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>This object will store summary level briefing information from CEE. This Object is created to Integrate CEE Applicaiton data with Salesforce.com. It allows users to link CEE Briefings with Accounts in Salesforce.com.</description>
    <label>Customer Engagements &amp; Events</label>
    <nameField>
        <displayFormat>CEE-{000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Engagements &amp; Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/GlobalTriggerManagement__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>GlobalTriggerManagement</label>
</CustomObject>

objects/Jiffle_Agenda_Item__c.object
<CustomObject>
    <fields>
        <fullName>Jiffle_Event__c</fullName>
        <label>Jiffle Event</label>
        <referenceTo>Jiffle_Event__c</referenceTo>
        <relationshipLabel>JiffleNow Agenda Items</relationshipLabel>
        <relationshipName>Jiffle_Agenda_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>JiffleNow Agenda Item</label>
    <nameField>
        <label>Jiffle Agenda Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>JiffleNow Agenda Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Jiffle_Attendee_Invitee__c.object
<CustomObject>
    <fields>
        <fullName>Attendee_Email__c</fullName>
        <label>Attendee Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Attendee_First_Name__c</fullName>
        <label>Attendee First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attendee_Last_Name__c</fullName>
        <label>Attendee Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contact Sync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <label>Contact Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Engagements_Events__c</fullName>
        <label>Customer Engagements &amp; Events</label>
        <referenceTo>CEE__c</referenceTo>
        <relationshipName>Jiffle_Attendees_Invitees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Jiffle_Session_Meeting__c</fullName>
        <label>Salesforce Meeting ID</label>
        <referenceTo>Jiffle_Meeting_Session__c</referenceTo>
        <relationshipName>CEE_Jiffle_Invites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Meeting_Attended__c</fullName>
        <label>Meeting Attended</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Don't Know</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Jiffle_Attendees_Invitees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requestor_Email__c</fullName>
        <label>Requestor Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>JiffleNow Attendee</label>
    <nameField>
        <displayFormat>JF-{0000000}</displayFormat>
        <label>JiffleNow Invite Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JiffleNow Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Jiffle_Event__c.object
<CustomObject>
    <label>Global Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Global Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Jiffle_Meeting_Session__c.object
<CustomObject>
    <fields>
        <fullName>Jiffle_Agenda_Item__c</fullName>
        <label>JiffleNow Agenda Item</label>
        <referenceTo>Jiffle_Agenda_Item__c</referenceTo>
        <relationshipLabel>JiffleNow Meeting</relationshipLabel>
        <relationshipName>Jiffle_Meetings_Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <description>Briefing Request Status</description>
        <inlineHelpText>Current stage of a briefing request</inlineHelpText>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>JiffleNow Meeting</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Salesforce Meeting Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JiffleNow Meeting</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/NGCC_Mapping_Object__c.object
<CustomObject>
    <label>CC Mapping Object</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NGCC Mapping Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ObjectRecordTypeIds__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is used to store the record type ids of account and contact objects.</description>
    <label>Object Record Type Ids</label>
</CustomObject>

objects/Org_Constant_CS__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Org Constant CS</label>
</CustomObject>

objects/Org_Constants__c.object
<CustomObject>
    <label>Org Constant</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Org Constants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/JiffleNowAttendee_Reconcile_Test.cls
/************************************************************************************************************************************
Name    : JiffleNowAttendee_Reconcile_Test
Author  : Mukesh Srivastava
Purpose : This Test class is validate New Attendee Creation and Sync as Contact,View my Meetings,Reconcile scenario
Created Date: 5/25/2015
Modification History: 

*************************************************************************************************************************************/
@isTest
public class JiffleNowAttendee_Reconcile_Test {
    //Setting Up data for This test class
    @testSetup static void setupTestData() {
        CEE_TestUtility.loadCustomSettings();
       // List < sObject > cOrgCS = Test.loadData(Org_Constant_CS__c.sObjectType, 'GlobalTestOrgConstantCS');
        List < sObject > cOrgConstantObject = Test.loadData(Org_Constants__c.sObjectType, 'OrgConstants');
       // List < sObject > cObjRecId = Test.loadData(ObjectRecordTypeIds__c.sObjectType, 'GlobalTestObjectRecordTypeIds');
        List < sObject > cMappings = Test.loadData(NGCC_Mapping_Object__c.sObjectType, 'GlobalTestMapping');
        List < sObject > cAccounts = Test.loadData(Account.sObjectType, 'GlobalTestAccounts');
        List < sObject > cEvents = Test.loadData(Jiffle_Event__c.sObjectType, 'GlobalTestEvents');
        GlobalTriggerManagement__c gm = new GlobalTriggerManagement__c();
        gm.Name = 'JiffleR1_CEE';
        gm.Active__c = false;
        insert gm;
        
        List < Account > alist = (List < Account > ) cAccounts;
        List < Jiffle_Event__c > evtlist = (List < Jiffle_Event__c > ) cEvents;
        
        Id idOfJiffleRec = Schema.SObjectType.CEE__c.getRecordTypeInfosByName().get('Jifflenow (Event, Tradeshow, Conference)').getRecordTypeId();

        //Creating New CEE
        CEE__c ceeObj = new CEE__c();
        ceeObj.Primary_Account__c = alist[0].Id;
        ceeObj.Jiffle_Event__c = evtlist[0].Id;
        ceeObj.RecordTypeId = idOfJiffleRec;
        insert ceeObj;
        
        //Creating New Agenda
        Jiffle_Agenda_Item__c jfAgenda = new Jiffle_Agenda_Item__c();
        jfAgenda.Name = 'Agenda';
        jfAgenda.Jiffle_Event__c = evtlist[0].Id;
        insert jfAgenda;

        //Creating New Jiffle Meeting
        Jiffle_Meeting_Session__c jfMeeting = new Jiffle_Meeting_Session__c();
        jfMeeting.Jiffle_Agenda_Item__c = jfAgenda.Id;
        jfMeeting.Request_Status__c = 'Active';
        insert jfMeeting;

        //Creating Attendees
        List < Jiffle_Attendee_Invitee__c > jfAttendee = new List < Jiffle_Attendee_Invitee__c > ();
        for (Integer i = 0; i < 20; i++) {
            Jiffle_Attendee_Invitee__c jfAtt = new Jiffle_Attendee_Invitee__c();
            jfAtt.Attendee_First_Name__c = 'FirstAtt' + i;
            jfAtt.Attendee_Last_Name__c = 'LastAtt' + i;
            jfAtt.Attendee_Email__c = 'LastAtt@test.com' + i;
            jfAtt.Primary_Account__c = alist[0].Id;
            jfAtt.Jiffle_Session_Meeting__c = jfMeeting.Id;
            jfAtt.Customer_Engagements_Events__c = ceeObj.Id;
            jfAtt.Requestor_Email__c = userinfo.getUserEmail();
            jfAtt.Contact_Sync__c = false;
            jfAtt.Title__c = 'CFO' + i;
            if (i == 10) {
                jfAtt.Meeting_Attended__c = 'No';
            }
            jfAttendee.add(jfAtt);
        }

        insert jfAttendee;

    }

    //@ Testing New CEE Creation and Ensuring Region is Populated
    static testMethod void testNewAttendeesCreation() {
        Jiffle_Meeting_Session__c jfMS = [Select Id from Jiffle_Meeting_Session__c Limit 1];
        CEE__c jfCEE = [Select Id from CEE__c Limit 1];
        Account acc = [Select Id from Account Limit 1];

        List < Jiffle_Attendee_Invitee__c > jfAttendee = new List < Jiffle_Attendee_Invitee__c > ();

        for (Integer i = 50; i < 80; i++) {
            Jiffle_Attendee_Invitee__c jfAtt = new Jiffle_Attendee_Invitee__c();
            jfAtt.Attendee_First_Name__c = 'FirstAtt' + i;
            jfAtt.Attendee_Last_Name__c = 'LastAtt' + i;
            jfAtt.Attendee_Email__c = 'LastAtt@test.com' + i;
            jfAtt.Primary_Account__c = acc.Id;
            jfAtt.Jiffle_Session_Meeting__c = jfMS.Id;
            jfAtt.Customer_Engagements_Events__c = jfCEE.Id;
            jfAtt.Requestor_Email__c = userinfo.getUserEmail();
            jfAtt.Contact_Sync__c = True;
            jfAtt.Contact_Type__c = 'Customer';
            jfAtt.Title__c = 'CEO' + i;
            jfAttendee.add(jfAtt);
        }

        Test.startTest();
            insert jfAttendee;
        Test.stopTest();
    }

    //@ Testing when No record was selected from List
    static testMethod void testReconcilationNoSelection() {
        List < Jiffle_Attendee_Invitee__c > lstJSAtt = new List < Jiffle_Attendee_Invitee__c > ();
        Test.startTest();
            Test.setCurrentPageReference(New PageReference('Page.JiffleNowReconcile'));
            ApexPages.StandardSetcontroller stdSetCtlAttendee = New ApexPages.StandardSetController(lstJSAtt);
            System.currentPageReference().getParameters().put('retURL', '/home/home.jsp');
            System.currentPageReference().getParameters().put('action', 'Yes');
            stdSetCtlAttendee.setSelected(lstJSAtt);
            JiffleNowReconcile_CTE setContAtt = new JiffleNowReconcile_CTE(stdSetCtlAttendee);
            setContAtt.cmdDone();
        Test.stopTest();
    }

    //@ Testing when All record was selected from List from Reconcile
    static testMethod void testReconcilationAllSelection() {
        List < Jiffle_Attendee_Invitee__c > lstJSAtt = [Select Id from Jiffle_Attendee_Invitee__c LIMIT 30];
        Test.startTest();
            Test.setCurrentPageReference(New PageReference('Page.JiffleNowReconcile'));
            ApexPages.StandardSetcontroller stdSetCtlAttendee = New ApexPages.StandardSetController(lstJSAtt);
            System.currentPageReference().getParameters().put('retURL', '/home/home.jsp');
            System.currentPageReference().getParameters().put('action', 'Yes');
            stdSetCtlAttendee.setSelected(lstJSAtt);
            JiffleNowReconcile_CTE setContAtt = new JiffleNowReconcile_CTE(stdSetCtlAttendee);
            setContAtt.cmdSubmit();
            setContAtt.cmdDone();
        Test.stopTest();
    }

    //@ Testing to view my Meetings
    static testMethod void testMyMeetingViewer() {
        CEE__c ceeObj = [Select Jiffle_Event__c from CEE__c LIMIT 1];
        Jiffle_Event__c jfEvent = [Select Id from Jiffle_Event__c where Id = : ceeObj.Jiffle_Event__c Limit 1];
        Test.startTest();
            Test.setCurrentPageReference(New PageReference('Page.JiffleNowEventsMeetingViewer'));
            ApexPages.StandardController stdCtlEvent = New ApexPages.StandardController(jfEvent);
            JiffleNowMeetingViewer_CTE contAtt = new JiffleNowMeetingViewer_CTE(stdCtlEvent);
            contAtt.getSessions();
        Test.stopTest();
    }
    
    //@ Testing to Cancelled or Deleted Meeting
    static testMethod void testMeetingCancelledDeleted() {
        Jiffle_Meeting_Session__c  jmObj = [Select Id,Request_Status__c from Jiffle_Meeting_Session__c LIMIT 1];
        jmObj.Request_Status__c = 'Deleted';
        Test.startTest();
            update jmObj;
        Test.stopTest();
    }
}