objects/Account.object
<CustomObject>
    <fields>
        <fullName>CRName__c</fullName>
        <label>CR Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
                <value>
                    <fullName>BRAZIL</fullName>
                </value>
                <value>
                    <fullName>UNITED STATES</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Theatre__c</fullName>
        <description>Describes which Cisco geographical region the account us managed by.</description>
        <label>Theatre</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>APJ</fullName>
                </value>
                <value>
                    <fullName>EMEAR</fullName>
                </value>
                <value>
                    <fullName>Global Service Provider</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>EndUser</fullName>
        <active>true</active>
        <description>Existing or Prospective Customer Account</description>
        <label>End-User</label>
    </recordTypes>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Lead_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>NGCC Phase1:Prospect associated to existing SFDC Contacts</description>
        <label>Sales Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Leads (Lead Contact)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MODS_Contact__c</fullName>
        <description>NGCC Phase1:External Reference of MODS and unique identifier for MODS prospects</description>
        <label>MODS Person Party ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ObjectRecordTypeIds__c.object
<CustomObject>
    <fields>
        <fullName>Account_End_User_RecordTypeId__c</fullName>
        <description>This is the  Id for the End User Account record type.</description>
        <label>Account End User RecordTypeId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Manual_EndUser_RecordTypeId__c</fullName>
        <description>This is the id of the Contact Manual End User record type.</description>
        <label>Contact Manual EndUser RecordTypeId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>eLeadsRecordTypeId__c</fullName>
        <description>This field stores the id of the eLeads record type id.</description>
        <label>eLeadsRecordTypeId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is used to store the record type ids of account and contact objects.</description>
    <label>Object Record Type Ids</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Additional_User_Permissions__c</fullName>
        <description>Allows permission for additional functionality which are based on User and not by profile.
1)AccountCreateByTerritory: New SBC functionality which allows SBC based on Geo Rules
2)Enable EndUser ACCTCreation : Can Create End-User accounts
3)Enable Lead Conversion : Can Convert leads
4)Enable PDR ACCTCreation : Can Create End-User Account during CCW deal conversion
5)Request Resource : Allows AMs to access SE functionality
6)SE User : Allows SEs to access SE Functionality
7)2028 Visibility:Users that will be refreshed by 2028 black box process
8)NBM Approver : User can set status field of NBM records to 'Screen 3' Approval status</description>
        <label>Additional User Permissions</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>2028 Visibility</fullName>
                </value>
                <value>
                    <fullName>AccountCreateByTerritory</fullName>
                </value>
                <value>
                    <fullName>AcquisitionUser</fullName>
                </value>
                <value>
                    <fullName>Activate Sales Account View</fullName>
                </value>
                <value>
                    <fullName>CCE Enabled</fullName>
                </value>
                <value>
                    <fullName>DSEC360</fullName>
                </value>
                <value>
                    <fullName>DSEC360SAV</fullName>
                </value>
                <value>
                    <fullName>DSEContactIntelligence</fullName>
                </value>
                <value>
                    <fullName>DSECRinSFDC</fullName>
                </value>
                <value>
                    <fullName>DSEFA</fullName>
                </value>
                <value>
                    <fullName>DSEGA</fullName>
                </value>
                <value>
                    <fullName>DSENotification</fullName>
                </value>
                <value>
                    <fullName>DSESWSS</fullName>
                </value>
                <value>
                    <fullName>DSETAC</fullName>
                </value>
                <value>
                    <fullName>Einstein Opportunities</fullName>
                </value>
                <value>
                    <fullName>Enable_ePSS</fullName>
                </value>
                <value>
                    <fullName>Enable_VSS</fullName>
                </value>
                <value>
                    <fullName>Enable EndUser ACCTCreation</fullName>
                </value>
                <value>
                    <fullName>Enable Lead Conversion</fullName>
                </value>
                <value>
                    <fullName>Enable PDR ACCTCreation</fullName>
                </value>
                <value>
                    <fullName>Enable Target Prospect Creation</fullName>
                </value>
                <value>
                    <fullName>GSPO_BDM</fullName>
                </value>
                <value>
                    <fullName>GSSO HD Forecast User</fullName>
                </value>
                <value>
                    <fullName>MCP Prospect Engage</fullName>
                </value>
                <value>
                    <fullName>MCP Prospect Profiler</fullName>
                </value>
                <value>
                    <fullName>NBM Approver</fullName>
                </value>
                <value>
                    <fullName>NextGen Forecasting Pilot User</fullName>
                </value>
                <value>
                    <fullName>QIJanACVPilotUser</fullName>
                </value>
                <value>
                    <fullName>RAE SEP Enabled</fullName>
                </value>
                <value>
                    <fullName>Request Resource</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Marketing_Call_Center__c</fullName>
        <label>Marketing Call Center</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Convergys Manila - Global</fullName>
                </value>
                <value>
                    <fullName>Convergys Manila - ASIA</fullName>
                </value>
                <value>
                    <fullName>Convergys Suzhou China</fullName>
                </value>
                <value>
                    <fullName>Sellbytel Kuala Lumpur</fullName>
                </value>
                <value>
                    <fullName>Concentrix Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Sellbytel Korea</fullName>
                </value>
                <value>
                    <fullName>Inhouse Korea</fullName>
                </value>
                <value>
                    <fullName>Inhouse Japan</fullName>
                </value>
                <value>
                    <fullName>Sellbytel Sydney Australia</fullName>
                </value>
                <value>
                    <fullName>Inhouse Indonesia</fullName>
                </value>
                <value>
                    <fullName>Convergys India</fullName>
                </value>
                <value>
                    <fullName>Concentrix Debrecen Hungary</fullName>
                </value>
                <value>
                    <fullName>Concentrix Belfast Northern Ireland</fullName>
                </value>
                <value>
                    <fullName>Raya Cairo Egypt</fullName>
                </value>
                <value>
                    <fullName>Sellbytel Moscow Russia</fullName>
                </value>
                <value>
                    <fullName>Sellbytel Lisbon Portugal</fullName>
                </value>
                <value>
                    <fullName>Alea Canada</fullName>
                </value>
                <value>
                    <fullName>eCoast New Hampshire</fullName>
                </value>
                <value>
                    <fullName>Cisco RTP</fullName>
                </value>
                <value>
                    <fullName>Convergys Appleton WI</fullName>
                </value>
                <value>
                    <fullName>Convergys Newcastle UK</fullName>
                </value>
                <value>
                    <fullName>MRP</fullName>
                </value>
                <value>
                    <fullName>Concentrix Sofia Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Raya Warsaw Poland</fullName>
                </value>
                <value>
                    <fullName>WebEx IS</fullName>
                </value>
                <value>
                    <fullName>DCR EMEAR</fullName>
                </value>
                <value>
                    <fullName>DCR Brazil</fullName>
                </value>
                <value>
                    <fullName>DCR US</fullName>
                </value>
                <value>
                    <fullName>GVS Nashville</fullName>
                </value>
                <value>
                    <fullName>N3 Atlanta</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Theatre__c</fullName>
        <inlineHelpText>Please contact GSTS Support to Edit this field</inlineHelpText>
        <label>Theater</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Americas-Canada</fullName>
                </value>
                <value>
                    <fullName>Americas-Global Enterprise Segment</fullName>
                </value>
                <value>
                    <fullName>Americas-LATAM</fullName>
                </value>
                <value>
                    <fullName>Americas-US Commercial</fullName>
                </value>
                <value>
                    <fullName>Americas-US Public Sector</fullName>
                </value>
                <value>
                    <fullName>APJC-APAC</fullName>
                </value>
                <value>
                    <fullName>APJC-Greater China</fullName>
                </value>
                <value>
                    <fullName>APJC-Japan</fullName>
                </value>
                <value>
                    <fullName>EMEAR</fullName>
                </value>
                <value>
                    <fullName>Global Service Provider</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/NGCC_LeadScreenMashup_Test.cls
@isTest(SeeAllData = true)
public class NGCC_LeadScreenMashup_Test{
    
    private static testMethod void MarketingActivityTest(){
        String CALL_NOTES = 'CALL_NOTES';
        String CALL_STATUS = 'CALL_STATUS';
        String OFFER_ARCHITECTURE = 'CALL_STATUS';
        String OFFER_DESCRIPTION = 'CALL_STATUS';
        String ACTIVITY_TYPE = 'CALL_STATUS';
        String OFFER_TYPE_NAME = 'CALL_STATUS';
        String PERSON_PARTY_ID = 'CALL_STATUS';
        String OFFER_NAME = 'CALL_STATUS';
        String ACTIVITY_DATE = '01-01-01';
        String ACTIVITY_DATE2 = '01-01-02';
        
        NGCC_LeadScreenMashupCTL.MarketingActivity mark = new NGCC_LeadScreenMashupCTL.MarketingActivity (CALL_NOTES, CALL_STATUS, OFFER_ARCHITECTURE, 
                                                          OFFER_DESCRIPTION,ACTIVITY_TYPE, OFFER_TYPE_NAME, PERSON_PARTY_ID, OFFER_NAME,ACTIVITY_DATE);
    
        NGCC_LeadScreenMashupCTL.MarketingActivity mark2 = new NGCC_LeadScreenMashupCTL.MarketingActivity (CALL_NOTES, CALL_STATUS, OFFER_ARCHITECTURE, 
                                                          OFFER_DESCRIPTION,ACTIVITY_TYPE, OFFER_TYPE_NAME, PERSON_PARTY_ID, OFFER_NAME,ACTIVITY_DATE2);

        mark.compareTo(mark2);
        mark2.compareTo(mark);
        mark.compareTo(mark);
    }
    
    private static testMethod void MODSParseTest(){
        PageReference current = ApexPages.currentPage();
        Test.setCurrentPage(current);
        current.getParameters().put('node', '{"STATUS":"SUCCESS","MESSAGE":"1 Activities(s) found","TOTAL_ACTIVITIES":[{"Marketing":"1"}],"ACTIVITIES":[{"Marketing":[{"CALL_NOTES":"","TREATMENT_NAME":"","CALL_STATUS":"","OFFER_ARCHITECTURE":"SP Routing","OFFER_DESCRIPTION":"CN_CABLE SUMMIT EVENT","ACTIVITY_TYPE":"ATTENDED EVENT IN PERSON","OFFER_TYPE_NAME":"LIVE EVENT - CISCO","OFFER_NAME":" FY14 CN_Cable Summit Event","ACTIVITY_DATE":"12/6/2013"}]}]}');
        Lead a = new Lead();
       
        ApexPages.StandardController controller = new ApexPages.StandardController(a);   
        NGCC_LeadScreenMashupCTL searcher = new NGCC_LeadScreenMashupCTL(controller);
        searcher.getMODSData();
    }
    
    public static testMethod void NGCC_LeadScreenMashup_Lead_Test() {
        
        ObjectRecordTypeIds__c orgConstant = ObjectRecordTypeIds__c.getInstance(); 
        Id endCustAcc = orgConstant.Account_End_User_RecordTypeId__c;
        Id endCustCon = orgConstant.Contact_Manual_EndUser_RecordTypeId__c;
        Id eLeadRecType = orgConstant.eLeadsRecordTypeId__c;
        
        
        Profile p = [SELECT Id FROM Profile WHERE Name Like '%Enterprise%'
            Limit 1
        ];
        
        
        User uAM = new User(Alias = 'newUser', Email = 'newuserSM@cisco.com.reg',
            EmailEncodingKey = 'UTF-8', LastName = 'Testing', LanguageLocaleKey = 'en_US',Additional_User_Permissions__c='Enable EndUser ACCTCreation',
            LocaleSidKey = 'en_US', ProfileId = p.Id,Marketing_Call_Center__c = 'Alea Canada',
            TimeZoneSidKey = 'America/Los_Angeles', UserName = 'newuserSM@cisco.com.reg', Theatre__c = 'Americas-US Commercial');
        System.runAs(uAM) {
             Account a = new Account(name='Test End-User Account',CRName__c ='Test End-User Account',RECORDTYPEID=endCustAcc,Country__c='UNITED STATES');
             insert a;
             
             contact c = new contact(firstName='Test',LastName ='EndCustomer', RECORDTYPEID=endCustCon,email='testpa@test.com.test',accountId=a.id);
             insert c;
             
             Lead l = NGCC_CallScript_Data_Test.testLead();
             Lead l2 = NGCC_CallScript_Data_Test.testLead();
             l.Lead_Contact__c = c.Id; 
             l2.Lead_Contact__c = c.Id;
             l2.RecordTypeId = eLeadRecType;
             l2.Status = 'Marketing Qualified';
             l.MODS_Contact__c = 123456; 
             l2.MODS_Contact__c = 123456;           
             update l;
             update l2;
            
             
             l.Lead_Contact__c = NULL;
             update l;
             
             l.Lead_Contact__c = c.Id;             
             update l;
             
              Test.setCurrentPageReference(New PageReference('Page.NGCC_LeadScreenMashup'));
              //System.currentPageReference().getParameters().put('id', l.Id);
              ApexPages.Standardcontroller stdCtlCallScript = New ApexPages.StandardController(l);
              NGCC_LeadScreenMashupCTL ccLeadMashup = new NGCC_LeadScreenMashupCTL(stdCtlCallScript);
              
              
        }
    }
}