objects/Account.object
<CustomObject>
    <fields>
        <fullName>Theatre__c</fullName>
        <description>Describes which Cisco geographical region the account us managed by.</description>
        <label>Theatre</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>APJ</fullName>
                </value>
                <value>
                    <fullName>EMEAR</fullName>
                </value>
                <value>
                    <fullName>Global Service Provider</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Assigned_Partner__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Partner Account assigned to this target account.</description>
        <label>Assigned Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Assigned_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Target Account to whom partners are being assigned</description>
        <label>Customer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Assigned_Partner_Customer_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>Partner assignments of End User Accounts are stored in this object.</description>
    <label>zzTarget Prospect</label>
    <nameField>
        <label>Target Prospect Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Target Prospects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Additional_User_Permissions__c</fullName>
        <description>Allows permission for additional functionality which are based on User and not by profile.
1)AccountCreateByTerritory: New SBC functionality which allows SBC based on Geo Rules
2)Enable EndUser ACCTCreation : Can Create End-User accounts
3)Enable Lead Conversion : Can Convert leads
4)Enable PDR ACCTCreation : Can Create End-User Account during CCW deal conversion
5)Request Resource : Allows AMs to access SE functionality
6)SE User : Allows SEs to access SE Functionality
7)2028 Visibility:Users that will be refreshed by 2028 black box process
8)NBM Approver : User can set status field of NBM records to 'Screen 3' Approval status</description>
        <label>Additional User Permissions</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>2028 Visibility</fullName>
                </value>
                <value>
                    <fullName>AccountCreateByTerritory</fullName>
                </value>
                <value>
                    <fullName>AcquisitionUser</fullName>
                </value>
                <value>
                    <fullName>Activate Sales Account View</fullName>
                </value>
                <value>
                    <fullName>CCE Enabled</fullName>
                </value>
                <value>
                    <fullName>DSEC360</fullName>
                </value>
                <value>
                    <fullName>DSEC360SAV</fullName>
                </value>
                <value>
                    <fullName>DSEContactIntelligence</fullName>
                </value>
                <value>
                    <fullName>DSECRinSFDC</fullName>
                </value>
                <value>
                    <fullName>DSEFA</fullName>
                </value>
                <value>
                    <fullName>DSEGA</fullName>
                </value>
                <value>
                    <fullName>DSENotification</fullName>
                </value>
                <value>
                    <fullName>DSESWSS</fullName>
                </value>
                <value>
                    <fullName>DSETAC</fullName>
                </value>
                <value>
                    <fullName>Einstein Opportunities</fullName>
                </value>
                <value>
                    <fullName>Enable_ePSS</fullName>
                </value>
                <value>
                    <fullName>Enable_VSS</fullName>
                </value>
                <value>
                    <fullName>Enable EndUser ACCTCreation</fullName>
                </value>
                <value>
                    <fullName>Enable Lead Conversion</fullName>
                </value>
                <value>
                    <fullName>Enable PDR ACCTCreation</fullName>
                </value>
                <value>
                    <fullName>Enable Target Prospect Creation</fullName>
                </value>
                <value>
                    <fullName>GSPO_BDM</fullName>
                </value>
                <value>
                    <fullName>GSSO HD Forecast User</fullName>
                </value>
                <value>
                    <fullName>MCP Prospect Engage</fullName>
                </value>
                <value>
                    <fullName>MCP Prospect Profiler</fullName>
                </value>
                <value>
                    <fullName>NBM Approver</fullName>
                </value>
                <value>
                    <fullName>NextGen Forecasting Pilot User</fullName>
                </value>
                <value>
                    <fullName>QIJanACVPilotUser</fullName>
                </value>
                <value>
                    <fullName>RAE SEP Enabled</fullName>
                </value>
                <value>
                    <fullName>Request Resource</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Theatre__c</fullName>
        <inlineHelpText>Please contact GSTS Support to Edit this field</inlineHelpText>
        <label>Theater</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Americas-Canada</fullName>
                </value>
                <value>
                    <fullName>Americas-Global Enterprise Segment</fullName>
                </value>
                <value>
                    <fullName>Americas-LATAM</fullName>
                </value>
                <value>
                    <fullName>Americas-US Commercial</fullName>
                </value>
                <value>
                    <fullName>Americas-US Public Sector</fullName>
                </value>
                <value>
                    <fullName>APJC-APAC</fullName>
                </value>
                <value>
                    <fullName>APJC-Greater China</fullName>
                </value>
                <value>
                    <fullName>APJC-Japan</fullName>
                </value>
                <value>
                    <fullName>EMEAR</fullName>
                </value>
                <value>
                    <fullName>Global Service Provider</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/P360_NewTargetProsController_CTE_v1_Test.cls
//** This Test Class is used to TP Creation from Account Page**/
//** Author:     Mukesh JSC Team
//** Date:       01/16/2013


@isTest(SeeAllData=True)
public class P360_NewTargetProsController_CTE_v1_Test{

    public static testMethod void testP360_NewTargetProsController_CTE_v1_PositiveTest() 
    {
        
        
        user u = new user(firstName='Test',LastName ='AM', USERNAME='testam@cisco.com.sales.test',email='testam@cisco.com.test',ALIAS='testam',COMMUNITYNICKNAME='testam',ISACTIVE=True,
                            TIMEZONESIDKEY='America/Los_Angeles',PROFILEID = '00e30000000qhPXAAY',LANGUAGELOCALEKEY ='en_US',THEATRE__C='APJC-APAC',
                            LOCALESIDKEY ='en_US',EMAILENCODINGKEY='UTF-8');
        
             
        insert u;
       
        u.Additional_User_Permissions__c='Enable Target Prospect Creation';
        update u;
        Test.startTest();
                
        Assigned_Partner__c TPPos = GenericStaticTestData.gettestTargetProspectRecord();       

        System.RunAs(u){

        /////////Positive Test /////////////////////////
        Test.setCurrentPageReference(New PageReference('Page.P360_NewTargetProspectPagev1'));
        System.currentPageReference().getParameters().put('CF00N80000004wXYC', 'Testing');
        ApexPages.Standardcontroller stdCtlTPCreatePos = New ApexPages.StandardController(TPPos);
        
        P360_NewTargetProsController_CTE_v1 contTPCreatePos=new P360_NewTargetProsController_CTE_v1(stdCtlTPCreatePos);
        system.debug('TP Account'+TPPos.Customer_Account__c);

        contTPCreatePos.getCreateNewValidity();
        contTPCreatePos.accountPageRedirect();
        
        /////////Negative Test /////////////////////////
        Test.setCurrentPageReference(New PageReference('Page.P360_NewTargetProspectPagev1'));
        
        P360_NewTargetProsController_CTE_v1 contTPCreateNeg=new P360_NewTargetProsController_CTE_v1();
        
        contTPCreateNeg.getCreateNewValidity();
        contTPCreateNeg.accountPageRedirect();
        contTPCreateNeg.PageRedirect();
                
        }
        
       Test.stopTest();
    }
    
    public static testMethod void testP360_NewTargetProsController_CTE_v1_NegativeTest() 
    {
        
        Assigned_Partner__c TPPos = GenericStaticTestData.gettestTargetProspectRecord();
        
        user u = new user(firstName='Test',LastName ='AM', USERNAME='testam@cisco.com.sales.test',email='testam@cisco.com.test',ALIAS='testam',COMMUNITYNICKNAME='testam',ISACTIVE=True,
                            TIMEZONESIDKEY='America/Los_Angeles',PROFILEID = '00e30000000qhPXAAY',LANGUAGELOCALEKEY ='en_US',THEATRE__C='APJC-APAC',
                            LOCALESIDKEY ='en_US',EMAILENCODINGKEY='UTF-8');
        
             
        insert u;
       
        
        Test.startTest();
        System.RunAs(u){
        
        /////////Positive Test /////////////////////////
        Test.setCurrentPageReference(New PageReference('Page.P360_NewTargetProspectPagev1'));
        ApexPages.Standardcontroller stdCtlTPCreatePos = New ApexPages.StandardController(TPPos);
        
        P360_NewTargetProsController_CTE_v1 contTPCreatePos=new P360_NewTargetProsController_CTE_v1(stdCtlTPCreatePos);
        
        contTPCreatePos.getCreateNewValidity();
        contTPCreatePos.accountPageRedirect();
        /*
        /////////Negative Test /////////////////////////
        Test.setCurrentPageReference(New PageReference('Page.P360_NewTargetProspectPagev1'));
        
        P360_NewTargetProsController_CTE_v1 contTPCreateNeg=new P360_NewTargetProsController_CTE_v1();
        
        contTPCreateNeg.getCreateNewValidity();
        contTPCreateNeg.accountPageRedirect();
        contTPCreateNeg.PageRedirect();
          */      
        }
        
       Test.stopTest();
    }
    
    
}