objects/Account.object
<CustomObject>
    <fields>
        <fullName>LineofBusiness__c</fullName>
        <label>Line of Business</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Commercial Named</fullName>
                </value>
                <value>
                    <fullName>Commercial Non-named</fullName>
                </value>
                <value>
                    <fullName>Enterprise</fullName>
                </value>
                <value>
                    <fullName>Inside Sales</fullName>
                </value>
                <value>
                    <fullName>Public Sector</fullName>
                </value>
                <value>
                    <fullName>Service Provider</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Locations_Number__c</fullName>
        <description>Count of number of partner sites that rolls up to same BE GEO ID</description>
        <label># Partner Locations</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Theatre__c</fullName>
        <description>Describes which Cisco geographical region the account us managed by.</description>
        <label>Theatre</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>APJ</fullName>
                </value>
                <value>
                    <fullName>EMEAR</fullName>
                </value>
                <value>
                    <fullName>Global Service Provider</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VMTOP__c</fullName>
        <description>Vertical Market (Top) from CR</description>
        <label>Vertical Market (Top)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Business_Entity__c</fullName>
        <description>Business Entity associated with the technology.</description>
        <label>Business Entity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mix__c</fullName>
        <label>Mix %</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product_Family_Ref__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote Integration: Individual Product Family associated to Line Items and mapped with product family Master list</description>
        <label>Product Family ID</label>
        <referenceTo>Product_Family__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <description>Quote Integration: Individual Product Family associated to Line Items</description>
        <label>Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Business_Entity__c</fullName>
        <description>Business Entity associated with the technology.</description>
        <label>Business Entity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Analytics</fullName>
                </value>
                <value>
                    <fullName>AS-S</fullName>
                </value>
                <value>
                    <fullName>AS-T</fullName>
                </value>
                <value>
                    <fullName>Collaboration</fullName>
                </value>
                <value>
                    <fullName>Computing Systems</fullName>
                </value>
                <value>
                    <fullName>Data Center Switching</fullName>
                </value>
                <value>
                    <fullName>Enterprise Routing</fullName>
                </value>
                <value>
                    <fullName>Enterprise Switching</fullName>
                </value>
                <value>
                    <fullName>Industrial IOT Networking</fullName>
                </value>
                <value>
                    <fullName>IOT</fullName>
                </value>
                <value>
                    <fullName>Meraki</fullName>
                </value>
                <value>
                    <fullName>Mobility</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Security</fullName>
                </value>
                <value>
                    <fullName>Service Provider Routing</fullName>
                </value>
                <value>
                    <fullName>SP Video Infrastructure</fullName>
                </value>
                <value>
                    <fullName>SP Video Software and Solutions</fullName>
                </value>
                <value>
                    <fullName>TS-S</fullName>
                </value>
                <value>
                    <fullName>UNKNOWN</fullName>
                </value>
                <value>
                    <fullName>Wireless</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Business_Entity__c</fullName>
        <description>Quote Integration: Contain Sub Business Entity Description from EDW - SUB_BUSINESS_ENTITY_DESCR</description>
        <label>Sub Business Entity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product_Family__c.object
<CustomObject>
    <description>Quote Integration: Master List of Product Families integrated via Informatica</description>
    <label>Product Family</label>
    <nameField>
        <label>Product Family Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Theatre__c</fullName>
        <inlineHelpText>Please contact GSTS Support to Edit this field</inlineHelpText>
        <label>Theater</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Americas-Canada</fullName>
                </value>
                <value>
                    <fullName>Americas-Global Enterprise Segment</fullName>
                </value>
                <value>
                    <fullName>Americas-LATAM</fullName>
                </value>
                <value>
                    <fullName>Americas-US Commercial</fullName>
                </value>
                <value>
                    <fullName>Americas-US Public Sector</fullName>
                </value>
                <value>
                    <fullName>APJC-APAC</fullName>
                </value>
                <value>
                    <fullName>APJC-Greater China</fullName>
                </value>
                <value>
                    <fullName>APJC-Japan</fullName>
                </value>
                <value>
                    <fullName>EMEAR</fullName>
                </value>
                <value>
                    <fullName>Global Service Provider</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/customerWinJSON_test.cls
@istest(seeAlldata=true)
public class customerWinJSON_test{
    public static testmethod void getJsonStringmethod1(){
        Profile p = [SELECT Id FROM Profile WHERE Name='Cisco_ADMIN']; 
        User u = new User(Alias = 'standt', Email='standarduser1@cisco.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles',Theatre__c='APJC-APAC', UserName='standarduser1@cisco.com');
        System.runAs(u){
            CustomerWinJSON.reqPay r = new CustomerWinJSON.reqPay();
            CustomerWinJSON.should s = new CustomerWinJSON.should();      
            CustomerWinJSON.childOptyLine2 c = new CustomerWinJSON.childOptyLine2();
            
            
            String json = '{'+
                '                    \"title\": \"Collab Spotlight\",'+
                '                    \"url\": \"https://salesconnect.cisco.com/open.html?h=PAGE-501\",'+
                '                    \"date\": \"2009-11-15T14:12:12\",'+
                '                    \"lastmodified\": ['+
                '                        \"2018-12-05T00:00:00.000-0600\"'+
                '                    ],'+
                '                    \"bizent\": ['+
                '                        \"Collaboration\"'+
                '                    ],'+
                '                    \"category\": \"saleshub\"'+
                '                }';
            List<String> jsonLst = new List<String>();
            jsonLst.add(json);
            
            Account acc = new Account();
            acc.name = 'Test Acc';
            acc.VMTOP__c='test';
            acc.LineofBusiness__c='enterprise';
            acc.Theatre__c='americas';
            acc.partner_locations_number__c = 10;
            insert acc;
            
            opportunity opp = new opportunity();
            
            opp.name = 'Test Opp';
            opp.stagename = 'Prospecting';
            opp.CloseDate = system.today()+2;
            opp.Competitors__c='arista';
            insert opp;
            
            
            Product2 prod = new Product2(Name = 'Laptop X200', Business_Entity__c = 'meraki',Sub_Business_Entity__c='test',
                                         Family = 'Hardware');
            insert prod;
            Id pricebookId = Test.getStandardPricebookId();
            
            PricebookEntry standardPrice = new PricebookEntry(
                Pricebook2Id = pricebookId, Product2Id = prod.Id,
                UnitPrice = 10000, IsActive = true);
            insert standardPrice;
            
            // Create a custom price book
            Pricebook2 customPB = new Pricebook2(Name='Custom Pricebook', isActive=true);
            insert customPB;
            
            // 2. Insert a price book entry with a custom price.
            PricebookEntry customPrice = new PricebookEntry(
                Pricebook2Id = customPB.Id, Product2Id = prod.Id,
                UnitPrice = 12000, IsActive = true);
            insert customPrice;
            
            //OpportunityLineItem OPplineitem2 = new OpportunityLineItem (Quantity=2, Product2Id,PriceBookEntry.Product2.Business_Entity__c,PriceBookEntry.
            //Product2.Sub_Business_Entity__c,opportunity.Competitors__c,opportunity.Account.VMTOP__c,opportunity.
            // Account.LineofBusiness__c,opportunity.Account.Theatre__c from OpportunityLineItem where OpportunityId=:recordId and Mix__c!=0);
            List<OpportunityLineItem> oplitem=[Select Product2Id,PriceBookEntry.Product2.Business_Entity__c,PriceBookEntry.Product2.Sub_Business_Entity__c,
                                               opportunity.Competitors__c,opportunity.Account.VMTOP__c,opportunity.Account.LineofBusiness__c,opportunity.Account.Theatre__c,product_Family__C,Product_Family_Ref__r.name from 
                                               OpportunityLineItem where Mix__c!=0 and PriceBookEntry.Product2.Sub_Business_Entity__c!='' and Product_Family_Ref__c!=null limit 1];
            // List<OpportunityLineItem> oplitem = new List<OpportunityLineItem>();
            
            // oplitem .add(OPplineitem2);
            
            // insert oplitem;
            
            CustomerWinJSON.getJsonString(oplitem);
            CustomerWinJSON.getJsonString2(oplitem);
            CustomerWinJSON.getJsonString3(oplitem);
            CustomerWinJSON.getJsonString4(oplitem);
            CustomerWinJSON.getJsonString5(oplitem);
            CustomerWinJSON.getJsonString6(oplitem);
            CustomerWinJSON.getJsonString7(oplitem);
            CustomerWinJSON.getSalesPresentationJson(oplitem);
            
        }    
    }
}