objects/Account.object
<CustomObject>
    <fields>
        <fullName>AddressLine1_English__c</fullName>
        <description>used for non-english profiles</description>
        <label>Address Line 1 (English)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AddressLine1__c</fullName>
        <label>Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AddressLine2_English__c</fullName>
        <description>used for non-english profiles</description>
        <label>Address Line 2 (English)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AddressLine2__c</fullName>
        <label>Address Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSCID__c</fullName>
        <label>CSC ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSCSiteID__c</fullName>
        <description>Previously CSC Site ID</description>
        <externalId>true</externalId>
        <label>Party ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City_English__c</fullName>
        <description>used for non-english profiles</description>
        <label>City (English)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
                <value>
                    <fullName>BRAZIL</fullName>
                </value>
                <value>
                    <fullName>INDIA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State_Province_English__c</fullName>
        <description>non-English profiles</description>
        <label>State/Province (English)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State/Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Theatre__c</fullName>
        <description>Describes which Cisco geographical region the account us managed by.</description>
        <label>Theatre</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>APJ</fullName>
                </value>
                <value>
                    <fullName>EMEAR</fullName>
                </value>
                <value>
                    <fullName>Global Service Provider</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Channel</fullName>
        <active>true</active>
        <description>Registered Partner Account from PDB (Partner Database)</description>
        <label>Channel</label>
    </recordTypes>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer recordtype for C360</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>EndUser</fullName>
        <active>true</active>
        <description>Existing or Prospective Customer Account</description>
        <label>End-User</label>
    </recordTypes>
</CustomObject>

objects/ObjectRecordTypeIds__c.object
<CustomObject>
    <fields>
        <fullName>AccountChannelRecordTypeId__c</fullName>
        <description>This field stores the id of the channel account record type.</description>
        <label>Account Channel RecordTypeId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is used to store the record type ids of account and contact objects.</description>
    <label>Object Record Type Ids</label>
</CustomObject>

objects/Org_Constants__c.object
<CustomObject>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Prod_LT__c</fullName>
        <label>Prod LT</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>URL</fullName>
                    <default>true</default>
                    <label>URL</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>non_prod_value__c</fullName>
        <label>non prod value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>prod_value__c</fullName>
        <label>prod value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Org Constant</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Org Constants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Additional_User_Permissions__c</fullName>
        <description>Allows permission for additional functionality which are based on User and not by profile.
1)AccountCreateByTerritory: New SBC functionality which allows SBC based on Geo Rules
2)Enable EndUser ACCTCreation : Can Create End-User accounts
3)Enable Lead Conversion : Can Convert leads
4)Enable PDR ACCTCreation : Can Create End-User Account during CCW deal conversion
5)Request Resource : Allows AMs to access SE functionality
6)SE User : Allows SEs to access SE Functionality
7)2028 Visibility:Users that will be refreshed by 2028 black box process
8)NBM Approver : User can set status field of NBM records to 'Screen 3' Approval status</description>
        <label>Additional User Permissions</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>2028 Visibility</fullName>
                </value>
                <value>
                    <fullName>AccountCreateByTerritory</fullName>
                </value>
                <value>
                    <fullName>AcquisitionUser</fullName>
                </value>
                <value>
                    <fullName>Activate Sales Account View</fullName>
                </value>
                <value>
                    <fullName>CCE Enabled</fullName>
                </value>
                <value>
                    <fullName>DSEC360</fullName>
                </value>
                <value>
                    <fullName>DSEC360SAV</fullName>
                </value>
                <value>
                    <fullName>DSEContactIntelligence</fullName>
                </value>
                <value>
                    <fullName>DSECRinSFDC</fullName>
                </value>
                <value>
                    <fullName>DSEFA</fullName>
                </value>
                <value>
                    <fullName>DSEGA</fullName>
                </value>
                <value>
                    <fullName>DSENotification</fullName>
                </value>
                <value>
                    <fullName>DSESWSS</fullName>
                </value>
                <value>
                    <fullName>DSETAC</fullName>
                </value>
                <value>
                    <fullName>Einstein Opportunities</fullName>
                </value>
                <value>
                    <fullName>Enable_ePSS</fullName>
                </value>
                <value>
                    <fullName>Enable_VSS</fullName>
                </value>
                <value>
                    <fullName>Enable EndUser ACCTCreation</fullName>
                </value>
                <value>
                    <fullName>Enable Lead Conversion</fullName>
                </value>
                <value>
                    <fullName>Enable PDR ACCTCreation</fullName>
                </value>
                <value>
                    <fullName>Enable Target Prospect Creation</fullName>
                </value>
                <value>
                    <fullName>GSPO_BDM</fullName>
                </value>
                <value>
                    <fullName>GSSO HD Forecast User</fullName>
                </value>
                <value>
                    <fullName>MCP Prospect Engage</fullName>
                </value>
                <value>
                    <fullName>MCP Prospect Profiler</fullName>
                </value>
                <value>
                    <fullName>NBM Approver</fullName>
                </value>
                <value>
                    <fullName>NextGen Forecasting Pilot User</fullName>
                </value>
                <value>
                    <fullName>QIJanACVPilotUser</fullName>
                </value>
                <value>
                    <fullName>RAE SEP Enabled</fullName>
                </value>
                <value>
                    <fullName>Request Resource</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Theatre__c</fullName>
        <inlineHelpText>Please contact GSTS Support to Edit this field</inlineHelpText>
        <label>Theater</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Americas-Canada</fullName>
                </value>
                <value>
                    <fullName>Americas-Global Enterprise Segment</fullName>
                </value>
                <value>
                    <fullName>Americas-LATAM</fullName>
                </value>
                <value>
                    <fullName>Americas-US Commercial</fullName>
                </value>
                <value>
                    <fullName>Americas-US Public Sector</fullName>
                </value>
                <value>
                    <fullName>APJC-APAC</fullName>
                </value>
                <value>
                    <fullName>APJC-Greater China</fullName>
                </value>
                <value>
                    <fullName>APJC-Japan</fullName>
                </value>
                <value>
                    <fullName>EMEAR</fullName>
                </value>
                <value>
                    <fullName>Global Service Provider</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TSN_Select_Req_Test.cls
/***************************************************************************************************************************
Modification History

Shivi Srivastava    Removed SeeAllData=True    16-Apr-2019
****************************************************************************************************************************/
@isTest(SeeAllData=false)

private Class TSN_Select_Req_Test{
    private static testMethod void test(){
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Cisco_Admin' Limit 1];
        User admUser = new User(Additional_User_Permissions__c = 'Enable EndUser ACCTCreation', Alias = 'newUser', Email = 'batchJobOppty@cisco.com',
                                EmailEncodingKey = 'UTF-8', LastName = 'Testing', LanguageLocaleKey = 'en_US',
                                LocaleSidKey = 'en_US', ProfileId = p.Id, TimeZoneSidKey = 'America/Los_Angeles', UserName = 'batchJobOppty@cisco.com.testing', Theatre__c = 'Americas-US Commercial');
        insert admUser; 
        Id devRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Channel').getRecordTypeId();
        ObjectRecordTypeIds__c o = new ObjectRecordTypeIds__c();
        o.AccountChannelRecordTypeId__c = devRecordTypeId;
        insert o;
        System.runAs(admUser){
            Org_Constants__c os =new Org_Constants__c();
            os.Key__c = 'Oppty: ProfileIds to skip Triggers';
            os.non_prod_value__c = '00e30000000dcbfAAA,00e30000000dfUEAAY,00e30000000eca0AAA,00e30000000qiJjAAI,00e30000000dcbgAAA,00e30000000rrZwAAI';
            os.Prod_LT__c = 'GSTS,Data_Migration,Integration_Echo_Suppression,GSTS_Analyst,ADMIN, PSS';
            os.prod_value__c = '00e30000000dcbfAAA,00e30000000dfUEAAY,00e30000000eca0AAA,00e30000000qiJjAAI,00e30000000dcbgAAA,00e30000000rrZwAAI';
            os.Type__c = 'URL';
            insert os;
            
            Id RecordTypeIdAccount = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Channel').getRecordTypeId();
            Account a = new Account(Name = 'test',recordtypeid=RecordTypeIdAccount ,CSCSiteID__c ='5555',CSCID__c = '5555',ownerid = admUser.id,AddressLine1__c='Test123',AddressLine1_English__c='Test231',AddressLine2__c='Testqa1',AddressLine2_English__c='Testqa123',City__c='UN',City_English__c='Test',State__c= 'AP',State_Province_English__c='ENDTESt',Country__c='INDIA',Country_English__c='INDIA',TOKENID__c='12333',ZipPostalCode__c='847733',Zip_Postal_Code_English__c='766644');
            insert a;  
            
            Account acct = new Account(Name='Testing');
            insert acct;
            
            list<contact> conlist = new list<contact>();
            contact con = new contact(lastName= 'Test contact');
            insert con;
            conlist.add(con);
            // Cisco_US_Commercial User
            //@@ 10/05 - Added Additional User Permission check.
            //User opptyOwner = [Select id from user where profile.name='Cisco_US_Commercial' and IsActive = True AND Additional_User_Permissions__c excludes ('Enable_ePSS') limit 1];
            
            // Cisco_Sales_Cases User
            Profile pro = [SELECT Id FROM Profile WHERE Name = 'Cisco_Sales_Cases' Limit 1];
            User currentUser = new User( Alias = 'newUse', Email = 'batchJobOppty@cisco.com',
                                        EmailEncodingKey = 'UTF-8', LastName = 'Testing', LanguageLocaleKey = 'en_US',
                                        LocaleSidKey = 'en_US', ProfileId = pro.Id, TimeZoneSidKey = 'America/Los_Angeles', UserName = 'batchJobOppty1@cisco.com.testing', Theatre__c = 'Americas-US Commercial');
            insert currentUser;
            //User currentUser = [Select id from user where profileid=:Utilities.getTSNProfileId() and IsActive = True limit 1];
            ProfileID__c pf = new ProfileID__c();
            pf.Cisco_Renewals__c = '00ec0000000QmlF';
            pf.Cisco_PSS__c = '00e30000000rrZw';       
            insert pf;
            Opportunity oppty = new Opportunity(OwnerId=currentUser.Id,Opportunity_Owner_AM__c=currentUser.Id,name='test_oppty',stageName='1 - Prospect',CloseDate=Date.today().addDays(2),Expected_Product__c = 11,AccountID= acct.ID,Theater__c = 'Americas-US Commercial',Competitors__c = 'Adobe');
            insert oppty;
            Id PSTSRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('PSTS Case').getRecordTypeId();
            Id GVERecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('GVE Case').getRecordTypeId();
            Id CustSuccessRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Customer Success Adoption Request').getRecordTypeId();
            Id EngageSerResRecordTypeID = Schema.SObjectType.Case.getRecordTypeInfosByName().get('AS Pre Sales Engagement Request').getRecordTypeId();
            
            Case c1 = new Case(AccountId = a.Id,recordtypeid=PSTSRecordTypeId,OwnerId = currentUser.Id);
            insert c1; // PH Case 
            
            Case c2 = new Case(AccountId = a.Id,recordtypeid=GVERecordTypeId,OwnerId = currentUser.Id);
            //insert c2; // TSN Case 
            
            Case c3 =  new Case(AccountId = a.Id,recordtypeid=GVERecordTypeId,OwnerId = currentUser.Id,contactId= con.id);
            
            Case c4 = new Case();
            
            Case c5 = new Case(AccountId = a.Id,recordtypeid=CustSuccessRecordTypeId,OwnerId = currentUser.Id); 
            
            Case c6 = new Case(Opportunity__c=oppty.id, AccountId = a.Id,recordtypeid=EngageSerResRecordTypeID,OwnerId = currentUser.Id); 
            
            
            Case[] cs = new Case[]{c1,c2,c3,c4,c5,c6};
                
                Test.StartTest();
            
            System.currentPageReference().getParameters().put('id', c1.id);
            System.currentPageReference().getParameters().put('RecordType',PSTSRecordTypeId);
            
            
            ApexPages.StandardController stdCon = new ApexPages.StandardController(c1); 
            TSN_SelectReq_CTE selectreq= new TSN_SelectReq_CTE(stdCon);
            selectreq.redirect();       
            selectreq.cancel();
            selectreq.Contacttype = 'test';
            selectreq.Name = 'test'; 
            selectreq.Title = 'test';
            selectreq.wpn = 'test';
            selectreq.ipn = 'test';
            selectreq.mn = 'test';
            selectreq.country = 'test';
            selectreq.ciscoid = 'bdabbara';  
            
            /////////////////////////////////////////////////////////////////////////////////////////////////////////
            
            
            System.currentPageReference().getParameters().put('id', c2.id);
            System.currentPageReference().getParameters().put('RecordType',GVERecordTypeId);
            //System.currentPageReference().getParameters().put('00N80000004S02p','susv@cisco.com');
            System.currentPageReference().getParameters().put('def_account_id',a.Id);  
            System.currentPageReference().getParameters().put('userTheme','Theme3');
            
            
            ApexPages.StandardController stdCon1 = new ApexPages.StandardController(c2); 
            TSN_SelectReq_CTE selectreq1= new TSN_SelectReq_CTE(stdCon1);
            
            selectreq1.redirect();
            
            
            selectreq1.setContype('Partner');
            selectreq1.getContype();
            
            selectreq1.setConname('susv@cisco.com');
            selectreq1.getConname();
            
            selectreq1.getCecval();
            
            selectreq1.setCaseval(c4);
            selectreq1.getCaseval();
            
            selectreq1.Save();
            
            selectreq1.setContype('Cisco');
            selectreq1.getContype();
            
            selectreq1.setConname('susv@cisco.com');
            selectreq1.getConname();
            
            selectreq1.id = c2.id;
            
            selectreq1.setCaseval(c4);
            selectreq1.getCaseval();
            
            selectreq1.Save();
            
            
            
            // selectreq1.contype = 'Cisco';
            selectreq1.setContype('Cisco');
            selectreq1.getContype();
            
            selectreq1.getItems();
            
            
            
            
            
            
            
            /////////////////////////////////////////////////////////////////////////////////////////////////////////
            
            
            System.currentPageReference().getParameters().put('id', c3.id);
            System.currentPageReference().getParameters().put('RecordType',GVERecordTypeId);
            System.currentPageReference().getParameters().put('Cecid','susv@cisco.com');
            System.currentPageReference().getParameters().put('def_parent_id',c1.id);
            System.currentPageReference().getParameters().put('CF00NS0000000wTX4',oppty.Name);
            System.currentPageReference().getParameters().put('CF00NS0000000wTX4_lkid',oppty.Id);
            System.currentPageReference().getParameters().put('def_account_id',a.Id);
            System.currentPageReference().getParameters().put('def_contact_id',con.Id);  
            System.currentPageReference().getParameters().put('userTheme','Theme4u');
            
            
            
            //System.currentPageReference().getParameters().put('CF00N80000004w7Ao_lkid','12345678');
            
            
            
            
            ApexPages.StandardController stdCon2 = new ApexPages.StandardController(c3); 
            TSN_SelectReq_CTE selectreq2= new TSN_SelectReq_CTE(stdCon2);
            
            selectreq2.redirect();
            selectreq2.setCaseval(c4);
            selectreq2.getCaseval();
            
            selectreq2.setThemeFromSession();    
            
            selectreq2.setCount(true);
            selectreq2.getCount();
            
            selectreq2.setConname('susv@cisco.com');
            selectreq2.getConname();
            
            selectreq2.getCecval();
            
            selectreq2.cancel();
            
            selectreq2.setContype('Cisco');
            selectreq2.getContype();
            selectreq2.Save();
            
            
            
            System.currentPageReference().getParameters().put('id', c6.id);
            System.currentPageReference().getParameters().put('RecordType',EngageSerResRecordTypeID);
            System.currentPageReference().getParameters().put('Cecid','susv@cisco.com');
            System.currentPageReference().getParameters().put('def_parent_id',c1.id);
            System.currentPageReference().getParameters().put('CF00NS0000000wTX4',oppty.Name);
            System.currentPageReference().getParameters().put('CF00NS0000000wTX4_lkid',oppty.Id);
            System.currentPageReference().getParameters().put('def_account_id',a.Id);
            System.currentPageReference().getParameters().put('def_contact_id',con.Id);    
            System.currentPageReference().getParameters().put('userTheme','Theme4u');   
            
            ApexPages.StandardController stdCon6 = new ApexPages.StandardController(c6); 
            TSN_SelectReq_CTE selectreq6= new TSN_SelectReq_CTE(stdCon6);
            selectreq6.rType=null;
            selectreq6.redirect();       
            
            ApexPages.StandardController stdCon3 = new ApexPages.StandardController(c6); 
            TSN_SelectReq_CTE selectreq3= new TSN_SelectReq_CTE(stdCon3);
            
            selectreq3.redirect();
            selectreq3.getId(); 
            selectreq3.setId(c6.Id);          
            selectreq3.setCaseval(c6);
            selectreq3.getCaseval();
            selectreq3.contactName = 'Test';
            selectreq3.accountId = a.Id;    
            selectreq3.setThemeFromSession();    
            
            selectreq3.setCount(true);
            selectreq3.getCount();
            
            selectreq3.setConname('susv@cisco.com');
            selectreq3.getConname();
            
            selectreq3.getCecval();
            
            selectreq3.cancel();
            
            selectreq3.setContype('Cisco');
            selectreq3.getContype();
            selectreq3.Save();
            
            System.currentPageReference().getParameters().put('RecordType',PSTSRecordTypeId);
            
            TSN_SelectReq_CTE selectreq4= new TSN_SelectReq_CTE(stdCon3);
            selectreq4.rType = null; 
            selectreq4.Org = '';
            selectreq4.contacts = conlist;
            selectreq4.contacts1 = conlist;
            selectreq4.query = '';
            selectreq4.redirect();
            selectreq4.getId(); 
            selectreq4.setId(c6.Id);          
            selectreq4.setCaseval(c6);
            selectreq4.getCaseval();
            selectreq4.contactName = 'Test';
            selectreq4.accountId = a.Id;    
            selectreq4.setThemeFromSession();    
            
            selectreq4.setCount(true);
            selectreq4.getCount();
            
            selectreq4.setConname('susv@cisco.com');
            selectreq4.getConname();
            
            selectreq4.getCecval();
            
            selectreq4.cancel();
            
            selectreq4.setContype('Cisco');
            selectreq4.getContype();
            selectreq4.Save();
            
            
            
            
            
            
            Test.StopTest();
            
        }
    }
}