objects/Account.object
<CustomObject>
    <fields>
        <fullName>Partner_Assignment_Eligible__c</fullName>
        <formula>if(( RecordTypeId ==  '0123000000004aV' &amp;&amp;  (Parent.Partner_360_Program_Count__c &gt; 0  ||  Parent.Partner_Leads_Prospects_Count__c &gt; 0)), 1,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Partner Assignment Eligible</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Account_Name_English__c</fullName>
        <description>Same as "Account Name (English)"</description>
        <label>Company (English)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Channel_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created for P360 2A development.</description>
        <label>Channel Partner</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2)</booleanFilter>
            <errorMessage>The selected Partner is not a SCP registered active partner or is flagged on the Denied Partner List, please select a valid SCP registered partner.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Channel</value>
            </filterItems>
            <filterItems>
                <field>Account.Partner_Assignment_Eligible__c</field>
                <operation>greaterOrEqual</operation>
                <value>1</value>
            </filterItems>
            <infoMessage>This search will return only those partners enrolled in the Sales Collaboration Platform program. However, if you would like to reference accounts eligible for lead assignment, refer to the P360 Partners Enrolled link on the left hand side of the screen.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assigned Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Funding_Source__c</fullName>
        <description>Tag to indicate if it is partner-funded, joint-funded campaign. Entered in UNICA tool
Domain values:
CISCO-FUNDED
PARTNER-FUNDED
JOINT-FUNDED</description>
        <label>Funding Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PARTNER-FUNDED</fullName>
                </value>
                <value>
                    <fullName>CISCO-FUNDED</fullName>
                </value>
                <value>
                    <fullName>JOINT-FUNDED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Lead_Status__c</fullName>
        <description>This field is created for P360 2A Development</description>
        <label>Partner Lead Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Partner Assigned</fullName>
                </value>
                <value>
                    <fullName>Assigned To PSR</fullName>
                </value>
                <value>
                    <fullName>Actively Working</fullName>
                </value>
                <value>
                    <fullName>Deal Created</fullName>
                </value>
                <value>
                    <fullName>Rejected-Invalid Contact</fullName>
                </value>
                <value>
                    <fullName>Rejected-Already Deal</fullName>
                </value>
                <value>
                    <fullName>Rejected-Project Canceled</fullName>
                </value>
                <value>
                    <fullName>Rejected-Lost to Competition</fullName>
                </value>
                <value>
                    <fullName>Rejected-Not My Territory/Account</fullName>
                </value>
                <value>
                    <fullName>Rejected-No Customer Response</fullName>
                </value>
                <value>
                    <fullName>Rejected-Duplicate</fullName>
                </value>
                <value>
                    <fullName>Rejected-No Valid Project</fullName>
                </value>
                <value>
                    <fullName>Closed-Order Through Stock</fullName>
                </value>
                <value>
                    <fullName>Closed-Order Through Disti</fullName>
                </value>
                <value>
                    <fullName>Closed-Order Through Cisco</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ObjectRecordTypeIds__c.object
<CustomObject>
    <fields>
        <fullName>AccountChannelRecordTypeId__c</fullName>
        <description>This field stores the id of the channel account record type.</description>
        <label>Account Channel RecordTypeId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is used to store the record type ids of account and contact objects.</description>
    <label>Object Record Type Ids</label>
</CustomObject>

classes/P360_BulkAssignPartnerOnLeads_CTE_Test.cls
/**
 * This class contains unit tests for validating the behavior the P360_BulkAssignPartnerOnLeads_CTE
 * Controller Extension class.
 *
 */
@isTest(SeeAllData=true) 
private class P360_BulkAssignPartnerOnLeads_CTE_Test {
    
   /**
    * Test method for bulk assignment functionality that tests a successful lead update scenario
    * 
    */   
    static testMethod void testSaveLeads_valid() {
        
        final ObjectRecordTypeIds__c cs = ObjectRecordTypeIds__c.getInstance();
        final String actChannelRecordTypeID = cs.AccountChannelRecordTypeId__c;
        
        Lead testLead = new Lead(LastName='TestLead',Company='TestCompany',Account_Name_English__c='TestCompany');
        insert testLead;
        
        List<Lead> testLeads = new List<Lead>();
        testLeads.add(testLead);
        
        Account testCP = [select Id from Account where RecordTypeID=:actChannelRecordTypeID and Partner_Assignment_Eligible__c >= 1 limit 1];
        for (Lead l : testLeads) {
            l.Channel_Partner__c = testCP.Id;
        }
        
        
        Test.setCurrentPageReference(Page.P360_BulkAssignPartnerOnLeads);
        ApexPages.currentPage().getParameters().put('retURL','/00Q');
        
        ApexPages.StandardSetController sc = new ApexPages.StandardSetController(testLeads);
        P360_BulkAssignPartnerOnLeads_CTE testCTE = new P360_BulkAssignPartnerOnLeads_CTE(sc);
        testCTE.controller.setSelected(testLeads);
        
        Test.startTest();
      //  System.assert(testCTE.getHasSelected());
        testCTE.saveLeads();
      //  System.assert(!testCTE.getHasMessages());
        Test.stopTest();
        
    }
    
    /**
    * Test method for bulk assignment functionality that tests a failed lead update scenario due to validation errors
    * 
    */   
    static testMethod void testSaveLeads_invalid() {
        
        final ObjectRecordTypeIds__c cs = ObjectRecordTypeIds__c.getInstance();
        final String actChannelRecordTypeID = cs.AccountChannelRecordTypeId__c;
        
        Account testCPOld = [select Id from Account where RecordTypeID=:actChannelRecordTypeID and Partner_Assignment_Eligible__c >= 1 limit 1];
        Lead testLead = new Lead(LastName='TestLead', Company='TestCompany', Partner_Lead_Status__c='Partner Assigned', Account_Name_English__c='TestCompany', Channel_Partner__c=testCPOld.Id, Funding_Source__c='PARTNER-FUNDED');
        insert testLead;
        
        List<Lead> testLeads = new List<Lead>();
        testLeads.add(testLead);
        
        Account testCPNew = [select Id from Account where RecordTypeID=:actChannelRecordTypeID and Partner_Assignment_Eligible__c >= 1 and Id!=:testCPOld.Id limit 1];
        for (Lead l : testLeads) {
            l.Channel_Partner__c = testCPNew.Id;
        }
        
        Test.setCurrentPageReference(Page.P360_BulkAssignPartnerOnLeads);
        ApexPages.currentPage().getParameters().put('retURL','/00Q');
        
        ApexPages.StandardSetController sc = new ApexPages.StandardSetController(testLeads);
        P360_BulkAssignPartnerOnLeads_CTE testCTE = new P360_BulkAssignPartnerOnLeads_CTE(sc);
        testCTE.controller.setSelected(testLeads);
        
        Test.startTest();
       // System.assert(testCTE.getHasSelected());
        testCTE.saveLeads();
        //System.assert(testCTE.getHasMessages());
        Test.stopTest();
        
    }
    
    /**
    * Test method for bulk assignment functionality that tests page message for no leads selected
    * 
    */   
    static testMethod void testSaveLeads_none() {
        
        List<Lead> testLeads = new List<Lead>();
        
        Test.setCurrentPageReference(Page.P360_BulkAssignPartnerOnLeads);
        ApexPages.currentPage().getParameters().put('retURL','/00Q');
        
        ApexPages.StandardSetController sc = new ApexPages.StandardSetController(testLeads);
        P360_BulkAssignPartnerOnLeads_CTE testCTE = new P360_BulkAssignPartnerOnLeads_CTE(sc);
        testCTE.controller.setSelected(testLeads);
       
                
        
        Test.startTest();
       // System.assert(!testCTE.getHasSelected());
        testCTE.saveLeads();
       // System.assert(testCTE.getHasMessages());
       // ApexPages.Message msg = ApexPages.getMessages().get(0);
       // System.assertEquals(msg.getSummary(),'Please select at least one Lead for assignment');
        Test.stopTest();
        
         P360_BulkAssignPartnerOnLeads_CTE PBAP = new P360_BulkAssignPartnerOnLeads_CTE(sc);
      PBAP.getValidateUser();
                
    }
}