objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer recordtype for C360</description>
        <label>Customer</label>
    </recordTypes>
</CustomObject>

objects/ObjectRecordTypeIds__c.object
<CustomObject>
    <fields>
        <fullName>Account_BU_RecordType_18__c</fullName>
        <label>Account BU RecordType 18</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Customer_RecordTypeId__c</fullName>
        <label>Account Customer RecordTypeId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Customer_RecordType_18__c</fullName>
        <label>Account Customer RecordType 18</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is used to store the record type ids of account and contact objects.</description>
    <label>Object Record Type Ids</label>
</CustomObject>

objects/QSR__c.object
<CustomObject>
    <fields>
        <fullName>Meeting_Date__c</fullName>
        <description>As a CSE, I'd like to have a Meeting Date for QSR data layout</description>
        <label>Meeting Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Meeting_Status__c</fullName>
        <label>Meeting Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Meeting Scheduled</fullName>
                </value>
                <value>
                    <fullName>Closed-Success</fullName>
                </value>
                <value>
                    <fullName>Closed-Customer Refused</fullName>
                </value>
                <value>
                    <fullName>Closed-Invalid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Success_Plan__c</fullName>
        <label>Success Plan</label>
        <referenceTo>Success_Plan__c</referenceTo>
        <relationshipLabel>Quarterly Success Reviews (QSRs)</relationshipLabel>
        <relationshipName>QSR</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <description>Used for C360 Customer Success Program</description>
    <label>QSR</label>
    <nameField>
        <label>QSR  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QSR</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Success_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Customer_BU_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BU NAME</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Success Plans</relationshipLabel>
        <relationshipName>Success_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account Customer RT(Parent) to Success Plan (Child)</description>
        <label>Customer Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Success Plans</relationshipLabel>
        <relationshipName>Success_Plans2</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>Used for C360 Customer Success Program</description>
    <label>Success Plan</label>
    <nameField>
        <label>Success Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Success Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/QSRCustomerList.cls
public class QSRCustomerList {
    // Get recordType and update isCustomerRT, if account is a Customer or BU
   // @AuraEnabled
   /* public static string getRecordtype(Id AccId) {
        string  recordType;
        Id accountRecordtypeId = [SELECT Id, RecordtypeId FROM Account where Id = :AccId].RecordtypeId;
        ObjectRecordTypeIds__c accRTId = ObjectRecordTypeIds__c.getOrgDefaults();
        if(accountRecordtypeId == accRTId.Account_Customer_RecordType_18__c){
            recordType= accRTId.Account_Customer_RecordType_18__c;
        }else if(accountRecordtypeId == accRTId.Account_BU_RecordType_18__c){
            recordType = accRTId.Account_BU_RecordType_18__c;
        }
        return recordType;
    } */
    
    @AuraEnabled
    public static Boolean getRecordtype(Id AccId) {
        Boolean isCustomerRT = false;
        Id accountRecordtypeId = [SELECT Id, RecordtypeId FROM Account where Id = :AccId].RecordtypeId;
        ObjectRecordTypeIds__c accRTId = ObjectRecordTypeIds__c.getOrgDefaults();
        if(accountRecordtypeId == accRTId.Account_Customer_RecordTypeId__c){
            isCustomerRT = true;
        }
        return isCustomerRT;
    }
    
    //Loading oppty for a specific account
    @AuraEnabled
    public static List<QSR__c> fetchParentQSRList(Id AccId,boolean isCustomerRT) {      
        List<QSR__c> QSRData = new List<QSR__c>();   
        QSRData = null;
        QSRData = Database.query('SELECT Id,Name,Meeting_Status__c,Meeting_Date__c,Success_Plan__r.Customer_BU_Name__c,Success_Plan__r.Customer_BU_Name__r.Name '+
                                 +' FROM QSR__c '+
                                 +' WHERE '+
                                 + ((isCustomerRT) ? 'Success_Plan__r.Customer_BU_Name__r.ParentId =:AccId or Success_Plan__r.Customer_Name__r.Id =:AccId' : 'Success_Plan__r.Customer_BU_Name__r.Id =:AccId') +
                                 +' Order by Meeting_Date__c asc Limit 10');
        return QSRData;
        
    }
    
    //Loading oppty for a specific account in view all
    @AuraEnabled
    public Static List<QSR__c> getQSR(Integer Limits,String AccId,boolean isCustomerRT){ 
       
        List<QSR__c> QSRList = new List<QSR__c>();      
        
        QSRList = Database.query('SELECT Id,Name,Meeting_Status__c,Meeting_Date__c,Success_Plan__r.Customer_BU_Name__c,Success_Plan__r.Customer_BU_Name__r.Name '+
                                 +' FROM QSR__c '+
                                 +' WHERE '+
                                 + ((isCustomerRT) ? 'Success_Plan__r.Customer_BU_Name__r.ParentId =:AccId or Success_Plan__r.Customer_Name__r.Id =:AccId' : 'Success_Plan__r.Customer_BU_Name__r.Id =:AccId') +
                                 +' Order by Meeting_Date__c asc Limit ' + String.valueof(Limits));
        return QSRList;
    }
    
    //Total number of opty for lazy loading
    @AuraEnabled
    public static Integer TotalQSR(String AccId,boolean isCustomerRT){       
        AggregateResult results = Database.query('SELECT Count(Id) TotalQSR'+
                                 +' FROM QSR__c '+
                                 +' WHERE '+
                                 + ((isCustomerRT) ? 'Success_Plan__r.Customer_BU_Name__r.ParentId =:AccId or Success_Plan__r.Customer_Name__r.Id =:AccId' : 'Success_Plan__r.Customer_BU_Name__r.Id =:AccId') );
                                 
        
        Integer totalQSRList = (Integer)results.get('TotalQSR');
        return totalQSRList ;
    }  
    
    @Auraenabled
    public static void delteDocById(String docId){
        QSR__c delDoc=[Select Id from QSR__c where id=:docId];
        delete delDoc;
    }
}