objects/Account.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
                <value>
                    <fullName>BRAZIL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Additional_User_Permissions__c</fullName>
        <description>Allows permission for additional functionality which are based on User and not by profile.
1)AccountCreateByTerritory: New SBC functionality which allows SBC based on Geo Rules
2)Enable EndUser ACCTCreation : Can Create End-User accounts
3)Enable Lead Conversion : Can Convert leads
4)Enable PDR ACCTCreation : Can Create End-User Account during CCW deal conversion
5)Request Resource : Allows AMs to access SE functionality
6)SE User : Allows SEs to access SE Functionality
7)2028 Visibility:Users that will be refreshed by 2028 black box process
8)NBM Approver : User can set status field of NBM records to 'Screen 3' Approval status</description>
        <label>Additional User Permissions</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>2028 Visibility</fullName>
                </value>
                <value>
                    <fullName>AccountCreateByTerritory</fullName>
                </value>
                <value>
                    <fullName>AcquisitionUser</fullName>
                </value>
                <value>
                    <fullName>Activate Sales Account View</fullName>
                </value>
                <value>
                    <fullName>CCE Enabled</fullName>
                </value>
                <value>
                    <fullName>DSEC360</fullName>
                </value>
                <value>
                    <fullName>DSEC360SAV</fullName>
                </value>
                <value>
                    <fullName>DSEContactIntelligence</fullName>
                </value>
                <value>
                    <fullName>DSECRinSFDC</fullName>
                </value>
                <value>
                    <fullName>DSEFA</fullName>
                </value>
                <value>
                    <fullName>DSEGA</fullName>
                </value>
                <value>
                    <fullName>DSENotification</fullName>
                </value>
                <value>
                    <fullName>DSESWSS</fullName>
                </value>
                <value>
                    <fullName>DSETAC</fullName>
                </value>
                <value>
                    <fullName>Einstein Opportunities</fullName>
                </value>
                <value>
                    <fullName>Enable_ePSS</fullName>
                </value>
                <value>
                    <fullName>Enable_VSS</fullName>
                </value>
                <value>
                    <fullName>Enable EndUser ACCTCreation</fullName>
                </value>
                <value>
                    <fullName>Enable Lead Conversion</fullName>
                </value>
                <value>
                    <fullName>Enable PDR ACCTCreation</fullName>
                </value>
                <value>
                    <fullName>Enable Target Prospect Creation</fullName>
                </value>
                <value>
                    <fullName>GSPO_BDM</fullName>
                </value>
                <value>
                    <fullName>GSSO HD Forecast User</fullName>
                </value>
                <value>
                    <fullName>MCP Prospect Engage</fullName>
                </value>
                <value>
                    <fullName>MCP Prospect Profiler</fullName>
                </value>
                <value>
                    <fullName>NBM Approver</fullName>
                </value>
                <value>
                    <fullName>NextGen Forecasting Pilot User</fullName>
                </value>
                <value>
                    <fullName>QIJanACVPilotUser</fullName>
                </value>
                <value>
                    <fullName>RAE SEP Enabled</fullName>
                </value>
                <value>
                    <fullName>Request Resource</fullName>
                </value>
                <value>
                    <fullName>SE User</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/multiEditAccountController_Test.cls
/*
Author          : Shivi Srivastava
Release         : March 29, 2019 Release
Created         : March 26, 2019
Functionality   : multiEditAccountController Test Class


Modification History:
Itrack#        Date        Author              Change 
4/Jun/2019	Kavya 			Removed Seealldata true
*/
@isTest
public class multiEditAccountController_Test {
    static testMethod void multiAccountTest(){
        Utilities.setIsTestMethod(true);
        Utilities.setValidationSkip(true);        
        
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Cisco_ADMIN' Limit 1];
        User usr = lxTestDataFactory.createSingleUser(p.Id);
        insert usr;
        lxTestDataFactory.createCustomSettings();
        Account a = lxTestDataFactory.createChannelAccount(usr.Id);
        a.Country__c ='test';
        a.City__c = 'test';
        insert a;
        AccountTeamMember acntTM = new AccountTeamMember();
        acntTM.TeamMemberRole = 'Cisco_Admin';
        acntTM.AccountId = a.Id;
        acntTM.UserId = usr.Id;
        insert acntTM;
        
        AccountTeamMember atm = [Select Id,TeamMemberRole,User.Username FROM AccountTeamMember limit 1];
        system.debug('accnt team member'+atm);
        User usr1 = [select id from User where isActive=true and id=:atm.user.id limit 1];
        usr.Additional_User_Permissions__c = 'SE User';
        update usr;
        //userIdLst.add(usr.Id);
        String records= '[{'+
            '                    \"accId\": \"'+a.id+'\",'+
            '                    \"accOwner\": \"eudatamanager\",'+
            '                    \"atmId\": \"'+atm.id+'\",'+
            '                    \"atvOptyVal\": 0,' +
            '                \"cActiveOpty\": 1,'+
            '                \"city\": \"CANADA\",'+
            '                \"cOpty\": 12,'+
            '                \"country\": \"CANADA\",'+
            '                \"hasManager\": \"00530000000k1asAAA\",'+
            '                \"memberId\": \"'+usr1.id+'\",'+
            '                \"name\": \"SUNTORY K.K.\",'+
            '               \"optyVal\": 11,'+
            '               \"redirectURL\": \"https://ciscosales--qtr.cs52.my.salesforce.com/0018000000oAFXIAA4",'+
            '               \"role\": \"Systems Engineer (Assigned Account)\",'+
            '               \"teamId\": \"moando\",'+
            '                \"totalContact\": 1'+
            '                }]';
        
        String lstUserIds = '[{'+
            '                    \"id\": \"'+usr1.id+'\"'+
            '                }]';
        
        Test.startTest();
        Boolean save= multiEditAccountController.saveAssignments(records,lstUserIds,true);   
        Boolean save1= multiEditAccountController.saveAssignments(records,lstUserIds,false);   
        Boolean remove= multiEditAccountController.removeAssignments(records,lstUserIds);
        Boolean deleteRec= multiEditAccountController.deleteAssignments(records,lstUserIds);
        Boolean checkSE1=multiEditAccountController.checkSEUserPermission();
        system.runAs(usr){
            Boolean checkSE=multiEditAccountController.checkSEUserPermission();
        }
        Test.stopTest();
    }
}