objects/Account.object
<CustomObject>
    <fields>
        <fullName>AddressLine1__c</fullName>
        <label>Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
                <value>
                    <fullName>BRAZIL</fullName>
                </value>
                <value>
                    <fullName>UNITED STATES</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Theatre__c</fullName>
        <description>Describes which Cisco geographical region the account us managed by.</description>
        <label>Theatre</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>APJ</fullName>
                </value>
                <value>
                    <fullName>EMEAR</fullName>
                </value>
                <value>
                    <fullName>Global Service Provider</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Lead_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>NGCC Phase1:Prospect associated to existing SFDC Contacts</description>
        <label>Sales Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Leads (Lead Contact)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <businessProcess>NGCC Marketing Lead</businessProcess>
        <description>Prospect Leads from Next Gen Marketing Contact Center</description>
        <label>Prospect</label>
    </recordTypes>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Theatre__c</fullName>
        <inlineHelpText>Please contact GSTS Support to Edit this field</inlineHelpText>
        <label>Theater</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Americas-Canada</fullName>
                </value>
                <value>
                    <fullName>Americas-Global Enterprise Segment</fullName>
                </value>
                <value>
                    <fullName>Americas-LATAM</fullName>
                </value>
                <value>
                    <fullName>Americas-US Commercial</fullName>
                </value>
                <value>
                    <fullName>Americas-US Public Sector</fullName>
                </value>
                <value>
                    <fullName>APJC-APAC</fullName>
                </value>
                <value>
                    <fullName>APJC-Greater China</fullName>
                </value>
                <value>
                    <fullName>APJC-Japan</fullName>
                </value>
                <value>
                    <fullName>EMEAR</fullName>
                </value>
                <value>
                    <fullName>Global Service Provider</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/NGCC_ScheduledLeadContactInfo_Test.cls
@isTest(seeAllData=true)
private class NGCC_ScheduledLeadContactInfo_Test  
{
    public static String CRON_EXP = '0 0 0 15 3 ? 2022';
    static testmethod void test() 
    {
        // Fetch profile (Cisco_NGCC) Id using below code.
        Profile p = new Profile();
        p=[select Id,Name from Profile where Name=:'Cisco_NGCC'];
        // create the user with the above collected profile.
        User u = new User();
        u.FirstName='Test First';
        u.LastName='Test Last';
        u.Alias='Tes';
        u.Email='bsrigadd@cisco.com';
        u.UserName='test123@prudential.com';
        u.CommunityNickname='TestF';
        //u.UserRoleid = r.id ;
        u.Profileid=p.Id;
        u.EmailEncodingKey='UTF-8';     
        //u.Prudential_User_ID__c='X187665';
        u.TimeZoneSidKey='America/Los_Angeles';
        u.LocaleSidKey='en_US';
        u.LanguageLocaleKey='en_US';
        u.Theatre__c ='Americas-LATAM';
        insert u;
        
        Account a = new Account();
        a.Name='TestAccount';
        a.AddressLine1__c='Test';
        a.Country__c='UNITED STATES';
        a.City__c='San Jose';
        a.RecordTypeId = '0123000000004aU';
        insert a;
        contact c = new contact();
        c.Lastname='Testlastname';
        c.AccountId=a.Id;
        
        insert c;
        
        // Fetching Record type  (Prospect)
        RecordType r = new RecordType();
        r=[select Id,Name,SobjectType from RecordType where Name='Prospect' and SobjectType='Lead'];
      
        list<Lead> leads = new list<Lead>();
        for(Integer i=0;i<180;i++)
        {
            Lead l = new Lead(OwnerId=u.Id,LastName='Srigadde', Lead_Contact__c= c.Id, RecordTypeId=r.Id, Status='1 Waiting', Company='TestCompany1');
            leads.add(l);
        }
        
       // Profile pr = [SELECT Id FROM Profile WHERE Name='Cisco_NGCC'];
       // User u1 = new User();
        //u1=[select Id,isActive,ProfileId from User where ProfileId=: pr.Id and isActive = true Limit 1];
        
        //System.runAs(u1){
        insert leads;
        //update leads;
        //}

        
        
        Test.startTest();
        String jobId = System.schedule('ScheduleApexClassTest',CRON_EXP,new NGCC_ScheduledLeadContactInfo());
        // Get the information from the CronTrigger API object
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered,NextFireTime FROM CronTrigger WHERE id = :jobId];
         // Verify the expressions are the same
         System.assertEquals(CRON_EXP, ct.CronExpression);
         // Verify the job has not run 
         System.assertEquals(0, ct.TimesTriggered);
         // Verify the next time the job will run 
         System.assertEquals('2022-03-15 00:00:00', String.valueOf(ct.NextFireTime));
         NGCC_UpdateLeadContactInfo N = new NGCC_UpdateLeadContactInfo();
         ID batchprocessid = Database.executeBatch(N);
         
    }    
}