objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Potential_Dollar__c</fullName>
        <description>This field will be populated by trigger Calculate_AccountPotentialDollar, Account Potential Dollar = Exact Number of Employees * Vertical By Head for the Country and Industry combination, Currently used only for European Countries.</description>
        <label>Account Potential $</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AddressLine1_English__c</fullName>
        <description>used for non-english profiles</description>
        <label>Address Line 1 (English)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AddressLine2_English__c</fullName>
        <description>used for non-english profiles</description>
        <label>Address Line 2 (English)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRAddressLine1__c</fullName>
        <label>CR Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRAddressLine2__c</fullName>
        <label>CR Address Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRAdressFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CRAddressFlag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CRCity__c</fullName>
        <label>CR City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRCountry__c</fullName>
        <label>CR Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRState__c</fullName>
        <label>CR State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRZipPostalCode__c</fullName>
        <label>CR ZipPostalCode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City_English__c</fullName>
        <description>used for non-english profiles</description>
        <label>City (English)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_English__c</fullName>
        <description>non-English profiles</description>
        <label>Country (English)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
                <value>
                    <fullName>BRAZIL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
                <value>
                    <fullName>BRAZIL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State_Province_English__c</fullName>
        <description>non-English profiles</description>
        <label>State/Province (English)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Postal_Code_English__c</fullName>
        <description>non-English profiles</description>
        <label>Zip/Postal Code (English)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>needs_geolocation_update__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Release: P360 March 2013 
Purpose: Flag to notify GeoLocation Update is required or Not</description>
        <label>Needs Geolocation Update?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Channel</fullName>
        <active>true</active>
        <description>Registered Partner Account from PDB (Partner Database)</description>
        <label>Channel</label>
    </recordTypes>
</CustomObject>

objects/Assigned_Partner__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Partner Account assigned to this target account.</description>
        <label>Assigned Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Assigned_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cisco_Recomended_Partner_Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cisco Recommended PSR</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assigned_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Industry__c</fullName>
        <description>Industry associated with the end customer</description>
        <formula>TEXT(Customer_Account__r.Industry)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Industry</label>
        <type>Text</type>
    </fields>
    <description>Partner assignments of End User Accounts are stored in this object.</description>
    <label>zzTarget Prospect</label>
    <nameField>
        <label>Target Prospect Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Target Prospects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Vertical_Per_Head__c.object
<CustomObject>
    <fields>
        <fullName>Industry__c</fullName>
        <description>To capture List of Industries in Accounts</description>
        <label>Industry</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vertical_Per_Head_Austria__c</fullName>
        <description>Field to hold Vertical Per Head value against each industry for Austria</description>
        <label>Austria</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vertical_Per_Head_Belgium__c</fullName>
        <description>Field to hold Vertical Per Head value against each industry for Belgium</description>
        <label>Belgium</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vertical_Per_Head_Denmark__c</fullName>
        <description>Field to hold Vertical Per Head value against each industry for Denmark</description>
        <label>Denmark</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vertical_Per_Head_Finland__c</fullName>
        <description>Field to hold Vertical Per Head value against each industry for Finland</description>
        <label>Finland</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vertical_Per_Head_France__c</fullName>
        <description>Field to hold Vertical Per Head value against each industry for France</description>
        <label>France</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vertical_Per_Head_Germany__c</fullName>
        <description>Field to hold Vertical Per Head value against each industry for Germany</description>
        <label>Germany</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vertical_Per_Head_Greece__c</fullName>
        <description>Field to hold Vertical Per Head value against each industry for Greece</description>
        <label>Greece</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vertical_Per_Head_Ireland__c</fullName>
        <description>Field to hold Vertical Per Head value against each industry for Ireland</description>
        <label>Ireland</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vertical_Per_Head_Israel__c</fullName>
        <description>Field to hold Vertical Per Head value against each industry for Israel</description>
        <label>Israel</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vertical_Per_Head_Italy__c</fullName>
        <description>Field to hold Vertical Per Head value against each industry for Italy</description>
        <label>Italy</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vertical_Per_Head_Netherlands__c</fullName>
        <description>Field to hold Vertical Per Head value against each industry for Netherlands</description>
        <label>Netherlands</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <description>Object to hold Vertical Dollar Per Head Lookup Data</description>
    <label>zzVertical Per Head</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Vertical per Head</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vertical Per Head</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AccountBO.cls
/************************************************************************************************************************************
Name    : AccountBO
Author  : Bramhananda Naidu Dabbara
Purpose : Contains complete logic for all the events of Account Trigger
Created Date:  7/6/2015
Modification History: Sournaga- Code clean up, Enhancements & Optimization

*************************************************************************************************************************************/

   public  class AccountBO{

     // SCAVA Helper Method to validate Update Access at field level
     public static Boolean flsUpdateGet(SObjectField field)
    {
        return field.getDescribe().isUpdateable() ? true : false;
    }
     // SCAVA Helper Method to validate Create Access at field level
     public static Boolean flsGet(SObjectField field)
    {
        return field.getDescribe().isCreateable() ? true : false;
    }

    /* update the GEO location update of assigned partner acounts when CR Adress is changed */
    public static void accountGeoLocBeforeUpsertBatch(List<Account> accts){
    
        Map<id,account> accMap = new Map<id,account>([select id,
                                                        (SELECT Assigned_Partner__c FROM Assigned_Partners__r)
                                                        FROM Account
                                                        WHERE id in :accts]);
        for(Account acc: accts)
        {
            list<Assigned_Partner__c> tp;
            String addressNew = '';
            String addressOld = '';
            boolean needsUpdate = false;
            if(accMap!=null && accMap.containsKey(acc.id)) {
                tp = accMap.get(acc.id).assigned_partners__r;
            }
            system.debug('CRFLAG>>>>'+acc.CRAdressFlag__c);
            if(acc.CRAdressFlag__c){
            
                addressNew = acc.CRAddressLine1__c + acc.CRAddressLine2__c + acc.CRCity__c + acc.CRState__c + acc.CRZipPostalCode__c + acc.CRCountry__c;
            }
            else{
                addressNew = acc.AddressLine1_English__c+ acc.AddressLine2_English__c + acc.City_English__c
                            + acc.State_Province_English__c + acc.Zip_Postal_Code_English__c + acc.Country_English__c;
            }


            if(trigger.isInsert) {
                needsUpdate = ((!tp.isEmpty()) && (addressNew != ''));
            }
            
            if(trigger.isUpdate) {
                Account beforeUpdate = (Account)Trigger.oldMap.get(acc.Id);

                if(beforeUpdate.CRAdressFlag__c){
                    addressOld = beforeUpdate.CRAddressLine1__c + beforeUpdate.CRAddressLine2__c + beforeUpdate.CRCity__c
                                + beforeUpdate.CRState__c + beforeUpdate.CRZipPostalCode__c + beforeUpdate.CRCountry__c;
                }
                else {
                    addressOld = beforeUpdate.AddressLine1_English__c+ beforeUpdate.AddressLine2_English__c
                                + beforeUpdate.City_English__c + beforeUpdate.State_Province_English__c + beforeUpdate.Zip_Postal_Code_English__c
                                + beforeUpdate.Country_English__c;
                }
                
                //set needUpdate boolean to true if the account has target prospect &  assigned partner's address has been changed
                needsUpdate = (!tp.isEmpty()) && ((addressNew != addressOld) || (acc.Geolocation__Latitude__s == null));
            }

            if(needsUpdate) {
                acc.needs_geolocation_update__c=true;
            }
        }
    }

    //Check if the user has permission to delete the account and display appropriate error mesage configured in Label.
    public static void accountDelete(List<Account> accList) {
        Map<string,string> mpstd=new Map<string,string>();
        String profileId = Userinfo.getProfileId();
        String profileIds  = profileId.substring(0,15);
        string accDeleteId = Utilities.getConstant_CS('ProfileIds_for_Delete');
        string[] accDeleteIds;
        
        if(accDeleteId != null) {
            accDeleteIds= accDeleteId.split(';');
            for(string stIds:accDeleteIds) {
                mpstd.put(stIds,stIds);
            }
        }

        //if the user id does not exist in the map display error msg
        if(!((mpstd.containsKey(profileIds)) || (mpstd.containsKey(profileId)))) {
            for(Account acc: accList) {
                   acc.addError(Label.Account_Delete_Error);
            }
        }
    }
    
    /*This method used to throw the Jigsaw import exception */
    
    /*
    public static void jigsawImport( List<Account> lstAcc) {
    for(Account acc : lstAcc) {
            if(acc.jigsaw_clean__Jigsaw_Id__c != null && acc.jigsaw_clean__Sync_Status__c!=null && acc.jigsaw_clean__Sync_Status__c.equals('I')) {
                throw new jiggy_CustomException(Label.Jigsaw_Exception);
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.FATAL,Label.Account_Jigsaw_Import_Error);

            }
        }
    }
    */
    
    /* Update Account Potential Dollar value on Account based on the Country, Number of Employees and Industry selected on the record.
    Vertical per head for each country depending on industry is stored in rs_vertical_per_head__C object 
    public static void AccountPotentialDollar(List<Account> lstAcc) {
        // Vertical_Per_Head__c[] rsVerticalPerHead  = OrgHelper.getVerticalPerHead();
        for(Account acc:lstAcc) {
            if(acc.Country__c!=null &&  acc.NumberOfEmployees!=null && acc.Industry !=null) {
            
                for(Integer i=0;i<rsVerticalPerHead.size();i++) {
                
                    if(rsVerticalPerHead[i].Industry__c==acc.Industry) {
                    
                        if(acc.Country__c=='Austria'){ acc.Account_Potential_Dollar__c = acc.NumberOfEmployees  * rsVerticalPerHead[i].Vertical_Per_Head_Austria__c; }
                        if(acc.Country__c=='Belgium'){ acc.Account_Potential_Dollar__c = acc.NumberOfEmployees  * rsVerticalPerHead[i].Vertical_Per_Head_Belgium__c; }
                        if(acc.Country__c=='Denmark'){ acc.Account_Potential_Dollar__c = acc.NumberOfEmployees  * rsVerticalPerHead[i].Vertical_Per_Head_Denmark__c; }
                        if(acc.Country__c=='Finland'){ acc.Account_Potential_Dollar__c = acc.NumberOfEmployees  * rsVerticalPerHead[i].Vertical_Per_Head_Finland__c; }
                        if(acc.Country__c=='France'){ acc.Account_Potential_Dollar__c = acc.NumberOfEmployees  * rsVerticalPerHead[i].Vertical_Per_Head_France__c; }
                        if(acc.Country__c=='Germany'){ acc.Account_Potential_Dollar__c = acc.NumberOfEmployees  * rsVerticalPerHead[i].Vertical_Per_Head_Germany__c; }
                        if(acc.Country__c=='Greece'){ acc.Account_Potential_Dollar__c = acc.NumberOfEmployees  * rsVerticalPerHead[i].Vertical_Per_Head_Greece__c; }
                        if(acc.Country__c=='Ireland'){ acc.Account_Potential_Dollar__c = acc.NumberOfEmployees  * rsVerticalPerHead[i].Vertical_Per_Head_Ireland__c; }
                        if(acc.Country__c=='Israel'){ acc.Account_Potential_Dollar__c = acc.NumberOfEmployees  * rsVerticalPerHead[i].Vertical_Per_Head_Israel__c; }
                        if(acc.Country__c=='Italy'){ acc.Account_Potential_Dollar__c = acc.NumberOfEmployees  * rsVerticalPerHead[i].Vertical_Per_Head_Italy__c; }
                        if(acc.Country__c=='Netherlands'){ acc.Account_Potential_Dollar__c = acc.NumberOfEmployees  * rsVerticalPerHead[i].Vertical_Per_Head_Netherlands__c; }
                        if(acc.Country__c=='Norway'){ acc.Account_Potential_Dollar__c = acc.NumberOfEmployees  * rsVerticalPerHead[i].Vertical_Per_Head_Norway__c; }
                        if(acc.Country__c=='Portugal'){ acc.Account_Potential_Dollar__c = acc.NumberOfEmployees  * rsVerticalPerHead[i].Vertical_Per_Head_Portugal__c; }
                        if(acc.Country__c=='Spain'){ acc.Account_Potential_Dollar__c = acc.NumberOfEmployees  * rsVerticalPerHead[i].Vertical_Per_Head_Spain__c; }
                        if(acc.Country__c=='Sweden'){ acc.Account_Potential_Dollar__c = acc.NumberOfEmployees  * rsVerticalPerHead[i].Vertical_Per_Head_Sweden__c; }
                        if(acc.Country__c=='Switzerland'){ acc.Account_Potential_Dollar__c = acc.NumberOfEmployees  * rsVerticalPerHead[i].Vertical_Per_Head_Switzerland__c; }
                        if(acc.Country__c=='United Kingdom'){ acc.Account_Potential_Dollar__c = acc.NumberOfEmployees  * rsVerticalPerHead[i].Vertical_Per_Head_United_Kingdom__c; }
                    }
                }
            }
            else {
                acc.Account_Potential_Dollar__c = 0;
            }
        }
    }
    */
    
    /* Update Jabber phone value based on Account Phone Number */
    public static void jabberPhoneClean(Map<id,sobject> oldAccMap, List<Account> lstAcc) {
        JabberPhoneCleanUpcls jPhoneClean= new JabberPhoneCleanUpcls();
        List<Account> newAccountUpdate = new List<Account>();
        for(Account acc: lstAcc) {
            Account oldAcc = (Account)oldAccMap.get(acc.ID);
            if (acc.Phone != oldAcc.Phone || acc.CRCountry__c != oldAcc.CRCountry__c || acc.Jabber_Phone_Number__c == null || acc.Jabber_Phone_Number__c == '') {
                newAccountUpdate.add(acc);
            }
        }
        
        if(!newAccountUpdate.isEmpty()) {
            jPhoneClean.JabberAccountPhoneClean(newAccountUpdate);
        }
    }

    /* Recalculate Partner sharing on Account if the Account Owner is changed */
    public static void P360PartnerResharing(Map<id,sobject> oldAccMap, List<Account> lstAcc) {
        Map<id,Account> oldMpAccounts = new Map<id,Account>();
        if(!Partner360Utils.skip_P360_Partner_Resharing_On_OwnerChange) {
            Set<Id> AccountIds = new Set<Id>();
            ObjectRecordTypeIds__c o = ObjectRecordTypeIds__c.getInstance();
            
            String ACCOUNT_END_USER_RecTypeId = o.Account_End_User_RecordTypeId__c;
            for(Account a: lstAcc) {
            
                Account acOld = (Account)oldAccMap.get(a.id);
                if(a.RecordTypeId == ACCOUNT_END_USER_RecTypeId  && a.ownerId != acOld.ownerId) {
                    AccountIds.add(a.Id);
                }
                
                oldMpAccounts.put(a.id,acOld );
            }
            
            //Calculate partner account resharing for the accounts where owner is changed
            if(!AccountIds.isEmpty()) {
                P360_Partner_Resharing.Partner_Resharing_On_OwnerChange(AccountIds);
            }
            
            if(!Test.isRunningTest() && trigger.isUpdate) {
                // Mark static variable true to skip execution of trigger twice.
                Partner360Utils.skip_P360_Partner_Resharing_On_OwnerChange = true;  
            }
        }
        
        //if (!P360_TP_Created_Basedon_CI_Allocation.hasAlreadyUpdatedFollowUpTasks()) {
        //    P360_TP_Created_Basedon_CI_Allocation.setAlreadyUpdatedFollowUpTasks();
        //    P360_TP_Created_Basedon_CI_Allocation.onCreationAndUpdation(lstAcc, oldMpAccounts);
        //}
    }

    /* When a Channel Account record is deactivated, status associated with the Account record is updated to Inactive and the Account team is deleted.
       Similarly if a Channel Account record status is set to Active(Registered), status of the associated Contacts are updated as Active */
    public static void channelAccountandContactSync(Map<id,sobject> oldAccMap, List<Account> lstAcc) {
        Set<ID> accountsInactive = new set<ID>();
        Set<ID> accountsActive = new Set<ID>();
        AccountTeamMember[] acctTeamToDelete = new AccountTeamMember[]{};
        List<Contact> lstConToUpdate=new List<Contact>();
        Set<Id> setAccountId=new Set<Id>();
        JabberPhoneCleanUpcls jPhoneClean= new JabberPhoneCleanUpcls();
        Contact[] contactsToUpdate = new Contact[]{};
        
        for(Account a:lstAcc) {
            Account acsOld = (Account)oldAccMap.get(a.id);
            if(a.CRCountry__c != acsOld.CRCountry__c) 
            {
                setAccountId.add(a.Id);
            }
            
            //List of accounts where status is changed from active to inactive
            if(a.recordTypeId == Utilities.getAccountChannelRecordTypeId() && a.Partner_Account_Status__c != 'Active (Registered)' 
                && acsOld.Partner_Account_Status__c == 'Active (Registered)') 
            {
                //List of accounts where status is changed from inactive to active
                accountsInactive.add(a.id);
            } 
            else if(a.recordTypeId == Utilities.getAccountChannelRecordTypeId() && a.Partner_Account_Status__c == 'Active (Registered)' 
                      && acsOld.Partner_Account_Status__c != 'Active (Registered)') 
                {
                       accountsActive.add(a.id);
                }
        }
        
        if(!accountsInactive.isEmpty() || !accountsActive.isEmpty()) {
            List<Contact> con =[Select Id, ownerId, AccountId, Account.ownerId, OldContactOwnerBeforeDeletion__c, OldAccountNameBeforeDeletion__c, OldContactOwnerBeforeDeletion__r.IsActive 
                                From Contact 
                                Where AccountId IN :accountsInactive OR AccountId IN:accountsActive ];
            for(Contact c:con) {
                //change status of contacts associated with inactive accounts to inactive
                if(accountsInactive.contains(c.AccountId)) {
                    if(flsUpdateGet(Contact.OldContactOwnerBeforeDeletion__c)||flsGet(Contact.OldContactOwnerBeforeDeletion__c)) //SCAVA FIX
                    {
                    c.OldContactOwnerBeforeDeletion__c=c.ownerId;
                    }
                    if(flsUpdateGet(Contact.OldAccountNameBeforeDeletion__c)||flsGet(Contact.OldAccountNameBeforeDeletion__c)) //SCAVA FIX
                    {
                    c.OldAccountNameBeforeDeletion__c=c.AccountId;
                    }
                    c.ownerId=Utilities.getIntegrationUserId();
                    if(flsUpdateGet(Contact.ContactStatus__c)||flsGet(Contact.ContactStatus__c)) //SCAVA FIX
                    {
                    c.ContactStatus__c='Inactive';
                    }
                    contactsToUpdate.add(c);
                }

                if(accountsActive.contains(c.AccountId)) {
                    if( c.OldContactOwnerBeforeDeletion__c != null) {
                        if(c.OldContactOwnerBeforeDeletion__r.IsActive) {
                    if(flsUpdateGet(Contact.ownerId)||flsGet(Contact.ownerId)) //SCAVA FIX
                    {
                            c.ownerId=c.OldContactOwnerBeforeDeletion__c;
                    }
                        }
                    else {
                    if(flsUpdateGet(Contact.ownerId)||flsGet(Contact.ownerId)) //SCAVA FIX
                    {
                            c.ownerId=c.Account.ownerId;
                    }
                        }
                    }
                    
                    if(c.OldAccountNameBeforeDeletion__c != null) {
                    
                    if(flsUpdateGet(Contact.AccountId)||flsGet(Contact.AccountId)) //SCAVA FIX
                    {
                    c.AccountId=c.OldAccountNameBeforeDeletion__c;
                    }
                    }
                    c.ContactStatus__c='Active';
                    contactsToUpdate.add(c);
                }
            }

            //Delete account team associated with inactive accounts
            acctTeamToDelete = [Select Id From AccountTeamMember Where AccountId IN :accountsInactive];
            
        }
        
        if(!contactsToUpdate.isEmpty())
        {
            Update contactsToUpdate;
        }
        
        //Delete the Account Team when Account status is set to Inactive
        //SCAVA FIX
        
        if(!acctTeamToDelete.isEmpty())
        {
            //SCAVA FIX
            if (AccountTeamMember.sObjectType.getDescribe().isDeletable())
               {
                    Delete acctTeamToDelete;
                }
        }
        
        
        //Jabber phone clean up to remove any alphabetic values.
        if(!setAccountId.isEmpty()) {
            lstConToUpdate=[Select Id,Phone,AccountId,Jabber_Phone_Number__c  from Contact where AccountId IN : setAccountId];
            boolean accContactsUpdate=true;
            jPhoneClean.JabberContactPhoneClean(lstConToUpdate,accContactsUpdate);
        }
    }
}