objects/Account.object
<CustomObject>
    <fields>
        <fullName>AddressLine1_English__c</fullName>
        <description>used for non-english profiles</description>
        <label>Address Line 1 (English)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AddressLine2_English__c</fullName>
        <description>used for non-english profiles</description>
        <label>Address Line 2 (English)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRAddressLine1__c</fullName>
        <label>CR Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRAddressLine2__c</fullName>
        <label>CR Address Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRAdressFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CRAddressFlag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CRCity__c</fullName>
        <label>CR City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRCountry__c</fullName>
        <label>CR Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRState__c</fullName>
        <label>CR State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRZipPostalCode__c</fullName>
        <label>CR ZipPostalCode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City_English__c</fullName>
        <description>used for non-english profiles</description>
        <label>City (English)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_English__c</fullName>
        <description>non-English profiles</description>
        <label>Country (English)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
                <value>
                    <fullName>BRAZIL</fullName>
                </value>
                <value>
                    <fullName>UNITED STATES</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
                <value>
                    <fullName>BRAZIL</fullName>
                </value>
                <value>
                    <fullName>UNITED STATES</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Account_Status__c</fullName>
        <description>Indicates if the selected HQ partner site is still active</description>
        <label>Partner Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active (Registered)</fullName>
                </value>
                <value>
                    <fullName>Inactive (Unregistered)</fullName>
                </value>
                <value>
                    <fullName>Denied Partner List (DPL)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State_Province_English__c</fullName>
        <description>non-English profiles</description>
        <label>State/Province (English)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Postal_Code_English__c</fullName>
        <description>non-English profiles</description>
        <label>Zip/Postal Code (English)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Assigned_Partner__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Partner Account assigned to this target account.</description>
        <label>Assigned Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Assigned_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assignment_Activated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is the assignment activated by TAM/TBM</description>
        <label>Assignment Activated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PSR_Assigned_Date_Time__c</fullName>
        <description>Date/Time PSR was assigned to the Target Prospect</description>
        <label>PSR Assigned Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Partner_Assigned_Date__c</fullName>
        <description>Date/Time when the Partner was assigned to the Target Prospect</description>
        <label>Prospect/Partner Activated Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Partner_Status__c</fullName>
        <label>Partner Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned (New)</fullName>
                    <default>true</default>
                    <label>Assigned (New)</label>
                </value>
                <value>
                    <fullName>Partner Assigned</fullName>
                </value>
                <value>
                    <fullName>Assigned to PSR</fullName>
                </value>
                <value>
                    <fullName>Actively Working</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Target_Architecture__c</fullName>
        <label>Target Architecture</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Any/All Technologies</fullName>
                </value>
                <value>
                    <fullName>Collaboration-Unified Communications (UC)</fullName>
                </value>
                <value>
                    <fullName>Core-Routing Switching &amp; Services</fullName>
                </value>
                <value>
                    <fullName>Data Center-Unified Computing Systems (UCS)</fullName>
                </value>
                <value>
                    <fullName>Video-TelePresence &amp; Conferencing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Target_Description__c</fullName>
        <label>Target Description</label>
        <type>TextArea</type>
    </fields>
    <description>Partner assignments of End User Accounts are stored in this object.</description>
    <label>zzTarget Prospect</label>
    <nameField>
        <label>Target Prospect Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Target Prospects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/AccountTestMethods.cls
@istest
private class AccountTestMethods{
    
    private static testMethod void testChannelContactActDeact(){
        
        Account a = new Account(name='TestAccount',Partner_Account_Status__c='Active (Registered)',recordTypeId=Utilities.getAccountChannelRecordTypeId());
        Insert a;
        Contact c = new Contact(lastname='testContact',AccountId=a.Id, recordtypeId=Utilities.getContactManualPartnerRecordTypeId());
        Insert c;
        a.Partner_Account_Status__c='Inactive';
        Update a;
        a.Partner_Account_Status__c='Active (Registered)';
        Update a;
    
    }
    static testmethod void  accountDeletetest()
    {
      List<Account> acclist = new List<Account>();
       /* Account a = new Account(name='TestAccount',Partner_Account_Status__c='Active (Registered)',recordTypeId=Utilities.getAccountChannelRecordTypeId(),Country__c='UNITED STATES');
        Insert a;
        acclist.add(a);*/
        
         Account  accountTest= UtilUnitTest.getAccount(); 
         insert accountTest; 
        acclist.add(accountTest);
       
        
        Test.startTest();
        AccountBO ABO = new AccountBO();
        AccountBO.accountDelete(acclist);
       // AccountBO.accountGeoLocBeforeUpsertBatch(acclist);
        Test.StopTest();
      
    }
    static testmethod void accountGeoLocBeforeUpsertBatchtest()
    {
       // UtilUnitTest.loadAllStaticData();
       List<Account> acclist = new List<Account>(); 
        Account partnerAccountId = GenericStaticTestData.gettestChannelAccountRecord1();
        //partnerAccountId.CRAdressFlag__c = false;
        partnerAccountId.AddressLine1_English__c = 'test123';
        partnerAccountId.CRAddressLine1__c = 'TestQA';
        partnerAccountId.CRAddressLine1__c = 'Test';
        partnerAccountId.CRAddressLine2__c = 'Test';
        partnerAccountId.CRCity__c = 'test';
        partnerAccountId.CRState__c = 'testState';
        partnerAccountId.CRZipPostalCode__c = 'Q12345';
        partnerAccountId.CRCountry__c = 'UNITESTATES';
        partnerAccountId.AddressLine2_English__c = 'TEST123';
        partnerAccountId.City_English__c = 'TestEnd';
        partnerAccountId.State_Province_English__c = 'TESt';
        partnerAccountId.Zip_Postal_Code_English__c = '12sdf';
        partnerAccountId.Country_English__c = 'Testtest';
        acclist.add(partnerAccountId);
        update acclist;
        
        
        
          /*  Assigned_Partner__c assigned_partnercTest = new Assigned_partner__c(Name='Test Target Prospect Record',TARGET_ARCHITECTURE__C='Any/All Technologies',
            TARGET_DESCRIPTION__C='Test Target Prospect Record',Assigned_Partner__c = acclist[0].id , Partner_Status__c = 'Partner Assigned', 
            Partner_Assigned_Date__c = DateTime.now(), PSR_Assigned_Date_Time__c = DateTime.now());
            insert assigned_partnercTest;
            assigned_partnercTest.Assignment_Activated__c = true;
            update assigned_partnercTest;*/
           
      system.debug('acclist>>'+acclist);
        
      
            
        Test.startTest();
        
      //  AccountBO.accountGeoLocBeforeUpsertBatch(acclist);
        
        Test.stoptest();
        
    
    }
    static testmethod void deletetest()
    {
      List<Account> acclist = new List<Account>(); 
        Account partnerAccountId = GenericStaticTestData.gettestChannelAccountRecord1();
        //partnerAccountId.CRAdressFlag__c = false;
        partnerAccountId.AddressLine1_English__c = 'test123';
        partnerAccountId.CRAddressLine1__c = 'TestQA';
        partnerAccountId.CRAddressLine1__c = 'Test';
        partnerAccountId.CRAddressLine2__c = 'Test';
        partnerAccountId.CRCity__c = 'test';
        partnerAccountId.CRState__c = 'testState';
        partnerAccountId.CRZipPostalCode__c = 'Q12345';
        partnerAccountId.CRCountry__c = 'UNITESTATES';
        partnerAccountId.AddressLine2_English__c = 'TEST123';
        partnerAccountId.City_English__c = 'TestEnd';
        partnerAccountId.State_Province_English__c = 'TESt';
        partnerAccountId.Zip_Postal_Code_English__c = '12sdf';
        partnerAccountId.Country_English__c = 'Testtest';
        acclist.add(partnerAccountId);
        delete acclist; 
    }
}