objects/Account.object
<CustomObject>
    <fields>
        <fullName>Theatre__c</fullName>
        <description>Describes which Cisco geographical region the account us managed by.</description>
        <label>Theatre</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>APJ</fullName>
                </value>
                <value>
                    <fullName>EMEAR</fullName>
                </value>
                <value>
                    <fullName>Global Service Provider</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Apex_Batch_Job__c.object
<CustomObject>
    <fields>
        <fullName>Date_TimeStamp__c</fullName>
        <description>Used for Opty Share</description>
        <label>Date_TimeStamp</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TimeStamp__c</fullName>
        <description>Used for OptyShare class</description>
        <label>TimeStamp</label>
        <type>DateTime</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Used to store the query and notification email id for batch process.</description>
    <label>Apex Batch Job</label>
</CustomObject>

objects/AT_Workspace__c.object
<CustomObject>
    <fields>
        <fullName>AT_Expected_Book_Date__c</fullName>
        <description>Date AT opportunity is expected to book, may or may not align with Opportunity book date</description>
        <label>Workspace Expected Book Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AT_Expected_Product__c</fullName>
        <description>AT Product Booking value</description>
        <inlineHelpText>Expected Product Booking Revenue Amount in Thousands</inlineHelpText>
        <label>Workspace Expected Product($000)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AT_Forecast_Status__c</fullName>
        <description>AT Opportunity status (Commit, Upside = Forecast, None = Identified opportunity, not yet qualified)</description>
        <label>Workspace Forecast Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Commit</fullName>
                </value>
                <value>
                    <fullName>Upside</fullName>
                </value>
                <value>
                    <fullName>Not Forecastable</fullName>
                    <default>true</default>
                    <label>Not Forecastable</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AT_Team__c</fullName>
        <description>PSS's AT (Region) Team</description>
        <label>Workspace Team</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AT-Asia-Pacific</fullName>
                </value>
                <value>
                    <fullName>AT-EMER</fullName>
                </value>
                <value>
                    <fullName>AT-Japan</fullName>
                </value>
                <value>
                    <fullName>CIS-Canada</fullName>
                </value>
                <value>
                    <fullName>CIS-Central</fullName>
                </value>
                <value>
                    <fullName>CIS-East</fullName>
                </value>
                <value>
                    <fullName>CIS-South</fullName>
                </value>
                <value>
                    <fullName>CIS-SP</fullName>
                </value>
                <value>
                    <fullName>CIS-West</fullName>
                </value>
                <value>
                    <fullName>DC-Canada</fullName>
                </value>
                <value>
                    <fullName>DC-Com Central</fullName>
                </value>
                <value>
                    <fullName>DC-Com East</fullName>
                </value>
                <value>
                    <fullName>DC-Com South</fullName>
                </value>
                <value>
                    <fullName>DC-Com West</fullName>
                </value>
                <value>
                    <fullName>DC-Ent Central</fullName>
                </value>
                <value>
                    <fullName>DC-Ent East</fullName>
                </value>
                <value>
                    <fullName>DC-Ent South</fullName>
                </value>
                <value>
                    <fullName>DC-Ent West</fullName>
                </value>
                <value>
                    <fullName>DC-Federal</fullName>
                </value>
                <value>
                    <fullName>DC-GET</fullName>
                </value>
                <value>
                    <fullName>DC-SLED Central/East</fullName>
                </value>
                <value>
                    <fullName>DC-SLED South/West</fullName>
                </value>
                <value>
                    <fullName>DC-SP</fullName>
                </value>
                <value>
                    <fullName>ET-Digital Media</fullName>
                </value>
                <value>
                    <fullName>ET-HQ</fullName>
                </value>
                <value>
                    <fullName>Physical Security</fullName>
                </value>
                <value>
                    <fullName>Optical-SP</fullName>
                </value>
                <value>
                    <fullName>SA VTG</fullName>
                </value>
                <value>
                    <fullName>Sec/WL-Canada</fullName>
                </value>
                <value>
                    <fullName>Sec-SLED C-E</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AT_Technology__c</fullName>
        <description>Technology represented by this AT Workspace</description>
        <label>Workspace Technology</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CLOUD VIRTUALIZATION</fullName>
                </value>
                <value>
                    <fullName>COLLABORATION</fullName>
                </value>
                <value>
                    <fullName>COMPUTING SYSTEMS</fullName>
                </value>
                <value>
                    <fullName>DIGITAL MEDIA</fullName>
                </value>
                <value>
                    <fullName>ENTERPRISE ROUTING</fullName>
                </value>
                <value>
                    <fullName>IoT</fullName>
                </value>
                <value>
                    <fullName>MOBILITY</fullName>
                </value>
                <value>
                    <fullName>SECURITY</fullName>
                </value>
                <value>
                    <fullName>SP ROUTING</fullName>
                </value>
                <value>
                    <fullName>SP VIDEO INFRA</fullName>
                </value>
                <value>
                    <fullName>SP VIDEO SW &amp; SOLUTIONS</fullName>
                </value>
                <value>
                    <fullName>SWITCHING</fullName>
                </value>
                <value>
                    <fullName>WIRELESS</fullName>
                </value>
                <value>
                    <fullName>Advanced Services</fullName>
                </value>
                <value>
                    <fullName>CCS</fullName>
                </value>
                <value>
                    <fullName>CMS</fullName>
                </value>
                <value>
                    <fullName>ISG-Ecosystems</fullName>
                </value>
                <value>
                    <fullName>Refurbished</fullName>
                </value>
                <value>
                    <fullName>S+CC</fullName>
                </value>
                <value>
                    <fullName>Software</fullName>
                </value>
                <value>
                    <fullName>Technical Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Opportunity associated with the workspace</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Workspaces</relationshipLabel>
        <relationshipName>AT_Workspace</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>PSS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product Sales Specialist (owner of AT Workspace)</description>
        <label>Workspace User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00N30000002BoxqEAC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sync_With_Opportunity__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is checked if PSS Workspace has to be Sync with the Opportunity</description>
        <inlineHelpText>Sync With Opportunity Checkbox to Sync the PSS Workspace with the Opportunity</inlineHelpText>
        <label>Sync With Opportunity</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>forecast_status__c</fullName>
        <description>Forecast Status of the Opportunity associated with the AT workspace</description>
        <formula>TEXT(Opportunity__r.Forecast_Status__c)</formula>
        <label>forecast status</label>
        <type>Text</type>
    </fields>
    <label>Opportunity Workspace</label>
    <nameField>
        <label>Opportunity Workspace Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Workspaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Org_Constant_CS__c.object
<CustomObject>
    <fields>
        <fullName>Non_Production_Value__c</fullName>
        <label>Non Production Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Production_Value__c</fullName>
        <label>Production Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>Org Constant CS</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Organization__c</fullName>
        <label>Organization</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Theatre__c</fullName>
        <inlineHelpText>Please contact GSTS Support to Edit this field</inlineHelpText>
        <label>Theater</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Americas-Canada</fullName>
                </value>
                <value>
                    <fullName>Americas-Global Enterprise Segment</fullName>
                </value>
                <value>
                    <fullName>Americas-LATAM</fullName>
                </value>
                <value>
                    <fullName>Americas-US Commercial</fullName>
                </value>
                <value>
                    <fullName>Americas-US Public Sector</fullName>
                </value>
                <value>
                    <fullName>APJC-APAC</fullName>
                </value>
                <value>
                    <fullName>APJC-Greater China</fullName>
                </value>
                <value>
                    <fullName>APJC-Japan</fullName>
                </value>
                <value>
                    <fullName>EMEAR</fullName>
                </value>
                <value>
                    <fullName>Global Service Provider</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Workspace_Technology__c.object
<CustomObject>
    <fields>
        <fullName>Service_Source__c</fullName>
        <label>Service Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Workspace__c</fullName>
        <label>Opportunity Workspace</label>
        <referenceTo>AT_Workspace__c</referenceTo>
        <relationshipLabel>Workspace Technologies</relationshipLabel>
        <relationshipName>Workspace_Technologies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <description>Opportunity workspace technologies</description>
    <label>Workspace Technology</label>
    <nameField>
        <displayFormat>MT-{0}</displayFormat>
        <label>Workspace Technology Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workspace Technologies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ASWorkspaceSharingBatch_Test.cls
@isTest(seeAllData=true)
private class  ASWorkspaceSharingBatch_Test {

    public static testMethod void testDataToLoad(){
        //Load Org_Constant_CS__c custom settings records from static resource
/*       
        insert new Apex_Batch_Job__c(name='closedate',Date_TimeStamp__c=Date.Today()-5); 
        insert new Apex_Batch_Job__c(name='EngageCaseTimestamp',TimeStamp__c=Date.Today()-5);       
 */      
        //load custom settings
        User u = new User(Id = UserInfo.getUserId());

        List<Profile> pList = [SELECT Id FROM Profile WHERE Name = 'Cisco_ADMIN' OR Name = 'Cisco_Japan' ORDER BY Name ASC limit 2];
        List<User> users = new List<User>();

        For(Integer i=0;i<pList.size();i++){
           User usr = new User(Alias = 'testusr'+(i+1),
                               Email = 'testusr'+(i+1)+'@cisco.com.test',
                               EmailEncodingKey = 'UTF-8',
                               LastName = 'Test'+(i+1),
                               FirstName = 'cecid',
                               Organization__c = 'Test'+(i+1),
                               LanguageLocaleKey = 'en_US',
                               LocaleSidKey = 'en_US',
                               ProfileId = pList[i].Id,
                               CommunityNickname = 'testusr'+(i+1),
                               TimeZoneSidKey = 'America/Los_Angeles',
                               UserName = 'testusr'+(i+1)+'@cisco.com.test',
                               Theatre__c = 'Americas-Canada');
           users.add(usr);
        }
        
        System.runAs (u) {
            List<Org_Constant_CS__c> orgConstant = new List<Org_Constant_CS__c>();
            orgConstant.add(new Org_Constant_CS__c(Name='ServiceOneConnectionID',Non_Production_Value__c='04P0q000000CaSjEAK',Production_Value__c='04P34000000Gn2iEAC'));
//          INSERT orgConstant;
            INSERT users;
        }
    
         PartnerNetworkConnection networkConn =[select Id from PartnerNetworkConnection where ConnectionName = 'Services One' and ConnectionStatus = 'Accepted'];
    //  string networkId = Utilities.getConstant_CS('ServiceOneConnectionID'); 
     
        String ParentRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Parent Opportunity').getRecordTypeId();

        List<Account> accList = new List<Account>(); 
        List<Opportunity> oppList = new List<Opportunity>();
        List<AT_Workspace__c> WorkspaceList = new List<AT_Workspace__c>();
        List<Workspace_Technology__c> WorkspaceTechList = new List<Workspace_Technology__c>();
        
        Account acc = new Account(Name='Acme1', BillingCity='San Francisco'); 
        INSERT acc;
        accList.add(acc);
        accList.addAll([SELECT id, name from Account WHERE id IN(SELECT LocalRecordId FROM PartnerNetworkRecordConnection WHERE ConnectionId = :networkConn.Id AND Status='Sent') LIMIT 3]);
        integer accloopcount =0;
        if(accList.size()==1){
          accloopcount =1;
        }else{
          accloopcount =2;
        }
        
        for(Integer j=0;j<accloopcount ;j++){
        
           if(accList.size()>0){
           
            Opportunity opty = new Opportunity(dealid__c= 'B11'+(j+1),
                                               Name= 'TestT'+(j+1),
                                               AccountId=  accList[j].Id,
                                               StageName= '2 - Qualification',
                                               CloseDate= system.today().adddays(2),
                                               CurrencyIsoCode= 'USD',
                                               expected_product__c= 0,
                                               expected_service__c= 10,
                                               forecast_status__c= 'test',
                                               Non_Standard_Terms_and_Conditions__c = 'None',
                                               recordtypeid= ParentRecordTypeId,
                                               Service_Source__c= 'New',
                                               ownerId= users[0].Id,
                                               Opportunity_Owner_AM__c= users[0].Id,
                                               Close_Probability__c= 75
                                               );       
            INSERT opty;
            
            oppList.add(opty);
            }
        }
        oppList.addAll([SELECT id, name from Opportunity WHERE id IN(SELECT LocalRecordId FROM PartnerNetworkRecordConnection WHERE ConnectionId = :networkConn.Id AND Status='Sent') LIMIT 3]);
  
         integer opploopcount =0;
        if(oppList.size()==1){
          opploopcount =1;
        }else{
          opploopcount =4;
        }
        
        if(accList.size()>1){
          Opportunity phaseOpportunity = new Opportunity(dealid__c= oppList[1].dealid__c ,
                                                       Name= 'TestT2',
                                                       AccountId=  accList[1].Id,
                                                       StageName= '2 - Qualification',
                                                       CloseDate= system.today().adddays(2),
                                                       CurrencyIsoCode= 'USD',
                                                       expected_product__c= 0,
                                                       expected_service__c= 10,
                                                       forecast_status__c= 'test',
                                                       Non_Standard_Terms_and_Conditions__c = 'None', 
                                                       Service_Source__c= 'New',
                                                       ownerId= users[0].Id,
                                                       Opportunity_Owner_AM__c= users[0].Id,
                                                       Close_Probability__c= 75,
                                                       Parent_Id__c= oppList[1].Id
                                                       );
         INSERT phaseOpportunity;      
        }
        for(Integer K=0;k<opploopcount ;k++){
        
         if(oppList.size()>0){
           AT_Workspace__c Workspace = new AT_Workspace__c( AT_Technology__c= 'UC', 
                                                            AT_Expected_Product__c= 1, 
                                                            PSS__c= UserInfo.getUserId(), 
                                                            AT_Expected_Book_Date__c = System.today(), 
                                                            AT_Forecast_Status__c= 'Upside', 
                                                            Opportunity__c= oppList[k].Id, 
                                                            AT_Team__c= 'test', 
                                                            Sync_With_Opportunity__c = true
                                                            ); 
              WorkspaceList.add(Workspace);
           }
        }
        INSERT WorkspaceList;
        
        for(Integer l=0;l<opploopcount ;l++){
          Workspace_Technology__c wrksptech= new Workspace_Technology__c(Workspace__c = WorkspaceList[l].Id, 
                                                                         business_Entity__c = 'CSS-Security Services', 
                                                                         Expected_000__c = 100
                                                                         );
          WorkspaceTechList.add(wrksptech);
       }        
        INSERT WorkspaceTechList;
        
        if(WorkspaceTechList.size()>3){  
                PartnerNetworkRecordConnection networkConnRecord1 =new PartnerNetworkRecordConnection();
                networkConnRecord1 .ConnectionId = networkConn.Id ;
                networkConnRecord1 .LocalRecordId = WorkspaceTechList[3].Id;
                try{
                    insert networkConnRecord1;
                }catch(Exception e){ }  
        }
        Test.StartTest();
            
            ASWorkspaceSharingBatch ASWrksp = new ASWorkspaceSharingBatch();
            Database.executeBatch(ASWrksp);            
            Set<Id> workspIdSet = new Set<Id>();
            Set<String> dealIdSet = new Set<String>();
            
            for(AT_Workspace__c wrksp :[SELECT ID, Opportunity__c FROM AT_Workspace__c Where Id IN :WorkspaceList]){
               workspIdSet.add(wrksp.Id);
            }
            for(Opportunity opp :[SELECT ID, dealid__c FROM Opportunity Where Id IN :OppList]){
               dealIdSet.add(opp.dealid__c);
            }
            
          try{
                ASWrksp.shareWorkspaceTechForSharedWorkspace(workspIdSet, networkConn.Id  );
            }catch(Exception e){}
            try{ 
               ASWrksp.shareRelatedOpty(dealIdSet, networkConn.Id,  new Set<Id>{oppList[1].AccountId});             
              }catch(exception e){
            }   
            Test.StopTest();          
    }   
}