objects/Account.object
<CustomObject>
    <fields>
        <fullName>Theatre__c</fullName>
        <description>Describes which Cisco geographical region the account us managed by.</description>
        <label>Theatre</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>APJ</fullName>
                </value>
                <value>
                    <fullName>EMEAR</fullName>
                </value>
                <value>
                    <fullName>Global Service Provider</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>error_description__c</fullName>
        <label>Status Message</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Channel</fullName>
        <active>true</active>
        <description>Registered Partner Account from PDB (Partner Database)</description>
        <label>Channel</label>
    </recordTypes>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer recordtype for C360</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>EndUser</fullName>
        <active>true</active>
        <description>Existing or Prospective Customer Account</description>
        <label>End-User</label>
    </recordTypes>
</CustomObject>

objects/Multi_Object_Quote__c.object
<CustomObject>
    <fields>
        <fullName>DM_Quote_ID__c</fullName>
        <description>ID of the quotes from DM</description>
        <externalId>true</externalId>
        <label>Quote ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the related Opportunity for the Deal or Quote</description>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>CCW Deals and Quotes</relationshipLabel>
        <relationshipName>Multi_Object_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the Quote that this Deal or Quote is related to</description>
        <label>Quote</label>
        <referenceTo>Quote__c</referenceTo>
        <relationshipLabel>CCW Deals and Quotes</relationshipLabel>
        <relationshipName>CCW_Deals_and_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>CCW deals and Quotes are stored in this object when they are associated to Leads, Target Prospects or Cases. The record is used to attach deal data to Leads Target Prospects and Cases including Deal Status, Deal ID, Quote Net Price, Quote List price</description>
    <label>CCW Deal or Quote</label>
    <nameField>
        <label>Multi Object Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CCW Deals and Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ObjectRecordTypeIds__c.object
<CustomObject>
    <fields>
        <fullName>AccountChannelRecordTypeId__c</fullName>
        <description>This field stores the id of the channel account record type.</description>
        <label>Account Channel RecordTypeId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_PDB_RecordTypeId__c</fullName>
        <description>This is the record type Id of the Partner Provided contact record type.</description>
        <label>Contact PDB RecordTypeId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is used to store the record type ids of account and contact objects.</description>
    <label>Object Record Type Ids</label>
</CustomObject>

objects/Org_Constants__c.object
<CustomObject>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Prod_LT__c</fullName>
        <label>Prod LT</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>URL</fullName>
                    <default>true</default>
                    <label>URL</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>non_prod_value__c</fullName>
        <label>non prod value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>prod_value__c</fullName>
        <label>prod value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Org Constant</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Org Constants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PDI_Collaboration_Countries__c.object
<CustomObject>
    <fields>
        <fullName>Country1__c</fullName>
        <label>Country1</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Country2__c</fullName>
        <label>Country2</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Country3__c</fullName>
        <label>Country3</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Country4__c</fullName>
        <label>Country4</label>
        <type>TextArea</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Used for differentiating PDI Collaboration East and West Countries on case.</description>
    <label>PDI Collaboration Countries</label>
</CustomObject>

objects/ProfileID__c.object
<CustomObject>
    <fields>
        <fullName>Cisco_PSS__c</fullName>
        <description>This field stores the id of the Cisco PSS Profile</description>
        <label>Cisco_PSS</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cisco_Renewals__c</fullName>
        <defaultValue>'00e34000001CQnp'</defaultValue>
        <description>00e34000001CQnp</description>
        <inlineHelpText>00e34000001CQnp</inlineHelpText>
        <label>Cisco_Renewals</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cisco_US_Commercial__c</fullName>
        <description>This field stores the id of the Cisco US Commercial Profile</description>
        <label>Cisco_US_Commercial</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is used to store the profile ids for all the available profiles.</description>
    <label>Profile ID</label>
</CustomObject>

objects/Quote__c.object
<CustomObject>
    <fields>
        <fullName>Integrated_Quote__c</fullName>
        <description>Check whether the quote is integrated or not</description>
        <formula>IF(
DM_Quote_ID__c = Opportunity_Name__r.CCW_BOM_Integrated_Quote_Id__c ,'Yes',
'No'
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Integrated Quote</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <description>Displays the Opportunity Name for the associated Partner Quote</description>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Partner_Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity_Status__c</fullName>
        <description>Displays the Opportunity Status for the associated Partner Quote</description>
        <formula>CASE(Opportunity_Name__r.Opportunity_Status__c, 'Active', 'Active','')</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Status</label>
        <type>Text</type>
    </fields>
    <description>Quote Header information.  Used in related lists.  Quote details stored in PDR.</description>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Additional_User_Permissions__c</fullName>
        <description>Allows permission for additional functionality which are based on User and not by profile.
1)AccountCreateByTerritory: New SBC functionality which allows SBC based on Geo Rules
2)Enable EndUser ACCTCreation : Can Create End-User accounts
3)Enable Lead Conversion : Can Convert leads
4)Enable PDR ACCTCreation : Can Create End-User Account during CCW deal conversion
5)Request Resource : Allows AMs to access SE functionality
6)SE User : Allows SEs to access SE Functionality
7)2028 Visibility:Users that will be refreshed by 2028 black box process
8)NBM Approver : User can set status field of NBM records to 'Screen 3' Approval status</description>
        <label>Additional User Permissions</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>2028 Visibility</fullName>
                </value>
                <value>
                    <fullName>AccountCreateByTerritory</fullName>
                </value>
                <value>
                    <fullName>AcquisitionUser</fullName>
                </value>
                <value>
                    <fullName>Activate Sales Account View</fullName>
                </value>
                <value>
                    <fullName>CCE Enabled</fullName>
                </value>
                <value>
                    <fullName>DSEC360</fullName>
                </value>
                <value>
                    <fullName>DSEC360SAV</fullName>
                </value>
                <value>
                    <fullName>DSEContactIntelligence</fullName>
                </value>
                <value>
                    <fullName>DSECRinSFDC</fullName>
                </value>
                <value>
                    <fullName>DSEFA</fullName>
                </value>
                <value>
                    <fullName>DSEGA</fullName>
                </value>
                <value>
                    <fullName>DSENotification</fullName>
                </value>
                <value>
                    <fullName>DSESWSS</fullName>
                </value>
                <value>
                    <fullName>DSETAC</fullName>
                </value>
                <value>
                    <fullName>Einstein Opportunities</fullName>
                </value>
                <value>
                    <fullName>Enable_ePSS</fullName>
                </value>
                <value>
                    <fullName>Enable_VSS</fullName>
                </value>
                <value>
                    <fullName>Enable EndUser ACCTCreation</fullName>
                </value>
                <value>
                    <fullName>Enable Lead Conversion</fullName>
                </value>
                <value>
                    <fullName>Enable PDR ACCTCreation</fullName>
                </value>
                <value>
                    <fullName>Enable Target Prospect Creation</fullName>
                </value>
                <value>
                    <fullName>GSPO_BDM</fullName>
                </value>
                <value>
                    <fullName>GSSO HD Forecast User</fullName>
                </value>
                <value>
                    <fullName>MCP Prospect Engage</fullName>
                </value>
                <value>
                    <fullName>MCP Prospect Profiler</fullName>
                </value>
                <value>
                    <fullName>NBM Approver</fullName>
                </value>
                <value>
                    <fullName>NextGen Forecasting Pilot User</fullName>
                </value>
                <value>
                    <fullName>QIJanACVPilotUser</fullName>
                </value>
                <value>
                    <fullName>RAE SEP Enabled</fullName>
                </value>
                <value>
                    <fullName>Request Resource</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LnP_TC_Accepted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LnP T&amp;C Accepted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LnP_TC_Reset_Date__c</fullName>
        <label>LnP T&amp;C Reset Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LnP_T_C_Acepted_Date__c</fullName>
        <label>LnP T&amp;C Acepted Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Theatre__c</fullName>
        <inlineHelpText>Please contact GSTS Support to Edit this field</inlineHelpText>
        <label>Theater</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Americas-Canada</fullName>
                </value>
                <value>
                    <fullName>Americas-Global Enterprise Segment</fullName>
                </value>
                <value>
                    <fullName>Americas-LATAM</fullName>
                </value>
                <value>
                    <fullName>Americas-US Commercial</fullName>
                </value>
                <value>
                    <fullName>Americas-US Public Sector</fullName>
                </value>
                <value>
                    <fullName>APJC-APAC</fullName>
                </value>
                <value>
                    <fullName>APJC-Greater China</fullName>
                </value>
                <value>
                    <fullName>APJC-Japan</fullName>
                </value>
                <value>
                    <fullName>EMEAR</fullName>
                </value>
                <value>
                    <fullName>Global Service Provider</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CaseTestMethods.cls
@istest
private class CaseTestMethods{
    
    private static testMethod void test(){
    	Utilities.setIsTestMethod(true);
        Utilities.setValidationSkip(true);        
        //User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        //ProfileID__c profileId = new ProfileID__c(SetupOwnerId=UserInfo.getOrganizationId(), Cisco_US_Commercial__c=profileId);
        Profile profile = [SELECT Id FROM Profile WHERE Name = 'Cisco_Admin' Limit 1];
        Id profileId = profile.id;
        //insert profileId;
        User thisUser = new User(firstName='Test',LastName ='PA Contact', USERNAME='testpa1@cisco.com.sales.test',email='testpa232@cisco.com.test',ALIAS='testpa',COMMUNITYNICKNAME='testpa',ISACTIVE=True,
                             TIMEZONESIDKEY='America/Los_Angeles',LnP_T_C_Acepted_Date__c=Date.Today()+5,LnP_TC_Reset_Date__c=Date.Today()-5,LnP_TC_Accepted__c=true,PROFILEID =profileId ,LANGUAGELOCALEKEY ='en_US',THEATRE__C='APJC-APAC',
                             LOCALESIDKEY ='en_US',EMAILENCODINGKEY='UTF-8',Additional_User_Permissions__c='Enable EndUser ACCTCreation');
        insert thisUser;
        
        system.runAs(thisUser){ 
        ObjectRecordTypeIds__c  testCust = new ObjectRecordTypeIds__c ();
        testCust.AccountChannelRecordTypeId__c = '0123000000004aV';
        testCust.Contact_PDB_RecordTypeId__c='01280000000G6tn';
        insert testCust;
        
        Org_Constants__c os =new Org_Constants__c();
        os.Key__c = 'Oppty: ProfileIds to skip Triggers';
        os.non_prod_value__c = '00e30000000dcbfAAA,00e30000000dfUEAAY,00e30000000eca0AAA,00e30000000qiJjAAI,00e30000000dcbgAAA,00e30000000rrZwAAI';
        os.Prod_LT__c = 'GSTS,Data_Migration,Integration_Echo_Suppression,GSTS_Analyst,ADMIN, PSS';
        os.prod_value__c = '00e30000000dcbfAAA,00e30000000dfUEAAY,00e30000000eca0AAA,00e30000000qiJjAAI,00e30000000dcbgAAA,00e30000000rrZwAAI';
        os.Type__c = 'URL';
        insert os;
        
        
        ProfileID__c profileIds = new ProfileID__c();
        profileIds.Cisco_Renewals__c = '00e34000001CQnp';
        profileIds.Cisco_PSS__c = '00e30000000rrZw';
        insert profileIds; 
        
        PDI_Collaboration_Countries__c  testCountry = new PDI_Collaboration_Countries__c ();
        testCountry.Name =' Testing';
        testCountry.Country1__c = 'West';
        testCountry.Country2__c ='West';
        testCountry.Country3__c ='West';
        testCountry.Country4__c='West';
        insert testCountry;
        }
        Utilities.setIsTestMethod(true);
        
         
             
Id recTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Channel').getRecordTypeId();
        Id caserecTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('PSTS Case').getRecordTypeId();

        
        Account a = new Account(name='TestVC',RecordtypeId = '0123000000004aV');
        insert a;
        Account a1 = new Account(name='TestVC1',RecordtypeId = '0123000000004aV'); 
        insert a1;
        Contact co = new Contact(AccountId = a.Id, LastName = 'Test', Email = 'test@cisco.com' , RecordtypeId = '01280000000G6ti');
        insert co;   
        Contact co1 = new Contact(AccountId = a.Id, LastName = 'Test2', Email = 'test2@cisco.com', RecordtypeId = '01280000000G6ti');
        insert co1;   
       
        // Cisco_TSN User  

        User currentUser = [select id from User where profileid=:Utilities.getTSNProfileId() and isactive=true limit 1];
        // updateCaseCCWDealsSection method
        //Create new opportunity
        //Id RecordTypeIdopportunity = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Global Deal/Opportunity').getRecordTypeId();
        
        /*
        Multi_Object_Quote__c existingCCWRecord = [select id, Opportunity_Name__c from Multi_Object_Quote__c where Opportunity_Name__c != null limit 1];
        Quote__c quote = [select id, Opportunity_Name__c from Quote__c where Opportunity_Name__c != null AND Integrated_Quote__c = 'Yes' limit 1];
        */

       Group gp1=new Group(name='Front Line');
       insert gp1;
       Group gp2=new Group(name='Group2');
       insert gp2;
       Group gp3=new Group(name='Group3');
       insert gp3;
       Group gp4=new Group(name='GVE Tier I');
       insert gp4;
       System.runAs(currentUser){
       GroupMember gm1=new GroupMember(groupId=gp1.id,userorgroupId=currentUser.id);
       insert gm1;
       GroupMember gm2=new GroupMember(groupId=gp2.id,userorgroupId=currentUser.id);
       insert gm2;
       GroupMember gm3=new GroupMember(groupId=gp4.id,userorgroupId=currentUser.id);
       insert gm3;
       GroupMember gm4=new GroupMember(groupId=gp4.id,userorgroupId=currentUser.id);
       insert gm4;
       
       String str = CaseBO.getGroupName(gm4.Id);
     }
       
        System.runAs(currentUser){
          GroupMember gm1=new GroupMember(groupId=gp1.id,userorgroupId=currentUser.id);
          insert gm1;
           
        }
        
        
        Utilities.setValidationSkip(true);//skips validation rules
        // updateCaseCCWDealsSection method
        Id RecordTypeIdopportunity = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Global Deal/Opportunity').getRecordTypeId();
        Account acc= new Account(name='Test Account',BillingCity='San Francisco'); 
        insert acc;
        
        Opportunity opty = new Opportunity(Theater__c = 'Americas-Canada',Name='Test', AccountId = acc.id, StageName='2 - Qualification', CloseDate=System.today() + 50, Expected_Product__c=10.0,
                                                error_description__c='error', DealID__c='1', Opportunity_Status__c='Active', recordtypeId=RecordTypeIdopportunity, Opportunity_Owner_AM__c =thisUser.id,
                                                Competitors__c = 'A10 Networks', 
                                           Is_Product_Quote_Integrated__c = 'Yes', Is_Service_Quote_Integrated__c = 'No', CCW_BOM_Integrated_Quote_Id__c = '1001',Position__c='Americas lrpearso',
                                          CurrencyIsoCode = 'USD'); 
        insert opty;
        //Opportunity_Owner_AM__c =userinfo.getUserId(),
        Quote__c quote = new Quote__c(Opportunity_Name__c=opty.id, DM_Quote_ID__c = '1001');
        insert quote;
        
        Multi_Object_Quote__c existingCCWRecord = new Multi_Object_Quote__c(Opportunity_Name__c=opty.id,Deal_ID__c= opty.DealID__c);
        insert existingCCWRecord;
        
        
        
        Opportunity opty1 = new Opportunity(Theater__c = 'Americas-Canada',Name='Test', AccountId = acc.id, StageName='2 - Qualification', CloseDate=System.today() + 50, Expected_Product__c=10.0,
                                                error_description__c='error', DealID__c='1', Opportunity_Status__c='Active', recordtypeId=RecordTypeIdopportunity, Opportunity_Owner_AM__c =thisUser.id,
                                                Competitors__c = 'A10 Networks', 
                                           Is_Product_Quote_Integrated__c = 'Yes', Is_Service_Quote_Integrated__c = 'No', CCW_BOM_Integrated_Quote_Id__c = '1002',Position__c='Americas lrpearso',
                                          CurrencyIsoCode = 'USD'); 
        insert opty1;
        
        Quote__c quote1 = new Quote__c(Opportunity_Name__c=opty1.id, DM_Quote_ID__c = '1002');
        insert quote1;
        
        Id tsnRecTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('GVE Case').getRecordTypeId();
        Id pstsRecTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('PSTS Case').getRecordTypeId();
        Id phRecTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('PH Case').getRecordTypeId();
        
        //Case c1 = new Case(AccountId = a.Id,RecordtypeId =Utilities.getCasePSTSRecordTypeId(),ContactId = co.Id,status='New');
        Case c1 = new Case(AccountId = a.Id,RecordtypeId =pstsRecTypeId,ContactId = co.Id,status='New');
        //getCasePHRecordTypeId
        c1.web_cco_id__c='TESTccoId1@cisco.com';
        c1.suppliedemail='TESTccoId1@cisco.com';
        insert c1; //PH case
       
        //Case c2 = new Case(AccountId = a.Id,RecordtypeId =Utilities.getCasePSTSRecordTypeId(),ContactId = co.Id);
        Case c2 = new Case(AccountId = a.Id,RecordtypeId =pstsRecTypeId,ContactId = co.Id);
        c2.web_cco_id__c='TESTccoId2@cisco.com';
        c2.suppliedemail='TESTccoId2@cisco.com';
        insert c2; // PDI Case

        //Case c3 = new Case(AccountId = a.Id,RecordtypeId =Utilities.getCaseTSNRecordTypeId(),ContactId = co.Id,Contact_Type__c = 'Partner',Country__c = 'Albania', Origin = 'Web');
        Case c3 = new Case(AccountId = a.Id,RecordtypeId =tsnRecTypeId,ContactId = co.Id,Contact_Type__c = 'Partner',Country__c = 'Albania', Origin = 'Web');
        c3.web_cco_id__c='TESTccoId3@cisco.com';
        c3.suppliedemail='TESTccoId3@cisco.com';
        //c3.ownerId=currentUser.id;
        c3.Architecture__c='Test';
        insert c3; // TSN Case
       
       

        //Automation of CCO ID search
        c1.Web_CCO_ID__c = 'minus';
        AutomationCCOIdSearch.doCCOIdSearch(c1.Id);
        c1.Web_CCO_ID__c = 'tsunilkumar';
        AutomationCCOIdSearch.doCCOIdSearch(c1.Id);
        c1.Web_CCO_ID__c = 'dameyer';
        AutomationCCOIdSearch.doCCOIdSearch(c1.Id);
        
        //May release fix to just moved start test so that governer limit refreshes from line 41
        Test.startTest();

        //Route Web Case
        c1.suppliedemail ='test@cisco.com';
        c1.Case_Language__c = 'English';
        c1.category_PDI__c ='Physical Security';
        c1.country__c ='India';
        List<case> clist1 =  new List<case>();
        clist1.add(c1);
        
        //RouteWebCase.updatePDICase(clist1);

        c1.Case_Language__c = 'Simplified Chinese';
        c1.category_PDI__c = 'Data Center';
        List<case> clist2 =  new List<case>();
        clist2.add(c1);
        //RouteWebCase.updatePDICase(clist2);

        c1.Case_Language__c = 'Portuguese (Brazil)';
        c1.category_PDI__c = 'Smart Grid';
        List<case> clist3 =  new List<case>();
        clist3.add(c1);
        //RouteWebCase.updatePDICase(clist3);

        c1.Case_Language__c = 'Spanish (LATAM)';
        c1.category_PDI__c = 'Collaboration';
        List<case> clist4 =  new List<case>();
        clist4.add(c1);
        //RouteWebCase.updatePDICase(clist4);
        
        //CaseCloseEmailBounce 
        CaseCloseEmailBounce.sendCloseCaseBounceEmail(c1.Id,'test@test.com','SubjectTest','TesttextBody','testFromName'); 
        CaseCloseEmailBounce.sendOwnerEmail(c3.Id,'newuser@test.com','TestName','test@test.com','SubjectTest','TesttextBody'); 
        CaseCloseEmailBounce.sendReplyForDeletedCases('test@test.com','SubjectTest','TesttextBody'); 
       
        // Email Trigger
        EmailMessage msg1 = new EmailMessage(ParentId=c1.Id, FromName = 'Cisco Case Management', Incoming = True, TextBody = 'TestBody' ); 
        Insert msg1;
        EmailMessage msg2 = new EmailMessage(ParentId=c2.Id, FromName = 'Cisco Case Management', Incoming = True, TextBody = 'TestBody' ); 
        Insert msg2;
        EmailMessage msg3 = new EmailMessage(ParentId=c3.Id, FromName = 'Cisco Case Management', Incoming = True, TextBody = 'TestBody' ); 
        Insert msg3;
          
       
       //TSN Prevent Parent Case Close
       Case ch = new Case(Status='New',ParentId=c3.id);
       ch.Architecture__c='Test';
       ch.Assigned_SLA__c = '6 hr';
       insert ch;
       c3.Status = 'Resolved Pending';
       c3.Status_Reason__c='Resolved Successfully';
        try{
            update c3;
        }catch (System.dmlException e1){
            System.assertEquals('Parent case cannot be in Resolved Pending or Closed status when Child cases are open!',e1.getDmlMessage(0));
        } 
       update ch;
       
       //TSN_CaseOwnerSyncWithTeam
      
       ch.ownerId=currentUser.id;
       ch.team__c='Group2';
       update ch;
       try{
       ch.team__c='Group4';
       update ch;
       }catch(Exception exc){}



       //TSN_ChildCase_ParentCase_OwnerEmailIdPopulation
       System.runAs(currentUser)
       {
       //Case c4 = new Case(RecordtypeId =Utilities.getCaseTSNRecordTypeId());
       Case c4 = new Case(RecordtypeId =tsnRecTypeId);
       c4.ownerId=currentUser.id;
       c4.team__c='Group2';
       c4.Origin ='Web';
       c4.Assigned_SLA__c = '4 hr';
       c4.Architecture__c='Test';
       insert c4; // TSN Case
       BusinessHours  bs = caseBO.busHours;
       BusinessHours bhour = CaseBO.getBusinessHours();
       
       //Case ch1 = new Case(ParentId=c4.id,RecordtypeId =Utilities.getCaseTSNRecordTypeId());
           Case ch1 = new Case(ParentId=c4.id,RecordtypeId =tsnRecTypeId);
       ch1.ownerId=currentUser.id;
       ch1.team__c='Group2';
       ch1.Architecture__c='Test';       
       insert ch1;
       List<Case> caseList= new List<Case>();
       caseList.add(c4);
       caseList.add(ch1);
       CaseBO.VcPDBUpdate(caseList);
       caseBO.flsGet(case.Deal_Created_Date__c);
}


   //TSN_Update_Contact_Flags_For_Partner_Contacts
          //Case c4=new Case(AccountId = a.Id,RecordtypeId =Utilities.getCaseTSNRecordTypeId(),ContactId = co.Id);
        Case c4=new Case(AccountId = a.Id,RecordtypeId =tsnRecTypeId,ContactId = co.Id);
          c4.Architecture__c='Test';          
          insert c4;
          c4.contactId=co1.id;
          c4.accountId=a1.id;
          c4.Assigned_SLA__c = '48 hr';
          update c4;

   //PreventCaseDeletion    
     System.runAs(currentUser)
       {
        try{
            delete c4; 
        }
        catch(Exception exc){}
       } 
          
  //UpdateAccountContactByCCOIdContactSearch
          Contact contact1 = new Contact(AccountId = a.Id, LastName = 'Test', Email = 'test@cisco.com' , RecordtypeId = '01280000000G6tn');
          contact1.CCO_ID__c='testUser1,testuser,testuser3';
          contact1.email='testuser@gmail.com';
          insert contact1; 
          
          //Case c5=new Case(RecordtypeId =Utilities.getCaseTSNRecordTypeId());
          Case c5=new Case(RecordtypeId =tsnRecTypeId);
          c5.Web_CCO_ID__c='testuser';
          c5.Origin ='Web';
          c5.suppliedemail='testuser@gmail.com';
          c5.Architecture__c='Test';   
          c5.Assigned_SLA__c = '1 hr';
          //c5.Status = 'New';
          insert c5;
          //mkella
          /*c5.Status = 'Assigned';
          c5.OwnerId = '00580000007kt0u';
          update c5;*/
          
          //Case c6=new Case(RecordtypeId =Utilities.getCasePSTSRecordTypeId());
          Case c6=new Case(RecordtypeId =pstsRecTypeId);
          c6.contactId=co.id;
          c6.Web_CCO_ID__c='testuser6';
          c6.Origin ='Web';
          c6.Opportunity__c = opty1.Id;
          c6.suppliedemail='testuser@gmail.com';
          insert c6;
  
          Case c7=new Case(RecordtypeId =phRecTypeId);
        //Case c7=new Case(RecordtypeId =Utilities.getCasePHRecordTypeId());
          c7.Web_CCO_ID__c='testuser6';
          c7.Origin ='Web';
          c7.suppliedemail='testuser@gmail.com';
          c7.Opportunity__c = opty.Id;
          insert c7;
        
          Id cicRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('CIC Security & Trust Customer Engagement Request').getRecordTypeId();
          Case c8=new Case(recordTypeId =cicRecordTypeId);
          //c8.Web_CCO_ID__c='testuser8';
          //c8.Origin ='Web';
          //c8.suppliedemail='testuser@gmail.com';
          c8.AccountId = a.Id;
          c8.Opportunity__c = opty.Id;
          
          c8.OwnerId = '00580000007kt0u';
          // c8.CreatedById = Utilities.getConstant_CS('ConnectionUserId');
          // c8.Architecture__c='Test';          
          insert c8;
          c8.Status = 'Cancelled';
          update c8;
        
        // Case testCase = c7;
        // List<String> globalTriggers =  Spark_System_Config.listTrigger();
        String caseObjTestId = c7.id;
        String testRoomId   = 'Y2lzY29zcGFyazovL3VzL1JPT00vYmNhMTdkNDAtMjQzNy0xMWU2LTk0NmQtN2Y0YWMxYTQwOWFl';
        String mid          = 'Y2lzY29zcGFyazovL3VzL01FTUJFUlNISVAvYzhkMTNmOWQtYzcxMy00NjE5LWEwMDMtZmMxNDhmOWMyZTU1OjlhY2Y3YTQwLTlmNDAtMTFlNS1iMTcxLTMxMTEzZTM4YzhhMQ';
        
        String uniqueLocalKey = UserInfo.getOrganizationId().left(15)+'_'+caseObjTestId.left(15);
        
        
        Spark_Conversation__c sparkObj = new Spark_Conversation__c();
        sparkObj.Spark_Id__c   = testRoomId;
        sparkObj.ObjectId__c   = caseObjTestId;
        sparkObj.TriggerFields__c = '{"Case.Team__c":"GVE Tier I","Case.Origin":"Email","Case.Status":"Assigned"}';
        // sparkObj.Unique_Key__c = uniqueLocalKey;
        insert sparkObj;
        c7.OwnerId          = '00580000007kt0u';
        c7.Architecture__c  = 'Security'; 
      	update c7;
       // delete c7;
          
        //Utilities.setValidationSkip(true);
        // updateCaseCCWDealsSection method test
        /* Case c8=new Case(RecordtypeId =Utilities.getCaseTSNRecordTypeId());
          c8.Web_CCO_ID__c='testuser8';
          c8.Origin ='Web';
          c8.suppliedemail='testuser@gmail.com';
          c8.Opportunity__c = existingCCWRecord.Opportunity_Name__c;
          c8.Architecture__c='Test'; 
          c8.CreatedById = Utilities.getConstant_CS('ConnectionUserId');
          insert c8; 
        // updateCaseCCWDealsSection method test
          Case c81=new Case(RecordtypeId =Utilities.getCaseTSNRecordTypeId());
          c81.Web_CCO_ID__c='testuser8';
          c81.Origin ='Web';
          c81.suppliedemail='testuser@gmail.com';
          c81.Opportunity__c = opty.Id;
          c81.Architecture__c='Test';          
          insert c81;
        */
          Case c9=new Case(RecordtypeId =tsnRecTypeId);
        //Case c9=new Case(RecordtypeId =Utilities.getCaseTSNRecordTypeId());
          c9.Web_CCO_ID__c='testuser9';
          c9.Origin ='Web';
          c9.suppliedemail='testuser@gmail.com';
          c9.Architecture__c='Test';
          c9.Opportunity__c = opty1.Id;
          c9.Assigned_SLA__c = '24 hr';
          c9.Status = 'New';
                    
          insert c9;
          c9.Status = 'Monitor';
          update c9;
        
        string uId =UserInfo.getUserId();
        List<User> userList = CaseBO.getUserNamesFromId(uId,uId);
       Test.stopTest();
       
    }    
}