objects/Account.object
<CustomObject>
    <fields>
        <fullName>CRName__c</fullName>
        <label>CR Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
                <value>
                    <fullName>BRAZIL</fullName>
                </value>
                <value>
                    <fullName>UNITED STATES</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CEE__c.object
<CustomObject>
    <fields>
        <fullName>CPOC_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CPOC Location is added for CPOC lab request</description>
        <label>CPOC Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Preferred_Lab__c</field>
                <operation>contains</operation>
                <valueField>CEE_Location__c.Name</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CEE_Location__c</referenceTo>
        <relationshipLabel>Customer Engagements &amp; Events (CPOC Location)</relationshipLabel>
        <relationshipName>Customer_Engagements_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country of the CPOC Lab Request Customer</description>
        <formula>TEXT(Primary_Account__r.Country__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Preferred_Lab__c</fullName>
        <description>Location of CPOC Lab Request</description>
        <inlineHelpText>Please select a Preferred Lab and Service Type. You may select either one first. Not all services are offered in all the CPOC Labs.</inlineHelpText>
        <label>Preferred Lab</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CPOC Bangalore</fullName>
                </value>
                <value>
                    <fullName>CPOC London</fullName>
                </value>
                <value>
                    <fullName>CPOC RTP</fullName>
                </value>
                <value>
                    <fullName>CPOC Sydney</fullName>
                </value>
                <value>
                    <fullName>CPOC Tokyo</fullName>
                </value>
                <value>
                    <fullName>CPOC Herndon</fullName>
                </value>
                <value>
                    <fullName>CPOC San Jose</fullName>
                </value>
                <value>
                    <fullName>CPOC POV Assurance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Scheduler_Email__c</fullName>
        <description>Email Id of Primary Schedular and it is related to CPOC lab request.</description>
        <formula>Primary_Scheduler__r.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Scheduler Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Scheduler__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Scheduler</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Customer_Engagement_Scheduler6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Secondary_Scheduler_Email__c</fullName>
        <description>Secondary Schedular of the CPOC Lab Request based on preferred Lab</description>
        <formula>Secondary_Scheduler__r.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Secondary Scheduler Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Scheduler__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Secondary Scheduler</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Customer_Engagement_Scheduler7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type is related to CPOC lab request for Customer</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Service_type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>CPOC Managed</fullName>
                </value>
                <value>
                    <fullName>SE Managed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>This object will store summary level briefing information from CEE. This Object is created to Integrate CEE Applicaiton data with Salesforce.com. It allows users to link CEE Briefings with Accounts in Salesforce.com.</description>
    <label>Customer Engagements &amp; Events</label>
    <nameField>
        <displayFormat>CEE-{000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Engagements &amp; Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Customer_Proof_Of_Concept_CPOC</fullName>
        <active>true</active>
        <description>Customer testing and validation</description>
        <label>Customer Proof Of Concept(CPOC)</label>
    </recordTypes>
</CustomObject>

objects/CEE_Location__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Location_Active__c</fullName>
        <description>Setting to determine visibility of a CEE Location in the CEE application.</description>
        <label>Is Location Active?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Location_Type__c</fullName>
        <label>Location Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>EBC/EC</fullName>
                </value>
                <value>
                    <fullName>Non EBC/EC</fullName>
                </value>
                <value>
                    <fullName>ITCE</fullName>
                </value>
                <value>
                    <fullName>ITCE Cisco</fullName>
                </value>
                <value>
                    <fullName>ITCE Non Cisco</fullName>
                </value>
                <value>
                    <fullName>Tradeshow</fullName>
                </value>
                <value>
                    <fullName>CPOC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Scheduler_Email__c</fullName>
        <inlineHelpText>The Primary Scheduler and Site Contact.</inlineHelpText>
        <label>Primary Scheduler Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Primary_Scheduler__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Scheduler</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CES_Locations_Primary_Scheduler</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Secondary_Scheduler_Email__c</fullName>
        <label>Secondary Scheduler Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Secondary_Scheduler__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Secondary Scheduler</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CES_Locations_Secondary_Scheduler</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>The location details for a given Location, either a Field Sales Office (FSO), Executive Briefing Center (EBC), or Customer Briefing Center provided as part of the Customer Engagement implementation.</description>
    <label>CEE Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CEE Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CPOC_Lab_Request__c.object
<CustomObject>
    <fields>
        <fullName>CPOC_Approval_Process_London__c</fullName>
        <description>CPOC Approval Process London</description>
        <label>CPOC Approval Process London</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CPOC_Approval_RTP_SYDNEY__c</fullName>
        <description>CPOC Approval RTP SYDNEY</description>
        <label>CPOC Approval RTP SYDNEY</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CPOC_Approval__c</fullName>
        <description>CPOC Approval</description>
        <label>CPOC_Approval</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CPOC_RTP_Sydney__c</fullName>
        <description>CPOC RTP Sydney</description>
        <label>CPOC RTP Sydney</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CPOC_Tokyo__c</fullName>
        <description>CPOC Tokyo</description>
        <label>CPOC Tokyo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CPOC_Type__c</fullName>
        <description>CPOC type</description>
        <label>CPOC Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>requested_days_5_plus__c</fullName>
        <description>requested days 5 plus</description>
        <label>requested_days_5_plus</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>CPOC Related custom setting values</description>
    <label>CPOC_Lab_Request</label>
</CustomObject>

objects/CPOC_Personnel__c.object
<CustomObject>
    <fields>
        <fullName>Personnel__c</fullName>
        <description>Engineer available for respective preferred lab</description>
        <label>Personnel</label>
        <referenceTo>Personnel__c</referenceTo>
        <relationshipLabel>CPOC Personnels</relationshipLabel>
        <relationshipName>CPOC_Personnels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>CPOC Personnel</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Personnel Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CPOC Personnels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Personnel__c.object
<CustomObject>
    <fields>
        <fullName>CPOC_Location__c</fullName>
        <description>CPOC Loaction</description>
        <label>CPOC Location</label>
        <referenceTo>CEE_Location__c</referenceTo>
        <relationshipLabel>Personnels</relationshipLabel>
        <relationshipName>CPOC_Personnels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CPOC_Personals</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>This is a Master Object for CPOC Personnel.</description>
    <label>Personnel</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Personnel Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Personnels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CPOCPersonnelEdit_Test.cls
/***************************************************************************************************
Name    : CPOCPersonnelEdit_Test 
Author  : Abinash Das
Purpose : Tests for the Personnel Edit Controller  
Created Date: Jul 8 2016                     
*****************************************************************************************************/

@isTest
private class CPOCPersonnelEdit_Test {

    /*@method: Resource page new test method*/
    static testMethod void personnelTestNew() {
        //Setup Account
        User admin = CEE_TestUtility.getUser('admin', true);
        Account a = null;
        Opportunity o = null;
        
        System.runAs(admin){
            CEE_TestUtility.loadCustomSettings();
            CPOC_Lab_Request__c cpoclabreq = new CPOC_Lab_Request__c();
            cpoclabreq.requested_days_5_plus__c = '5+ days,<1 day';
            cpoclabreq.CPOC_Approval__c = 'CPOC_Approval';
            cpoclabreq.CPOC_Approval_Process_London__c = 'CPOC_Approval_London';
            cpoclabreq.CPOC_Approval_RTP_SYDNEY__c = 'CPOC_Approval_Process_RTP_SYDNEY';
            cpoclabreq.CPOC_RTP_Sydney__c = 'CPOC RTP,CPOC Sydney';
            cpoclabreq.CPOC_Tokyo__c =  'CPOC Tokyo';
            cpoclabreq.CPOC_Type__c = 'Submitted,Hold,Cancelled,Scheduled';
            insert cpoclabreq;
            //Get account
            a = new Account(name='Test End-User Account',CRName__c ='Test End-User Account',RECORDTYPEID='0123000000004aUAAQ',Country__c='UNITED STATES');
            insert a;
           //get opportunity
            o = CEE_TestUtility.getOpty();
            o.accountid = a.id;
            update o;
            
        }
        //Setup location
        CEE_Location__c location = new CEE_Location__c();
        location.Name = 'CPOC Bangalore';
        location.Is_Location_Active__c = 'Yes';
        location.Location_Type__c = 'CPOC';
        User primaryScheduler = CEE_TestUtility.getUser('CPOC'+'1', true);
        User secondScheduler = CEE_TestUtility.getUser('CPOC'+'2', true);
        location.Primary_Scheduler__c = primaryScheduler.id;
        location.Secondary_Scheduler__c = secondScheduler.id;
        location.Primary_Scheduler_Email__c = primaryScheduler.Email;
        location.Secondary_Scheduler_Email__c = secondScheduler.Email;
        insert location;
        
        //Setup Personnel
        Personnel__c ceepersonnel = new Personnel__c();
        ceepersonnel.CPOC_Location__c = location.id;
        ceepersonnel.User__c = primaryScheduler.id;
        insert ceepersonnel;
        
        //Setup CPOC request
        CEE__c cpocrequest = new CEE__c();
        cpocrequest.preferred_lab__c = 'CPOC Bangalore';
        cpocrequest.Service_type__c = 'Custom';
        cpocrequest.Requested_Days__c = '3 days' ;
        cpocrequest.Delivery_Type__c = 'Virtual';
        cpocrequest.Type__c = 'CPOC Managed';
        cpocrequest.Requested_customer_Arrival_Date__c = Datetime.now();
        cpocrequest.CPOC_Start_Date__c = Datetime.now();
        cpocrequest.Number_of_Cisco_Attendees__c = 3;
        cpocrequest.Number_of_Customer_Attendees__c = 3;
        cpocrequest.Number_of_Partner_Attendees__c = 3;
        cpocrequest.Primary_Architecture__c = 'Collaboration';
        cpocrequest.Key_Technology__c = 'Conferencing';
        cpocrequest.SE_Email__c = 'prjangid@cisco.com';
        cpocrequest.SE_Manager_Email__c = 'prjangid@cisco.com';
        cpocrequest.Additional_Email_IDs__c = 'prjangid@cisco.com';
        cpocrequest.Test_Objectives__c = 'Test Data Objectives';
        cpocrequest.Opportunity__c = o.id;
        cpocrequest.Primary_Account__c = a.id;
        cpocrequest.request_status__c = 'Saved, not Submitted';
        test.starttest(); 
        //Record type
                RecordType ceeType = null;
                try{
                     ceeType = [select Id from RecordType where DeveloperName = 'Customer_Proof_Of_Concept_CPOC' and SobjectType = 'CEE__c'];
                     cpocrequest.RecordTypeId = ceeType.Id;
                } catch (Exception e){
                    System.debug('getBriefing - Error fetching record types - ' + e.getStackTraceString());
                }            
        insert cpocrequest;

        //TEST = setup cpoc Room   
        CPOC_Personnel__c cpocpersonnel = new CPOC_Personnel__c();
        cpocpersonnel.CPOC_End_date__c = Datetime.now() + 1;
        cpocpersonnel.CPOC_Start_Date__c = Datetime.now();
        cpocpersonnel.Customer_Engagements_Events__c = cpocrequest.id;
        cpocpersonnel.Personnel__c = ceepersonnel.id;
        insert cpocpersonnel;
         
        
        ApexPages.StandardController stdItem = new ApexPages.StandardController(cpocpersonnel);
        CPOC_PersonnelEditController personnelController = new CPOC_PersonnelEditController(stdItem);
        
        //Utility methods
        personnelController.getPersonnelOptions();
        personnelController.returnPersonalAvaibilityStatus();
        personnelController.doCancel();
        
        //Save
        personnelController.doSave();
      
        try{
        CPOC_Personnel__c cpoc1 = new CPOC_Personnel__c(Customer_Engagements_Events__c = cpocrequest.Id);
        ApexPages.StandardController stdItem1 = new ApexPages.StandardController(cpoc1);
        CPOC_PersonnelEditController personnelController1 = new CPOC_PersonnelEditController(stdItem1);
        personnelController1.getPersonnelOptions();
        personnelController1.doSave();
        personnelController1.selPersonnel = ceepersonnel.id;
        personnelController1.doSave();
        }Catch(Exception e){
        System.debug('Exception Caught' + e);
    }
    }
}