objects/Account.object
<CustomObject>
    <fields>
        <fullName>Theatre__c</fullName>
        <description>Describes which Cisco geographical region the account us managed by.</description>
        <label>Theatre</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>APJ</fullName>
                </value>
                <value>
                    <fullName>EMEAR</fullName>
                </value>
                <value>
                    <fullName>Global Service Provider</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>DRT_Lead__c</fullName>
        <formula>IF
((
NOT
(
ISBLANK 
(TEXT(DRT_Main_Stage__c)))
&amp;&amp;
(
NOT
(TEXT
(DRT_Main_Stage__c) == 'Not a DRT Lead' ||  TEXT(DRT_Sub_Stage__c) == '0B - Send to DMT'))),True,False)</formula>
        <label>DRT Lead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Expected_Product__c</fullName>
        <description>NGCC Phase1:Sales History - This field will store the Expected Product List Amount value and show it in the sales history block</description>
        <formula>IF(Expected_Product_List_Amount__c &lt;= 100000,
   TEXT(Expected_Product_List_Amount__c),
   '100K+')</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expected Product List Amount</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expected_Service__c</fullName>
        <description>NGCC Phase1:Sales History - This field will store the Expected Service List Amount value and show it in the sales history block</description>
        <formula>IF(Expected_Service_List_Amount__c &lt;= 100000,
TEXT(Expected_Service_List_Amount__c),
'100K+')</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expected Service List Amount</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Owner_AM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity Owner AM</description>
        <label>Opportunity Owner AM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunity_Owner_AM</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <businessProcess>NGCC Marketing Lead</businessProcess>
        <description>Prospect Leads from Next Gen Marketing Contact Center</description>
        <label>Prospect</label>
    </recordTypes>
    <recordTypes>
        <fullName>eLeads</fullName>
        <active>true</active>
        <businessProcess>eLeads</businessProcess>
        <description>eLeads integration</description>
        <label>eLeads</label>
    </recordTypes>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Position_1__c</fullName>
        <label>Forecasting Positions</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Theatre__c</fullName>
        <inlineHelpText>Please contact GSTS Support to Edit this field</inlineHelpText>
        <label>Theater</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Americas-Canada</fullName>
                </value>
                <value>
                    <fullName>Americas-Global Enterprise Segment</fullName>
                </value>
                <value>
                    <fullName>Americas-LATAM</fullName>
                </value>
                <value>
                    <fullName>Americas-US Commercial</fullName>
                </value>
                <value>
                    <fullName>Americas-US Public Sector</fullName>
                </value>
                <value>
                    <fullName>APJC-APAC</fullName>
                </value>
                <value>
                    <fullName>APJC-Greater China</fullName>
                </value>
                <value>
                    <fullName>APJC-Japan</fullName>
                </value>
                <value>
                    <fullName>EMEAR</fullName>
                </value>
                <value>
                    <fullName>Global Service Provider</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/NoEPSSOpptyOwnerTest.cls
@isTest(SeeAllData = true)
public class NoEPSSOpptyOwnerTest {
    
    
    
    private static testMethod void test(){
        Profile p = [SELECT Id FROM Profile WHERE Name='Cisco_ADMIN']; 
        User u = new User(Alias = 'standt', Email='standarduser100@cisco.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles',Theatre__c='APJC-APAC', 
                          UserName='standarduser100@cisco.com');
                
        System.runAs(u){
        Id devRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('End-User').getRecordTypeId();
        Date vCloseDate = System.today();
        User currentUser = [select defaultCurrencyIsoCode from User where Id = :UserInfo.getUserId()];
            
        //Query for Pricebook2
        String defaultPricebookId;
        Pricebook2[] pricebook2 = [select id from Pricebook2];
        if(pricebook2 == null || pricebook2.size() == 0){
            Pricebook2 createDefaultPB = new Pricebook2(name='default pricebook', isActive=true);
            insert createDefaultPB;
            defaultPricebookId = createDefaultPB.Id;
        }
        else{
            defaultPricebookId = pricebook2[0].Id;
            
        }
        
        Account acct1 = [select id from account where RecordTypeId=:devRecordTypeId limit 1];
        Opportunity oppty1 = new Opportunity(name='Test1',Accountid=acct1.id, StageName='3 - Proposal',CloseDate= vCloseDate,Competitors__c = 'A10 Networks',Expected_Product__c=2,Pricebook2Id=defaultPricebookId,CurrencyIsoCode=currentUser.defaultCurrencyIsoCode);
        oppty1.Expected_Service__c = 0;
        oppty1.Expected_Product__c = 10;
        insert oppty1;
        }
    }
    
    // Test Method to check the BDR/LDR Flow
     private static testMethod void NGCCUserTest(){
        //Creating NGCC User
        Profile p = [SELECT Id FROM Profile WHERE Name='Cisco_NGCC']; 
        User u = new User(Alias = 'standt', Email='standarduser1034@cisco.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          Position_1__c = 'XYZ',
                          TimeZoneSidKey='America/Los_Angeles',Theatre__c='	Americas-Canada', 
                          UserName='ngccusr1034@cisco.com');
        insert u;
         
        //Setting up LDR/BDR Permission Set
        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'NGCC_DRR'];
        insert new PermissionSetAssignment(AssigneeId = u.id, PermissionSetId = ps.Id);
        
        //Creating AM User
        Profile p1 = [SELECT Id FROM Profile WHERE Name='Cisco_Sales']; 
        User u1 = new User(Alias = 'standt', Email='standarduser1045@cisco.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p1.Id, 
                          TimeZoneSidKey='America/Los_Angeles',Theatre__c='	Americas-Canada', 
                          Position_1__c = 'ABC',
                          UserName='salesusr1045@cisco.com');
        insert u1;
        
            //lxTestDataFactory.createCustomSettings();                
         
        //Creating Opportunity Using BDR/LDR User
        System.runAs(u){

        Id devRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('End-User').getRecordTypeId();
        Date vCloseDate = System.today();
        User currentUser = [select defaultCurrencyIsoCode from User where Id = :UserInfo.getUserId()];
        
        //Query for Pricebook2
        String defaultPricebookId;
        Pricebook2[] pricebook2 = [select id from Pricebook2];
        if(pricebook2 == null || pricebook2.size() == 0){
            Pricebook2 createDefaultPB = new Pricebook2(name='default pricebook', isActive=true);
            insert createDefaultPB;
            defaultPricebookId = createDefaultPB.Id;
        }
        else{
            defaultPricebookId = pricebook2[0].Id;
            
        }
        //added by Kavya
        Id leadRecordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('eLeads').getRecordTypeId();
       
        Lead l1 = new Lead(
            firstName='Test',
            LastName ='Lead', 
            RECORDTYPEID=leadRecordTypeId,
            company='Test End-User Account',
            email='test@test.com.test', 
            LeadSource='eLeads'
        );
        insert l1;
            
        Account acct1 = [select id from account where RecordTypeId=:devRecordTypeId limit 1];
           
        //Get Parent Opportunity Record Type    
        //Id opportunityRecTypeID = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Parent Opportunity').getRecordTypeId(); 
            
        Opportunity oppty1 = new Opportunity(
            name='Test1',
            Accountid=acct1.id, 
            //RECORDTYPEID = opportunityRecTypeID,
            StageName='1 - Prospect',
            CloseDate= vCloseDate,
            Expected_Product__c=2,
            Expected_Service__c = 0,
            Pricebook2Id=defaultPricebookId,
            CurrencyIsoCode=currentUser.defaultCurrencyIsoCode,
            Opportunity_Owner_AM__c = u1.Id,
            DRT_Lead__c = l1.Id
        );
        insert oppty1;
        }
    }
    
}