objects/Account.object
<CustomObject>
    <fields>
        <fullName>Partner_Name__c</fullName>
        <label>Partner Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Partner_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Partner_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A lookup to the Account object for storing the Partner Name</description>
        <label>Partner Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Contact Records (Partner Name)</relationshipLabel>
        <relationshipName>Partner_Contacts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>This object stores the information about the Partner Contacts related to Quotes.</description>
    <label>Partner Contact Record</label>
    <nameField>
        <label>Partner Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Contact Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Partner_Contact_Oppty_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Creates a Master-detail relationship between the Opportunity and Partner Contact. Stores the opportunity related to the partner contact.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quote Contacts</relationshipLabel>
        <relationshipName>Partner_Contacts1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Partner_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the related Partner Contact Record information for the mapping object.</description>
        <label>Partner Contact Record</label>
        <referenceTo>Partner_Contact__c</referenceTo>
        <relationshipLabel>Partner Contacts</relationshipLabel>
        <relationshipName>Partner_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Name__c</fullName>
        <description>Formula field which copies the Partner name for the Partner Contact</description>
        <formula>Partner_Contact__r.Partner_Name__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Partner Name</label>
        <type>Text</type>
    </fields>
    <description>Used to map partner contacts to Opportunities and used as a Oppty related list</description>
    <label>Partner Contact</label>
    <nameField>
        <label>Partner Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Service_Type__c</fullName>
        <description>Added for ISP Mar 09 release to classify the Service Program as AS or TS</description>
        <label>Service Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>TS</fullName>
                </value>
                <value>
                    <fullName>CCS</fullName>
                </value>
                <value>
                    <fullName>CMS</fullName>
                </value>
                <value>
                    <fullName>CSS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quote__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <description>Displays the Opportunity Name for the associated Partner Quote</description>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Partner_Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PartnerAcctId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field stores the Partner Account ID</description>
        <label>Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>Quote Header information.  Used in related lists.  Quote details stored in PDR.</description>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/testmethod4trig.cls
@istest
private class testmethod4trig
{
private static testMethod void test()
{
DATE vCloseDate=system.today();
Pricebookentry[] AS_P=[SELECT product2.id FROM Pricebookentry WHERE IsActive=true AND PRODUCTCODE='Service' AND product2.service_type__c='AS' limit 1];
Pricebookentry[] servASPb = [select Id,CurrencyIsoCode from Pricebookentry where IsActive=true AND PRODUCTCODE='Service'  and CurrencyIsoCode='USD' AND product2id=:AS_P[0].product2id limit 3];
Opportunity newOpportunity1 = new Opportunity(dealid__c='A111',name='Test111',StageName='2 - Qualification',CloseDate= vCloseDate.adddays(2),CurrencyIsoCode='USD',expected_product__c=0,expected_service__c=10,forecast_status__c='Commit',Non_Standard_Terms_and_Conditions__c='None', recordtypeid='0123000000003ykAAA');
insert newOpportunity1;
account newaccount=new account(name='abc');
insert newaccount;
Quote__c testquote = new Quote__c(name='test',Opportunity_Name__c=newOpportunity1.id,PartnerAcctId__c=newaccount.id);
insert testquote;

} 
private static testMethod void test1()
{
DATE vCloseDate=system.today();
account newacc=new account(name='abc');
insert newacc;
Opportunity newOppty = new Opportunity(dealid__c='A111',name='Test111',StageName='2 - Qualification',CloseDate= vCloseDate.adddays(2),CurrencyIsoCode='USD',expected_product__c=0,expected_service__c=10,forecast_status__c='Commit',Non_Standard_Terms_and_Conditions__c='None', recordtypeid='0123000000003ykAAA');
insert newOppty;
Partner_Contact__c pc= new Partner_Contact__c(name='pcname',Partner_Name__c=newacc.id);
insert pc;
Partner_Contact_Oppty_Mapping__c pcom= new Partner_Contact_Oppty_Mapping__c(Partner_Contact__c=pc.id,Opportunity__c=newOppty.id);
insert pcom;
Partner_Contact__c pcu= new Partner_Contact__c(name='pcname1',id=pc.id);
update pcu;
 ID[] updatedContacts = new ID[]{};
updatedContacts.add(pc.id);
PartnerContactFutureClass.updateContactMapping(updatedContacts);
}

}