objects/Account.object
<CustomObject>
    <fields>
        <fullName>Allocated_Partner_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Partner Allocated to the End Customer Account</description>
        <label>Allocated Partner 1</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Allocated Partner 1</relationshipLabel>
        <relationshipName>AllocatedPartner1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Allocated_Partner_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Partner Allocated to the End Customer Account</description>
        <label>Allocated Partner 2</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Allocated Partner 2</relationshipLabel>
        <relationshipName>AllocatedPartner2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Allocated_Partner_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Partner Allocated to the End Customer Account</description>
        <label>Allocated Partner 3</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Allocated Partner 3</relationshipLabel>
        <relationshipName>AllocatedPartner3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Allocated_Partner_4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Partner Allocated to the End Customer Account</description>
        <label>Allocated Partner 4</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Allocated Partner 4</relationshipLabel>
        <relationshipName>AllocatedPartner4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRAddressLine1__c</fullName>
        <label>CR Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRAddressLine2__c</fullName>
        <label>CR Address Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRCity__c</fullName>
        <label>CR City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRCountry__c</fullName>
        <label>CR Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRState__c</fullName>
        <label>CR State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRZipPostalCode__c</fullName>
        <label>CR ZipPostalCode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Incumbent_Partner_Status__c</fullName>
        <formula>IF(OR(ISPICKVAL(Validation_Flag__c,'Yes'),ISPICKVAL(Validation_Flag__c,'')), 

IF((ISPICKVAL( Unallocated_Account__c ,'Yes')  &amp;&amp; (ISBLANK( Allocated_Partner_1__c ) &amp;&amp; ISBLANK( Allocated_Partner_2__c ) &amp;&amp; ISBLANK( Allocated_Partner_3__c )  &amp;&amp; ISBLANK( Allocated_Partner_4__c ) )), 
'RED',

IF((NOT(ISPICKVAL( Unallocated_Account__c ,'Yes'))  &amp;&amp;  NOT(ISPICKVAL( Release_to_Unallocated_Pool__c,'Yes')) &amp;&amp; ((NOT (ISBLANK(Allocated_Partner_1__c )) &amp;&amp;  ISBLANK(Allocated_Partner_2__c ) &amp;&amp; ISBLANK(Allocated_Partner_3__c ) &amp;&amp; ISBLANK(Allocated_Partner_4__c )) || (NOT (ISBLANK(Allocated_Partner_2__c )) &amp;&amp;  ISBLANK(Allocated_Partner_1__c ) &amp;&amp; ISBLANK(Allocated_Partner_3__c ) &amp;&amp; ISBLANK(Allocated_Partner_4__c )) || (NOT (ISBLANK(Allocated_Partner_3__c )) &amp;&amp;  ISBLANK(Allocated_Partner_1__c ) &amp;&amp; ISBLANK(Allocated_Partner_2__c ) &amp;&amp; ISBLANK(Allocated_Partner_4__c )) || (NOT (ISBLANK(Allocated_Partner_4__c )) &amp;&amp;  ISBLANK(Allocated_Partner_1__c ) &amp;&amp; ISBLANK(Allocated_Partner_2__c ) &amp;&amp; ISBLANK(Allocated_Partner_3__c )))),

'GREEN',

IF(NOT(ISPICKVAL( Unallocated_Account__c ,'Yes')  ||  ISPICKVAL( Release_to_Unallocated_Pool__c,'Yes')) &amp;&amp; (NOT (ISBLANK(Allocated_Partner_1__c )) || NOT (ISBLANK(Allocated_Partner_2__c )) || NOT (ISBLANK(Allocated_Partner_3__c )) || NOT (ISBLANK(Allocated_Partner_4__c ))),
'YELLOW','')
))
,
'')</formula>
        <label>Incumbent Partner Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Account_Status__c</fullName>
        <description>Indicates if the selected HQ partner site is still active</description>
        <label>Partner Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active (Registered)</fullName>
                </value>
                <value>
                    <fullName>Inactive (Unregistered)</fullName>
                </value>
                <value>
                    <fullName>Denied Partner List (DPL)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Assignment_Eligible__c</fullName>
        <formula>if(( RecordTypeId ==  '0123000000004aV' &amp;&amp;  (Parent.Partner_360_Program_Count__c &gt; 0  ||  Parent.Partner_Leads_Prospects_Count__c &gt; 0)), 1,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Partner Assignment Eligible</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer recordtype for C360</description>
        <label>Customer</label>
    </recordTypes>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>End_Customer_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created as part of P360 Sep '12 Release. 
Look Up to End Customer Account.</description>
        <label>End Customer Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2)</booleanFilter>
            <errorMessage>The selected Account is not a valid End Customer Account.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>End-User</value>
            </filterItems>
            <filterItems>
                <field>Account.OwnerId</field>
                <operation>notEqual</operation>
                <value>00530000000yzog,00580000001Un7V,0053000000109nk,00530000000z0wq,00580000003Xh5f,00530000000xtmN,00530000001ADkn,00530000000xcnT,00580000003Ftxq,00530000000zZBB,00530000000zZB5,00580000001URNM,00530000000dKAp,00530000000fYnT</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (End Customer Account)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Funding_Source__c</fullName>
        <description>Tag to indicate if it is partner-funded, joint-funded campaign. Entered in UNICA tool
Domain values:
CISCO-FUNDED
PARTNER-FUNDED
JOINT-FUNDED</description>
        <label>Funding Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PARTNER-FUNDED</fullName>
                </value>
                <value>
                    <fullName>CISCO-FUNDED</fullName>
                </value>
                <value>
                    <fullName>JOINT-FUNDED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Lead_Status__c</fullName>
        <description>This field is created for P360 2A Development</description>
        <label>Partner Lead Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Partner Assigned</fullName>
                </value>
                <value>
                    <fullName>Assigned To PSR</fullName>
                </value>
                <value>
                    <fullName>Actively Working</fullName>
                </value>
                <value>
                    <fullName>Deal Created</fullName>
                </value>
                <value>
                    <fullName>Rejected-Invalid Contact</fullName>
                </value>
                <value>
                    <fullName>Rejected-Already Deal</fullName>
                </value>
                <value>
                    <fullName>Rejected-Project Canceled</fullName>
                </value>
                <value>
                    <fullName>Rejected-Lost to Competition</fullName>
                </value>
                <value>
                    <fullName>Rejected-Not My Territory/Account</fullName>
                </value>
                <value>
                    <fullName>Rejected-No Customer Response</fullName>
                </value>
                <value>
                    <fullName>Rejected-Duplicate</fullName>
                </value>
                <value>
                    <fullName>Rejected-No Valid Project</fullName>
                </value>
                <value>
                    <fullName>Closed-Order Through Stock</fullName>
                </value>
                <value>
                    <fullName>Closed-Order Through Disti</fullName>
                </value>
                <value>
                    <fullName>Closed-Order Through Cisco</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>QAPartner__c</fullName>
        <description>Name of the preferred partner.
LTLM integrated field.</description>
        <label>Preferred Partner Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recommended_Mapped_Partners__c</fullName>
        <label>Secondary Partner BEC ID</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/P360_mobility_partner_assign_API.cls
@RestResource(urlMapping='/p360mobility/AssignPartner/*')
global with sharing class P360_mobility_partner_assign_API{

    @HttpGet
    global static Partner_Assign_Response getPartnerList(){
        /*
        Return all records
        String off = RestContext.request.params.get('offset');
        */
        
        //in .mon sandbox
        String channel_recordTypeId = '0123000000004aVAAQ'; 
        
        String lm = RestContext.request.params.get('limit');
        String leadid = RestContext.request.params.get('id');
        String searchString = RestContext.request.params.get('search');
        String country = RestContext.request.params.get('country');
        
        Integer lim = Integer.valueOf((lm==null?'200':lm));
        String queryCondition = (searchString ==null?' ':'AND Name LIKE \'' +searchString+ '%\'');
        String countryCondition = (country==null?' ':' AND CRCountry__c = \''+country+'\' ');
        
        List<Lead> leads = [SELECT Partner_Lead_Status__c, Funding_Source__c, QAPartner__c, Recommended_Mapped_Partners__c, End_Customer_Account__c, End_Customer_Account__r.Incumbent_Partner_Status__c FROM Lead where id = :leadid];

        if(leads.size() < 1){
            return new Partner_Assign_Response('Error', 'Lead not found for your visibility', 0, null);
        }
        Lead lead = leads.get(0);
        
        if('Deal Created'.equals(lead.Partner_Lead_Status__c)){
            return new Partner_Assign_Response('Success', 'Partner cannot be changed for Leads that in "Deal Created" status', 0, null);
        }

        //if partner funded or joint funded        
        if('PARTNER-FUNDED'.equals(lead.Funding_Source__c)||'JOINT-FUNDED'.equals(lead.Funding_Source__c)){
            return new Partner_Assign_Response('Success', 'Partner cannot be changed for Leads that are not Cisco-Funded', 0, null);
        }
        //cisco funded lead that's with End customer account that's GREEN or YELLOW
        if(lead.End_Customer_Account__c != null ){
            if('GREEN'.equals(lead.End_Customer_Account__r.Incumbent_Partner_Status__c)||'YELLOW'.equals(lead.End_Customer_Account__r.Incumbent_Partner_Status__c)){
                Account end_cust= [SELECT id, Allocated_Partner_1__c, Allocated_Partner_2__c, Allocated_Partner_3__c, Allocated_Partner_4__c FROM Account Where id = :lead.End_Customer_Account__c];                      

                List<Account> recommendedPartners = [SELECT id, Name, Phone, Website, CRAddressLine1__c, CRAddressLine2__c, CRCity__c, CRCountry__c, CRState__c, CRZipPostalCode__c FROM Account WHERE id IN (:end_cust.Allocated_Partner_1__c, :end_cust.Allocated_Partner_2__c, :end_cust.Allocated_Partner_3__c, :end_cust.Allocated_Partner_4__c)];
                
                return new Partner_Assign_Response('Success', 'OK' , recommendedPartners.size(),recommendedPartners);
            }
        }
        //Cisco funded lead with no end-customer account or RED account
        
        String soql = 'SELECT id, Name, Phone, Website, CRAddressLine1__c, CRAddressLine2__c, CRCity__c, CRCountry__c, CRState__c, CRZipPostalCode__c  FROM account WHERE Partner_Assignment_Eligible__c > 0 AND Partner_Account_Status__c = \'Active (Registered)\' AND RecordTypeId = \''+channel_recordTypeId+'\' '+ countryCondition +' '+queryCondition+' LIMIT :lim';
        System.Debug(soql);
        List<Account> recommendedPartners = Database.query(soql);
        return new Partner_Assign_Response('Success', 'OK' , recommendedPartners.size(),recommendedPartners);
    }
    
    global class Partner_Assign_Response{
        global String success;
        global String message;
        global Integer total;
        global List<Account> records;
        
        global Partner_Assign_Response(String success, String message, Integer total, List<Account> records) {
            this.success = success;
            this.message = message;
            this.total = total;
            this.records = records;
        }
    }
    
    @isTest(SeeAllData=true)
    public static void testGetPSRUsers(){
    
        
        RestResponse res = new RestResponse();
        
        System.RestContext.request = new RestRequest();
        RestContext.request.requestURI = '/services/apexrest/p360mobility/AssignPartner/';
        RestContext.request.addParameter('offset', '0');
        RestContext.request.addParameter('id', GenericStaticTestData.gettesteLeadRecord().id);
        RestContext.request.addParameter('limit', '200');

        
        Partner_Assign_Response results = P360_mobility_partner_assign_API.getPartnerList();
        
        System.debug('::::results.records is::::'+results.records);
        
        System.assertEquals('Success', results.success);        
    }

}