objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_ID__c</fullName>
        <label>TO BE DELETED Account ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Status__c</fullName>
        <description>This field is used for the reporting to see whether the account is active partner account based on active partner users on it.</description>
        <label>Account Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AddressLine1__c</fullName>
        <label>Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSCSiteID__c</fullName>
        <description>Previously CSC Site ID</description>
        <externalId>true</externalId>
        <label>Party ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
                <value>
                    <fullName>BRAZIL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DUNSNumber__c</fullName>
        <label>zzD&amp;B Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HQ_Party_ID__c</fullName>
        <description>HQ_Party_Id is an identifier coming from CR for an Account.</description>
        <label>HQ Party ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State/Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Account_Group__c.object
<CustomObject>
    <customHelpPage>SalesAccountView_Help_Window</customHelpPage>
    <description>This Object stores FDEV Group information from FDEV</description>
    <label>SalesAccountView</label>
    <nameField>
        <label>Sales Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SalesAccountView</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account_Group_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Account_Group__c</fullName>
        <description>Master Detail field relating to SalesAccountView object</description>
        <label>Sales Account View</label>
        <referenceTo>Account_Group__c</referenceTo>
        <relationshipLabel>End User Account</relationshipLabel>
        <relationshipName>R00N80000002iqXREAY</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Account_ID__c</fullName>
        <description>Master Detail field relating to Account object</description>
        <label>Account ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Account View</relationshipLabel>
        <relationshipName>R00N80000002iqY0EAI</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <description>This object is to create many to many relationship between Account Object and FDEV Account Group object</description>
    <label>Sales Account Relationship</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Account Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Direct_SAV_SuperGroup_Rel__c.object
<CustomObject>
    <fields>
        <fullName>Account_Group__c</fullName>
        <description>Master Detail Field relating to SalesAccountView Object</description>
        <label>SalesAccountView</label>
        <referenceTo>Account_Group__c</referenceTo>
        <relationshipLabel>Super Group</relationshipLabel>
        <relationshipName>Direct_SAV_Super_Group_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Super_Group__c</fullName>
        <description>Master Detail Field relating to Super Group Object</description>
        <label>Super Group</label>
        <referenceTo>Super_Group__c</referenceTo>
        <relationshipLabel>SalesAccount</relationshipLabel>
        <relationshipName>Direct_SAV_Super_Group_Relationships</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <description>This object is to create many to many relationship between Direct Super Group Object and FDEV Account Group object</description>
    <label>Direct SAV Super Group Relationship</label>
    <nameField>
        <displayFormat>DSSGR-{0}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Direct SAV Super Group Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Super_Group__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <description>Super Group Record Type in FDEV</description>
        <label>Sales Credit Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <description>This object will store the FDEV super group information from FDEV</description>
    <label>Super Group</label>
    <nameField>
        <label>Super Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Super Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SuperGroup_Direct_TestMethods.cls
// This class acts as Test Class for Super_Group_Direct_SAV,Super_Group_Direct_Acct, Super_Group_Direct_Oppty , Super_Group_Direct_Export_CTE & Super_Group_Direct_Export_Link_CTE Classes
// Release -- FY'13 Year End Rel 

@istest(SeeAllData=true)
public class SuperGroup_Direct_TestMethods{

    public static ApexPages.StandardController DirectSuperGrpCon = null;
    public static PageReference DirectPageRef = null;
    public static Super_Group__c testDirectSuperGrp = null;
    public static List<Account_Group__c> testSAVList = new List<Account_Group__c>();
    public static List<Account_Group_Relationship__c> testSAVAcctRelList = new List<Account_Group_Relationship__c>();
    public static List<Direct_SAV_SuperGroup_Rel__c> testSuperGrpSAVRelList = new List<Direct_SAV_SuperGroup_Rel__c>();
    public static List<Account> testAcctList = new List<Account>();
    public static List<Opportunity> testOpptyList = new List<Opportunity>();
    
    public static void  init(){
    
    testDirectSuperGrp = new Super_Group__c(Name = 'TestDirectSuper', Type__c='Direct');
    insert testDirectSuperGrp; // Direct Super Group
    
        for(Integer i=0;i<10;i++){
            testSAVList.add(new Account_Group__c(Name='TestSAV'+i));
        }
        insert testSAVList; // Sales Account List
        
        for(Integer i=0;i<10;i++){
            testAcctList.add(new Account(Name='AccountTest'+i, RecordTypeId = '0123000000004aU',Account_Status__c='Active'));
        }
        insert testAcctList; // Account List
             
        for(Integer i=0;i<10;i++){
            testSAVAcctRelList.add(new Account_Group_Relationship__c (Account_Group__c = testSAVList[i].Id, Account_ID__c = testAcctList[i].Id));
        }
        insert testSAVAcctRelList; // Account Grp Relationship List
        
        for(Integer i=0;i<10;i++){
            testSuperGrpSAVRelList.add(new Direct_SAV_SuperGroup_Rel__c (Account_Group__c = testSAVList[i].Id, Super_Group__c = testDirectSuperGrp.Id));
        }
        insert testSuperGrpSAVRelList; // Direct SuperGrp SAV Relationship List
        
        for(Integer i=0;i<10;i++){
            testOpptyList.add(new Opportunity(Name='OpptyTest'+i,Account_Group__c = testSAVList[i].Id, accountId= testAcctList[i].Id,StageName='2 - Qualification',Partner_Expected_Book_Date__c = System.today().adddays(2), CloseDate= System.today().adddays(10),Public_Sector_Funding__c='Economic Stimulus Program'));
        }
        insert testOpptyList; // Opportunity List  
        
        DirectSuperGrpCon = new ApexPages.StandardController(testDirectSuperGrp);
        DirectPageRef = ApexPages.currentPage();
        DirectPageRef.getParameters().put('id',testDirectSuperGrp.Id); 

    }
    
   public static testMethod void  execute_Test(){
        init();
        Test.StartTest();  
        Utilities.setIsTestMethod(true);
        Super_Group_Direct_SAV_CTE_Test();
        Super_Group_Direct_Acct_CTE_Test();
        Super_Group_Direct_Oppty_CTE_Test();
        Super_Group_Direct_Export_CTE_Test();
        Super_Group_Direct_Export_Link_CTE_Test();
        Test.StopTest();
    }  
    
   public static void  Super_Group_Direct_SAV_CTE_Test(){ 
        Super_Group_Direct_SAV_CTE classController = new Super_Group_Direct_SAV_CTE(DirectSuperGrpCon);
        classController.SAVCON = null;     
        classController.sortColumnNameNew = 'Name';
        classController.getAccountGroupRecords();
        classController.OrderData();
        
    }
    
   public static void  Super_Group_Direct_Acct_CTE_Test(){ 
        Super_Group_Direct_Acct_CTE classController = new Super_Group_Direct_Acct_CTE(DirectSuperGrpCon);
        classController.ACCTCON = null;  
        classController.sortColumnNameNew = 'Name';
        classController.SuperGrpAccountData();
        classController.getAccountRecords();
        classController.OrderData();
        classController.Paging('Select Id, Name,Owner.Name,HQ_Party_ID__c,CSCSiteID__c,DUNSNumber__c,AddressLine1__c,City__c,State__c,Country__c from Account order by Name LIMIT 2');
    }
    
   public static void  Super_Group_Direct_Oppty_CTE_Test(){ 
        Super_Group_Direct_Oppty_CTE classController = new Super_Group_Direct_Oppty_CTE(DirectSuperGrpCon);
        classController.OPPTYCON = null;     
        classController.sortColumnNameNew = 'Account.Name';
        classController.getOpptyRecords();
        classController.OrderData();
    }  
        
   public static void  Super_Group_Direct_Export_CTE_Test(){ 
        Super_Group_Direct_Export_CTE classController = new Super_Group_Direct_Export_CTE(DirectSuperGrpCon);
        classController.createOpptyMap();    
        classController.createAcctMap();
        classController.populateSuperGrpInfoList();
    }
    public static void  Super_Group_Direct_Export_Link_CTE_Test(){ 
        Super_Group_Direct_Export_Link_CTE classController = new Super_Group_Direct_Export_Link_CTE(DirectSuperGrpCon);
        classController.Save();    
    }   
}