objects/Account.object
<CustomObject>
    <fields>
        <fullName>Assigned_CSE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Customer Success Engineer added to particular customer (Account) record</description>
        <label>Assigned CSE</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts0Bqy</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer recordtype for C360</description>
        <label>Customer</label>
    </recordTypes>
</CustomObject>

objects/C360ListViewIds__c.object
<CustomObject>
    <fields>
        <fullName>AllCustomers__c</fullName>
        <label>AllCustomers</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Business_Units__c</fullName>
        <label>Customer Business Units</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customers__c</fullName>
        <label>Customers</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>C360_ListViewsSetting</label>
</CustomObject>

classes/MyAssignedCustomersApexController.cls
/************************************************************************************************************************************
Name    : MyAssignedCustomersApexController
Author  : C360 Dev team
Purpose : Contains logic to fetch count of current logged in user customers, business units and accounts in MyAssignedCustomers component
Date    : 02/24/2019
Change History : none
*************************************************************************************************************************************/
public class MyAssignedCustomersApexController {
    //fecth count of Customers, Business unit  based on logged in User
    @AuraEnabled
    public static String MyAssignedCustomers(String loggedInUserId){
        Map<String,String> resultMap = new Map<String,String>();
        Map<String,integer> returnMap = new Map<String,integer>();
        Map<string,List<Account>> accList= new Map<string,List<Account>>();
        
        set<Id> CU =new set<Id>();
        List<Account> aclist = new List<Account>();
        //query to fetch Customer, BU's records 
     
        List<Account> custList = new List<Account>([select id from Account where Assigned_CSE__c =: loggedInUserId and RecordType.Name IN ('Customer') ]);
        List<Account> buList = new List<Account>([select id from Account where Assigned_CSE__c =: loggedInUserId and RecordType.Name IN ('Business Unit') ]);
      
             
        returnMap.put('Customers',custList.size());
        returnMap.put('Customer Business Units',buList.size());
        resultMap.put('data',JSON.serialize(returnMap));
        String listMap = MyAssignedCustomersApexController.getCustomSettingRecord(); 
       	resultMap.put('listView',listMap);
        return JSON.serialize(resultMap);
    }
    
    public static string getCustomSettingRecord(){
        C360ListViewIds__c  custVal = C360ListViewIds__c.getInstance('MyAssignCustomersListViews');  
       	Map<String,String> mapCustListViews = new Map<String,String>();
        mapCustListViews.put('Customers',custVal.Customers__c);
        mapCustListViews.put('Customer Business Units',custVal.Customer_Business_Units__c);
        mapCustListViews.put('ViewAll',custVal.AllCustomers__c);
        
        return JSON.serialize(mapCustListViews);
        
    }
}