objects/Account_Executive_Sponsor__c.object
<CustomObject>
    <fields>
        <fullName>VP_CEC__c</fullName>
        <label>VP CEC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Account Executive Sponsor</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Executive Sponsors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Account_Executive_User__c.object
<CustomObject>
    <fields>
        <fullName>Account_Executive_Sponsor__c</fullName>
        <label>Account Executive Sponsor</label>
        <referenceTo>Account_Executive_Sponsor__c</referenceTo>
        <relationshipLabel>Account Executive Users</relationshipLabel>
        <relationshipName>Account_Executive_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Executive_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Executive User</label>
    <nameField>
        <displayFormat>ESPU-{00000}</displayFormat>
        <label>Executive User</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Executive Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AccountExecSponsorBeforeUpsert_Test.cls
/***************************************************************************************************
Name    : AccountExecSponsorBeforeUpsert_Test 
Author  : Eric Pesch
Purpose : Trigger Tests for the Account_Executive_Sponsor__c object  
Created Date: Dec 1 2014
Modification History: 
Eric Pesch - Jan 5 2015: Added Comments, cleanup                     
*****************************************************************************************************/ 

@isTest
private class AccountExecSponsorBeforeUpsert_Test {
	
	/* @method: Test inserting an Account Executive Sponsor record*/
    private static testMethod void accountESPInsert() {
        Test.startTest();
        Account_Executive_Sponsor__c esp = CEE_TestUtility.getAccountExecutiveSponsor('test', true);
        Test.stopTest();
        
        List<Account_Executive_User__c> espUsers = [select id from Account_Executive_User__c where Account_Executive_Sponsor__c =: esp.Id];        
        //System.assert(true, esp.Id != null); //Validate record was inserted
        //System.assertEquals(4, espUsers.size()); //Validate the associated Users to the record
    }
    
    /* @method: Test updating and removing a User from the Executive Sponsor record*/
    private static testMethod void accountESPUpdate(){
    	Account_Executive_Sponsor__c esp = CEE_TestUtility.getAccountExecutiveSponsor('test', true);
    	User vp = CEE_TestUtility.getUser('vpnew', true);
    	esp.VP_CEC__c = 'vpnew';
    	
        Test.startTest();
        update esp;
        
        esp.VP_CEC__c = 'vpnew';
        update esp;
        Test.stopTest();
        
        //Previous validation tests
        List<Account_Executive_User__c> espUsers = [select id, User__c from Account_Executive_User__c where Account_Executive_Sponsor__c =: esp.Id];        
        //System.assert(true, esp.Id != null);
        //System.assertEquals(4, espUsers.size());
        
        Boolean espVPValid = false;
        for(Account_Executive_User__c user : espUsers){
			if(user.User__c == vp.Id){
				espVPValid = true;
			}        	
        }
        //System.assert(true, espVPValid); //Test to see if VP User was swapped out correctly
    }
}