objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer recordtype for C360</description>
        <label>Customer</label>
    </recordTypes>
</CustomObject>

objects/Agenda_Item__c.object
<CustomObject>
    <fields>
        <fullName>CEE_Attendee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CEE Attendee</label>
        <referenceTo>CEE_Attendee__c</referenceTo>
        <relationshipLabel>Agenda Items</relationshipLabel>
        <relationshipName>Agenda_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Catering_Attendees__c</fullName>
        <description>Number of Attendees accounted for Catering.</description>
        <label>Attendees</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Catering_Department_Code__c</fullName>
        <description>Department to be billed for Catering.</description>
        <label>Department Code</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Catering_Type__c</fullName>
        <description>Type of catering provided for Agenda Item.</description>
        <label>Catering Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Breakfast - Hot Food and Drinks</fullName>
                </value>
                <value>
                    <fullName>Breakfast - Cold Food and Drinks</fullName>
                </value>
                <value>
                    <fullName>Morning Snacks</fullName>
                </value>
                <value>
                    <fullName>Lunch - Hot Food and Drinks</fullName>
                </value>
                <value>
                    <fullName>Lunch - Cold Food and Drinks</fullName>
                </value>
                <value>
                    <fullName>Afternoon Snacks</fullName>
                </value>
                <value>
                    <fullName>Drinks Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <label>Start Date/Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Topic__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Topic</label>
        <referenceTo>Topic__c</referenceTo>
        <relationshipLabel>Agenda Items</relationshipLabel>
        <relationshipName>Agenda_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agenda Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agenda Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Agenda_Room__c.object
<CustomObject>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <defaultValue>Null</defaultValue>
        <label>Start Date/Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Agenda Room</label>
    <nameField>
        <displayFormat>RM-{00000}</displayFormat>
        <label>Room Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agenda Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Briefing_Site__c.object
<CustomObject>
    <description>Additional Field Sales Offices (FSO) attached to Customer Engagement requests.</description>
    <label>Briefing Site</label>
    <nameField>
        <displayFormat>SITE-{00000}</displayFormat>
        <label>Site Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Briefing Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CEE__c.object
<CustomObject>
    <fields>
        <fullName>Primary_FSO__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Primary site is lookup field from CEE Location object, it is related to CPOC lab request.</description>
        <inlineHelpText>Field Sales Office</inlineHelpText>
        <label>Primary Site</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4 AND 6) OR (5)</booleanFilter>
            <errorMessage>The chosen Primary Site does not match the filter criteria of the EBC/EC and Other/FSO Location field.</errorMessage>
            <filterItems>
                <field>$Source.EBC_CBC_Location__c</field>
                <operation>equals</operation>
                <valueField>CEE_Location__c.Name</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.EBC_CBC_Location__c</field>
                <operation>notEqual</operation>
                <value>Other/FSO</value>
            </filterItems>
            <filterItems>
                <field>$Source.EBC_CBC_Location__c</field>
                <operation>equals</operation>
                <value>Other/FSO</value>
            </filterItems>
            <filterItems>
                <field>CEE_Location__c.Is_Location_Active__c</field>
                <operation>equals</operation>
                <value>Yes</value>
            </filterItems>
            <filterItems>
                <field>$User.Id</field>
                <operation>equals</operation>
                <value>005300000010pIr</value>
            </filterItems>
            <filterItems>
                <field>CEE_Location__c.Name</field>
                <operation>notContain</operation>
                <value>CPOC</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CEE_Location__c</referenceTo>
        <relationshipLabel>Customer Engagements &amp; Events (Primary Site)</relationshipLabel>
        <relationshipName>Customer_Engagement_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <defaultValue>DATETIMEVALUE(Today() + 10)</defaultValue>
        <inlineHelpText>Shown in User's Local Timezone</inlineHelpText>
        <label>Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Timezone__c</fullName>
        <description>Timezone picklist field (primarily for ITCE engagements)</description>
        <label>Timezone</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>(UTC-11:00) Samoa Standard Time (Pacific/Pago_Pago)</fullName>
                </value>
                <value>
                    <fullName>(UTC-11:00) Niue Time (Pacific/Niue)</fullName>
                </value>
                <value>
                    <fullName>(UTC-10:00) Hawaii-Aleutian Standard Time (America/Atka)</fullName>
                </value>
                <value>
                    <fullName>(UTC-10:00) Hawaii Standard Time (Pacific/Honolulu)</fullName>
                </value>
                <value>
                    <fullName>(UTC-09:30) Marquesas Time (Pacific/Marquesas)</fullName>
                </value>
                <value>
                    <fullName>(UTC-09:00) Gambier Time (Pacific/Gambier)</fullName>
                </value>
                <value>
                    <fullName>(UTC-09:00) Alaska Daylight Time (America/Anchorage)</fullName>
                </value>
                <value>
                    <fullName>(UTC-08:00) Pitcairn Standard Time (Pacific/Pitcairn)</fullName>
                </value>
                <value>
                    <fullName>(UTC-08:00) Pacific Standard Time (America/Tijuana)</fullName>
                </value>
                <value>
                    <fullName>(UTC-08:00) Pacific Daylight Time (America/Los_Angeles)</fullName>
                </value>
                <value>
                    <fullName>(UTC-07:00) Mountain Standard Time (Mexico/BajaSur)</fullName>
                </value>
                <value>
                    <fullName>(UTC-07:00) Mountain Standard Time (America/Phoenix)</fullName>
                </value>
                <value>
                    <fullName>(UTC-07:00) Mountain Daylight Time (America/Denver)</fullName>
                </value>
                <value>
                    <fullName>(UTC-06:00) Central Standard Time (America/Mexico_City)</fullName>
                </value>
                <value>
                    <fullName>(UTC-06:00) Central Standard Time (America/El_Salvador)</fullName>
                </value>
                <value>
                    <fullName>(UTC-06:00) Central Daylight Time (America/Chicago)</fullName>
                </value>
                <value>
                    <fullName>(UTC-05:00) Eastern Standard Time (America/Panama)</fullName>
                </value>
                <value>
                    <fullName>(UTC-05:00) Eastern Daylight Time (America/New_York)</fullName>
                </value>
                <value>
                    <fullName>(UTC-05:00) Peru Time (America/Lima)</fullName>
                </value>
                <value>
                    <fullName>(UTC-05:00) Eastern Daylight Time (America/Indianapolis)</fullName>
                </value>
                <value>
                    <fullName>(UTC-05:00) Colombia Time (America/Bogota)</fullName>
                </value>
                <value>
                    <fullName>(UTC-04:30) Venezuela Time (America/Caracas)</fullName>
                </value>
                <value>
                    <fullName>(UTC-04:00) Atlantic Daylight Time (Atlantic/Bermuda)</fullName>
                </value>
                <value>
                    <fullName>(UTC-04:00) Chile Summer Time (America/Santiago)</fullName>
                </value>
                <value>
                    <fullName>(UTC-04:00) Atlantic Standard Time (America/Puerto_Rico)</fullName>
                </value>
                <value>
                    <fullName>(UTC-04:00) Atlantic Daylight Time (America/Halifax)</fullName>
                </value>
                <value>
                    <fullName>(UTC-03:30) Newfoundland Daylight Time (America/St_Johns)</fullName>
                </value>
                <value>
                    <fullName>(UTC-03:00) Brasilia Summer Time (America/Sao_Paulo)</fullName>
                </value>
                <value>
                    <fullName>(UTC-03:00) Argentine Summer Time (America/Buenos_Aires)</fullName>
                </value>
                <value>
                    <fullName>(UTC-02:00) South Georgia Standard Time (Atlantic/South_Georgia)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>This object will store summary level briefing information from CEE. This Object is created to Integrate CEE Applicaiton data with Salesforce.com. It allows users to link CEE Briefings with Accounts in Salesforce.com.</description>
    <label>Customer Engagements &amp; Events</label>
    <nameField>
        <displayFormat>CEE-{000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Engagements &amp; Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>OBX</fullName>
        <active>true</active>
        <description>Delivering Demonstrations, Briefings, and Events</description>
        <label>Outcome Based Experience (OBX - formerly EBC)</label>
    </recordTypes>
</CustomObject>

objects/CEE_Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Agenda_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agenda Item</label>
        <referenceTo>Agenda_Item__c</referenceTo>
        <relationshipLabel>CEE Attendees</relationshipLabel>
        <relationshipName>CEE_Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CEE Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CEE Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CEE_Location__c.object
<CustomObject>
    <fields>
        <fullName>Department_Code__c</fullName>
        <label>Department Code</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <description>The location details for a given Location, either a Field Sales Office (FSO), Executive Briefing Center (EBC), or Customer Briefing Center provided as part of the Customer Engagement implementation.</description>
    <label>CEE Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CEE Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CEE_Room__c.object
<CustomObject>
    <fields>
        <fullName>CEE_Location__c</fullName>
        <label>CEE Location</label>
        <referenceTo>CEE_Location__c</referenceTo>
        <relationshipLabel>CEE Rooms</relationshipLabel>
        <relationshipName>CEE_Rooms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>CEE Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CEE Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Topic__c.object
<CustomObject>
    <label>CEE Topic</label>
    <nameField>
        <label>Topic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CEE Topics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CEE_AgendaItemController_Test.cls
/***************************************************************************************************
Name    : CEE_AgendaItemController_Test 
Author  : Eric Pesch
Purpose : Controller test for the Agenda Item Edit Page Controller
Created Date: Dec 1 2014
Modification History: 
Eric Pesch - Jan 5 2015: Added Comments, cleanup                     
*****************************************************************************************************/ 

@isTest
private class CEE_AgendaItemController_Test {
    
    /*@method: Test for a new Agenda Item insert*/
    private static testMethod void agendaItemNewTest() {
        //Variables
        String testRoot = null, testEnv = null;
        
        //Setup Account
        User admin = CEE_TestUtility.getUser('admin', true);
        Account acct = null;
        Opportunity oppty = null;
        
        System.runAs(admin){
            CEE_TestUtility.loadCustomSettings();
            acct = CEE_TestUtility.getAccount('brief', true);
        }
        
        //Setup locations
        CEE_Location__c loc = CEE_TestUtility.getLocation('brief', true, 'EBC/EC');
        CEE_Location__c locB = CEE_TestUtility.getLocation('roomB', true, 'Non EBC/EC');
        CEE_Room__c room = CEE_TestUtility.getRoom('brief', true, loc, false, 6);
        CEE_Room__c roomB = CEE_TestUtility.getRoom('roomB', true, locB, false, 6);
        
        //Setup briefing
        Opportunity opppt =  CEE_TestUtility.getOpty();
        CEE__c briefing = CEE_TestUtility.getBriefing('brief', true, 'OBX', acct, opppt, loc);
        Briefing_Site__c siteB = CEE_TestUtility.getBriefingSite('siteB', true, briefing, locB); //insert alternate location
        
        //Setup topics
        Topic__c topic = CEE_TestUtility.getTopic('brief', true, false);
        Topic__c topicB = CEE_TestUtility.getTopic('brief2', true, false);
        CEE_TestUtility.getOtherTopic();
        
        Test.startTest();
        Agenda_Room__c agendaRoom = CEE_TestUtility.getAgendaRoom('brief', true, briefing, room);
        Agenda_Room__c agendaRoomB = CEE_TestUtility.getAgendaRoom('roomB', true, briefing, roomB);
        
        //Setup agenda item
        Agenda_Item__c agenda = CEE_TestUtility.getAgendaItem('brief', false, briefing, loc, agendaRoom, topic);
        agenda.Topic__c = null;
        agenda.Start_Date_Time__c = null;
        agenda.Catering_Attendees__c = null;
        agenda.Catering_Department_Code__c = null;
        agenda.Catering_Type__c = ' Drinks Only';
       // agenda.Catering_Department_Code__c = siteB.Primary_FSO__r.Department_Code__c;
        
        
        //Get standard parameters
        Test.setCurrentPage(new PageReference(''));
        testRoot = Utilities.getConstant_CS('CEE Outlook URL');
        testEnv = Utilities.getConstant_CS('CEE Environment');
        
        //APEX Page testing
        
        ApexPages.StandardController stdItem = new ApexPages.StandardController(agenda);
        CEE_AgendaItemController agendaItemController = new CEE_AgendaItemController(stdItem);
        List<SelectOption> dynRooms = agendaItemController.getDynRooms();
        agendaItemController.setDynRooms(null);
        
        List<SelectOption> architecture = agendaItemController.getArchitectureOptions();
        agendaItemController.setArchitectureOptions(null);
        
        List<SelectOption> subArch = agendaItemController.getSubArchitectureOptions();
        agendaItemController.setSubArchitectureOptions(null);
        
        List<SelectOption> solution = agendaItemController.getSolutionOptions();
        agendaItemController.setSolutionOptions(null);
        
        agendaItemController.populateCatering();
        
        agendaItemController.populateSites();
        agendaItemController.checkName();
        
        agendaItemController.selectedRooms.add(agendaRoomB.Id);
        
        //Save test
        PageReference save = agendaItemController.doSave();
        //Savenew test
        PageReference saveNew = agendaItemController.doSaveNew();
        
        Test.stopTest();
    }
    
    /*@method: Test for updating an old Agenda Item*/
    private static testMethod void agendaItemUpdateTest() {
        //Variables
        String testRoot = null, testEnv = null;
        
        //Setup Account
        User admin = CEE_TestUtility.getUser('admin', true);
        Account acct = null;
        Opportunity oppty = null;
        
        System.runAs(admin){
            CEE_TestUtility.loadCustomSettings();
            acct = CEE_TestUtility.getAccount('brief', true);
        }
        
        //Setup locations
        CEE_Location__c loc = CEE_TestUtility.getLocation('brief', true, 'EBC/EC');
        //CEE_Location__c locB = CEE_TestUtility.getLocation('roomB', true, 'Non EBC/EC');
        CEE_Room__c room = CEE_TestUtility.getRoom('brief', true, loc, false, 6);
        //CEE_Room__c roomB = CEE_TestUtility.getRoom('roomB', true, locB, false, 6);
        
        //Setup briefing
         Opportunity opppt =  CEE_TestUtility.getOpty();
        CEE__c briefing = CEE_TestUtility.getBriefing('brief', true, 'OBX', acct, opppt, loc);
        //Briefing_Site__c siteB = CEE_TestUtility.getBriefingSite('siteB', true, briefing, locB); //insert alternate location
        
        //Setup topics
        Topic__c topic = CEE_TestUtility.getTopic('brief', true, false);
        //Topic__c topicB = CEE_TestUtility.getTopic('brief2', true, false);
        CEE_TestUtility.getOtherTopic();
        Agenda_Room__c agendaRoom = CEE_TestUtility.getAgendaRoom('brief', true, briefing, room);
        //Agenda_Room__c agendaRoomB = CEE_TestUtility.getAgendaRoom('roomB', true, briefing, roomB);
        
        //Setup agenda item
        Test.startTest();
        Agenda_Item__c agenda = CEE_TestUtility.getAgendaItem('brief', true, briefing, loc, agendaRoom, topic);
        
        //Get standard parameters
        Test.setCurrentPage(new PageReference(''));
        testRoot = Utilities.getConstant_CS('CEE Outlook URL');
        testEnv = Utilities.getConstant_CS('CEE Environment');
        
        //APEX Page testing
         CEE_Attendee__c presenter = CEE_TestUtility.getAttendee('brief', false, briefing, agenda, true);
        ApexPages.StandardController stdItem = new ApexPages.StandardController(agenda);
        CEE_AgendaItemController agendaItemController = new CEE_AgendaItemController(stdItem);
        List<SelectOption> dynRooms = agendaItemController.getDynRooms();
        List<SelectOption> architecture = agendaItemController.getArchitectureOptions();
        List<SelectOption> subArch = agendaItemController.getSubArchitectureOptions();
        List<SelectOption> solution = agendaItemController.getSolutionOptions();
        
        //agendaItemController.selectedRooms.add(agendaRoomB.Id);
        agendaItemController.showFullSolutions = true;
        agendaItemController.checkName();
        
        //Save tests
        PageReference save = agendaItemController.doSave();
        
        //CEEAgendaItemPopupController
        ApexPages.StandardController stdItemBr = new ApexPages.StandardController(briefing);
        CEEAgendaItemPopupController popupController = new CEEAgendaItemPopupController(stdItemBr);
        popupController.loadData();
        popupController.getAgendaitems();
        popupController.deleteAgendaItem();
        
        //Agenda item popup test added 20/8
        PageReference pageRef = Page.CEEAgendaItemModal;
        Test.setCurrentPageReference(pageRef);
        pageRef.getParameters().put('id', agenda.id);
        ApexPages.StandardController stdItem1 = new ApexPages.StandardController(agenda);
        CEEAgendaItemModalController agendaItemController1 = new CEEAgendaItemModalController(stdItem1);
        CEEAgendaItemModalController ceeIgendaCnt = new CEEAgendaItemModalController();
        ceeIgendaCnt.isExcep = true;       
        ceeIgendaCnt.getAgendaItem();
        ceeIgendaCnt.selArchitecture = 'Collaboration';
        ceeIgendaCnt.selSubArchitecture = 'Collaboration Overview';
        ceeIgendaCnt.getSolutionOptions();
        ceeIgendaCnt.getDynRooms();
        ceeIgendaCnt.saveAgendaItem();
        ceeIgendaCnt.showFullSolutions = true;        
       
        List<SelectOption> architecture1 = ceeIgendaCnt.getArchitectureOptions();
        ceeIgendaCnt.setArchitectureOptions(null);
        
        List<SelectOption> subArch1 = ceeIgendaCnt.getSubArchitectureOptions();
        ceeIgendaCnt.setSubArchitectureOptions(null);
        
        List<SelectOption> solution1 = ceeIgendaCnt.getSolutionOptions();
        agendaItemController.setSolutionOptions(null);  
        ceeIgendaCnt.getAgendaItemsData();   
        ceeIgendaCnt.checkName();
        ceeIgendaCnt.getArchitectureOptions();
        ceeIgendaCnt.getSubArchitectureOptions();
        Test.stopTest();
    }
    
    /*@method: Test for updating an old ITCE Agenda Item*/
    private static testMethod void agendaItemUpdateITCETest() {
        //Variables
        String testRoot = null, testEnv = null;
        
        //Setup Account
        User admin = CEE_TestUtility.getUser('admin', true);
        Account acct = null;
        Opportunity oppty = null;

        System.runAs(admin){
            CEE_TestUtility.loadCustomSettings();
            acct = CEE_TestUtility.getAccount('brief', true);
        }
        
        //Setup briefing
        Opportunity opppt =  CEE_TestUtility.getOpty();
        CEE__c briefing = CEE_TestUtility.getBriefing('brief', false, 'Upcoming IT Customer Engagement Briefing', acct, opppt, null);
        briefing.Primary_FSO__c = null;
        briefing.Timezone__c = '(UTC-05:00) Eastern Daylight Time (America/New_York)';
        insert briefing;
        
        //Setup topics
        Topic__c topic = CEE_TestUtility.getTopic('brief', true, false);
        Topic__c topicB = CEE_TestUtility.getTopic('brief2', true, false);
        CEE_TestUtility.getOtherTopic();
        
        //Setup agenda item
        Agenda_Item__c agenda = CEE_TestUtility.getAgendaItem('brief', true, briefing, null, null, topic);
        
        //Get standard parameters
        Test.setCurrentPage(new PageReference(''));
        testRoot = Utilities.getConstant_CS('CEE Outlook URL');
        testEnv = Utilities.getConstant_CS('CEE Environment');
        
        
        
        //APEX Page testing
        Test.startTest();
        ApexPages.StandardController stdItem = new ApexPages.StandardController(agenda);
        CEE_AgendaItemController agendaItemController = new CEE_AgendaItemController(stdItem);
        List<SelectOption> architecture = agendaItemController.getArchitectureOptions();
        List<SelectOption> subArch = agendaItemController.getSubArchitectureOptions();
        List<SelectOption> solution = agendaItemController.getSolutionOptions();
        
        //Save tests
        PageReference save = agendaItemController.doSave();
        Test.stopTest();
    }
    
}