objects/Account.object
<CustomObject>
    <fields>
        <fullName>CRName__c</fullName>
        <label>CR Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
                <value>
                    <fullName>BRAZIL</fullName>
                </value>
                <value>
                    <fullName>UNITED STATES</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Geographic_Region__c</fullName>
        <description>Indicates Cisco Geo Region</description>
        <label>Geographic Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Americas</fullName>
                    <color>#0B6FCE</color>
                    <label>Americas</label>
                </value>
                <value>
                    <fullName>APJ</fullName>
                    <color>#78C953</color>
                    <label>APJ</label>
                </value>
                <value>
                    <fullName>EMEAR</fullName>
                    <color>#E27001</color>
                    <label>EMEAR</label>
                </value>
                <value>
                    <fullName>GC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsEcosystemPartner__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsEcosystemPartner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PDB_BE_GEO_ID__c</fullName>
        <inlineHelpText>The Partner Country identifier sourced from the Partner Database.</inlineHelpText>
        <label>BE GEO ID (PDB)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Account_Status__c</fullName>
        <description>Indicates if the selected HQ partner site is still active</description>
        <label>Partner Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active (Registered)</fullName>
                </value>
                <value>
                    <fullName>Inactive (Unregistered)</fullName>
                </value>
                <value>
                    <fullName>Denied Partner List (DPL)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Company_Status__c</fullName>
        <description>Indicates if the partner at BE GEO level is still active</description>
        <label>Partner Company Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active (Registered)</fullName>
                </value>
                <value>
                    <fullName>Inactive (Unregistered)</fullName>
                </value>
                <value>
                    <fullName>Denied Partner List (DPL)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Channel</fullName>
        <active>true</active>
        <description>Registered Partner Account from PDB (Partner Database)</description>
        <label>Channel</label>
    </recordTypes>
</CustomObject>

objects/ObjectRecordTypeIds__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is used to store the record type ids of account and contact objects.</description>
    <label>Object Record Type Ids</label>
</CustomObject>

objects/Org_Constant_CS__c.object
<CustomObject>
    <fields>
        <fullName>Non_Production_Value__c</fullName>
        <label>Non Production Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Production_Value__c</fullName>
        <label>Production Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>Org Constant CS</label>
</CustomObject>

objects/Org_Constants__c.object
<CustomObject>
    <label>Org Constant</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Org Constants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Partner_Program_Enrollment__c.object
<CustomObject>
    <fields>
        <fullName>PROGRAM_UN_ID__c</fullName>
        <description>Partner Program unique ID (authorisation that requires PPE enrollment)</description>
        <externalId>true</externalId>
        <label>PROGRAM_UN_ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Partner_Company__c</fullName>
        <description>Partner BE GEO name</description>
        <label>Partner Company</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Partner Company</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Program Enrollments</relationshipLabel>
        <relationshipName>Partner_Program_Enrollments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program_Effective_Date__c</fullName>
        <description>Program start date</description>
        <label>Program Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program_Enrollment_Status__c</fullName>
        <description>Indicates if Active or Inactive</description>
        <label>Program Enrollment Status</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Program_Expiration_Date__c</fullName>
        <description>Program Expiry date</description>
        <label>Program Expiration Date</label>
        <type>Date</type>
    </fields>
    <customHelpPage>HelpPartnerProgramEnrollment</customHelpPage>
    <description>This object stores details of the programs enrolled by the partner.</description>
    <label>Partner Program Enrollment</label>
    <nameField>
        <label>Partner Program/Track Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Program Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/EcosystemPartnerSharingBatch_Test.cls
/*
Test Class for EcosystemPartnerSharing
*/
@isTest
public class EcosystemPartnerSharingBatch_Test {
    public static testMethod void testprogramenrollment(){  
        List < sObject > objRecTypeData = Test.loadData(ObjectRecordTypeIds__c.sObjectType,'GlobalTestObjectRecordTypeIds');
        List < sObject > osCSData = Test.loadData(Org_Constants__c.sObjectType,'OrgConstants');
        Org_Constant_CS__c ocs = new Org_Constant_CS__c();
        ocs.name = 'Exclude From PUI and Competitor Popup';
        ocs.Non_Production_Value__c = 'Cisco_ADMIN';
        ocs.Production_Value__c = 'Cisco_ADMIN';
        insert ocs;

        Id RecordTypeIdpartneraccount = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Partner Company').getRecordTypeId();
        Id RecordTypeIdchannelaccount1 = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Channel').getRecordTypeId();
        Id RecordTypeIdchannelaccountend = Schema.SObjectType.Account.getRecordTypeInfosByName().get('End-User').getRecordTypeId();

        Account endCustomerAccount = new Account(name='Test End-User Account',CRName__c ='Test End-User Account',RECORDTYPEID=RecordTypeIdchannelaccountend,Country__c='UNITED STATES');
        insert endCustomerAccount;

        Account a = new Account(name='TestAccount',Partner_Account_Status__c= 'Active (Registered)',Partner_Company_Status__c='Active (Registered)',recordTypeId=RecordTypeIdpartneraccount,Country__c='UNITED STATES',IsEcosystemPartner__c=false );
        Insert a;

        Partner_Program_Enrollment__c PPE = new Partner_Program_Enrollment__c();
        PPE.Name='Cisco Sales Collaboration Platform1';
        PPE.PROGRAM_ENROLLMENT_STATUS__C='Active';
        PPE.PARTNER_COMPANY__C = a.id;

        PPE.Program_Effective_Date__c = system.today()-1;
        PPE.Program_Expiration_Date__c = system.today()+5;
        PPE.PROGRAM_UN_ID__c = '178662201-AUTHORIZATION-ATP-OPCR';
        insert PPE; 
      
        Account channelAccount = new Account(name='Test Channel Account',Partner_Account_Status__c= 'Active (Registered)',Partner_Company_Status__c='Active (Registered)',Type='Distributor',PDB_BE_GEO_ID__c = '2345',parentid=a.Id, RECORDTYPEID=RecordTypeIdchannelaccount1 ,Country__c='UNITED STATES',IsEcosystemPartner__c=true,Geographic_Region__c='APAC');
        insert channelAccount ; 

        User currentUser = [select defaultCurrencyIsoCode,id from User where Id = :UserInfo.getUserId()];                                
        Test.startTest();
            SchedulableContext sc = null;
            EcosystemPartnerSharingSchedule CSCR = new EcosystemPartnerSharingSchedule();
            CSCR.execute(sc);
        Test.stopTest();   
    }
 }