objects/Account.object
<CustomObject>
    <fields>
        <fullName>Theatre__c</fullName>
        <description>Describes which Cisco geographical region the account us managed by.</description>
        <label>Theatre</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>APJ</fullName>
                </value>
                <value>
                    <fullName>EMEAR</fullName>
                </value>
                <value>
                    <fullName>Global Service Provider</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer recordtype for C360</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>EndUser</fullName>
        <active>true</active>
        <description>Existing or Prospective Customer Account</description>
        <label>End-User</label>
    </recordTypes>
</CustomObject>

objects/ObjectRecordTypeIds__c.object
<CustomObject>
    <fields>
        <fullName>Account_Customer_RecordTypeId__c</fullName>
        <label>Account Customer RecordTypeId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is used to store the record type ids of account and contact objects.</description>
    <label>Object Record Type Ids</label>
</CustomObject>

objects/Org_Constants__c.object
<CustomObject>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>prod_value__c</fullName>
        <label>prod value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Org Constant</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Org Constants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProfileID__c.object
<CustomObject>
    <fields>
        <fullName>Cisco_PSS__c</fullName>
        <description>This field stores the id of the Cisco PSS Profile</description>
        <label>Cisco_PSS</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cisco_Renewals__c</fullName>
        <defaultValue>'00e34000001CQnp'</defaultValue>
        <description>00e34000001CQnp</description>
        <inlineHelpText>00e34000001CQnp</inlineHelpText>
        <label>Cisco_Renewals</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is used to store the profile ids for all the available profiles.</description>
    <label>Profile ID</label>
</CustomObject>

objects/Success_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>"Yes"</defaultValue>
        <label>Active</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_BU_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BU NAME</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Success Plans</relationshipLabel>
        <relationshipName>Success_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account Customer RT(Parent) to Success Plan (Child)</description>
        <label>Customer Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Success Plans</relationshipLabel>
        <relationshipName>Success_Plans2</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>Used for C360 Customer Success Program</description>
    <label>Success Plan</label>
    <nameField>
        <label>Success Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Success Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Additional_User_Permissions__c</fullName>
        <description>Allows permission for additional functionality which are based on User and not by profile.
1)AccountCreateByTerritory: New SBC functionality which allows SBC based on Geo Rules
2)Enable EndUser ACCTCreation : Can Create End-User accounts
3)Enable Lead Conversion : Can Convert leads
4)Enable PDR ACCTCreation : Can Create End-User Account during CCW deal conversion
5)Request Resource : Allows AMs to access SE functionality
6)SE User : Allows SEs to access SE Functionality
7)2028 Visibility:Users that will be refreshed by 2028 black box process
8)NBM Approver : User can set status field of NBM records to 'Screen 3' Approval status</description>
        <label>Additional User Permissions</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>2028 Visibility</fullName>
                </value>
                <value>
                    <fullName>AccountCreateByTerritory</fullName>
                </value>
                <value>
                    <fullName>AcquisitionUser</fullName>
                </value>
                <value>
                    <fullName>Activate Sales Account View</fullName>
                </value>
                <value>
                    <fullName>CCE Enabled</fullName>
                </value>
                <value>
                    <fullName>DSEC360</fullName>
                </value>
                <value>
                    <fullName>DSEC360SAV</fullName>
                </value>
                <value>
                    <fullName>DSEContactIntelligence</fullName>
                </value>
                <value>
                    <fullName>DSECRinSFDC</fullName>
                </value>
                <value>
                    <fullName>DSEFA</fullName>
                </value>
                <value>
                    <fullName>DSEGA</fullName>
                </value>
                <value>
                    <fullName>DSENotification</fullName>
                </value>
                <value>
                    <fullName>DSESWSS</fullName>
                </value>
                <value>
                    <fullName>DSETAC</fullName>
                </value>
                <value>
                    <fullName>Einstein Opportunities</fullName>
                </value>
                <value>
                    <fullName>Enable_ePSS</fullName>
                </value>
                <value>
                    <fullName>Enable_VSS</fullName>
                </value>
                <value>
                    <fullName>Enable EndUser ACCTCreation</fullName>
                </value>
                <value>
                    <fullName>Enable Lead Conversion</fullName>
                </value>
                <value>
                    <fullName>Enable PDR ACCTCreation</fullName>
                </value>
                <value>
                    <fullName>Enable Target Prospect Creation</fullName>
                </value>
                <value>
                    <fullName>GSPO_BDM</fullName>
                </value>
                <value>
                    <fullName>GSSO HD Forecast User</fullName>
                </value>
                <value>
                    <fullName>MCP Prospect Engage</fullName>
                </value>
                <value>
                    <fullName>MCP Prospect Profiler</fullName>
                </value>
                <value>
                    <fullName>NBM Approver</fullName>
                </value>
                <value>
                    <fullName>NextGen Forecasting Pilot User</fullName>
                </value>
                <value>
                    <fullName>QIJanACVPilotUser</fullName>
                </value>
                <value>
                    <fullName>RAE SEP Enabled</fullName>
                </value>
                <value>
                    <fullName>Request Resource</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Theatre__c</fullName>
        <inlineHelpText>Please contact GSTS Support to Edit this field</inlineHelpText>
        <label>Theater</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Americas-Canada</fullName>
                </value>
                <value>
                    <fullName>Americas-Global Enterprise Segment</fullName>
                </value>
                <value>
                    <fullName>Americas-LATAM</fullName>
                </value>
                <value>
                    <fullName>Americas-US Commercial</fullName>
                </value>
                <value>
                    <fullName>Americas-US Public Sector</fullName>
                </value>
                <value>
                    <fullName>APJC-APAC</fullName>
                </value>
                <value>
                    <fullName>APJC-Greater China</fullName>
                </value>
                <value>
                    <fullName>APJC-Japan</fullName>
                </value>
                <value>
                    <fullName>EMEAR</fullName>
                </value>
                <value>
                    <fullName>Global Service Provider</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/C360_SuccessPlan_Trigger_HandlerTest.cls
/************************************************************************************************************************************
Name    : C360_SuccessPlan_Trigger_HandlerTest
Author  : C360 Dev team
Purpose : Contains logic to execute test methods of Handler class for success plan object trigger 
Date    : 28/06/2019
Change History : None
*************************************************************************************************************************************/
@isTest
public class C360_SuccessPlan_Trigger_HandlerTest {
    static testMethod void testMethod1() 
    {
        //Creating dataset
        Profile prof = [select id from profile where name LIKE '%Cisco_CustomerSuccess%'];
        User user = new User(Alias = 'newUser', Email='newuser@cisco.com',
                             EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                             LocaleSidKey='en_US', ProfileId = prof.id,
                             TimeZoneSidKey='America/Los_Angeles', UserName='newuser@cisco.com', 
                             Theatre__c = 'Americas-US Commercial', Additional_User_Permissions__c='Enable EndUser ACCTCreation');
        
        insert user;
        
        insert new ObjectRecordTypeIds__c(Account_Customer_RecordTypeId__c=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId());
        insert new ProfileID__c(Cisco_Renewals__c = '11e30000000dcbg', Cisco_PSS__c='22e30000000dcbg');
        insert new Org_Constants__c(Key__c = 'Oppty: ProfileIds to skip Triggers', prod_value__c='prodval');
        
        
        system.runAs(user){
            List<Account> accts = new List<Account>();
            
            Account acc = new Account();
            acc.Name = 'customer acc';
            acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
            insert acc;
            accts.add(acc);
            
            Account acc2 = new Account();
            acc2.Name = 'Bu acc';
            acc2.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Unit').getRecordTypeId();
            acc2.ParentId = acc.Id;
            insert acc2;
            accts.add(acc2);
            
            test.startTest();
            try
            {
                List<Success_Plan__c> SPList = new List<Success_Plan__c>();
                Success_Plan__c sp= new Success_Plan__c();
                sp.Name = 'SP Name';
                sp.Active__c = 'Yes';
                sp.Customer_Name__c = acc.Id;
                sp.Customer_BU_Name__c=acc2.Id;
                insert sp;  
                SPList.add(sp);
                // sp.Customer_BU_Name__c = acc2.Id;
                // update sp;
                Success_Plan__c sp2= new Success_Plan__c();
                sp2.Name = 'SP Name Test';
                sp2.Active__c = 'No';
                sp2.Customer_Name__c = acc.Id;
                sp2.Customer_BU_Name__c = acc2.Id;    
                insert sp2; 
                sp2.Active__c='Yes';
                sp2.Name='Test';
                update sp2;
                SPList.add(sp2);
                
                Success_Plan__c sp3= new Success_Plan__c();
                sp3.Name = 'SP Name';
                sp3.Active__c = 'Yes';
                sp3.Customer_Name__c = acc.Id;
                insert sp3; 
                SPList.add(sp3);
                Success_Plan__c sp4= new Success_Plan__c();
                sp4.Name = 'SP Name Test1';
                sp4.Active__c = 'Yes';
                sp4.Customer_Name__c = acc.Id;
                insert sp4; 
                // sp4.Active__c='Yes';
                // sp4.Name= 'SP Test';
                // update sp4;
                SPList.add(sp4);
            }
            
            catch(Exception e) {
                Boolean expectedExceptionThrown = e.getMessage().contains('A new Success Plan cannot be created for this BU. Please mark any existing active Success Plans as not Active before creating a new Success Plan') ? true : false;
                //   System.Assert(expectedExceptionThrown,true);
                Boolean expectedExceptionThrown1 = e.getMessage().contains('A new Success Plan cannot be created for this customer. Please mark any existing active Success Plans as not Active before creating a new Success Plan') ? true : false;
                //   System.Assert(expectedExceptionThrown1,true);
                Boolean expectedExceptionThrown2 = e.getMessage().contains('Success Plan Name you have selected already exists, Please select another Name for the Success Plan .') ? true : false;
                //   System.Assert(expectedExceptionThrown2,true);
            } 
            
            test.stopTest();            
        }}
    static testMethod void testMethod2() 
    {
        C360_SuccessPlan_Trigger_Handler.processAfterDelete();
        C360_SuccessPlan_Trigger_Handler.processAfterInsert();
        C360_SuccessPlan_Trigger_Handler.processAfterUnDelete();
        C360_SuccessPlan_Trigger_Handler.processAfterUpdate();
        C360_SuccessPlan_Trigger_Handler.processBeforeDelete();
        C360_SuccessPlan_Trigger_Handler.processBeforeUpdate();
    }
}