objects/Account.object
<CustomObject>
    <fields>
        <fullName>Allocated_Partner_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Partner Allocated to the End Customer Account</description>
        <label>Allocated Partner 1</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Allocated Partner 1</relationshipLabel>
        <relationshipName>AllocatedPartner1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Allocated_Partner_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Partner Allocated to the End Customer Account</description>
        <label>Allocated Partner 2</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Allocated Partner 2</relationshipLabel>
        <relationshipName>AllocatedPartner2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Allocated_Partner_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Partner Allocated to the End Customer Account</description>
        <label>Allocated Partner 3</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Allocated Partner 3</relationshipLabel>
        <relationshipName>AllocatedPartner3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Allocated_Partner_4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Partner Allocated to the End Customer Account</description>
        <label>Allocated Partner 4</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Allocated Partner 4</relationshipLabel>
        <relationshipName>AllocatedPartner4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CRName__c</fullName>
        <label>CR Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
                <value>
                    <fullName>BRAZIL</fullName>
                </value>
                <value>
                    <fullName>UNITED STATES</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Expected_Booking_Other__c</fullName>
        <label>Expected Booking Other</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expected_Bookings_Collab_App_000__c</fullName>
        <label>Potential Bookings-Collab App ($000)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expected_Bookings_Collab_Voice_000__c</fullName>
        <label>Potential Bookings-Collab Voice ($000)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expected_Bookings_Data_Center_UCS_000__c</fullName>
        <label>Potential Bookings-Data Center UCS $000</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expected_Bookings_Routing_000__c</fullName>
        <label>Potential Bookings-Routing ($000)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expected_Bookings_Security_000__c</fullName>
        <label>Potential Bookings-Security ($000)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expected_Bookings_Services_000__c</fullName>
        <label>Potential Bookings-Services ($000)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expected_Bookings_Switching_000__c</fullName>
        <label>Potential Bookings-Switching ($000)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expected_Bookings_Telepresence_000__c</fullName>
        <label>Potential Bookings-Telepresence ($000)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expected_Bookings_Wireless_000__c</fullName>
        <label>Potential Bookings-Wireless ($000)</label>
        <precision>16</precision>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Release_to_Unallocated_Pool__c</fullName>
        <description>Flags end customer accounts which can be released to uncovered pool (Shark Pool)</description>
        <label>Release to Unallocated Pool</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                    <color>#FF0000</color>
                    <label>Yes</label>
                </value>
                <value>
                    <fullName>No</fullName>
                    <color>#78C953</color>
                    <label>No</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unallocated_Account__c</fullName>
        <description>Flags end customer accounts that are not allocated to any partner.</description>
        <label>Unallocated Account</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                    <color>#FF0000</color>
                    <label>Yes</label>
                </value>
                <value>
                    <fullName>No</fullName>
                    <color>#78C953</color>
                    <label>No</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Wallet_Collab_Applications__c</fullName>
        <label>Wallet-Collab Applications ($000)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Wallet_Data_Center_UCS_000__c</fullName>
        <description>Current Fiscal Year Data Center UCS  wallet in thousands per Customer Intelligence data source for the end customer</description>
        <label>Wallet-Data Center UCS ($000)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Wallet_Other_000__c</fullName>
        <description>Current Fiscal Year Other wallet in thousands per Customer Intelligence data source for the end customer</description>
        <label>Wallet-Other ($000)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Wallet_Routing_000__c</fullName>
        <description>Current Fiscal Year Routing  wallet in thousands per Customer Intelligence data source for the end customer</description>
        <label>Wallet-Routing ($000)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Wallet_Security_000__c</fullName>
        <description>Current Fiscal Year Security  wallet in thousands per Customer Intelligence data source for the end customer</description>
        <label>Wallet-Security ($000)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Wallet_Services_000__c</fullName>
        <label>Wallet-Services ($000)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Wallet_Switching_000__c</fullName>
        <description>Current Fiscal Year Switching  wallet in thousands per Customer Intelligence data source for the end customer</description>
        <label>Wallet-Switching ($000)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Wallet_Unified_Communications_000__c</fullName>
        <description>Current Fiscal Year Unified Communications  wallet in thousands per Customer Intelligence data source for the end customer</description>
        <label>Wallet-Collab Voice ($000)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Wallet_Video_000__c</fullName>
        <description>Current Fiscal Year Video wallet in thousands per Customer Intelligence data source for the end customer</description>
        <label>Wallet-Telepresence ($000)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Wallet_Wireless_000__c</fullName>
        <description>Current Fiscal Year Wireless  wallet in thousands per Customer Intelligence data source for the end customer</description>
        <label>Wallet-Wireless ($000)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Channel</fullName>
        <active>true</active>
        <description>Registered Partner Account from PDB (Partner Database)</description>
        <label>Channel</label>
    </recordTypes>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer recordtype for C360</description>
        <label>Customer</label>
    </recordTypes>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Partner_Admin_Roles__c</fullName>
        <description>Displays all the admin roles for the various channels tools assigned to the partner contact</description>
        <label>Partner Admin Roles</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/LnP_Constants__c.object
<CustomObject>
    <fields>
        <fullName>Archive_Days__c</fullName>
        <description>This field will hold the number which determine the Archive lead period for LnP.</description>
        <label>Archive Days</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reset_Date__c</fullName>
        <description>This field will hold the date when the LnP TnC are last reset.</description>
        <label>Reset Date</label>
        <type>Date</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This custom setting will hold the static values for LnP</description>
    <label>LnP_Constants</label>
</CustomObject>

classes/SCP_Communities_leadFilter_Test.cls
@isTest
public class SCP_Communities_leadFilter_Test {
  /***************/
    static testMethod void myUnitTest() {
        
        // Create Org_Constant_CS__c custom settings data
        String timestamp = String.valueOf(Datetime.now().getTime());
        UtilUnitTest.loadAllStaticData();
        String channelAccountRecTypeId = [Select Id,Name, DeveloperName from RecordType where sobjecttype='Account' and Name = 'Channel'].Id;        
        LnP_Constants__c lnpC = new LnP_Constants__c();
        lnpC.Archive_Days__c = 180;
        lnpC.Reset_Date__c = system.today();
        insert lnpC;
        
        // Get PA record
        user pauser1 = GenericStaticTestData.gettestPAUserRecord();
        Contact c = GenericStaticTestData.gettestPartnerProvidedPAContactRecord();
        c.Partner_Admin_Roles__c = 'PARTNER_LED_APP_ADMIN,PARTNER_LED_APP_USER';
        update c;
        string roleName = pauser1.UserRole.name;
        
        user psruser1 = GenericStaticTestData.gettestPSRUserRecord();
        psruser1.LanguageLocaleKey = 'en_US';
        
        //update psruser1;
        Contact c2 = GenericStaticTestData.gettestPartnerProvidedPSRContactRecord();
        c2.Partner_Admin_Roles__c = 'PARTNER_LED_APP_USER';
        update c2;
        
        // Get End customer account
        Account eca =new Account();
        eca = GenericStaticTestData.getTestEndUserAccountRecordRed();
        eca.Name = 'testec'+timestamp;
        eca.Unallocated_Account__c = 'Yes';
        eca.Release_to_Unallocated_Pool__c = 'Yes';
        eca.RecordTypeId = '0123000000004aUAAQ';
        eca.CRName__c = 'testec CRName'+timestamp;
        eca.Country__c='UNITED STATES';
        eca.Industry = 'Center/ISPs';
        eca.Wallet_Wireless_000__c = 20 ;
        eca.Wallet_Video_000__c = 20 ;
        eca.Wallet_Unified_Communications_000__c = 20 ;
        eca.Wallet_Switching_000__c = 20 ;
        eca.Wallet_Services_000__c = 20 ;
        eca.Wallet_Security_000__c = 20 ;
        eca.Wallet_Routing_000__c = 20 ;
        eca.Wallet_Other_000__c = 20 ;
        eca.Wallet_Data_Center_UCS_000__c = 20 ;
        eca.Wallet_Collab_Applications__c = 20 ;
        eca.Wallet_Unified_Communications_000__c = 20 ;
        eca.Wallet_Wireless_000__c = 20 ;
        eca.Expected_Bookings_Wireless_000__c = 40 ;
        eca.Expected_Bookings_Telepresence_000__c = 40 ;
        eca.Expected_Bookings_Switching_000__c = 40 ;
        eca.Expected_Bookings_Services_000__c = 40 ;
        eca.Expected_Bookings_Security_000__c = 40 ;
        eca.Expected_Bookings_Routing_000__c = 40 ;
        eca.Expected_Bookings_Data_Center_UCS_000__c = 40 ;
        eca.Expected_Bookings_Collab_Voice_000__c = 40 ;
        eca.Expected_Bookings_Collab_App_000__c = 40 ;
        eca.Expected_Booking_Other__c = 40 ;
        eca.Allocated_Partner_1__c = null;
        eca.Allocated_Partner_2__c = null;
        eca.Allocated_Partner_3__c = null;
        eca.Allocated_Partner_4__c = null;
       // eca.OwnerId = pauser1.Id;
        update eca;
        
        List<Sobject> l3 = Test.loadData( SCP_Communities_LeadFilter_Columns__c.SobjectType, 'SCP_LeadFilter_Columns_data' );
        List<sObject> orgCS = Test.loadData(Org_Constant_CS__c.sobjectType, 'OrgConstantCS_data') ;
          System.runAs(pauser1) {           
            Id partnerAccountId = GenericStaticTestData.gettestChannelAccountRecord1().Id;
            Lead testLead = new Lead(firstName='Test Manual',LastName ='Lead', RECORDTYPEID='0123000000004aSAAQ', Partner_Lead_Status__c = 'Partner Assigned',LeadSource='test',company='Test End-User Account',email='test@test.com.test', Channel_Partner__c = partnerAccountId);
            insert testLead;
           
            SCP_Communities_listviews__c viewRec2 = SCP_Communities_listviews__c.getValues('My Newly Assigned Leads');
            User_Preference__c   usp = new User_Preference__c(view_id__c = viewRec2.id, user__c = pauser1.id, Columns_Sort_Order__c='Partner Status~~asc',Selected_column_order__c='Partner Status');
            insert usp; 
            
            Test.startTest();            
            SCP_Communities_leadFilter_CT leadcon = new SCP_Communities_leadFilter_CT();
            PageReference pageRef = Page.SCP_Communities_leadFilter;            
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('view', 'newleads');
            leadCon.getSearchPageUrl();
            leadCon.toggelSelectAll();
            leadCon.massUpdate();           
            leadCon.clearFields();
            leadCon.AssignPartnerName(channelAccountRecTypeId);
            SCP_Communities_listviews__c viewRec1 = SCP_Communities_listviews__c.getValues('My Newly Assigned Leads');
            SCP_Communities_leadFilter_CT.getListViewStatus(viewRec1.Id);
            LeadCon.getViewListComponent();
            
            // Testing SCP_Communiiteis_LeadFilter_Clone page            
            SCP_Communities_leadFilter_CT_Clone leadcon1 = new SCP_Communities_leadFilter_CT_Clone();
            PageReference pageRef1 = Page.SCP_Communities_leadFilter_Clone;         
            Test.setCurrentPage(pageRef1);
            ApexPages.currentPage().getParameters().put('view', 'newleads');
            leadCon1.getSearchPageUrl();            
            leadCon1.massUpdate();           
            leadCon1.clearFields();
            leadCon1.AssignPartnerName(channelAccountRecTypeId);
            SCP_Communities_leadFilter_CT_Clone.getListViewStatus(viewRec1.Id);
            LeadCon1.getViewListComponent();
            leadCon1.getDataTableComponent();
            leadCon1.getGirdHeaderlocal('Industry');
            leadCon1.refresh();
            leadCon1.sObjectName='';
            leadCon1.country='usa';            
            List<String> mPickVals1= new List<String>{'VIEW','SCB'};
            leadCon1.getMultiPickSelectedValue(mPickVals1);
            List<String> mPickVals= new List<String>{'ALL','SCB'};
            leadCon1.getMultiPickSelectedValue(mPickVals);
            //leadCon1.isPSR=false;
            
            string strId = [select id from SCP_Communities_listviews__c where name='My Newly Assigned Leads' and objectType__c = 'Lead'].Id;
            User_Preference__c usPref = new User_Preference__c(View_Id__c=strId,User__c=userinfo.getUserId(),Selected_column_order__c='Lead Source;City',Columns_Sort_Order__c = 'Date Added~~desc;Lead Source~~asc');
            insert usPref;            
            leadCon1.getDataTableComponent();            
            leadCon1.first();           
            Boolean isHasNext = leadCon1.hasNext;
            Boolean isHasPrevious = leadCon1.hasPrevious;
            leadCon1.next();
            leadCon1.previous();
            leadCon1.last();
            leadCon1.setPageNum();            
            if( ! leadCon1.pageRecords.isEmpty() ) {
                leadCon1.pageRecords[0].isSelected = true;
                leadCon1.toggelPSR();
            }
            
            Integer totalPages = leadCon1.totalPages;            
            leadCon1.cancelMassUpdate();
            leadCon1.selectedView = strId;
            Boolean isMYNL = leadCon1.isNewlyAssignedLeads;
            leadCon1.getDataTableComponent();
            
            leadCon1.assignPSRs();
            leadCon1.pageRecords[0].leadRec.Partner_Lead_Status__c = 'Partner Assigned';
            leadCon1.AssignPartnerName(partnerAccountId);
            leadCon1.checkForExistingCookie();
            leadCon1.clearAsignPSRFields();
            
            leadCon1.pageRecords[0].isSelected = true;
            SCP_Communities_PSRBulk_CT psr = leadCon1.getPsr();
            psr.psr1_Id = userInfo.getUserId();
            leadCon1.assignPSRs();
            leadCon1.getViewSettingsUrl();
            Component.Apex.SelectList viewList = leadCon1.getViewListComponent();
            leadCon1.setViewList(viewList);
            SCP_Communities_leadFilter_CT_Clone.getListViewStatus(strId);
            lead rec = leadCon1.pageRecords[0].leadRec;
            rec.Partner_Lead_Status__c = 'Assigned to PSR';
            leadCon1.pageRecords[0].isSelected = true;
            leadCon1.updateStatus(rec);
            leadCon1.enableMassEdit('Actively Working');     
            leadCon1.massUpdate();
            leadCon1.getIsChekAccesLead();
            SCP_Communities_leadFilter_CT_Clone.updateTC();
            System.debug('********* Exception : ' +ApexPages.getMessages() );

            leadCon1.cancelMassUpdate();
            String userLang = leadCon1.Userlang;
            String cecId = leadCon1.CCOId;
            String currentUserAccId = leadCon1.Currentuseraccount;
            leadCon1.doSearch();
            SCP_Communities_listviews__c viewRec3 = SCP_Communities_listviews__c.getValues('My Archived Leads');
            SCP_Communities_leadFilter_CT.getListViewStatus(viewRec3.Id);
            SCP_Communities_leadFilter_CT_Clone.getListViewStatus(viewRec3.Id);
            leadCon1.doSearch();
            SCP_Communities_listviews__c viewRec4 = SCP_Communities_listviews__c.getValues('All Active Leads');
            SCP_Communities_leadFilter_CT.getListViewStatus(viewRec4.Id);
            SCP_Communities_leadFilter_CT_Clone.getListViewStatus(viewRec4.Id);
            leadCon1.doSearch();
            User_Preference__c usPref1 = new User_Preference__c(View_Id__c=strId,User__c=userinfo.getUserId(),Selected_column_order__c='Lead Source;PSR 1',Columns_Sort_Order__c = 'Date Added~~desc;Lead Source~~asc');
            insert usPref1;            
            leadCon1.getDataTableComponent();            
            Test.stopTest();           
        }
    }
    
    static testMethod void myUnitTest_WITHOUTORGCONSTENTDATA() {
    
        LnP_Constants__c lnpC = new LnP_Constants__c();
        lnpC.Archive_Days__c = 180;
        lnpC.Reset_Date__c = system.today();
        insert lnpC;
        
        // Create Org_Constant_CS__c custom settings data
        String timestamp = String.valueOf(Datetime.now().getTime());
        UtilUnitTest.loadAllStaticData();
        String channelAccountRecTypeId = [Select Id,Name, DeveloperName from RecordType where sobjecttype='Account' and Name = 'Channel'].Id;

        // Get PA record
        user pauser1 = GenericStaticTestData.gettestPAUserRecord();
        Contact c = GenericStaticTestData.gettestPartnerProvidedPAContactRecord();
        c.Partner_Admin_Roles__c = 'PARTNER_LED_APP_ADMIN,PARTNER_LED_APP_USER';
        update c;
        string roleName = pauser1.UserRole.name;
        
        user psruser1 = GenericStaticTestData.gettestPSRUserRecord();
        psruser1.LanguageLocaleKey = 'en_US';        
        Contact c2 = GenericStaticTestData.gettestPartnerProvidedPSRContactRecord();
        c2.Partner_Admin_Roles__c = 'PARTNER_LED_APP_USER';
        update c2;
        
        // Get End customer account
        Account eca =new Account();
        eca = GenericStaticTestData.getTestEndUserAccountRecordRed();
        eca.Name = 'testec'+timestamp;
        eca.Unallocated_Account__c = 'Yes';
        eca.Release_to_Unallocated_Pool__c = 'Yes';
        eca.RecordTypeId = '0123000000004aUAAQ';
        eca.CRName__c = 'testec CRName'+timestamp;
        eca.Country__c='UNITED STATES';
        eca.Industry = 'Center/ISPs';
        eca.Wallet_Wireless_000__c = 20 ;
        eca.Wallet_Video_000__c = 20 ;
        eca.Wallet_Unified_Communications_000__c = 20 ;
        eca.Wallet_Switching_000__c = 20 ;
        eca.Wallet_Services_000__c = 20 ;
        eca.Wallet_Security_000__c = 20 ;
        eca.Wallet_Routing_000__c = 20 ;
        eca.Wallet_Other_000__c = 20 ;
        eca.Wallet_Data_Center_UCS_000__c = 20 ;
        eca.Wallet_Collab_Applications__c = 20 ;
        eca.Wallet_Unified_Communications_000__c = 20 ;
        eca.Wallet_Wireless_000__c = 20 ;
        eca.Expected_Bookings_Wireless_000__c = 40 ;
        eca.Expected_Bookings_Telepresence_000__c = 40 ;
        eca.Expected_Bookings_Switching_000__c = 40 ;
        eca.Expected_Bookings_Services_000__c = 40 ;
        eca.Expected_Bookings_Security_000__c = 40 ;
        eca.Expected_Bookings_Routing_000__c = 40 ;
        eca.Expected_Bookings_Data_Center_UCS_000__c = 40 ;
        eca.Expected_Bookings_Collab_Voice_000__c = 40 ;
        eca.Expected_Bookings_Collab_App_000__c = 40 ;
        eca.Expected_Booking_Other__c = 40 ;
        eca.Allocated_Partner_1__c = null;
        eca.Allocated_Partner_2__c = null;
        eca.Allocated_Partner_3__c = null;
        eca.Allocated_Partner_4__c = null;
      //  eca.OwnerId = pauser1.Id;
        update eca;
        
        List<Sobject> l3 = Test.loadData( SCP_Communities_LeadFilter_Columns__c.SobjectType, 'SCP_LeadFilter_Columns_data' );
        System.runAs(pauser1) {
            Id partnerAccountId = GenericStaticTestData.gettestChannelAccountRecord1().Id;
            user pauser3 = GenericStaticTestData.gettestPAUserRecord();
            Lead testLead = new Lead(firstName='Test Manual',LastName ='Lead', RECORDTYPEID='0123000000004aSAAQ', Partner_Lead_Status__c = 'Actively Working',LeadSource='test',company='Test End-User Account',email='test@test.com.test', Channel_Partner__c = partnerAccountId, PSR_1__c = pauser3.id);
            insert testLead;
            Test.startTest();
            // Testing SCP_Communiites_LeadFilter page
            SCP_Communities_leadFilter_CT leadcon = new SCP_Communities_leadFilter_CT();
            PageReference pageRef = Page.SCP_Communities_leadFilter;            
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('view', 'newleads');
            leadCon.getSearchPageUrl();
            leadCon.toggelSelectAll();
            leadCon.massUpdate();           
            leadCon.clearFields();
            leadCon.AssignPartnerName(channelAccountRecTypeId);
            SCP_Communities_listviews__c viewRec1 = SCP_Communities_listviews__c.getValues('My Newly Assigned Leads');
            SCP_Communities_leadFilter_CT.getListViewStatus(viewRec1.Id);
            LeadCon.getViewListComponent();
            
            SCP_Communities_leadFilter_CT_Clone leadcon1 = new SCP_Communities_leadFilter_CT_Clone();
            PageReference pageRef1 = Page.SCP_Communities_leadFilter_Clone;         
            Test.setCurrentPage(pageRef1);
            ApexPages.currentPage().getParameters().put('view', 'newleads');
            leadCon1.getSearchPageUrl();            
            leadCon1.massUpdate();           
            leadCon1.clearFields();
            leadCon1.AssignPartnerName(channelAccountRecTypeId);
            SCP_Communities_leadFilter_CT_Clone.getListViewStatus(viewRec1.Id);
            LeadCon1.getViewListComponent();
            leadCon1.getDataTableComponent();            
            leadCon1.refresh();
            
            string strId = [select id from SCP_Communities_listviews__c where name='My Newly Assigned Leads' and objectType__c = 'Lead'].Id;
            User_Preference__c usPref = new User_Preference__c(View_Id__c=strId,User__c=userinfo.getUserId(),Selected_column_order__c='Lead Source;City',Columns_Sort_Order__c = 'Date Added~~desc;Lead Source~~asc');
            insert usPref;            
            leadCon1.getDataTableComponent();            
            leadCon1.first();           
            Boolean isHasNext = leadCon1.hasNext;
            Boolean isHasPrevious = leadCon1.hasPrevious;
            leadCon1.next();
            leadCon1.previous();
            leadCon1.last();
            leadCon1.setPageNum();            
            if( ! leadCon1.pageRecords.isEmpty() ) {
                leadCon1.pageRecords[0].isSelected = true;
                leadCon1.toggelPSR();
            }
            
            Integer totalPages = leadCon1.totalPages;            
            leadCon1.cancelMassUpdate();
            leadCon1.selectedView = strId;
            leadCon1.getDataTableComponent();            
            leadCon1.assignPSRs();
            //leadCon1.pageRecords[0].leadRec.Partner_Lead_Status__c = 'Partner Assigned';
            leadCon1.AssignPartnerName(partnerAccountId);
            leadCon1.checkForExistingCookie();
            leadCon1.clearAsignPSRFields();
            
            //leadCon1.pageRecords[0].isSelected = true;
            SCP_Communities_PSRBulk_CT psr = leadCon1.getPsr();
            psr.psr1_Id = userInfo.getUserId();
            leadCon1.assignPSRs();
            
           /* lead rec = leadCon1.pageRecords[0].leadRec;
            rec.Partner_Lead_Status__c = 'Assigned to PSR';
            leadCon1.pageRecords[0].isSelected = true;
            leadCon1.updateStatus(rec);*/
            leadCon1.enableMassEdit('Actively Working');     
            leadCon1.massUpdate();
            System.debug('********* Exception : ' +ApexPages.getMessages() );

            leadCon1.cancelMassUpdate();
            String userLang = leadCon1.Userlang;
            String cecId = leadCon1.CCOId;
            String currentUserAccId = leadCon1.Currentuseraccount;
            Test.stopTest();                        
        }
    }    
  /*************/
}