objects/Account.object
<CustomObject>
    <fields>
        <fullName>Theatre__c</fullName>
        <description>Describes which Cisco geographical region the account us managed by.</description>
        <label>Theatre</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>APJ</fullName>
                </value>
                <value>
                    <fullName>EMEAR</fullName>
                </value>
                <value>
                    <fullName>Global Service Provider</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ProfileID__c.object
<CustomObject>
    <fields>
        <fullName>Cisco_US_Commercial__c</fullName>
        <description>This field stores the id of the Cisco US Commercial Profile</description>
        <label>Cisco_US_Commercial</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is used to store the profile ids for all the available profiles.</description>
    <label>Profile ID</label>
</CustomObject>

objects/Resource_Request_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <description>This Field defines the opportunity for which the request was raised</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Resource Requests and Assignments</relationshipLabel>
        <relationshipName>Requests_and_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Resource_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This Field defines the name of the resource assigned to the request</description>
        <label>Resource</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Resource_Requests_and_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Resource_Status__c</fullName>
        <description>This field defines the status of the Requested Resource.</description>
        <label>Resource Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Declined - Approved</fullName>
                </value>
                <value>
                    <fullName>Declined - Pending</fullName>
                </value>
                <value>
                    <fullName>Direct Assignment</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>This object is used to store SE Requests and SE Assignments from the SE Workspace</description>
    <label>Resource Request/Assignment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Resource Request/Assignments Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Requests and Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Additional_User_Permissions__c</fullName>
        <description>Allows permission for additional functionality which are based on User and not by profile.
1)AccountCreateByTerritory: New SBC functionality which allows SBC based on Geo Rules
2)Enable EndUser ACCTCreation : Can Create End-User accounts
3)Enable Lead Conversion : Can Convert leads
4)Enable PDR ACCTCreation : Can Create End-User Account during CCW deal conversion
5)Request Resource : Allows AMs to access SE functionality
6)SE User : Allows SEs to access SE Functionality
7)2028 Visibility:Users that will be refreshed by 2028 black box process
8)NBM Approver : User can set status field of NBM records to 'Screen 3' Approval status</description>
        <label>Additional User Permissions</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>2028 Visibility</fullName>
                </value>
                <value>
                    <fullName>AccountCreateByTerritory</fullName>
                </value>
                <value>
                    <fullName>AcquisitionUser</fullName>
                </value>
                <value>
                    <fullName>Activate Sales Account View</fullName>
                </value>
                <value>
                    <fullName>CCE Enabled</fullName>
                </value>
                <value>
                    <fullName>DSEC360</fullName>
                </value>
                <value>
                    <fullName>DSEC360SAV</fullName>
                </value>
                <value>
                    <fullName>DSEContactIntelligence</fullName>
                </value>
                <value>
                    <fullName>DSECRinSFDC</fullName>
                </value>
                <value>
                    <fullName>DSEFA</fullName>
                </value>
                <value>
                    <fullName>DSEGA</fullName>
                </value>
                <value>
                    <fullName>DSENotification</fullName>
                </value>
                <value>
                    <fullName>DSESWSS</fullName>
                </value>
                <value>
                    <fullName>DSETAC</fullName>
                </value>
                <value>
                    <fullName>Einstein Opportunities</fullName>
                </value>
                <value>
                    <fullName>Enable_ePSS</fullName>
                </value>
                <value>
                    <fullName>Enable_VSS</fullName>
                </value>
                <value>
                    <fullName>Enable EndUser ACCTCreation</fullName>
                </value>
                <value>
                    <fullName>Enable Lead Conversion</fullName>
                </value>
                <value>
                    <fullName>Enable PDR ACCTCreation</fullName>
                </value>
                <value>
                    <fullName>Enable Target Prospect Creation</fullName>
                </value>
                <value>
                    <fullName>GSPO_BDM</fullName>
                </value>
                <value>
                    <fullName>GSSO HD Forecast User</fullName>
                </value>
                <value>
                    <fullName>MCP Prospect Engage</fullName>
                </value>
                <value>
                    <fullName>MCP Prospect Profiler</fullName>
                </value>
                <value>
                    <fullName>NBM Approver</fullName>
                </value>
                <value>
                    <fullName>NextGen Forecasting Pilot User</fullName>
                </value>
                <value>
                    <fullName>QIJanACVPilotUser</fullName>
                </value>
                <value>
                    <fullName>RAE SEP Enabled</fullName>
                </value>
                <value>
                    <fullName>Request Resource</fullName>
                </value>
                <value>
                    <fullName>SE User</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LnP_TC_Accepted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LnP T&amp;C Accepted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LnP_TC_Reset_Date__c</fullName>
        <label>LnP T&amp;C Reset Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LnP_T_C_Acepted_Date__c</fullName>
        <label>LnP T&amp;C Acepted Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Notification_Entity__c</fullName>
        <label>Notification Entity</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Notification_Platform__c</fullName>
        <label>Notification Platform</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Notification_Platform</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Notification_Preference__c</fullName>
        <label>Notification Preference</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Daily Digest</fullName>
                    <default>true</default>
                    <label>Daily Digest</label>
                </value>
                <value>
                    <fullName>Real Time</fullName>
                    <isActive>false</isActive>
                    <label>Real Time</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reporting_Manager_Level_1_cec__c</fullName>
        <label>Reporting Manager Level 1 cec</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Theatre__c</fullName>
        <inlineHelpText>Please contact GSTS Support to Edit this field</inlineHelpText>
        <label>Theater</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Americas-Canada</fullName>
                </value>
                <value>
                    <fullName>Americas-Global Enterprise Segment</fullName>
                </value>
                <value>
                    <fullName>Americas-LATAM</fullName>
                </value>
                <value>
                    <fullName>Americas-US Commercial</fullName>
                </value>
                <value>
                    <fullName>Americas-US Public Sector</fullName>
                </value>
                <value>
                    <fullName>APJC-APAC</fullName>
                </value>
                <value>
                    <fullName>APJC-Greater China</fullName>
                </value>
                <value>
                    <fullName>APJC-Japan</fullName>
                </value>
                <value>
                    <fullName>EMEAR</fullName>
                </value>
                <value>
                    <fullName>Global Service Provider</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/Notification_Platform.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>WebEx Teams</fullName>
    </customValue>
    <masterLabel>Notification Platform</masterLabel>
</GlobalValueSet>

classes/OpptyMultiEdit_CTE_test.cls
/************************************************************************************************************************************
Name    : OpptyMultiEdit_CTE_test 
Purpose : Test class for OpptyMultiEdit_CTE class

Modification History:  updated by Naresh

*************************************************************************************************************************************/ 

@isTest
public class OpptyMultiEdit_CTE_test {
    public static testMethod void test_OpptyMultiEdit_CTE_N()
    {
        Utilities.setIsTestMethod(true);
        Utilities.setValidationSkip(true);
        Utilities.setSkipFuture(true);
        
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Cisco_ADMIN' Limit 1];
        User usr = lxTestDataFactory.createSingleUser(p.Id);
        system.runAs(usr){
            lxTestDataFactory.createCustomSettings();
            PageReference newpage  = new PageReference('/apex/OpptyMultiEdit?robots=true');
            Test.setCurrentPageReference( newpage );
            Opportunity testOpty = lxTestDataFactory.createSingleOppty();
            testOpty.Opportunity_Status__c ='Lost';
            testOpty.Contractual_Pricing_Letter_Opportunity__c = 'No';
            insert testOpty;
            List<opportunity> opptyList = new List<Opportunity>();
            opptyList.add(testOpty);
            ApexPages.StandardSetController ssc = new ApexPages.StandardSetController( opptyList );
            ssc.setSelected(opptyList);                                                      
            String proflie= UserInfo.getProfileId();
            String profileId = proflie.substring(0,proflie.length()-3);                                                      
            ProfileID__c objectnew = new ProfileID__c(SetupOwnerId=UserInfo.getOrganizationId(), Cisco_US_Commercial__c=profileId);
            OpptyMultiEdit_CTE.wrapOpportunity wpOpp = new OpptyMultiEdit_CTE.wrapOpportunity(testOpty);
            OpptyMultiEdit_CTE.seOpportunity seoppty = new OpptyMultiEdit_CTE.seOpportunity();
            seoppty.seOpp =testOpty;
            seoppty.selected = true;
            
            seoppty.headerSelected = true;
            List<OpptyMultiEdit_CTE.seOpportunity> seWrapperList = new List<OpptyMultiEdit_CTE.seOpportunity>();
            seWrapperList.add(seoppty);
            System.debug('>>> '+seWrapperList);
            OpptyMultiEdit_CTE.seTech setech = new OpptyMultiEdit_CTE.seTech();
            setech.techBE = 'test';
            setech.techMixPercent = 12;
            OpptyMultiEdit_CTE.seService seservice = new OpptyMultiEdit_CTE.seService();
            seservice.serviceBE = 'test';
            seservice.serviceMixPercent = 12;
            seOppty.selected = true;
            seOppty.headerSelected = true;
            seOppty.seOpp = testOpty;
            Account a = lxTestDataFactory.createChannelAccount(usr.Id);
            insert a;
            Pricebook2 pb21 = lxTestDataFactory.createPriceBook2();
            insert pb21;
            Opportunity opty2 = lxTestDataFactory.createSingleOpportunity(a.id, pb21.id, usr.Id);
            insert opty2;
            seoppty.selected = true;
            Resource_Request_Assignment__c resreq= new Resource_Request_Assignment__c(Opportunity_Name__c=opty2.Id,
                                                                                Resource_Name__c=usr.Name,Resource_Status__c='Decline-Pending');
            
           
            OpptyMultiEdit_CTE ct = new OpptyMultiEdit_CTE( ssc ); 
           
            ct.getGoToUrl();
            ct.setGoToUrl('/test');
            ct.setSaveNew();
            ct.getErrorMsg();  
            ct.getOpptyList();
            ct.getOpptyCount();    
            ct.getStage1();        
            ct.getStage2();
            ct.getStage3();
            ct.getStage4();
            ct.getStage5();
            ct.getTeamRolePicklist();
            ct.getWrapOpptunityList();
            ct.getSEWrapperList();
            ct.showSE();
            ct.showSpecialist();
            ct.seWrapperList=seWrapperList;
            ct.checkBoxAction();
            ct.seassignMyself();
            ct.seAssignSomeoneElse();
            ct.closePopup();
            ct.saveNClose();
            ct.saveNew();
            ct.getsearchBy();
            ct.passUserId();
            ct.seUserSave();
            ct.prevListviewId = 'test';
            ct.listViewId = 'test';
            ct.searchKey='shi';
            ct.search();

            if(opty2!=null){
                ct.getCompetitorsPicklist();
                ct.setCompetitorsPicklist(opty2);
                ct.ExtensionSave();
                ct.processSelected();
            }
            
        }
        
    }  
    public static testMethod void test_OpptyMultiEdit_CTE_N1(){
        Utilities.setIsTestMethod(true);
        Utilities.setValidationSkip(true);
        Utilities.setSkipFuture(true);
        
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Cisco_ADMIN' Limit 1];
        User usr = lxTestDataFactory.createSingleUser(p.Id);
        system.runAs(usr){
            User user1 = new User(firstName='Test1',LastName ='PA Contact', USERNAME='testpa2@cisco.com.sales.test',email='testpa232@cisco.com.test',ALIAS='testp',COMMUNITYNICKNAME='testp',ISACTIVE=True,
                             TIMEZONESIDKEY='America/Los_Angeles',LnP_T_C_Acepted_Date__c=Date.Today()+5,LnP_TC_Reset_Date__c=Date.Today()-5,LnP_TC_Accepted__c=true,PROFILEID =p.Id ,LANGUAGELOCALEKEY ='en_US',THEATRE__C='APJC-APAC',
                             LOCALESIDKEY ='en_US',EMAILENCODINGKEY='UTF-8',Additional_User_Permissions__c='SE User',
                            Notification_Entity__c='Case; Opportunity',Notification_Platform__c='Email; WebEx Teams',Notification_Preference__c='Daily Digest'
                            );
            insert user1;
            user1.Reporting_Manager_Level_1_cec__c=usr.Username.substringBefore('@');
            update user1;
            lxTestDataFactory.createCustomSettings();
            PageReference newpage  = new PageReference('/apex/OpptyMultiEdit?robots=true');
            Test.setCurrentPageReference( newpage );
            Opportunity testOpty = lxTestDataFactory.createSingleOppty();
            testOpty.Opportunity_Status__c ='Lost';
            testOpty.Contractual_Pricing_Letter_Opportunity__c = 'No';
            insert testOpty;
            List<opportunity> opptyList = new List<Opportunity>();
            opptyList.add(testOpty);
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController( opptyList );
        OpptyMultiEdit_CTE ct = new OpptyMultiEdit_CTE( ssc ); 
        ct.searchKey='';
        ct.search();
        ct.checkSEMOrSED(user1.username.substringBefore('@'));
        }
    }
    
}