objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_Rollup_Renewals__c</fullName>
        <label>Customer Rollup Renewals</label>
        <summaryFilterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>Renewals Opportunity</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Opportunity.StageName</field>
            <operation>contains</operation>
            <value>1 - Prospect, 2 - Qualification, 3 - Proposal, 4 - Agreement, Planning, Customer Accepted, Implementing, Complete, Not Implemented</value>
        </summaryFilterItems>
        <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Forecasted_Attrition_Rollup__c</fullName>
        <label>Forecasted Attrition Rollup</label>
        <summarizedField>Opportunity.Forecasted_Attrition_000s__c</summarizedField>
        <summaryFilterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>Renewals Opportunity</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Opportunity.StageName</field>
            <operation>equals</operation>
            <value>1 - Prospect, 2 - Qualification, 4 - Agreement, 3 - Proposal</value>
        </summaryFilterItems>
        <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Forecasted_Attrition__c</fullName>
        <label>Total Expected Attrition</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Roll_up_of_Total_Expected_ATR__c</fullName>
        <label>Roll up of Total Expected ATR</label>
        <summarizedField>Opportunity.Expected_Total_ATR_000s__c</summarizedField>
        <summaryFilterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>Renewals Opportunity</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Opportunity.StageName</field>
            <operation>contains</operation>
            <value>1 - Prospect, 2 - Qualification, 3 - Proposal, 4 - Agreement</value>
        </summaryFilterItems>
        <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Roll_up_of_Total_Prior_ATR__c</fullName>
        <label>Roll up of Total Prior ATR</label>
        <summarizedField>Opportunity.Total_Prior_ATR__c</summarizedField>
        <summaryFilterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>Renewals Opportunity</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Opportunity.StageName</field>
            <operation>contains</operation>
            <value>1 - Prospect, 2 - Qualification, 3 - Proposal, 4 - Agreement</value>
        </summaryFilterItems>
        <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Theatre__c</fullName>
        <description>Describes which Cisco geographical region the account us managed by.</description>
        <label>Theatre</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>APJ</fullName>
                </value>
                <value>
                    <fullName>EMEAR</fullName>
                </value>
                <value>
                    <fullName>Global Service Provider</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Upcoming_Renewals__c</fullName>
        <label>Total # Upcoming Renewals</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Channel</fullName>
        <active>true</active>
        <description>Registered Partner Account from PDB (Partner Database)</description>
        <label>Channel</label>
    </recordTypes>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>Customer recordtype for C360</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>EndUser</fullName>
        <active>true</active>
        <description>Existing or Prospective Customer Account</description>
        <label>End-User</label>
    </recordTypes>
</CustomObject>

objects/Apex_Batch_Job__c.object
<CustomObject>
    <fields>
        <fullName>query1__c</fullName>
        <label>query1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>query__c</fullName>
        <label>query</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Used to store the query and notification email id for batch process.</description>
    <label>Apex Batch Job</label>
</CustomObject>

objects/ObjectRecordTypeIds__c.object
<CustomObject>
    <fields>
        <fullName>AccountChannelRecordTypeId__c</fullName>
        <description>This field stores the id of the channel account record type.</description>
        <label>Account Channel RecordTypeId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_BU_RecordType_18__c</fullName>
        <label>Account BU RecordType 18</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Customer_RecordType_18__c</fullName>
        <label>Account Customer RecordType 18</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_End_User_RT_18__c</fullName>
        <label>Account End User RT 18</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is used to store the record type ids of account and contact objects.</description>
    <label>Object Record Type Ids</label>
</CustomObject>

objects/Org_Constant_CS__c.object
<CustomObject>
    <fields>
        <fullName>Non_Production_Value__c</fullName>
        <label>Non Production Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Production_Value__c</fullName>
        <label>Production Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>Org Constant CS</label>
</CustomObject>

objects/Org_Constants__c.object
<CustomObject>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>prod_value__c</fullName>
        <label>prod value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Org Constant</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Org Constants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProfileID__c.object
<CustomObject>
    <fields>
        <fullName>Cisco_PSS__c</fullName>
        <description>This field stores the id of the Cisco PSS Profile</description>
        <label>Cisco_PSS</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cisco_Renewals__c</fullName>
        <defaultValue>'00e34000001CQnp'</defaultValue>
        <description>00e34000001CQnp</description>
        <inlineHelpText>00e34000001CQnp</inlineHelpText>
        <label>Cisco_Renewals</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is used to store the profile ids for all the available profiles.</description>
    <label>Profile ID</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Additional_User_Permissions__c</fullName>
        <description>Allows permission for additional functionality which are based on User and not by profile.
1)AccountCreateByTerritory: New SBC functionality which allows SBC based on Geo Rules
2)Enable EndUser ACCTCreation : Can Create End-User accounts
3)Enable Lead Conversion : Can Convert leads
4)Enable PDR ACCTCreation : Can Create End-User Account during CCW deal conversion
5)Request Resource : Allows AMs to access SE functionality
6)SE User : Allows SEs to access SE Functionality
7)2028 Visibility:Users that will be refreshed by 2028 black box process
8)NBM Approver : User can set status field of NBM records to 'Screen 3' Approval status</description>
        <label>Additional User Permissions</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>2028 Visibility</fullName>
                </value>
                <value>
                    <fullName>AccountCreateByTerritory</fullName>
                </value>
                <value>
                    <fullName>AcquisitionUser</fullName>
                </value>
                <value>
                    <fullName>Activate Sales Account View</fullName>
                </value>
                <value>
                    <fullName>CCE Enabled</fullName>
                </value>
                <value>
                    <fullName>DSEC360</fullName>
                </value>
                <value>
                    <fullName>DSEC360SAV</fullName>
                </value>
                <value>
                    <fullName>DSEContactIntelligence</fullName>
                </value>
                <value>
                    <fullName>DSECRinSFDC</fullName>
                </value>
                <value>
                    <fullName>DSEFA</fullName>
                </value>
                <value>
                    <fullName>DSEGA</fullName>
                </value>
                <value>
                    <fullName>DSENotification</fullName>
                </value>
                <value>
                    <fullName>DSESWSS</fullName>
                </value>
                <value>
                    <fullName>DSETAC</fullName>
                </value>
                <value>
                    <fullName>Einstein Opportunities</fullName>
                </value>
                <value>
                    <fullName>Enable_ePSS</fullName>
                </value>
                <value>
                    <fullName>Enable_VSS</fullName>
                </value>
                <value>
                    <fullName>Enable EndUser ACCTCreation</fullName>
                </value>
                <value>
                    <fullName>Enable Lead Conversion</fullName>
                </value>
                <value>
                    <fullName>Enable PDR ACCTCreation</fullName>
                </value>
                <value>
                    <fullName>Enable Target Prospect Creation</fullName>
                </value>
                <value>
                    <fullName>GSPO_BDM</fullName>
                </value>
                <value>
                    <fullName>GSSO HD Forecast User</fullName>
                </value>
                <value>
                    <fullName>MCP Prospect Engage</fullName>
                </value>
                <value>
                    <fullName>MCP Prospect Profiler</fullName>
                </value>
                <value>
                    <fullName>NBM Approver</fullName>
                </value>
                <value>
                    <fullName>NextGen Forecasting Pilot User</fullName>
                </value>
                <value>
                    <fullName>QIJanACVPilotUser</fullName>
                </value>
                <value>
                    <fullName>RAE SEP Enabled</fullName>
                </value>
                <value>
                    <fullName>Request Resource</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Theatre__c</fullName>
        <inlineHelpText>Please contact GSTS Support to Edit this field</inlineHelpText>
        <label>Theater</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Americas-Canada</fullName>
                </value>
                <value>
                    <fullName>Americas-Global Enterprise Segment</fullName>
                </value>
                <value>
                    <fullName>Americas-LATAM</fullName>
                </value>
                <value>
                    <fullName>Americas-US Commercial</fullName>
                </value>
                <value>
                    <fullName>Americas-US Public Sector</fullName>
                </value>
                <value>
                    <fullName>APJC-APAC</fullName>
                </value>
                <value>
                    <fullName>APJC-Greater China</fullName>
                </value>
                <value>
                    <fullName>APJC-Japan</fullName>
                </value>
                <value>
                    <fullName>EMEAR</fullName>
                </value>
                <value>
                    <fullName>Global Service Provider</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CustomerGURenewalRollupToAccountTest.cls
/************************************************************************************************************************************
Name    : CustomerGURenewalRollupToAccountTest
Author  : C360 Dev team
Purpose : Contains logic to execute test methods of CustomerGURenewalRollupToAccount,CustomerGURenewalRollupScheduleBatchApex
Date    : 25/02/2019

*************************************************************************************************************************************/
@isTest
public class CustomerGURenewalRollupToAccountTest{
    static testMethod void testmethodRollup(){
        Profile prof = [select id from profile where name LIKE '%Cisco_ADMIN%' limit 1];
        User user = new User(Alias = 'newUser', Email='newuser@cisco.com',
                             EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                             LocaleSidKey='en_US', ProfileId = prof.id,
                             TimeZoneSidKey='America/Los_Angeles', UserName='newuser@cisco.com', 
                             Theatre__c = 'Americas-US Commercial', Additional_User_Permissions__c='Enable EndUser ACCTCreation');
        insert user;
        
        insert new ProfileID__c(Cisco_Renewals__c = '11e30000000dcbg', Cisco_PSS__c='22e30000000dcbg');
        insert new Org_Constants__c(Key__c = 'Oppty: ProfileIds to skip Triggers', prod_value__c='prodval');
        insert new Org_Constant_CS__c(Name='PilotProfileId',Non_Production_Value__c='00e30000000dV6c',Production_Value__c='00e30000000dV6c');
        
        system.runAs(user){     
            
            Id customerRecId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
            Id buRecId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Unit').getRecordTypeId();
            Id endUserRecId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('End-User').getRecordTypeId();
            Id channerRecId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Channel').getRecordTypeId();
            
            insert new ObjectRecordTypeIds__c(AccountChannelRecordTypeId__c = channerRecId,Account_Customer_RecordType_18__c=customerRecId,Account_BU_RecordType_18__c=buRecId,Account_End_User_RT_18__c=endUserRecId);
            
            Account customer = new Account(Name='CUSTOMER-AMP',RecordTypeId=customerRecId,Total_Upcoming_Renewals__c = 0,Forecasted_Attrition__c=0);
            insert customer;
            
            Account bu1 = new Account(Name='BU - AMP AU',ParentId=customer.Id,RecordTypeId=buRecId,Total_Upcoming_Renewals__c = 0,Forecasted_Attrition__c=0);
            Account bu2 = new Account(Name='BU - AMP US',ParentId=customer.Id,RecordTypeId=buRecId,Total_Upcoming_Renewals__c = 0,Forecasted_Attrition__c=0);
            List<Account> buList = new List<Account>();
            buList.add(bu1);
            buList.add(bu2);
            insert buList;
            
            Account endUser1 = new Account(Name='PACIFIC INDUSTRIES',ParentId=bu1.Id,RecordTypeId=endUserRecId);
            insert endUser1;
            
            Id oppRecId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Renewals Opportunity').getRecordTypeId();
            List<Opportunity> oppList = new List<Opportunity>();
            Opportunity opp1 = new Opportunity(Name='AMP Capital',recordTypeId=oppRecId,AccountId=endUser1.Id,StageName='1 - Prospect',CloseDate=System.today(),Partner_Required__c = true,Forecasted_Attrition_000s__c=50);
            Opportunity opp2 = new Opportunity(Name='AMP Capital Meraki Retail Wifi',recordTypeId=oppRecId,AccountId=endUser1.Id,StageName='1 - Prospect',CloseDate=System.today(),Partner_Required__c = true,Forecasted_Attrition_000s__c=50);
            oppList.add(opp1);
            oppList.add(opp2);
            insert oppList ;
            
            Profile prof1 = [select id from profile where name LIKE '%Cisco_Sales%' limit 1];
            User salesUser = new User(Alias = 'salesUse', Email='salesUser@cisco.com',
                                      EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                                      LocaleSidKey='en_US', ProfileId = prof1.id,
                                      TimeZoneSidKey='America/Los_Angeles', UserName='salesUser@cisco.com', 
                                      Theatre__c = 'Americas-US Commercial');
            insert salesUser;
            List<OpportunityTeamMember> oppTeamList = new List<OpportunityTeamMember>();
            OpportunityTeamMember member1 = new OpportunityTeamMember(OpportunityId=opp1.Id,userId=salesUser.Id,TeamMemberRole='Account Manager',opportunityAccessLevel='Edit');
            OpportunityTeamMember member3 = new OpportunityTeamMember(OpportunityId=opp2.Id,userId=salesUser.Id,TeamMemberRole='Account Manager',opportunityAccessLevel='Edit');
            oppTeamList.add(member1);
            oppTeamList.add(member3);
            insert oppTeamList;
            
            insert new  Apex_Batch_Job__c (Name ='OppRollupToAccount',query__c='Select Id,Name,Customer_Rollup_Renewals__c,Forecasted_Attrition_Rollup__c,ParentId,Roll_up_of_Total_Prior_ATR__c,Roll_up_of_Total_Expected_ATR__c from Account where (Customer_Rollup_Renewals__c > 0 OR Forecasted_Attrition_Rollup__c > 0',query1__c ='OR Roll_up_of_Total_Prior_ATR__c>0 OR Roll_up_of_Total_Expected_ATR__c > 0 )  and Id =\''+enduser1.id+'\'');
            
            String query = 'Select Id,Name,Customer_Rollup_Renewals__c,Forecasted_Attrition_Rollup__c,ParentId,Roll_up_of_Total_Prior_ATR__c,Roll_up_of_Total_Expected_ATR__c from Account where (Customer_Rollup_Renewals__c > 0 OR Forecasted_Attrition_Rollup__c > 0  OR Roll_up_of_Total_Prior_ATR__c>0 OR Roll_up_of_Total_Expected_ATR__c > 0 )  and Id =\''+enduser1.id+'\'';
            CustomerGURenewalRollupToAccount obj = new CustomerGURenewalRollupToAccount(query);
            String sch = '0 0 8 13 2 ?';
            CustomerGURenewalRollupScheduleBatchApex gl= new CustomerGURenewalRollupScheduleBatchApex();
            gl.query='Select Id,Name,Customer_Rollup_Renewals__c,Forecasted_Attrition_Rollup__c,ParentId,Roll_up_of_Total_Prior_ATR__c,Roll_up_of_Total_Expected_ATR__c from Account where (Customer_Rollup_Renewals__c > 0 OR Forecasted_Attrition_Rollup__c > 0 OR Roll_up_of_Total_Prior_ATR__c>0 OR Roll_up_of_Total_Expected_ATR__c > 0 )  and Id =\''+enduser1.id+'\'';
            String jobIds = System.schedule('testBasicScheduledApex',sch,gl);
            ID JobId = Database.executeBatch(obj,200);  
            
        }
    }   
}