objects/Activity.object
<CustomObject>
    <fields>
        <fullName>Theater__c</fullName>
        <description>Describes which Cisco geographical region the activities managed by”.</description>
        <inlineHelpText>Theater must be selected in order to use the Marketing Campaign field</inlineHelpText>
        <label>Theater</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Americas-Canada</fullName>
                </value>
                <value>
                    <fullName>Americas-Global Enterprise Segment</fullName>
                </value>
                <value>
                    <fullName>Americas-LATAM</fullName>
                </value>
                <value>
                    <fullName>Americas-US Commercial</fullName>
                </value>
                <value>
                    <fullName>Americas-US Public Sector</fullName>
                </value>
                <value>
                    <fullName>APJC-APAC</fullName>
                </value>
                <value>
                    <fullName>APJC-Greater China</fullName>
                </value>
                <value>
                    <fullName>APJC-Japan</fullName>
                </value>
                <value>
                    <fullName>EMEAR</fullName>
                </value>
                <value>
                    <fullName>Global Enterprise</fullName>
                </value>
                <value>
                    <fullName>Global Service Provider</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Call_Script__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CC Call Script</label>
        <referenceTo>CC_Call_Script__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Campaign_Name__c</fullName>
        <label>Campaign Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign_source__c</fullName>
        <label>Campaign source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <description>User Story- 5251</description>
        <label>Priority</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program_Originating_Country__c</fullName>
        <label>Program Originating Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Theatre__c</fullName>
        <description>US5251 - Launching a program event</description>
        <label>Theatre</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

objects/CC_Call_Script__c.object
<CustomObject>
    <fields>
        <fullName>Default_Call_Script__c</fullName>
        <defaultValue>false</defaultValue>
        <description>NGCC Phase1: The call script which can be defined as default</description>
        <inlineHelpText>Check mark if this Call Script constitutes to default Call Script</inlineHelpText>
        <label>Default Call Script</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Global Eloqua</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Theater__c</fullName>
        <description>NGCC Phase1: Call Script Theater where the Call Script will be Used</description>
        <inlineHelpText>Call Script Theater where the Call Script will be Used</inlineHelpText>
        <label>Theater</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>APJ</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
                <value>
                    <fullName>EMEAR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>NGCC Phase1: Call Script master object which defines call scripts and its current status. Call Script can be edited only if the call script is in draft or inactive.</description>
    <label>CC Call Script</label>
    <nameField>
        <label>CC Call Script Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Call Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Call_Status__c</fullName>
        <description>NGCC Phase1:Call Status depending upon disposition value.  Can be only updated by system based on disposition.</description>
        <label>Call Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Call Back Later</fullName>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
                <value>
                    <fullName>Invalid Call Completed</fullName>
                </value>
                <value>
                    <fullName>Max Attempts Reached</fullName>
                </value>
                <value>
                    <fullName>Nurture</fullName>
                </value>
                <value>
                    <fullName>PE Cancelled/Completed</fullName>
                </value>
                <value>
                    <fullName>Call Completed</fullName>
                </value>
                <value>
                    <fullName>Requalification Required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Campaign_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>NGCC Phase1:Unica Campaign name</description>
        <label>Campaign Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Campaign.Eloqua_Campaign_Id__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Outcome__c</fullName>
        <description>NGCC Phase1:Latest call disposition</description>
        <label>Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Call Back</fullName>
                </value>
                <value>
                    <fullName>Max Attempts Reached</fullName>
                </value>
                <value>
                    <fullName>Cust Prefers a different buying method</fullName>
                </value>
                <value>
                    <fullName>Customer Dropped Off</fullName>
                </value>
                <value>
                    <fullName>Customer Service</fullName>
                </value>
                <value>
                    <fullName>Invalid Info</fullName>
                </value>
                <value>
                    <fullName>Lead Escalation</fullName>
                </value>
                <value>
                    <fullName>Nurture</fullName>
                </value>
                <value>
                    <fullName>Qualified Lead</fullName>
                </value>
                <value>
                    <fullName>Transfer out</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProgramEvent__c</fullName>
        <description>Program Event Code/Key Code associated with the lead generation
LTLM integrated field</description>
        <label>Program Event Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Theater__c</fullName>
        <description>Theatre Name 
LTLM integrated field</description>
        <label>Theater</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Closed</fullName>
        <active>true</active>
        <businessProcess>eLeads</businessProcess>
        <description>Rejected/closed eLeads lead</description>
        <label>Closed</label>
    </recordTypes>
</CustomObject>

objects/NGCC_Mapping_Object__c.object
<CustomObject>
    <fields>
        <fullName>Theater__c</fullName>
        <label>Theater</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>APJ</fullName>
                </value>
                <value>
                    <fullName>EMEAR</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CC Mapping Object</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NGCC Mapping Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/NGCC_Campaign_Management_Cls.cls
/*********************************************************************************************************************************
Name    : NGCC_Campaign_Management_Cls
Author  : Ramzil
Purpose : This class is to handle all Campaign related activity for NGCC project
            Assigning Theater and Default Call Script
            Closing Lead when Campaign is Cancelled and Closed
            
Created Date:  1/25/2014 
Modification History:   @Mukesh Modified to make readable code
                        @Mukesh added Maximum attempt and priority update to all lead
						Nirup, update to default call script only if the field is null (2/16/16)
                     
**********************************************************************************************************************************/
public class NGCC_Campaign_Management_Cls{
    
	//@ method: To process All before activity on Campaign Object
    public static void NGCC_Campaign_Management_Before(List<Campaign> newLstCampaign){
        
        List<Campaign> lstCampCallScriptAssignment = new List<Campaign>();
        Map<String,NGCC_Mapping_Object__c> mapMPObj=new Map<String,NGCC_Mapping_Object__c>();        
        for(NGCC_Mapping_Object__c mObj: [Select Name,Id,Theater__c from NGCC_Mapping_Object__c]){
            mapMPObj.put(mObj.Name,mObj);
        }  
        for(Campaign camp: newLstCampaign){
            //system.debug('Check2');
            //system.debug('CALL -->' +camp.Call_Script__c);
            //system.debug('Program -->' +camp.Program_Originating_Country__c);
            if(camp.Program_Originating_Country__c != null && camp.Call_Script__c == null){
                //system.debug('Check3-->'+mapMPObj);
                if(mapMPObj.containsKey(camp.Program_Originating_Country__c)){
                    //system.debug('Check4-->' +mapMpObj);
                  camp.Theatre__c = mapMPObj.get(camp.Program_Originating_Country__c).Theater__c;
                  lstCampCallScriptAssignment.add(Camp);
                }
            }
        }
        NGCC_Campaign_CallScript_Assignment(lstCampCallScriptAssignment);
    }   
    //@ method: To process assign Theater and Default Call Script
    public static void NGCC_Campaign_CallScript_Assignment(List<Campaign> newLstCampaign){  
        set<string> theaterSet = new set<string>();
        for(Campaign cm : newLstCampaign){
            if(cm.Theatre__c != null){
                theaterSet.add(cm.Theatre__c);
            }
        }
        
        Map<String, Id> mapTheaterCallScript = new Map<String,Id>(); // If campaign source is not a "Global Eloqua"
        Map<String, Id> mapTheaterCallScript_Eloqua = new Map<String,Id>();// If campaign source is  a " Global Eloqua"
        for(CC_Call_Script__c csObj: [Select Id, Theater__c,Default_Call_Script__c,Source__c FROM CC_Call_Script__c Where Default_Call_Script__c=true AND Theater__c In :theaterSet])
        {
            if(csObj.Source__c == 'Global Eloqua'){
                mapTheaterCallScript_Eloqua.put(csObj.Theater__c,csObj.Id);
            }else{
                mapTheaterCallScript.put(csObj.Theater__c,csObj.Id); // If source is empty in call script , considering call script not related Global Eloqua            
            }
            
        }
        
        for(Campaign camp: newLstCampaign){
            
            if(camp.Campaign_source__c == 'Global Eloqua'){
                if(mapTheaterCallScript_Eloqua.containsKey(camp.Theatre__c)){
                    camp.Call_Script__c = mapTheaterCallScript_Eloqua.get(camp.Theatre__c);
                } 
            }else{
                if(mapTheaterCallScript.containsKey(camp.Theatre__c)){
                    camp.Call_Script__c = mapTheaterCallScript.get(camp.Theatre__c);
                } 
            }
            
                  
        }       
    }
    static map<Id,Campaign> mapCIdCamp= new map<Id,Campaign>();
    static Set<Id> setCampId = new Set<Id>();
    
    //@ method: To process All after activity on Campaign Object
    public static void NGCC_Campaign_Management_After(List<Campaign> newLstCampaign,Map<Id,Campaign> mapIdCampaign){ 
    
        for(Campaign camp: newLstCampaign){
            if(camp.Status != mapIdCampaign.get(camp.Id).Status){
                if(camp.Status == 'Cancelled' || camp.Status == 'Completed'){
                    setCampId.add(camp.Id);
                }
            }
            
            if(camp.Status != 'Cancelled' || camp.Status != 'Completed'){
                    if(camp.Priority__c != mapIdCampaign.get(camp.Id).Priority__c){
                        mapCIdCamp.put(camp.Id,camp);
                    }
            }
        }
        
        NGCC_Campaign_Lead_Update(setCampId);
    }
    // @ method: To process Close all Leads when campaign is completed or cancelled   
    public static void NGCC_Campaign_Lead_Update(Set<Id> setCanClsdCampaign){
        List<Lead> lstLeadToProcess = [Select Id, Call_Status__c,Outcome__c,ProgramEvent__c,Campaign_Name__c FROM Lead 
                                        Where Campaign_Name__c IN : setCanClsdCampaign OR  Campaign_Name__c IN :mapCIdCamp.keySet()]; 
        for(Lead ldObj: lstLeadToProcess){
            if(setCampId.contains(ldObj.Campaign_Name__c )){
                ldObj.Call_Status__c = 'PE Cancelled/Completed';
                ldObj.Status = 'Inactive';
            }
        }        
        if(!lstLeadToProcess.isEmpty()){
            Database.SaveResult[] updateLeadStatus = Database.update(lstLeadToProcess ,false);
            system.debug('*************'+lstLeadToProcess.size());
        }
    }  
}