objects/Agenda_Item__c.object
<CustomObject>
    <fields>
        <fullName>CEE_Attendee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CEE Attendee</label>
        <referenceTo>CEE_Attendee__c</referenceTo>
        <relationshipLabel>Agenda Items</relationshipLabel>
        <relationshipName>Agenda_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Topic__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Topic</label>
        <referenceTo>Topic__c</referenceTo>
        <relationshipLabel>Agenda Items</relationshipLabel>
        <relationshipName>Agenda_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agenda Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agenda Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Agenda_Room__c.object
<CustomObject>
    <label>Agenda Room</label>
    <nameField>
        <displayFormat>RM-{00000}</displayFormat>
        <label>Room Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agenda Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CEE__c.object
<CustomObject>
    <fields>
        <fullName>Post_Engagement_Message_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A flag for a workflow/trigger combo to check whether the trigger has been fired already.</description>
        <label>Post Engagement Message Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Engagements &amp; Events</relationshipLabel>
        <relationshipName>Primary_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <description>Briefing Request Status and it is related to CPOC lab request.</description>
        <inlineHelpText>Current stage of an Engagement Request</inlineHelpText>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Returned (all resources released)</fullName>
                </value>
                <value>
                    <fullName>Cancelled (all resources released)</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Saved, not Submitted</fullName>
                </value>
                <value>
                    <fullName>Assigned to PM</fullName>
                </value>
                <value>
                    <fullName>Submitted by Requester</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Lab Redirect</fullName>
                </value>
                <value>
                    <fullName>Returned by Scheduler</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>emailHasNotBeenSent__c</fullName>
        <defaultValue>true</defaultValue>
        <description>flag to prevent duplicate emails in trigger "CEESendPresenterPostEngagementNotes"</description>
        <label>emailHasNotBeenSent</label>
        <type>Checkbox</type>
    </fields>
    <description>This object will store summary level briefing information from CEE. This Object is created to Integrate CEE Applicaiton data with Salesforce.com. It allows users to link CEE Briefings with Accounts in Salesforce.com.</description>
    <label>Customer Engagements &amp; Events</label>
    <nameField>
        <displayFormat>CEE-{000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Engagements &amp; Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>OBX</fullName>
        <active>true</active>
        <description>Delivering Demonstrations, Briefings, and Events</description>
        <label>Outcome Based Experience (OBX - formerly EBC)</label>
    </recordTypes>
</CustomObject>

objects/CEE_Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Agenda_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agenda Item</label>
        <referenceTo>Agenda_Item__c</referenceTo>
        <relationshipLabel>CEE Attendees</relationshipLabel>
        <relationshipName>CEE_Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CEE Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CEE Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CEE_Invite__c.object
<CustomObject>
    <fields>
        <fullName>Agenda_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Agenda Item</label>
        <referenceTo>Agenda_Item__c</referenceTo>
        <relationshipName>CES_Invites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CEE_Attendee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CEE Attendee</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CEE_Attendee__c.Agenda_Item__c</field>
                <operation>equals</operation>
                <valueField>$Source.Agenda_Item__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CEE_Attendee__c</referenceTo>
        <relationshipLabel>CEE Invites</relationshipLabel>
        <relationshipName>CEE_Invites</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CEE Invite</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>CEE Invite ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CEE Invites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CEE_Location__c.object
<CustomObject>
    <description>The location details for a given Location, either a Field Sales Office (FSO), Executive Briefing Center (EBC), or Customer Briefing Center provided as part of the Customer Engagement implementation.</description>
    <label>CEE Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CEE Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CEE_Room__c.object
<CustomObject>
    <fields>
        <fullName>CEE_Location__c</fullName>
        <label>CEE Location</label>
        <referenceTo>CEE_Location__c</referenceTo>
        <relationshipLabel>CEE Rooms</relationshipLabel>
        <relationshipName>CEE_Rooms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>CEE Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CEE Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Topic__c.object
<CustomObject>
    <label>CEE Topic</label>
    <nameField>
        <label>Topic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CEE Topics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CEE_PreBriefingController_Test.cls
/***************************************************************************************************
Name    : CEE_PreBriefingController_Test 
Author  : Akeem Shirley
Purpose : Tests for the Pre Briefing PDF class  
Created Date: Dec 1 2014
Modification History: 
Eric Pesch - Jan 5 2015: Added Comments, cleanup                     
*****************************************************************************************************/

@isTest
public class CEE_PreBriefingController_Test {

    public static testMethod void testMyController() {

        User admin = CEE_TestUtility.getUser('admin', true);

        Account testAcct;
        System.runAs(admin){
            CEE_TestUtility.loadCustomSettings();
            testAcct = CEE_TestUtility.getAccount('cee', true);
        }
        
        
        
        //Opportunity testOpt = null;
        Opportunity opppt =  CEE_TestUtility.getOpty();
        CEE_Location__c testLoc = CEE_TestUtility.getLocation('cee', true, 'EBC/EC');
        CEE__c briefing= CEE_TestUtility.getBriefing('cee', true, 'OBX', testAcct, opppt, testLoc);
        
        //attendee and invitee details
        Topic__c topic = CEE_TestUtility.getTopic('brief', true, false);
        CEE_Room__c room = CEE_TestUtility.getRoom('brief', true, testLoc, false, 6);
        Agenda_Room__c agendaRoom = CEE_TestUtility.getAgendaRoom('brief', false, briefing, room);
        Agenda_Item__c agenda = CEE_TestUtility.getAgendaItem('brief', true, briefing, testLoc, agendaRoom, topic);
       //CEE_Attendee__c attendee = CEE_TestUtility.getAttendee('brief', false, briefing,agenda,true);
        //CEE_Invite__c invite = CEE_TestUtility.getInvite('brief', false, briefing,attendee,agenda,agendaRoom);
        
        
        briefing.Primary_Account__c = testAcct.id;
        briefing.Post_Engagement_Message_Sent__c = true;
        briefing.emailHasNotBeenSent__c = true;
        briefing.Request_Status__c = 'Confirmed';
        update briefing;
        
   
        
        ApexPages.StandardController sc = new ApexPages.standardController(briefing);
        CEE_PreBriefingController myPage = new CEE_PreBriefingController(sc);

        CEE__c test = myPage.getBriefing();
        myPage.setBriefing(briefing);
        myPage.getAttendeeMap();
        
        List<Agenda_Item__c> testAI = myPage.getLstAgendaItems();
        
    }
}