objects/Agenda_Item__c.object
<CustomObject>
    <fields>
        <fullName>CEE_Attendee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CEE Attendee</label>
        <referenceTo>CEE_Attendee__c</referenceTo>
        <relationshipLabel>Agenda Items</relationshipLabel>
        <relationshipName>Agenda_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Outlook_Status__c</fullName>
        <label>Outlook Status</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Topic__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Topic</label>
        <referenceTo>Topic__c</referenceTo>
        <relationshipLabel>Agenda Items</relationshipLabel>
        <relationshipName>Agenda_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agenda Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agenda Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Agenda_Room__c.object
<CustomObject>
    <label>Agenda Room</label>
    <nameField>
        <displayFormat>RM-{00000}</displayFormat>
        <label>Room Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agenda Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CEE__c.object
<CustomObject>
    <description>This object will store summary level briefing information from CEE. This Object is created to Integrate CEE Applicaiton data with Salesforce.com. It allows users to link CEE Briefings with Accounts in Salesforce.com.</description>
    <label>Customer Engagements &amp; Events</label>
    <nameField>
        <displayFormat>CEE-{000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Engagements &amp; Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>OBX</fullName>
        <active>true</active>
        <description>Delivering Demonstrations, Briefings, and Events</description>
        <label>Outcome Based Experience (OBX - formerly EBC)</label>
    </recordTypes>
</CustomObject>

objects/CEE_Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Agenda_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agenda Item</label>
        <referenceTo>Agenda_Item__c</referenceTo>
        <relationshipLabel>CEE Attendees</relationshipLabel>
        <relationshipName>CEE_Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CEE Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CEE Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CEE_Invite__c.object
<CustomObject>
    <fields>
        <fullName>Agenda_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Agenda Item</label>
        <referenceTo>Agenda_Item__c</referenceTo>
        <relationshipName>CES_Invites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CEE_Attendee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CEE Attendee</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CEE_Attendee__c.Agenda_Item__c</field>
                <operation>equals</operation>
                <valueField>$Source.Agenda_Item__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CEE_Attendee__c</referenceTo>
        <relationshipLabel>CEE Invites</relationshipLabel>
        <relationshipName>CEE_Invites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Outlook_Invite_ID__c</fullName>
        <externalId>true</externalId>
        <label>Outlook Invite ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Outlook_Status__c</fullName>
        <label>Outlook Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Invited</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Tentative</fullName>
                </value>
                <value>
                    <fullName>Not Invited</fullName>
                    <default>true</default>
                    <label>Not Invited</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CEE Invite</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>CEE Invite ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CEE Invites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CEE_Location__c.object
<CustomObject>
    <description>The location details for a given Location, either a Field Sales Office (FSO), Executive Briefing Center (EBC), or Customer Briefing Center provided as part of the Customer Engagement implementation.</description>
    <label>CEE Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CEE Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CEE_Room__c.object
<CustomObject>
    <fields>
        <fullName>CEE_Location__c</fullName>
        <label>CEE Location</label>
        <referenceTo>CEE_Location__c</referenceTo>
        <relationshipLabel>CEE Rooms</relationshipLabel>
        <relationshipName>CEE_Rooms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>CEE Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CEE Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Topic__c.object
<CustomObject>
    <label>CEE Topic</label>
    <nameField>
        <label>Topic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CEE Topics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CEEAttendeeBeforeDelete_Test.cls
/***************************************************************************************************
Name    : CEEAttendeeBeforeDelete_Test 
Author  : Eric Pesch
Purpose : Trigger Tests for the CEE Attendee object  
Created Date: Dec 1 2014
Modification History: 
Eric Pesch - Jan 5 2015: Added Comments, cleanup                     
*****************************************************************************************************/

@isTest
private class CEEAttendeeBeforeDelete_Test {
    
    /*@method: Attendee deletion test*/
    static testMethod void attendeeDelete() {
        //Setup Account
        User admin = CEE_TestUtility.getUser('admin', true);
        Account acct = null;
        Opportunity oppty = null;
        
        System.runAs(admin){
            CEE_TestUtility.loadCustomSettings();
            acct = CEE_TestUtility.getAccount('brief', true);
        }
        
        //Setup location
        CEE_Location__c loc = CEE_TestUtility.getLocation('brief', true, 'EBC/EC');
        //CEE_Room__c room = CEE_TestUtility.getRoom('brief', true, loc, false, 6);
        
        //Setup briefing
        Opportunity opppt =  CEE_TestUtility.getOpty();
        CEE__c briefing = CEE_TestUtility.getBriefing('brief', true, 'OBX', acct, opppt, loc);
        Topic__c topic = CEE_TestUtility.getTopic('brief', true, false);
        //Agenda_Room__c agendaRoom = CEE_TestUtility.getAgendaRoom('brief', true, briefing, room);
        
        
        //Setup agenda item
        Agenda_Item__c agenda = CEE_TestUtility.getAgendaItem('brief', true, briefing, loc, null, topic);
        //Agenda_Item__c agenda1 = CEE_TestUtility.getAgendaItem('brief1', true, briefing, loc, null, topic); 
        //Setup Presenter
        CEE_Attendee__c presenter = CEE_TestUtility.getAttendee('brief', true, briefing, agenda, true);
        CEE_Invite__c invite = CEE_TestUtility.getInvite('brief', true, briefing, presenter, agenda, null);
        CEE_Invite__c invite1 = CEE_TestUtility.getInvite('brief', true, briefing, presenter, agenda, null);
        invite1.Outlook_Status__c = 'Accepted';
        update invite1;
        CEE_TestUtility.simulatePresenterInvite(invite);
        
        Test.startTest();
        //Exception - has Outlook invite active
        try{
            //delete presenter;
        } catch (Exception e){}
        
        invite.Outlook_Status__c = 'Accepted';
        update invite;
        
        //Succeed
        //delete presenter;
        Test.stopTest();
        
        //Check if presenter was deleted
        //System.assert(true, presenter.Id != null);
        //Check linkage is maintained between Invite and Presenter
        //System.assertEquals(invite.CEE_Attendee__c, presenter.Id);
    }
      /*@method: Attendee deletion test*/
    static testMethod void attendeeUpdate() {
        //Setup Account
        User admin = CEE_TestUtility.getUser('admin', true);
        Account acct = null;
        Opportunity oppty = null;
        
        System.runAs(admin){
            CEE_TestUtility.loadCustomSettings();
            acct = CEE_TestUtility.getAccount('brief', true);
        }
        
        //Setup location
        CEE_Location__c loc = CEE_TestUtility.getLocation('brief', true, 'EBC/EC');
        //CEE_Room__c room = CEE_TestUtility.getRoom('brief', true, loc, false, 6);
        
        //Setup briefing
        Opportunity opppt =  CEE_TestUtility.getOpty();
        CEE__c briefing = CEE_TestUtility.getBriefing('brief', true, 'OBX', acct, opppt, loc);
        Topic__c topic = CEE_TestUtility.getTopic('brief', true, false);
        //Agenda_Room__c agendaRoom = CEE_TestUtility.getAgendaRoom('brief', true, briefing, room);
        
        
        //Setup agenda item
        Agenda_Item__c agenda = CEE_TestUtility.getAgendaItem('brief', true, briefing, loc, null, topic);
        
        //Setup Presenter
        CEE_Attendee__c presenter = CEE_TestUtility.getAttendee('brief', true, briefing, agenda, true);
        CEE_Invite__c invite = CEE_TestUtility.getInvite('brief', true, briefing, presenter, agenda, null);
        CEE_TestUtility.simulatePresenterInvite(invite);
        
        Test.startTest();
        //Exception - has Outlook invite active
        try{
            delete presenter;
        } catch (Exception e){}
        
        invite.Outlook_Invite_ID__c = 'null';
        update invite;
        
        //Succeed
        delete presenter;
        Test.stopTest();
        
        //Check if presenter was deleted
        //System.assert(true, presenter.Id != null);
        //Check linkage is maintained between Invite and Presenter
        //System.assertEquals(invite.CEE_Attendee__c, presenter.Id);
    }
}