objects/Agenda_Room__c.object
<CustomObject>
    <label>Agenda Room</label>
    <nameField>
        <displayFormat>RM-{00000}</displayFormat>
        <label>Room Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agenda Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CEE__c.object
<CustomObject>
    <description>This object will store summary level briefing information from CEE. This Object is created to Integrate CEE Applicaiton data with Salesforce.com. It allows users to link CEE Briefings with Accounts in Salesforce.com.</description>
    <label>Customer Engagements &amp; Events</label>
    <nameField>
        <displayFormat>CEE-{000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Engagements &amp; Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>OBX</fullName>
        <active>true</active>
        <description>Delivering Demonstrations, Briefings, and Events</description>
        <label>Outcome Based Experience (OBX - formerly EBC)</label>
    </recordTypes>
</CustomObject>

objects/CEE_Location__c.object
<CustomObject>
    <description>The location details for a given Location, either a Field Sales Office (FSO), Executive Briefing Center (EBC), or Customer Briefing Center provided as part of the Customer Engagement implementation.</description>
    <label>CEE Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CEE Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CEE_Room__c.object
<CustomObject>
    <fields>
        <fullName>CEE_Location__c</fullName>
        <label>CEE Location</label>
        <referenceTo>CEE_Location__c</referenceTo>
        <relationshipLabel>CEE Rooms</relationshipLabel>
        <relationshipName>CEE_Rooms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>CEE Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CEE Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Topic__c.object
<CustomObject>
    <label>CEE Topic</label>
    <nameField>
        <label>Topic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CEE Topics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CEE_AgendaRoomEditController_Test.cls
/***************************************************************************************************
Name    : CEE_AgendaRoomEditController_Test 
Author  : Eric Pesch
Purpose : Tests for the Agenda Room Edit Visualforce Page  
Created Date: Dec 1 2014
Modification History: 
Eric Pesch - Jan 5 2015: Added Comments, cleanup                     
*****************************************************************************************************/

@isTest
private class CEE_AgendaRoomEditController_Test {

    /*@method: Agenda Room page new test method*/
    static testMethod void agendaRoomTestNew() {
        //Setup Account
        User admin = CEE_TestUtility.getUser('admin', true);
        Account acct = null;
        Opportunity oppty = null;
        CEE_Location__c loc = null;
        CEE_Room__c room = null;
        Opportunity opppt =  null;
        
        System.runAs(admin){
            CEE_TestUtility.loadCustomSettings();
            acct = CEE_TestUtility.getAccount('brief', true);
        
        //Setup location
        loc = CEE_TestUtility.getLocation('brief', true, 'EBC/EC');
        room = CEE_TestUtility.getRoom('brief', true, loc, false, 6);
        
        //Setup briefing
        opppt =  CEE_TestUtility.getOpty();
        }
        CEE__c briefing = CEE_TestUtility.getBriefing('brief', true, 'OBX', acct, opppt, loc);
        Topic__c topic = CEE_TestUtility.getTopic('brief', true, false);

        //TEST = setup agenda Room      
        Agenda_Room__c agendaRoom = CEE_TestUtility.getAgendaRoom('brief', false, briefing, room);
        ApexPages.StandardController stdItem = new ApexPages.StandardController(agendaRoom);
        CEE_AgendaRoomEditController roomController = new CEE_AgendaRoomEditController(stdItem);
        
        //Utility methods
        roomController.getRoomOptions();
        roomController.setRoomOptions(null);

        
        //Save
        roomController.doSaveNew();
        roomController.doSave(true);
        roomcontroller.docancel();
    }
    
    /*@method: Agenda Room old update/insert test*/
    static testMethod void agendaRoomTest() {
        //Setup Account
        User admin = CEE_TestUtility.getUser('admin', true);
        Account acct = null;
        Opportunity oppty = null;
        Opportunity opppt =null;
        CEE_Location__c loc =null;
        CEE_Room__c room =null;
        System.runAs(admin){
            CEE_TestUtility.loadCustomSettings();
            acct = CEE_TestUtility.getAccount('brief', true);
        
        
        //Setup location
        loc = CEE_TestUtility.getLocation('brief', true, 'EBC/EC');
        room = CEE_TestUtility.getRoom('brief', true, loc, false, 6);
        
        //Setup briefing
         opppt =  CEE_TestUtility.getOpty();
        }
        CEE__c briefing = CEE_TestUtility.getBriefing('brief', true, 'OBX', acct, opppt, loc);
        Topic__c topic = CEE_TestUtility.getTopic('brief', true, false);
        Agenda_Room__c agendaRoom = CEE_TestUtility.getAgendaRoom('brief', true, briefing, room);
        
        Test.startTest();
        ApexPages.StandardController stdItem = new ApexPages.StandardController(agendaRoom);
        CEE_AgendaRoomEditController roomController = new CEE_AgendaRoomEditController(stdItem);
        
        //Utility methods
        
        roomController.getRoomOptions();
        roomController.setRoomOptions(null);

        
        //Save
        roomController.doSaveNew();
        roomController.doSave(true);
        

        Test.stopTest();
    }
    
}