objects/Agenda_Room__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Briefing_Status__c</fullName>
        <label>Briefing Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Briefing_Type__c</fullName>
        <label>Briefing Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Engagements_Events__c</fullName>
        <label>Customer Engagements &amp; Events</label>
        <referenceTo>CEE__c</referenceTo>
        <relationshipLabel>Rooms</relationshipLabel>
        <relationshipName>Agenda_Rooms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <defaultValue>NULL</defaultValue>
        <label>End Date Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Room_Name__c</fullName>
        <label>Room Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Room__c</fullName>
        <label>Room</label>
        <referenceTo>CEE_Room__c</referenceTo>
        <relationshipLabel>Agenda Rooms</relationshipLabel>
        <relationshipName>Agenda_Rooms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <defaultValue>Null</defaultValue>
        <label>Start Date/Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Agenda Room</label>
    <nameField>
        <displayFormat>RM-{00000}</displayFormat>
        <label>Room Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agenda Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Briefing_Site__c.object
<CustomObject>
    <fields>
        <fullName>Additional_Participant_Location__c</fullName>
        <inlineHelpText>Additional Location to tie to Customer Engagement.</inlineHelpText>
        <label>Additional Participant Location</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 OR 2) AND 3</booleanFilter>
            <errorMessage>Location must be active in order to select.</errorMessage>
            <filterItems>
                <field>CEE_Location__c.Is_Location_Active__c</field>
                <operation>equals</operation>
                <value>Yes</value>
            </filterItems>
            <filterItems>
                <field>$User.Id</field>
                <operation>equals</operation>
                <value>005300000010pIr</value>
            </filterItems>
            <filterItems>
                <field>CEE_Location__c.Location_Type__c</field>
                <operation>notEqual</operation>
                <value>CPOC</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CEE_Location__c</referenceTo>
        <relationshipLabel>Briefing Sites</relationshipLabel>
        <relationshipName>Briefing_Sites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Customer_Engagements_Events__c</fullName>
        <inlineHelpText>Related Customer Engagement for additional Briefing Site.</inlineHelpText>
        <label>Customer Engagements &amp; Events</label>
        <referenceTo>CEE__c</referenceTo>
        <relationshipLabel>Briefing Sites</relationshipLabel>
        <relationshipName>Briefing_Sites</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <description>Additional Field Sales Offices (FSO) attached to Customer Engagement requests.</description>
    <label>Briefing Site</label>
    <nameField>
        <displayFormat>SITE-{00000}</displayFormat>
        <label>Site Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Briefing Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CEE__c.object
<CustomObject>
    <fields>
        <fullName>Briefing_Status__c</fullName>
        <description>Request status</description>
        <label>Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <defaultValue>DATETIMEVALUE(Today()+11)</defaultValue>
        <inlineHelpText>Shown in User's Local Timezone</inlineHelpText>
        <label>End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Primary_FSO__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Primary site is lookup field from CEE Location object, it is related to CPOC lab request.</description>
        <inlineHelpText>Field Sales Office</inlineHelpText>
        <label>Primary Site</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4 AND 6) OR (5)</booleanFilter>
            <errorMessage>The chosen Primary Site does not match the filter criteria of the EBC/EC and Other/FSO Location field.</errorMessage>
            <filterItems>
                <field>$Source.EBC_CBC_Location__c</field>
                <operation>equals</operation>
                <valueField>CEE_Location__c.Name</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.EBC_CBC_Location__c</field>
                <operation>notEqual</operation>
                <value>Other/FSO</value>
            </filterItems>
            <filterItems>
                <field>$Source.EBC_CBC_Location__c</field>
                <operation>equals</operation>
                <value>Other/FSO</value>
            </filterItems>
            <filterItems>
                <field>CEE_Location__c.Is_Location_Active__c</field>
                <operation>equals</operation>
                <value>Yes</value>
            </filterItems>
            <filterItems>
                <field>$User.Id</field>
                <operation>equals</operation>
                <value>005300000010pIr</value>
            </filterItems>
            <filterItems>
                <field>CEE_Location__c.Name</field>
                <operation>notContain</operation>
                <value>CPOC</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CEE_Location__c</referenceTo>
        <relationshipLabel>Customer Engagements &amp; Events (Primary Site)</relationshipLabel>
        <relationshipName>Customer_Engagement_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Room_Name__c</fullName>
        <label>Room Name</label>
        <length>131000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <defaultValue>DATETIMEVALUE(Today() + 10)</defaultValue>
        <inlineHelpText>Shown in User's Local Timezone</inlineHelpText>
        <label>Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Timezone__c</fullName>
        <description>Timezone picklist field (primarily for ITCE engagements)</description>
        <label>Timezone</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>(UTC-11:00) Samoa Standard Time (Pacific/Pago_Pago)</fullName>
                </value>
                <value>
                    <fullName>(UTC-11:00) Niue Time (Pacific/Niue)</fullName>
                </value>
                <value>
                    <fullName>(UTC-10:00) Hawaii-Aleutian Standard Time (America/Atka)</fullName>
                </value>
                <value>
                    <fullName>(UTC-10:00) Hawaii Standard Time (Pacific/Honolulu)</fullName>
                </value>
                <value>
                    <fullName>(UTC-09:30) Marquesas Time (Pacific/Marquesas)</fullName>
                </value>
                <value>
                    <fullName>(UTC-09:00) Gambier Time (Pacific/Gambier)</fullName>
                </value>
                <value>
                    <fullName>(UTC-09:00) Alaska Daylight Time (America/Anchorage)</fullName>
                </value>
                <value>
                    <fullName>(UTC-08:00) Pitcairn Standard Time (Pacific/Pitcairn)</fullName>
                </value>
                <value>
                    <fullName>(UTC-08:00) Pacific Standard Time (America/Tijuana)</fullName>
                </value>
                <value>
                    <fullName>(UTC-08:00) Pacific Daylight Time (America/Los_Angeles)</fullName>
                </value>
                <value>
                    <fullName>(UTC-07:00) Mountain Standard Time (Mexico/BajaSur)</fullName>
                </value>
                <value>
                    <fullName>(UTC-07:00) Mountain Standard Time (America/Phoenix)</fullName>
                </value>
                <value>
                    <fullName>(UTC-07:00) Mountain Daylight Time (America/Denver)</fullName>
                </value>
                <value>
                    <fullName>(UTC-06:00) Central Standard Time (America/Mexico_City)</fullName>
                </value>
                <value>
                    <fullName>(UTC-06:00) Central Standard Time (America/El_Salvador)</fullName>
                </value>
                <value>
                    <fullName>(UTC-06:00) Central Daylight Time (America/Chicago)</fullName>
                </value>
                <value>
                    <fullName>(UTC-05:00) Eastern Standard Time (America/Panama)</fullName>
                </value>
                <value>
                    <fullName>(UTC-05:00) Eastern Daylight Time (America/New_York)</fullName>
                </value>
                <value>
                    <fullName>(UTC-05:00) Peru Time (America/Lima)</fullName>
                </value>
                <value>
                    <fullName>(UTC-05:00) Eastern Daylight Time (America/Indianapolis)</fullName>
                </value>
                <value>
                    <fullName>(UTC-05:00) Colombia Time (America/Bogota)</fullName>
                </value>
                <value>
                    <fullName>(UTC-04:30) Venezuela Time (America/Caracas)</fullName>
                </value>
                <value>
                    <fullName>(UTC-04:00) Atlantic Daylight Time (Atlantic/Bermuda)</fullName>
                </value>
                <value>
                    <fullName>(UTC-04:00) Chile Summer Time (America/Santiago)</fullName>
                </value>
                <value>
                    <fullName>(UTC-04:00) Atlantic Standard Time (America/Puerto_Rico)</fullName>
                </value>
                <value>
                    <fullName>(UTC-04:00) Atlantic Daylight Time (America/Halifax)</fullName>
                </value>
                <value>
                    <fullName>(UTC-03:30) Newfoundland Daylight Time (America/St_Johns)</fullName>
                </value>
                <value>
                    <fullName>(UTC-03:00) Brasilia Summer Time (America/Sao_Paulo)</fullName>
                </value>
                <value>
                    <fullName>(UTC-03:00) Argentine Summer Time (America/Buenos_Aires)</fullName>
                </value>
                <value>
                    <fullName>(UTC-02:00) South Georgia Standard Time (Atlantic/South_Georgia)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>This object will store summary level briefing information from CEE. This Object is created to Integrate CEE Applicaiton data with Salesforce.com. It allows users to link CEE Briefings with Accounts in Salesforce.com.</description>
    <label>Customer Engagements &amp; Events</label>
    <nameField>
        <displayFormat>CEE-{000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Engagements &amp; Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CEE_Location__c.object
<CustomObject>
    <fields>
        <fullName>Site_Time_Zone__c</fullName>
        <label>Site Time Zone</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <description>The location details for a given Location, either a Field Sales Office (FSO), Executive Briefing Center (EBC), or Customer Briefing Center provided as part of the Customer Engagement implementation.</description>
    <label>CEE Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CEE Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CEE_Room__c.object
<CustomObject>
    <fields>
        <fullName>CEE_Location__c</fullName>
        <label>CEE Location</label>
        <referenceTo>CEE_Location__c</referenceTo>
        <relationshipLabel>CEE Rooms</relationshipLabel>
        <relationshipName>CEE_Rooms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>CEE Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CEE Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CEE_AgendaRoomEditController.cls
/***************************************************************************************************
Name    : CEE_AgendaRoomEditController 
Author  : Eric Pesch
Purpose : Visualforce Page Controller for custom Agenda Room page  
Created Date: Dec 22 2014
Modification History: 
Eric Pesch - Jan 5 2015: Added Comments, cleanup      
Sourabha - June 19 2015 - Added enhancements for CCE2 June release.               
*****************************************************************************************************/

public class CEE_AgendaRoomEditController {
    
    // SCAVA Helper Method
     public static Boolean flsGet(SObjectField field)
    {
        return field.getDescribe().isCreateable() ? true : false;
    }
    // SCAVA Helper Method to validate Update Access at field level
     public static Boolean flsUpdate(SObjectField field)
    {
        return field.getDescribe().isUpdateable() ? true : false;
    }
    
    //Record and controller variables
    private final String TAG = 'CEE_AgendaRoomEditController';
    private Agenda_Room__c room;
    private final ApexPages.StandardController controller;
    
    //Related object list variables
    public CEE__c briefing { get; set; }
    private List<Agenda_Room__c> briefingRooms;
    private List<Briefing_Site__c> sites;    
    private List<CEE_Room__c> siteRooms;
    
    //Page display variables
    public String pageUrl { get; set; }
    public String pageDisplay { get; set; }
    public Boolean isNew { get; set; }
    public String roomName { get; set; }
    
    //Room variables
    public String selRoom { get; set; }
    
    //Time variables
    public String siteStartTime { get; set; }
    public String siteEndTime { get; set; }
   
    /*@method: Save and New button click*/
    public PageReference doSaveNew(){
        return doSave(true);
    }
    /*@method: ONLY Save button click*/
    public PageReference doSave(){
        return doSave(false);
    }
    /*@method: Generic save function*/
    public PageReference doSave(boolean isSaveNew){
        
        if(String.isEmpty(selRoom)){
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.WARNING,'Invalid or no Room selected'));
            return null;
        }
        
        //Save the attendee record
        try{
            if(room.Id == null){
                // SCAVA FIX
                if(flsGet(Agenda_Room__c.Room__c)|| flsUpdate(Agenda_Room__c.Room__c))
                {
                room.Room__c = selRoom; 
                }
                insert room;
            } else {
                
                if(room.room__c!=selroom){
                    ApexPages.addMessage(new ApexPages.message(ApexPages.severity.WARNING,'Room cannot be changed'));
                    return null;
                 }
                else
                    update room;
            }
        } catch(Exception e){
            System.debug(e.getStackTraceString());
            ApexPages.addMessages(e);
            return null;
        }
        
        //Save-New behavior
        if(isSaveNew){
            //String editID = '/' + ('' + room.get('Id')).subString(0, 3) + '/e?';
            //SCAVA FIX
            String editID =  ('' + room.get('Id')).subString(0, 3) + '/e?';
            Map<String, String> parameters = ApexPages.currentPage().getParameters();
            
            //Grab lookup field prefix            
            String prefix = Utilities.getConstant_CS('CEE Field Prefix');
            
            //Relate associated page parameters
            for(String key : parameters.keySet()){
                String value = parameters.get(key);
                if(key.contains(prefix)){             
                    editId += key + '=' + value + '&';
                } else if (key.equals('retURL')) {
                    editId += key + '=' + value + '&';
                }
                System.debug(TAG + 'key/value - ' + key + ' / ' + value);
            }
            editId = editId.substring(0,editId.length()-1);         
            
            // return new PageReference(editId);
           //SCAVA FIX
            return new PageReference('/' +editId);
        }
        
        //Briefing return
        return new PageReference('/'+room.Customer_Engagements_Events__c);
    }

    /*@Constructor: Controller construction and initialization*/
    public CEE_AgendaRoomEditController(ApexPages.StandardController stdController){
        List<String> popFields = new List<String>{'Id', 'Name', 'Account_Name__c', 'Briefing_Status__c','Briefing_Type__c', 'Customer_Engagements_Events__c', 
            'End_Date_Time__c','Room__c','Room_Name__c','Start_Date_Time__c'};
        List<String> locations = new List<String>();
        
        this.controller = stdController;
        if(!Test.isRunningTest()){
            this.controller.addFields(popFields);
        }
        this.room = (Agenda_Room__c)stdController.getRecord();
        this.pageDisplay = 'New Agenda Room'; //default behavior
        this.pageUrl = ApexPages.currentPage().getUrl();
        this.isNew = true;
        
        //Populate briefing sites
        try{
            briefing = [select Id, Primary_FSO__c, Start_Date_Time__c, End_Date_Time__c, Primary_FSO__r.Site_Time_Zone__c, Timezone__c from CEE__c 
                        where Id =: room.Customer_Engagements_Events__c];
            sites = [select Id, Additional_Participant_Location__c from Briefing_Site__c where Customer_Engagements_Events__c =: room.Customer_Engagements_Events__c];
        } catch(Exception e){
            System.debug(TAG + 'Error retrieving Briefing - ' + e.getStackTraceString());
        }
        
        //Populate default variables
        if(this.room.Id != null){
            isNew = false;
            if(room.Name != null){
                roomName = room.Name;
                pageDisplay = room.Name;
            }
            selRoom = room.Room__c;
        } else {
            // SCAVA Fix
            if(flsGet(Agenda_Room__c.Start_Date_Time__c)||flsUpdate(Agenda_Room__c.Start_Date_Time__c)) {
            room.Start_Date_Time__c = briefing.Start_Date_Time__c;
            }
            if(flsGet(Agenda_Room__c.End_Date_Time__c)||flsUpdate(Agenda_Room__c.End_Date_Time__c)) {
            room.End_Date_Time__c = briefing.End_Date_Time__c;
            }
        }
        siteStartTime = CEE_Utility.calcSiteTime(briefing, briefing.Start_Date_Time__c);
        siteEndTime = CEE_Utility.calcSiteTime(briefing, briefing.End_Date_Time__c);
        
        //Get rooms - Primary Site OR Briefing Sites
        for(Briefing_Site__c site : sites){
            locations.add(site.Additional_Participant_Location__c);
        }
        if(briefing != null){
            locations.add(briefing.Primary_FSO__c);
        }
        System.debug(TAG + 'location - ' + locations);
        
        try{
            //Get briefing Rooms
            List<Id> oldBriefingRooms = new List<Id>();
            briefingRooms = [select Id, Name, Room__c from Agenda_Room__c where Customer_Engagements_Events__c =: room.Customer_Engagements_Events__c
                            and Id !=: room.Id];
            for(Agenda_Room__c briefingRoom : briefingRooms){
                oldBriefingRooms.add(briefingRoom.Room__c);
            }
            
            //Filter sites by locations and not added already
            siteRooms = [select Id, Name, CEE_Location__c, CEE_Location__r.Name from CEE_Room__c where CEE_Location__c IN : locations
                        AND Id NOT IN : oldBriefingRooms];
        } catch (Exception e){
            System.debug(TAG + 'Error retrieving Room Options - ' + e.getStackTraceString());
        }
    }
    
            /* **********************************************************
           Added By Naresh (nkalahas@cisco.com) on 31/01/2018  to redirect to previous page on cancel
       ************************************************************  */          

       public PageReference doCancel() {
        String url = ApexPages.currentPage().getHeaders().get('Referer');

        
        PageReference pageRef = new PageReference('/' + room.Customer_Engagements_Events__c );
        pageRef.setRedirect(true);
        return pageRef; 


        }
    
    /*@method: Getter for Select Room Picklist*/
    public List<SelectOption> getRoomOptions(){
        List<SelectOption> roomOptions = new List<SelectOption>();
        
        for(CEE_Room__c siteRoom : siteRooms){
            roomOptions.add(new SelectOption(siteRoom.Id, siteRoom.CEE_Location__r.Name + ' - ' + siteRoom.Name));
        }
        
        if(roomOptions.size() == 0){
            roomOptions.add(new SelectOption('','No CEE Rooms found for Briefing Sites',true));
        } else {
            roomOptions.add(new SelectOption('','--None--'));
        }
        
        roomOptions.sort();
        return roomOptions;
    }
    public void setRoomOptions(List<SelectOption> rooms){ }
}