objects/Agenda_Room__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Engagements_Events__c</fullName>
        <label>Customer Engagements &amp; Events</label>
        <referenceTo>CEE__c</referenceTo>
        <relationshipLabel>Rooms</relationshipLabel>
        <relationshipName>Agenda_Rooms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Room_Name_Dataloder__c</fullName>
        <formula>Room__r.Display_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Room Name Dataloder</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Room_Name__c</fullName>
        <label>Room Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Agenda Room</label>
    <nameField>
        <displayFormat>RM-{00000}</displayFormat>
        <label>Room Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agenda Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CEE__c.object
<CustomObject>
    <fields>
        <fullName>Room_Name__c</fullName>
        <label>Room Name</label>
        <length>131000</length>
        <type>LongTextArea</type>
    </fields>
    <description>This object will store summary level briefing information from CEE. This Object is created to Integrate CEE Applicaiton data with Salesforce.com. It allows users to link CEE Briefings with Accounts in Salesforce.com.</description>
    <label>Customer Engagements &amp; Events</label>
    <nameField>
        <displayFormat>CEE-{000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Engagements &amp; Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ObjectRecordTypeIds__c.object
<CustomObject>
    <fields>
        <fullName>CEE_OBX_Record_Type_ID__c</fullName>
        <label>CEE OBX Record Type ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is used to store the record type ids of account and contact objects.</description>
    <label>Object Record Type Ids</label>
</CustomObject>

classes/RoomUpdateBatch.cls
/***************************************************************************************************
Name    : CEE_AgendaItemController 
Author  : Bramha
Purpose : Batch class to update CEE Roomname frm Related Lists
Created Date: Dec 1 2014
Modification History: 
May'2015 WR-01089 - bdabbara : Added doSaveNew() method for new "Save & New" button action
*****************************************************************************************************/ 
global with sharing class RoomUpdateBatch implements Database.Batchable<sObject>{
      
        private final string query;
        
        global RoomUpdateBatch(String query)
        {
            this.query = query;
        } 
        
        global Database.QueryLocator start(Database.BatchableContext BC)
        {     
            system.debug('query-->'+query);    
            return Database.getQueryLocator(query);             
        }
                
        global void execute(Database.BatchableContext BC, List<sObject> scope)
        { 
            
            set<string> ceeIDs = new set<string>();       
            List<cee__c> updateCECS  = new List<cee__c>();
            List<cee__c> updateCECS1  = new List<cee__c>();
            Map<string,string> agendaRoomsMapNew=new Map<string,string>();
            string obxTypeId = ObjectRecordTypeIds__c.getorgdefaults().CEE_OBX_Record_Type_ID__c;   
            for(Agenda_Room__c aNew: (List<Agenda_Room__c>)scope){ 
                if(aNew.Room_Name_Dataloder__c != null){                                  
                    ceeIDs.add(aNew.Customer_Engagements_Events__c);                    
                    agendaRoomsMapNew.put(aNew.Customer_Engagements_Events__c,aNew.Room_Name_Dataloder__c);  
                            
                }
            }
            
            if(!ceeIDs.isEmpty()){
                updateCECS = [select room_name__c,id from cee__c where id in :ceeIDs and RecordTypeId =: obxTypeId ];                
                system.debug('%%updateCECS'+updateCECS);
                 for(cee__c c:updateCECS){                    
                    if(c.room_name__c==null){
                        c.room_name__c=agendaRoomsMapNew.get(c.id);                 
                    }
                    else{
                        if(!c.room_name__c.contains(agendaRoomsMapNew.get(c.id)))
                            c.room_name__c=c.room_name__c+', '+agendaRoomsMapNew.get(c.id);                            
                    }                   
                } 
                try{
                    update updateCECS;
                }catch(Exception e){
                    system.debug('Exception'+e);
                }
            }   
        }
        global void finish(Database.BatchableContext BC)
        {
           System.debug('Job Completed');  
        }   
    }