objects/Apex_Batch_Job__c.object
<CustomObject>
    <fields>
        <fullName>query__c</fullName>
        <label>query</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Used to store the query and notification email id for batch process.</description>
    <label>Apex Batch Job</label>
</CustomObject>

classes/ScheduleOfferTaskScheduleBatchApex.cls
/************************************************************************************************************************************
Name    : ScheduleOfferTaskScheduleBatchApex
Author  : C360 Dev team
Purpose : Contains logic to Implement ScheduleOfferTask batch apex Scheduler
Date    : 25/01/2019
Change History : none
*************************************************************************************************************************************/

global class ScheduleOfferTaskScheduleBatchApex implements Schedulable {
Public String query = Apex_Batch_Job__c.getInstance('ScheduleOfferTask').query__c;
global void execute(SchedulableContext sc)
     {         
        ScheduleOfferTask load = new ScheduleOfferTask(query);
        ID JobId = Database.executeBatch(load,100);  
     }
}