objects/Apex_Batch_Job__c.object
<CustomObject>
    <fields>
        <fullName>query1__c</fullName>
        <label>query1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>query__c</fullName>
        <label>query</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Used to store the query and notification email id for batch process.</description>
    <label>Apex Batch Job</label>
</CustomObject>

objects/Offer__c.object
<CustomObject>
    <fields>
        <fullName>Annual_Recurring_Revenue_ARR__c</fullName>
        <inlineHelpText>ARR represents software subscription and services</inlineHelpText>
        <label>Annual Recurring Revenue (ARR)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Next_Contract_Renewal_Date__c</fullName>
        <inlineHelpText>Next Contract Renewal Date will default to contract with the next upcoming end date that is in this offer</inlineHelpText>
        <label>Next Contract Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Offer_Level_1_Name__c</fullName>
        <label>Offer Level 1 Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Term_Length__c</fullName>
        <inlineHelpText>Term Length is the average of all contract renewal dates for this offer</inlineHelpText>
        <label>Term Length</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tier_Support__c</fullName>
        <inlineHelpText>Tier Support will default to the highest level of support where more than one record is found</inlineHelpText>
        <label>Tier Support</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <description>Contains Cisco's Product details for Customer Success Program</description>
    <label>Offer</label>
    <nameField>
        <label>Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Task_Master__c.object
<CustomObject>
    <fields>
        <fullName>IsNewTask__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsNewTask</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Offer_Name__c</fullName>
        <label>Offer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_Name__c</fullName>
        <label>Task Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Task_Stage__c</fullName>
        <label>Task Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Purchase</fullName>
                </value>
                <value>
                    <fullName>Onboard</fullName>
                </value>
                <value>
                    <fullName>Implement</fullName>
                </value>
                <value>
                    <fullName>Use</fullName>
                </value>
                <value>
                    <fullName>Engage</fullName>
                </value>
                <value>
                    <fullName>Adopt</fullName>
                </value>
                <value>
                    <fullName>Optimize</fullName>
                </value>
                <value>
                    <fullName>Advocate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Task_Type__c</fullName>
        <label>Task Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ACTIVITIES</fullName>
                </value>
                <value>
                    <fullName>EXIT CRITERIA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>C360 : Static table for all offer activities</description>
    <label>Task Master</label>
    <nameField>
        <displayFormat>T-{000}</displayFormat>
        <label>Task Master Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ScheduleOfferTaskTest.cls
/************************************************************************************************************************************
Name    : ScheduleOfferTaskTest
Author  : C360 Dev team
Purpose : Contains logic to execute test case for a Batch class which works on Offer Task
Date    : 24/01/2019
*************************************************************************************************************************************/
@isTest(SeeallData=False)
public class ScheduleOfferTaskTest {

static testMethod void testMethod1() 
    {
        List<Offer__c> lstOffer= new List<Offer__c>();
        for(Integer i=0 ;i <2;i++)
        {
            Offer__c off = new Offer__C();
            off.Name ='OfferName'+i;
            off.Offer_Level_1_Name__c='OfferName'+i;
            lstOffer.add(off);
        }
        
        insert lstOffer;
         List<ID> offerId  = new List<ID>();
        for( Offer__c offid : lstOffer )
        {
            offerId.add(offid.Id);
         
        }       
        
        List<Task_Master__c> Tsm = new List<Task_Master__c>();
        for(Integer i=0; i<5;i++)
        {
            Task_Master__C ts = new Task_Master__C();
            ts.Task_Name__c ='TaskName'+i;
            
            
            ts.Offer_Name__c ='OfferName'+i;
            Tsm.add(ts);
        }
        insert tsm;
        
        List<Task> Ots = new List<Task>();
        for(Offer__c off : lstOffer )
        for(Task_Master__c ts : tsm)
        {
            if(off.Offer_Level_1_Name__c == ts.Offer_Name__c){
            Task ts1 = new Task();
            ts1.Task_Name__c=ts.Task_Name__c;
               ts1.Task_Stage__c='Purchase';
               ts1.Task_Type__c='ACTIVITIES';
              
               
                
              
               ots.add(ts1);
            }
        }
        insert ots;
         List<Task> Ots2 = new List<Task>();
        {
           Task ts1 = new Task();
               ts1.Task_Stage__c='Implement' ;
            ts1.Description='Additional Notes Text';
            ts1.Id=ots[1].Id;
               ots2.add(ts1);
            
        }
        
        update ots2;
        
         Offer__c off = new Offer__C();
            off.Name ='OfferName';
            off.Offer_Level_1_Name__c='OfferName';
        off.Annual_Recurring_Revenue_ARR__c = 100000;
            off.Tier_Support__c = 'Level1';
            off.Term_Length__c = '2 Years';
            off.Next_Contract_Renewal_Date__c =system.Today();
        insert off;
          
      Id offID = off.Id;
        
        String Stage='Purchase';
        String NullString ='';
        
        Set<string> subjectSet = new Set<string>();      
       for(Task t : [SELECT Id,WhatId FROM Task where What.Type='Offer__c']){
       subjectSet.add(t.WhatId);
       }
       
        Apex_Batch_Job__c setting = new Apex_Batch_Job__c();
        setting.Name = 'ScheduleOfferTask';
        setting.query__c = 'SELECT Id,Name, Offer_Level_1_Name__c FROM Offer__c limit 1';
        setting.query1__c = 'SELECT name,Task_Name__c,Task_Stage__c,Task_Type__c,Offer_Name__c FROM Task_Master__c WHERE IsNewTask__c = False';
        insert setting;
        
        
        Test.startTest();
            //Apex_Batch_Job__c abj = Apex_Batch_Job__c.getValues('Test Setting'); 
           // system.debug('abj--->'+abj);
           // String query = abj.query__c;
            ScheduleOfferTaskScheduleBatchApex sOffer = new ScheduleOfferTaskScheduleBatchApex();
            String sch = '0 0 8 13 2 ?';
            //ScheduleOfferTask obj = new ScheduleOfferTask(query);
            String jobIds = System.schedule('testBasicScheduledApex',sch,sOffer);
            //Id JobId = DataBase.executeBatch(obj,200);
            
        Test.stopTest();
    }
}