objects/Assigned_Partner__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_Partner_Sales_Rep_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned Partner Sales Rep 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assigned_Partners4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assigned_Partner_Sales_Rep_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned Partner Sales Rep 3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assigned_Partners3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assigned_Partner_Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sales Rep from the partner assigned to this target account.</description>
        <label>Assigned Partner Sales Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assigned_Partners_Sales_Rep</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assigned_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Partner Account assigned to this target account.</description>
        <label>Assigned Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Assigned_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Status__c</fullName>
        <label>Partner Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned (New)</fullName>
                    <default>true</default>
                    <label>Assigned (New)</label>
                </value>
                <value>
                    <fullName>Partner Assigned</fullName>
                </value>
                <value>
                    <fullName>Assigned to PSR</fullName>
                </value>
                <value>
                    <fullName>Actively Working</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Partner assignments of End User Accounts are stored in this object.</description>
    <label>zzTarget Prospect</label>
    <nameField>
        <label>Target Prospect Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Target Prospects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Channel_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created for P360 2A development.</description>
        <label>Channel Partner</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2)</booleanFilter>
            <errorMessage>The selected Partner is not a SCP registered active partner or is flagged on the Denied Partner List, please select a valid SCP registered partner.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Channel</value>
            </filterItems>
            <filterItems>
                <field>Account.Partner_Assignment_Eligible__c</field>
                <operation>greaterOrEqual</operation>
                <value>1</value>
            </filterItems>
            <infoMessage>This search will return only those partners enrolled in the Sales Collaboration Platform program. However, if you would like to reference accounts eligible for lead assignment, refer to the P360 Partners Enrolled link on the left hand side of the screen.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assigned Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSR_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Partner Sales Rep One</description>
        <label>Assigned Partner Sales Rep 1</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>User.ProfileId</field>
                <operation>equals</operation>
                <value>00en0000000Hg4k</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSR_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Partner Sales Rep 2</description>
        <label>Assigned Partner Sales Rep 2</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>User.Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Channel_Partner__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Leads2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSR_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Partner Sales Rep 3</description>
        <label>Assigned Partner Sales Rep 3</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>No contact exist under account</errorMessage>
            <filterItems>
                <field>User.Contact.AccountId</field>
                <operation>startsWith</operation>
                <valueField>$Source.Channel_Partner__c</valueField>
            </filterItems>
            <infoMessage>Filter on PSR3 lookup</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Leads3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Lead_Status__c</fullName>
        <description>This field is created for P360 2A Development</description>
        <label>Partner Lead Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Partner Assigned</fullName>
                </value>
                <value>
                    <fullName>Assigned To PSR</fullName>
                </value>
                <value>
                    <fullName>Actively Working</fullName>
                </value>
                <value>
                    <fullName>Deal Created</fullName>
                </value>
                <value>
                    <fullName>Rejected-Invalid Contact</fullName>
                </value>
                <value>
                    <fullName>Rejected-Already Deal</fullName>
                </value>
                <value>
                    <fullName>Rejected-Project Canceled</fullName>
                </value>
                <value>
                    <fullName>Rejected-Lost to Competition</fullName>
                </value>
                <value>
                    <fullName>Rejected-Not My Territory/Account</fullName>
                </value>
                <value>
                    <fullName>Rejected-No Customer Response</fullName>
                </value>
                <value>
                    <fullName>Rejected-Duplicate</fullName>
                </value>
                <value>
                    <fullName>Rejected-No Valid Project</fullName>
                </value>
                <value>
                    <fullName>Closed-Order Through Stock</fullName>
                </value>
                <value>
                    <fullName>Closed-Order Through Disti</fullName>
                </value>
                <value>
                    <fullName>Closed-Order Through Cisco</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Status__c</fullName>
        <description>PLOC field, indicates the lead status as determined by the partner.</description>
        <label>TO_BE_DELETED_Partner Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Accepted/In Progress</fullName>
                </value>
                <value>
                    <fullName>Confirmed Sales Project</fullName>
                </value>
                <value>
                    <fullName>Rejected - Already Opportunity</fullName>
                </value>
                <value>
                    <fullName>Rejected - Project Cancelled</fullName>
                </value>
                <value>
                    <fullName>Rejected - Lost to Competition</fullName>
                </value>
                <value>
                    <fullName>Rejected - No Customer Response</fullName>
                </value>
                <value>
                    <fullName>Rejected - Invalid/No Interest</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <businessProcess>NGCC Marketing Lead</businessProcess>
        <description>Prospect Leads from Next Gen Marketing Contact Center</description>
        <label>Prospect</label>
    </recordTypes>
</CustomObject>

objects/Org_Constant_CS__c.object
<CustomObject>
    <fields>
        <fullName>Production_Value__c</fullName>
        <label>Production Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>Org Constant CS</label>
</CustomObject>

classes/P360_ReassignLeadsandTPsonDeactivedUser.cls
/*
 Description : Automatically reassign leads and target prospects to a current PA when PSRs are deactivated
 
         Lead:
                - Inactive PSR on the Lead record should be removed from the Lead record.
                - If there are no other PSR assigned on the Lead, then Partner Status on the Lead record should be re-set to "Partner Assigned" status.
                - Only Leads with Partner Status as  "Actively Working" and "Assigned to PSR" should be considered for the Re-set.
Target Prospect:
                - Inactive PSR on the TP record should be removed from the TP record
                - If there are no other PSR assigned on the TP, then Partner status on the TP record should be re-set to "Partner Assigned" status and TP should remain "Activated".
                - Only Active TP records with "Actively Working" and "Assigned to PSR" should be considered for the Re-Set.
 
*/

public class P360_ReassignLeadsandTPsonDeactivedUser {
    
    // SCAVA Helper Method to validate Update Access at field level
     public static Boolean flsUpdate(SObjectField field)
    {
        return field.getDescribe().isUpdateable() ? true : false;
    }

    
    public static void ReassignLeadsandTPsDirect(set<Id> setUser){
        ReassignLeadsandTPsProcess(setUser);    
    }
    
    @future
    public static void ReassignLeadsandTPsFuture(set<Id> setUser){
        ReassignLeadsandTPsProcess(setUser);    
    }

 public static void ReassignLeadsandTPsProcess(set<Id> setUser)
 {  
    //Initialize variable.
    list<lead> lstLead = new list<lead>();
    list<Assigned_Partner__c> lstTP = new list<Assigned_Partner__c>();
    boolean bval=false;
    string activelyWorking = Org_Constant_CS__c.getValues('P360 Actively working').Production_Value__c;
    string partnerAssigned = Org_Constant_CS__c.getValues('P360 Partner Assigned').Production_Value__c;                
    string assignedtoPSR = Org_Constant_CS__c.getValues('P360 Assigned to PSR').Production_Value__c; 
    
    //iterate leads filter by userset ids.
    for(lead l:[select id,Partner_Lead_Status__c,Channel_Partner__c,PSR_1__c,PSR_2__c,PSR_3__c from lead where (Partner_Lead_Status__c =:activelyWorking or Partner_Lead_Status__c =:assignedtoPSR) and (PSR_1__c IN: setUser or PSR_2__c IN: setUser or PSR_3__c IN: setUser) ])
    {
         bval = false;
         
        //check whether psr 1,2,3 values exist in userset.
        if(setUser.contains(l.PSR_1__c))
        {
            //SCAVA FIX
            if(flsUpdate(Lead.PSR_1__c))
            {
            l.PSR_1__c =null; 
            }
            bval = true;            
        }
        if(setUser.contains(l.PSR_2__c))
        {
            if(flsUpdate(Lead.PSR_2__c))
            {
            l.PSR_2__c = null; 
            }
            bval = true;            
        }
        if(setUser.contains(l.PSR_3__c))
        {
            if(flsUpdate(Lead.PSR_3__c))
            {
            l.PSR_3__c = null;
            }
            bval = true;
        }
        
        
        if(bval)
        {   
            //check whether psr 1,2,3 has values.       
            if(l.PSR_1__c !=null || l.PSR_2__c !=null || l.PSR_3__c !=null)
            {    
            //SCAVA FIX
            if(flsUpdate(Lead.Partner_Lead_Status__c))
            {       
                l.Partner_Lead_Status__c = assignedtoPSR;
            }
            }
            else
            {
                l.Partner_Lead_Status__c = partnerAssigned;
            }           
            
            //add to list.
            lstLead.add(l);
        }
                
     }
     
     //Iterate Target Prospect filter by Userset ids.
     for(Assigned_Partner__c tp:[select id,Partner_Status__c,Assigned_Partner__c,Assigned_Partner_Sales_Rep__c,Assigned_Partner_Sales_Rep_2__c,Assigned_Partner_Sales_Rep_3__c from Assigned_Partner__c where (Partner_Status__c =:activelyWorking or Partner_Status__c =:assignedtoPSR) and  (Assigned_Partner_Sales_Rep__c IN: setUser or Assigned_Partner_Sales_Rep_2__c IN: setUser or Assigned_Partner_Sales_Rep_3__c IN: setUser)])
    {
         bval = false;
         
         //check whether psr 1,2,3 values exist in userset.
        if(setUser.contains(tp.Assigned_Partner_Sales_Rep__c))
        {
            //SCAVA FIX
            if(flsUpdate(Assigned_Partner__c.Assigned_Partner_Sales_Rep__c))
            {
            tp.Assigned_Partner_Sales_Rep__c = null; 
            }
            bval = true;            
        }
        if(setUser.contains(tp.Assigned_Partner_Sales_Rep_2__c))
        {
            //SCAVA FIX
            if(flsUpdate(Assigned_Partner__c.Assigned_Partner_Sales_Rep_2__c))
            {
            tp.Assigned_Partner_Sales_Rep_2__c = null; 
            }
            bval = true;            
        }
        if(setUser.contains(tp.Assigned_Partner_Sales_Rep_3__c))
        {
            //SCAVA FIX
            if(flsUpdate(Assigned_Partner__c.Assigned_Partner_Sales_Rep_3__c))
            {
            tp.Assigned_Partner_Sales_Rep_3__c = null;
            }
            bval = true;
        }
        
        if(bval)
        {
            //check whether psr 1,2,3 has values.
            if(tp.Assigned_Partner_Sales_Rep__c !=null || tp.Assigned_Partner_Sales_Rep_2__c !=null || tp.Assigned_Partner_Sales_Rep_3__c !=null)
            {
                //SCAVA FIX
            if(flsUpdate(Assigned_Partner__c.Partner_Status__c))
            {
                tp.Partner_Status__c = assignedtoPSR;
            }
            }
            else
            {
                tp.Partner_Status__c = partnerAssigned;
            }
            
            //add to list.
            lstTP.add(tp);
        }
                
     }
     
     //check list is not empty.
     if(!lstLead.isEmpty())
     {
        database.update(lstLead,false);
     }
     
     //check list is not empty.
     if(!lstTP.isEmpty())
     {
        database.update(lstTP,false);
     }
    
 }
}