objects/Assigned_Partner__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Partner Account assigned to this target account.</description>
        <label>Assigned Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Assigned_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSR_Assigned_Date_Time__c</fullName>
        <description>Date/Time PSR was assigned to the Target Prospect</description>
        <label>PSR Assigned Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Partner_Assigned_Date__c</fullName>
        <description>Date/Time when the Partner was assigned to the Target Prospect</description>
        <label>Prospect/Partner Activated Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Partner_Status__c</fullName>
        <label>Partner Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned (New)</fullName>
                    <default>true</default>
                    <label>Assigned (New)</label>
                </value>
                <value>
                    <fullName>Partner Assigned</fullName>
                </value>
                <value>
                    <fullName>Assigned to PSR</fullName>
                </value>
                <value>
                    <fullName>Actively Working</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Target_Architecture__c</fullName>
        <label>Target Architecture</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Any/All Technologies</fullName>
                </value>
                <value>
                    <fullName>Collaboration-Unified Communications (UC)</fullName>
                </value>
                <value>
                    <fullName>Core-Routing Switching &amp; Services</fullName>
                </value>
                <value>
                    <fullName>Data Center-Unified Computing Systems (UCS)</fullName>
                </value>
                <value>
                    <fullName>Video-TelePresence &amp; Conferencing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Target_Description__c</fullName>
        <label>Target Description</label>
        <type>TextArea</type>
    </fields>
    <description>Partner assignments of End User Accounts are stored in this object.</description>
    <label>zzTarget Prospect</label>
    <nameField>
        <label>Target Prospect Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Target Prospects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Channel_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created for P360 2A development.</description>
        <label>Channel Partner</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2)</booleanFilter>
            <errorMessage>The selected Partner is not a SCP registered active partner or is flagged on the Denied Partner List, please select a valid SCP registered partner.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Channel</value>
            </filterItems>
            <filterItems>
                <field>Account.Partner_Assignment_Eligible__c</field>
                <operation>greaterOrEqual</operation>
                <value>1</value>
            </filterItems>
            <infoMessage>This search will return only those partners enrolled in the Sales Collaboration Platform program. However, if you would like to reference accounts eligible for lead assignment, refer to the P360 Partners Enrolled link on the left hand side of the screen.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assigned Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CustomCountry__c</fullName>
        <description>Lead Address Country</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALAND ISLANDS</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BONAIRE, SINT EUSTATIUS AND SABA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PSR_Assigned_Date__c</fullName>
        <description>Date when PSR1,PSR2 or PSR3 is assigned</description>
        <label>PSR Assignment Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Partner_Assigned_Date__c</fullName>
        <description>Date when Channel Partner is assigned to a lead</description>
        <label>Partner Assignment Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Partner_Lead_Status__c</fullName>
        <description>This field is created for P360 2A Development</description>
        <label>Partner Lead Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Partner Assigned</fullName>
                </value>
                <value>
                    <fullName>Assigned To PSR</fullName>
                </value>
                <value>
                    <fullName>Actively Working</fullName>
                </value>
                <value>
                    <fullName>Deal Created</fullName>
                </value>
                <value>
                    <fullName>Rejected-Invalid Contact</fullName>
                </value>
                <value>
                    <fullName>Rejected-Already Deal</fullName>
                </value>
                <value>
                    <fullName>Rejected-Project Canceled</fullName>
                </value>
                <value>
                    <fullName>Rejected-Lost to Competition</fullName>
                </value>
                <value>
                    <fullName>Rejected-Not My Territory/Account</fullName>
                </value>
                <value>
                    <fullName>Rejected-No Customer Response</fullName>
                </value>
                <value>
                    <fullName>Rejected-Duplicate</fullName>
                </value>
                <value>
                    <fullName>Rejected-No Valid Project</fullName>
                </value>
                <value>
                    <fullName>Closed-Order Through Stock</fullName>
                </value>
                <value>
                    <fullName>Closed-Order Through Disti</fullName>
                </value>
                <value>
                    <fullName>Closed-Order Through Cisco</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Status__c</fullName>
        <description>PLOC field, indicates the lead status as determined by the partner.</description>
        <label>TO_BE_DELETED_Partner Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Accepted/In Progress</fullName>
                </value>
                <value>
                    <fullName>Confirmed Sales Project</fullName>
                </value>
                <value>
                    <fullName>Rejected - Already Opportunity</fullName>
                </value>
                <value>
                    <fullName>Rejected - Project Cancelled</fullName>
                </value>
                <value>
                    <fullName>Rejected - Lost to Competition</fullName>
                </value>
                <value>
                    <fullName>Rejected - No Customer Response</fullName>
                </value>
                <value>
                    <fullName>Rejected - Invalid/No Interest</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Closed</fullName>
        <active>true</active>
        <businessProcess>eLeads</businessProcess>
        <description>Rejected/closed eLeads lead</description>
        <label>Closed</label>
    </recordTypes>
    <recordTypes>
        <fullName>Manual</fullName>
        <active>true</active>
        <businessProcess>Global - Manual Lead</businessProcess>
        <description>Manually &amp; imported</description>
        <label>Manual</label>
    </recordTypes>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <businessProcess>NGCC Marketing Lead</businessProcess>
        <description>Prospect Leads from Next Gen Marketing Contact Center</description>
        <label>Prospect</label>
    </recordTypes>
</CustomObject>

classes/P360TxM_RM_DashboardCTE_Test.cls
@isTest(SeeAllData=True)
public class P360TxM_RM_DashboardCTE_Test{
    public static testMethod void testTxMDashboard(){
    List<Assigned_Partner__c>  testList = new List<Assigned_Partner__c> ();
    List<Lead> leadList  = new List<Lead>();
    
      Id partnerAccountId = GenericStaticTestData.gettestChannelAccountRecord1().Id;
          Lead testLead4 = new Lead(firstName='Test Manual',LastName ='Lead', RECORDTYPEID='0123000000004aSAAQ', Partner_Lead_Status__c = 'Closed-Order Through Disti',LeadSource='test',company='Test End-User Account',email='test@test.com.test', Channel_Partner__c = partnerAccountId,CustomCountry__c='',PSR_Assigned_Date__c= null,CREATEDDATE = DateTime.now()-130);
          insert testLead4;
          testLead4.Partner_Lead_status__c='Rejected-Not My Territory/Account';
          update testLead4;
          
          leadList.add(testLead4);
          Assigned_Partner__c testTp = new Assigned_partner__c(Name='Test Target Prospect Record',TARGET_ARCHITECTURE__C='Any/All Technologies',TARGET_DESCRIPTION__C='Test Target Prospect Record',Assigned_Partner__c = partnerAccountId, Partner_Status__c = 'Partner Assigned', Partner_Assigned_Date__c = DateTime.now(), PSR_Assigned_Date_Time__c = DateTime.now());
          insert testTp;
          testList.add(testTp);
          
          PageReference pageRef = Page.P360TxM_RM_Dashboard;       
          Test.setCurrentPage(pageRef);
          
          P360TxM_RM_DashboardCTE controller=new P360TxM_RM_DashboardCTE();
          
          controller.initDashboard();
          controller.getItems();
          controller.getlstReports();
          P360TxM_RM_DashboardCTE.getChartData();
          string strPartnerFilter = 'Test';
          controller.getstrPartnerFilter();
          controller.setstrPartnerFilter(strPartnerFilter);
          controller.cmdPartnerFilter();
          controller.showAllFilter();
          
          controller.getCountofPartnerAssignedLead();
          controller.SelectedValue = 'test';  
          controller.urlsforDashboards();
    }

}