objects/Assigned_Partner__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Partner Account assigned to this target account.</description>
        <label>Assigned Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Assigned_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Target Account to whom partners are being assigned</description>
        <label>Customer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Assigned_Partner_Customer_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <description>Release: P360 March 2013 
Purpose: To Capture Date on which the TP will Expire and get Deactivated</description>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Extend_By__c</fullName>
        <description>Release: P360 March 2013 
Purpose: Used to extend the Target Prospect Expiration Date by 30,60,90 Days..</description>
        <label>Extend By</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>15 Days</fullName>
                </value>
                <value>
                    <fullName>30 Days</fullName>
                </value>
                <value>
                    <fullName>60 Days</fullName>
                </value>
                <value>
                    <fullName>90 Days</fullName>
                </value>
                <value>
                    <fullName>No Expiration</fullName>
                    <default>true</default>
                    <label>No Expiration</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Extension_Reason__c</fullName>
        <description>Release: P360 March 2013 
Purpose: Store the reason for Extension in Expiration Date.This will be nullified by trigger after creating a child record in prospect extensions.</description>
        <label>Extension Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Explicit Extension by Partner</fullName>
                </value>
                <value>
                    <fullName>Initial Expiration with Prospect Upload</fullName>
                </value>
                <value>
                    <fullName>New Deal Creation</fullName>
                </value>
                <value>
                    <fullName>Partner Created Target Prospect Default</fullName>
                </value>
                <value>
                    <fullName>TxM Extension</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TBM_TAM_Username__c</fullName>
        <description>Created as part of P360 Sep '12 Release. 
Hold the Username of the Look Up field "TBM/TAM" for Gadget.</description>
        <formula>TBM_TAM__r.Username</formula>
        <label>TBM TAM Username</label>
        <type>Text</type>
    </fields>
    <description>Partner assignments of End User Accounts are stored in this object.</description>
    <label>zzTarget Prospect</label>
    <nameField>
        <label>Target Prospect Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Target Prospects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CCW_Urls__c.object
<CustomObject>
    <fields>
        <fullName>createDealUrl__c</fullName>
        <description>Url to CCW Initiate Deal page</description>
        <label>createDealUrl</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>viewDealUrl__c</fullName>
        <description>Link to CCW View All Deal page</description>
        <label>viewDealUrl</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>CCW_Urls</label>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CCO_ID__c</fullName>
        <externalId>true</externalId>
        <label>CCO ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Prospect_Extension__c.object
<CustomObject>
    <fields>
        <fullName>Extension_Reason__c</fullName>
        <description>Release: P360 March 2013 
Purpose: To Store Reason for Extension</description>
        <label>Extension Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Explicit Extension by Partner</fullName>
                </value>
                <value>
                    <fullName>Initial Expiration with Prospect Upload</fullName>
                </value>
                <value>
                    <fullName>New Deal Creation</fullName>
                </value>
                <value>
                    <fullName>Partner Created Target Prospect Default</fullName>
                </value>
                <value>
                    <fullName>TxM Extension</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Target_Prospect__c</fullName>
        <description>Release: P360 March 2013 
Purpose: Actual TP for which the Extension was Received</description>
        <label>Target Prospect</label>
        <referenceTo>Assigned_Partner__c</referenceTo>
        <relationshipLabel>Prospect Extensions</relationshipLabel>
        <relationshipName>Target_Prospect_Extensions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <description>This will store all data related to extensions of expiration dates.</description>
    <label>Prospect Extension</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Prospect Extensions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prospect Extensions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/SCP_Communities_tpdetails_CT.cls
public with sharing class SCP_Communities_tpdetails_CT {

    public Assigned_Partner__c tp { get; set; }
    public Integer daysLeft{get;set;}
    public boolean isExtendButtonRendered{get;set;}
    public boolean isExtendButtonDisabled{get;set;}
    
    public boolean isPA {
    	get {
    		return (prmFilterUtility.isPA);
    	}
    }
    public String extendMessage{
        get{
            if(this.tp.Expiration_Date__c != null){
                extendMessage = Label.PRM_extendmsg;
                String daysBetween = String.valueOf(Date.today().daysBetween(this.tp.Expiration_Date__c));
                extendMessage = this.extendMessage.replaceFirst('\\{0\\}', daysBetween);
            }else{
                extendMessage = null;
            }
            return extendMessage;
        }
        set;
    }

    public SCP_Communities_tpdetails_CT(ApexPages.StandardController stdCon) {
    	System.debug('SCP_Communities_tpdetails_CT: Start Constructor');
        	this.tp = (Assigned_Partner__c) stdCon.getRecord();
         this.initTpExtension();
        System.debug('SCP_Communities_tpdetails_CT: End Constructor');
   }

    /**
     * @description Controller contructor helper method to determine visibility of 'Extend' button to partner user
     *              Set the extend buttons render and disable boolean variable and adds warning info message to user
     */
    public void initTpExtension(){
        System.debug('SCP_Communities_tpdetails_CT.initTpExtension(): Start initTpExtension');
        this.daysLeft = 0;
        this.isExtendButtonRendered = false;
        //only apply for TP records whose expiration dates is not null
        if(this.tp.Expiration_Date__c != null){
            Integer extendCount = 0;
            //Get TP count of extension
            List<AggregateResult> extendCountAggResult = [Select count(a.Id) ExtendCount from Prospect_Extension__c a 
                            where a.Target_Prospect__c= :this.tp.Id AND a.Extension_Reason__c = 'Explicit Extension by Partner' 
                            AND CreatedDate > :this.tp.CreatedDate];
            if(extendCountAggResult.size()>0){
                extendCount = (Integer) extendCountAggResult[0].get('ExtendCount');
            }
            
            daysLeft = Date.today().daysBetween(this.tp.Expiration_Date__c);
            if(extendCount == 0 && daysLeft <= 14 && daysLeft > 0 ){
                String extendMessage = Label.PRM_extendmsg;
                String daysBetween = String.valueOf(daysLeft);
                extendMessage = this.extendMessage.replaceFirst('\\{0\\}', daysBetween);
                Apexpages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,'' + extendMessage));
                this.isExtendButtonRendered = true;
                this.isExtendButtonDisabled = false;
            }else{
                this.isExtendButtonRendered = true;
                this.isExtendButtonDisabled = true;
            }
        }
        System.debug('SCP_Communities_tpdetails_CT.initTpExtension(): End initTpExtension');
    }
    /**
     * @description Default action method called for the TP Detail VF page.  Determines the page redirect based on
     *              user profiles.  The redirects apply as follows
     *              Standard TP View: Apply for all 
     *              TP Detail VF Page: Only users with partner profiles and admin
     */
    public PageReference redirect() {
        System.debug('SCP_Communities_tpdetails_CT.initTpExtension(): Start redirect');
        PageReference viewPage = null;
        Profile p = [select name from Profile where id = 
                :UserInfo.getProfileId()];
        if (!'POC - Partner Community'.equals(p.name) && !'Partner360_Portal_Profile'.equals(p.name)){
            viewPage =  New PageReference('/'+tp.Id + '/d?nooverride=1');
            viewPage.setRedirect(true);
        }
        
        System.debug('SCP_Communities_tpdetails_CT.initTpExtension(): End redirect');
        return viewPage;
    }
    
    public PageReference extend(){
        System.debug('extend(): Start extend');
        Boolean isTpExtensionFailed = false;
        if(this.tp.Expiration_Date__c != null) {
            this.tp.Extend_By__c = '30 Days';
            this.tp.Extension_Reason__c = 'Explicit Extension by Partner';

            try{
                System.debug('extend(): Update TP Rec');
                update this.tp;
            }catch(DmlException dmlEx){
                System.debug('extend(): DmlException');
                System.debug(dmlEx);
                Apexpages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,'' + dmlEx));
                isTpExtensionFailed = true;
            }catch(Exception ex){
                System.debug('extend(): Exception');
                System.debug(ex);
                Apexpages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,'' + ex));
                isTpExtensionFailed = true;
            }
        }
        
        System.debug('extend(): Update Fail?'+isTpExtensionFailed);
        PageReference extendRedirect = null;
        if(!isTpExtensionFailed){
            //getting error when redirecting page back to tp record, will return null and rerender extend button and details
            this.isExtendButtonDisabled = true;
            //extendRedirect = new PageReference('/'+this.tp.Id + '/d');
            //extendRedirect.setRedirect(true);
        }
        System.debug('extend(): Redirect PageReference');
        System.debug(extendRedirect);
        return null;
    }
    
    public PageReference initiateDeal(){
        System.debug('initiateDeal(): Start initiateDeal');
        Boolean isTpExtensionFailed = false;
        if(this.tp.Expiration_Date__c != null) {
            this.tp.Extend_By__c = '60 Days';
            this.tp.Extension_Reason__c = 'New Deal Extensions';

            try{
                System.debug('initiateDeal(): Update TP Rec');
                System.debug(this.tp);
                update this.tp;
            }catch(DmlException dmlEx){
                System.debug('initiateDeal(): DmlException');
                System.debug(dmlEx);
                Apexpages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,'' + dmlEx));
                isTpExtensionFailed = true;
            }catch(Exception ex){
                System.debug('initiateDeal(): Exception');
                System.debug(ex);
                Apexpages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,'' + ex));
                isTpExtensionFailed = true;
            }
        }
        
        System.debug('initiateDeal(): Update Successfull?'+isTpExtensionFailed);
        PageReference initiateDealCCW = null;
        if(!isTpExtensionFailed){
            String amCCOId=''; 
            String sfdcAccountId = this.tp.Customer_Account__c; 
            String targetprospectId= this.tp.Id; 
            String prefLang = prmFilterUtility.loggedInUserGadgetLanguage;
    
            if(this.tp.TBM_TAM_Username__c!=null){ 
                amCCOId = this.tp.TBM_TAM_Username__c.substringBefore('@'); 
            }
            
            
            String createAccDealURL = CCW_Urls__c.getInstance().createDealUrl__c + 
            '?amCcoId=' + amCCOId + 
            '&sfdcAccountId=' + sfdcAccountId + 
            '&sfdcLeadFlag=TP' + 
            '&targetProspectLeadId=' + targetprospectId + 
            '&localeChanged=' + prefLang; 
            
            initiateDealCCW = new PageReference(createAccDealURL);
            System.debug(createAccDealURL);
            initiateDealCCW.setRedirect(true);
        }
        
        System.debug('initiateDeal(): End initiateDeal');
        return initiateDealCCW;
    }
    
    public PageReference viewAllDeals(){
        String role = '';
        String prefLang = prmFilterUtility.loggedInUserGadgetLanguage;
        String remoteUser = prmFilterUtility.logUser.Contact.CCO_ID__c;

        String customerId = tp.Customer_Account__c;
        if(prmFilterUtility.isPA){
            role = 'PA';
        } else if (prmFilterUtility.isPSR) {
            role = 'PSR';
        }
        String viewAccDealURL = CCW_Urls__c.getInstance().viewDealUrl__c+'?actionType=showP360Deals&partnerCCOID='
            + remoteUser
            + '&sfdcAccountId='
            + customerId
            + '&partnerRole=' + role + '&localeChanged=' + prefLang;
        
        PageReference viewAllDeals = new PageReference(viewAccDealURL);
        viewAllDeals.setRedirect(true);
        return viewAllDeals;
    }
    
    public PageReference addEditPSR() {
    	String url = '/apex/SCP_Communities_psrFilterLookup';
    	PageReference psrLookup = new PageReference(url);
    	psrLookup.getParameters().put('Id',tp.Id);
    	psrLookup.setRedirect(true);
    	System.debug(System.LoggingLevel.INFO, '$$$$ psrLookup : '+psrLookup+' Page.SCP_Communities_psrFilterLookup : '+Page.SCP_Communities_psrFilterLookup);
    	return psrLookup;
    	
    }
}