objects/Assigned_Partner__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Partner Account assigned to this target account.</description>
        <label>Assigned Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Assigned_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Assigned_Date__c</fullName>
        <description>Date/Time when the Partner was assigned to the Target Prospect</description>
        <label>Prospect/Partner Activated Date/Time</label>
        <type>DateTime</type>
    </fields>
    <description>Partner assignments of End User Accounts are stored in this object.</description>
    <label>zzTarget Prospect</label>
    <nameField>
        <label>Target Prospect Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Target Prospects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Channel_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created for P360 2A development.</description>
        <label>Channel Partner</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2)</booleanFilter>
            <errorMessage>The selected Partner is not a SCP registered active partner or is flagged on the Denied Partner List, please select a valid SCP registered partner.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Channel</value>
            </filterItems>
            <filterItems>
                <field>Account.Partner_Assignment_Eligible__c</field>
                <operation>greaterOrEqual</operation>
                <value>1</value>
            </filterItems>
            <infoMessage>This search will return only those partners enrolled in the Sales Collaboration Platform program. However, if you would like to reference accounts eligible for lead assignment, refer to the P360 Partners Enrolled link on the left hand side of the screen.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assigned Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSR_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Partner Sales Rep One</description>
        <label>Assigned Partner Sales Rep 1</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>User.ProfileId</field>
                <operation>equals</operation>
                <value>00en0000000Hg4k</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSR_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Partner Sales Rep 2</description>
        <label>Assigned Partner Sales Rep 2</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>User.Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Channel_Partner__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Leads2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSR_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Partner Sales Rep 3</description>
        <label>Assigned Partner Sales Rep 3</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>No contact exist under account</errorMessage>
            <filterItems>
                <field>User.Contact.AccountId</field>
                <operation>startsWith</operation>
                <valueField>$Source.Channel_Partner__c</valueField>
            </filterItems>
            <infoMessage>Filter on PSR3 lookup</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Leads3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSR_Assigned_Date__c</fullName>
        <description>Date when PSR1,PSR2 or PSR3 is assigned</description>
        <label>PSR Assignment Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Partner_Assigned_Date__c</fullName>
        <description>Date when Channel Partner is assigned to a lead</description>
        <label>Partner Assignment Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Partner_Lead_Status__c</fullName>
        <description>This field is created for P360 2A Development</description>
        <label>Partner Lead Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Partner Assigned</fullName>
                </value>
                <value>
                    <fullName>Assigned To PSR</fullName>
                </value>
                <value>
                    <fullName>Actively Working</fullName>
                </value>
                <value>
                    <fullName>Deal Created</fullName>
                </value>
                <value>
                    <fullName>Rejected-Invalid Contact</fullName>
                </value>
                <value>
                    <fullName>Rejected-Already Deal</fullName>
                </value>
                <value>
                    <fullName>Rejected-Project Canceled</fullName>
                </value>
                <value>
                    <fullName>Rejected-Lost to Competition</fullName>
                </value>
                <value>
                    <fullName>Rejected-Not My Territory/Account</fullName>
                </value>
                <value>
                    <fullName>Rejected-No Customer Response</fullName>
                </value>
                <value>
                    <fullName>Rejected-Duplicate</fullName>
                </value>
                <value>
                    <fullName>Rejected-No Valid Project</fullName>
                </value>
                <value>
                    <fullName>Closed-Order Through Stock</fullName>
                </value>
                <value>
                    <fullName>Closed-Order Through Disti</fullName>
                </value>
                <value>
                    <fullName>Closed-Order Through Cisco</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Org_Constant_CS__c.object
<CustomObject>
    <fields>
        <fullName>Non_Production_Value__c</fullName>
        <label>Non Production Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Production_Value__c</fullName>
        <label>Production Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>Org Constant CS</label>
</CustomObject>

objects/P360_Apex_Batch_Job__c.object
<CustomObject>
    <fields>
        <fullName>DT_DailyEmailNotification__c</fullName>
        <label>DT DailyEmailNotification</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>JobEmailAlerts__c</fullName>
        <description>JobEmailAlerts</description>
        <label>JobEmailAlerts</label>
        <type>Email</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Used for P360 Daily Email Job</description>
    <label>P360 Apex Batch Job Detail</label>
</CustomObject>

classes/EmailUtil_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class EmailUtil_Test {
    
    
    private static void prepareData() {
        //load custom settings
        User u = new User(Id = UserInfo.getUserId());
        
        System.runAs (u) {            
            Date dtToday = System.today() - 3;
            List<P360_Apex_Batch_Job__c> jobDetail = new List<P360_Apex_Batch_Job__c>();
            jobDetail.add(new P360_Apex_Batch_Job__c(Name='P360 dtToday',DT_DailyEmailNotification__c=dtToday,JobEmailAlerts__c='test@cisco.com'));
            insert jobDetail;
            
            List<Org_Constant_CS__c> orgConstant = new List<Org_Constant_CS__c>();
            orgConstant.add(new Org_Constant_CS__c(Name='P360 Partner Assigned',Non_Production_Value__c='Partner Assigned',Production_Value__c='Partner Assigned'));
            orgConstant.add(new Org_Constant_CS__c(Name='P360 Assigned to PSR',Non_Production_Value__c='Assigned to PSR',Production_Value__c='Assigned to PSR'));
            orgConstant.add(new Org_Constant_CS__c(Name='P360 Executive User',Non_Production_Value__c='Executive',Production_Value__c='Executive'));
            orgConstant.add(new Org_Constant_CS__c(Name='P360 Lead120Days',Non_Production_Value__c='120',Production_Value__c='120'));
            orgConstant.add(new Org_Constant_CS__c(Name='P360 Lead Aging',Non_Production_Value__c='1',Production_Value__c='1'));            
            insert orgConstant;
        }
    }
    
    static testMethod void UnitTestPSR() {
        prepareData();
        // TO DO: implement unit test
        UtilUnitTest.loadAllStaticData();
        List<Lead> newLead = new List<Lead>();  
        //List<Assigned_partner__c> TPs = new List<Assigned_partner__c>();
        //map<id,User> oldAcc = new map<id,User>();
        
        GenericStaticTestData.insertTestLeadRecords();                
        GenericStaticTestData.insertTestUserRecords();
        
        GenericStaticTestData.testeLeadRecord.PSR_1__c= GenericStaticTestData.testPSRUserRecord.id;
        GenericStaticTestData.testeLeadRecord.Partner_Lead_Status__c='Assigned To PSR';         
        GenericStaticTestData.testeLeadRecord.PSR_Assigned_Date__c = System.today() - 1;
        GenericStaticTestData.testeLeadRecord.PSR_2__c= GenericStaticTestData.testPSRUserRecord.id;       
        GenericStaticTestData.testeLeadRecord.PSR_3__c= GenericStaticTestData.testPSRUserRecord.id;
        newLead.add(GenericStaticTestData.testeLeadRecord);        
        update newLead;
        
      // ********* Scheduler Call ***************
        Test.StartTest();
      // Changed the scheduler calls from P360_DailyEmailNotification to P360EmailNotificationScheduler            
            P360EmailNotificationScheduler pDS2 = new P360EmailNotificationScheduler();      
            String sch2 = '0 0 23 * * ?';
            String jobId = System.schedule('Test check2', sch2, pDS2);         
            CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];        
            System.assertEquals(sch2, ct.CronExpression);
         
        Test.stopTest();
    }   
    
    static testMethod void UnitTestPA() {
        prepareData();
        // TO DO: implement unit test
        UtilUnitTest.loadAllStaticData();
        List<Lead> newLead = new List<Lead>();  
        //List<Assigned_partner__c> TPs = new List<Assigned_partner__c>();
        //map<id,User> oldAcc = new map<id,User>(); 
        
        GenericStaticTestData.insertTestLeadRecords();                
        GenericStaticTestData.insertTestUserRecords();        
       
        
        GenericStaticTestData.testManualLeadRecord.Channel_Partner__c  = GenericStaticTestData.testChannelAccountRecord1.id;
        GenericStaticTestData.testManualLeadRecord.Partner_Lead_Status__c='Partner Assigned'; 
        GenericStaticTestData.testManualLeadRecord.Partner_Assigned_Date__c = System.today() - 1;
        newLead.add(GenericStaticTestData.testManualLeadRecord);
        
        GenericStaticTestData.testPartnerGereratedLeadRecord.Partner_Lead_Status__c='Partner Assigned';
        newLead.add(GenericStaticTestData.testPartnerGereratedLeadRecord);  
        User us = new User(Id = UserInfo.getUserId());        
        System.runAs (us) {
           update newLead;
        }
        User u = new User(Id = UserInfo.getUserId());
        map<id,user> mapUsers =new Map<id,user>();
        map<id,user> mapPartnerUser = new map<id,user>();
        Set<Id> lst = new Set<Id>();
        lst.add(u.id);
        Set<Id> lstPA = new Set<Id>();
        lstPA.add(u.id);
        EmailNotification_Utility.psrLeadsCount.put(u.id,2);        
        mapUsers.put(u.id,u);
        mapPartnerUser.put(u.id,u);
        datetime dt = datetime.now(); 
        EmailNotification_Utility.checkStringNotNull(' ');               
        /********* Scheduler Call ****************/        
       Test.StartTest();
            // Changed the scheduler calls from P360_DailyEmailNotification to P360EmailNotificationScheduler
            EmailNotification_Utility.dtToday = system.today()-1;
            EmailNotification_Utility.lastRunDate = system.today()-1;            
            P360EmailNotificationScheduler pDS2 = new P360EmailNotificationScheduler();      
            String sch2 = '0 0 23 * * ?';
            system.schedule('Test check2', sch2, pDS2);
            EmailNotification_Utility.insertPA_PSR_RecordCount(null,lst,lstPA,mapUsers,mapPartnerUser);
            EmailNotification_Utility.validateAssignedDate(dt);            
        Test.stopTest();
    }
}