objects/Assigned_Partner__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_PSR_SYS1__c</fullName>
        <description>Created as part of P360 Sep '12 release. 
Partner users can't access data for other users, so Gadget can not update the lookup field directly or read user's full name of PSR1 from lookup. 
Gadget will update this field while updating and read name from this field while reading.</description>
        <label>Assigned Partner Sales Rep 1 Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assigned_PSR_SYS2__c</fullName>
        <description>Created as part of P360 Sep '12 release. 
Partner users can't access data for other users, so Gadget can not update the lookup field directly or read user's full name of PSR2 from lookup. 
Gadget will update this field while updating and read name from this field while reading.</description>
        <label>Assigned Partner Sales Rep 2 Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assigned_PSR_SYS3__c</fullName>
        <description>Created as part of P360 Sep '12 release. 
Partner users can't access data for other users, so Gadget can not update the lookup field directly or read user's full name of PSR3 from lookup. 
Gadget will update this field while updating and read name from this field while reading.</description>
        <label>Assigned Partner Sales Rep 3 Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assigned_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Partner Account assigned to this target account.</description>
        <label>Assigned Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Assigned_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assignment_Activated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is the assignment activated by TAM/TBM</description>
        <label>Assignment Activated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PSR_Assigned_Date_Time__c</fullName>
        <description>Date/Time PSR was assigned to the Target Prospect</description>
        <label>PSR Assigned Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Partner_Assigned_Date__c</fullName>
        <description>Date/Time when the Partner was assigned to the Target Prospect</description>
        <label>Prospect/Partner Activated Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Partner_Status__c</fullName>
        <label>Partner Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned (New)</fullName>
                    <default>true</default>
                    <label>Assigned (New)</label>
                </value>
                <value>
                    <fullName>Partner Assigned</fullName>
                </value>
                <value>
                    <fullName>Assigned to PSR</fullName>
                </value>
                <value>
                    <fullName>Actively Working</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Target_Architecture__c</fullName>
        <label>Target Architecture</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Any/All Technologies</fullName>
                </value>
                <value>
                    <fullName>Collaboration-Unified Communications (UC)</fullName>
                </value>
                <value>
                    <fullName>Core-Routing Switching &amp; Services</fullName>
                </value>
                <value>
                    <fullName>Data Center-Unified Computing Systems (UCS)</fullName>
                </value>
                <value>
                    <fullName>Video-TelePresence &amp; Conferencing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Target_Description__c</fullName>
        <label>Target Description</label>
        <type>TextArea</type>
    </fields>
    <description>Partner assignments of End User Accounts are stored in this object.</description>
    <label>zzTarget Prospect</label>
    <nameField>
        <label>Target Prospect Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Target Prospects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/P360_TargetProspectTriggers_Test.cls
@isTest(SeeAllData=false) 
public class P360_TargetProspectTriggers_Test {

public static testMethod void testP360_UpdatePSR_APFields_Trigger()
{       
       System.debug(System.LoggingLevel.INFO,'@@@@ Limits.getQueries(): '+Limits.getQueries()+' Limits.getLimitQueries(): '+Limits.getLimitQueries());
       UtilUnitTest.loadAllStaticData();
       System.debug(System.LoggingLevel.INFO,'@@@@ Limits.getQueries(): '+Limits.getQueries()+' Limits.getLimitQueries(): '+Limits.getLimitQueries());
       Id PSRUserId = GenericStaticTestData.gettestPSRUserRecord().id;
       Id partnerAccountId = GenericStaticTestData.gettestChannelAccountRecord1().Id;
       //Assigned_Partner__c TP = GenericStaticTestData.gettestTargetProspectRecord();
       Assigned_Partner__c TP = new Assigned_partner__c(Name='Test Target Prospect Record',TARGET_ARCHITECTURE__C='Any/All Technologies',
            TARGET_DESCRIPTION__C='Test Target Prospect Record',Assigned_Partner__c = partnerAccountId, Partner_Status__c = 'Partner Assigned', 
            Partner_Assigned_Date__c = DateTime.now(), PSR_Assigned_Date_Time__c = DateTime.now(), Assignment_Activated__c = true);
       System.debug(System.LoggingLevel.INFO,'@@@@ Limits.getQueries(): '+Limits.getQueries()+' Limits.getLimitQueries(): '+Limits.getLimitQueries());
       
       
       
       //TP.Assignment_Activated__c = true;
       //Update TP;
       System.debug(System.LoggingLevel.INFO,'@@@@ Limits.getQueries(): '+Limits.getQueries()+' Limits.getLimitQueries(): '+Limits.getLimitQueries());
       Test.startTest();
       TP.Assigned_PSR_SYS1__c = PSRUserId ;
       TP.Assigned_PSR_SYS2__c = PSRUserId ;
       TP.Assigned_PSR_SYS3__c = PSRUserId ;
       TP.Partner_Status__c   = Partner360Utils.PARTNER_STATUS_ACTIVELY_WORKING;
        
       List<Assigned_Partner__c> TPs = New list<Assigned_Partner__c>();
       TPs.add(TP);
       List<Assigned_Partner__c> TPsToUpsert = TPs.deepclone() ;
       TPsToUpsert[0].Target_Architecture__c = 'Video-TelePresence & Conferencing';
       TPsToUpsert.add(TP);
        
       system.runas(GenericStaticTestData.gettestPAUserRecord())
       {
          Upsert TPsToUpsert;       
          System.debug(System.LoggingLevel.INFO,'@@@@ Limits.getQueries(): '+Limits.getQueries()+' Limits.getLimitQueries(): '+Limits.getLimitQueries());
       }
       
       Test.stopTest();
       

}







}