objects/AT_Workspace__c.object
<CustomObject>
    <fields>
        <fullName>AT_Expected_Book_Date__c</fullName>
        <description>Date AT opportunity is expected to book, may or may not align with Opportunity book date</description>
        <label>Workspace Expected Book Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AT_Forecast_Status__c</fullName>
        <description>AT Opportunity status (Commit, Upside = Forecast, None = Identified opportunity, not yet qualified)</description>
        <label>Workspace Forecast Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Commit</fullName>
                </value>
                <value>
                    <fullName>Upside</fullName>
                </value>
                <value>
                    <fullName>Not Forecastable</fullName>
                    <default>true</default>
                    <label>Not Forecastable</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Forecast_Position_ID__c</fullName>
        <description>Holds forecast Position ID for corresponding selected PSS Team</description>
        <label>Forecast Position ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Opportunity associated with the workspace</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Workspaces</relationshipLabel>
        <relationshipName>AT_Workspace</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>PSS_Workspace_Status__c</fullName>
        <label>Workspace Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PSS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product Sales Specialist (owner of AT Workspace)</description>
        <label>Workspace User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00N30000002BoxqEAC</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Workspace</label>
    <nameField>
        <label>Opportunity Workspace Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Workspaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/baGetOverdueFlag_FP.cls
global class baGetOverdueFlag_FP {

webservice static string getOverdueflag (string terrID,date fp_start_date)
{
 String flag='NOOVERDUE';
 
 system.debug('terrID is :   '+terrID+'   ,fp_start_date  : '+ fp_start_date+' fp_start_date-30 is : '+(fp_start_date-30)+' fp_start_date-14 : '+(fp_start_date-14)   );

 AT_WORKSPACE__C[] opty = [select          
                        id        
                from AT_WORKSPACE__C a
                where a.PSS_Workspace_Status__c = 'Active'
                and   a.Opportunity__r.DealID__c  <> null    and a.Opportunity__r.StageName <>'1 - Prospect'  and a.AT_Forecast_Status__c <> 'Not Forecastable' and a.Forecast_Position_ID__c <>null and  a.Forecast_Position_ID__c <>'0'
                and   (a.Forecast_Position_ID__c = :terrID or a.PSS__r.Username = :terrID)
                and a.AT_Expected_Book_Date__c>=:fp_start_date-30 and a.AT_Expected_Book_Date__c<=:fp_start_date-14 limit 1
                ];

 if(opty.size() > 0)
    flag = 'OVERDUE_LT30';
 //return opty;
        AT_WORKSPACE__C[] opty1 = [select
                                id
                                from AT_WORKSPACE__C a
                where a.PSS_Workspace_Status__c = 'Active'
                and   a.Opportunity__r.DealID__c  <> null    and a.Opportunity__r.StageName <>'1 - Prospect'  and a.AT_Forecast_Status__c <> 'Not Forecastable' and a.Forecast_Position_ID__c <>null and a.Forecast_Position_ID__c <>'0'
                                and (a.Forecast_Position_ID__c = :terrID or a.PSS__r.Username = :terrID)
                               and a.AT_Expected_Book_Date__c<:fp_start_date-30 limit 1
                                ];
 if(opty1.size() > 0)
         flag = 'OVERDUE_GT30';
system.debug('flag is '+flag+'   fp_start_date-30  : '+ (fp_start_date-30) );
return  flag;
}
}