objects/AT_Workspace__c.object
<CustomObject>
    <fields>
        <fullName>Is_Multi_Tech__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Multi Tech</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Opportunity associated with the workspace</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Workspaces</relationshipLabel>
        <relationshipName>AT_Workspace</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Opportunity Workspace</label>
    <nameField>
        <label>Opportunity Workspace Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Workspaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Workspace_Technology__c.object
<CustomObject>
    <fields>
        <fullName>Business_Entity__c</fullName>
        <label>Business Entity (BE)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CLOUD VIRTUALIZATION</fullName>
                </value>
                <value>
                    <fullName>COLLABORATION</fullName>
                </value>
                <value>
                    <fullName>COMPUTING SYSTEMS</fullName>
                </value>
                <value>
                    <fullName>DIGITAL MEDIA</fullName>
                </value>
                <value>
                    <fullName>IoT</fullName>
                </value>
                <value>
                    <fullName>MOBILITY</fullName>
                </value>
                <value>
                    <fullName>SECURITY</fullName>
                </value>
                <value>
                    <fullName>SP VIDEO INFRA</fullName>
                </value>
                <value>
                    <fullName>SP VIDEO SW &amp; SOLUTIONS</fullName>
                </value>
                <value>
                    <fullName>SWITCHING</fullName>
                </value>
                <value>
                    <fullName>WIRELESS</fullName>
                </value>
                <value>
                    <fullName>AS-Advanced Services</fullName>
                </value>
                <value>
                    <fullName>CCS</fullName>
                </value>
                <value>
                    <fullName>CCS-Consulting Services</fullName>
                </value>
                <value>
                    <fullName>CMS-Cisco Managed Services</fullName>
                </value>
                <value>
                    <fullName>CSS-Security Services</fullName>
                </value>
                <value>
                    <fullName>ISG-Ecosystems</fullName>
                </value>
                <value>
                    <fullName>Refurbished</fullName>
                </value>
                <value>
                    <fullName>Software</fullName>
                </value>
                <value>
                    <fullName>TS-Technical Services</fullName>
                </value>
                <value>
                    <fullName>DTG: Consumer-Retail</fullName>
                </value>
                <value>
                    <fullName>DTG: Consumer-Hospitality</fullName>
                </value>
                <value>
                    <fullName>DTG: Consumer-S&amp;E</fullName>
                </value>
                <value>
                    <fullName>DTG: Energy-Utilities</fullName>
                </value>
                <value>
                    <fullName>DTG: Energy-O&amp;G</fullName>
                </value>
                <value>
                    <fullName>DTG: Energy-Other</fullName>
                </value>
                <value>
                    <fullName>DTG: FSI-Retail Banking</fullName>
                </value>
                <value>
                    <fullName>DTG: FSI-Insurance</fullName>
                </value>
                <value>
                    <fullName>DTG: FSI-Wealth Mgmt</fullName>
                </value>
                <value>
                    <fullName>DTG: H/C-Life Science</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Expected_000__c</fullName>
        <label>Amount($000)</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Workspace__c</fullName>
        <label>Opportunity Workspace</label>
        <referenceTo>AT_Workspace__c</referenceTo>
        <relationshipLabel>Workspace Technologies</relationshipLabel>
        <relationshipName>Workspace_Technologies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <description>Opportunity workspace technologies</description>
    <label>Workspace Technology</label>
    <nameField>
        <displayFormat>MT-{0}</displayFormat>
        <label>Workspace Technology Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workspace Technologies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Alekhya_PSS_Clone_CTE_Test.cls
@isTest
public class Alekhya_PSS_Clone_CTE_Test {
    public static testMethod void test_PSS_Clone_CTE(){
        Test.startTest();
        User newUser = Renewals_TestUtility.getUser('opssuser', true);
        Utilities.setIsTestMethod(true);
        Utilities.setValidationSkip(true);
        Utilities.setSkipFuture(true);
        lxTestDataFactory.createCustomSettings();
        system.runAs(newUser){
            Opportunity o = lxTestDataFactory.createSingleOppty();
            insert o;
            AT_Workspace__c ws = new AT_Workspace__c(Name='test', Opportunity__c = o.id, Is_Multi_Tech__c = true);       
            Database.SaveResult  result2 = Database.Insert(ws);
            Test.setCurrentPageReference(new PageReference('PSS_Clone_Alekhya?id=' + result2.id));
            ApexPages.StandardController ssc = new ApexPages.StandardController(ws);
            Alekhya_PSS_Clone_CTE controller = new Alekhya_PSS_Clone_CTE(ssc);
            controller.clonethis();
            
            AT_Workspace__c ws2 = new AT_Workspace__c(Name='test',Opportunity__c = o.id);       
            Database.SaveResult result3 = Database.Insert(ws2);
            Workspace_Technology__c wt = new Workspace_Technology__c(Workspace__c = ws2.id, Expected_000__c=50, Business_Entity__c='SECURITY');
            Database.SaveResult result4 = Database.Insert(wt);
            Test.setCurrentPageReference(new PageReference('PSS_Clone_Alekhya?id=' + result3.id));
            ApexPages.StandardController ssc2 = new ApexPages.StandardController(ws2);
            Alekhya_PSS_Clone_CTE controller2 = new Alekhya_PSS_Clone_CTE(ssc2);
            controller2.clonethis();
        }
        Test.stopTest();
       
    }

}