objects/AT_Workspace__c.object
<CustomObject>
    <fields>
        <fullName>AT_Expected_Book_Date__c</fullName>
        <description>Date AT opportunity is expected to book, may or may not align with Opportunity book date</description>
        <label>Workspace Expected Book Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AT_Expected_Product__c</fullName>
        <description>AT Product Booking value</description>
        <inlineHelpText>Expected Product Booking Revenue Amount in Thousands</inlineHelpText>
        <label>Workspace Expected Product($000)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AT_Forecast_Status__c</fullName>
        <description>AT Opportunity status (Commit, Upside = Forecast, None = Identified opportunity, not yet qualified)</description>
        <label>Workspace Forecast Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Commit</fullName>
                </value>
                <value>
                    <fullName>Upside</fullName>
                </value>
                <value>
                    <fullName>Not Forecastable</fullName>
                    <default>true</default>
                    <label>Not Forecastable</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AT_Technology__c</fullName>
        <description>Technology represented by this AT Workspace</description>
        <label>Workspace Technology</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CLOUD VIRTUALIZATION</fullName>
                </value>
                <value>
                    <fullName>COLLABORATION</fullName>
                </value>
                <value>
                    <fullName>COMPUTING SYSTEMS</fullName>
                </value>
                <value>
                    <fullName>DIGITAL MEDIA</fullName>
                </value>
                <value>
                    <fullName>ENTERPRISE ROUTING</fullName>
                </value>
                <value>
                    <fullName>IoT</fullName>
                </value>
                <value>
                    <fullName>MOBILITY</fullName>
                </value>
                <value>
                    <fullName>SECURITY</fullName>
                </value>
                <value>
                    <fullName>SP ROUTING</fullName>
                </value>
                <value>
                    <fullName>SP VIDEO INFRA</fullName>
                </value>
                <value>
                    <fullName>SP VIDEO SW &amp; SOLUTIONS</fullName>
                </value>
                <value>
                    <fullName>SWITCHING</fullName>
                </value>
                <value>
                    <fullName>WIRELESS</fullName>
                </value>
                <value>
                    <fullName>Advanced Services</fullName>
                </value>
                <value>
                    <fullName>CCS</fullName>
                </value>
                <value>
                    <fullName>CMS</fullName>
                </value>
                <value>
                    <fullName>ISG-Ecosystems</fullName>
                </value>
                <value>
                    <fullName>Refurbished</fullName>
                </value>
                <value>
                    <fullName>S+CC</fullName>
                </value>
                <value>
                    <fullName>Software</fullName>
                </value>
                <value>
                    <fullName>Technical Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_Status__c</fullName>
        <description>Opportunity_Status of the Opportunity associated with the AT workspace</description>
        <formula>TEXT(Opportunity__r.Opportunity_Status__c)</formula>
        <label>Opportunity Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Opportunity associated with the workspace</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Workspaces</relationshipLabel>
        <relationshipName>AT_Workspace</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>PSS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product Sales Specialist (owner of AT Workspace)</description>
        <label>Workspace User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00N30000002BoxqEAC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Stage of the Opportunity associated with the AT workspace</description>
        <formula>TEXT( Opportunity__r.StageName )</formula>
        <label>Opportunity Stage</label>
        <type>Text</type>
    </fields>
    <label>Opportunity Workspace</label>
    <nameField>
        <label>Opportunity Workspace Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Workspaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ATFunnelWS.cls
global class ATFunnelWS { 
       
    global class MyATTech {
        webservice String Technology;
        webservice Integer Stage1NotForecastable;
        webservice Integer Stage2Upside;
        webservice Integer Stage2Commit;
        webservice Integer Stage3Upside;
        webservice Integer Stage3Commit;
        webservice Integer Stage4Upside;
        webservice Integer Stage4Commit;
        webservice Integer Stage5Upside;
        webservice Integer Stage5Commit;
    }
   
    WebService static MyATTech[] getATFunnel(){
        
        Map<String,Integer[]> m = new Map<String, Integer[]>();
        String commitStatus = 'Commit';
        String upsideStatus = 'Upside';
        MyATTech[] ATsums = new MyATTech[]{};
        
        for(AT_Workspace__c w: [Select AT_Technology__c, AT_Expected_Product__c, Stage__c, AT_Forecast_Status__c From AT_Workspace__c Where PSS__c= :UserInfo.getUserId() and Opportunity_Status__c = 'Active' and (AT_Expected_Book_Date__c = THIS_FISCAL_QUARTER OR  AT_Expected_Book_Date__c = NEXT_FISCAL_QUARTER)]){
            
            if(m.containsKey(w.AT_Technology__c)){
                if(w.Stage__c.contains('1'))
                    m.get(w.AT_Technology__c)[0] += integer.valueOf(String.valueOf(w.AT_Expected_Product__c));
                else if(w.Stage__c.contains('2') && w.AT_Forecast_Status__c == upsideStatus)
                    m.get(w.AT_Technology__c)[1] += integer.valueOf(String.valueOf(w.AT_Expected_Product__c)); 
                else if(w.Stage__c.contains('2') && w.AT_Forecast_Status__c == commitStatus)
                    m.get(w.AT_Technology__c)[2] += integer.valueOf(String.valueOf(w.AT_Expected_Product__c));      
                else if(w.Stage__c.contains('3') && w.AT_Forecast_Status__c == upsideStatus)
                    m.get(w.AT_Technology__c)[3] += integer.valueOf(String.valueOf(w.AT_Expected_Product__c));
                else if(w.Stage__c.contains('3') && w.AT_Forecast_Status__c == commitStatus)
                    m.get(w.AT_Technology__c)[4] += integer.valueOf(String.valueOf(w.AT_Expected_Product__c));      
                else if(w.Stage__c.contains('4') && w.AT_Forecast_Status__c == upsideStatus)
                    m.get(w.AT_Technology__c)[5] += integer.valueOf(String.valueOf(w.AT_Expected_Product__c));
                else if(w.Stage__c.contains('4') && w.AT_Forecast_Status__c == commitStatus)
                    m.get(w.AT_Technology__c)[6] += integer.valueOf(String.valueOf(w.AT_Expected_Product__c)); 
                else if(w.Stage__c.contains('5') && w.AT_Forecast_Status__c == upsideStatus)
                    m.get(w.AT_Technology__c)[7] += integer.valueOf(String.valueOf(w.AT_Expected_Product__c));
                else if(w.Stage__c.contains('5') && w.AT_Forecast_Status__c == commitStatus)
                    m.get(w.AT_Technology__c)[8] += integer.valueOf(String.valueOf(w.AT_Expected_Product__c));     
            }
            else{
                String Technology = w.AT_Technology__c;
                Integer Stage1NotForecastable = 0;
                Integer Stage2Upside = 0;
                Integer Stage2Commit = 0;
                Integer Stage3Upside = 0;
                Integer Stage3Commit = 0;
                Integer Stage4Upside = 0;
                Integer Stage4Commit = 0;
                Integer Stage5Upside = 0;
                Integer Stage5Commit = 0;
                
                if(w.Stage__c.contains('1'))
                    Stage1NotForecastable = integer.valueOf(String.valueOf(w.AT_Expected_Product__c));
                else if(w.Stage__c.contains('2') && w.AT_Forecast_Status__c == upsideStatus)
                    Stage2Upside = integer.valueOf(String.valueOf(w.AT_Expected_Product__c)); 
                else if(w.Stage__c.contains('2') && w.AT_Forecast_Status__c == commitStatus)
                    Stage2Commit = integer.valueOf(String.valueOf(w.AT_Expected_Product__c));      
                else if(w.Stage__c.contains('3') && w.AT_Forecast_Status__c == upsideStatus)
                    Stage3Upside = integer.valueOf(String.valueOf(w.AT_Expected_Product__c));
                else if(w.Stage__c.contains('3') && w.AT_Forecast_Status__c == commitStatus)
                    Stage3Commit = integer.valueOf(String.valueOf(w.AT_Expected_Product__c));      
                else if(w.Stage__c.contains('4') && w.AT_Forecast_Status__c == upsideStatus)
                    Stage4Upside = integer.valueOf(String.valueOf(w.AT_Expected_Product__c));
                else if(w.Stage__c.contains('4') && w.AT_Forecast_Status__c == commitStatus)
                    Stage4Commit = integer.valueOf(String.valueOf(w.AT_Expected_Product__c)); 
                else if(w.Stage__c.contains('5') && w.AT_Forecast_Status__c == upsideStatus)
                    Stage5Upside = integer.valueOf(String.valueOf(w.AT_Expected_Product__c));
                else if(w.Stage__c.contains('5') && w.AT_Forecast_Status__c == commitStatus)
                    Stage5Commit = integer.valueOf(String.valueOf(w.AT_Expected_Product__c)); 
                
                Integer[] dollarSums = new Integer[]{Stage1NotForecastable,Stage2Upside,Stage2Commit,Stage3Upside,Stage3Commit,Stage4Upside,Stage4Commit,Stage5Upside,Stage5Commit};
                
                m.put(Technology,dollarSums);
                             
            }
            
        }
        
        for(String Tech: m.keySet()){  
          
            MyATTech at = new MyATTech();
            
            at.Technology = Tech;
            at.Stage1NotForecastable= m.get(Tech)[0];
            at.Stage2Upside= m.get(Tech)[1];
            at.Stage2Commit= m.get(Tech)[2];
            at.Stage3Upside= m.get(Tech)[3];
            at.Stage3Commit= m.get(Tech)[4];
            at.Stage4Upside= m.get(Tech)[5];
            at.Stage4Commit= m.get(Tech)[6];
            at.Stage5Upside= m.get(Tech)[7];
            at.Stage5Commit= m.get(Tech)[8];
            
            ATsums.add(at);            
        }

        return ATsums;
        
   }
   
   public static testMethod void test_ActionRequiredWS(){
       
        Opportunity oppty1 = new Opportunity(name='Test1',StageName='1 - Prospect',CloseDate= System.today());
        Opportunity oppty3 = new Opportunity(name='Test3',StageName='2 - Qualification',CloseDate= System.today());
        Opportunity oppty5 = new Opportunity(name='Test5',StageName='3 - Proposal',CloseDate= System.today());
        Opportunity oppty7 = new Opportunity(name='Test7',StageName='4 - Agreement',CloseDate= System.today());
        Opportunity oppty9 = new Opportunity(name='Test9',StageName='5 - Closed Won',CloseDate= System.today());
       
        Opportunity[] opptyArray = new Opportunity[]{oppty1,oppty3,oppty5,oppty7,oppty9};

        Database.SaveResult[]  result = Database.Insert(opptyArray);
        
        AT_Workspace__c[] workspaceArray = new AT_Workspace__c[]{};
        
        for(Database.SaveResult o : result){
            AT_Workspace__c temp = new AT_Workspace__c(AT_Technology__c='UC',AT_Expected_Product__c=integer.valueOf(2),PSS__c=UserInfo.getUserId(),AT_Expected_Book_Date__c=System.today(),AT_Forecast_Status__c='Upside',Opportunity__c=o.Id);
            AT_Workspace__c temp2 = new AT_Workspace__c(AT_Technology__c='UC',AT_Expected_Product__c=integer.valueOf(2),PSS__c=UserInfo.getUserId(),AT_Expected_Book_Date__c=System.today(),AT_Forecast_Status__c='Commit',Opportunity__c=o.Id);
            workspaceArray.add(temp);
            workspaceArray.add(temp2);
            
            AT_Workspace__c temp3 = new AT_Workspace__c(AT_Technology__c=o.id,AT_Expected_Product__c=integer.valueOf(2),PSS__c=UserInfo.getUserId(),AT_Expected_Book_Date__c=System.today(),AT_Forecast_Status__c='Upside',Opportunity__c=o.Id);
            AT_Workspace__c temp4 = new AT_Workspace__c(AT_Technology__c=o.id+'ANS',AT_Expected_Product__c=integer.valueOf(2),PSS__c=UserInfo.getUserId(),AT_Expected_Book_Date__c=System.today(),AT_Forecast_Status__c='Commit',Opportunity__c=o.Id);
            workspaceArray.add(temp3);
            workspaceArray.add(temp4);   
        }
        
        Insert workspaceArray;
       
        getATFunnel();
   }

}