objects/Briefing_PM__c.object
<CustomObject>
    <description>Includes Site to Scheduler and Primary and Secondary PM mappings.</description>
    <label>Briefing PM</label>
    <nameField>
        <displayFormat>BPM-{0}</displayFormat>
        <label>Briefing Program Manager</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Briefing PMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CEE__c.object
<CustomObject>
    <description>This object will store summary level briefing information from CEE. This Object is created to Integrate CEE Applicaiton data with Salesforce.com. It allows users to link CEE Briefings with Accounts in Salesforce.com.</description>
    <label>Customer Engagements &amp; Events</label>
    <nameField>
        <displayFormat>CEE-{000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Engagements &amp; Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>OBX</fullName>
        <active>true</active>
        <description>Delivering Demonstrations, Briefings, and Events</description>
        <label>Outcome Based Experience (OBX - formerly EBC)</label>
    </recordTypes>
</CustomObject>

objects/CEE_Location__c.object
<CustomObject>
    <description>The location details for a given Location, either a Field Sales Office (FSO), Executive Briefing Center (EBC), or Customer Briefing Center provided as part of the Customer Engagement implementation.</description>
    <label>CEE Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CEE Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CEE_Room__c.object
<CustomObject>
    <fields>
        <fullName>CEE_Location__c</fullName>
        <label>CEE Location</label>
        <referenceTo>CEE_Location__c</referenceTo>
        <relationshipLabel>CEE Rooms</relationshipLabel>
        <relationshipName>CEE_Rooms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>CEE Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CEE Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CEE_PMLoadBalanceController_Test.cls
/***************************************************************************************************
Name    : CEE_PMLoadBalanceController_Test 
Author  : Eric Pesch
Purpose : Tests for the PM Load Balance list controller  
Created Date: Dec 1 2014
Modification History: 
Eric Pesch - Jan 5 2015: Added Comments, cleanup                     
*****************************************************************************************************/

@isTest
private class CEE_PMLoadBalanceController_Test {
    
    /*@method: PM Load Balance VF page tests*/
    private static testMethod void pmLoadBalanceTest() {
        //Variables
        String testRoot = null, testEnv = null;
        
        //Setup Account
        User admin = CEE_TestUtility.getUser('admin', true);
        Account acct = null;
        Opportunity oppty = null;
        
        System.runAs(admin){
            CEE_TestUtility.loadCustomSettings();
            acct = CEE_TestUtility.getAccount('brief', true);
        }
        
        //Setup location
        CEE_Location__c loc = CEE_TestUtility.getLocation('brief', true, 'EBC/EC');
        Briefing_PM__c briefPM = CEE_TestUtility.getBriefingPM('pm', true, loc);
        Briefing_PM__c briefPMB = CEE_TestUtility.getBriefingPM('am', true, loc);
        CEE_Room__c room = CEE_TestUtility.getRoom('brief', true, loc, false, 6);
        
        //Setup briefing
        Opportunity opppt =  CEE_TestUtility.getOpty();
        CEE__c briefing = CEE_TestUtility.getBriefing('brief', true, 'OBX', acct, opppt, loc);
        
        Test.startTest();
        ApexPages.StandardController stdItem = new ApexPages.StandardController(briefing);
        CEE_PMLoadBalanceController balanceController = new CEE_PMLoadBalanceController(stdItem);
        balanceController.setCurrAvailability();
        
        //Get classes
        CEE_PMLoadBalanceController.Header testHeader = new CEE_PMLoadBalanceController.Header();
        CEE_PMLoadBalanceController.Day testDay = new CEE_PMLoadBalanceController.Day();
        CEE_PMLoadBalanceController.PMAvailability testPM1 = new CEE_PMLoadBalanceController.PMAvailability();
        
        //Get utility methods
        List<CEE_PMLoadBalanceController.Header> headers = balanceController.getHeaders();
        
        List<SelectOption> months = balanceController.getDynMonth();
        balanceController.setDynMonth(null);
        
        List<SelectOption> sites = balanceController.getDynSite();
        balanceController.setDynSite(null);
        
        Test.stopTest();
    }
}