objects/Briefing_PM__c.object
<CustomObject>
    <fields>
        <fullName>Primary_PM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary PM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Briefing_PMs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Secondary_PM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Secondary PM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Briefing_PMs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>Includes Site to Scheduler and Primary and Secondary PM mappings.</description>
    <label>Briefing PM</label>
    <nameField>
        <displayFormat>BPM-{0}</displayFormat>
        <label>Briefing Program Manager</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Briefing PMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CEE_Location__c.object
<CustomObject>
    <description>The location details for a given Location, either a Field Sales Office (FSO), Executive Briefing Center (EBC), or Customer Briefing Center provided as part of the Customer Engagement implementation.</description>
    <label>CEE Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CEE Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CEEBriefingPMBeforeUpsert_Test.cls
/***************************************************************************************************
Name    : CEEBriefingPMBeforeUpsert_Test 
Author  : Eric Pesch
Purpose : Trigger Tests for the Briefing_PM__c object  
Created Date: Dec 1 2014
Modification History: 
Eric Pesch - Jan 5 2015: Added Comments, cleanup                     
*****************************************************************************************************/

@isTest
private class CEEBriefingPMBeforeUpsert_Test {
	
	/*@method: Test PM insertion*/
    static testMethod void pmInsertTest() {
        //Setup location
    	CEE_Location__c loc = CEE_TestUtility.getLocation('pm', true, 'EBC/EC');
    	
    	Test.startTest();
    	Briefing_PM__c briefPM = CEE_TestUtility.getBriefingPM('pm', true, loc);
    	
    	Test.stopTest();
    	
    	//System.assert(true, briefPM.Id != null);
    	//Check if user ID were populated correctly
    	//System.assert(true, briefPM.Primary_PM__c != null);
    	//System.assert(true, briefPM.Secondary_PM__c != null);
    }
}