objects/BTx_Engagement_Revenue__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <description>Comments associated with revenue</description>
        <label>Offer-Other Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Engagement_Total_DC_Mix__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Computing Systems Mix %</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Engagement__c</fullName>
        <description>BTx Engagement for which revenue is being captured.</description>
        <label>Project</label>
        <referenceTo>BTx_Engagement_Activity__c</referenceTo>
        <relationshipLabel>BTx Project Revenue by Offers</relationshipLabel>
        <relationshipName>BTx_Engagement_Revenue</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_this_a_Primary_Solution__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is this a Primary Offer?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Solution__c</fullName>
        <label>Offers</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agile Agency / Bank / Firm Platform</fullName>
                </value>
                <value>
                    <fullName>Business Conferencing and Training</fullName>
                </value>
                <value>
                    <fullName>Business Video</fullName>
                </value>
                <value>
                    <fullName>Connected Agency / Bank / Firm Platform</fullName>
                </value>
                <value>
                    <fullName>Connected Analytics for Network Deployment</fullName>
                </value>
                <value>
                    <fullName>Connected Analytics for Retail</fullName>
                </value>
                <value>
                    <fullName>Connected Energy</fullName>
                </value>
                <value>
                    <fullName>Connected Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Connected Processes</fullName>
                </value>
                <value>
                    <fullName>Critical Infrastructure Security</fullName>
                </value>
                <value>
                    <fullName>Customer Effort Analytics</fullName>
                </value>
                <value>
                    <fullName>Cyber Security for Industry</fullName>
                </value>
                <value>
                    <fullName>Cyber Security for Insurance / Banking</fullName>
                </value>
                <value>
                    <fullName>Digital Enterprise</fullName>
                </value>
                <value>
                    <fullName>Digital Interactive Experience</fullName>
                </value>
                <value>
                    <fullName>Digital Team Collaboration</fullName>
                </value>
                <value>
                    <fullName>Distribution Center-Future</fullName>
                </value>
                <value>
                    <fullName>Employee Enablement-Future</fullName>
                </value>
                <value>
                    <fullName>Extended Care</fullName>
                </value>
                <value>
                    <fullName>Flexible Fulfillment</fullName>
                </value>
                <value>
                    <fullName>Guest and Staff Communications</fullName>
                </value>
                <value>
                    <fullName>Guest Loyalty Experience</fullName>
                </value>
                <value>
                    <fullName>Guest Mobile Experience</fullName>
                </value>
                <value>
                    <fullName>Guest Personalized Stay</fullName>
                </value>
                <value>
                    <fullName>Intelligent Contact Center</fullName>
                </value>
                <value>
                    <fullName>Interactive Kiosks</fullName>
                </value>
                <value>
                    <fullName>Life Line</fullName>
                </value>
                <value>
                    <fullName>Location-Based Analytics</fullName>
                </value>
                <value>
                    <fullName>Location Integrated Real Time communications</fullName>
                </value>
                <value>
                    <fullName>Location Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Used to record revenue and pipeline information for a BTx Engagement</description>
    <label>BTx Project Revenue by Offer</label>
    <nameField>
        <displayFormat>BTx Revenue-{0}</displayFormat>
        <label>BTx Project Revenue</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BTx Project Revenue by Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BTx_Engagement_Test.cls
// ******* Change History ********
//  majanard - 03052015: Removed the reference for Vertical__c from BTx_Engagement_Revenue__c query.
// ******* Change History ********

@isTest(seeAllData=true)
private Class BTx_Engagement_Test
{
    static testMethod void BTx_Revenue_TestMethod()    
    {  
        Test.startTest(); 
        BTx_Engagement_Revenue__c btx = [SELECT ID, Engagement__c, Solution__c, Is_this_a_Primary_Solution__c, Comments__c FROM BTx_Engagement_Revenue__c limit 1];  
        btx.Solution__c = 'Other (provide description below)';
        btx.Comments__c = 'executing test method';
        btx.Is_this_a_Primary_Solution__c = false;
        btx.Engagement_Total_DC_Mix__c = 100;
        update btx;
        
        btx.Solution__c = 'Digital Store Entertainment';
       update btx;
        
        
        
        ApexPages.StandardController controller = new ApexPages.StandardController(btx);
        Apexpages.currentPage().getParameters().put('CF00N80000004vwCK_lkid',btx.Engagement__c);
        PageReference pageRef = new BTx_Revenue(controller).pageredir();
        Apexpages.currentPage().getParameters().put('CF00N80000004vwCK_lkid',null);
         Apexpages.currentPage().getParameters().put('retURL','/'+btx.ID);
        PageReference pageRef1 = new BTx_Revenue(controller).pageredir();
        Apexpages.currentPage().getParameters().put('note','true');
        Apexpages.currentPage().getParameters().put('sn','0');
        Apexpages.currentPage().getParameters().put('retURL','/'+btx.Engagement__c);
        PageReference pageRef2 = new BTx_Revenue(controller).pageredir();
        Test.stopTest();    
    }
}