objects/BTx_Engagement_Activity__c.object
<CustomObject>
    <description>Business Value Approach (BVA) is a sales process that targets our customers' critical business needs. It enables account teams to identify sales opportunities and best position Cisco products, services and solutions.
The BVA session will help you uncover the customer’s business initiatives, develop a hypothesis to address the customer’s business needs with a Cisco Solution, and develop a specific sales approach to move distinct opportunities through the BVA process.</description>
    <label>BTx Project/Activity</label>
    <nameField>
        <displayFormat>BTx Project-{0}</displayFormat>
        <label>BTx Project/Activity</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BTx Projects/Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CC_Response__c.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>NGCC Phase1:Lead/Prospect assocaited to response</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>CC Responses</relationshipLabel>
        <relationshipName>CC_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>NGCC Phase-1: Each customer response will be captured in CC Response object and this defines response detail including the customer disposition values.</description>
    <label>CC Response</label>
    <nameField>
        <label>CC Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>CustomCountry__c</fullName>
        <description>Lead Address Country</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALAND ISLANDS</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BONAIRE, SINT EUSTATIUS AND SABA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <businessProcess>NGCC Marketing Lead</businessProcess>
        <description>Prospect Leads from Next Gen Marketing Contact Center</description>
        <label>Prospect</label>
    </recordTypes>
</CustomObject>

objects/ObjectRecordTypeIds__c.object
<CustomObject>
    <fields>
        <fullName>AccountChannelRecordTypeId__c</fullName>
        <description>This field stores the id of the channel account record type.</description>
        <label>Account Channel RecordTypeId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountPartnerCompanyRecordTypeId__c</fullName>
        <description>This is the id for the Partner Company Record type.</description>
        <label>Account Partner Company RecordTypeId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_End_User_RecordTypeId__c</fullName>
        <description>This is the  Id for the End User Account record type.</description>
        <label>Account End User RecordTypeId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BTx_Engagement_Activity__c</fullName>
        <label>BTx Engagement Activity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BTx_Non_Engagement_Activity__c</fullName>
        <label>BTx Non-Engagement Activity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CEE_OBX_Record_Type_ID__c</fullName>
        <label>CEE OBX Record Type ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_TSN_RecordType__c</fullName>
        <description>Case TSN RecordType</description>
        <label>Case TSN RecordType</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Closed_Lead_RecordTypeId__c</fullName>
        <description>This field stores the id of the Closed Lead record type</description>
        <label>Closed Lead RecordTypeId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Manual_EndUser_RecordTypeId__c</fullName>
        <description>This is the id of the Contact Manual End User record type.</description>
        <label>Contact Manual EndUser RecordTypeId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Manual_Partner_RecordTypeId__c</fullName>
        <description>This is the record type id for Manual Partner Contact record type.</description>
        <label>Contact Manual Partner RecordTypeId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_PDB_RecordTypeId__c</fullName>
        <description>This is the record type Id of the Partner Provided contact record type.</description>
        <label>Contact PDB RecordTypeId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GSPO_Qualification_Record_Type__c</fullName>
        <description>Contains the record type id of GSPO Qualification record type</description>
        <label>GSPO Qualification Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LCD_Qualification_Record_Type_Id__c</fullName>
        <label>LCD Qualification Record Type Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manual_Lead_RecordTypeId__c</fullName>
        <description>This field stores the id of the Manual Lead record type id</description>
        <label>Manual Lead RecordTypeId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketing_Lead_RecordType__c</fullName>
        <description>This is to store marketing_Lead recordtype</description>
        <label>Marketing Lead RecordType</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketing_Qualified_Lead__c</fullName>
        <description>To store marketing qualified after approval process</description>
        <label>Marketing Qualified Lead</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Parent_RecordTypeId__c</fullName>
        <description>This field stores the id of the Opportunity Parent record type.</description>
        <label>Opportunity Parent RecordTypeId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Partner_Parent_RecordTypeId__c</fullName>
        <description>This field stores the id of the Opportunity Partner Parent record type id</description>
        <label>Opportunity Partner Parent RecordTypeId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Partner_Phase_RecordTypeId__c</fullName>
        <description>This field stores the id of the Opportunity Partner Phase record type id</description>
        <label>Opportunity Partner Phase RecordTypeId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Phase_RecordTypeId__c</fullName>
        <description>This field stores the id of the Opportunity Phase record type.</description>
        <label>Opportunity Phase RecordTypeId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Solution_Plan_RecordTypeId__c</fullName>
        <description>This field stores the id of the Oportunity Solution Plan record type id</description>
        <label>Opportunity Solution Plan RecordTypeId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Void_Merged_RecordTypeId__c</fullName>
        <description>This field stores the id of the Opportunity Void Merged record type id</description>
        <label>Opportunity Void Merged RecordTypeId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Generated_Lead_RecordTypeId__c</fullName>
        <description>This field stores the id of the Partner Generated Lead record type id</description>
        <label>Partner Generated Lead RecordTypeId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>eLeadsRecordTypeId__c</fullName>
        <description>This field stores the id of the eLeads record type id.</description>
        <label>eLeadsRecordTypeId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is used to store the record type ids of account and contact objects.</description>
    <label>Object Record Type Ids</label>
</CustomObject>

classes/NGCC_MobilePostChat_Survey_Test.cls
@isTest(seeAllData=True)     
public class NGCC_MobilePostChat_Survey_Test{    
    
    public static testMethod void test_Survey() {
        Lead chtLead = new Lead();
        chtLead.LastName = 'Chat Test';
        chtLead.status= 'New Prospect';
        chtLead.company= 'Salesforce';
        chtLead.CustomCountry__c = 'India';
        chtLead.RecordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('Prospect').getRecordTypeId();
        insert  chtLead; 
        CC_Response__c resp = new CC_Response__c();
        resp.Lead__c = chtLead.id;
        resp.Name = 'Salesforce';
        insert resp;
        
        String currentPosition = Apexpages.currentPage().getParameters().put('userLocation',chtLead.id);
        String transcriptDetailsTemp = Apexpages.currentPage().getParameters().put('transcriptDetails',UserInfo.getUserId());
        String session_ID = Apexpages.currentPage().getParameters().put('session_ID','89a9a262-0731-4830-ab26-789643e2eefb');
        String chatButton_ID  = Apexpages.currentPage().getParameters().put('chatButton_ID','57334000000000');
        String buttonid  = Apexpages.currentPage().getParameters().put('buttonId','573340000004DIs');
        NGCC_MobilePostChat_Survey_Cls npg = new NGCC_MobilePostChat_Survey_Cls();
        NGCC_MobilePostChat_Survey_Cls.getAgentDetails(chtLead.Id,UserInfo.getUserID());
    }
    static void loadOrgRecTypeCS(){
        ObjectRecordTypeIds__c objrecType = new ObjectRecordTypeIds__c();
        objrecType.ACCOUNTCHANNELRECORDTYPEID__C='0123000000004aV';
        objrecType.ACCOUNT_END_USER_RECORDTYPEID__C='0123000000004aU';
        objrecType.ACCOUNTPARTNERCOMPANYRECORDTYPEID__C='01280000000G6ts';
        objrecType.CONTACT_MANUAL_ENDUSER_RECORDTYPEID__C='0123000000004aT';
        objrecType.CONTACT_MANUAL_PARTNER_RECORDTYPEID__C='01280000000G6ti';
        objrecType.CONTACT_PDB_RECORDTYPEID__C='01280000000G6tn';
        objrecType.CLOSED_LEAD_RECORDTYPEID__C='012300000001O02';
        objrecType.ELEADSRECORDTYPEID__C='0123000000004aR';
        objrecType.MANUAL_LEAD_RECORDTYPEID__C='0123000000004aS';
        objrecType.OPPORTUNITY_PARENT_RECORDTYPEID__C='0123000000003yk';
        objrecType.OPPORTUNITY_PARTNER_PARENT_RECORDTYPEID__C='0128000000020Dl';
        objrecType.OPPORTUNITY_PARTNER_PHASE_RECORDTYPEID__C='0128000000020Dq';
        objrecType.OPPORTUNITY_PHASE_RECORDTYPEID__C='012300000000CDL';
        objrecType.OPPORTUNITY_SOLUTION_PLAN_RECORDTYPEID__C='012300000000bfZ';
        objrecType.OPPORTUNITY_VOID_MERGED_RECORDTYPEID__C='012800000002e0M';
        objrecType.PARTNER_GENERATED_LEAD_RECORDTYPEID__C='012300000000lFW';
        objrecType.GSPO_QUALIFICATION_RECORD_TYPE__C='01280000000G7GD';
        objrecType.LCD_QUALIFICATION_RECORD_TYPE_ID__C='012800000003c7X';
        objrecType.BTX_ENGAGEMENT_ACTIVITY__C='01280000000G6LR';
        objrecType.BTX_NON_ENGAGEMENT_ACTIVITY__C='01280000000G6Lb';
        objrecType.CASE_TSN_RECORDTYPE__C='01280000000G78n';
        objrecType.MARKETING_LEAD_RECORDTYPE__C='012S00000000fSJ';
        objrecType.MARKETING_QUALIFIED_LEAD__C='012S00000000fSK';
        objrecType.CEE_OBX_Record_Type_ID__c='01280000000GFZzAAO';
        insert objrecType;    
    }
}