objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Call_Script__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CC Call Script</label>
        <referenceTo>CC_Call_Script__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Campaign_Name__c</fullName>
        <label>Campaign Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign_source__c</fullName>
        <label>Campaign source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Originating_Country__c</fullName>
        <label>Program Originating Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

objects/CC_Call_Script__c.object
<CustomObject>
    <fields>
        <fullName>Default_Call_Script__c</fullName>
        <defaultValue>false</defaultValue>
        <description>NGCC Phase1: The call script which can be defined as default</description>
        <inlineHelpText>Check mark if this Call Script constitutes to default Call Script</inlineHelpText>
        <label>Default Call Script</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Global Eloqua</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>NGCC Phase1: Current Status of the Call Script</description>
        <inlineHelpText>Shows the Current Status of the Call Script</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Previewed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Theater__c</fullName>
        <description>NGCC Phase1: Call Script Theater where the Call Script will be Used</description>
        <inlineHelpText>Call Script Theater where the Call Script will be Used</inlineHelpText>
        <label>Theater</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>APJ</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
                <value>
                    <fullName>EMEAR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>NGCC Phase1: Call Script master object which defines call scripts and its current status. Call Script can be edited only if the call script is in draft or inactive.</description>
    <label>CC Call Script</label>
    <nameField>
        <label>CC Call Script Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Call Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Campaign_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>NGCC Phase1:Unica Campaign name</description>
        <label>Campaign Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Campaign.Eloqua_Campaign_Id__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CustomCountry__c</fullName>
        <description>Lead Address Country</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALAND ISLANDS</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BONAIRE, SINT EUSTATIUS AND SABA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>UNITED STATES</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Theater__c</fullName>
        <description>Theatre Name 
LTLM integrated field</description>
        <label>Theater</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <businessProcess>NGCC Marketing Lead</businessProcess>
        <description>Prospect Leads from Next Gen Marketing Contact Center</description>
        <label>Prospect</label>
    </recordTypes>
</CustomObject>

objects/NGCC_Mapping_Object__c.object
<CustomObject>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Chinese (Simplified): zh_CN</fullName>
                </value>
                <value>
                    <fullName>Danish: da</fullName>
                </value>
                <value>
                    <fullName>Dutch: nl_NL</fullName>
                </value>
                <value>
                    <fullName>English: en_US</fullName>
                </value>
                <value>
                    <fullName>Finnish: fi</fullName>
                </value>
                <value>
                    <fullName>French: fr</fullName>
                </value>
                <value>
                    <fullName>German: de</fullName>
                </value>
                <value>
                    <fullName>Italian: it</fullName>
                </value>
                <value>
                    <fullName>Japanese: ja</fullName>
                </value>
                <value>
                    <fullName>Korean: ko</fullName>
                </value>
                <value>
                    <fullName>Portuguese (Brazil): pt_BR</fullName>
                </value>
                <value>
                    <fullName>Russian: ru</fullName>
                </value>
                <value>
                    <fullName>Spanish: es</fullName>
                </value>
                <value>
                    <fullName>Thai: th</fullName>
                </value>
                <value>
                    <fullName>Polish: pl</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Theater__c</fullName>
        <label>Theater</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>APJ</fullName>
                </value>
                <value>
                    <fullName>EMEAR</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CC Mapping Object</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NGCC Mapping Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/NGCC_Campaign_Managment_Test.cls
@isTest(SeeAllData = true)
public class NGCC_Campaign_Managment_Test {
    
    public static Campaign campgDataPrep(){
        Campaign cm = new Campaign();
        cm.Name = 'tst Campaign';
        cm.Program_Originating_Country__c ='UNITED STATES';
        return cm;
    }
    
    @isTest
    public static void createCampaignTest(){
        ID mapRtyID = Schema.SObjectType.NGCC_Mapping_Object__c.getRecordTypeInfosByName().get('Country Mapping').getRecordTypeID();
        List <NGCC_Mapping_Object__c> cMap = new List <NGCC_Mapping_Object__c>();
        cMap.add(new NGCC_Mapping_Object__c( Name='UNITED STATES', Theater__c='Americas',Language__c='English: en_US',recordtypeId=mapRtyID));
        insert cMap;
        
        List <CC_Call_Script__c> callScript = new List<CC_Call_Script__c>();
        callScript.add(new CC_Call_Script__c(Name='Test_ELQ_AMER_Debug', Theater__c='Americas',Source__c='Global Eloqua',Status__c='Previewed', Default_Call_Script__c = true));
        callScript.add(new CC_Call_Script__c(Name='Test_AMER_Debug', Theater__c='Americas',Status__c='Previewed', Default_Call_Script__c = true));
        insert callScript;
        
        List<Campaign> newCmp = new List<Campaign>();
        Campaign cm = campgDataPrep();
        Campaign cm1 = campgDataPrep();
        cm1.Campaign_source__c ='Global Eloqua';
        newCmp.add(cm);
        newCmp.add(cm1);
        Test.startTest();
        insert newCmp;
        Test.stopTest();
        system.assert(cm.Call_Script__c == null || cm.Call_Script__c == '');
        system.assert(cm1.Call_Script__c == null || cm1.Call_Script__c == '');
        
    }
    
    @isTest
    public static void cancelCampaignTest(){
        Campaign cm = campgDataPrep();
        insert cm;
        
        List<Lead> nwLds = new List<Lead>();
        for (integer i=0; i<= 5; i++){
            Lead newLead = new Lead (
                LastName = 'Lead' +i,
                RecordTypeId = Schema.Sobjecttype.Lead.getRecordTypeInfosByName().get('Prospect').getRecordTypeId(),
                Company = '123',
                Status = 'New Prospect',
                CustomCountry__c = 'UNITED STATES', Campaign_Name__c =cm.Id);
            nwLds.add(newLead);
            
        }
        insert nwLds;
        cm.Status='Completed';
        Test.startTest();
        update cm;
        Test.stopTest();
        system.assert(cm.Status =='Completed');
        
        
        
    }

}