objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Program_Event_Code__c</fullName>
        <externalId>true</externalId>
        <label>Program Event Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Program_Event_Description__c</fullName>
        <label>Program Event Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Program_Event_Name__c</fullName>
        <label>Program Event Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>Eloqua_Campaign__c</fullName>
        <description>MCP April Release 2015: To Validate if the members are associated to Eloqua Campaign not NGCC</description>
        <formula>If( ISBLANK(Campaign.Eloqua_Campaign_Id__c) ,false,true)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Eloqua Campaign</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByCampaign</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Campaign_Description__c</fullName>
        <description>Marketing Program Description
LTLM SFDC Mapping
$Start/group/pfx:TRN__LEADS/CPGN__NAME</description>
        <label>Campaign Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProgramEvent__c</fullName>
        <description>Program Event Code/Key Code associated with the lead generation
LTLM integrated field</description>
        <label>Program Event Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Event_Description__c</fullName>
        <description>NGCC Phase1:Unica cell description</description>
        <label>Program Event Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Program_Event_Name__c</fullName>
        <description>Name of the Program Event Code/Key Code associated with the lead generation</description>
        <label>Program Event Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/EloquaCampaignAssociationUpdateTrg_Cls.cls
/*********************************************************************************************************************************
Name    : EloquaCampaignAssociationUpdateTrg_Cls
Author  : Mukesh Srivastava
Purpose : The purpose of the class to handle after insert operation on Eloqua Leads association .Updating all the eloqua leads 
          which doesnt have Program event details          
Created Date:  2/24/2015 
Modification History: 
                      
**********************************************************************************************************************************/
public class EloquaCampaignAssociationUpdateTrg_Cls{
     
    /* Collect all the Leads associated to Campaign*/
    public static void CampaignMemberProcessing(List<CampaignMember> newLstCM)
    {
            map<Id,CampaignMember> mapOfLead = new map<Id,CampaignMember>();
            Set<Id> setCampaign = new Set<Id>();
                    
            for(CampaignMember cmObj : newLstCM){
                if(cmObj.Eloqua_Campaign__c){
                    if(cmObj.LeadId != Null){
                        mapOfLead.put(cmObj.LeadId,cmObj); //Collecting map of Lead Id and Campaign Member Object
                        setCampaign.add(cmObj.CampaignId); //Collecting Set of Campaign Id for pulling Campaign details
                    }
                }
            }         
            
            if(!mapOfLead.isEmpty()){
                UpdateCampaignName(mapOfLead,setCampaign);
            }
    }
    /* Update the Leads attribute if the campaign detail at Lead level is blank*/
    public static void UpdateCampaignName(map<Id,CampaignMember> newCM_C,Set<Id> setOfCamp)
    {
        //Querying List of Campaigns used for member association
        Map<Id,Campaign> mapIdCampaign = new Map<Id,Campaign>([SELECT Id,Name,Description,Program_Event_Code__c from Campaign where Id IN :setOfCamp]);
        
        String userName = 'eloqua_integration@cisco.com';
        
        if(Test.isRunningTest()){
            userName = 'eloqua_integration@cisco.com.testing';
        }
       
        //Pull Lead detail which need the update
        List<Lead> lstLead = [Select Id,Program_Event_Name__c,ProgramEvent__c,Program_Event_Description__c,Campaign_Description__c from Lead where Id IN : newCM_C.keySet() AND CreatedBy.UserName=:userName];
        
        //Updating Lead detail with Campaign Information only if the details are missing.
        for(Lead lObj : lstLead){
            if(lObj.Program_Event_Name__c == NULL){
               lObj.Program_Event_Name__c = mapIdCampaign.get(newCM_C.get(lObj.Id).CampaignId).Name;
            }
            
            if(lObj.ProgramEvent__c == NULL){
              lObj.ProgramEvent__c = mapIdCampaign.get(newCM_C.get(lObj.Id).CampaignId).Program_Event_Code__c; 
            }
            
            if(lObj.Campaign_Description__c == NULL){                
                lObj.Campaign_Description__c = mapIdCampaign.get(newCM_C.get(lObj.Id).CampaignId).Description;
            }            
        }
        //Updating the updated list
        Database.SaveResult[] lstEloquaSaveResult = Database.update(lstLead, true);
    }
}