objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Campaign_Code__c</fullName>
        <label>Campaign Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign_Name__c</fullName>
        <label>Campaign Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Offer_Architecture__c</fullName>
        <label>Offer Architecture</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Offer_Description__c</fullName>
        <label>Offer Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Offer_Name__c</fullName>
        <label>Offer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Offer_URL__c</fullName>
        <label>Offer URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Technology__c</fullName>
        <label>Primary Technology</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Event_Description__c</fullName>
        <label>Program Event Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Program_Event_Name__c</fullName>
        <label>Program Event Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Campaign_Code__c</fullName>
        <description>NGCC Phase1:Unica Campaign code</description>
        <label>Campaign Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign_Description__c</fullName>
        <description>Marketing Program Description
LTLM SFDC Mapping
$Start/group/pfx:TRN__LEADS/CPGN__NAME</description>
        <label>Campaign Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>NGCC Phase1:Unica Campaign name</description>
        <label>Campaign Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Campaign.Eloqua_Campaign_Id__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CustomCountry__c</fullName>
        <description>Lead Address Country</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALAND ISLANDS</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BONAIRE, SINT EUSTATIUS AND SABA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>EGYPT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Offer_Architecture__c</fullName>
        <description>NGCC Phase1:Unica's treatment Offer Architecture</description>
        <label>Offer Architecture</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Offer_Description__c</fullName>
        <description>Created as part of P360 Sep '12 Release. 
Offer description for sending leads to sales. Entered in UNICA tool.</description>
        <label>Offer Description</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Offer_Name__c</fullName>
        <description>NGCC Phase1:Unica treatment's Offer Name</description>
        <label>Offer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Offer_URL__c</fullName>
        <description>Created as part of P360 Sep '12 Release. 
"URL of the offer.
Entered in UNICA tool"</description>
        <label>Offer URL</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Primary_Technology__c</fullName>
        <description>NGCC Phase1:Unica's treatment Primary Technology</description>
        <label>Primary Technology</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Event_Description__c</fullName>
        <description>NGCC Phase1:Unica cell description</description>
        <label>Program Event Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Program_Event_Name__c</fullName>
        <description>Name of the Program Event Code/Key Code associated with the lead generation</description>
        <label>Program Event Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Theater__c</fullName>
        <description>Theatre Name 
LTLM integrated field</description>
        <label>Theater</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <businessProcess>NGCC Marketing Lead</businessProcess>
        <description>Prospect Leads from Next Gen Marketing Contact Center</description>
        <label>Prospect</label>
    </recordTypes>
</CustomObject>

objects/ObjectRecordTypeIds__c.object
<CustomObject>
    <fields>
        <fullName>Marketing_Lead_RecordType__c</fullName>
        <description>This is to store marketing_Lead recordtype</description>
        <label>Marketing Lead RecordType</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is used to store the record type ids of account and contact objects.</description>
    <label>Object Record Type Ids</label>
</CustomObject>

classes/NGCC_Flow_Create_Callback_Task_Test.cls
@isTest(SeeAllData = true)
public class NGCC_Flow_Create_Callback_Task_Test {
    @isTest
    public static void CreateTaskTest(){
        Lead l;
        Campaign camp;
        List<NGCC_Flow_Create_Callback_Task.TaskFields> TaskInfo = new List<NGCC_Flow_Create_Callback_Task.TaskFields>();
        camp = new Campaign(Name='Testing Campaign',
                            Program_Event_Name__c = 'Program_Event_Name__c',
                            Offer_Description__c = 'Offer_Description__c',
                            Offer_URL__c = 'Offer_URL__c',
                            Primary_Technology__c = 'Primary_Technology__c',
                            Campaign_Code__c = 'Campaign_Code__c',
                            Description = 'Campaign_Description__c',
                            Program_Event_Description__c = 'Program_Event_Description__c',
                            Offer_Name__c = 'Offer_Name__c',
                            Offer_Architecture__c = 'Offer_Architecture__c'
                            
                           );
        insert camp;
        
        ObjectRecordTypeIds__c orgConstant = ObjectRecordTypeIds__c.getInstance(); 
        Id marketingRecId = orgConstant.Marketing_Lead_RecordType__c;
        l= new Lead();
        l.RecordTypeId=marketingRecId;
        l.Status = 'New Prospect';
        l.LastName = 'TestLast';
        l.Company = 'Test Company';
        l.Campaign_Name__c = camp.Id;
        l.CustomCountry__c = 'EGYPT';
        l.Theater__c = 'EMEAR';
        insert l;
        
        NGCC_Flow_Create_Callback_Task.TaskFields taskdetails = new NGCC_Flow_Create_Callback_Task.TaskFields();
        taskdetails.WhoId = l.id;
        taskdetails.LeadFirstname='Test';
        taskdetails.LeadLastname ='TestLast';
        taskdetails.CallbackDateTime=system.now();
        taskdetails.Theater='EMEAR';
        
        TaskInfo.add(taskdetails);
        NGCC_Flow_Create_Callback_Task.CreateTask(TaskInfo);
    }
}