objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Eloqua_Campaign_Id__c</fullName>
        <description>MCP April Release 2015:  To store Eloqua System Generated Id</description>
        <label>Eloqua Campaign Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

objects/EloquaCampaignMemberStatus__c.object
<CustomObject>
    <fields>
        <fullName>HasResponded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>HasResponded</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SortOrder__c</fullName>
        <label>SortOrder</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Eloqua April Release 2015: To Store new status for Campaign Members</description>
    <label>EloquaCampaignMemberStatus</label>
</CustomObject>

objects/EloquaFieldUpdates__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Eloqua April 2015: List of Field which need to be updated once eloqua rating is available</description>
    <label>EloquaFieldUpdates</label>
</CustomObject>

classes/EloquaCampaignAdvanceSetupTrg_Cls.cls
/*********************************************************************************************************************************
Name    : EloquaCampaignAssociationUpdateTrg_Cls
Author  : Mukesh Srivastava
Purpose : The purpose of the class to handle after insert operation on Eloqua Leads association .Updating all the eloqua leads 
          which doesnt have Program event details          
Created Date:  2/24/2015 
Modification History: 
                      
**********************************************************************************************************************************/
public class EloquaCampaignAdvanceSetupTrg_Cls{
    /* Collect all the Leads associated to Campaign*/
    public static void CampaignAdvanceSetup(List<Campaign> lstCamps){
          
    List<CampaignMemberStatus> newCampaignMemberStatus = new List<CampaignMemberStatus>();
    Map < String, EloquaCampaignMemberStatus__c> eloquaCampaignStatus = EloquaCampaignMemberStatus__c.getAll();
    Map < String, EloquaFieldUpdates__c > eloquaFieldMapping = EloquaFieldUpdates__c.getAll();
    
    List<EloquaCampaignMemberStatus__c> sf=new list<EloquaCampaignMemberStatus__c>([Select Id from EloquaCampaignMemberStatus__c]);

    for (Campaign c : lstCamps) {
        // Add campaign ids to list for removal of campaign member status values 
                     
        if(c.Eloqua_Campaign_Id__c != NULL){
            for(EloquaCampaignMemberStatus__c eCS: eloquaCampaignStatus.values()){
                    newCampaignMemberStatus.add (new CampaignMemberStatus(
                    CampaignId=c.id,
                    HasResponded=eCS.HasResponded__c,
                    IsDefault=eCS.IsDefault__c,
                    Label=eCS.Name,
                    SortOrder=eCS.SortOrder__c.intValue()));        
            }
        }
              
    }//end loop
        if(!newCampaignMemberStatus.isEmpty()){
            insert newCampaignMemberStatus;
        }
    }
}