objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Priority__c</fullName>
        <description>User Story- 5251</description>
        <label>Priority</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

objects/CC_Response__c.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>NGCC Phase1:Lead/Prospect assocaited to response</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>CC Responses</relationshipLabel>
        <relationshipName>CC_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>NGCC Phase-1: Each customer response will be captured in CC Response object and this defines response detail including the customer disposition values.</description>
    <label>CC Response</label>
    <nameField>
        <label>CC Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CC_Response_Detail__c.object
<CustomObject>
    <fields>
        <fullName>CC_Master_Question_Answer_Bank__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>NGCC Phase1:Reference to the master question and answer bank associated to call script Q and A</description>
        <label>CC Master Question/Answer Bank</label>
        <referenceTo>CC_Master_Question_Answer_Bank__c</referenceTo>
        <relationshipLabel>CC Response Detail (CC Master Question/Answer Bank)</relationshipLabel>
        <relationshipName>CC_Response_Detail1</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>NGCC Phase-1: Customer response which captured during the call script will be stored in Response Detail Object.</description>
    <label>CC Response Detail</label>
    <nameField>
        <label>CC Response Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Response Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/NGCC_Rule_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Countries__c</fullName>
        <label>Country</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Theater__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BRITISH INDIAN OCEAN TERRITORY</fullName>
                </value>
                <value>
                    <fullName>BRUNEI DARUSSALAM</fullName>
                </value>
                <value>
                    <fullName>CAMBODIA</fullName>
                </value>
                <value>
                    <fullName>CHRISTMAS ISLAND</fullName>
                </value>
                <value>
                    <fullName>COCOS (KEELING) ISLANDS</fullName>
                </value>
                <value>
                    <fullName>COOK ISLANDS</fullName>
                </value>
                <value>
                    <fullName>FIJI</fullName>
                </value>
                <value>
                    <fullName>FRENCH POLYNESIA</fullName>
                </value>
                <value>
                    <fullName>INDIA</fullName>
                </value>
                <value>
                    <fullName>INDONESIA</fullName>
                </value>
                <value>
                    <fullName>JAPAN</fullName>
                </value>
                <value>
                    <fullName>KIRIBATI</fullName>
                </value>
                <value>
                    <fullName>KOREA, REPUBLIC OF</fullName>
                </value>
                <value>
                    <fullName>KOREA,DEMOCRATIC PEOPLE'S REPUBLIC OF</fullName>
                </value>
                <value>
                    <fullName>LAO PEOPLE'S DEMOCRATIC REPUBLIC</fullName>
                </value>
                <value>
                    <fullName>MALAYSIA</fullName>
                </value>
                <value>
                    <fullName>MALDIVES</fullName>
                </value>
                <value>
                    <fullName>MARSHALL ISLANDS</fullName>
                </value>
                <value>
                    <fullName>MICRONESIA, FEDERATED STATES OF</fullName>
                </value>
                <value>
                    <fullName>MYANMAR</fullName>
                </value>
                <value>
                    <fullName>NAURU</fullName>
                </value>
                <value>
                    <fullName>NEPAL</fullName>
                </value>
                <value>
                    <fullName>NEW CALEDONIA</fullName>
                </value>
                <value>
                    <fullName>NEW ZEALAND</fullName>
                </value>
                <value>
                    <fullName>NIUE</fullName>
                </value>
                <value>
                    <fullName>UNITED STATES</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_Attribute__c</fullName>
        <label>Lead Attribute API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MODS_Leads__c</fullName>
        <label>MODS / Leads</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MODS Q/A</fullName>
                </value>
                <value>
                    <fullName>Lead Attribute</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1-High</fullName>
                </value>
                <value>
                    <fullName>2-Medium</fullName>
                </value>
                <value>
                    <fullName>3-Low</fullName>
                </value>
                <value>
                    <fullName>4-N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CC Lead Priority Rule</label>
    <nameField>
        <displayFormat>NGCC Rule-{000000}</displayFormat>
        <label>NGCC Rule Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Lead Priority Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Leads</fullName>
        <active>true</active>
        <description>Choose "Leads" for Lead rules</description>
        <label>Leads</label>
    </recordTypes>
    <recordTypes>
        <fullName>MODS</fullName>
        <active>false</active>
        <description>Choose "MODS" for MODS rules</description>
        <label>MODS</label>
    </recordTypes>
</CustomObject>

objects/ObjectRecordTypeIds__c.object
<CustomObject>
    <fields>
        <fullName>AccountChannelRecordTypeId__c</fullName>
        <description>This field stores the id of the channel account record type.</description>
        <label>Account Channel RecordTypeId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountPartnerCompanyRecordTypeId__c</fullName>
        <description>This is the id for the Partner Company Record type.</description>
        <label>Account Partner Company RecordTypeId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_End_User_RecordTypeId__c</fullName>
        <description>This is the  Id for the End User Account record type.</description>
        <label>Account End User RecordTypeId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BTx_Engagement_Activity__c</fullName>
        <label>BTx Engagement Activity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BTx_Non_Engagement_Activity__c</fullName>
        <label>BTx Non-Engagement Activity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CEE_OBX_Record_Type_ID__c</fullName>
        <label>CEE OBX Record Type ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_TSN_RecordType__c</fullName>
        <description>Case TSN RecordType</description>
        <label>Case TSN RecordType</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Closed_Lead_RecordTypeId__c</fullName>
        <description>This field stores the id of the Closed Lead record type</description>
        <label>Closed Lead RecordTypeId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Manual_EndUser_RecordTypeId__c</fullName>
        <description>This is the id of the Contact Manual End User record type.</description>
        <label>Contact Manual EndUser RecordTypeId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Manual_Partner_RecordTypeId__c</fullName>
        <description>This is the record type id for Manual Partner Contact record type.</description>
        <label>Contact Manual Partner RecordTypeId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_PDB_RecordTypeId__c</fullName>
        <description>This is the record type Id of the Partner Provided contact record type.</description>
        <label>Contact PDB RecordTypeId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GSPO_Qualification_Record_Type__c</fullName>
        <description>Contains the record type id of GSPO Qualification record type</description>
        <label>GSPO Qualification Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LCD_Qualification_Record_Type_Id__c</fullName>
        <label>LCD Qualification Record Type Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manual_Lead_RecordTypeId__c</fullName>
        <description>This field stores the id of the Manual Lead record type id</description>
        <label>Manual Lead RecordTypeId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketing_Lead_RecordType__c</fullName>
        <description>This is to store marketing_Lead recordtype</description>
        <label>Marketing Lead RecordType</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketing_Qualified_Lead__c</fullName>
        <description>To store marketing qualified after approval process</description>
        <label>Marketing Qualified Lead</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Parent_RecordTypeId__c</fullName>
        <description>This field stores the id of the Opportunity Parent record type.</description>
        <label>Opportunity Parent RecordTypeId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Partner_Parent_RecordTypeId__c</fullName>
        <description>This field stores the id of the Opportunity Partner Parent record type id</description>
        <label>Opportunity Partner Parent RecordTypeId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Partner_Phase_RecordTypeId__c</fullName>
        <description>This field stores the id of the Opportunity Partner Phase record type id</description>
        <label>Opportunity Partner Phase RecordTypeId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Phase_RecordTypeId__c</fullName>
        <description>This field stores the id of the Opportunity Phase record type.</description>
        <label>Opportunity Phase RecordTypeId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Solution_Plan_RecordTypeId__c</fullName>
        <description>This field stores the id of the Oportunity Solution Plan record type id</description>
        <label>Opportunity Solution Plan RecordTypeId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Void_Merged_RecordTypeId__c</fullName>
        <description>This field stores the id of the Opportunity Void Merged record type id</description>
        <label>Opportunity Void Merged RecordTypeId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Generated_Lead_RecordTypeId__c</fullName>
        <description>This field stores the id of the Partner Generated Lead record type id</description>
        <label>Partner Generated Lead RecordTypeId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>eLeadsRecordTypeId__c</fullName>
        <description>This field stores the id of the eLeads record type id.</description>
        <label>eLeadsRecordTypeId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is used to store the record type ids of account and contact objects.</description>
    <label>Object Record Type Ids</label>
</CustomObject>

classes/NGCC_Lead_Priority_Test.cls
@isTest
//(seealldata=true)
public class NGCC_Lead_Priority_Test {

    static void loadOrgRecTypeCS(){
        ObjectRecordTypeIds__c objrecType = new ObjectRecordTypeIds__c();
        objrecType.ACCOUNTCHANNELRECORDTYPEID__C='0123000000004aV';
        objrecType.ACCOUNT_END_USER_RECORDTYPEID__C='0123000000004aU';
        objrecType.ACCOUNTPARTNERCOMPANYRECORDTYPEID__C='01280000000G6ts';
        objrecType.CONTACT_MANUAL_ENDUSER_RECORDTYPEID__C='0123000000004aT';
        objrecType.CONTACT_MANUAL_PARTNER_RECORDTYPEID__C='01280000000G6ti';
        objrecType.CONTACT_PDB_RECORDTYPEID__C='01280000000G6tn';
        objrecType.CLOSED_LEAD_RECORDTYPEID__C='012300000001O02';
        objrecType.ELEADSRECORDTYPEID__C='0123000000004aR';
        objrecType.MANUAL_LEAD_RECORDTYPEID__C='0123000000004aS';
        objrecType.OPPORTUNITY_PARENT_RECORDTYPEID__C='0123000000003yk';
        objrecType.OPPORTUNITY_PARTNER_PARENT_RECORDTYPEID__C='0128000000020Dl';
        objrecType.OPPORTUNITY_PARTNER_PHASE_RECORDTYPEID__C='0128000000020Dq';
        objrecType.OPPORTUNITY_PHASE_RECORDTYPEID__C='012300000000CDL';
        objrecType.OPPORTUNITY_SOLUTION_PLAN_RECORDTYPEID__C='012300000000bfZ';
        objrecType.OPPORTUNITY_VOID_MERGED_RECORDTYPEID__C='012800000002e0M';
        objrecType.PARTNER_GENERATED_LEAD_RECORDTYPEID__C='012300000000lFW';
        objrecType.GSPO_QUALIFICATION_RECORD_TYPE__C='01280000000G7GD';
        objrecType.LCD_QUALIFICATION_RECORD_TYPE_ID__C='012800000003c7X';
        objrecType.BTX_ENGAGEMENT_ACTIVITY__C='01280000000G6LR';
        objrecType.BTX_NON_ENGAGEMENT_ACTIVITY__C='01280000000G6Lb';
        objrecType.CASE_TSN_RECORDTYPE__C='01280000000G78n';
        objrecType.MARKETING_LEAD_RECORDTYPE__C='012S00000000fSJ';
        objrecType.MARKETING_QUALIFIED_LEAD__C='012S00000000fSK';
        objrecType.CEE_OBX_Record_Type_ID__c='01280000000GFZzAAO';
        insert objrecType;    
    }

    static testMethod void NGCC_LeadPriority_Test1(){
       /* Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User u = new User(Alias = 'standt', Email='testUser@ngcc.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='testUser@ngcc.com');
        insert u;
        System.runAs(u) {*/
        loadOrgRecTypeCS();
        Campaign cm = new Campaign();
        cm.name = 'Tst Campaign ';
        insert cm;
 
        CC_Master_Question_Answer_Bank__c ccMaster = new CC_Master_Question_Answer_Bank__c(name='M');
        insert ccMaster;
        
        ID rtId=Schema.SObjectType.Lead.getRecordTypeInfosByName().get('Prospect').getRecordTypeID();
            
        list<NGCC_Rule_Assignment__c> rules = new list<NGCC_Rule_Assignment__c>();
        rules.add(new NGCC_Rule_Assignment__c(MODS_Leads__c='Lead Attribute',Countries__c='UK;US',Lead_Attribute__c='lastName',Priority__c='1',Rank__c='4',Theater__c='APJ',Value__c='m1,m'));
        rules.add(new NGCC_Rule_Assignment__c(MODS_Leads__c='Lead Attribute',Countries__c='UNITED STATES',Lead_Attribute__c='lastName',Priority__c='4-N/A',Rank__c='1',Theater__c='APJY',Value__c='m1,m'));

        rules.add(new NGCC_Rule_Assignment__c(MODS_Q_A__c=ccMaster.id,MODS_Leads__c='MODS Q/A',Countries__c='India;UNITED STATES',Priority__c='2',Rank__c='2',Theater__c='APJX',Value__c='m1,m'));
        rules.add(new NGCC_Rule_Assignment__c(MODS_Q_A__c=ccMaster.id,MODS_Leads__c='MODS Q/A',Countries__c='India;UNITED STATES',Priority__c='4-N/A',Rank__c='3',Theater__c='APJ',Value__c='m1,m'));
        insert rules;
        
        list<lead> leads = new list<lead>();
        leads.add(new lead(Campaign_Name__c = cm.id,lastName='m',CustomCountry__c='UNITED STATES',Theater__c='APJ',Company='Company',Status='1 Waiting',LeadSource='Web',recordtypeId=rtId));
        leads.add(new lead(Campaign_Name__c = cm.id,lastName='n',CustomCountry__c='UNITED STATES',Theater__c='APJY',Company='Company',Status='1 Waiting',LeadSource='Web',recordtypeId=rtId));
        leads.add(new lead(Campaign_Name__c = cm.id,lastName='o',CustomCountry__c='UNITED STATES',Theater__c='APJX',Company='Company',Status='1 Waiting',LeadSource='Web',recordtypeId=rtId));
        insert leads;
        
        list<CC_Response__c> response = new list<CC_Response__c>();
        response.add(new CC_Response__c(name='m',Lead__c=leads[0].id));
        
        insert response;
        
        
        list<CC_Response_Detail__c> detail = new list<CC_Response_Detail__c>();
        detail.add(new CC_Response_Detail__c(name='m',Response_Id__c=response[0].id,Customer_Response_Detail__c='m',CC_Master_Question_Answer_Bank__c=ccMaster.id));
        insert detail;
        
        
        for(Lead l : Leads){
            l.ETL_Load_Flag__c = true;
        }
        test.startTest();
        update leads;
        test.stopTest();
       // }
    }
    
    static testMethod void NGCC_LeadPriority_Bulk(){
        
    /*    Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User u = new User(Alias = 'standt', Email='testUser@ngcc.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='testUser@ngcc.com');
        insert u;
        System.runAs(u) {*/
        loadOrgRecTypeCS();
        Campaign cm = new Campaign();
        cm.name = 'Tst Campaign ';
        insert cm;
 
        CC_Master_Question_Answer_Bank__c ccMaster = new CC_Master_Question_Answer_Bank__c(name='m');
        insert ccMaster;
        
        ID rtId=Schema.SObjectType.Lead.getRecordTypeInfosByName().get('Prospect').getRecordTypeID();
            
        list<NGCC_Rule_Assignment__c> rules = new list<NGCC_Rule_Assignment__c>();
        rules.add(new NGCC_Rule_Assignment__c(MODS_Leads__c='Lead Attribute',Countries__c='UK;UNITED STATES',Lead_Attribute__c='lastName',Priority__c='1',Rank__c='1',Theater__c='APJXC',Value__c='m'));
        rules.add(new NGCC_Rule_Assignment__c(MODS_Q_A__c=ccMaster.id,MODS_Leads__c='MODS Q/A',Countries__c='India;UNITED STATES',Priority__c='2',Rank__c='2',Theater__c='APJXC',Value__c='m'));
        rules.add(new NGCC_Rule_Assignment__c(MODS_Q_A__c=ccMaster.id,MODS_Leads__c='MODS Q/A',Countries__c='India;UNITED STATES',Priority__c='4-N/A',Rank__c='3',Theater__c='APJ',Value__c='m'));
        insert rules;
        list<lead> leads;
        for(integer i=0; i<=500; i++){
            leads = new list<lead>();
            
            leads.add(new lead(Campaign_Name__c = cm.id,lastName='m',CustomCountry__c='UNITED STATES',Theater__c='APJXC',Company='Company',status='1 Waiting',LeadSource='Web',recordtypeId=rtId));
            leads.add(new lead(Campaign_Name__c = cm.id,lastName='m',CustomCountry__c='UNITED STATES',Theater__c='APJXC',Company='Company',status='1 Waiting',LeadSource='Web',recordtypeId=rtId));
            leads.add(new lead(Campaign_Name__c = cm.id,lastName='m',CustomCountry__c='UNITED STATES',Theater__c='APJ',Company='Company',status='1 Waiting',LeadSource='Web',recordtypeId=rtId));
        }   
        if(leads.size()  > 0 ){
            insert leads;
        }
        
        list<CC_Response__c> response;
        for(lead l : leads){
            if(l.id != null){
                 response = new list<CC_Response__c>();
                response.add(new CC_Response__c(name='m',Lead__c=l.id));
            }
        
        }
        
        
        if(response.size()  > 0 ){
            insert response;
        }
        list<CC_Response_Detail__c> detail;
        for(CC_Response__c c : response){
            if(c.id != null){
             detail = new list<CC_Response_Detail__c>();
            detail.add(new CC_Response_Detail__c(name='m',Response_Id__c=c.id,Customer_Response_Detail__c='m',CC_Master_Question_Answer_Bank__c=ccMaster.id));
            }
            
        }
            
        if(detail.size()  > 0 ){
            insert detail;
        }   
    
            
        for(Lead l : Leads){
            l.ETL_Load_Flag__c = true;
        }
        
        test.startTest();
        update leads;
        test.stopTest();
        
        for(Lead l : leads){
            l.CC_Call_Priority__c = '4-N/A';
        }
        update leads;
        set<String> countryLeadSet = new set<string>();
        countryLeadSet.add('United States');
        countryLeadSet.add('India');
        LeadTriggerUtil.callPriorityNA(leads, countryLeadSet);
       // }
    }
}