objects/CC_Assignment_Ruleset__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Center</label>
        <referenceTo>CC_Call_Center_Country_Assignment__c</referenceTo>
        <relationshipLabel>CC Assignment Rulesets</relationshipLabel>
        <relationshipName>CC_Assignment_Rulesets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <label>CC Assignment Ruleset</label>
    <nameField>
        <label>CC Assignment Ruleset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Assignment Rulesets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CC_Call_Center_Country_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                    <default>true</default>
                    <label>AFGHANISTAN</label>
                </value>
                <value>
                    <fullName>ALAND ISLANDS</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
                <value>
                    <fullName>UNITED STATES</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CC Call Center Country Assignment</label>
    <nameField>
        <label>CC Call Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Call Center Country Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/NGCC_One_default_Ruleset_per_CC_Test.cls
@istest
public class NGCC_One_default_Ruleset_per_CC_Test 
{
    public static testmethod void testmeth()
    {
        // create a record in CC_Assignment_Ruleset__c with the field isDefault__c == true ,Contact_Center__r.name,Contact_Center__c 
    //CC_Assignment_Ruleset__c c1 = new CC_Assignment_Ruleset__c();
    //c1 =[select id,Contact_Center__c from CC_Assignment_Ruleset__c where Contact_Center__c!=NULL ];
    CC_Call_Center_Country_Assignment__c c= new CC_Call_Center_Country_Assignment__c();
    c.name = 'Concentrix-Latam';
    c.Country__c = 'UNITED STATES';
    insert c;
    
    //call center 2 insert
    CC_Call_Center_Country_Assignment__c c1= new CC_Call_Center_Country_Assignment__c();
    c.name = 'Concentrix-Latamsf';
    c.Country__c = 'UNITED STATES';
    insert c1;
   
    CC_Assignment_Ruleset__c cc = new CC_Assignment_Ruleset__c ();
    cc.name ='Concentrix-Latam';
    cc.Contact_Center__c = c.Id;
    cc.isDefault__c  = true;
    
    insert cc;
    cc.isDefault__c  = true;
    update cc;
    
    CC_Assignment_Ruleset__c cc1 = new CC_Assignment_Ruleset__c ();
    cc1.name ='Concentrix-Latam';
    cc1.Contact_Center__c = c.Id;
    cc1.isDefault__c  = false;
    
    insert cc1;
    cc1.isDefault__c  = false;
    update cc1;
        
    }
}