objects/CC_Call_Script_Q_A__c.object
<CustomObject>
    <fields>
        <fullName>Call_Script__c</fullName>
        <description>NGCC Phase1: Reference to the Call Script to the Call Script Q&amp;A is associated.</description>
        <inlineHelpText>Call Script Reference for the associated Call Script Q&amp;A</inlineHelpText>
        <label>CC Call Script</label>
        <referenceTo>CC_Call_Script__c</referenceTo>
        <relationshipLabel>CC Call Scripts Q/A</relationshipLabel>
        <relationshipName>CC_Call_Scripts_Q_A</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <description>NGCC Phase1: All Call Script will have list of questionnaire which will be presented to users. Call Script Q&amp;A will be the replica of CC master Question/Answer Bank and customizable at this Call Script Q&amp;A level.</description>
    <label>CC Call Script Q/A</label>
    <nameField>
        <label>CC Call Script Q/A Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Call Scripts Q/A</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CC_Response__c.object
<CustomObject>
    <fields>
        <fullName>Call_Script__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>NGCC Phase1:Call Script Reference for the associated Call Script Q and A</description>
        <label>CC Call Script</label>
        <referenceTo>CC_Call_Script__c</referenceTo>
        <relationshipLabel>CC Responses</relationshipLabel>
        <relationshipName>CC_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>NGCC Phase-1: Each customer response will be captured in CC Response object and this defines response detail including the customer disposition values.</description>
    <label>CC Response</label>
    <nameField>
        <label>CC Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Theatre__c</fullName>
        <inlineHelpText>Please contact GSTS Support to Edit this field</inlineHelpText>
        <label>Theater</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Americas-Canada</fullName>
                </value>
                <value>
                    <fullName>Americas-Global Enterprise Segment</fullName>
                </value>
                <value>
                    <fullName>Americas-LATAM</fullName>
                </value>
                <value>
                    <fullName>Americas-US Commercial</fullName>
                </value>
                <value>
                    <fullName>Americas-US Public Sector</fullName>
                </value>
                <value>
                    <fullName>APJC-APAC</fullName>
                </value>
                <value>
                    <fullName>APJC-Greater China</fullName>
                </value>
                <value>
                    <fullName>APJC-Japan</fullName>
                </value>
                <value>
                    <fullName>EMEAR</fullName>
                </value>
                <value>
                    <fullName>Global Service Provider</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/NGCC_CallScript_Previewer_Test.cls
@isTest(SeeAllData = true)
public class NGCC_CallScript_Previewer_Test {

    // Testing the overall save of Call Script with much validation
    public static testMethod void test_CallScript_Full_Launch_Test() {

        Profile p = [SELECT Id FROM Profile WHERE Name Like '%NGCC%'
            Limit 1
        ];
        UserRole r = [SELECT Id FROM UserRole WHERE Name Like '%Site Manager Alea (Canada)%'
            Limit 1
        ];
        UserRole rSDR = [SELECT Id FROM UserRole WHERE Name Like '%SDR Alea (Canada)%'
            Limit 1
        ];

        User uSMgr = new User(Alias = 'newUser', Email = 'newuserSM@cisco.com.qtr',
            EmailEncodingKey = 'UTF-8', LastName = 'Testing', LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US', ProfileId = p.Id, UserRoleId = r.id,
            TimeZoneSidKey = 'America/Los_Angeles', UserName = 'newuserSM@testorg.com', Theatre__c = 'EMEAR');
        insert uSMgr;
        
        PermissionSet ps = [SELECT Id from PermissionSet where Name like '%NGCC_Call_Script_Super_User%'];
        PermissionSetAssignment psAssignment = new PermissionSetAssignment();
        psAssignment.AssigneeId = uSMgr.Id;
        psAssignment.PermissionSetId = ps.Id;
        insert psAssignment;

        System.runAs(uSMgr) {

            List < CC_Call_Script_Q_A__c > ccCallScriptQA = NGCC_CallScript_Data_Test.testCall_Script_QA();

            Test.startTest();
            CC_Response__c ccRes = new CC_Response__c();
                Test.setCurrentPageReference(New PageReference('Page.NGCC_CallScript_Preview_Mgmt'));
                System.currentPageReference().getParameters().put('CallScript', ccCallScriptQA[0].Call_Script__c);
                System.currentPageReference().getParameters().put('Theater', 'Americas');
                
                ApexPages.Standardcontroller stdCtlCallScriptPreviewer = New ApexPages.StandardController(ccRes);
                NGCC_CallScript_Preview_Mgmt_CTE ccCallScriptPreviewer = new NGCC_CallScript_Preview_Mgmt_CTE(stdCtlCallScriptPreviewer);
                ccCallScriptPreviewer.validateCallScript();   
                PageReference pageRef  = ccCallScriptPreviewer.launchCallScript();  
                //System.assertEquals('/apex/NGCC_CallScript_Preview',pageRef.getUrl());
                 
                 String urlNewPage = pageRef.getUrl();
                 urlNewPage.substring(urlNewPage.indexOf('?')+1);
                 map<string,String> mapQueryString = new map<string,string>();
                 List<String> lstString = urlNewPage.split('&');
                 for(String l:lstString){
                     List<string> lstPar = l.split('=');
                     mapQueryString.put(lstPar[0],lstPar[1]);
                 }
                 
                 Test.setCurrentPageReference(New PageReference('Page.NGCC_CallScript_Preview'));
            System.currentPageReference().getParameters().put('preview', 'yes');
            System.currentPageReference().getParameters().put('ResponseId', mapQueryString.get('ResponseId'));
            System.currentPageReference().getParameters().put('lang', 'en_US');
            System.currentPageReference().getParameters().put('retURL',  mapQueryString.get('retURL'));
            Lead leadCS = new Lead();
            
            ApexPages.Standardcontroller stdCtlCallScript = New ApexPages.StandardController(leadCS);
            NGCC_CallScript_CTE ccCallScript = new NGCC_CallScript_CTE(stdCtlCallScript);
            ccCallScript.getCreateDynamicComponent();
            ccCallScript.cmdSubmitCallScript();
            
            //Stop Testing
            Test.stopTest();
        }
    }    
}