objects/CC_Call_Script__c.object
<CustomObject>
    <fields>
        <fullName>Theater__c</fullName>
        <description>NGCC Phase1: Call Script Theater where the Call Script will be Used</description>
        <inlineHelpText>Call Script Theater where the Call Script will be Used</inlineHelpText>
        <label>Theater</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>APJ</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
                <value>
                    <fullName>EMEAR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>NGCC Phase1: Call Script master object which defines call scripts and its current status. Call Script can be edited only if the call script is in draft or inactive.</description>
    <label>CC Call Script</label>
    <nameField>
        <label>CC Call Script Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Call Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CC_Call_Script_Q_A__c.object
<CustomObject>
    <fields>
        <fullName>Answer_Options__c</fullName>
        <description>NGCC Phase1: Stores SFDC Ids of Answer Options associated Question and should only be updated ETL or Through inline UI</description>
        <inlineHelpText>Do Not Edit. This should be edited.</inlineHelpText>
        <label>Answer Options</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CC_Master_Question_Bank__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>NGCC Phase1: Reference to Master Question Answer Bank.Will be used for provide translation support</description>
        <inlineHelpText>Master Question Record Reference used in Call Script Q&amp;A</inlineHelpText>
        <label>CC Master Question Bank</label>
        <referenceTo>CC_Master_Question_Answer_Bank__c</referenceTo>
        <relationshipLabel>CC Call Scripts Q/A</relationshipLabel>
        <relationshipName>CC_Call_Scripts_Q_A</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Call_Script__c</fullName>
        <description>NGCC Phase1: Reference to the Call Script to the Call Script Q&amp;A is associated.</description>
        <inlineHelpText>Call Script Reference for the associated Call Script Q&amp;A</inlineHelpText>
        <label>CC Call Script</label>
        <referenceTo>CC_Call_Script__c</referenceTo>
        <relationshipLabel>CC Call Scripts Q/A</relationshipLabel>
        <relationshipName>CC_Call_Scripts_Q_A</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <description>NGCC Phase1: Question Type for the Question. Define how Question will be Presented in Call Script</description>
        <inlineHelpText>Question Type how the Question will be presented in Call Script</inlineHelpText>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Long Text</fullName>
                </value>
                <value>
                    <fullName>Radio</fullName>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
                <value>
                    <fullName>MultiSelect</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>DateTime</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Country</fullName>
                </value>
                <value>
                    <fullName>Route To Partner</fullName>
                </value>
                <value>
                    <fullName>Route To AM</fullName>
                </value>
                <value>
                    <fullName>Route To PSR</fullName>
                </value>
                <value>
                    <fullName>Preferred Partner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>NGCC Phase1: All Call Script will have list of questionnaire which will be presented to users. Call Script Q&amp;A will be the replica of CC master Question/Answer Bank and customizable at this Call Script Q&amp;A level.</description>
    <label>CC Call Script Q/A</label>
    <nameField>
        <label>CC Call Script Q/A Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Call Scripts Q/A</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CC_Master_Question_Answer_Bank__c.object
<CustomObject>
    <fields>
        <fullName>Answer_Text__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>NGCC Phase1: Answer Text associated MODS Answer Code</description>
        <inlineHelpText>Answer Text associated to MODS Answer Code</inlineHelpText>
        <label>Answer Text</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <description>NGCC Phase1: Question Type definition used for presenting in Call Script.</description>
        <inlineHelpText>Define type of input the question can take</inlineHelpText>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Long Text</fullName>
                </value>
                <value>
                    <fullName>Radio</fullName>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
                <value>
                    <fullName>MultiSelect</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>DateTime</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Country</fullName>
                </value>
                <value>
                    <fullName>Route To Partner</fullName>
                </value>
                <value>
                    <fullName>Route To AM</fullName>
                </value>
                <value>
                    <fullName>Route To PSR</fullName>
                </value>
                <value>
                    <fullName>Preferred Partner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>NGCC Phase-1: Master Question /Answer Bank are the integrated object with MODS Q&amp;A library and all translations are controlled reference master question and answers.</description>
    <label>CC Master Question/Answer Bank</label>
    <nameField>
        <label>CC Master Question Answer Bank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Master Question/Answer Banks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CC_Question_Answer_Translations__c.object
<CustomObject>
    <fields>
        <fullName>Answer_Text__c</fullName>
        <description>NGCC Phase1:Direct reference of Answer Text in case Answer Translation</description>
        <formula>CC_Master_Question_Answer_Bank__r.Answer_Text__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Direct reference of Answer Text in case Answer Translation</inlineHelpText>
        <label>Answer Text</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Master_Question_Answer_Bank__c</fullName>
        <description>NGCC Phase1:Reference to the master record for the translation is stored</description>
        <inlineHelpText>Reference to the master record for the translation is stored</inlineHelpText>
        <label>CC Master Question Answer Bank</label>
        <referenceTo>CC_Master_Question_Answer_Bank__c</referenceTo>
        <relationshipLabel>CC Question/Answer Translations</relationshipLabel>
        <relationshipName>CC_Question_Answer_Translations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Language_Code__c</fullName>
        <description>NGCC Phase1:System Generated Language Code based on Translated Language</description>
        <externalId>true</externalId>
        <inlineHelpText>System Generated Language Code based on Translated Language</inlineHelpText>
        <label>Language Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>NGCC Phase1:Define language for the question or answer</description>
        <inlineHelpText>Define language for the question or answer</inlineHelpText>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Danish</fullName>
                </value>
                <value>
                    <fullName>Dutch</fullName>
                </value>
                <value>
                    <fullName>English</fullName>
                    <default>true</default>
                    <label>English</label>
                </value>
                <value>
                    <fullName>Finnish</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Portuguese (Brazil)</fullName>
                </value>
                <value>
                    <fullName>Russian</fullName>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
                <value>
                    <fullName>Swedish</fullName>
                </value>
                <value>
                    <fullName>Thai</fullName>
                </value>
                <value>
                    <fullName>Arabic</fullName>
                </value>
                <value>
                    <fullName>Czech</fullName>
                </value>
                <value>
                    <fullName>Greek</fullName>
                </value>
                <value>
                    <fullName>Hungarian</fullName>
                </value>
                <value>
                    <fullName>Polish</fullName>
                </value>
                <value>
                    <fullName>Turkish</fullName>
                </value>
                <value>
                    <fullName>Chinese Simplified</fullName>
                </value>
                <value>
                    <fullName>Vietnamese</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Translated_Value__c</fullName>
        <description>NGCC Phase1:Translated value for Questions or Answers</description>
        <inlineHelpText>Translated value for Questions or Answers</inlineHelpText>
        <label>Translated Value</label>
        <length>400</length>
        <type>LongTextArea</type>
    </fields>
    <description>NGCC Phase-1: Each question and answer may have translation in specific languages and these translations are used to provide agent to launch call script in specific language</description>
    <label>CC Question/Answer Translations</label>
    <nameField>
        <displayFormat>QA_T-{000000}</displayFormat>
        <label>CC Question/Answer Translations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Question/Answer Translations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/NGCC_Flow_CallScript_Controller.cls
/***************************************************************************************************
Name    : NGCC_Flow_CallScript_Controller
Author  : Ghattamaneni Chaithanya
Purpose : This class is controller for NGCC_Flow_CallScript Component, it is responsible for get the values from Callscript
Date	: 07-Apr-2019

Modification History: 

*****************************************************************************************************/

public class NGCC_Flow_CallScript_Controller {
    @AuraEnabled
    public static Map<String, String> getCallScriptQA(string QuestionCode,string Lang,string CallScriptName,string Info){
        Map<String, String> options = new Map<String, String>();
        Set<string> setAnsId = new Set<string>();
        List<CC_Call_Script__c> callScript = [select id,Theater__c from CC_Call_Script__c where Name = :CallScriptName limit 1];          
        List<CC_Call_Script_Q_A__c> CCQ = [select id, Name,CC_Master_Question_Bank__c,Question_Type__c,CC_Master_Question_Bank__r.name,Call_Script__c,Answer_Options__c 
                                           from CC_Call_Script_Q_A__c where Call_Script__c =:callScript[0].id and Name=:QuestionCode limit 1];
        
        List<CC_Question_Answer_Translations__c> CCQAT = new  List<CC_Question_Answer_Translations__c>();
        CCQAT =  [select id, Translated_Value__c,CC_Master_Question_Answer_Bank__c,Language_Code__c,Language__c 
                  from CC_Question_Answer_Translations__c where CC_Master_Question_Answer_Bank__c=:CCQ[0].CC_Master_Question_Bank__c and Language_Code__c=:Lang limit 1];
        if(CCQAT.isEmpty()){
            CCQAT =  [select id, Translated_Value__c,CC_Master_Question_Answer_Bank__c,Language_Code__c,Language__c 
                      from CC_Question_Answer_Translations__c where CC_Master_Question_Answer_Bank__c=:CCQ[0].CC_Master_Question_Bank__c and Language_Code__c='en_US' limit 1];
        }
        options.put(QuestionCode,CCQAT[0].Translated_Value__c);
        if(CCQ[0].Question_Type__c == 'Picklist' || CCQ[0].Question_Type__c=='Radio'){
            List <String> strNewValue;
            if(CCQ[0].Answer_Options__c != null){
                strNewValue = new List <String>(CCQ[0].Answer_Options__c.split(','));
            }
            for (String optionName: strNewValue) {
                setAnsId.add(optionName.subString(optionName.indexOf(':')+1,optionName.length()));
            }
            if(Info != 'PS_Lead_TimeFrame' &&  Info != 'PS_Lead_ProjectBudget'){
                    for(CC_Question_Answer_Translations__c qat : [Select Id, Answer_Text__c,Translated_Value__c,CC_Master_Question_Answer_Bank__r.Name,CC_Master_Question_Answer_Bank__c from CC_Question_Answer_Translations__c 
                                                              where CC_Master_Question_Answer_Bank__c IN: setAnsId AND Language_Code__c =: CCQAT[0].Language_Code__c order by Answer_Text__c]){
                         options.put(qat.CC_Master_Question_Answer_Bank__r.Name,qat.Translated_Value__c);
                         setAnsId.remove(qat.CC_Master_Question_Answer_Bank__c);
                   }
            }            
            if(!setAnsId.isEmpty()){
                for(CC_Question_Answer_Translations__c qat : [Select Id, Answer_Text__c,Translated_Value__c,CC_Master_Question_Answer_Bank__r.Name,CC_Master_Question_Answer_Bank__c from CC_Question_Answer_Translations__c 
                                                              where CC_Master_Question_Answer_Bank__c IN: setAnsId AND Language_Code__c ='en_US' order by Answer_Text__c]){
                     options.put(qat.CC_Master_Question_Answer_Bank__r.Name,qat.Translated_Value__c);
                     setAnsId.remove(qat.CC_Master_Question_Answer_Bank__c);
                }
            }
        }
        return options;
    }
}