objects/CC_Master_Question_Answer_Bank__c.object
<CustomObject>
    <fields>
        <fullName>MODS_Question_Answer_Code__c</fullName>
        <description>NGCC Phase1: Define MODS Question and Answers assocaited to Question or Answer</description>
        <externalId>true</externalId>
        <inlineHelpText>Define MODS Question and Answers assocaited to Question or Answer</inlineHelpText>
        <label>MODS Question/Answer Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <description>NGCC Phase-1: Master Question /Answer Bank are the integrated object with MODS Q&amp;A library and all translations are controlled reference master question and answers.</description>
    <label>CC Master Question/Answer Bank</label>
    <nameField>
        <label>CC Master Question Answer Bank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Master Question/Answer Banks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CC_Response_Detail__c.object
<CustomObject>
    <fields>
        <fullName>CC_Master_Question_Answer_Bank__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>NGCC Phase1:Reference to the master question and answer bank associated to call script Q and A</description>
        <label>CC Master Question/Answer Bank</label>
        <referenceTo>CC_Master_Question_Answer_Bank__c</referenceTo>
        <relationshipLabel>CC Response Detail (CC Master Question/Answer Bank)</relationshipLabel>
        <relationshipName>CC_Response_Detail1</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>NGCC Phase-1: Customer response which captured during the call script will be stored in Response Detail Object.</description>
    <label>CC Response Detail</label>
    <nameField>
        <label>CC Response Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Response Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <description>Lead Address Line 1</description>
        <label>Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_2__c</fullName>
        <description>Lead Address Line 2</description>
        <label>Address Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_3__c</fullName>
        <description>NGCC Phase1:Prospect/Lead current Address Line 3</description>
        <label>Address Line 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Call_Permission__c</fullName>
        <description>NGCC Phase1:Permission to call for marketing offers/promotion</description>
        <label>Call Permission</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_Department__c</fullName>
        <description>Department of the contact</description>
        <label>Contact Department</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomCity__c</fullName>
        <description>Lead Address City</description>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomCountry__c</fullName>
        <description>Lead Address Country</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALAND ISLANDS</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BONAIRE, SINT EUSTATIUS AND SABA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CustomState__c</fullName>
        <description>Lead Address State/Province</description>
        <label>State/Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomZip__c</fullName>
        <description>Lead Address Zip/Postal Code</description>
        <label>Zip/Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Main_Technology__c</fullName>
        <description>Main Product the customer interested.</description>
        <label>Main Technology</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Preferred_Language__c</fullName>
        <description>NGCC Phase1:Preferred language of the customer</description>
        <label>Preferred Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Danish: da</fullName>
                </value>
                <value>
                    <fullName>Dutch: nl_NL</fullName>
                </value>
                <value>
                    <fullName>English: en_US</fullName>
                </value>
                <value>
                    <fullName>Finnish: fi</fullName>
                </value>
                <value>
                    <fullName>French: fr</fullName>
                </value>
                <value>
                    <fullName>German: de</fullName>
                </value>
                <value>
                    <fullName>Italian: it</fullName>
                </value>
                <value>
                    <fullName>Japanese: ja</fullName>
                </value>
                <value>
                    <fullName>Korean: ko</fullName>
                </value>
                <value>
                    <fullName>Portuguese (Brazil): pt_BR</fullName>
                </value>
                <value>
                    <fullName>Russian: ru</fullName>
                </value>
                <value>
                    <fullName>Spanish: es</fullName>
                </value>
                <value>
                    <fullName>Swedish: sv</fullName>
                </value>
                <value>
                    <fullName>Thai: th</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProductAmount__c</fullName>
        <description>Indicates the "Product Amount" of Partner Sales Lead</description>
        <label>Estimated Product Amount</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project_Flag__c</fullName>
        <description>NGCC Phase1:Flag to indicate whether customer has any project</description>
        <label>Project Flag</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>QABudget__c</fullName>
        <description>Budget the customer has indicated for the project.
LTLM integrated field</description>
        <label>Project Budget</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>$0 - $999</fullName>
                </value>
                <value>
                    <fullName>$1000 - $4999</fullName>
                </value>
                <value>
                    <fullName>$5000 - $14,999</fullName>
                </value>
                <value>
                    <fullName>$15,000 - $24,999</fullName>
                </value>
                <value>
                    <fullName>$25,000 - $49,999</fullName>
                </value>
                <value>
                    <fullName>$50,000 - $99,999</fullName>
                </value>
                <value>
                    <fullName>$100,000+</fullName>
                </value>
                <value>
                    <fullName>No budget available</fullName>
                </value>
                <value>
                    <fullName>Don't know / Not responsible</fullName>
                </value>
                <value>
                    <fullName>Budget amount not fixed</fullName>
                </value>
                <value>
                    <fullName>Did not respond</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>QAPartner__c</fullName>
        <description>Name of the preferred partner.
LTLM integrated field.</description>
        <label>Preferred Partner Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QATimeFrame__c</fullName>
        <description>Project time frame
LTLM integrated field</description>
        <label>Time Frame</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Now - 3 Months</fullName>
                </value>
                <value>
                    <fullName>4 - 6 Months</fullName>
                </value>
                <value>
                    <fullName>7 - 12 Months</fullName>
                </value>
                <value>
                    <fullName>Over 12 Months</fullName>
                </value>
                <value>
                    <fullName>No Plans To Purchase</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ServicesAmount__c</fullName>
        <description>Indicates the "Services Amount" of Partner Sales Lead</description>
        <label>Estimated Service Amount</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ObjectRecordTypeIds__c.object
<CustomObject>
    <fields>
        <fullName>Marketing_Lead_RecordType__c</fullName>
        <description>This is to store marketing_Lead recordtype</description>
        <label>Marketing Lead RecordType</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is used to store the record type ids of account and contact objects.</description>
    <label>Object Record Type Ids</label>
</CustomObject>

classes/NGCC_Update_Lead_Attributes_Test.cls
/* 
 * NGCC_Update_Lead_Attributes_Test is a test class that tests the NGCC_Update_Lead_Attributes class
 * @author: Daniel Pisciottano
 * @created date: March 28, 2014
*/ 
@isTest(SeeAllData=true) 
private class NGCC_Update_Lead_Attributes_Test {
    private static String leadRecordTypeId = ObjectRecordTypeIds__c.getInstance().Marketing_Lead_RecordType__c;
    private static Lead testLead = new Lead();
    private static CC_Response__c testResponse = new CC_Response__c();
    private static CC_Response_Detail__c testResponseDetail1 = new CC_Response_Detail__c();
    private static CC_Response_Detail__c testResponseDetail2 = new CC_Response_Detail__c();
    private static CC_Response_Detail__c testResponseDetail3 = new CC_Response_Detail__c();
    private static CC_Response_Detail__c testResponseDetail4 = new CC_Response_Detail__c();
    private static CC_Response_Detail__c testResponseDetail5 = new CC_Response_Detail__c();
    private static CC_Response_Detail__c testResponseDetail6 = new CC_Response_Detail__c();
    private static List<CC_Response_Detail__c> testResponseDetailList = new List<CC_Response_Detail__c>();
    private static CC_Master_Question_Answer_Bank__c testQABank1 = new CC_Master_Question_Answer_Bank__c();
    private static CC_Master_Question_Answer_Bank__c testQABank2 = new CC_Master_Question_Answer_Bank__c();
    private static CC_Master_Question_Answer_Bank__c testQABank3 = new CC_Master_Question_Answer_Bank__c();
    private static CC_Master_Question_Answer_Bank__c testQABank4 = new CC_Master_Question_Answer_Bank__c();
    private static CC_Master_Question_Answer_Bank__c testQABank5 = new CC_Master_Question_Answer_Bank__c();
    private static CC_Master_Question_Answer_Bank__c testQABank6 = new CC_Master_Question_Answer_Bank__c();
    private static List<CC_Master_Question_Answer_Bank__c> testQABankList = new List<CC_Master_Question_Answer_Bank__c>();
    
    /* Method that creates a test Lead object */
    static void initializeLead(){
        testLead.RecordTypeId = leadRecordTypeId;
        testLead.FirstName = 'John';
        testLead.LastName = 'Doe';
        testLead.Title = 'Engineer';
        testLead.Contact_Department__c = 'Engineering';
        testLead.Phone = '(123) 123-4567';
        testLead.Call_Permission__c = 'Yes';
        testLead.Email = 'test@test.com';
        testLead.Preferred_Language__c = 'English: en_US';
        testLead.Company = 'Dummy Company';
        testLead.Address_Line_1__c = '123 Main Street';
        testLead.Address_Line_2__c = 'Suite 123';
        testLead.Address_Line_3__c = '';
        testLead.CustomCity__c = 'Some City';
        testLead.CustomState__c = 'Some State';
        testLead.CustomCountry__c = 'United States';
        testLead.CustomZip__c = '12345';
        testLead.Project_Flag__c = 'Yes';
        testLead.QATimeFrame__c = 'Unknown';
        testLead.QABudget__c = 'Budget amount not fixed';
        testLead.Main_Technology__c = 'Computers';
        testLead.QAPartner__c = 'Tech Company #2';
        testLead.ProductAmount__c = 10000;
        testLead.ServicesAmount__c = 11;

        INSERT testLead;
    }
    static void initializeQABank(){
        testQABank1.MODS_Question_Answer_Code__c= 'First_Name_FF_V1';
        testQABank1.Name = 'First_Name_FF_V1';
        testQABankList.add(testQABank1);

        testQABank2.MODS_Question_Answer_Code__c = 'Last_Name_FF_V1';
        testQABank2.Name = 'Last_Name_FF_V1';
        testQABankList.add(testQABank2);

        testQABank3.MODS_Question_Answer_Code__c = 'Job_Title_FF_V1';
        testQABank3.Name = 'Job_Title_FF_V1';
        testQABankList.add(testQABank3);

        testQABank4.MODS_Question_Answer_Code__c = 'Contact_Site_City_FF_V1';
        testQABank4.Name = 'Contact_Site_City_FF_V1';
        testQABankList.add(testQABank4);
        
        testQABank5.MODS_Question_Answer_Code__c = 'ESTIMATED_PRODUCT_VALUE_SFDC';
        testQABank5.Name = 'ESTIMATED_PRODUCT_VALUE_SFDC';
        testQABank5.Question_Type__c ='Number';
        testQABankList.add(testQABank5);
        
        testQABank6.MODS_Question_Answer_Code__c = 'APPOINTMENT_DATE_TIME_SFDC';
        testQABank6.Name = 'APPOINTMENT_DATE_TIME_SFDC';
        testQABank6.Question_Type__c ='DateTime';
        testQABankList.add(testQABank6);
        
        INSERT testQABankList;
    }

    /* Method initializes response object and corresponding detail objects */
    static void initializeResponse(){
        testResponse.Lead__c = testLead.Id;
        testResponse.Status__c = 'Qualified Lead';
        INSERT testResponse;

        testResponseDetailList.clear();
        testResponseDetail1.Response_Id__c = testResponse.Id;
        testResponseDetail1.CC_Master_Question_Answer_Bank__c = testQABank1.Id;
        testResponseDetail1.Customer_Response_Detail__c = 'Joe';
        testResponseDetailList.add(testResponseDetail1);
        
        testResponseDetail2.Response_Id__c = testResponse.Id;
        testResponseDetail2.CC_Master_Question_Answer_Bank__c = testQABank2.Id;
        testResponseDetail2.Customer_Response_Detail__c = 'Shmoe';
        testResponseDetailList.add(testResponseDetail2);
        
        testResponseDetail3.Response_Id__c = testResponse.Id;
        testResponseDetail3.CC_Master_Question_Answer_Bank__c = testQABank3.Id;
        testResponseDetail3.Customer_Response_Detail__c = 'Engineer Lead';
        testResponseDetailList.add(testResponseDetail3);
        
        testResponseDetail4.Response_Id__c = testResponse.Id;
        testResponseDetail4.CC_Master_Question_Answer_Bank__c = testQABank4.Id;
        testResponseDetail4.Customer_Response_Detail__c = 'Another City';
        testResponseDetailList.add(testResponseDetail4);
        
        Double varEst = 9999;
        string varStrEst = string.valueof(varEst);
        testResponseDetail5.Response_Id__c = testResponse.Id;
        testResponseDetail5.CC_Master_Question_Answer_Bank__c = testQABank5.Id;
        testResponseDetail5.Customer_Response_Detail__c = varStrEst ;
        testResponseDetail5.Customer_Response__c = varStrEst;
        testResponseDetailList.add(testResponseDetail5);
        
        testResponseDetail6.Response_Id__c = testResponse.Id;
        testResponseDetail6.CC_Master_Question_Answer_Bank__c = testQABank6.Id;
        testResponseDetail6.Customer_Response_Detail__c = '9/25/2014 3:47 PM';
        testResponseDetailList.add(testResponseDetail6);
        
                
        INSERT testResponseDetailList;
    }
    
    /* Method that updates the testResponse object with a call status of nurture which should not allow for further processing */
    static void initializeDataStatusNurture(){
        testResponse.Call_Back_Time__c = System.now() + 200;
        testResponse.Status__c = 'Call Back';
        testResponse.Call_Status__c = 'Call Back Later';
        UPDATE testResponse;
    }
    
    /* Method that updates the testResponse object with a call status of call completed which should allow for further processing */
    static void initializeDataStatusContacted(){
        testResponse.Call_Status__c = 'Call Completed';
        testResponse.Call_Script_Completed__c = True;
        UPDATE testResponse;
    }
    
    /* Method that updates the testResponse object with a call status of call completed which should allow for further processing */
    static void initializeCSContacted(){
        testResponse.Call_Status__c = 'Call Completed';
        testResponse.Status__c = 'Qualified Lead';
        testResponse.Call_Script_Completed__c = True;
        UPDATE testResponse;
    }
    
    /* Main test method */
    static testMethod void UpdateLeadAttributesTest(){
        initializeQABank();
        initializeLead();
        initializeResponse();
        system.debug('testResponseDetailList'+testResponseDetailList);
        
        Test.startTest();
        
        System.Debug('Lead Initialized');
        Lead l = [SELECT Id, FirstName, LastName, Title, CustomCity__c FROM Lead WHERE Lead.Id = :testLead.Id];
        System.Debug(l);
        
        initializeDataStatusNurture();

        System.Debug('Lead After Call Status Nurture');

        l = [SELECT Id, FirstName, LastName, Title, CustomCity__c FROM Lead WHERE Lead.Id = :testLead.Id];
        System.Debug(l);
        
        initializeDataStatusContacted();
        
        System.Debug('Lead After Call Status Call Completed');
        
        Lead lt = [SELECT Id,ProductAmount__c,ServicesAmount__c FROM Lead WHERE Lead.Id = :testLead.Id];
        System.Debug(lt);
        
        testResponseDetailList[4].Customer_Response_Detail__c = NULL;
        testResponseDetailList[4].Customer_Response__c = NULL;
        testResponseDetailList[5].Customer_Response_Detail__c = NULL;
        testResponseDetailList[5].Customer_Response__c = NULL;
        update testResponseDetailList;
        initializeCSContacted();
        
        testResponseDetailList[0].Customer_Response_Detail__c = 'This is not valid scenario so that trigger to update the lead';
        testResponseDetailList[0].Customer_Response__c = 'This is not valid scenario so that trigger to update the lead';
        update testResponseDetailList;
        initializeCSContacted();
        
        Test.stopTest();
    }
    // added by gchaitha to increase code coverage
    public static testmethod void additionalmethod(){
        NGCC_Update_Lead_Attributes.flsUpdateGet(lead.Outcome__c);
    }     
}