objects/CC_Master_Question_Answer_Bank__c.object
<CustomObject>
    <fields>
        <fullName>Answer_Options_Id__c</fullName>
        <description>NGCC Phase1: Define the list of options available for the question as ID separated by Commas</description>
        <inlineHelpText>Do Not Edit</inlineHelpText>
        <label>Answer Options Id</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Local_to_SFDC__c</fullName>
        <defaultValue>false</defaultValue>
        <description>NGCC Phase1: Define if the Question is Local to SFDC and should be Integrated</description>
        <inlineHelpText>Define if the Question doesnt need to flow MODS</inlineHelpText>
        <label>Local to SFDC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question_Category__c</fullName>
        <description>NGCC Phase1: Define Default Question Category for Call Script</description>
        <inlineHelpText>Define Default Question Category/Tab for Call Script</inlineHelpText>
        <label>Question Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>1:Contact Information</fullName>
                </value>
                <value>
                    <fullName>2:Account Information</fullName>
                </value>
                <value>
                    <fullName>3:Lead Information</fullName>
                </value>
                <value>
                    <fullName>4:Additional Information</fullName>
                </value>
                <value>
                    <fullName>5:Campaign Information</fullName>
                </value>
                <value>
                    <fullName>6:Partner Information</fullName>
                </value>
                <value>
                    <fullName>7:Call Information</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Question_Text__c</fullName>
        <description>NGCC Phase1: Question Text integrated from MODS</description>
        <inlineHelpText>Question Text for the Associated Question</inlineHelpText>
        <label>Question Text</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <description>NGCC Phase1: Question Type definition used for presenting in Call Script.</description>
        <inlineHelpText>Define type of input the question can take</inlineHelpText>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Long Text</fullName>
                </value>
                <value>
                    <fullName>Radio</fullName>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
                <value>
                    <fullName>MultiSelect</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>DateTime</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Country</fullName>
                </value>
                <value>
                    <fullName>Route To Partner</fullName>
                </value>
                <value>
                    <fullName>Route To AM</fullName>
                </value>
                <value>
                    <fullName>Route To PSR</fullName>
                </value>
                <value>
                    <fullName>Preferred Partner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>NGCC Phase-1: Master Question /Answer Bank are the integrated object with MODS Q&amp;A library and all translations are controlled reference master question and answers.</description>
    <label>CC Master Question/Answer Bank</label>
    <nameField>
        <label>CC Master Question Answer Bank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Master Question/Answer Banks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/NGCC_CallScriptQuestionListview_Test.cls
@isTest
private class NGCC_CallScriptQuestionListview_Test

{
    public static testMethod void testMeth(){
    
    list<CC_Master_Question_Answer_Bank__c> lstcc = new list<CC_Master_Question_Answer_Bank__c>();
    CC_Master_Question_Answer_Bank__c cc = new CC_Master_Question_Answer_Bank__c();
    cc.Question_Text__c = 'Test';
    cc.Question_Type__c = 'Test1';
    cc.Local_to_SFDC__c = True;
    cc.Answer_Options_Id__c = 'Test3';
    cc.Question_Category__c = 'Test4';
    //cc.Call_Script__c = 'Test5';
    lstcc.add(cc);
    insert cc;
    
    CC_Master_Question_Answer_Bank__c ccm = new CC_Master_Question_Answer_Bank__c();
    ccm.Name = 'Test';
    ccm.Question_Text__c = 'Test1';
    ccm.Question_Type__c = 'Test2';
    ccm.Local_to_SFDC__c = true;
    ccm.Answer_Options_Id__c = 'Test4';
    ccm.Question_Category__c= 'Test5';
    lstcc.add(ccm);
    insert ccm;
    
    ApexPages.StandardSetController stdController = new ApexPages.StandardSetController(lstcc);  
    stdController.setSelected(lstcc);
    NGCC_CallScriptQuestionListview Ngcc = new NGCC_CallScriptQuestionListview(stdController);  
    Ngcc.SaveCallScript();
    Ngcc.getHasSelected();
    Ngcc.getHasMessages();
    
    }


}