objects/CC_Master_Question_Answer_Bank__c.object
<CustomObject>
    <fields>
        <fullName>Answer_Options_Id__c</fullName>
        <description>NGCC Phase1: Define the list of options available for the question as ID separated by Commas</description>
        <inlineHelpText>Do Not Edit</inlineHelpText>
        <label>Answer Options Id</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Answer_Text__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>NGCC Phase1: Answer Text associated MODS Answer Code</description>
        <inlineHelpText>Answer Text associated to MODS Answer Code</inlineHelpText>
        <label>Answer Text</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <description>NGCC Phase-1: Master Question /Answer Bank are the integrated object with MODS Q&amp;A library and all translations are controlled reference master question and answers.</description>
    <label>CC Master Question/Answer Bank</label>
    <nameField>
        <label>CC Master Question Answer Bank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Master Question/Answer Banks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Answer</fullName>
        <active>true</active>
        <label>Answer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Question</fullName>
        <active>true</active>
        <label>Question</label>
    </recordTypes>
</CustomObject>

objects/CC_Question_Answer_Translations__c.object
<CustomObject>
    <fields>
        <fullName>Answer_Text__c</fullName>
        <description>NGCC Phase1:Direct reference of Answer Text in case Answer Translation</description>
        <formula>CC_Master_Question_Answer_Bank__r.Answer_Text__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Direct reference of Answer Text in case Answer Translation</inlineHelpText>
        <label>Answer Text</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Master_Question_Answer_Bank__c</fullName>
        <description>NGCC Phase1:Reference to the master record for the translation is stored</description>
        <inlineHelpText>Reference to the master record for the translation is stored</inlineHelpText>
        <label>CC Master Question Answer Bank</label>
        <referenceTo>CC_Master_Question_Answer_Bank__c</referenceTo>
        <relationshipLabel>CC Question/Answer Translations</relationshipLabel>
        <relationshipName>CC_Question_Answer_Translations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Language_Code__c</fullName>
        <description>NGCC Phase1:System Generated Language Code based on Translated Language</description>
        <externalId>true</externalId>
        <inlineHelpText>System Generated Language Code based on Translated Language</inlineHelpText>
        <label>Language Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>NGCC Phase1:Define language for the question or answer</description>
        <inlineHelpText>Define language for the question or answer</inlineHelpText>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Danish</fullName>
                </value>
                <value>
                    <fullName>Dutch</fullName>
                </value>
                <value>
                    <fullName>English</fullName>
                    <default>true</default>
                    <label>English</label>
                </value>
                <value>
                    <fullName>Finnish</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Portuguese (Brazil)</fullName>
                </value>
                <value>
                    <fullName>Russian</fullName>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
                <value>
                    <fullName>Swedish</fullName>
                </value>
                <value>
                    <fullName>Thai</fullName>
                </value>
                <value>
                    <fullName>Arabic</fullName>
                </value>
                <value>
                    <fullName>Czech</fullName>
                </value>
                <value>
                    <fullName>Greek</fullName>
                </value>
                <value>
                    <fullName>Hungarian</fullName>
                </value>
                <value>
                    <fullName>Polish</fullName>
                </value>
                <value>
                    <fullName>Turkish</fullName>
                </value>
                <value>
                    <fullName>Chinese Simplified</fullName>
                </value>
                <value>
                    <fullName>Vietnamese</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Translated_Value__c</fullName>
        <description>NGCC Phase1:Translated value for Questions or Answers</description>
        <inlineHelpText>Translated value for Questions or Answers</inlineHelpText>
        <label>Translated Value</label>
        <length>400</length>
        <type>LongTextArea</type>
    </fields>
    <description>NGCC Phase-1: Each question and answer may have translation in specific languages and these translations are used to provide agent to launch call script in specific language</description>
    <label>CC Question/Answer Translations</label>
    <nameField>
        <displayFormat>QA_T-{000000}</displayFormat>
        <label>CC Question/Answer Translations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Question/Answer Translations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/NGCC_Q_A_Translation_Anwers_CTE.cls
/******************************************************************************************************************************************************
Name    : NGCC_Q_A_Translation_Anwers_CTE 
Author  : Mukesh Srivastava
Purpose : Controller to show all the available translated options for a particular question in the specified lanugage
Created Date: 4/18/2014
Modification History:                       
*********************************************************************************************************************************************************/

public class NGCC_Q_A_Translation_Anwers_CTE {
    
    Private CC_Question_Answer_Translations__c qaTrans;
    Public List<CC_Question_Answer_Translations__c> qansTrans {get;set;}
    Public List<CC_Master_Question_Answer_Bank__c> newQansTrans {get;set;}
    Public boolean bNewTranslation {get;set;}
    Public boolean bAvailableOption {get;set;}
    Set<Id> setAnsId = new Set<Id>();
    
    // SCAVA Helper Method
     public static Boolean flsGet(SObjectField field)
    {
        return field.getDescribe().isCreateable() ? true : false;
    }
    
    // SCAVA Helper Method to validate Update Access at field level
     public static Boolean flsUpdateGet(SObjectField field)
    {
        return field.getDescribe().isUpdateable() ? true : false;
    }
    
    /* Controller to get record of the particular question */
    Public NGCC_Q_A_Translation_Anwers_CTE(ApexPages.StandardController controller) {
        this.qaTrans =  [select id, CC_Master_Question_Answer_Bank__r.Answer_Options_Id__c,Language_Code__c,Language__c from CC_Question_Answer_Translations__c where id = :controller.getId() limit 1];
        getAnswerTrans();
    }   
        
    /* @ method: Getting the translation for the answer options associated to the Question
    //@ Sets the whether the options are available and whether we need translation for the option in the given language
    //@ Sets page error if the no options available for the particular question basically either its the answer detail or Text questions */
    Public void getAnswerTrans(){
        try
        {
            List < String > strNewValue = new List < String > (this.qaTrans.CC_Master_Question_Answer_Bank__r.Answer_Options_Id__c.split(','));
            
            bAvailableOption = true;
            
            for (String optionName: strNewValue) {
                setAnsId.add(Id.valueOf(optionName.subString(optionName.indexOf(':')+1,optionName.length())));
            }
            qansTrans= [Select Id, Answer_Text__c,Translated_Value__c from CC_Question_Answer_Translations__c 
                        where CC_Master_Question_Answer_Bank__c IN: setAnsId AND Language_Code__c =: qaTrans.Language_Code__c];
            if(qansTrans.isEmpty())
            {
                bNewTranslation = true;
            }
            else
            {
                bNewTranslation = false;
            }
            
        }catch(Exception e)
        {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO,'No other options available for this Question/Answer Bank Translation.'));
            bAvailableOption = false;
            bNewTranslation = false;
        }
    }
    
    /* @ method: To update the translation if the user has modified any of the translation or created new translation
    //@ return: null to refresh the page */
    public pageReference cmdUpdate(){
        try
        {
            Database.SaveResult[] updateQAAnswerTrans = Database.Update(qansTrans,false); 
        }catch(Exception e)
        {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO,'Unable to Update the Translaton.'));
        }
        return null;
    }    
    
    /* @ method: If the translation are not available for the options user can add translation in the particular language
    //@ Create all options translations to be translatable */
    public void cmdAddTranslation(){
        List<CC_Question_Answer_Translations__c > newLstQansTrans= new List<CC_Question_Answer_Translations__c>();
        try{
            for(CC_Master_Question_Answer_Bank__c  newQansObj : [Select Answer_Text__c,Id from CC_Master_Question_Answer_Bank__c where Id IN: setAnsId])
            {
                CC_Question_Answer_Translations__c newQansTrans = new CC_Question_Answer_Translations__c();
                /*newQansTrans.CC_Master_Question_Answer_Bank__c = newQansObj.Id;
                newQansTrans.Language_Code__c = qaTrans.Language_Code__c;
                newQansTrans.Language__c = qaTrans.Language__c;*/
                newQansTrans.CC_Master_Question_Answer_Bank__c = newQansObj.Id;
                //SCAVA
                if(flsGet(CC_Question_Answer_Translations__c.Language_Code__c)){
                newQansTrans.Language_Code__c = qaTrans.Language_Code__c;
                }
                if(flsGet(CC_Question_Answer_Translations__c.Language__c)){
                newQansTrans.Language__c = qaTrans.Language__c;
                }
                //SCAVA
                newLstQansTrans.add(newQansTrans);
            }
            Database.SaveResult[] insertNewQAAnswerTrans = Database.Insert(newLstQansTrans,false);  
        }catch(Exception e)
        {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO,'Unable to add the Translaton.'));
        }    
    }
}