objects/CC_Master_Question_Answer_Bank__c.object
<CustomObject>
    <description>NGCC Phase-1: Master Question /Answer Bank are the integrated object with MODS Q&amp;A library and all translations are controlled reference master question and answers.</description>
    <label>CC Master Question/Answer Bank</label>
    <nameField>
        <label>CC Master Question Answer Bank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Master Question/Answer Banks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Theater__c</fullName>
        <description>Theatre Name 
LTLM integrated field</description>
        <label>Theater</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/NGCC_Rule_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Countries__c</fullName>
        <label>Country</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Theater__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BRITISH INDIAN OCEAN TERRITORY</fullName>
                </value>
                <value>
                    <fullName>BRUNEI DARUSSALAM</fullName>
                </value>
                <value>
                    <fullName>CAMBODIA</fullName>
                </value>
                <value>
                    <fullName>CHRISTMAS ISLAND</fullName>
                </value>
                <value>
                    <fullName>COCOS (KEELING) ISLANDS</fullName>
                </value>
                <value>
                    <fullName>COOK ISLANDS</fullName>
                </value>
                <value>
                    <fullName>FIJI</fullName>
                </value>
                <value>
                    <fullName>FRENCH POLYNESIA</fullName>
                </value>
                <value>
                    <fullName>INDIA</fullName>
                </value>
                <value>
                    <fullName>INDONESIA</fullName>
                </value>
                <value>
                    <fullName>JAPAN</fullName>
                </value>
                <value>
                    <fullName>KIRIBATI</fullName>
                </value>
                <value>
                    <fullName>KOREA, REPUBLIC OF</fullName>
                </value>
                <value>
                    <fullName>KOREA,DEMOCRATIC PEOPLE'S REPUBLIC OF</fullName>
                </value>
                <value>
                    <fullName>LAO PEOPLE'S DEMOCRATIC REPUBLIC</fullName>
                </value>
                <value>
                    <fullName>MALAYSIA</fullName>
                </value>
                <value>
                    <fullName>MALDIVES</fullName>
                </value>
                <value>
                    <fullName>MARSHALL ISLANDS</fullName>
                </value>
                <value>
                    <fullName>MICRONESIA, FEDERATED STATES OF</fullName>
                </value>
                <value>
                    <fullName>MYANMAR</fullName>
                </value>
                <value>
                    <fullName>NAURU</fullName>
                </value>
                <value>
                    <fullName>NEPAL</fullName>
                </value>
                <value>
                    <fullName>NEW CALEDONIA</fullName>
                </value>
                <value>
                    <fullName>NEW ZEALAND</fullName>
                </value>
                <value>
                    <fullName>NIUE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_Attribute__c</fullName>
        <label>Lead Attribute API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MODS_Leads__c</fullName>
        <label>MODS / Leads</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MODS Q/A</fullName>
                </value>
                <value>
                    <fullName>Lead Attribute</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MODS_Q_A__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MODS Q/A</label>
        <referenceTo>CC_Master_Question_Answer_Bank__c</referenceTo>
        <relationshipName>NGCC_Rule_Assignments1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1-High</fullName>
                </value>
                <value>
                    <fullName>2-Medium</fullName>
                </value>
                <value>
                    <fullName>3-Low</fullName>
                </value>
                <value>
                    <fullName>4-N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rank__c</fullName>
        <label>Rank</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Theater__c</fullName>
        <label>Theater</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>APJ</fullName>
                </value>
                <value>
                    <fullName>EMEAR</fullName>
                </value>
                <value>
                    <fullName>Greater China</fullName>
                </value>
                <value>
                    <fullName>Americas</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>CC Lead Priority Rule</label>
    <nameField>
        <displayFormat>NGCC Rule-{000000}</displayFormat>
        <label>NGCC Rule Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Lead Priority Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>MODS</fullName>
        <active>false</active>
        <description>Choose "MODS" for MODS rules</description>
        <label>MODS</label>
    </recordTypes>
</CustomObject>

classes/NGCC_Rule_Assignment_Trg_Test.cls
@isTest
public with sharing class NGCC_Rule_Assignment_Trg_Test {
	static testMethod void SingleItemTest(){
		CC_Master_Question_Answer_Bank__c ccMaster = new CC_Master_Question_Answer_Bank__c(name='M');
        insert ccMaster;
        
        
		list<NGCC_Rule_Assignment__c> rules = new list<NGCC_Rule_Assignment__c>();
        rules.add(new NGCC_Rule_Assignment__c(MODS_Leads__c='Lead Attribute',Countries__c='UK;US',Lead_Attribute__c='lastName',Priority__c='1',Rank__c='1',Theater__c='APJXC',Value__c='m1,m', Active__c= true));
        rules.add(new NGCC_Rule_Assignment__c(MODS_Q_A__c=ccMaster.id,MODS_Leads__c='MODS Q/A',Countries__c='India;US',Priority__c='2',Rank__c='2',Theater__c='APJXC',Value__c='m1,m',Active__c= true));
        rules.add(new NGCC_Rule_Assignment__c(MODS_Q_A__c=ccMaster.id,MODS_Leads__c='MODS Q/A',Countries__c='India;US',Priority__c='2',Rank__c='2',Theater__c='APJXC',Value__c='m1,m',Active__c= false));
        rules.add(new NGCC_Rule_Assignment__c(MODS_Q_A__c=ccMaster.id,MODS_Leads__c='MODS Q/A',Countries__c='India;US',Priority__c='4-N/A',Rank__c='3',Theater__c='APJ',Value__c='m1,m', Active__c= true));
        rules.add(new NGCC_Rule_Assignment__c(MODS_Q_A__c=ccMaster.id,MODS_Leads__c='MODS Q/A',Countries__c='India;US',Priority__c='4-N/A',Rank__c='3',Theater__c='APJ',Value__c='m1,m', Active__c= true));
        insert rules;
        
        list<NGCC_Rule_Assignment__c> rules2 = new list<NGCC_Rule_Assignment__c>();
        rules2.add(new NGCC_Rule_Assignment__c(MODS_Leads__c='Lead Attribute',Countries__c='UK;US',Lead_Attribute__c='lastName',Priority__c='1',Rank__c='1',Theater__c='APJXC',Value__c='m1,m', Active__c= true));
        rules2.add(new NGCC_Rule_Assignment__c(MODS_Q_A__c=ccMaster.id,MODS_Leads__c='MODS Q/A',Countries__c='India;US',Priority__c='2',Rank__c='2',Theater__c='APJXC',Value__c='m1,m',Active__c= true));
        rules2.add(new NGCC_Rule_Assignment__c(MODS_Q_A__c=ccMaster.id,MODS_Leads__c='MODS Q/A',Countries__c='India;US',Priority__c='2',Rank__c='2',Theater__c='APJXC',Value__c='m1,m',Active__c= false));
        rules2.add(new NGCC_Rule_Assignment__c(MODS_Q_A__c=ccMaster.id,MODS_Leads__c='MODS Q/A',Countries__c='India;US',Priority__c='4-N/A',Rank__c='3',Theater__c='APJ',Value__c='m1,m', Active__c= true));
        rules2.add(new NGCC_Rule_Assignment__c(MODS_Q_A__c=ccMaster.id,MODS_Leads__c='MODS Q/A',Countries__c='India;US',Priority__c='4-N/A',Rank__c='3',Theater__c='APJ',Value__c='m1,m', Active__c= true));
        insert rules2;
        
        rules[0].Priority__c='2';
        update rules2;
        
        
        /*
        list<NGCC_Rule_Assignment__c> rules2 = new list<NGCC_Rule_Assignment__c>();
        rules2.add(new NGCC_Rule_Assignment__c(MODS_Leads__c='Lead Attribute',Countries__c='UK;US',Lead_Attribute__c='lastName',Priority__c='1',Rank__c='1',Theater__c='APJXC',Value__c='m1,m', Active__c= true));
        rules2.add(rules[0]);
        rules2.add(rules[2]);
        
        
        rules2[1].Priority__c='2';
        upsert rules2;
        */
	
	}
}