objects/CC_Response__c.object
<CustomObject>
    <fields>
        <fullName>AM_Email_Id__c</fullName>
        <label>AM Email Id</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Call_Status__c</fullName>
        <description>NGCC Phase1:Call Status of the response</description>
        <label>Call Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Call Completed</fullName>
                </value>
                <value>
                    <fullName>Call Back Later</fullName>
                </value>
                <value>
                    <fullName>Nuture</fullName>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
                <value>
                    <fullName>Invalid Call Completed</fullName>
                </value>
                <value>
                    <fullName>PE Cancelled/Completed</fullName>
                </value>
                <value>
                    <fullName>Max Attempts Reached</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>NGCC Phase1:Campaign for which the response was created</description>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>CC Responses</relationshipLabel>
        <relationshipName>CC_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>NGCC Phase1:Lead/Prospect assocaited to response</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>CC Responses</relationshipLabel>
        <relationshipName>CC_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>NGCC Phase1:Agent notes provided by Agent while saving the response</description>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Partner_Contact_Email_Id__c</fullName>
        <label>Partner Contact Email Id</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Response_Date_Time__c</fullName>
        <description>NGCC Phase1:Response date and time when the response was created</description>
        <label>Response Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Response_Type__c</fullName>
        <description>NGCC Phase1:Response type when the response was created</description>
        <label>Response Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inbound Call</fullName>
                </value>
                <value>
                    <fullName>Outbound Call</fullName>
                </value>
                <value>
                    <fullName>Inbound Chat</fullName>
                </value>
                <value>
                    <fullName>Web Inquiry</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_Event_Number__c</fullName>
        <description>NGCC Phase1:Source Event Number assocaite to the response default is SFDC ID</description>
        <label>Source Event Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>NGCC Phase1:Disposition status of the call/response</description>
        <label>Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Call Back</fullName>
                </value>
                <value>
                    <fullName>Max Attempts Reached</fullName>
                </value>
                <value>
                    <fullName>Cust Prefers a different buying method</fullName>
                </value>
                <value>
                    <fullName>Customer Dropped Off</fullName>
                </value>
                <value>
                    <fullName>Customer Service</fullName>
                </value>
                <value>
                    <fullName>Invalid Info</fullName>
                </value>
                <value>
                    <fullName>Lead Escalation</fullName>
                </value>
                <value>
                    <fullName>Nurture</fullName>
                </value>
                <value>
                    <fullName>Qualified Lead</fullName>
                </value>
                <value>
                    <fullName>Transfer out</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>NGCC Phase-1: Each customer response will be captured in CC Response object and this defines response detail including the customer disposition values.</description>
    <label>CC Response</label>
    <nameField>
        <label>CC Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>AM_Email_Id__c</fullName>
        <label>AM Email Id</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Call_Status__c</fullName>
        <description>NGCC Phase1:Call Status depending upon disposition value.  Can be only updated by system based on disposition.</description>
        <label>Call Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Call Back Later</fullName>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
                <value>
                    <fullName>Invalid Call Completed</fullName>
                </value>
                <value>
                    <fullName>Max Attempts Reached</fullName>
                </value>
                <value>
                    <fullName>Nurture</fullName>
                </value>
                <value>
                    <fullName>PE Cancelled/Completed</fullName>
                </value>
                <value>
                    <fullName>Call Completed</fullName>
                </value>
                <value>
                    <fullName>Requalification Required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Campaign_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>NGCC Phase1:Unica Campaign name</description>
        <label>Campaign Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Campaign.Eloqua_Campaign_Id__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CustomCountry__c</fullName>
        <description>Lead Address Country</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALAND ISLANDS</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BONAIRE, SINT EUSTATIUS AND SABA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner_Contact_Email__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used for Coding purpose,
used In Notify Partner by Email visual force page</description>
        <label>Partner Contact Email</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Route_to_AM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>NGCC Phase1:AM assigned to lead by Agent</description>
        <label>Route to AM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RouteAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Event_Number__c</fullName>
        <label>Source Event Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/NGCC_QA_and_Lead_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>Call_Status__c</fullName>
        <description>Corresponding Call Status for the Disposition value</description>
        <label>Call Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Mapping of MODS question code with Lead Attributes and various actions need to be performed after each response. This object also helps to define theater specific lead qualification and routing questions.</description>
    <label>NGCC QA and Lead Mapping</label>
</CustomObject>

classes/NGCC_CreateBulkResponseController.cls
/************************************************************************************************************************************
Name    : NGCC_CreateBulkResponseController
Author  : Ramzil Roxann
Purpose : Allow user to create responses for leads which are not valid for NGCC project through List view
Created Date: 2/25/2014
Modification History:  
                     Awnish added logic to populated source event number on the responses # PBI000000051342
*************************************************************************************************************************************/

public with sharing class NGCC_CreateBulkResponseController {

     // SCAVA Helper Method
     public static Boolean flsGet(SObjectField field)
    {
        return field.getDescribe().isCreateable() ? true : false;
    }
    
    // SCAVA Helper Method to validate Update Access at field level
     public static Boolean flsUpdateGet(SObjectField field)
    {
        return field.getDescribe().isUpdateable() ? true : false;
    }
    
    public Apexpages.StandardSetController controller {get;set;}
    public CC_Response__c response { get; set;}
    public string responsetype { get; set;}
    
    Set<Id> setleadId = new Set<Id>();
    List<Lead> lstleads = new List<Lead>();
    List<CC_Response__c> lstresponse = new List<CC_Response__c>();
    
    public NGCC_CreateBulkResponseController(ApexPages.StandardSetController stdcontroller) {
        this.controller = stdController; 
        response = new CC_Response__c();
        for(Lead l: (List<Lead>) controller.getSelected()){
            setleadId.add(l.id);                  
        }
        
        if(setleadId != null && !setleadId.isEmpty()){
            lstleads = [Select Id,Name,Route_to_AM__r.Email,Partner_Contact_Email__r.Email,Campaign_Name__c,
                        CustomCountry__c, source_event_number__c FROM Lead Where Id=:setleadId]; 
        }        
    }
    
    //@method: To create bulk response taking input from UI 
    public PageReference saveLeads() { 
        
        if(lstleads != null && !lstleads.isEmpty()){
            for(Lead leadobj : lstleads){  
                CC_Response__c respobj = new CC_Response__c();
                NGCC_QA_and_Lead_Mapping__c myCSStatus = NGCC_QA_and_Lead_Mapping__c.getValues(response.Status__c); 
                //SCAVA 
                if(flsGet(CC_Response__c.Lead__c)||flsUpdateGet(CC_Response__c.Lead__c)){
                respobj.Lead__c = leadobj.Id;
                }
                if(flsGet(CC_Response__c.Name)||flsUpdateGet(CC_Response__c.Name)){
                respobj.Name = leadobj.Name + System.now();
                }
                if(flsGet(CC_Response__c.AM_Email_Id__c)||flsUpdateGet(CC_Response__c.AM_Email_Id__c)){
                respobj.AM_Email_Id__c = leadobj.Route_to_AM__r.Email;
                }
                if(flsGet(CC_Response__c.Partner_Contact_Email_Id__c)||flsUpdateGet(CC_Response__c.Partner_Contact_Email_Id__c)){
                respobj.Partner_Contact_Email_Id__c = leadobj.Partner_Contact_Email__r.Email;
                }
                if(flsGet(CC_Response__c.Campaign__c)||flsUpdateGet(CC_Response__c.Campaign__c)){
                respobj.Campaign__c = leadobj.Campaign_Name__c;
                }
                if(flsGet(CC_Response__c.source_event_number__c)||flsUpdateGet(CC_Response__c.source_event_number__c)){
                respobj.source_event_number__c = leadobj.source_event_number__c; // Added by Awnish for Source Event Number Fix # PBI000000051342
                }
                if(flsGet(CC_Response__c.Status__c)||flsUpdateGet(CC_Response__c.Status__c)){
                respobj.Status__c = response.Status__c;
                }
                if(flsGet(CC_Response__c.Response_Type__c)||flsUpdateGet(CC_Response__c.Response_Type__c)){
                respobj.Response_Type__c = response.Response_Type__c;
                }
                if(flsGet(CC_Response__c.Notes__c)||flsUpdateGet(CC_Response__c.Notes__c)){
                respobj.Notes__c = response.Notes__c;
                }
                if(flsGet(CC_Response__c.Response_Date_Time__c)||flsUpdateGet(CC_Response__c.Response_Date_Time__c)){
                respobj.Response_Date_Time__c=System.now(); 
                }
                if(flsGet(CC_Response__c.Call_Status__c)||flsUpdateGet(CC_Response__c.Call_Status__c)){
                respobj.Call_Status__c = myCSStatus.Call_Status__c; 
                }//SCAVA
                lstresponse.add(respobj);
            }
        }
        
        if(lstresponse!= null && !lstresponse.isEmpty()){
            Database.insert(lstresponse,false);
        }
        
        return new PageReference('/00Q');        
    }
    
    /*@method: verify if any of the record is selected or not
      @returns true or false
    */
    public Boolean getHasSelected() {
        Boolean retval;
        if (controller.getSelected() == null || controller.getSelected().size() == 0) {
            ApexPages.Message errMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'Please select at least one Lead for creating CC Response');
            ApexPages.addMessage(errMsg);
            retval = false;
        } else {
            retval = true;
        }
        return retval;
    }
    
    /*@method: verify if any error occured
      @returns true or false
    */
    public Boolean getHasMessages() {
        Boolean retval;
        if (ApexPages.getMessages().size() == 0) {
            retval = false;
        } else {
            retval = true;
        }
        return retval;
    }
    
    /*@method: Provide back functionality to go back to List view
      @return pagereference back to list view
    */
    public PageReference CancelRecords(){
        return new PageReference('/00Q');
    }
}