objects/CC_Response__c.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>NGCC Phase1:Lead/Prospect assocaited to response</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>CC Responses</relationshipLabel>
        <relationshipName>CC_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>NGCC Phase1:Disposition status of the call/response</description>
        <label>Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Call Back</fullName>
                </value>
                <value>
                    <fullName>Max Attempts Reached</fullName>
                </value>
                <value>
                    <fullName>Cust Prefers a different buying method</fullName>
                </value>
                <value>
                    <fullName>Customer Dropped Off</fullName>
                </value>
                <value>
                    <fullName>Customer Service</fullName>
                </value>
                <value>
                    <fullName>Invalid Info</fullName>
                </value>
                <value>
                    <fullName>Lead Escalation</fullName>
                </value>
                <value>
                    <fullName>Nurture</fullName>
                </value>
                <value>
                    <fullName>Qualified Lead</fullName>
                </value>
                <value>
                    <fullName>Transfer out</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>NGCC Phase-1: Each customer response will be captured in CC Response object and this defines response detail including the customer disposition values.</description>
    <label>CC Response</label>
    <nameField>
        <label>CC Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <description>Lead Address Line 1</description>
        <label>Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_2__c</fullName>
        <description>Lead Address Line 2</description>
        <label>Address Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_3__c</fullName>
        <description>NGCC Phase1:Prospect/Lead current Address Line 3</description>
        <label>Address Line 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Call_Permission__c</fullName>
        <description>NGCC Phase1:Permission to call for marketing offers/promotion</description>
        <label>Call Permission</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_Department__c</fullName>
        <description>Department of the contact</description>
        <label>Contact Department</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomCity__c</fullName>
        <description>Lead Address City</description>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomCountry__c</fullName>
        <description>Lead Address Country</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALAND ISLANDS</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BONAIRE, SINT EUSTATIUS AND SABA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CustomState__c</fullName>
        <description>Lead Address State/Province</description>
        <label>State/Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomZip__c</fullName>
        <description>Lead Address Zip/Postal Code</description>
        <label>Zip/Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Main_Technology__c</fullName>
        <description>Main Product the customer interested.</description>
        <label>Main Technology</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Preferred_Language__c</fullName>
        <description>NGCC Phase1:Preferred language of the customer</description>
        <label>Preferred Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Danish: da</fullName>
                </value>
                <value>
                    <fullName>Dutch: nl_NL</fullName>
                </value>
                <value>
                    <fullName>English: en_US</fullName>
                </value>
                <value>
                    <fullName>Finnish: fi</fullName>
                </value>
                <value>
                    <fullName>French: fr</fullName>
                </value>
                <value>
                    <fullName>German: de</fullName>
                </value>
                <value>
                    <fullName>Italian: it</fullName>
                </value>
                <value>
                    <fullName>Japanese: ja</fullName>
                </value>
                <value>
                    <fullName>Korean: ko</fullName>
                </value>
                <value>
                    <fullName>Portuguese (Brazil): pt_BR</fullName>
                </value>
                <value>
                    <fullName>Russian: ru</fullName>
                </value>
                <value>
                    <fullName>Spanish: es</fullName>
                </value>
                <value>
                    <fullName>Swedish: sv</fullName>
                </value>
                <value>
                    <fullName>Thai: th</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProductAmount__c</fullName>
        <description>Indicates the "Product Amount" of Partner Sales Lead</description>
        <label>Estimated Product Amount</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project_Flag__c</fullName>
        <description>NGCC Phase1:Flag to indicate whether customer has any project</description>
        <label>Project Flag</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>QABudget__c</fullName>
        <description>Budget the customer has indicated for the project.
LTLM integrated field</description>
        <label>Project Budget</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>$0 - $999</fullName>
                </value>
                <value>
                    <fullName>$1000 - $4999</fullName>
                </value>
                <value>
                    <fullName>$5000 - $14,999</fullName>
                </value>
                <value>
                    <fullName>$15,000 - $24,999</fullName>
                </value>
                <value>
                    <fullName>$25,000 - $49,999</fullName>
                </value>
                <value>
                    <fullName>$50,000 - $99,999</fullName>
                </value>
                <value>
                    <fullName>$100,000+</fullName>
                </value>
                <value>
                    <fullName>No budget available</fullName>
                </value>
                <value>
                    <fullName>Don't know / Not responsible</fullName>
                </value>
                <value>
                    <fullName>Budget amount not fixed</fullName>
                </value>
                <value>
                    <fullName>Did not respond</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>QAPartner__c</fullName>
        <description>Name of the preferred partner.
LTLM integrated field.</description>
        <label>Preferred Partner Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QATimeFrame__c</fullName>
        <description>Project time frame
LTLM integrated field</description>
        <label>Time Frame</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Now - 3 Months</fullName>
                </value>
                <value>
                    <fullName>4 - 6 Months</fullName>
                </value>
                <value>
                    <fullName>7 - 12 Months</fullName>
                </value>
                <value>
                    <fullName>Over 12 Months</fullName>
                </value>
                <value>
                    <fullName>No Plans To Purchase</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ServicesAmount__c</fullName>
        <description>Indicates the "Services Amount" of Partner Sales Lead</description>
        <label>Estimated Service Amount</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ObjectRecordTypeIds__c.object
<CustomObject>
    <fields>
        <fullName>Marketing_Lead_RecordType__c</fullName>
        <description>This is to store marketing_Lead recordtype</description>
        <label>Marketing Lead RecordType</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is used to store the record type ids of account and contact objects.</description>
    <label>Object Record Type Ids</label>
</CustomObject>

classes/NGCC_PS_CreateResponseDetails_Flow_Test.cls
@isTest(SeeAllData=true) 
public class NGCC_PS_CreateResponseDetails_Flow_Test {
    @isTest
    public static void createResponseDetailsTest(){
       
        Lead testLead = new Lead();
        testLead.RecordTypeId = ObjectRecordTypeIds__c.getInstance().Marketing_Lead_RecordType__c;
        testLead.FirstName = 'John';
        testLead.LastName = 'Doe';
        testLead.Title = 'Engineer';
        testLead.Contact_Department__c = 'Engineering';
        testLead.Phone = '(123) 123-4567';
        testLead.Call_Permission__c = 'Yes';
        testLead.Email = 'test@test.com';
        testLead.Preferred_Language__c = 'English: en_US';
        testLead.Company = 'Dummy Company';
        testLead.Address_Line_1__c = '123 Main Street';
        testLead.Address_Line_2__c = 'Suite 123';
        testLead.Address_Line_3__c = '';
        testLead.CustomCity__c = 'Some City';
        testLead.CustomState__c = 'Some State';
        testLead.CustomCountry__c = 'United States';
        testLead.CustomZip__c = '12345';
        testLead.Project_Flag__c = 'Yes';
        testLead.QATimeFrame__c = 'Unknown';
        testLead.QABudget__c = 'Budget amount not fixed';
        testLead.Main_Technology__c = 'Computers';
        testLead.QAPartner__c = 'Tech Company #2';
        testLead.ProductAmount__c = 10000;
        testLead.ServicesAmount__c = 11;
        
        INSERT testLead;
        
        CC_Response__c testResponse = new CC_Response__c();
        testResponse.Lead__c = testLead.Id;
        testResponse.Status__c = 'Qualified Lead';
        INSERT testResponse;
        
        NGCC_PS_CreateResponseDetails_Flow.createResponseDetails(new List<Id>{testResponse.id});
    }
}