objects/CEE__c.object
<CustomObject>
    <fields>
        <fullName>Expected_Product__c</fullName>
        <description>This field is to display the Expected Product Converted Value on CES record</description>
        <formula>Opportunity__r.Expected_Product__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expected Product Converted ($000)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Jiffle_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>JiffleNow Re-design: To create relationship of Events with CEE-Lookup Relationship</description>
        <label>Global Event</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Jiffle_Event__c.Event_Start_Date__c</field>
                <operation>greaterOrEqual</operation>
                <valueField>Jiffle_Event__c.Jiffle_Today_Date__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Jiffle_Event__c</referenceTo>
        <relationshipLabel>Customer Engagements &amp; Events</relationshipLabel>
        <relationshipName>Customer_Engagements_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Engagements &amp; Events</relationshipLabel>
        <relationshipName>Primary_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <description>This object will store summary level briefing information from CEE. This Object is created to Integrate CEE Applicaiton data with Salesforce.com. It allows users to link CEE Briefings with Accounts in Salesforce.com.</description>
    <label>Customer Engagements &amp; Events</label>
    <nameField>
        <displayFormat>CEE-{000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Engagements &amp; Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/GlobalTriggerManagement__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>GlobalTriggerManagement</label>
</CustomObject>

objects/Jiffle_Agenda_Item__c.object
<CustomObject>
    <fields>
        <fullName>Jiffle_Event__c</fullName>
        <label>Jiffle Event</label>
        <referenceTo>Jiffle_Event__c</referenceTo>
        <relationshipLabel>JiffleNow Agenda Items</relationshipLabel>
        <relationshipName>Jiffle_Agenda_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>JiffleNow Agenda Item</label>
    <nameField>
        <label>Jiffle Agenda Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>JiffleNow Agenda Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Jiffle_Attendee_Invitee__c.object
<CustomObject>
    <fields>
        <fullName>Attendee_Email__c</fullName>
        <label>Attendee Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Attendee_First_Name__c</fullName>
        <label>Attendee First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attendee_Last_Name__c</fullName>
        <label>Attendee Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contact Sync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Customer_Engagements_Events__c</fullName>
        <label>Customer Engagements &amp; Events</label>
        <referenceTo>CEE__c</referenceTo>
        <relationshipName>Jiffle_Attendees_Invitees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Jiffle_Session_Meeting__c</fullName>
        <label>Salesforce Meeting ID</label>
        <referenceTo>Jiffle_Meeting_Session__c</referenceTo>
        <relationshipName>CEE_Jiffle_Invites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Primary_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Jiffle_Attendees_Invitees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requestor_Email__c</fullName>
        <label>Requestor Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Requestor__c</fullName>
        <label>Requestor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFDC_Source__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SFDC Source?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>JiffleNow Attendee</label>
    <nameField>
        <displayFormat>JF-{0000000}</displayFormat>
        <label>JiffleNow Invite Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JiffleNow Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Jiffle_Event__c.object
<CustomObject>
    <fields>
        <fullName>Event_End_Date__c</fullName>
        <label>Event End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Start_Date__c</fullName>
        <label>Event Start Date</label>
        <type>Date</type>
    </fields>
    <label>Global Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Global Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Jiffle_Meeting_Session__c.object
<CustomObject>
    <fields>
        <fullName>Jiffle_Agenda_Item__c</fullName>
        <label>JiffleNow Agenda Item</label>
        <referenceTo>Jiffle_Agenda_Item__c</referenceTo>
        <relationshipLabel>JiffleNow Meeting</relationshipLabel>
        <relationshipName>Jiffle_Meetings_Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Meeting_UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This field is to store the Jiffle's Unique Meeting ID</description>
        <externalId>true</externalId>
        <label>JiffleNow Meeting UUID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>JiffleNow Meeting</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Salesforce Meeting Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JiffleNow Meeting</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/NGCC_Mapping_Object__c.object
<CustomObject>
    <label>CC Mapping Object</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NGCC Mapping Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ObjectRecordTypeIds__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is used to store the record type ids of account and contact objects.</description>
    <label>Object Record Type Ids</label>
</CustomObject>

objects/Org_Constant_CS__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Org Constant CS</label>
</CustomObject>

objects/Org_Constants__c.object
<CustomObject>
    <label>Org Constant</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Org Constants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProfileID__c.object
<CustomObject>
    <fields>
        <fullName>Cisco_Renewals__c</fullName>
        <defaultValue>'00e34000001CQnp'</defaultValue>
        <description>00e34000001CQnp</description>
        <inlineHelpText>00e34000001CQnp</inlineHelpText>
        <label>Cisco_Renewals</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is used to store the profile ids for all the available profiles.</description>
    <label>Profile ID</label>
</CustomObject>

classes/JiffleNowReporting_Emails_Batchable_Test.cls
/************************************************************************************************************************************
Name    : JiffleNowReporting_Emails_Batchable_Test 
Author  : Mukesh Srivastava
Purpose : This Test class to perform Reconcile Email generation and Reporting Updates
Created Date: 5/25/2015
Modification History: 
	Author  : Ghattamaneni Chaithanya
	Purpose : test Custom setting records are added to fix test class failure line no# 20-24
	Date	: 17-May-2019
*************************************************************************************************************************************/
@isTest
public class JiffleNowReporting_Emails_Batchable_Test {
    //Setting Up data for This test class
    @testSetup static void setupTestData() {
        List < sObject > cUsers = Test.loadData(User.sObjectType,'GlobalTestUsers');
        List < User > userlist = (List < User > ) cUsers;
        system.debug('userlist[0]'+userlist[0].profileId);
        System.RunAs(userlist[0]){
            
        // Added by gchaitha to fix test failure
        ProfileID__c ProfileIDObj = new ProfileID__c();
        ProfileIDObj.SetupOwnerId = UserInfo.getOrganizationId();
        ProfileIDObj.Cisco_Renewals__c = 'test';
        insert ProfileIDObj;
            
        CEE_TestUtility.loadCustomSettings();           
        //List < sObject > cOrgCS = Test.loadData(Org_Constant_CS__c.sObjectType, 'GlobalTestOrgConstantCS');
        List < sObject > cOrgConstantObject = Test.loadData(Org_Constants__c.sObjectType, 'OrgConstants');
       // List < sObject > cObjRecId = Test.loadData(ObjectRecordTypeIds__c.sObjectType, 'GlobalTestObjectRecordTypeIds');
        List < sObject > cMappings = Test.loadData(NGCC_Mapping_Object__c.sObjectType, 'GlobalTestMapping');
        List < sObject > cAccounts = Test.loadData(Account.sObjectType, 'GlobalTestAccounts');
        List < sObject > cEvents = Test.loadData(Jiffle_Event__c.sObjectType, 'GlobalTestEvents');
        
       
        GlobalTriggerManagement__c gm = new GlobalTriggerManagement__c();
        gm.Name = 'JiffleR1_CEE';
        gm.Active__c = false;
        insert gm;
        
        List < Account > alist = (List < Account > ) cAccounts;
        List < Jiffle_Event__c > evtlist = (List < Jiffle_Event__c > ) cEvents;
        List < Jiffle_Agenda_Item__c> agendalist = new List < Jiffle_Agenda_Item__c> ();
        
        Integer j = 0;
        for (Jiffle_Event__c jfEObj: evtlist) {
            if (j == 0) { //Before Event
                jfEObj.Event_Start_Date__c = date.today();
                jfEObj.Event_End_Date__c = date.today() + 5;
            } else if (j == 1) { //After Event
                jfEObj.Event_Start_Date__c = date.today() - 32;
                jfEObj.Event_End_Date__c = date.today() - 29;
                Integer daysAfterEvent = jfEObj.Event_End_Date__c.daysBetween(System.today());
                system.debug('fffffff'+daysAfterEvent);
            } else {
                jfEObj.Event_Start_Date__c = date.today() - (j + 4);
                jfEObj.Event_End_Date__c = date.today() - (j + 2);
            }
            Jiffle_Agenda_Item__c jfAgenda = new Jiffle_Agenda_Item__c();
            jfAgenda.Name = 'Agenda' + j;
            jfAgenda.Jiffle_Event__c = jfEObj.Id;
            agendalist.add(jfAgenda);
            j++;
        }

        update evtlist;
        system.debug('ttttttt'+evtlist);
        insert agendalist;

        List < CEE__c > lstCEE = new List < CEE__c > ();
        List < Opportunity > lstOppty = new List < Opportunity > ();

        Id idOfJiffleRec = Schema.SObjectType.CEE__c.getRecordTypeInfosByName().get('Jifflenow (Event, Tradeshow, Conference)').getRecordTypeId();
        Integer i = 0;
        Date vCloseDate = System.today();
        List< Jiffle_Meeting_Session__c> meetingList = new List< Jiffle_Meeting_Session__c>();
        
        for (Account accObj: alist) {
            CEE__c ceeObj = new CEE__c();
            ceeObj.Primary_Account__c = accObj.Id;
            ceeObj.Jiffle_Event__c = evtlist[i].Id;
            ceeObj.RecordTypeId = idOfJiffleRec;
            lstCEE.add(ceeObj);

            Opportunity opptyObj = new Opportunity(Name = 'Test1' + i, StageName = '1 - Identify', CloseDate = vCloseDate,
                Expected_Product__c = 10, Forecast_Discount__c = 1, CurrencyIsoCode = UserInfo.getDefaultCurrency(),
                AccountId = accObj.Id, Competitors__c = 'Allot', Has_Competitors__c = true, Opportunity_Status__c = 'Booked',skipValidations__c = true,Partner_Required__c =false);
            lstOppty.add(opptyObj);
            
            Jiffle_Meeting_Session__c jfMeeting=new Jiffle_Meeting_Session__c();
            jfMeeting.Jiffle_Agenda_Item__c = agendalist[i].Id;
            jfMeeting.Meeting_UUID__c = 'UUID'+i;
            meetingList.add(jfMeeting);
            
            i = i + 1;
        }
        insert lstCEE;
        insert lstOppty;
        insert meetingList;
        
        List<CEE__c> ceels = [Select Jiffle_event__r.Event_End_Date__c from CEE__c];
        system.debug('tttttttt'+ceels);
        
        List< Jiffle_Attendee_Invitee__c > jfAttendee= new List< Jiffle_Attendee_Invitee__c >();
        Integer p = 0;
        for(Jiffle_Meeting_Session__c jfMeetingObj: meetingList){
            Id idCEE = lstCEE[p].Id;
            for(Integer k=0;k<10;k++){
                Jiffle_Attendee_Invitee__c jfAtt = new Jiffle_Attendee_Invitee__c();
                jfAtt.Attendee_First_Name__c = 'FirstAtt'+k;
                jfAtt.Attendee_Last_Name__c = 'LastAtt'+k;
                jfAtt.Attendee_Email__c = 'LastAtt@test.com'+k;
                jfAtt.Jiffle_Session_Meeting__c = jfMeetingObj.Id;
                jfAtt.Customer_Engagements_Events__c = idCEE;
                jfAtt.Requestor_Email__c  = userlist[k].Email;
                jfAtt.Requestor__c = userlist[k].FirstName;
                jfAtt.Contact_Sync__c = false;
                jfAtt.Title__c = 'CFO'+k;
                jfAtt.SFDC_Source__c = true;           
                jfAttendee.add(jfAtt);
            }  
            p++;             
        }
        
        insert jfAttendee;
        }
    }
    
    //@ Testing Reporting Batch Updates which tracks new Opportunities and Event Metrics
    static testMethod void testReportingUpdateBatchTest() {
        Test.startTest();
            JiffleNowReporting_Batchable ejfUpdate = new JiffleNowReporting_Batchable();
            Id batchinstanceid = database.executeBatch(ejfUpdate, 50);
        Test.stopTest();
    }

    //@ Testing Email Reminder to Reconcile Contacts
    static testMethod void testEmailReminderBatchTest() {
        Test.startTest();        
            JiffleNowWeeklyConfirmation_Batchable ejfEmailUpdate = new JiffleNowWeeklyConfirmation_Batchable();
            Id batchinstanceid = database.executeBatch(ejfEmailUpdate, 50);
        Test.stopTest();
    }

}