objects/CEE__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_Engineer__c</fullName>
        <description>This will store the concatenated value of Personnel. This is related to CPOC lab request.</description>
        <label>Assigned Engineer</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <description>This object will store summary level briefing information from CEE. This Object is created to Integrate CEE Applicaiton data with Salesforce.com. It allows users to link CEE Briefings with Accounts in Salesforce.com.</description>
    <label>Customer Engagements &amp; Events</label>
    <nameField>
        <displayFormat>CEE-{000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Engagements &amp; Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CPOC_Personnel__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Engagements_Events__c</fullName>
        <description>CPOC Lab Request related to this engineer</description>
        <label>Customer Engagements &amp; Events</label>
        <referenceTo>CEE__c</referenceTo>
        <relationshipLabel>CPOC Personnel</relationshipLabel>
        <relationshipName>CPOC_Personnels</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Personnel__c</fullName>
        <description>Engineer available for respective preferred lab</description>
        <label>Personnel</label>
        <referenceTo>Personnel__c</referenceTo>
        <relationshipLabel>CPOC Personnels</relationshipLabel>
        <relationshipName>CPOC_Personnels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>CPOC Personnel</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Personnel Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CPOC Personnels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Personnel__c.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CPOC_Personals</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>This is a Master Object for CPOC Personnel.</description>
    <label>Personnel</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Personnel Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Personnels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CPOCPersonnelTriggerHandler.cls
/***************************************************************************************************
Name    : CPOCRoomsTriggerHandler 
Author  : Abinash Das
Purpose : Handler Class to delete Personnel once deleted from related list.  
Created Date: Apr 08 2016              
*****************************************************************************************************/

Public Class CPOCPersonnelTriggerHandler{
    
    // SCAVA Helper Method to validate Update Access at field level
     public static Boolean flsUpdate(SObjectField field)
    {
        return field.getDescribe().isUpdateable() ? true : false;
    }

    public List<CPOC_Personnel__c> listNewSobject;
    public List<CPOC_Personnel__c> listOldSobject;
    Map<Id,List<String>> mapCPOCEngagementPersonnel;
    
    public CPOCPersonnelTriggerHandler(List<sObject> listOld, List<sObject> listNew){
        listNewSobject = new List<CPOC_Personnel__c>();
        listOldSobject = new List<CPOC_Personnel__c>();
        listNewSobject = listNew;
        listOldSobject = listOld;
    }
    /* Method to create Personnel data */
    public void assignEngineerOnDML( String dmlType ){

        Set<Id> setPersonnelEventId = new Set<Id>();
        mapCPOCEngagementPersonnel = new Map<Id,List<String>>();
        if( dmlType == 'upsert' ){
            if( listNewSobject != null ){
                for(CPOC_Personnel__c sObjdata : listNewSobject ){
                
                    if(!setPersonnelEventId.contains(sObjdata.Customer_Engagements_Events__c)){
                    
                        setPersonnelEventId.add(sObjdata.Customer_Engagements_Events__c);
                    }
                }
                List<CEE__c> listCPOCEvents = new List<CEE__c>();
                listCPOCEvents = [SELECT Id, (SELECT Id, Customer_Engagements_Events__c, Personnel__r.User__r.alias FROM CPOC_Personnels__r) FROM CEE__c WHERE Id IN : setPersonnelEventId ];
        
                for( CEE__c cpocEvents : listCPOCEvents  ){
                    
                    if(! mapCPOCEngagementPersonnel.keySet().contains(cpocEvents.Id) ){
                    
                        mapCPOCEngagementPersonnel.put( cpocEvents.Id, new List<String>() );
                        
                    }
                    
                    for( CPOC_Personnel__c dataPersonnel : cpocEvents.CPOC_Personnels__r ){
                        
                        mapCPOCEngagementPersonnel.get(cpocEvents.Id).add(dataPersonnel.Personnel__r.User__r.alias);
                    }
                    
                }
            }
        }else if( dmlType == 'delete' ){
        
            prepareTheDataForDeleteProcess();
        }
        genericProcessForAllDMLAction(mapCPOCEngagementPersonnel);
        
    }
    /* Method to delete Personnel if deleted from related list */
    public void prepareTheDataForDeleteProcess(){
        Set<Id> setPersonnelEventId = new Set<Id>();
        if( listOldSobject != null ){
            for(CPOC_Personnel__c sObjdata : listOldSobject ){
            
                if(!setPersonnelEventId.contains(sObjdata.Customer_Engagements_Events__c)){
                
                    setPersonnelEventId.add(sObjdata.Customer_Engagements_Events__c);
                }
            }
            List<CEE__c> listCPOCEvents = new List<CEE__c>();
            listCPOCEvents = [SELECT Id, (SELECT Id, Customer_Engagements_Events__c, Personnel__r.User__r.alias FROM CPOC_Personnels__r) FROM CEE__c WHERE Id IN : setPersonnelEventId ];
    
            for( CEE__c cpocEvents : listCPOCEvents  ){
                
                if(! mapCPOCEngagementPersonnel.keySet().contains(cpocEvents.Id) ){
                
                    mapCPOCEngagementPersonnel.put( cpocEvents.Id, new List<String>() );
                    
                }
                
                for( CPOC_Personnel__c dataPersonnel : cpocEvents.CPOC_Personnels__r ){
                    
                    mapCPOCEngagementPersonnel.get(cpocEvents.Id).add(dataPersonnel.Personnel__r.User__r.alias);
                }
                
            }
        }

    }
    /* Method to add Personnel once added to Related List */
    public void genericProcessForAllDMLAction(Map<Id,List<String>> mapCPOCEngagementPersonnel){
        List<CEE__c> listEventsToUpdate = new List<CEE__c>();
        for( Id eventId : mapCPOCEngagementPersonnel.keySet() ){
            String aliasFormatted = '';
            Integer loopCounter = 0;
            if(mapCPOCEngagementPersonnel.get(eventId).isEmpty() ){
                CEE__c ceeObj = new CEE__c(Id=eventId);
                // SCAVA FIX
                if(flsUpdate(CEE__c.Assigned_Engineer__c))
                {
                ceeObj.Assigned_Engineer__c = '';
                }
                listEventsToUpdate.add(ceeObj);
                
            }else{                                           
                for( String aliasname : mapCPOCEngagementPersonnel.get(eventId) ){
                    if( loopCounter == 0 ){
                        aliasFormatted = aliasname;
                    }else{
                        aliasFormatted = aliasFormatted+','+aliasname;
                    }
                    loopCounter++;
                }  
                CEE__c ceeObj = new CEE__c(Id=eventId);
                // SCAVA FIX
                if(flsUpdate(CEE__c.Assigned_Engineer__c))
                {
                ceeObj.Assigned_Engineer__c = aliasFormatted;
                }
                listEventsToUpdate.add(ceeObj);
            }
            
            
        }
        update listEventsToUpdate;
    }
}