objects/CEE__c.object
<CustomObject>
    <description>This object will store summary level briefing information from CEE. This Object is created to Integrate CEE Applicaiton data with Salesforce.com. It allows users to link CEE Briefings with Accounts in Salesforce.com.</description>
    <label>Customer Engagements &amp; Events</label>
    <nameField>
        <displayFormat>CEE-{000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Engagements &amp; Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>OBX</fullName>
        <active>true</active>
        <description>Delivering Demonstrations, Briefings, and Events</description>
        <label>Outcome Based Experience (OBX - formerly EBC)</label>
    </recordTypes>
</CustomObject>

objects/CEE_Location__c.object
<CustomObject>
    <description>The location details for a given Location, either a Field Sales Office (FSO), Executive Briefing Center (EBC), or Customer Briefing Center provided as part of the Customer Engagement implementation.</description>
    <label>CEE Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CEE Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CEE_Room__c.object
<CustomObject>
    <fields>
        <fullName>CEE_Location__c</fullName>
        <label>CEE Location</label>
        <referenceTo>CEE_Location__c</referenceTo>
        <relationshipLabel>CEE Rooms</relationshipLabel>
        <relationshipName>CEE_Rooms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>CEE Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CEE Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CEE_Briefing_InviteList_Controller_Test.cls
/***************************************************************************************************
Name    : CEE_Briefing_InviteList_Controller_Test 
Author  : Eric Pesch
Purpose : Test for CEE Brefing Invitelist Shell page 
Created Date: Dec 1 2014
Modification History: 
Eric Pesch - Jan 5 2015: Added Comments, cleanup                     
*****************************************************************************************************/

@isTest
private class CEE_Briefing_InviteList_Controller_Test {

    /*@method: Briefing Invite List test method*/
    static testMethod void ceeBriefingInviteListTest() {
        //Variables
        String testRoot = null, testEnv = null;
        
        //Setup Account
        User admin = CEE_TestUtility.getUser('admin', true);
        Account acct = null;
        Opportunity oppty = null;
        
        System.runAs(admin){
            CEE_TestUtility.loadCustomSettings();
            acct = CEE_TestUtility.getAccount('brief', true);
        }
        
        //Setup location
        CEE_Location__c loc = CEE_TestUtility.getLocation('brief', true, 'EBC/EC');
        
        CEE_Room__c room = CEE_TestUtility.getRoom('brief', true, loc, false, 6);
        
        //Setup briefing
        Opportunity opppt =  CEE_TestUtility.getOpty();
        CEE__c briefing = CEE_TestUtility.getBriefing('brief', true, 'OBX', acct, opppt, loc);
        
        //APEX Page testing
        ApexPages.StandardController stdItem = new ApexPages.StandardController(briefing);
        CEE_Briefing_InviteList_Controller briefingController = new CEE_Briefing_InviteList_Controller(stdItem);
        
        //Back method
        PageReference backRef = briefingController.backMethod();
    }
}