objects/CEE__c.object
<CustomObject>
    <fields>
        <fullName>CPOC_End_Date__c</fullName>
        <description>Visit End Date of CPOC lab request</description>
        <label>CPOC End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CPOC_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CPOC Location is added for CPOC lab request</description>
        <label>CPOC Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Preferred_Lab__c</field>
                <operation>contains</operation>
                <valueField>CEE_Location__c.Name</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CEE_Location__c</referenceTo>
        <relationshipLabel>Customer Engagements &amp; Events (CPOC Location)</relationshipLabel>
        <relationshipName>Customer_Engagements_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CPOC_Start_Date__c</fullName>
        <description>Visit Start Date of CPOC Lab request</description>
        <label>CPOC Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Primary_Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Engagements &amp; Events</relationshipLabel>
        <relationshipName>Primary_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <description>Briefing Request Status and it is related to CPOC lab request.</description>
        <inlineHelpText>Current stage of an Engagement Request</inlineHelpText>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Returned (all resources released)</fullName>
                </value>
                <value>
                    <fullName>Cancelled (all resources released)</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Saved, not Submitted</fullName>
                </value>
                <value>
                    <fullName>Assigned to PM</fullName>
                </value>
                <value>
                    <fullName>Submitted by Requester</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Lab Redirect</fullName>
                </value>
                <value>
                    <fullName>Returned by Scheduler</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Requested_Customer_Arrival_Date__c</fullName>
        <description>Requested customer arrival date populated by customer while creating CPOC Lab Request.</description>
        <label>Requested Customer Arrival Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Requested_Customer_End_Date__c</fullName>
        <description>Requested Customer arrival end date is populated based on service type and and the value of requested customer arrival date</description>
        <label>Requested Customer End Date</label>
        <type>DateTime</type>
    </fields>
    <description>This object will store summary level briefing information from CEE. This Object is created to Integrate CEE Applicaiton data with Salesforce.com. It allows users to link CEE Briefings with Accounts in Salesforce.com.</description>
    <label>Customer Engagements &amp; Events</label>
    <nameField>
        <displayFormat>CEE-{000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Engagements &amp; Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CEE_Location__c.object
<CustomObject>
    <description>The location details for a given Location, either a Field Sales Office (FSO), Executive Briefing Center (EBC), or Customer Briefing Center provided as part of the Customer Engagement implementation.</description>
    <label>CEE Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CEE Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CEE_Room__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CEE_Location__c</fullName>
        <label>CEE Location</label>
        <referenceTo>CEE_Location__c</referenceTo>
        <relationshipLabel>CEE Rooms</relationshipLabel>
        <relationshipName>CEE_Rooms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>CEE Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CEE Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CPOC_Room__c.object
<CustomObject>
    <fields>
        <fullName>CPOC_End_Date__c</fullName>
        <description>Visit End date of this particular room</description>
        <label>Room End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CPOC_Start_Date__c</fullName>
        <description>Visit Start date of this particular room</description>
        <label>Room Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Customer_Engagements_Events__c</fullName>
        <description>CPOC Request related to CPOC Room</description>
        <label>Customer Engagements &amp; Events</label>
        <referenceTo>CEE__c</referenceTo>
        <relationshipLabel>CPOC Rooms</relationshipLabel>
        <relationshipName>CPOC_Rooms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Room__c</fullName>
        <description>Rooms available for CPOC Lab Request</description>
        <label>Room</label>
        <referenceTo>CEE_Room__c</referenceTo>
        <relationshipLabel>CPOC Rooms</relationshipLabel>
        <relationshipName>CPOC_Rooms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <description>This is a junction object between Customer Engagement and Events and CEE Rooms Object.</description>
    <label>CPOC Room</label>
    <nameField>
        <displayFormat>RM-{00000}</displayFormat>
        <label>Room Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CPOC Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CPOC_RoomEditController.cls
/***************************************************************************************************
Name    : CPOC_RoomEditController 
Author  : Priyanka Jangid
Purpose : Visualforce Page Controller for custom CPOC Room page  
Created Date: Jan 25 2016    
Modified By :
        Sudi - Aug 17th 2016: Added this extra check during normalization fix.
                              To check the RoolId is empty or not to void code execution.
*****************************************************************************************************/

public class CPOC_RoomEditController {
    // SCAVA Helper Method to validate Update Access at field level
     public static Boolean flsUpdateGet(SObjectField field)
    {
        return field.getDescribe().isUpdateable() ? true : false;
    }
    // SCAVA Helper Method to validate Create Access at field level
     public static Boolean flsGet(SObjectField field)
    {
        return field.getDescribe().isCreateable() ? true : false;
    }

    //Record and controller variables
    private static String TAG = 'CPOC_RoomEditController';
    public CPOC_Room__c room;
    public final ApexPages.StandardController controller;
    
    //Related object list variables
    public CEE__c briefing { get; set; }       
    public List<CEE_Room__c> siteRooms;
    public string sRoomStatus{get;set;}
    
    //Page display variables
    public String pageUrl { get; set; }
    public String pageDisplay { get; set; }    
    public String roomName { get; set; }
    public list<CPOC_Room__c> lstRooms{get;set;}    
    //Room variables
    public String selRoom { get; set; }
    public string selRoomName {get;set;}    
    public void returnRoomAvaibilityStatus(){  
        try{
            // Sudi - Aug 17th 2016 : Added this condition in code as part normalization fix.
            // Checking for selroom is empty or not.
            if(String.isEmpty(selRoom)){
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.WARNING,'Invalid or no Room selected'));               
            }
            else{
                lstRooms = new list<CPOC_Room__c>();
                lstRooms = [select id, Customer_Engagements_Events__r.Primary_Account__r.Name,CPOC_Start_Date__c,CPOC_End_Date__c,room__r.Name,Customer_Engagements_Events__r.Request_Status__c from CPOC_Room__c
                                                 where Customer_Engagements_Events__r.Request_Status__c in('Submitted','Scheduled','Lab Redirect') AND Room__c =:selRoom
                                                 AND id != :room.id
                                                 AND ((CPOC_Start_Date__c >=: room.CPOC_Start_Date__c  AND CPOC_Start_Date__c <=:  room.CPOC_End_date__c)
                                                 OR (CPOC_End_Date__c >=: room.CPOC_Start_Date__c  AND CPOC_End_Date__c <=: room.CPOC_End_date__c)
                                                 OR(CPOC_Start_Date__c <=: room.CPOC_Start_Date__c  AND CPOC_End_Date__c >=: room.CPOC_End_date__c) )];
                                                       
                selRoomName = [select name from CEE_Room__c where id=:selRoom limit 1].Name;               
                sRoomStatus = ((lstRooms.isEmpty()) ? 'Not Booked' : 'Booked');   
            }
        }                  
        catch(Exception e){            
            ApexPages.addMessages(e);           
        }              
    }
    /*@method: Generic save function*/
    public PageReference doSave(){        
        if(String.isEmpty(selRoom)){
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.WARNING,'Invalid or no Room selected'));
            return null;
        }
        
        //Save the attendee record
        try{
            if(room.Id == null){
            
            if(flsUpdateGet(CPOC_Room__c.Room__c)||flsGet(CPOC_Room__c.Room__c)) //SCAVA FIX
               {
                room.Room__c = selRoom; 
               }
                insert room;
            } else {
                if(room.room__c == selroom){
                    update room;
                 }
                else{
                    ApexPages.addMessage(new ApexPages.message(ApexPages.severity.WARNING,'Room cannot be changed'));
                    return null;
                 }
            }
        } catch(Exception e){            
            ApexPages.addMessages(e);
            return null;
        }        
        
        //Briefing return       
        return new PageReference('/'+room.Customer_Engagements_Events__c);
    }
      /* **********************************************************
           Added By Naresh (nkalahas@cisco.com) on 31/01/2018  to redirect to previous page on cancel
       ************************************************************  */          

       public PageReference doCancel() {
        String url = ApexPages.currentPage().getHeaders().get('Referer');

        PageReference pageRef = new PageReference('/' + room.Customer_Engagements_Events__c );
        pageRef.setRedirect(true);
        return pageRef; 

        }  
        
    /*@Constructor: Controller construction and initialization*/
    public CPOC_RoomEditController(ApexPages.StandardController stdController){
        List<String> popFields = new List<String>{'Id', 'Name', 'Customer_Engagements_Events__c', 
            'CPOC_End_date__c','Room__c', 'CPOC_Start_Date__c', 'room__r.Name','Customer_Engagements_Events__r.Primary_Account__r.Name'}; 
        List<String> locations = new List<String>();        
        this.controller = stdController;
        if(!Test.isRunningTest()){
            this.controller.addFields(popFields);
        }
        this.room = (CPOC_Room__c)stdController.getRecord();
        this.pageDisplay = 'New CPOC Room'; //default behavior
        this.pageUrl = ApexPages.currentPage().getUrl();
        
            
        //Populate briefing sites
        try{
            briefing = [select Id, CPOC_Location__c, CPOC_Start_Date__c, CPOC_End_Date__c,Requested_Customer_Arrival_Date__c, Requested_Customer_End_Date__c 
                        from CEE__c 
                        where Id =: room.Customer_Engagements_Events__c];                
        } catch(Exception e){
            System.debug(TAG + 'Error retrieving Briefing - ' + e.getStackTraceString());
        }
        
        //Populate default variables      
        if(this.room.Id == null){
            if(flsUpdateGet(CPOC_Room__c.CPOC_Start_Date__c)||flsGet(CPOC_Room__c.CPOC_Start_Date__c)) //SCAVA FIX     
            {
             room.CPOC_Start_Date__c = briefing.CPOC_Start_Date__c;
            }
            if(flsUpdateGet(CPOC_Room__c.CPOC_End_date__c)||flsGet(CPOC_Room__c.CPOC_End_date__c)) //SCAVA FIX 
            {
            room.CPOC_End_date__c = briefing.CPOC_End_Date__c;
            }           
        } else {                        
            if(room.Name != null){
                roomName = room.Name;
                pageDisplay = room.Name;
            }
            selRoom = room.Room__c;
        }             
        //Get rooms - Primary Site OR Briefing Sites
        if(briefing != null){
            locations.add(briefing.CPOC_Location__c);
        }        
        
        try{
            //Get briefing Rooms
            List<Id> oldcpocRooms = new List<Id>();
            List<CPOC_Room__c> cpocRooms = [select Id, Name, Room__c from CPOC_Room__c where Customer_Engagements_Events__c =: room.Customer_Engagements_Events__c
                            and Id !=: room.Id];
            for(CPOC_Room__c cpocRoom : cpocRooms){
                oldcpocRooms.add(cpocRoom.Room__c);
            }
            
            //Filter sites by locations and not added already
            siteRooms = [select Id, Name, CEE_Location__c, CEE_Location__r.Name, Active__c from CEE_Room__c where CEE_Location__c IN : locations
                        AND Id NOT IN : oldcpocRooms AND Active__c = TRUE ];
        } catch (Exception e){
            System.debug(TAG + 'Error retrieving Room Options - ' + e.getStackTraceString());
        }
    }
    
    /*@method: Getter for Select Room Picklist*/
    public List<SelectOption> getRoomOptions(){
        List<SelectOption> roomOptions = new List<SelectOption>();
        
        for(CEE_Room__c siteRoom : siteRooms){
            roomOptions.add(new SelectOption(siteRoom.Id, siteRoom.CEE_Location__r.Name + ' - ' + siteRoom.Name));
        }
        
        if(roomOptions.isEmpty()){
            roomOptions.add(new SelectOption('','No CPOC Rooms found for this CPOC Lab',true));
        } else {
            roomOptions.add(new SelectOption('','--None--'));
        }
        roomOptions.sort();
        return roomOptions;
    }
}