objects/CEE__c.object
<CustomObject>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <defaultValue>DATETIMEVALUE(Today()+11)</defaultValue>
        <inlineHelpText>Shown in User's Local Timezone</inlineHelpText>
        <label>End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Jiffle_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>JiffleNow Re-design: To create relationship of Events with CEE-Lookup Relationship</description>
        <label>Global Event</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Jiffle_Event__c.Event_Start_Date__c</field>
                <operation>greaterOrEqual</operation>
                <valueField>Jiffle_Event__c.Jiffle_Today_Date__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Jiffle_Event__c</referenceTo>
        <relationshipLabel>Customer Engagements &amp; Events</relationshipLabel>
        <relationshipName>Customer_Engagements_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>For Best Search results use the Deal ID or Opportunity name to search for the opportunity you want to associate with the request. Click lookup, enter information and select the opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Customer Engagements &amp; Events</relationshipLabel>
        <relationshipName>Customer_Engagement_Scheduler</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Engagements &amp; Events</relationshipLabel>
        <relationshipName>Primary_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <description>Briefing Request Status and it is related to CPOC lab request.</description>
        <inlineHelpText>Current stage of an Engagement Request</inlineHelpText>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Returned (all resources released)</fullName>
                </value>
                <value>
                    <fullName>Cancelled (all resources released)</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Saved, not Submitted</fullName>
                </value>
                <value>
                    <fullName>Assigned to PM</fullName>
                </value>
                <value>
                    <fullName>Submitted by Requester</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Lab Redirect</fullName>
                </value>
                <value>
                    <fullName>Returned by Scheduler</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <defaultValue>DATETIMEVALUE(Today() + 10)</defaultValue>
        <inlineHelpText>Shown in User's Local Timezone</inlineHelpText>
        <label>Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <description>This object will store summary level briefing information from CEE. This Object is created to Integrate CEE Applicaiton data with Salesforce.com. It allows users to link CEE Briefings with Accounts in Salesforce.com.</description>
    <label>Customer Engagements &amp; Events</label>
    <nameField>
        <displayFormat>CEE-{000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Engagements &amp; Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Jiffle_Agenda_Item__c.object
<CustomObject>
    <fields>
        <fullName>Jiffle_Event__c</fullName>
        <label>Jiffle Event</label>
        <referenceTo>Jiffle_Event__c</referenceTo>
        <relationshipLabel>JiffleNow Agenda Items</relationshipLabel>
        <relationshipName>Jiffle_Agenda_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Topic__c</fullName>
        <label>Topic</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>JiffleNow Agenda Item</label>
    <nameField>
        <label>Jiffle Agenda Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>JiffleNow Agenda Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Jiffle_Attendee_Invitee__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Engagements_Events__c</fullName>
        <label>Customer Engagements &amp; Events</label>
        <referenceTo>CEE__c</referenceTo>
        <relationshipName>Jiffle_Attendees_Invitees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <formula>Jiffle_Session_Meeting__r.End_Date_Time__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Jiffle_Meeting_Location__c</fullName>
        <formula>Jiffle_Session_Meeting__r.Jiffle_Meeting_Location__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Jiffle Meeting Location</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Jiffle_Session_Meeting__c</fullName>
        <label>Salesforce Meeting ID</label>
        <referenceTo>Jiffle_Meeting_Session__c</referenceTo>
        <relationshipName>CEE_Jiffle_Invites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Meeting_Type__c</fullName>
        <formula>Jiffle_Session_Meeting__r.Meeting_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Meeting Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <formula>IF(Customer_Engagements_Events__r.Opportunity__c="","No Related Opportunity",HYPERLINK("/"&amp;Customer_Engagements_Events__r.Opportunity__c, Customer_Engagements_Events__r.Opportunity__r.Name, "_parent"))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Jiffle_Attendees_Invitees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requestor_Email__c</fullName>
        <label>Requestor Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <formula>Jiffle_Session_Meeting__r.Start_Date_Time__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start_Date_Time</label>
        <type>DateTime</type>
    </fields>
    <label>JiffleNow Attendee</label>
    <nameField>
        <displayFormat>JF-{0000000}</displayFormat>
        <label>JiffleNow Invite Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JiffleNow Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Jiffle_Event__c.object
<CustomObject>
    <fields>
        <fullName>Event_UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Event UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Global Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Global Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Jiffle_Meeting_Session__c.object
<CustomObject>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <defaultValue>DATETIMEVALUE(Today()+11)</defaultValue>
        <inlineHelpText>Shown in User's Local Timezone</inlineHelpText>
        <label>End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>External_Edit_URL__c</fullName>
        <label>External Edit URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Jiffle_Agenda_Item__c</fullName>
        <label>JiffleNow Agenda Item</label>
        <referenceTo>Jiffle_Agenda_Item__c</referenceTo>
        <relationshipLabel>JiffleNow Meeting</relationshipLabel>
        <relationshipName>Jiffle_Meetings_Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Jiffle_Meeting_Location__c</fullName>
        <label>Jiffle Meeting Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Meeting_Type__c</fullName>
        <description>This field is to store Meeting Type of the Jiffle Meeting record</description>
        <label>Meeting Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <description>Briefing Request Status</description>
        <inlineHelpText>Current stage of a briefing request</inlineHelpText>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <defaultValue>DATETIMEVALUE(Today() + 10)</defaultValue>
        <inlineHelpText>Shown in User's Local Timezone</inlineHelpText>
        <label>Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <label>JiffleNow Meeting</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Salesforce Meeting Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JiffleNow Meeting</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Org_Constant_CS__c.object
<CustomObject>
    <fields>
        <fullName>Non_Production_Value__c</fullName>
        <label>Non Production Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Production_Value__c</fullName>
        <label>Production Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>Org Constant CS</label>
</CustomObject>

objects/Topic__c.object
<CustomObject>
    <label>CEE Topic</label>
    <nameField>
        <label>Topic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CEE Topics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/JiffleNowMeetingSchedular_CTE.cls
/************************************************************************************************************************************
Name    : JiffleNowMeetingSchedular_CTE
Author  : Mukesh Srivastava
Purpose : This class is a controller extension for initiating JiffleMeeting and 
            1) Making sure only visibile and active opportunity list is shown the user for scheduling the meeting
            2) Pursing Parameters from different initiation points where Jiffle Meeting can be Initiated
            3) 
Created Date: 4/15/2015
Modification History: 
[7/27/2015] Awnish: Added a logic to fetch the Help Guide Image - PBI000000051759
*************************************************************************************************************************************/
public with sharing class JiffleNowMeetingSchedular_CTE {
    // Declaring Variables
    public List < Jiffle_Meeting_Session__c > lstMeetingSession {get;set;}
    public CEE__c CEENew {get;set;}
    public String selectedCEE {get;set;}
    public String selectedOppty {get;set;}
    public Boolean eMode {get;set;}
    public String CEEId;
    public String eventId;
    public String eId;
    public String accountId;
    public String opptyId;
    public String opptyName;
    public String returnURL;
    public ApexPages.StandardSetController jiffleCEESession {get;set;}
    public Integer size {get;set;}
    public Integer noOfRecords {get;set;}
    public Id idOfJiffleRec {get;set;}
    public string sessionEditId {get;set;}

    //@ Constructor to process all the parameter from different scenarios
    public JiffleNowMeetingSchedular_CTE(ApexPages.StandardController controller) {
        CEENew = new CEE__c(); //Initiazing New CEE record
        idOfJiffleRec = Schema.SObjectType.CEE__c.getRecordTypeInfosByName().get('Jifflenow (Event, Tradeshow, Conference)').getRecordTypeId();
        // Collecting all the parameters
        CEEId = ApexPages.currentPage().getParameters().get('id');
        eventId = ApexPages.currentPage().getParameters().get('eventId');
        accountId = ApexPages.currentPage().getParameters().get('accId');
        opptyId = ApexPages.currentPage().getParameters().get('opptyId');
        opptyName = ApexPages.currentPage().getParameters().get('opptyName');
        eId = ApexPages.currentPage().getParameters().get('eId');
        returnURL = ApexPages.currentPage().getParameters().get('retURL');
        sessionEditId = '#'+ ApexPages.currentPage().getParameters().get('sessionId');
        size = 5;
        // When Users are redirected from JiffleNow or User is creating new meeting from Event list page or from Event detailed page
        if (eventId != null) {
            createMeetingFromEvent();
        } else If(eId != null) {
            CEENew.Jiffle_Event__c = eId;            
        }

        // When User has initiated from Account
        if (accountId != null) {
            CEENew.Primary_Account__c = accountId;
        }
        
        // When User has initiated from Opportunity
        if (opptyId != null) {
            createMeetingFromOppty();
        }
        
        //When User want to edit the Engagement
        if (CEEId != NULL) {
            editMeeting();
        }
    }

    //@ Method Set the value of Jiffle Event received from URL Parameter when initiated from Event
    public void createMeetingFromEvent() {
        CEENew.Jiffle_Event__c = [Select Id from Jiffle_Event__c where Event_UUID__c = : eventId limit 1].Id;
        CEENew.Primary_Account__c = null;
    }

    //@ Method Set the value of Oppoty and Account received from URL Parameter when initiated from Opportunity
    public void createMeetingFromOppty() {
            if (opptyName == null) {
                Opportunity opObj = [Select Name, AccountId,Opportunity_Status__c from Opportunity where Id = : opptyId LIMIT 1];
                Id opId = opptyId;
                if(opObj.Opportunity_Status__c == 'Active'){
                    selectedOppty = opId + opObj.Name;
                }else{
                    ApexPages.Message msg = new Apexpages.Message(ApexPages.Severity.Info, System.Label.NonActiveOpportunityMessage);
                    ApexPages.addmessage(msg);  
                }
                CEENew.Primary_Account__c = opObj.AccountId;
            } else {
                selectedOppty = opptyId + opptyName;
            }
        }
        
    //@ Method Get the list of meetings/Sessions scheduled for under scoped engagement       
    public void editMeeting() {
        eMode = true;       
        Set < Id > setMeetingSession = new Set < Id > ();
        for (Jiffle_Attendee_Invitee__c jAIObj: [Select Jiffle_Session_Meeting__c, Requestor_Email__c from Jiffle_Attendee_Invitee__c 
                                                    Where Customer_Engagements_Events__c = : CEEId AND Requestor_Email__c =: UserInfo.getUserEmail()]) {
            setMeetingSession.add(jAIObj.Jiffle_Session_Meeting__c);
        }
        lstMeetingSession = [Select Id, End_Date_Time__c, External_Edit_URL__c, Name, Jiffle_Meeting_Location__c, Meeting_Type__c, 
                                Request_Status__c, Start_Date_Time__c, Jiffle_Agenda_Item__c,Jiffle_Agenda_Item__r.Topic__c from Jiffle_Meeting_Session__c 
                                Where Id IN: setMeetingSession Order by Start_Date_Time__c DESC];        
        jiffleCEESession = new ApexPages.StandardSetController(lstMeetingSession);
        noOfRecords = jiffleCEESession.getResultSize();        
    }
    
    public List<Jiffle_Meeting_Session__c> getCEESessions() {
        jiffleCEESession.setPageSize(size);
        return (List<Jiffle_Meeting_Session__c>) jiffleCEESession.getRecords();
    }
    
    //@ Method Reading the account selected by user called by action support
    public pageReference readAccount() {
        getOppties();
        return null;
    }
    
    //@ Method Cancel the Operation and return to ReturnURL if any
    public pageReference cmdCancel() {
        PageReference pageRef = new PageReference(returnURL);
        pageRef.setRedirect(true);
        return pageRef;
    }
    
     //@ Method to fetch the help guide image link from document
    public String getHelpGuideImageLink(){   
       Org_Constant_CS__c jnOrgCS = Org_Constant_CS__c.getValues('JiffleNowHelpGuideImageURL');
       String helpGuideURL = jnOrgCS.Production_Value__c;
        Organization org = [Select Id, IsSandbox FROM Organization limit 1];
        if(org.IsSandbox == TRUE){
            helpGuideURL = jnOrgCS.Non_Production_Value__c;
        }
         return helpGuideURL ;
    }

    //@ Method reset the page when user is in Edit mode
    public pageReference submitNewRequest() {
        return null;
    }
    
    //@ Method to find out production and sandbox URLs
    public String getJiffleURL(){        
        Org_Constant_CS__c jnOrgCS = Org_Constant_CS__c.getValues('JiffleNowInstanceURL');        
        String strJiffleURL = jnOrgCS.Production_Value__c;
        
        Organization org = [Select Id, IsSandbox FROM Organization limit 1];
        if(org.IsSandbox == TRUE){
            strJiffleURL = jnOrgCS.Non_Production_Value__c;
        }
        return strJiffleURL;
    }

    //@ Method Creating Opportunity list of options
    public List < SelectOption > getOppties() {
        List < SelectOption > options = new List < SelectOption > ();

        //Add blank and default option to display when the page loads.
        options.add(new SelectOption(' ', 'Select an Opportunity'));
        options.add(new SelectOption('000000000000012345No Related Opportunity', 'No Related Opportunity'));

        //Create list of all the active opportunities associated to account selected for meeting with value as combination of Opportunity Id and Opportunity Name
        List < Opportunity > lstOppty;
        if (CEEId != NULL) {
            List < CEE__c > CEEExisting = [Select Id, Primary_Account__c, Opportunity__c, Opportunity__r.Name from CEE__c where Id = : CEEId Limit 1];
            selectedCEE = CEEExisting[0].Opportunity__c + CEEExisting[0].Opportunity__r.Name;
            lstOppty = new List < Opportunity > ([SELECT Id, Name FROM Opportunity Where AccountId = : CEEExisting[0].Primary_Account__c AND Opportunity_Status__c = 'Active'
                ORDER BY Name ASC
            ]);
        } else {
            system.debug('sss'+CEENew.Primary_account__c);
            if(CEENew.Primary_Account__c != NULL){
                lstOppty = new List < Opportunity > ([SELECT Id, Name FROM Opportunity Where AccountId = : CEENew.Primary_Account__c AND Opportunity_Status__c = 'Active'
                    ORDER BY Name ASC
                ]);
            }
        }
        // Setting the list of Options
        if(lstOppty != NULL){
            for (Opportunity oObj: lstOppty) {
                options.add(new SelectOption(oObj.Id + oObj.Name, oObj.Name));
            }
            
            //reseting selected value when user changed account
            if(lstOppty.size()>0){
                selectedOppty = '';            
            }else{
                selectedOppty = '000000000000012345No Related Opportunity';
            }
        }        
        return options;
    }
}