objects/CEE__c.object
<CustomObject>
    <fields>
        <fullName>Post_Engagement_Message_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A flag for a workflow/trigger combo to check whether the trigger has been fired already.</description>
        <label>Post Engagement Message Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Engagements &amp; Events</relationshipLabel>
        <relationshipName>Primary_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Primary_FSO__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Primary site is lookup field from CEE Location object, it is related to CPOC lab request.</description>
        <inlineHelpText>Field Sales Office</inlineHelpText>
        <label>Primary Site</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4 AND 6) OR (5)</booleanFilter>
            <errorMessage>The chosen Primary Site does not match the filter criteria of the EBC/EC and Other/FSO Location field.</errorMessage>
            <filterItems>
                <field>$Source.EBC_CBC_Location__c</field>
                <operation>equals</operation>
                <valueField>CEE_Location__c.Name</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.EBC_CBC_Location__c</field>
                <operation>notEqual</operation>
                <value>Other/FSO</value>
            </filterItems>
            <filterItems>
                <field>$Source.EBC_CBC_Location__c</field>
                <operation>equals</operation>
                <value>Other/FSO</value>
            </filterItems>
            <filterItems>
                <field>CEE_Location__c.Is_Location_Active__c</field>
                <operation>equals</operation>
                <value>Yes</value>
            </filterItems>
            <filterItems>
                <field>$User.Id</field>
                <operation>equals</operation>
                <value>005300000010pIr</value>
            </filterItems>
            <filterItems>
                <field>CEE_Location__c.Name</field>
                <operation>notContain</operation>
                <value>CPOC</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CEE_Location__c</referenceTo>
        <relationshipLabel>Customer Engagements &amp; Events (Primary Site)</relationshipLabel>
        <relationshipName>Customer_Engagement_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <description>Briefing Request Status and it is related to CPOC lab request.</description>
        <inlineHelpText>Current stage of an Engagement Request</inlineHelpText>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Returned (all resources released)</fullName>
                </value>
                <value>
                    <fullName>Cancelled (all resources released)</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Saved, not Submitted</fullName>
                </value>
                <value>
                    <fullName>Assigned to PM</fullName>
                </value>
                <value>
                    <fullName>Submitted by Requester</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Lab Redirect</fullName>
                </value>
                <value>
                    <fullName>Returned by Scheduler</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Timezone__c</fullName>
        <description>Timezone picklist field (primarily for ITCE engagements)</description>
        <label>Timezone</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>(UTC-11:00) Samoa Standard Time (Pacific/Pago_Pago)</fullName>
                </value>
                <value>
                    <fullName>(UTC-11:00) Niue Time (Pacific/Niue)</fullName>
                </value>
                <value>
                    <fullName>(UTC-10:00) Hawaii-Aleutian Standard Time (America/Atka)</fullName>
                </value>
                <value>
                    <fullName>(UTC-10:00) Hawaii Standard Time (Pacific/Honolulu)</fullName>
                </value>
                <value>
                    <fullName>(UTC-09:30) Marquesas Time (Pacific/Marquesas)</fullName>
                </value>
                <value>
                    <fullName>(UTC-09:00) Gambier Time (Pacific/Gambier)</fullName>
                </value>
                <value>
                    <fullName>(UTC-09:00) Alaska Daylight Time (America/Anchorage)</fullName>
                </value>
                <value>
                    <fullName>(UTC-08:00) Pitcairn Standard Time (Pacific/Pitcairn)</fullName>
                </value>
                <value>
                    <fullName>(UTC-08:00) Pacific Standard Time (America/Tijuana)</fullName>
                </value>
                <value>
                    <fullName>(UTC-08:00) Pacific Daylight Time (America/Los_Angeles)</fullName>
                </value>
                <value>
                    <fullName>(UTC-07:00) Mountain Standard Time (Mexico/BajaSur)</fullName>
                </value>
                <value>
                    <fullName>(UTC-07:00) Mountain Standard Time (America/Phoenix)</fullName>
                </value>
                <value>
                    <fullName>(UTC-07:00) Mountain Daylight Time (America/Denver)</fullName>
                </value>
                <value>
                    <fullName>(UTC-06:00) Central Standard Time (America/Mexico_City)</fullName>
                </value>
                <value>
                    <fullName>(UTC-06:00) Central Standard Time (America/El_Salvador)</fullName>
                </value>
                <value>
                    <fullName>(UTC-06:00) Central Daylight Time (America/Chicago)</fullName>
                </value>
                <value>
                    <fullName>(UTC-05:00) Eastern Standard Time (America/Panama)</fullName>
                </value>
                <value>
                    <fullName>(UTC-05:00) Eastern Daylight Time (America/New_York)</fullName>
                </value>
                <value>
                    <fullName>(UTC-05:00) Peru Time (America/Lima)</fullName>
                </value>
                <value>
                    <fullName>(UTC-05:00) Eastern Daylight Time (America/Indianapolis)</fullName>
                </value>
                <value>
                    <fullName>(UTC-05:00) Colombia Time (America/Bogota)</fullName>
                </value>
                <value>
                    <fullName>(UTC-04:30) Venezuela Time (America/Caracas)</fullName>
                </value>
                <value>
                    <fullName>(UTC-04:00) Atlantic Daylight Time (Atlantic/Bermuda)</fullName>
                </value>
                <value>
                    <fullName>(UTC-04:00) Chile Summer Time (America/Santiago)</fullName>
                </value>
                <value>
                    <fullName>(UTC-04:00) Atlantic Standard Time (America/Puerto_Rico)</fullName>
                </value>
                <value>
                    <fullName>(UTC-04:00) Atlantic Daylight Time (America/Halifax)</fullName>
                </value>
                <value>
                    <fullName>(UTC-03:30) Newfoundland Daylight Time (America/St_Johns)</fullName>
                </value>
                <value>
                    <fullName>(UTC-03:00) Brasilia Summer Time (America/Sao_Paulo)</fullName>
                </value>
                <value>
                    <fullName>(UTC-03:00) Argentine Summer Time (America/Buenos_Aires)</fullName>
                </value>
                <value>
                    <fullName>(UTC-02:00) South Georgia Standard Time (Atlantic/South_Georgia)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>emailHasNotBeenSent__c</fullName>
        <defaultValue>true</defaultValue>
        <description>flag to prevent duplicate emails in trigger "CEESendPresenterPostEngagementNotes"</description>
        <label>emailHasNotBeenSent</label>
        <type>Checkbox</type>
    </fields>
    <description>This object will store summary level briefing information from CEE. This Object is created to Integrate CEE Applicaiton data with Salesforce.com. It allows users to link CEE Briefings with Accounts in Salesforce.com.</description>
    <label>Customer Engagements &amp; Events</label>
    <nameField>
        <displayFormat>CEE-{000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Engagements &amp; Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>OBX</fullName>
        <active>true</active>
        <description>Delivering Demonstrations, Briefings, and Events</description>
        <label>Outcome Based Experience (OBX - formerly EBC)</label>
    </recordTypes>
</CustomObject>

objects/CEE_Location__c.object
<CustomObject>
    <description>The location details for a given Location, either a Field Sales Office (FSO), Executive Briefing Center (EBC), or Customer Briefing Center provided as part of the Customer Engagement implementation.</description>
    <label>CEE Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CEE Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CEESendPresenterPostEngagementNotes_Test.cls
/***************************************************************************************************
Name    : CEESendPresenterPostEngagementNotes_Test 
Author  : Brian Mansfield
Purpose : Test for sending a Presenter post-engagement  
Created Date: Dec 1 2014
Modification History: 
Eric Pesch - Jan 5 2015: Added Comments, cleanup    
Jay Dash - Aug 8 2015 : Added getOpty()                   
*****************************************************************************************************/

@isTest
public class CEESendPresenterPostEngagementNotes_Test {

    /*@method: Testing OBX post-engagement note*/       
    static testMethod void obx (){
        User admin = CEE_TestUtility.getUser('admin', true);
        
        Account testAcct;
        System.runAs(admin){
            CEE_TestUtility.loadCustomSettings();
            testAcct = CEE_TestUtility.getAccount('cee', true);
            // prefix
        }
        
        Opportunity testOpt = null;
        Opportunity opppt =  CEE_TestUtility.getOpty();
        CEE_Location__c testLoc = CEE_TestUtility.getLocation('cee', true, 'EBC/EC');
        CEE__c testCEEOBX = CEE_TestUtility.getBriefing('cee', true, 'OBX', testAcct, opppt, testLoc);

        testCEEOBX.Primary_Account__c = testAcct.id;
        testCEEOBX.Post_Engagement_Message_Sent__c = true;
        testCEEOBX.emailHasNotBeenSent__c = true;
        testCEEOBX.Request_Status__c = 'Confirmed';
        update testCEEOBX;
    }
    
    /*@method: Testing ITCE post-engagement note*/
    static testMethod void itce (){
        User admin = CEE_TestUtility.getUser('admin', true);
        
        Account testAcct2;
        System.runAs(admin){
            CEE_TestUtility.loadCustomSettings();
            testAcct2 = CEE_TestUtility.getAccount('cee2', true);
        }
        
        Opportunity testOpt = null;
        Opportunity opppt =  CEE_TestUtility.getOpty();
        CEE_Location__c testLoc = CEE_TestUtility.getLocation('cee2', true, 'EBC/EC');
        
        CEE__c testCEEITCE = CEE_TestUtility.getBriefing('cee2', false, 'Upcoming_ITCE_Briefing', testAcct2, opppt, testLoc);
        testCEEITCE.Primary_FSO__c = null;
        testCEEITCE.Timezone__c = 'UTC-05:00';
        testCEEITCE.Post_Engagement_Message_Sent__c = true;
        testCEEITCE.emailHasNotBeenSent__c = true;
        testCEEITCE.Request_Status__c = 'Confirmed';
        
        insert testCEEITCE;
    }
}