objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ContactPermissionCall__c</fullName>
        <description>Indicates if Cisco can call the contact or not</description>
        <label>Contact Permission-Call</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PreferredLanguage__c</fullName>
        <description>Language Preferred  by the contact</description>
        <label>Preferred Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Afrikaans</fullName>
                </value>
                <value>
                    <fullName>Arabic (Saudi Arabia)</fullName>
                </value>
                <value>
                    <fullName>Bahasa</fullName>
                </value>
                <value>
                    <fullName>Bulgarian</fullName>
                </value>
                <value>
                    <fullName>Catalan</fullName>
                </value>
                <value>
                    <fullName>Chinese (Simplified)</fullName>
                </value>
                <value>
                    <fullName>Chinese (Traditional)</fullName>
                </value>
                <value>
                    <fullName>Croatian</fullName>
                </value>
                <value>
                    <fullName>Czech</fullName>
                </value>
                <value>
                    <fullName>Danish</fullName>
                </value>
                <value>
                    <fullName>Dutch</fullName>
                </value>
                <value>
                    <fullName>English</fullName>
                </value>
                <value>
                    <fullName>Estonian</fullName>
                </value>
                <value>
                    <fullName>Faroese</fullName>
                </value>
                <value>
                    <fullName>Finnish</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Greek</fullName>
                </value>
                <value>
                    <fullName>Hebrew</fullName>
                </value>
                <value>
                    <fullName>Hungarian</fullName>
                </value>
                <value>
                    <fullName>Icelandic</fullName>
                </value>
                <value>
                    <fullName>Indonesian</fullName>
                </value>
                <value>
                    <fullName>Irish</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Latvian</fullName>
                </value>
                <value>
                    <fullName>Lithuanian</fullName>
                </value>
                <value>
                    <fullName>Macedonian</fullName>
                </value>
                <value>
                    <fullName>Norwegian</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <description>Lead Address Line 1</description>
        <label>Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Call_Permission__c</fullName>
        <description>NGCC Phase1:Permission to call for marketing offers/promotion</description>
        <label>Call Permission</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_Department__c</fullName>
        <description>Department of the contact</description>
        <label>Contact Department</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomCity__c</fullName>
        <description>Lead Address City</description>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomCountry__c</fullName>
        <description>Lead Address Country</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALAND ISLANDS</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BONAIRE, SINT EUSTATIUS AND SABA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CustomState__c</fullName>
        <description>Lead Address State/Province</description>
        <label>State/Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomZip__c</fullName>
        <description>Lead Address Zip/Postal Code</description>
        <label>Zip/Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>NGCC Phase1:Prospect associated to existing SFDC Contacts</description>
        <label>Sales Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Leads (Lead Contact)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Preferred_Language__c</fullName>
        <description>NGCC Phase1:Preferred language of the customer</description>
        <label>Preferred Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Danish: da</fullName>
                </value>
                <value>
                    <fullName>Dutch: nl_NL</fullName>
                </value>
                <value>
                    <fullName>English: en_US</fullName>
                </value>
                <value>
                    <fullName>Finnish: fi</fullName>
                </value>
                <value>
                    <fullName>French: fr</fullName>
                </value>
                <value>
                    <fullName>German: de</fullName>
                </value>
                <value>
                    <fullName>Italian: it</fullName>
                </value>
                <value>
                    <fullName>Japanese: ja</fullName>
                </value>
                <value>
                    <fullName>Korean: ko</fullName>
                </value>
                <value>
                    <fullName>Portuguese (Brazil): pt_BR</fullName>
                </value>
                <value>
                    <fullName>Russian: ru</fullName>
                </value>
                <value>
                    <fullName>Spanish: es</fullName>
                </value>
                <value>
                    <fullName>Swedish: sv</fullName>
                </value>
                <value>
                    <fullName>Thai: th</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <businessProcess>NGCC Marketing Lead</businessProcess>
        <description>Prospect Leads from Next Gen Marketing Contact Center</description>
        <label>Prospect</label>
    </recordTypes>
</CustomObject>

classes/NGCC_UpdateLeadContactInfo.cls
/*********************************************************************************************
Name    : NGCC_UpdateLeadContactInfo 
Author  : Bapu Rao Srigadde
Purpose : To update the contact information on Lead
Created Date: 06/12/2014
Modification History: 
Modified date: Added mobile field -Bapu
*********************************************************************************************/

global class NGCC_UpdateLeadContactInfo implements Database.Batchable<Sobject> 
{

 // SCAVA Helper Method
     public static Boolean flsGet(SObjectField field)
    {
        return field.getDescribe().isCreateable() ? true : false;
    }
    
    // SCAVA Helper Method to validate Update Access at field level
     public static Boolean flsUpdateGet(SObjectField field)
    {
        return field.getDescribe().isUpdateable() ? true : false;
    }

global Database.QueryLocator start(Database.BatchableContext BC) 
    {
    Profile objProfile = [select id, name from Profile where name =:'Cisco_NGCC'];
    set<Id> userId = new set<Id>();
    list<User> lstUser = [Select id, name,ProfileId from User Where ProfileId =: objProfile.Id ];
    
    for(User objUser : lstUser){
            userId.add(objUser.Id);
    }
    string strRecordTypeId = 
    Schema.Sobjecttype.Lead.getRecordTypeInfosByName().get('Prospect').getRecordTypeId();
 String StrQuery='Select id,name,Title,Phone,MobilePhone,Call_Permission__c,Contact_Department__c,Email, Preferred_Language__c,Company,Lead_Contact__c,Address_Line_1__c,'
     +'CustomCity__c,CustomState__c,CustomCountry__c,CustomZip__c, FirstName, LastName '
     +'from lead where Lead_Contact__c != null and RecordTypeId =:strRecordTypeId and LastModifiedById IN:userId and LastModifiedDate = TODAY AND HOUR_IN_DAY(LastModifiedDate) > 1';
    
    //Added condition to ensure that the batch job running in test will only process less than 200 records.  Current test classes for the NGCC are setup for seealldata=true
    //This is a temp fix.  Final fix is update the NGCC test classes as seealldata=false
    if( Test.isRunningTest() ){
        StrQuery += ' limit 180'; 
    }
        
   return Database.getQueryLocator(StrQuery);
    }
      
    global list<Contact> contactDetails(list<Lead> lstExactLead){
     list<Contact> lstContact = new list<Contact>();
     list<Contact> lstContact1 = new list<Contact>();
     Set<String> contactID = new Set<String>();
     map<id,lead> mapLead = new map<id,lead>();
     for(Lead objLead : lstExactLead){
      contactID.add(objLead.Lead_Contact__c);
      mapLead.put(objLead.Lead_Contact__c,objLead);
     }
     lstContact = [Select id,name,FirstName, LastName,Title,Phone, MobilePhone ,ContactPermissionCall__c,Email, Department,PreferredLanguage__c from Contact where id IN :contactID];
          //MailingAddress,OtherAddress
          system.debug('before==='+lstContact);
      for(Contact objContact : lstContact){
          Lead objLead = mapLead.get(objContact.Id);
          //SCAVA
          if(flsGet(Contact.FirstName)||flsUpdateGet(Contact.FirstName)){ 
          objContact.FirstName = objLead.FirstName;
          }
          if(flsGet(Contact.LastName)||flsUpdateGet(Contact.LastName)){ 
          objContact.LastName = objLead.LastName;  
          }
          if(flsGet(Contact.Email)||flsUpdateGet(Contact.Email)){ 
          objContact.Email = objLead.Email;
          }
          if(flsGet(Contact.Title)||flsUpdateGet(Contact.Title)){ 
          objContact.Title = objLead.Title;
          }
          if(flsGet(Contact.Department)||flsUpdateGet(Contact.Department)){ 
          objContact.Department = objLead.Contact_Department__c;
          }
          if(flsGet(Contact.Phone)||flsUpdateGet(Contact.Phone)){ 
          objContact.Phone = objLead.Phone;
          }
          if(flsGet(Contact.MobilePhone)||flsUpdateGet(Contact.MobilePhone)){ 
          objContact.MobilePhone = objLead.MobilePhone; 
          }
          if(flsGet(Contact.ContactPermissionCall__c)||flsUpdateGet(Contact.ContactPermissionCall__c)){ 
          objContact.ContactPermissionCall__c = objLead.Call_Permission__c;
          }
          if(flsGet(Contact.Email)||flsUpdateGet(Contact.Email)){ 
          objContact.Email = objLead.Email;
          }
          if(flsGet(Contact.PreferredLanguage__c)||flsUpdateGet(Contact.PreferredLanguage__c)){ 
          objContact.PreferredLanguage__c = objLead.Preferred_Language__c;
          }
          if(flsGet(Contact.MailingCity)||flsUpdateGet(Contact.MailingCity)){ 
          objContact.MailingCity = objLead.CustomCity__c;
          }
          if(flsGet(Contact.MailingCountry)||flsUpdateGet(Contact.MailingCountry)){ 
          objContact.MailingCountry = objLead.CustomCountry__c;
          }
          if(flsGet(Contact.MailingStreet)||flsUpdateGet(Contact.MailingStreet)){ 
          objContact.MailingStreet = objLead.Address_Line_1__c;
          }
          if(flsGet(Contact.MailingState)||flsUpdateGet(Contact.MailingState)){ 
          objContact.MailingState = objLead.CustomState__c;
          }
          if(flsGet(Contact.MailingPostalcode)||flsUpdateGet(Contact.MailingPostalcode)){ 
          objContact.MailingPostalcode = objLead.CustomZip__c;
          }//SCAVA
          lstContact1.add(objContact);
          
      }
     return lstContact1;
    }
    
    global void execute(Database.BatchableContext BC, list<sObject> scope)
    {
     try
  {
   list<Contact> leadContacts = new list<Contact>();
   list<Lead> lstLead = new list<Lead>();

   lstLead = (list<Lead>)scope;
      system.debug('**********************'+lstLead);
   leadContacts = contactDetails(lstLead);
   system.debug('leadContacts==='+leadContacts);
   update leadContacts;
   system.debug('leadContacts==='+leadContacts);
  }
  catch(Exception exc)
  {
   System.debug('***Exception in execute***'+ exc); 
  }
 }
      
    global void finish(Database.BatchableContext BC)
    {
     try
     {
         
     }
     catch(Exception exc)
     {
      System.debug('***Exception in finish'+exc); 
   }
 }
}