objects/CRMDB__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name_Value__c</fullName>
        <formula>Account_Name__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account_Name_Value</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master customer linked to customer contract.</description>
        <inlineHelpText>Matches P&amp;L Customer Name</inlineHelpText>
        <label>Master Customer Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CRMDB</relationshipLabel>
        <relationshipName>Customer_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_State__c</fullName>
        <description>Select from Green, Yellow, Red (see AUSE process)</description>
        <inlineHelpText>Select from Green, Yellow, Red (see Executive Summary Process)</inlineHelpText>
        <label>Account State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Red</fullName>
                    <color>#FF0000</color>
                    <label>Red</label>
                </value>
                <value>
                    <fullName>Yellow</fullName>
                    <color>#FFFF66</color>
                    <label>Yellow</label>
                </value>
                <value>
                    <fullName>Green</fullName>
                    <color>#33FF33</color>
                    <label>Green</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Active_Customer__c</fullName>
        <description>Is this customer live (Day 2)?</description>
        <inlineHelpText>Is this customer live (Day 2)? Drop down options:  
Yes
Yes-pending disconnect
No-disconnected
No-pending activation"</inlineHelpText>
        <label>Active Contract</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>Yes-pending disconnect</fullName>
                </value>
                <value>
                    <fullName>No-disconnected</fullName>
                    <label>No-disconnected (No longer a CMS Customer)</label>
                </value>
                <value>
                    <fullName>No – Contract Expired (Other Active CMS Contracts)</fullName>
                </value>
                <value>
                    <fullName>No-pending activation</fullName>
                </value>
                <value>
                    <fullName>No-disconnected (No longer a CMS Customer)</fullName>
                    <isActive>false</isActive>
                    <label>No-disconnected (No longer a CMS Customer)</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_CAP_caused_by_CMS__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is CAP caused by CMS</description>
        <inlineHelpText>Y/N</inlineHelpText>
        <label>Is CAP caused by CMS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Customer_on_CAP__c</fullName>
        <description>Is Customer on CAP</description>
        <inlineHelpText>If Customer is NOT on CAP select No in the drop down. If the Customer is on CAP select appropriate CAP type and save. Then complete All fields in the CAP Management Section.</inlineHelpText>
        <label>Is Customer on CAP</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
                <value>
                    <fullName>CAP - A</fullName>
                </value>
                <value>
                    <fullName>CAP - B</fullName>
                </value>
                <value>
                    <fullName>CAP - M</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <description>Name of SDM direct Manager, or assigned Manager, for the informational and modelling purposes.</description>
        <label>Manager</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Master_Customer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent of customer contract</description>
        <label>Parent Customer Contract</label>
        <referenceTo>CRMDB__c</referenceTo>
        <relationshipLabel>Child Customer Contracts</relationshipLabel>
        <relationshipName>CRMDB_Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SDM_Assigned__c</fullName>
        <description>Name of the SDM assigned (only one name allowed).  </description>
        <inlineHelpText>Name of the SDM assigned (only one name allowed, additional SDMs should be added to the Contacts Field)</inlineHelpText>
        <label>SDM Lead</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Theater__c</fullName>
        <description>CET Theater</description>
        <inlineHelpText>CET Theater</inlineHelpText>
        <label>Theater</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>APJC</fullName>
                </value>
                <value>
                    <fullName>EMEAR</fullName>
                </value>
                <value>
                    <fullName>AMER</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_CMS_Contract_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Loaded from  Booked Qualification in a Child Record, Summed from Child record(s) to a Parent.</description>
        <inlineHelpText>Loaded from  Booked Qualification in a Child Record, Summed from Child record(s) to a Parent.</inlineHelpText>
        <label>Total CMS Contract Value($000)</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <description>Data of customer information, customer sentiment, renewal date, financial information, what is important for customer etc. Each customer may have multiple contracts, which are managed separately. About 70 SDMs input the data and additional ~100 others use it. In total about 200 users. Used as user input form and only authorized users can access it. Data is populated manually by SDMs and DB Admin.</description>
    <label>CRMDB</label>
    <nameField>
        <label>Customer Contract</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRMDB</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CRMDBContractHierarchyClass.cls
public with sharing class CRMDBContractHierarchyClass {

    @AuraEnabled
    public static List<CRMDB__c> getCrmdbList() {
        //Fetch data
        System.debug('>>Shivi');
        return [SELECT ID,Name,Account_Name_Value__c,Account_Name__c,Active_Customer__c,
                Is_CAP_caused_by_CMS__c,Is_Customer_on_CAP__c,Manager__c,
                SDM_Assigned__c,Theater__c,Account_State__c,Total_CMS_Contract_Value__c,(SELECT ID,Name,Account_Name__c,Account_Name_Value__c,
                Active_Customer__c,Is_CAP_caused_by_CMS__c,Is_Customer_on_CAP__c,Manager__c,
                SDM_Assigned__c,Theater__c,Account_State__c,Total_CMS_Contract_Value__c 
                FROM CRMDB_Customers__r ORDER BY Name ASC NULLS FIRST) 
                FROM CRMDB__c WHERE Master_Customer_Name__c = null ORDER BY Name ASC NULLS FIRST];
        
    }      
    
}