objects/CRMDB__c.object
<CustomObject>
    <fields>
        <fullName>Active_Customer__c</fullName>
        <description>Is this customer live (Day 2)?</description>
        <inlineHelpText>Is this customer live (Day 2)? Drop down options:  
Yes
Yes-pending disconnect
No-disconnected
No-pending activation"</inlineHelpText>
        <label>Active Contract</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>Yes-pending disconnect</fullName>
                </value>
                <value>
                    <fullName>No-disconnected</fullName>
                    <label>No-disconnected (No longer a CMS Customer)</label>
                </value>
                <value>
                    <fullName>No – Contract Expired (Other Active CMS Contracts)</fullName>
                </value>
                <value>
                    <fullName>No-pending activation</fullName>
                </value>
                <value>
                    <fullName>No-disconnected (No longer a CMS Customer)</fullName>
                    <isActive>false</isActive>
                    <label>No-disconnected (No longer a CMS Customer)</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Annual_CMS_Contract_Value_CR_S__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Child Record is the sum of  Annual CMS Contract + Annual CRs,  Parent Record is the Sum of all Child record(s) Annual Contract+CRs.</description>
        <inlineHelpText>Child Record is the sum of  Annual CMS Contract + Annual CRs,  Parent Record is the Sum of all Child record(s) Annual Contract+CRs.</inlineHelpText>
        <label>Annual CMS Contract Value + CR(S)($000)</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Annual_CMS_Contract_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Loaded from  Booked Qualification in a Child Record, Summed from Child record(s) to a Parent.</description>
        <inlineHelpText>Loaded from  Booked Qualification in a Child Record, Summed from Child record(s) to a Parent.</inlineHelpText>
        <label>Annual CMS Contract Value($000)</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Annual_Child_CMS_CR__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Summation of child's Annual_CMS_Contract_Value_CR_S__c  value</description>
        <inlineHelpText>Child Record is the sum of Annual Contract CRs, Parent Record is the Sum of CRs for all children.</inlineHelpText>
        <label>Annual Customer CR(s) Value($000)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Brief_Summary_for_Red_Yellow_Status__c</fullName>
        <description>Provide a brief bulleted summary of Yellow or Red status</description>
        <label>Brief Summary for Yellow / Red Status</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CAP_Case_Opened_Date__c</fullName>
        <description>This is provided by the CAP manager and entered into the CRMDB by the SDM</description>
        <inlineHelpText>This is provided by the CAP manager and entered into the CRMDB by the SDM</inlineHelpText>
        <label>CAP Case Opened Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CAP_Title__c</fullName>
        <description>This is provided by the CAP manager and entered into the CRMDB by the SDM</description>
        <inlineHelpText>This is provided by the CAP manager and entered into the CRMDB by the SDM</inlineHelpText>
        <label>CAP Title</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CAP_case_Manager_Name__c</fullName>
        <description>This is provided by the CAP manager and entered into the CRMDB by the SDM</description>
        <inlineHelpText>This is provided by the CAP manager and entered into the CRMDB by the SDM</inlineHelpText>
        <label>CAP Case Manager Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CAP_case_Number_Engagement_ID__c</fullName>
        <description>This is provided by the CAP manager and entered into the CRMDB by the SDM</description>
        <inlineHelpText>This is provided by the CAP manager and entered into the CRMDB by the SDM</inlineHelpText>
        <label>CAP Case Number (Engagement ID)</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_CAP_caused_by_CMS__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is CAP caused by CMS</description>
        <inlineHelpText>Y/N</inlineHelpText>
        <label>Is CAP caused by CMS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Customer_on_CAP__c</fullName>
        <description>Is Customer on CAP</description>
        <inlineHelpText>If Customer is NOT on CAP select No in the drop down. If the Customer is on CAP select appropriate CAP type and save. Then complete All fields in the CAP Management Section.</inlineHelpText>
        <label>Is Customer on CAP</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
                <value>
                    <fullName>CAP - A</fullName>
                </value>
                <value>
                    <fullName>CAP - B</fullName>
                </value>
                <value>
                    <fullName>CAP - M</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Master_Customer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent of customer contract</description>
        <label>Parent Customer Contract</label>
        <referenceTo>CRMDB__c</referenceTo>
        <relationshipLabel>Child Customer Contracts</relationshipLabel>
        <relationshipName>CRMDB_Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason_for_Yellow_Red__c</fullName>
        <description>Check the box if the reason for the account being flagged as Yellow or Red.</description>
        <inlineHelpText>Select reason(s) for the account being flagged as Yellow or Red is caused by CMS Delivery performance</inlineHelpText>
        <label>Reason for Yellow / Red</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Delivery</fullName>
                </value>
                <value>
                    <fullName>Cisco Product</fullName>
                </value>
                <value>
                    <fullName>CMS Offer</fullName>
                </value>
                <value>
                    <fullName>Platform</fullName>
                </value>
                <value>
                    <fullName>Vendor</fullName>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Selective Transition</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_CMS_Contract_Value_CR_S__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Child Record is the sum of  Total CMS Contract + CRs,  Parent Record is the Sum of all Child record(s) Contract+CRs.</description>
        <inlineHelpText>Child Record is the sum of  Total CMS Contract + CRs,  Parent Record is the Sum of all Child record(s) Contract+CRs.</inlineHelpText>
        <label>Total CMS Contract Value + CR(S)($000)</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_CMS_Contract_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Loaded from  Booked Qualification in a Child Record, Summed from Child record(s) to a Parent.</description>
        <inlineHelpText>Loaded from  Booked Qualification in a Child Record, Summed from Child record(s) to a Parent.</inlineHelpText>
        <label>Total CMS Contract Value($000)</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Child_CMS_CR__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Summation of child's Total_CMS_Contract_Value_CR_S__c</description>
        <inlineHelpText>Child Record is the sum of Total Contract CRs,  Parent Record is the Sum of CRs for all children.</inlineHelpText>
        <label>Total Customer CR(s) Value($000)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <description>Data of customer information, customer sentiment, renewal date, financial information, what is important for customer etc. Each customer may have multiple contracts, which are managed separately. About 70 SDMs input the data and additional ~100 others use it. In total about 200 users. Used as user input form and only authorized users can access it. Data is populated manually by SDMs and DB Admin.</description>
    <label>CRMDB</label>
    <nameField>
        <label>Customer Contract</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRMDB</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CRMDB_Helper.cls
/*
Author          : Hardik S.
Release         : CMRDB Qualification and CRMDB Integration
Created         : May 17, 2019
Functionality   : Logic to do summation of Annual and Total CMS CRS 


Modification History:
Itrack#        Date        Author             Change 
US277513       5/17/2019   Kavya M            New Contract(Parent/Child) Request Automation   
US318317       6/1/2019    Awnish K.          Parent Summation should be changed when Annual/ Total CMS value on child record is edited
US318316       6/1/2019    Awnish K.          The Child contract Annual and total CR values should be editable
DE258765       6/1/2019    Awnish K.          Parent Sum twice on Active Contract change
*/
public with sharing class CRMDB_Helper{
    public static Boolean parentUpdate = false;
    public static Boolean childUpdate = false;
    
    //Updated Cap fields on the child records when Cap fields are updated on parent record.
    Public static void capFieldsUpdate(list <CRMDB__c> CRMDBList,list<CRMDB__c>oldCRMDBList){
        if(Utilities.getConstant_CS('CRMDB Trigger Skip')=='No'){
            List<CRMDB__c>childList=new List<CRMDB__C>();
            List<CRMDB__c>FinalList = new List<CRMDB__c>();
            
            if(!CRMDBList.isEmpty()){
                childList=[SELECT Is_Customer_on_CAP__c, Is_CAP_caused_by_CMS__c, CAP_Title__c, CAP_Case_Opened_Date__c, CAP_case_Number_Engagement_ID__c,
                           CAP_case_Manager_Name__c,Brief_Summary_for_Red_Yellow_Status__c,Master_Customer_Name__c FROM CRMDB__c WHERE Master_Customer_Name__c IN:CRMDBList];
            }
            if(!childList.isEmpty()){
                for(CRMDB__c CRMDB :childList){
                    for(CRMDB__c c:CRMDBList){
                        if(CRMDB.Master_Customer_Name__c== c.id){
                            CRMDB.Is_Customer_on_CAP__c=c.Is_Customer_on_CAP__c;
                            CRMDB.Is_CAP_caused_by_CMS__c=c.Is_CAP_caused_by_CMS__c;
                            CRMDB.CAP_Title__c=c.CAP_Title__c;
                            CRMDB.CAP_Case_Opened_Date__c=c.CAP_Case_Opened_Date__c;
                            CRMDB.CAP_case_Number_Engagement_ID__c=c.CAP_case_Number_Engagement_ID__c;
                            CRMDB.CAP_case_Manager_Name__c=c.CAP_case_Manager_Name__c;
                            CRMDB.Brief_Summary_for_Red_Yellow_Status__c=c.Brief_Summary_for_Red_Yellow_Status__c;
                            CRMDB.Reason_for_Yellow_Red__c=c.Reason_for_Yellow_Red__c; 
                            FinalList.add(CRMDB);
                        }   
                        
                    } 
                }
            }
            if(!FinalList.isEmpty()){
                parentUpdate=true;
                Update FinalList;
            }
        }
    }
    
    //Update Total and Annual CMS CRs field when Total and Annual CMS fields are updated
    public static void totalandAnnualContractUpdate(Map<Id,CRMDB__c>oldRecMap,List<CRMDB__c>newRecList){
        if(Utilities.getConstant_CS('CRMDB Trigger Skip')=='No'){
            for(CRMDB__c crmdbChild : newRecList){
                if((crmdbChild.Annual_Child_CMS_CR__c!= oldRecMap.get(crmdbChild.Id).Annual_Child_CMS_CR__c || crmdbChild.Annual_CMS_Contract_Value__c  != oldRecMap.get(crmdbChild.Id).Annual_CMS_Contract_Value__c) ){
                    crmdbChild.Annual_CMS_Contract_Value_CR_S__c = crmdbChild.Annual_CMS_Contract_Value__c + crmdbChild.Annual_Child_CMS_CR__c;
                }
                if((crmdbChild.Total_Child_CMS_CR__c!= oldRecMap.get(crmdbChild.Id).Total_Child_CMS_CR__c || crmdbChild.Total_CMS_Contract_Value__c  != oldRecMap.get(crmdbChild.Id).Total_CMS_Contract_Value__c)){
                    crmdbChild.Total_CMS_Contract_Value_CR_S__c =  crmdbChild.Total_CMS_Contract_Value__c + crmdbChild.Total_Child_CMS_CR__c;
                }
            }
        }
    }  
    
    //Summation of child CRs to Parent
    public static void qualificationUpdate(Map<Id,CRMDB__c>oldRecMap,List<CRMDB__c>newRecList){
        if(Utilities.getConstant_CS('CRMDB Trigger Skip')=='No'){
            List<Id> parentIDLst = new List<Id>();
            List<CRMDB__c> parentCrmdbUpdateLst = new List<CRMDB__c>();
            
            //Logic to update parent when the child is activated
            for(CRMDB__c crmdb  : newRecList){
                if(crmdb.Master_Customer_Name__c!=null && 
                   (crmdb.Active_Customer__c!=oldRecMap.get(crmdb.Id).Active_Customer__c ||
                    crmdb.Total_CMS_Contract_Value_CR_S__c!=oldRecMap.get(crmdb.Id).Total_CMS_Contract_Value_CR_S__c  ||
                    crmdb.Annual_CMS_Contract_Value_CR_S__c!=oldRecMap.get(crmdb.Id).Annual_CMS_Contract_Value_CR_S__c 
                   )){
                       parentIDLst.add(crmdb.Master_Customer_Name__c);
                   }
            }
            //Fetching parent records to update 
            List<CRMDB__c> parentLst = [select id,Total_CMS_Contract_Value_CR_S__c,Total_CMS_Contract_Value__c,Annual_CMS_Contract_Value_CR_S__c,Annual_CMS_Contract_Value__c from CRMDB__c where id in : parentIDLst];
            for(CRMDB__c parentCrmdb : parentLst){
                for(CRMDB__c crmdb  : newRecList){
                    if(crmdb.Master_Customer_Name__c==parentCrmdb.Id){
                        //Sum Annual and Total CMS Contract Value and CRs value on parent when the Active Customer Flag is Yes on child record
                        if(crmdb.Active_Customer__c==oldRecMap.get(crmdb.Id).Active_Customer__c && crmdb.Active_Customer__c.contains('Yes')){
                            if(crmdb.Annual_CMS_Contract_Value_CR_S__c!=oldRecMap.get(crmdb.Id).Annual_CMS_Contract_Value_CR_S__c){
                                parentCrmdb.Annual_CMS_Contract_Value_CR_S__c -= oldRecMap.get(crmdb.Id).Annual_CMS_Contract_Value_CR_S__c;
                                parentCrmdb.Annual_CMS_Contract_Value_CR_S__c += crmdb.Annual_CMS_Contract_Value_CR_S__c;
                            }
                            if(crmdb.Annual_CMS_Contract_Value__c!=oldRecMap.get(crmdb.Id).Annual_CMS_Contract_Value__c){
                                parentCrmdb.Annual_CMS_Contract_Value__c -= oldRecMap.get(crmdb.Id).Annual_CMS_Contract_Value__c;
                                parentCrmdb.Annual_CMS_Contract_Value__c += crmdb.Annual_CMS_Contract_Value__c;
                            }
                            if(crmdb.Total_CMS_Contract_Value_CR_S__c!=oldRecMap.get(crmdb.Id).Total_CMS_Contract_Value_CR_S__c){
                                parentCrmdb.Total_CMS_Contract_Value_CR_S__c -= oldRecMap.get(crmdb.Id).Total_CMS_Contract_Value_CR_S__c;
                                parentCrmdb.Total_CMS_Contract_Value_CR_S__c += crmdb.Total_CMS_Contract_Value_CR_S__c;
                            }
                            if(crmdb.Total_CMS_Contract_Value__c!=oldRecMap.get(crmdb.Id).Total_CMS_Contract_Value__c){
                                parentCrmdb.Total_CMS_Contract_Value__c -= oldRecMap.get(crmdb.Id).Total_CMS_Contract_Value__c;
                                parentCrmdb.Total_CMS_Contract_Value__c += crmdb.Total_CMS_Contract_Value__c;
                            }
                            
                        }
                        //Sum Annual and Total CMS Contract Value and CRs value on parent when the Active Customer Flag is changed from No to Yes on child record
                        else if(crmdb.Active_Customer__c.contains('Yes') && oldRecMap.get(crmdb.Id).Active_Customer__c.contains('No')){
                            parentCrmdb.Total_CMS_Contract_Value_CR_S__c += crmdb.Total_CMS_Contract_Value_CR_S__c;
                            parentCrmdb.Annual_CMS_Contract_Value_CR_S__c += crmdb.Annual_CMS_Contract_Value_CR_S__c;
                            parentCrmdb.Total_CMS_Contract_Value__c += crmdb.Total_CMS_Contract_Value__c;
                            parentCrmdb.Annual_CMS_Contract_Value__c += crmdb.Annual_CMS_Contract_Value__c;
                            
                            //Remove Annual and Total CMS Contract Value and CRs value on parent when the Active Customer Flag is changed from Yes to No on child record
                        }else if (crmdb.Active_Customer__c.contains('No') && oldRecMap.get(crmdb.Id).Active_Customer__c.contains('Yes')){
                            if(crmdb.Annual_CMS_Contract_Value_CR_S__c!=oldRecMap.get(crmdb.Id).Annual_CMS_Contract_Value_CR_S__c){
                                parentCrmdb.Annual_CMS_Contract_Value_CR_S__c -= oldRecMap.get(crmdb.Id).Annual_CMS_Contract_Value_CR_S__c;
                            }else{
                                parentCrmdb.Annual_CMS_Contract_Value_CR_S__c -= crmdb.Annual_CMS_Contract_Value_CR_S__c;
                            }
                            if(crmdb.Annual_CMS_Contract_Value__c!=oldRecMap.get(crmdb.Id).Annual_CMS_Contract_Value__c){
                                parentCrmdb.Annual_CMS_Contract_Value__c -= oldRecMap.get(crmdb.Id).Annual_CMS_Contract_Value__c;
                            }else{
                                parentCrmdb.Annual_CMS_Contract_Value__c -= crmdb.Annual_CMS_Contract_Value__c;
                            }
                            if(crmdb.Total_CMS_Contract_Value__c!=oldRecMap.get(crmdb.Id).Total_CMS_Contract_Value__c){
                                parentCrmdb.Total_CMS_Contract_Value__c -= oldRecMap.get(crmdb.Id).Total_CMS_Contract_Value__c;
                            }else{
                                parentCrmdb.Total_CMS_Contract_Value__c -= crmdb.Total_CMS_Contract_Value__c;
                            }
                            if(crmdb.Total_CMS_Contract_Value_CR_S__c!=oldRecMap.get(crmdb.Id).Total_CMS_Contract_Value_CR_S__c){
                                parentCrmdb.Total_CMS_Contract_Value_CR_S__c -= oldRecMap.get(crmdb.Id).Total_CMS_Contract_Value_CR_S__c;
                            }else{
                                parentCrmdb.Total_CMS_Contract_Value_CR_S__c -= crmdb.Total_CMS_Contract_Value_CR_S__c;
                            }
                        }
                        parentCrmdb.Annual_Child_CMS_CR__c = parentCrmdb.Annual_CMS_Contract_Value_CR_S__c - parentCrmdb.Annual_CMS_Contract_Value__c;
                        parentCrmdb.Total_Child_CMS_CR__c = parentCrmdb.Total_CMS_Contract_Value_CR_S__c - parentCrmdb.Total_CMS_Contract_Value__c;
                    }
                }
                parentCrmdbUpdateLst.add(parentCrmdb);
            }
            childUpdate=true;
            update parentCrmdbUpdateLst;
        }
    }
    
    //Validate CAP fields on Child
    public static void childCapFieldsUpdateValidation(list <CRMDB__c> CRMDBList,list<CRMDB__c>oldCRMDBList){
        if(Utilities.getConstant_CS('CRMDB Trigger Skip')=='No'){
            for(CRMDB__c newRec:CRMDBList){
                for(CRMDB__c oldRec:oldCRMDBList){
                    if(newRec.Master_Customer_Name__c!=null && parentUpdate==false && newRec.Master_Customer_Name__c==oldRec.Master_Customer_Name__c){
                        if(//newRec.Is_Customer_on_CAP__c!=oldRec.Is_Customer_on_CAP__c ||
                            newRec.Is_CAP_caused_by_CMS__c!=oldRec.Is_CAP_caused_by_CMS__c ||
                            newRec.CAP_Title__c!=oldRec.CAP_Title__c||
                            newRec.CAP_Case_Opened_Date__c!=oldRec.CAP_Case_Opened_Date__c||
                            newRec.CAP_case_Number_Engagement_ID__c!=oldRec.CAP_case_Number_Engagement_ID__c||
                            newRec.CAP_case_Manager_Name__c!=oldRec.CAP_case_Manager_Name__c||
                            newRec.Brief_Summary_for_Red_Yellow_Status__c!=oldRec.Brief_Summary_for_Red_Yellow_Status__c){
                                newRec.addError('Please update CAP fields on CRMDB Parent Contract.');  
                            }
                    }
                }
            }
        }
    }
    
    //Show Error message when SDM try to update parent Contract Annual and Total CMS Values 
    Public static void totalandAnnualContractValidation(list <CRMDB__c> CRMDBList,Map<Id,CRMDB__c>oldRecMap){
        if(Utilities.getConstant_CS('CRMDB Trigger Skip')=='No'){
            for(CRMDB__c crmdb:CRMDBList){
                if(crmdb.Master_Customer_Name__c==null && childUpdate==false){
                    if( crmdb.Total_CMS_Contract_Value__c!=oldRecMap.get(crmdb.Id).Total_CMS_Contract_Value__c ||
                       crmdb.Annual_CMS_Contract_Value__c!=oldRecMap.get(crmdb.Id).Annual_CMS_Contract_Value__c ||
                       crmdb.Total_CMS_Contract_Value_CR_S__c!=oldRecMap.get(crmdb.Id).Total_CMS_Contract_Value_CR_S__c ||
                       crmdb.Annual_CMS_Contract_Value_CR_S__c!=oldRecMap.get(crmdb.Id).Annual_CMS_Contract_Value_CR_S__c ||
                       crmdb.Annual_Child_CMS_CR__c!=oldRecMap.get(crmdb.Id).Annual_Child_CMS_CR__c ||
                       crmdb.Total_Child_CMS_CR__c!=oldRecMap.get(crmdb.Id).Total_Child_CMS_CR__c
                      ){
                          crmdb.addError('Please update Total and Annual CMS fields on CRMDB Child Contract.');  
                      }
                }
            }
        }
    } 
    
}