objects/DashboardNameIdMapping__mdt.object
<CustomObject>
    <fields>
        <fullName>DashboardID__c</fullName>
        <label>DashboardID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DashboardSize__c</fullName>
        <description>Length of the dashboard approx.</description>
        <label>DashboardSize</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DashboardNameIdMapping</label>
    <pluralLabel>DashboardNameIdMapping</pluralLabel>
</CustomObject>

classes/EACentroController.cls
public with sharing class EACentroController
{
public string eaDashboardId{ get;set;}
public string eaDashboardSize{ get;set;}

public EACentroController ()
{
String dashboardName = ApexPages.currentPage().getParameters().get('dashboardName');
list <DashboardNameIdMapping__mdt> dashboardList = [select developername, DashboardID__c, DashboardSize__c from DashboardNameIdMapping__mdt where developername = :dashboardname limit 1];
if (!dashboardList.isempty())
{
eaDashboardId = dashboardList [0].DashboardID__c;
eaDashboardSize = dashboardList [0].DashboardSize__c;
}
}
}