objects/Disti_to_Partner_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>Channel_Partner__c</fullName>
        <formula>Partner__r.Name</formula>
        <label>Channel Partner</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distributor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This fields is used for store the distributor account name</description>
        <label>Distributor</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The selected Partner is not a SCP registered active Distributor or is flagged on the Denied Distributor List, please select a valid SCP registered Distributor.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Channel</value>
            </filterItems>
            <filterItems>
                <field>Account.Partner_Assignment_Eligible__c</field>
                <operation>greaterOrEqual</operation>
                <value>1</value>
            </filterItems>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Distributor</value>
            </filterItems>
            <infoMessage>This search will return only those Disti enrolled in the Sales Collaboration Platform program. However, if you would like to reference accounts eligible for lead assignment, refer to the P360 Partners Enrolled link on the left hand side of the screen.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Distributor Partners</relationshipLabel>
        <relationshipName>Disti_to_Partner_Mappings1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This filed is loop up to channel Partner account</description>
        <label>Partner</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The selected Partner is not a SCP registered active partner or is flagged on the Denied Partner List, please select a valid SCP registered partner.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Channel</value>
            </filterItems>
            <filterItems>
                <field>Account.Partner_Assignment_Eligible__c</field>
                <operation>greaterOrEqual</operation>
                <value>1</value>
            </filterItems>
            <infoMessage>This search will return only those partners enrolled in the Sales Collaboration Platform program. However, if you would like to reference accounts eligible for lead assignment, refer to the P360 Partners Enrolled link on the left hand side of the screen.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Distributors</relationshipLabel>
        <relationshipName>Disti_to_Partner_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>This object has relationship  between distributor to partner mapping.</description>
    <label>Distibutor &amp; Partner Mapping</label>
    <nameField>
        <displayFormat>DP-{00000}</displayFormat>
        <label>Disti Partner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP_Communities_Dist to Partner Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Channel_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created for P360 2A development.</description>
        <label>Channel Partner</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2)</booleanFilter>
            <errorMessage>The selected Partner is not a SCP registered active partner or is flagged on the Denied Partner List, please select a valid SCP registered partner.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Channel</value>
            </filterItems>
            <filterItems>
                <field>Account.Partner_Assignment_Eligible__c</field>
                <operation>greaterOrEqual</operation>
                <value>1</value>
            </filterItems>
            <infoMessage>This search will return only those partners enrolled in the Sales Collaboration Platform program. However, if you would like to reference accounts eligible for lead assignment, refer to the P360 Partners Enrolled link on the left hand side of the screen.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assigned Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Lead_Status__c</fullName>
        <description>This field is created for P360 2A Development</description>
        <label>Partner Lead Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Partner Assigned</fullName>
                </value>
                <value>
                    <fullName>Assigned To PSR</fullName>
                </value>
                <value>
                    <fullName>Actively Working</fullName>
                </value>
                <value>
                    <fullName>Deal Created</fullName>
                </value>
                <value>
                    <fullName>Rejected-Invalid Contact</fullName>
                </value>
                <value>
                    <fullName>Rejected-Already Deal</fullName>
                </value>
                <value>
                    <fullName>Rejected-Project Canceled</fullName>
                </value>
                <value>
                    <fullName>Rejected-Lost to Competition</fullName>
                </value>
                <value>
                    <fullName>Rejected-Not My Territory/Account</fullName>
                </value>
                <value>
                    <fullName>Rejected-No Customer Response</fullName>
                </value>
                <value>
                    <fullName>Rejected-Duplicate</fullName>
                </value>
                <value>
                    <fullName>Rejected-No Valid Project</fullName>
                </value>
                <value>
                    <fullName>Closed-Order Through Stock</fullName>
                </value>
                <value>
                    <fullName>Closed-Order Through Disti</fullName>
                </value>
                <value>
                    <fullName>Closed-Order Through Cisco</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Closed</fullName>
        <active>true</active>
        <businessProcess>eLeads</businessProcess>
        <description>Rejected/closed eLeads lead</description>
        <label>Closed</label>
    </recordTypes>
</CustomObject>

classes/SCP_Communities_PSRBulk_CT.cls
public without sharing class SCP_Communities_PSRBulk_CT extends SCP_Communities_ComponentControllerBase {
	
	public SCP_Communities_PSRBulk_CT() {
		leadRec = new Lead();
		System.debug(System.LoggingLevel.INFO,'#### isLead : '+isLead+' ####');
		isLead = false;
		System.debug(System.LoggingLevel.INFO,'#### isLead : '+isLead+' ####');
		// Modified By: Sudi 02 Nov 2014 
	    // Release : November Sprint 3
	    // User Story : US7093
	    // Below code is added to populate the Partner name drop down values in Partnar mass update
		partnerNameList = new list<SelectOption>();	
		set<SelectOption> newList = new set<SelectOption>();
		partnerNameList.add(new SelectOption('',Label.PRM_Picklist_Value_Select_options));		
		for(Disti_to_Partner_Mapping__c DP : [Select Partner__c, Channel_Partner__c from Disti_to_Partner_Mapping__c where Distributor__c=:channelAccount]){
			if(DP.Partner__c != null){						
				newList.add(new SelectOPtion(DP.Partner__c,DP.Channel_Partner__c));
			}				
		} 
		partnerNameList.addAll(newList);
		disableUpdate = false;

	}
	
	private String key ;
	
	public SCP_Communities_PageControllerBase pageController;
	
	public String getKey() {
		return this.key;
	}
	public override void setKey(String value) {
		if(value != null) {
			this.key = value;
			if(this.pageController != null)
			this.pageController.setComponentControllerMap(this.key, (SCP_Communities_PSRBulk_CT)this);
		}
	}
	
	public SCP_Communities_PageControllerBase getPageController() {
		return (this.pageController);
	}
	
  	public override void setPageController(SCP_Communities_PageControllerBase value) {
	  	System.debug(System.LoggingLevel.INFO, '*** INSIDE setPageController OF PSR');
	  	if(value != null) {	  		
	  		this.pageController = value;
	  		if(this.key != null)
	  		this.pageController.setComponentControllerMap(this.key,(SCP_Communities_PSRBulk_CT)this);
	  	}
  	}
	
	
		public string psr1_name { get; set; }
        public string psr1_Id { get; set; }
        public string psr2_name { get; set; }
        public string psr2_Id {get; set;}
        public string psr3_name { get; set; }
        public string psr3_Id { get; set; }
        
    	public void assignPSRs() {
       		pageController.assignPSRs();
   			psr1_name = null;
			psr1_Id = null;
			psr2_name = null;
			psr2_Id = null;
			psr3_name = null;
			psr3_Id = null;
        }
        
        public Lead leadRec { get; set; }
        public Boolean isLead { get; set; }
        public Boolean isPA {
        	get {
        		return (prmFilterUtility.isPA);
        	}
        }
        public Boolean isPSR {
        	get {
        		return (prmFilterUtility.isPSR);
        	}
        } 
        // Modified By: Sudi 02 Nov 2014 
	    // Release : November Sprint 3
	    // User Story : US7093
	    // Below method is used to get the distributor role
        public boolean isDisti{
			get{			
				return (prmFilterUtility.loggedInUserIsDisti =='Distributor')?true:false;
			}
		}
		public String channelAccount{
			get{
					return String.valueof(prmFilterUtility.loggedInUserPartnerAccount);
			}
		}
		// Modified By: Sudi 02 Nov 2014 
	    // Release : November Sprint 4
	    // User Story : US7093
	    // Below method is used to populated the Partner lead status drop down
        public List<SelectOption> getleadStatusList() {
        	
			List<SelectOption> options = new List<SelectOption>();
			//	leadSourceList.add(new SelectOption('All',Label.PRM_Picklist_Value_All));
			Schema.DescribeFieldResult status  = Lead.Partner_Lead_Status__c.getDescribe();
			for(Schema.Picklistentry sp : status.getPicklistValues()) {				
				if(isPA && sp.value != 'Partner Assigned' && sp.value != 'Deal Created') {					
					options.add(new SelectOption(sp.value,sp.label));
				}
				else if(isPSR  && sp.value != 'Partner Assigned' && sp.value != 'Deal Created'){					
					options.add(new SelectOption(sp.value,sp.label));
				}
			}
			return options;
        }
        public String leadStatus { get; set; }
        public Boolean disableUpdate { get; set; }
        public list<SelectOption> partnerNameList{get;set;}
        public string selectedPartner{get;set;}
        
        // Modified By: Sudi 02 Nov 2014 
	    // Release : November Sprint 4
	    // User Story : US7093
	    // Below method is added for update the Channel partner for all selected leads in lead filter page
        public void AssignPartnerName(){
    		pageController.AssignPartnerName(selectedPartner);
    	}
    	// Modified By: Santhosh 04 Nov 2014 
	    // Release : November Sprint 4
	    // User Story : US7118
	    // Below method used to enable the mass update in lead filter gird view
        public void enableMassEdit() {
        	disableUpdate = false;
        	if(leadStatus == 'Actively Working' || leadStatus.startsWith('Closed-Order')) {
        		disableUpdate = true;
        	}
        	pageController.enableMassEdit(leadStatus);
        	//return null;
        }
        // Modified By: Santhosh 04 Nov 2014 
	    // Release : November Sprint 4
	    // User Story : US7118
	    // Below method is mass Update the partner lead status.
        public void updateStatus() {
        	if(leadStatus != null && leadStatus != '') {
        		leadRec.Partner_Lead_Status__c = leadStatus;
        	}        	
        	pageController.updateStatus(leadRec);
        }
         // Modified By: Santhosh 04 Nov 2014 
	    // Release : November Sprint 4
	    // User Story : US7118
	    // Below method is used to cancel the mass update status.
        public Pagereference cancelMassUpdate() {
        	leadStatus = '';
        	selectedPartner = '';
        	disableUpdate = false;
        	return pageController.cancelMassUpdate();
        }
}