objects/DuplicateLine__c.object
<CustomObject>
    <fields>
        <fullName>OpptyEx__c</fullName>
        <externalId>true</externalId>
        <label>OpptyEx</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ToUpdate</fullName>
                    <default>true</default>
                    <label>ToUpdate</label>
                </value>
                <value>
                    <fullName>Updated</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DuplicateLine</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>DuplicateLine Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DuplicateLines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DuplicateLine.cls
public class DuplicateLine {
    
    public Static Set<Id> opptyAlreadyAdded = new Set<Id>(); 
   
    public static void processIds(Set<Id> OpptyIds){
        DuplicateLine__c[] dlisToAdd = new DuplicateLine__c[]{};        

        for (Id oId : OpptyIds) {
            if (!opptyAlreadyAdded.contains(oId)){
               DuplicateLine__c dliTmp = new DuplicateLine__c(OpptyEx__c=oId, Status__c='ToUpdate');
               dlisToAdd.add(dliTmp);
               opptyAlreadyAdded.add(oId);
            }              
        } 
        if (dlisToAdd.size() > 0){upsert dlisToAdd OpptyEx__c;}        
    }    

}