objects/DuplicateLine__c.object
<CustomObject>
    <fields>
        <fullName>OpptyEx__c</fullName>
        <externalId>true</externalId>
        <label>OpptyEx</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ToUpdate</fullName>
                    <default>true</default>
                    <label>ToUpdate</label>
                </value>
                <value>
                    <fullName>Updated</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DuplicateLine</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>DuplicateLine Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DuplicateLines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DuplicateLineBatchKickoff.cls
global class DuplicateLineBatchKickoff implements Schedulable {

    global void execute(SchedulableContext SC) {
        DuplicateLineBatch recalculate = new DuplicateLineBatch();
        recalculate.query='SELECT OpptyEx__c from DuplicateLine__c where Status__c = \'ToUpdate\' limit 100000';
        recalculate.email='sfdc-integration-apex-exceptions@external.cisco.com';
        ID batchprocessid = Database.executeBatch(recalculate,100);
        System.debug(batchprocessid);
    }
}