objects/EZProtect_Setting__mdt.object
<CustomObject>
    <fields>
        <fullName>EZProtectBaseURL__c</fullName>
        <label>EZProtect Base URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>EZProtect Setting</label>
    <pluralLabel>EZProtect Settings</pluralLabel>
</CustomObject>

classes/EZProtectWebPortalController.cls
public class EZProtectWebPortalController 
{
    public string getEZProtectBaseURL()
    {
         List<EZProtect_Setting__mdt> setting = new List<EZProtect_Setting__mdt>([SELECT ID, EZProtectBaseURL__c FROM EZProtect_Setting__mdt]);
         
         if(setting != null && setting.size() > 0)
         {
             return setting[0].EZProtectBaseURL__c;
         }
        
        return null;
    }
}