objects/Forecast_Tab_10_0_CS__c.object
<CustomObject>
    <fields>
        <fullName>EndpointURL__c</fullName>
        <inlineHelpText>This field contains the EndpointURL for the Forecast Tab class</inlineHelpText>
        <label>EndpointURL</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndpointVersion__c</fullName>
        <label>EndpointVersion</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Custom setting for Endpoint URL in Forecast_Tab_10_0_CT</description>
    <label>Forecast_Tab_10_0_CS</label>
</CustomObject>

objects/Org_Constant_CS__c.object
<CustomObject>
    <fields>
        <fullName>Non_Production_Value__c</fullName>
        <label>Non Production Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Production_Value__c</fullName>
        <label>Production Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>Org Constant CS</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Additional_User_Permissions__c</fullName>
        <description>Allows permission for additional functionality which are based on User and not by profile.
1)AccountCreateByTerritory: New SBC functionality which allows SBC based on Geo Rules
2)Enable EndUser ACCTCreation : Can Create End-User accounts
3)Enable Lead Conversion : Can Convert leads
4)Enable PDR ACCTCreation : Can Create End-User Account during CCW deal conversion
5)Request Resource : Allows AMs to access SE functionality
6)SE User : Allows SEs to access SE Functionality
7)2028 Visibility:Users that will be refreshed by 2028 black box process
8)NBM Approver : User can set status field of NBM records to 'Screen 3' Approval status</description>
        <label>Additional User Permissions</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>2028 Visibility</fullName>
                </value>
                <value>
                    <fullName>AccountCreateByTerritory</fullName>
                </value>
                <value>
                    <fullName>AcquisitionUser</fullName>
                </value>
                <value>
                    <fullName>Activate Sales Account View</fullName>
                </value>
                <value>
                    <fullName>CCE Enabled</fullName>
                </value>
                <value>
                    <fullName>DSEC360</fullName>
                </value>
                <value>
                    <fullName>DSEC360SAV</fullName>
                </value>
                <value>
                    <fullName>DSEContactIntelligence</fullName>
                </value>
                <value>
                    <fullName>DSECRinSFDC</fullName>
                </value>
                <value>
                    <fullName>DSEFA</fullName>
                </value>
                <value>
                    <fullName>DSEGA</fullName>
                </value>
                <value>
                    <fullName>DSENotification</fullName>
                </value>
                <value>
                    <fullName>DSESWSS</fullName>
                </value>
                <value>
                    <fullName>DSETAC</fullName>
                </value>
                <value>
                    <fullName>Einstein Opportunities</fullName>
                </value>
                <value>
                    <fullName>Enable_ePSS</fullName>
                </value>
                <value>
                    <fullName>Enable_VSS</fullName>
                </value>
                <value>
                    <fullName>Enable EndUser ACCTCreation</fullName>
                </value>
                <value>
                    <fullName>Enable Lead Conversion</fullName>
                </value>
                <value>
                    <fullName>Enable PDR ACCTCreation</fullName>
                </value>
                <value>
                    <fullName>Enable Target Prospect Creation</fullName>
                </value>
                <value>
                    <fullName>GSPO_BDM</fullName>
                </value>
                <value>
                    <fullName>GSSO HD Forecast User</fullName>
                </value>
                <value>
                    <fullName>MCP Prospect Engage</fullName>
                </value>
                <value>
                    <fullName>MCP Prospect Profiler</fullName>
                </value>
                <value>
                    <fullName>NBM Approver</fullName>
                </value>
                <value>
                    <fullName>NextGen Forecasting Pilot User</fullName>
                </value>
                <value>
                    <fullName>QIJanACVPilotUser</fullName>
                </value>
                <value>
                    <fullName>RAE SEP Enabled</fullName>
                </value>
                <value>
                    <fullName>Request Resource</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <label>Organization</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Theatre__c</fullName>
        <inlineHelpText>Please contact GSTS Support to Edit this field</inlineHelpText>
        <label>Theater</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Americas-Canada</fullName>
                </value>
                <value>
                    <fullName>Americas-Global Enterprise Segment</fullName>
                </value>
                <value>
                    <fullName>Americas-LATAM</fullName>
                </value>
                <value>
                    <fullName>Americas-US Commercial</fullName>
                </value>
                <value>
                    <fullName>Americas-US Public Sector</fullName>
                </value>
                <value>
                    <fullName>APJC-APAC</fullName>
                </value>
                <value>
                    <fullName>APJC-Greater China</fullName>
                </value>
                <value>
                    <fullName>APJC-Japan</fullName>
                </value>
                <value>
                    <fullName>EMEAR</fullName>
                </value>
                <value>
                    <fullName>Global Service Provider</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/Forecast_Tab_10_0_CT_test.cls
@isTest
private class Forecast_Tab_10_0_CT_test {
    private static void prepareData() {
        //load custom settings
        User u = new User(Id = UserInfo.getUserId());
        
        System.runAs (u) {
            List<Org_Constant_CS__c> orgConstant = new List<Org_Constant_CS__c>();
            orgConstant.add(new Org_Constant_CS__c(Name='FCST BASE',Non_Production_Value__c='http://wwwin-tools.cisco.com/E-Sales/opmgmt',Production_Value__c='http://wwwin-tools.cisco.com/E-Sales/opmgmt'));
            orgConstant.add(new Org_Constant_CS__c(Name='VPN',Non_Production_Value__c='http://wwwin.cisco.com/WWSales/e-sales/images/fcstTab.gif',Production_Value__c='http://wwwin-tools.cisco.com/E-Sales/opmgmt/images/top_left_esales.gif'));
            orgConstant.add(new Org_Constant_CS__c(Name='ISDC URL',Non_Production_Value__c='https://sandbox2.cloud9analytics.com/CentralApplication/index.jsp?pkg=new',Production_Value__c='https://central.cloud9analytics.com/CentralApplication/index.jsp?pkg=new'));

            insert orgConstant;
            
            
            List<Forecast_Tab_10_0_CS__c> fcTab = new List<Forecast_Tab_10_0_CS__c>();
            fcTab.add(new Forecast_Tab_10_0_CS__c(Name='SFDCValidateURL',EndpointURL__c='/services/Soap/c/',EndpointVersion__c='31.0/'));
            insert fcTab;
        }
    }

    @isTest static void test_method_one() {
        prepareData();
        String FCST_BASE = Utilities.getConstant_CS('FCST BASE');
        String VPN = Utilities.getConstant_CS('VPN');
        String username = UserInfo.getUserName();
        username = username.split('@')[0];//get first part of username
        username = username.replace('qa_', '');
        Url hostname = Url.getSalesforceBaseUrl();
        Test.setCurrentPage(Page.Forecast_Tab_10_0);


        Forecast_Tab_10_0_CT controller = new Forecast_Tab_10_0_CT();

        System.assertEquals(FCST_BASE, controller.FCST_BASE);
        System.assert(controller.VPN.startsWith(VPN + '?nocache='));
        System.assert(controller.appImgUrl.startsWith(FCST_BASE + controller.fcstImage + '?nocache='));
        System.assertNotEquals(null, controller.link);

        PageReference pr = controller.link;
        Map<String, String> urlParameters = pr.getParameters();
        System.assert(pr.getUrl().startsWith(FCST_BASE + controller.fcstRedirect));
        System.assertEquals('SFDC', urlParameters.get('SOURCE_APP'));
        System.assertEquals('MYFCST', urlParameters.get('nextPageCode'));
        System.assertEquals(username, urlParameters.get('SFDCUserId'));
        System.assertEquals(hostname.getHost(), urlParameters.get('SFDCHost'));
        System.assertEquals(hostname.toExternalForm() + '/services/Soap/c/31.0/' + UserInfo.getOrganizationId().substring(0,15), urlParameters.get('SFDCValidateURL'));
    }

    @isTest static void test_method_two() {
        //remove qa_prefix from username
        prepareData();

        Profile pList = [SELECT Id FROM Profile WHERE Name ='Cisco_ADMIN' limit 1];
        User newUser = new User();
        newUser.Alias = 'testusr';
        newUser.Email = 'testusr@cisco.com.test';
        newUser.EmailEncodingKey = 'UTF-8';
        newUser.LastName = 'Test';
        newUser.FirstName = 'cecid';
        newUser.Organization__c = 'Test';
        newUser.LanguageLocaleKey = 'en_US';
        newUser.LocaleSidKey = 'en_US';
        newUser.ProfileId = pList.Id;
        newUser.CommunityNickname = 'testusr';
        newUser.TimeZoneSidKey = 'America/Los_Angeles';
        newUser.UserName = 'qa_testusr@cisco.com.test';
        newUser.Theatre__c = 'Americas-Canada';
        String FCST_BASE = Utilities.getConstant_CS('FCST BASE');
        String VPN = Utilities.getConstant_CS('VPN');
        String username = 'testusr';
        Url hostname = Url.getSalesforceBaseUrl();
        Test.setCurrentPage(Page.Forecast_Tab_10_0);


        Forecast_Tab_10_0_CT controller;
        System.runAs(newUser) {
            controller = new Forecast_Tab_10_0_CT();
        }

        System.assertEquals(FCST_BASE, controller.FCST_BASE);
        System.assert(controller.VPN.startsWith(VPN + '?nocache='));
        System.assert(controller.appImgUrl.startsWith(FCST_BASE + controller.fcstImage + '?nocache='));
        System.assertNotEquals(null, controller.link);

        PageReference pr = controller.link;
        Map<String, String> urlParameters = pr.getParameters();
        System.assert(pr.getUrl().startsWith(FCST_BASE + controller.fcstRedirect));
        System.assertEquals('SFDC', urlParameters.get('SOURCE_APP'));
        System.assertEquals('MYFCST', urlParameters.get('nextPageCode'));
        System.assertEquals(username, urlParameters.get('SFDCUserId'));
        System.assertEquals(hostname.getHost(), urlParameters.get('SFDCHost'));
        System.assertEquals(hostname.toExternalForm() + '/services/Soap/c/31.0/' + UserInfo.getOrganizationId().substring(0,15), urlParameters.get('SFDCValidateURL'));
    }
    
        @isTest static void test_method_isdc() {
        //remove qa_prefix from username
        prepareData();

        Profile pList = [SELECT Id FROM Profile WHERE Name ='Cisco_ADMIN' limit 1];
        User newUser = new User();
        newUser.Alias = 'testusr';
        newUser.Email = 'testusr@cisco.com.test';
        newUser.EmailEncodingKey = 'UTF-8';
        newUser.LastName = 'Test';
        newUser.FirstName = 'cecid';
        newUser.Organization__c = 'Test';
        newUser.LanguageLocaleKey = 'en_US';
        newUser.LocaleSidKey = 'en_US';
        newUser.ProfileId = pList.Id;
        newUser.CommunityNickname = 'testusr';
        newUser.TimeZoneSidKey = 'America/Los_Angeles';
        newUser.UserName = 'qa_testusr@cisco.com.test';
        newUser.Theatre__c = 'Americas-Canada';
        newUser.Additional_User_Permissions__c = 'GSSO HD Forecast User';
        String ISDC_URL = Utilities.getConstant_CS('ISDC URL');
       
        String username = 'testusr';
        Url hostname = Url.getSalesforceBaseUrl();
        Test.setCurrentPage(Page.Forecast_Tab_10_0);


        Forecast_Tab_10_0_CT controller;
        System.runAs(newUser) {
            controller = new Forecast_Tab_10_0_CT();
        }

        System.assertNotEquals(null, controller.link);

        PageReference pr = controller.link;
        Map<String, String> urlParameters = pr.getParameters();
        
        }
}