objects/Lead.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>VDC</fullName>
        <active>true</active>
        <businessProcess>VDC Lead Process</businessProcess>
        <description>VDC Record Type to process VDC leads only.</description>
        <label>VDC</label>
    </recordTypes>
</CustomObject>

objects/ObjectRecordTypeIds__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Parent_Mobile_RecordTypeId__c</fullName>
        <label>Opportunity Parent Mobile RecordTypeId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Parent_RecordTypeId__c</fullName>
        <description>This field stores the id of the Opportunity Parent record type.</description>
        <label>Opportunity Parent RecordTypeId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is used to store the record type ids of account and contact objects.</description>
    <label>Object Record Type Ids</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Additional_User_Permissions__c</fullName>
        <description>Allows permission for additional functionality which are based on User and not by profile.
1)AccountCreateByTerritory: New SBC functionality which allows SBC based on Geo Rules
2)Enable EndUser ACCTCreation : Can Create End-User accounts
3)Enable Lead Conversion : Can Convert leads
4)Enable PDR ACCTCreation : Can Create End-User Account during CCW deal conversion
5)Request Resource : Allows AMs to access SE functionality
6)SE User : Allows SEs to access SE Functionality
7)2028 Visibility:Users that will be refreshed by 2028 black box process
8)NBM Approver : User can set status field of NBM records to 'Screen 3' Approval status</description>
        <label>Additional User Permissions</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>2028 Visibility</fullName>
                </value>
                <value>
                    <fullName>AccountCreateByTerritory</fullName>
                </value>
                <value>
                    <fullName>AcquisitionUser</fullName>
                </value>
                <value>
                    <fullName>Activate Sales Account View</fullName>
                </value>
                <value>
                    <fullName>CCE Enabled</fullName>
                </value>
                <value>
                    <fullName>DSEC360</fullName>
                </value>
                <value>
                    <fullName>DSEC360SAV</fullName>
                </value>
                <value>
                    <fullName>DSEContactIntelligence</fullName>
                </value>
                <value>
                    <fullName>DSECRinSFDC</fullName>
                </value>
                <value>
                    <fullName>DSEFA</fullName>
                </value>
                <value>
                    <fullName>DSEGA</fullName>
                </value>
                <value>
                    <fullName>DSENotification</fullName>
                </value>
                <value>
                    <fullName>DSESWSS</fullName>
                </value>
                <value>
                    <fullName>DSETAC</fullName>
                </value>
                <value>
                    <fullName>Einstein Opportunities</fullName>
                </value>
                <value>
                    <fullName>Enable_ePSS</fullName>
                </value>
                <value>
                    <fullName>Enable_VSS</fullName>
                </value>
                <value>
                    <fullName>Enable EndUser ACCTCreation</fullName>
                </value>
                <value>
                    <fullName>Enable Lead Conversion</fullName>
                </value>
                <value>
                    <fullName>Enable PDR ACCTCreation</fullName>
                </value>
                <value>
                    <fullName>Enable Target Prospect Creation</fullName>
                </value>
                <value>
                    <fullName>GSPO_BDM</fullName>
                </value>
                <value>
                    <fullName>GSSO HD Forecast User</fullName>
                </value>
                <value>
                    <fullName>MCP Prospect Engage</fullName>
                </value>
                <value>
                    <fullName>MCP Prospect Profiler</fullName>
                </value>
                <value>
                    <fullName>NBM Approver</fullName>
                </value>
                <value>
                    <fullName>NextGen Forecasting Pilot User</fullName>
                </value>
                <value>
                    <fullName>QIJanACVPilotUser</fullName>
                </value>
                <value>
                    <fullName>RAE SEP Enabled</fullName>
                </value>
                <value>
                    <fullName>Request Resource</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Theatre__c</fullName>
        <inlineHelpText>Please contact GSTS Support to Edit this field</inlineHelpText>
        <label>Theater</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Americas-Canada</fullName>
                </value>
                <value>
                    <fullName>Americas-Global Enterprise Segment</fullName>
                </value>
                <value>
                    <fullName>Americas-LATAM</fullName>
                </value>
                <value>
                    <fullName>Americas-US Commercial</fullName>
                </value>
                <value>
                    <fullName>Americas-US Public Sector</fullName>
                </value>
                <value>
                    <fullName>APJC-APAC</fullName>
                </value>
                <value>
                    <fullName>APJC-Greater China</fullName>
                </value>
                <value>
                    <fullName>APJC-Japan</fullName>
                </value>
                <value>
                    <fullName>EMEAR</fullName>
                </value>
                <value>
                    <fullName>Global Service Provider</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/OpportunityTriggerImpl.cls
/**
* Class OpportunityTriggerImpl
*
* Trigger Handler for the Opportunity SObject. This class implements the ITrigger
* interface to help ensure the trigger code is bulkified and all in one place.
***** Change History *****
* 9/28 - BeforeInsert & BeforeUpdate - set the Solution ID lookup value based on Picklist Value.
*
Modification History:
Itrack#        Date        		Author              		Change  
****************************************************************************
US250307     Feb 15,2019   Kavya M(kavmalli)                PSS - Edit Oppty fields except $, Book Date and Stage, Technology/Service line items
**********************************************/

public without sharing class OpportunityTriggerImpl
implements TriggerInterface
{
    private String parentMobileRecTypeId; 
    private String parentRecTypeId; 
    private String runningUserTheater;
    private Boolean isRunningUserPss = false;
    public static boolean sparkRun = false;
    
    // Constructor
    public void beforeInit(){
        //initiate any required variables or data for one time caching to be used in before operations
        this.parentMobileRecTypeId = ObjectRecordTypeIds__c.getInstance().Opportunity_Parent_Mobile_RecordTypeId__c;
        this.parentRecTypeId = ObjectRecordTypeIds__c.getInstance().Opportunity_Parent_RecordTypeId__c;
        User runningUser = [Select Theatre__c,Additional_User_Permissions__c From User where id =:UserInfo.getUserId()];
        if( runningUser != null ){
            if( runningUser.Theatre__c != null  ){
                this.runningUserTheater = runningUser.Theatre__c;
            }            
            if( runningUser.Additional_User_Permissions__c != null && runningUser.Additional_User_Permissions__c.contains('Enable_ePSS')){
                this.isRunningUserPss = true;
            }
        }     
    }
    
    public void afterInit(){
        //initiate any required variables or data for one time caching to be used in after operations
    }
    
    public void executeBeforeInsert(){
        system.debug('***Opty BEFORE INSERT****');
        OptyBO.CreteOptyUsingMobile(Trigger.new, parentMobileRecTypeId, parentRecTypeId, runningUserTheater, isRunningUserPss);
        if(!Trigger.isDelete){
            OptyBO.UpdateSolutionID(Trigger.new);           
        }
        //Added by Alekhya (Logic from OwnerAssignmentbyAT trigger)
        OptyBO.ownerAssignmentbyAT(Trigger.new);
        
        //Added by Alekhya (Logic from OpptyMandatoryCompetitor trigger)
        OptyBO.opptyMandatoryCompetitor(Trigger.new, Trigger.oldMap,Trigger.isUpdate,Trigger.isInsert);
        
        //Added by Alekhya (Logic from OpptyOwnerPostnChk trigger)
        OptyBO.opptyOwnerPostnChk(Trigger.new, Trigger.oldMap,Trigger.isInsert);
        
        //Added by Alekhya (Logic from OpptyValidationRuleChk trigger)
        OptyBO.opptyValidationRuleChk(Trigger.new, Trigger.oldMap,Trigger.isUpdate,Trigger.isInsert);
        
    }
    
    
    public void executeAfterInsert(){
        system.debug('***Opty AFTER INSERT****');
        OptyBO.NoEPSSOpptyOwner(Trigger.new);
        //Added by Alekhya (Logic from OpptyGetDealId trigger)
        OptyBO.OpptyGetDealId(Trigger.new, Trigger.oldMap, Trigger.isUpdate);
        //Added by Alekhya (Logic from PartnerUpdate trigger)
        OptyBO.partnerUpdate(Trigger.new, Trigger.oldMap,Trigger.isInsert);
        //Added by Alekhya (Logic from OpportunityExpectedAmtChanged  trigger)
        OptyBO.opportunityExpectedAmtChanged (Trigger.new, Trigger.old, Trigger.newMap,Trigger.isInsert,Trigger.isUpdate);
                
    }
    
    public void executeBeforeUpdate(){
        system.debug('***Opty BEFORE UPDATE****');  
        if(!Trigger.isDelete){
            OptyBO.UpdateSolutionID(Trigger.new);  
            
            //OptyBO.opportunitySparkRecordUpdate(Trigger.new, Trigger.oldMap);            
            //Added By: Kavya M(kavmalli)
            if(Utilities.getisPSSUser()) {
                return;
            }
            //added to check whether trigger is execute twice
            else if(!Utilities.getisTriggerRun()){
                Utilities.setisTriggerRun(true);
                String value = lxPilotUserCheck.CheckBeforeUpdate(Trigger.oldMap,Trigger.new,'noLines');  
            }
        }
        
         //Added by Alekhya (Logic from OpptyMandatoryCompetitor trigger)
        OptyBO.opptyMandatoryCompetitor(Trigger.new, Trigger.oldMap,Trigger.isUpdate,Trigger.isInsert);
        
        //Added by Alekhya (Logic from OpptyOwnerPostnChk trigger)
        OptyBO.opptyOwnerPostnChk(Trigger.new, Trigger.oldMap,Trigger.isInsert);
        
         //Added by Alekhya (Logic from OpptyValidationRuleChk trigger)
        OptyBO.opptyValidationRuleChk(Trigger.new, Trigger.oldMap,Trigger.isUpdate,Trigger.isInsert);
        
    }
    
    public void executeAfterUpdate()
    {      
        system.debug('***Opty AFTER Update****');
        //Added By: Kavya M(kavmalli)
        lxOpportunityUpdateForPB.updateRecords(Trigger.new, Trigger.oldMap);
        // Added as part of VDC Program to populate Opportunity Information on the Lead Record
        OptyBO.updateOpportunityOnLead(Trigger.new, Trigger.oldMap);
        //Added by Alekhya (Logic from OpptyGetDealId trigger)
        OptyBO.opptyGetDealId(Trigger.new, Trigger.oldMap,  Trigger.isUpdate);
        //Added by Alekhya (Logic from OpptyFutureUpdate trigger)
        OptyBO.opptyFutureUpdate(Trigger.new, Trigger.oldMap,  Trigger.isUpdate);
        //Added by Alekhya (Logic from opptyChildUpdate trigger)
        OptyBO.opptyChildUpdate(Trigger.new, Trigger.old);
        //Added by Alekhya (Logic from PartnerUpdate trigger)
        OptyBO.partnerUpdate(Trigger.new, Trigger.oldMap,Trigger.isInsert);
        //Added by Alekhya (Logic from OpportunityExpectedAmtChanged  trigger)
        OptyBO.opportunityExpectedAmtChanged (Trigger.new, Trigger.old, Trigger.newMap,Trigger.isInsert,Trigger.isUpdate);
    }
    
    
    public void executeBeforeDelete(){
        system.debug('***Opty BEFORE DELETE****'); 
        //Added by Alekhya (Logic from OpportunityBeforeDelete trigger)
        OptyBO.opportunityBeforeDelete(Trigger.old);     
    }
    
    public void executeAfterDelete(){}
    
    public void executeUnDelete(){}
}