objects/Lead_Prioritization_Model__c.object
<CustomObject>
    <fields>
        <fullName>Annual_Revenue_Weight__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Annual Revenue Weight</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Budget_Weight__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Budget Weight</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Buyer_Stage_Weight__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Buyer Stage  Weight</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Cisco_Architecture_Weight__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Cisco Architecture Weight</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Contact_Engagement_Weight__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Contact Engagement Weight</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Eloqua_Lead_Score_Weight__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Eloqua Lead Score Weight</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Eloqua_Lead_Source_Weight__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Eloqua Lead Source  Weight</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Job_Role_Weight__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Job Role Weight</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Lead_Category_Weight__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Lead Category Weight</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Lead_Source_Weight__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Lead Source Weight</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Main_Product_Weight__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Main Product Weight</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Medium_Type_Weight__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Medium Type Weight</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Number_of_Employees_Weight__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of Employees Weight</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Offer_Type_Weight__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Offer Type Weight</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product_Value_Weight__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Product Value Weight</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Project_Flag_Weight__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Project Flag  Weight</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SAVM_Segment_Weight__c</fullName>
        <defaultValue>0</defaultValue>
        <label>SAVM Segment Weight</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Services_Value_Weight__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Services Value Weight</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Theatre__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMERICAS</fullName>
                </value>
                <value>
                    <fullName>APJ</fullName>
                </value>
                <value>
                    <fullName>EMEAR</fullName>
                </value>
                <value>
                    <fullName>GREATER CHINA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Timeframe_Weight__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Timeframe Weight</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Vertical_Market_Weight__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Vertical Market Weight</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <description>Lead Prioritization Model Object to store the models that are referred at Region and Sub Region Level to compute the Lead Prioritization Star Rating for Manual and eLeads.</description>
    <label>Lead Prioritization Model</label>
    <nameField>
        <label>Prioritization Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Prioritization Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ranking__c.object
<CustomObject>
    <fields>
        <fullName>Theatre__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMERICAS</fullName>
                </value>
                <value>
                    <fullName>APJ</fullName>
                </value>
                <value>
                    <fullName>EMEAR</fullName>
                </value>
                <value>
                    <fullName>GREATER CHINA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>This object is created as part of Lead Prioritization project</description>
    <label>Ranking</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rankings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RankingVForceTest.cls
@isTest
private class RankingVForceTest {
    
    static testMethod void testRankingVForce(){
        Test.startTest();
        
        Lead_prioritization_model__c model = new Lead_prioritization_model__c();
        model.theatre__C = 'AMERICAS';
        model.Annual_Revenue_Weight__c = 5;
        model.Budget_Weight__c = 5;
        model.Buyer_Stage_Weight__c = 5;
        model.Cisco_Architecture_Weight__c = 5;
        model.Contact_Engagement_Weight__c = 5;
        model.Eloqua_Lead_Source_Weight__c = 5;
        model.Eloqua_Lead_Score_Weight__c = 5;
        model.Job_Role_Weight__c = 5;
        model.Vertical_Market_Weight__c = 5;
        model.Timeframe_Weight__c = 5;
        model.Lead_Category_Weight__c = 5;
        model.Lead_Source_Weight__c = 5;
        model.Main_Product_Weight__c = 5;
        model.Number_of_Employees_Weight__c = 5;
        model.Offer_Type_Weight__c = 5;
        model.Project_Flag_Weight__c = 5;
        model.Services_Value_Weight__c = 5;
        model.SAVM_Segment_Weight__c = 5;
        model.Product_Value_Weight__c = 5;
        model.medium_type_weight__c = 5;
       
       
        insert model;
        
        
            
        ApexPages.StandardController con = new Apexpages.StandardController(model);
        
        RankingVForce r = new RankingVForce( con ); 
        List <Ranking__C> testRank = r.getRanks();
        for (Ranking__C rank: testRank)
        {
            system.assertequals(rank.theatre__c, 'AMERICAS');
            
        }
        r.previous();
        r.next();
        r.first();
        r.last();
        r.refresh();
        r.Search();
        Boolean condition = r.hasNext;
        condition = r.hasPrevious;
       	Integer pageNum = r.pageNumber;
        Test.stopTest();
        
        
    } 

}