objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Call_Center_Vendor__c</fullName>
        <description>Call center vendor associated with the transaction. Value selected in SMCC application

Call Center Vendor</description>
        <label>Call Center Vendor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Call_Status__c</fullName>
        <description>NGCC Phase1:Call Status depending upon disposition value.  Can be only updated by system based on disposition.</description>
        <label>Call Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Call Back Later</fullName>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
                <value>
                    <fullName>Invalid Call Completed</fullName>
                </value>
                <value>
                    <fullName>Max Attempts Reached</fullName>
                </value>
                <value>
                    <fullName>Nurture</fullName>
                </value>
                <value>
                    <fullName>PE Cancelled/Completed</fullName>
                </value>
                <value>
                    <fullName>Call Completed</fullName>
                </value>
                <value>
                    <fullName>Requalification Required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CustomCountry__c</fullName>
        <description>Lead Address Country</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALAND ISLANDS</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BONAIRE, SINT EUSTATIUS AND SABA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_Qualifier_Call_Center__c</fullName>
        <description>Lead Qualifier Call Center for use by NGCC</description>
        <label>Lead Qualifier Call Center</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SDR_Lead_Owner_Name__c</fullName>
        <description>NGCC Phase1:SDR who worked on the lead</description>
        <label>SDR Lead Owner Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/NGCC_Popup_Excel_Cls.cls
public class NGCC_Popup_Excel_Cls{
    
    //@Variables declaration here
    public string  endDateFixed{get;set;}
    public string  searchCallCenter{get;set;}
    public string  startDateFixed{get;set;}
    public Transient  List<LeadHistory> requalificationLeads{get;set;}
    Public static List<string> customLabelCountries {get;set;}
    Public static List<string> customLabelUserList {get;set;}
    public Transient  List<RequalificationRecordsTempHolder> tempHistory {get;set;}
    
    //@Constructor: Getting parameters from URL.
    public NGCC_Popup_Excel_Cls(){
        endDateFixed = apexpages.currentpage().getparameters().get('endDateFixed');
        searchCallCenter = apexpages.currentpage().getparameters().get('searchCallCenter');
        startDateFixed = ApexPages.CurrentPage().getParameters().get('startDateFixed');
    }
    
    //@Static:Gettting list of user names and Countries from custom labels
    static{
        customLabelCountries = label.NGCC_Requalification_Countries.split(';');
        customLabelUserList  = label.NGCC_Requalification_UserList.split(';');
    }
    
    //@Method : On page load downloading report
    public void cmdExportToExcel(){
        if(searchCallCenter !=NULL && searchCallCenter != '' && searchCallCenter != '--None--'){
            requalificationLeads = [SELECT  LeadId,lead.Name,lead.lastname,lead.firstname,LEAD.STATUS,lead.SDR_Lead_Owner_Name__c,lead.CustomCountry__c, NewValue, OldValue,createdby.name, CreatedDate,Lead.leadsource,
            lead.recordtypeid,lead.Call_Center_Vendor__c,lead.Lead_Qualifier_Call_Center__c FROM LeadHistory 
            where (field='Call_Status__c') and
            lead.CustomCountry__c in :customLabelCountries  and
            Lead.leadsource='NGCC' and 
            (lead.Call_Center_Vendor__c=:searchCallCenter or 
            lead.Lead_Qualifier_Call_Center__c= :searchCallCenter) and 
            (lead.createddate >= :date.valueOf(startDateFixed) and lead.status not in ('Cancel','3.2 Rejected-Already oppty','3.2 Rejected-Already oppty','3.11 Rejected-Duplicate','3.6 Rejected-Lost to Competition','2 Accepted-Mine/Channel','3.8 Rejected-No Cisco Response(Admin Onl')and 
            lead.createddate <= :date.valueOf(endDateFixed)) order by createdby.name asc];
            if(!requalificationLeads.isEmpty()){
                tempHistory = new List<RequalificationRecordsTempHolder>();
                for(LeadHistory lh : requalificationLeads ){
                    if(lh.NewValue == 'Requalification Required' || lh.OldValue == 'Requalification Required'){
                        tempHistory.add(new RequalificationRecordsTempHolder(lh));                        
                    }
                }
            }else{
            }
        }else{
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,'Please Select Marketing Contact Center'));
        }
    }
    
    //@Inner class for holding lead history & lead records
    public class RequalificationRecordsTempHolder{
        public Transient  LeadHistory historyLeads {get;set;}
        public RequalificationRecordsTempHolder(LeadHistory historyLeads ){
            this.historyLeads = historyLeads; 
        }
    }
}