objects/Lead.object
<CustomObject>
    <fields>
        <fullName>CustomCountry__c</fullName>
        <description>Lead Address Country</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALAND ISLANDS</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BONAIRE, SINT EUSTATIUS AND SABA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_Prioritization_Score__c</fullName>
        <defaultValue>-1</defaultValue>
        <description>Hidden Field to store the lead prioritization numeric score that defines the star rating for the lead.</description>
        <label>Lead Prioritization Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lead_Record_Type_Name__c</fullName>
        <formula>RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Lead Record Type Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Region__c</fullName>
        <label>Sub-Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Manual</fullName>
        <active>true</active>
        <businessProcess>Global - Manual Lead</businessProcess>
        <description>Manually &amp; imported</description>
        <label>Manual</label>
    </recordTypes>
    <recordTypes>
        <fullName>eLeads</fullName>
        <active>true</active>
        <businessProcess>eLeads</businessProcess>
        <description>eLeads integration</description>
        <label>eLeads</label>
    </recordTypes>
</CustomObject>

objects/Lead_Prioritization_Model__c.object
<CustomObject>
    <fields>
        <fullName>Sub_Region__c</fullName>
        <label>Sub Region</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Theatre__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>ALL</fullName>
                    <default>true</default>
                    <label>ALL</label>
                </value>
                <value>
                    <fullName>ANZ</fullName>
                </value>
                <value>
                    <fullName>ASIA PACIFIC</fullName>
                </value>
                <value>
                    <fullName>CANADA</fullName>
                </value>
                <value>
                    <fullName>CENTRAL</fullName>
                </value>
                <value>
                    <fullName>CHINA</fullName>
                </value>
                <value>
                    <fullName>EMERGING</fullName>
                </value>
                <value>
                    <fullName>HONG KONG</fullName>
                </value>
                <value>
                    <fullName>INDIA &amp; SAARC</fullName>
                </value>
                <value>
                    <fullName>JAPAN</fullName>
                </value>
                <value>
                    <fullName>LATAM</fullName>
                </value>
                <value>
                    <fullName>NORTH</fullName>
                </value>
                <value>
                    <fullName>SOUTH</fullName>
                </value>
                <value>
                    <fullName>TAIWAN</fullName>
                </value>
                <value>
                    <fullName>UK &amp; IRELAND</fullName>
                </value>
                <value>
                    <fullName>US</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Theatre__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMERICAS</fullName>
                </value>
                <value>
                    <fullName>APJ</fullName>
                </value>
                <value>
                    <fullName>EMEAR</fullName>
                </value>
                <value>
                    <fullName>GREATER CHINA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Lead Prioritization Model Object to store the models that are referred at Region and Sub Region Level to compute the Lead Prioritization Star Rating for Manual and eLeads.</description>
    <label>Lead Prioritization Model</label>
    <nameField>
        <label>Prioritization Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Prioritization Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/LPRegionMapping__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Region__c</fullName>
        <label>Sub Region</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>LPRegionMapping</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>RegionMappings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LPRegionMappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Tx_Log__c.object
<CustomObject>
    <fields>
        <fullName>exception__c</fullName>
        <defaultValue>false</defaultValue>
        <label>exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>message__c</fullName>
        <label>message</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>originated__c</fullName>
        <label>originated</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>type__c</fullName>
        <label>type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Tx Log</label>
    <nameField>
        <label>Tx Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tx Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LeadScoreNightlyRefresh.cls
global class LeadScoreNightlyRefresh implements Database.Batchable < sObject > {
    
    global Date CurrDate = Date.today();
    global  String Run_mode;
    global final String g_strQuery = 'select id, Lead_Prioritization_Score__c  from lead '+'where lead_record_type_name__c in (\'eLeads\', \'Manual\') and (status = \'1 Waiting\' OR (status = \'2 Accepted-Mine/Channel\' AND isconverted = false))';
    fiscalyearsettings FiscalYear = [select name, startdate, enddate from fiscalyearsettings where  Startdate <= :CurrDate  and Enddate >= :CurrDate] ; 
    String Countrylist = '\'A';
    String strQuery;
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String restStrQuery = '';
        List <Lead_Prioritization_Model__c> model = [select ID, theatre__c,sub_region__c,lastmodifieddate from lead_prioritization_model__C 
                                                     where  lastmodifieddate >= :CurrDate]; 
        
        if (model.size()>0)
        {
            List <LPRegionMapping__c> RegionMap = [select region__c,Sub_Region__c, Country__c  from LPRegionMapping__c ];
            
            for(Lead_Prioritization_Model__c m: model)
            {
                if (m.sub_region__c != 'ALL')
                {
                    for (LPRegionMapping__c a: [select region__c,Sub_Region__c, Country__c  from LPRegionMapping__c  
                                                where region__c = :m.Theatre__c and sub_region__c = :m.Sub_Region__C])
                    {
                        
                        if (a.country__c != null) //
                            Countrylist +=  '\',\''+  a.Country__c  ;    
                        
                    }
                }
                
                if (m.Sub_Region__c == 'ALL')
                {
                    for (LPRegionMapping__c a: [select region__c,Sub_Region__c, Country__c  from LPRegionMapping__c  
                                                where region__c = :m.Theatre__c ])
                    {
                        
                        if (a.country__c != null ) 
                            Countrylist +=  '\',\''+  a.Country__c  ;    
                        
                    } 
                    
                }
                
                
            }
            countrylist += '\'';
            system.debug('Country List'+ countrylist);
            Datetime t1 = FiscalYear.StartDate;
            Datetime t2 = FiscalYear.EndDate;
            
            Datetime t5 = CurrDate;
            String fromstr1 = t1.format('yyyy-MM-dd\'T\'hh:mm:ss\'Z\'');
            String tostr1 = t2.format('yyyy-MM-dd\'T\'hh:mm:ss\'Z\'');
            
            String currD = t5.format('yyyy-MM-dd\'T\'hh:mm:ss\'Z\'');
            
            restStrQuery = '  and ((customcountry__c in ( '+ countrylist +') and CreatedDate >= '
                +fromstr1+' and CreatedDate <= ' + tostr1 +' ) OR CreatedDate >= '+ currD +')';
            
            
        }
        else {
            
            Datetime t5 = CurrDate;
            String currD = t5.format('yyyy-MM-dd\'T\'hh:mm:ss\'Z\'');
            restStrQuery = ' and CreatedDate >= '+ currD ;
            
        }
        
        if (Test.isRunningTest())
        {
            Datetime t5 = CurrDate;
            String currD = t5.format('yyyy-MM-dd\'T\'hh:mm:ss\'Z\'');
            restStrQuery = ' and lastmodifieddate >= '+ currD + ' LIMIT 5';
            
            
            
        }
        
        strQuery = g_strQuery + restStrQuery;
        
        return Database.getQueryLocator(strQuery);
    }
    
    
    global void execute(Database.BatchableContext BC, List < sObject > scope) {
        LPExtension obj1 = new LPExtension();
        List < Lead > lstLeadToUpdate = new List < Lead > ();   
        Map<String, Integer> scoremap = obj1.Calcscore((List <Lead> ) scope);
        
        for (Lead l: (List < Lead > ) scope) {  
            if (l.id !=null)
            {
                
                if (scoremap.containsKey(l.Id) == true)
                {
                    
                    l.Lead_Prioritization_Score__c = Double.valueOf(scoremap.get(l.Id)); 
                     
                    lstLeadToUpdate.add(l);
                }
                else
                {
                    l.Lead_Prioritization_Score__c = 0;
                      
                    lstLeadToUpdate.add(l);
                    
                }
                
            }
        }
        Database.SaveResult[] SaveResult = Database.update(lstLeadToUpdate, false);
        
        
        //Iterating over the save result and validating if any error occurred
        Integer iRows = 0;
        List < Tx_Log__c > lstLog = new List < Tx_Log__c > ();
        for (Database.SaveResult dsr: SaveResult) {
            Tx_Log__c newErrorRecord = new Tx_Log__c(name = lstLeadToUpdate[iRows].id, originated__c = 'Lead Prioritization Nightly Refresh', type__c = 'Lead', exception__c = true);
            if (dsr.isSuccess() != true) {
                if (dsr.getErrors().size() > 0) {
                    newErrorRecord.message__c = 'STATUS CODE: ' + dsr.getErrors()[0].getStatusCode() +
                        '\n ERROR: ' + dsr.getErrors()[0].getMessage() +
                        '\n AFFECTED FIELD: ' + dsr.getErrors()[0].getFields();
                }
                lstLog.add(newErrorRecord);
            }
            iRows++;
        }
        if (lstLog.size() > 0)
            Database.insert(lstLog, false);
        
    }
    global void finish(Database.BatchableContext BC) {
        
        AsyncApexJob aObj = [SELECT Id, Status, JobItemsProcessed, TotalJobItems, NumberOfErrors
                             FROM AsyncApexJob WHERE ID = : BC.getJobId()
                            ];
        
        String EmailToNotify = 'lead_prioritization_nightly_refresh_updates@cisco.com';
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[] {
            EmailToNotify
                };
                    mail.setToAddresses(toAddresses);
        mail.setSubject('Lead Score Batch Processing - ' + System.Today());
        String MailBody = 'Status : ' + aObj.Status + '<br/>';
        MailBody = MailBody + 'Total Batches : ' + aObj.TotalJobItems + '<br/>';
        MailBody = MailBody + 'Total Batches Procesed : ' + aObj.JobItemsProcessed + '<br/>';
        MailBody = MailBody + 'Failed Batches : ' + aObj.NumberOfErrors + '<br/>';
        mail.setHtmlBody(MailBody);
        
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] {
            mail
                });
    }
}