objects/Lead.object
<CustomObject>
    <fields>
        <fullName>CustomCountry__c</fullName>
        <description>Lead Address Country</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALAND ISLANDS</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BONAIRE, SINT EUSTATIUS AND SABA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>UNITED STATES</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DeduperProcessing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DeduperProcessing</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Prospect</fullName>
        <active>true</active>
        <businessProcess>NGCC Marketing Lead</businessProcess>
        <description>Prospect Leads from Next Gen Marketing Contact Center</description>
        <label>Prospect</label>
    </recordTypes>
</CustomObject>

objects/NGCC_NaaS_Credentials__c.object
<CustomObject>
    <fields>
        <fullName>Password__c</fullName>
        <description>Cisco password</description>
        <label>Password</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <description>Cisco username</description>
        <label>Username</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Cisco user credentials used for NaaS Integration to Send SMS</description>
    <label>NGCC NaaS Credentials</label>
</CustomObject>

objects/NGCC_Nass_SMS_Endpoints__c.object
<CustomObject>
    <fields>
        <fullName>EndpointUrl__c</fullName>
        <label>EndpointUrl</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>NGCC Nass SMS Endpoints</label>
</CustomObject>

objects/NGCC_SMS_History__c.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>NGCC SMS History</relationshipLabel>
        <relationshipName>NGCC_SMS_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sent_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sent By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>NGCC_SMS_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sent_Date__c</fullName>
        <label>Sent Date</label>
        <type>DateTime</type>
    </fields>
    <label>NGCC SMS History</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>SMS No-</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NGCC SMS History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ObjectRecordTypeIds__c.object
<CustomObject>
    <fields>
        <fullName>Manual_Lead_RecordTypeId__c</fullName>
        <description>This field stores the id of the Manual Lead record type id</description>
        <label>Manual Lead RecordTypeId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Generated_Lead_RecordTypeId__c</fullName>
        <description>This field stores the id of the Partner Generated Lead record type id</description>
        <label>Partner Generated Lead RecordTypeId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>eLeadsRecordTypeId__c</fullName>
        <description>This field stores the id of the eLeads record type id.</description>
        <label>eLeadsRecordTypeId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is used to store the record type ids of account and contact objects.</description>
    <label>Object Record Type Ids</label>
</CustomObject>

classes/NGCC_SendSMSExtn_Test.cls
/*********************************************************************************************************
Name    : NGCC_SendSMSExtn_Test
Author  : Ghattamaneni Chaithanya
Purpose : This is the test Class for the class NGCC_SendSMSExtn
Created Date: 29 Jan 2018
Modification History: 

*********************************************************************************************************/
@isTest
public class NGCC_SendSMSExtn_Test {
    @testSetup static void leadDataSetup() {        
        //Create Test Lead
        string recordtype = Schema.Sobjecttype.Lead.getRecordTypeInfosByName().get('Prospect').getRecordTypeId();  
        ObjectRecordTypeIds__c o = new ObjectRecordTypeIds__c();
        o.Manual_Lead_RecordTypeId__c = recordtype.subString(0,15);
        o.eLeadsRecordTypeId__c = recordtype.subString(0,15);
        o.Partner_Generated_Lead_RecordTypeId__c = recordtype.subString(0,15);
        insert o;
        Lead newLead = new Lead();
        newLead.LastName = 'TestleadSMS1';
        newLead.RecordTypeId = recordtype;
        newLead.Company = '123';
        newLead.Status = 'New Prospect';
        newLead.LeadSource = 'Web';
        newLead.CustomCountry__c = 'UNITED STATES';
        newLead.DeduperProcessing__c = true;
        insert newLead;
    }
    public static testmethod void updateLeadTest(){
        Lead testLead = [SELECT Id,MobilePhone FROM Lead WHERE Name='TestleadSMS1' LIMIT 1];
        test.startTest();
        ApexPages.StandardController sc = new ApexPages.standardController(testLead);
        NGCC_SendSMSExtn sendSMSExt = new NGCC_SendSMSExtn(sc);
        NGCC_SendSMSExtn.updatelead(testLead.id, '+1123456789');
        lead l = [select id,MobilePhone from lead where id =:testLead.id];
        test.stopTest();
        system.assertEquals('+1123456789',l.MobilePhone);
    }        
    public static testmethod void sendtestPositive(){
        Test.setMock(HttpCalloutMock.class, new NGCC_MockHttpResponseGenerator());
        NGCC_NaaS_Credentials__c userdetails = new NGCC_NaaS_Credentials__c();
        userdetails.name = 'NaaS Integration User';
        userdetails.Username__c = 'testUser';
        userdetails.Password__c =  'testPassword';
        insert userdetails;
        list<NGCC_Nass_SMS_Endpoints__c> EndPoints = new list<NGCC_Nass_SMS_Endpoints__c>();
        NGCC_Nass_SMS_Endpoints__c NaasEndpoint = new NGCC_Nass_SMS_Endpoints__c();
        NaasEndpoint.name = 'NaasURL';
        NaasEndpoint.EndpointUrl__c  = 'https://naasapi.cisco.com/rest/message'; 
        EndPoints.add(NaasEndpoint);
        insert EndPoints;
        Lead testLead = [SELECT Id,MobilePhone FROM Lead WHERE Name='TestleadSMS1' LIMIT 1];
        test.startTest();
        ApexPages.StandardController sc = new ApexPages.standardController(testLead);
        NGCC_SendSMSExtn sendSMSExt = new NGCC_SendSMSExtn(sc);
        string response =  NGCC_SendSMSExtn.Send('+911234567890','TestSMS',testLead.id);
        test.stopTest();
        system.assertEquals('200', response);
    } 
    public static testmethod void Sendtestexception(){
        Test.setMock(HttpCalloutMock.class, new NGCC_MockHttpResponseGenerator());
        list<NGCC_Nass_SMS_Endpoints__c> EndPoints = new list<NGCC_Nass_SMS_Endpoints__c>();
        NGCC_Nass_SMS_Endpoints__c NaasEndpoint = new NGCC_Nass_SMS_Endpoints__c();
        NaasEndpoint.name = 'NaasURL';
        NaasEndpoint.EndpointUrl__c  = 'https://naasapi.cisco.com/rest/message'; 
        EndPoints.add(NaasEndpoint);
        insert EndPoints;
        Lead testLead = [SELECT Id,MobilePhone FROM Lead WHERE Name='TestleadSMS1' LIMIT 1];
        User u = [select id from user where profile.name ='Cisco_ADMIN' and id!=:userinfo.getUserId() limit 1];
        
        ApexPages.StandardController sc = new ApexPages.standardController(testLead);
        NGCC_SendSMSExtn sendSMSExt = new NGCC_SendSMSExtn(sc);
        NGCC_SMS_History__c smsHis = new NGCC_SMS_History__c();
        smsHis.name__c = 'message 1';
        smsHis.Lead__c = testLead.id;
        smsHis.Sent_By__c = userinfo.getUserId();
        smsHis.Sent_Date__c = system.now();
        smsHis.Phone__c = testLead.MobilePhone;
        system.runAs(u){
            insert smsHis;
        }
        test.startTest();
        string response =  NGCC_SendSMSExtn.Send('+911234567890','TestSMS',testLead.id);
        test.stopTest();
       // system.assertEquals('\nInvalid Username or Password,please check "NGCC NaaS Credentials" Custom Settings.', response);
    }
    public static testmethod void SendtestexceptionforEndpoint(){
        Test.setMock(HttpCalloutMock.class, new NGCC_MockHttpResponseGenerator());
        Lead testLead = [SELECT Id,MobilePhone FROM Lead WHERE Name='TestleadSMS1' LIMIT 1];
        test.startTest();
        ApexPages.StandardController sc = new ApexPages.standardController(testLead);
        NGCC_SendSMSExtn sendSMSExt = new NGCC_SendSMSExtn(sc);
        string response =  NGCC_SendSMSExtn.Send('+911234567890','TestSMS',testLead.id);
        test.stopTest();
        system.assertEquals('error Argument 1 cannot be null', response);
    }
}