objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Call_Center_Vendor__c</fullName>
        <description>Call center vendor associated with the transaction. Value selected in SMCC application

Call Center Vendor</description>
        <label>Call Center Vendor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Call_Status__c</fullName>
        <description>NGCC Phase1:Call Status depending upon disposition value.  Can be only updated by system based on disposition.</description>
        <label>Call Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Call Back Later</fullName>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
                <value>
                    <fullName>Invalid Call Completed</fullName>
                </value>
                <value>
                    <fullName>Max Attempts Reached</fullName>
                </value>
                <value>
                    <fullName>Nurture</fullName>
                </value>
                <value>
                    <fullName>PE Cancelled/Completed</fullName>
                </value>
                <value>
                    <fullName>Call Completed</fullName>
                </value>
                <value>
                    <fullName>Requalification Required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CustomCountry__c</fullName>
        <description>Lead Address Country</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALAND ISLANDS</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BONAIRE, SINT EUSTATIUS AND SABA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_Qualifier_Call_Center__c</fullName>
        <description>Lead Qualifier Call Center for use by NGCC</description>
        <label>Lead Qualifier Call Center</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SDR_Assignment_Date__c</fullName>
        <defaultValue>IF( CONTAINS($UserRole.DeveloperName ,"SDR"),TODAY(),null)</defaultValue>
        <description>NGCC Phase1:Date when record was assigned to SDR for calling</description>
        <label>SDR Assignment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SDR_Lead_Owner_Name__c</fullName>
        <description>NGCC Phase1:SDR who worked on the lead</description>
        <label>SDR Lead Owner Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Submitted_to_Sales_Date__c</fullName>
        <description>NGCC Phase1:Date when the lead was submitted to sales for NGLM Routing</description>
        <label>Submitted to Sales Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Marketing_Call_Center__c</fullName>
        <label>Marketing Call Center</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Convergys Manila - Global</fullName>
                </value>
                <value>
                    <fullName>Convergys Manila - ASIA</fullName>
                </value>
                <value>
                    <fullName>Convergys Suzhou China</fullName>
                </value>
                <value>
                    <fullName>Sellbytel Kuala Lumpur</fullName>
                </value>
                <value>
                    <fullName>Concentrix Costa Rica</fullName>
                </value>
                <value>
                    <fullName>Sellbytel Korea</fullName>
                </value>
                <value>
                    <fullName>Inhouse Korea</fullName>
                </value>
                <value>
                    <fullName>Inhouse Japan</fullName>
                </value>
                <value>
                    <fullName>Sellbytel Sydney Australia</fullName>
                </value>
                <value>
                    <fullName>Inhouse Indonesia</fullName>
                </value>
                <value>
                    <fullName>Convergys India</fullName>
                </value>
                <value>
                    <fullName>Concentrix Debrecen Hungary</fullName>
                </value>
                <value>
                    <fullName>Concentrix Belfast Northern Ireland</fullName>
                </value>
                <value>
                    <fullName>Raya Cairo Egypt</fullName>
                </value>
                <value>
                    <fullName>Sellbytel Moscow Russia</fullName>
                </value>
                <value>
                    <fullName>Sellbytel Lisbon Portugal</fullName>
                </value>
                <value>
                    <fullName>Alea Canada</fullName>
                </value>
                <value>
                    <fullName>eCoast New Hampshire</fullName>
                </value>
                <value>
                    <fullName>Cisco RTP</fullName>
                </value>
                <value>
                    <fullName>Convergys Appleton WI</fullName>
                </value>
                <value>
                    <fullName>Convergys Newcastle UK</fullName>
                </value>
                <value>
                    <fullName>MRP</fullName>
                </value>
                <value>
                    <fullName>Concentrix Sofia Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Raya Warsaw Poland</fullName>
                </value>
                <value>
                    <fullName>WebEx IS</fullName>
                </value>
                <value>
                    <fullName>DCR EMEAR</fullName>
                </value>
                <value>
                    <fullName>DCR Brazil</fullName>
                </value>
                <value>
                    <fullName>DCR US</fullName>
                </value>
                <value>
                    <fullName>GVS Nashville</fullName>
                </value>
                <value>
                    <fullName>N3 Atlanta</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/NGCC_RequalificationLeadsReport_Cls1.cls
public class NGCC_RequalificationLeadsReport_Cls1{
     //@Navigation variables declaration
    public String searchCallCenter { get; set; }
    public Lead leads {get;set;} 
    public Set<Id> setIDS;
    Public static List<string> customLabelCountries {get;set;}
    Public static List<string> customLabelUserList {get;set;}
    public List<leadhistory> leadHistoryList {get;set;}
    
    //@Constructor to hide or show onloading a page
    public NGCC_RequalificationLeadsReport_Cls1(){
        leads = new Lead();
    }
    //@Static Block: Gettting list of user names and Countries from custom labels 
    static{
        customLabelCountries = label.NGCC_Requalification_Countries.split(';');
        customLabelUserList  = label.NGCC_Requalification_UserList.split(';');
    }
    //@Method : Getting Marketing Contact Center filed values dynamically from user object.
    public List<SelectOption> getOptions(){
        List<SelectOption> options = new List<SelectOption>();
        Schema.DescribeFieldResult fieldResult = User.Marketing_Call_Center__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry f : ple){       
          options.add(new SelectOption(f.getLabel(), f.getValue()));
        } 
        return  options ;   
    }
     //@Method: This is responsible for fetching list of records and display it in Visualforce PageBlock table.
    public void cmdQueryResult(){
        try{ 
        String startDate = DateTime.newInstance(leads.SDR_Assignment_Date__c.year(),leads.SDR_Assignment_Date__c.month(),leads.SDR_Assignment_Date__c.day()).format('YYYY-MM-dd');
        startDate += 'T00:00:00Z';
        String endDate = DateTime.newInstance(leads.Submitted_to_Sales_Date__c.year(),leads.Submitted_to_Sales_Date__c.month(),leads.Submitted_to_Sales_Date__c.day()).format('YYYY-MM-dd');
        endDate += 'T00:00:00Z';        
        if(startDate<endDate){
            List<LeadHistory> requalificationLeads = [SELECT  Id,LeadId,NewValue, OldValue FROM LeadHistory where (field='Call_Status__c') and
            lead.CustomCountry__c in :customLabelCountries and Lead.leadsource='NGCC' and  (lead.Call_Center_Vendor__c=:searchCallCenter or  lead.Lead_Qualifier_Call_Center__c= :searchCallCenter) and 
            (lead.createddate >= :date.valueOf(startDate) and lead.status not in ('Cancel','3.2 Rejected-Already oppty','3.2 Rejected-Already oppty','3.11 Rejected-Duplicate','3.6 Rejected-Lost to Competition','2 Accepted-Mine/Channel','3.8 Rejected-No Cisco Response(Admin Onl')and 
            lead.createddate <= :date.valueOf(endDate)) order by leadid ASC NULLS LAST limit 49999];
            setIDS = new Set<Id>();
            if(!requalificationLeads.isEmpty()){
                for(LeadHistory lh : requalificationLeads ){
                    if(lh.NewValue == 'Requalification Required' || lh.OldValue == 'Requalification Required'){
                        setIDS.add(lh.id);                       
                    }
                }
                getPieData();
                cmdRequalification_Report();
            }else{
                leadHistoryList.clear();
            }
            }else{
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Confirm,'End Date always greater than start date'));
                leadHistoryList.clear();
            }
            }catch(exception e){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Confirm,e.getMessage()));
            }
    }    
    public void cmdRequalification_Report(){ 
        try{
        if(!setIDS.isEmpty()){
             leadHistoryList = [SELECT  LeadId,lead.name,LEAD.STATUS,lead.SDR_Lead_Owner_Name__c,lead.CustomCountry__c, NewValue, OldValue,createdby.name, CreatedDate,Lead.leadsource,
            lead.Call_Center_Vendor__c  from leadhistory where ID IN :setIDS order by lead.firstname asc NULLS Last limit 49999];           
        }
        }catch(exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Confirm,e.getMessage()));
        }        
    }
    //@Method : This is responsible for dowloading the current report.
  
    //@Method: Display list of records in dashboard based on user name.
    public List<PieWedgeData> getPieData(){
        try{
        List<PieWedgeData> data = new List<PieWedgeData>();
        for(AggregateResult ar : [SELECT createdby.name name,Count(id) total from leadhistory where ID IN :setIDS and createdby.name in :customLabelUserList GROUP BY createdby.name]){
            data.add(new PieWedgeData((String)ar.get('name'),(Integer)ar.get('total')));
        }
        return data;
        }catch(exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Confirm,e.getMessage()));
        }
        return null;
    }
      //@Inner class for display holding User Name and Record Count in Dashboard.   
    public class PieWedgeData {
        public String name { get; set; }
        public Integer data{ get; set; }
        public PieWedgeData(String name, Integer data) {
            this.name = name;
            this.data= data;
        }
    }
}