objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Call_Center_Vendor__c</fullName>
        <description>Call center vendor associated with the transaction. Value selected in SMCC application

Call Center Vendor</description>
        <label>Call Center Vendor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Call_Status__c</fullName>
        <description>NGCC Phase1:Call Status depending upon disposition value.  Can be only updated by system based on disposition.</description>
        <label>Call Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Call Back Later</fullName>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
                <value>
                    <fullName>Invalid Call Completed</fullName>
                </value>
                <value>
                    <fullName>Max Attempts Reached</fullName>
                </value>
                <value>
                    <fullName>Nurture</fullName>
                </value>
                <value>
                    <fullName>PE Cancelled/Completed</fullName>
                </value>
                <value>
                    <fullName>Call Completed</fullName>
                </value>
                <value>
                    <fullName>Requalification Required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MQL_Created_Date__c</fullName>
        <description>NGCC Phase1:Date when Lead was converted to "Marketing Qualified".  Should be updated also when a lead is re-qualified and status changed to "Marketing Qualified"</description>
        <label>MQL Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Max__c</fullName>
        <defaultValue>false</defaultValue>
        <description>NGCC Phase1:Flag to indicate when the lead can be requalified again after sales rejection</description>
        <label>Lead Requalification Check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Previous_Rejected_Reason_Date__c</fullName>
        <description>NGCC Phase1:Date for rejected reason for previously rejected lead.  This field is only updated when lead is rejected back to CC</description>
        <label>Previous Rejected Reason Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Previous_Rejected_Reason_Details__c</fullName>
        <description>NGCC Phase1:Detailed rejected reason for previously rejected lead.  This field is only updated when lead is rejected back to CC</description>
        <label>Previous Rejected Reason Details</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Previous_Sales_Lead_Status__c</fullName>
        <description>NGCC Phase1:Previous lead status for leads that was rejected by sales. This field is only updated when lead is rejected back to CC</description>
        <label>Previous Sales Rejected Lead Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rejected_Reason_Details__c</fullName>
        <description>QW-5033, Used to describe the reason of rejecting the lead.</description>
        <label>Reason for Rejection - Details</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SDR_Lead_Owner_New__c</fullName>
        <description>NGCC Phase1:SDR SFDC Id who worked on the lead</description>
        <label>SDR Lead Owner</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Closed</fullName>
        <active>true</active>
        <businessProcess>eLeads</businessProcess>
        <description>Rejected/closed eLeads lead</description>
        <label>Closed</label>
    </recordTypes>
    <recordTypes>
        <fullName>eLeads</fullName>
        <active>true</active>
        <businessProcess>eLeads</businessProcess>
        <description>eLeads integration</description>
        <label>eLeads</label>
    </recordTypes>
</CustomObject>

objects/NGCC_Requalification_Settings__c.object
<CustomObject>
    <fields>
        <fullName>Max__c</fullName>
        <defaultValue>false</defaultValue>
        <description>True if the Lead with this combination need only one time requalification for multiple requalification then mark it as False</description>
        <label>Max</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OwnerId__c</fullName>
        <description>If can have Lead.SDR_Lead_Owner_New__c or Queue Id. If any new field to be referenced then the format will be Lead.API_NAME</description>
        <label>OwnerId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <description>Just the reference to whom the lead need to assigned</description>
        <label>Owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Lead requalification specific settings have been managed in this custom setting object which maps different requalification criteria with desired set of owner to be assigned.</description>
    <label>NGCC Requalification Settings</label>
</CustomObject>

objects/ObjectRecordTypeIds__c.object
<CustomObject>
    <fields>
        <fullName>Closed_Lead_RecordTypeId__c</fullName>
        <description>This field stores the id of the Closed Lead record type</description>
        <label>Closed Lead RecordTypeId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manual_Lead_RecordTypeId__c</fullName>
        <description>This field stores the id of the Manual Lead record type id</description>
        <label>Manual Lead RecordTypeId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketing_Lead_RecordType__c</fullName>
        <description>This is to store marketing_Lead recordtype</description>
        <label>Marketing Lead RecordType</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>eLeadsRecordTypeId__c</fullName>
        <description>This field stores the id of the eLeads record type id.</description>
        <label>eLeadsRecordTypeId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is used to store the record type ids of account and contact objects.</description>
    <label>Object Record Type Ids</label>
</CustomObject>

objects/Org_Constant_CS__c.object
<CustomObject>
    <fields>
        <fullName>Production_Value__c</fullName>
        <label>Production Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>Org Constant CS</label>
</CustomObject>

classes/NGCC_Lead_Management_Extended_Cls.cls
/*********************************************************************************************************************************
Name    : NGCC_Lead_Management_Extended_Cls
Author  : Mukesh Srivastava
Purpose : This class is to handle all Lead related activity for NGCC project and some P360.
            This combine P360 LeadStatusToClosed Trigger where when a lead is rejected lead must be closed.
            This extend the functionality for NGCC project and route lead to proper user for requalification
            
Created Date:  6/26/2014 
Modification History:
            @Fazur : Added new logic to avoid as soon as Partner rejected any lead with 3.1 or 3.9 or 3.12 status, same user getting wired exception message on lead UI.                      
**********************************************************************************************************************************/
public class NGCC_Lead_Management_Extended_Cls {
    public Static List < Lead > listEleadRejectedBySales = new List < Lead > ();
    public static void NGCC_Lead_Mmgt_Extended_Update(List < Lead > newLstLead) {
        ObjectRecordTypeIds__c objLeadRec = ObjectRecordTypeIds__c.getInstance();
        Map < String, Org_Constant_CS__c > mapOCS = Org_Constant_CS__c.getAll();

        Id manualRecId = objLeadRec.Manual_Lead_RecordTypeId__c;
        Id eleadRecId = objLeadRec.eLeadsRecordTypeId__c;
        Id closeRecId = objLeadRec.Closed_Lead_RecordTypeId__c;

        
        for (Lead l: newLstLead) {
            if ((l.RecordTypeId == manualRecId && mapOCS.get('P360_Rejection_To_Close').Production_Value__c.contains(l.Status)) ||
                    (l.RecordTypeId == eleadRecId && (l.Max__c == True ||
                                                    (l.MQL_Created_Date__c == NULL && mapOCS.get('P360_Rejection_To_Close').Production_Value__c.contains(l.Status)) ||
                                                     mapOCS.get('NGCC_Rejection_To_Close').Production_Value__c.contains(l.Status)))) {
                l.RecordTypeId = closeRecId;
                l.Previous_Sales_Lead_Status__c = l.Status;
                l.Previous_Rejected_Reason_Date__c = System.now();
                l.Previous_Rejected_Reason_Details__c =l.Rejected_Reason_Details__c;
            } else if (l.RecordTypeId == eleadRecId && mapOCS.get('NGCC_Rejection_To_Requalify').Production_Value__c.contains(l.Status) &&
                        l.MQL_Created_Date__c != NULL && l.Max__c == false) {
                //NGCC_UpdateRejectedLeadOwner(l);
                listEleadRejectedBySales.add(l);                
            }
        }
        if (!listEleadRejectedBySales.isEmpty()){
             User sdrLeadOwnerDetails = [select id,isactive from user where id =:listEleadRejectedBySales[0].SDR_Lead_Owner_New__c limit 1];
             NGCC_UpdateRejectedLeadOwner(listEleadRejectedBySales,sdrLeadOwnerDetails);      
        }
    }

    /* @ method: Process the eLeads which are rejected by Sale */
    public static void NGCC_UpdateRejectedLeadOwner(List<Lead> rejectedeleadsList,User sdrLeadOwnerDetails) {
        ObjectRecordTypeIds__c objLeadRec = ObjectRecordTypeIds__c.getInstance();


         Id marketingLeadRecType = objLeadRec.Marketing_Lead_RecordType__c;         
        Map < String, NGCC_Requalification_Settings__c > fieldMapping = NGCC_Requalification_Settings__c.getAll();
        for(Lead rejectedeleads : rejectedeleadsList){
            if (rejectedeleads.Max__c == false) {

            // Creating our unique combination based on Rejected Code + Call Center Vendor
            String combination = rejectedeleads.Status.split(' ')[0] + rejectedeleads.Call_Center_Vendor__c;
            if(combination.length()>38){
                combination= combination.substring(0,38);
            }
            system.debug('combination'+combination);
            if (fieldMapping.containsKey(combination)){
                if(!sdrLeadOwnerDetails.isActive){
                    rejectedeleads.OwnerId = fieldMapping.get(combination).OwnerId__c;
                    rejectedeleads.Max__c = fieldMapping.get(combination).Max__c;
                }else{
                    if (fieldMapping.get(combination).Owner__c == 'Lead.SDR_Lead_Owner_New__c'){
                        if (rejectedeleads.SDR_Lead_Owner_New__c != null) { 
                            rejectedeleads.OwnerId = rejectedeleads.SDR_Lead_Owner_New__c;
                            rejectedeleads.Max__c = fieldMapping.get(combination).Max__c;                        
                        }
                    }else{
                        rejectedeleads.OwnerId = fieldMapping.get(combination).OwnerId__c;
                        rejectedeleads.Max__c = fieldMapping.get(combination).Max__c;
                    }
                 }                
                rejectedeleads.RecordTypeId = marketingLeadRecType;
                rejectedeleads.Previous_Sales_Lead_Status__c = rejectedeleads.Status;
                rejectedeleads.Previous_Rejected_Reason_Date__c = System.now();
                rejectedeleads.Previous_Rejected_Reason_Details__c =rejectedeleads.Rejected_Reason_Details__c;
                rejectedeleads.Status = 'Rejected by Sales';
                rejectedeleads.Call_Status__c = 'Requalification Required';
            }
          }       
        }
    }

}