objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Estimated_Product_Amount_USD__c</fullName>
        <description>Release: FY15OCT
Purpose: Real dollar amount for use by external PA/PSR users since the existing Expected Product List Amount is stored in thousands</description>
        <label>Estimated Product Amount (USD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Estimated_Service_Amount_USD__c</fullName>
        <description>Release: FY15OCT 
Purpose: Real dollar amount for use by external PA/PSR users since the existing Expected Service List Amount is stored in thousands</description>
        <label>Estimated Service Amount (USD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expected_Product_List_Amount__c</fullName>
        <description>Release: P360 March 2013 
Purpose: CCW Field - Store Expected Product List Amount in thousands of the Quote associated with deal which was created from lead</description>
        <label>Expected Product List Amount ($000s)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expected_Service_List_Amount__c</fullName>
        <description>Release: P360 March 2013 
Purpose: CCW Field - Store Expected Service List Amount in thousands of the Quote associated with deal which was created from lead</description>
        <label>Expected Service List Amount ($000s)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Partner_Lead_Status__c</fullName>
        <description>This field is created for P360 2A Development</description>
        <label>Partner Lead Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Partner Assigned</fullName>
                </value>
                <value>
                    <fullName>Assigned To PSR</fullName>
                </value>
                <value>
                    <fullName>Actively Working</fullName>
                </value>
                <value>
                    <fullName>Deal Created</fullName>
                </value>
                <value>
                    <fullName>Rejected-Invalid Contact</fullName>
                </value>
                <value>
                    <fullName>Rejected-Already Deal</fullName>
                </value>
                <value>
                    <fullName>Rejected-Project Canceled</fullName>
                </value>
                <value>
                    <fullName>Rejected-Lost to Competition</fullName>
                </value>
                <value>
                    <fullName>Rejected-Not My Territory/Account</fullName>
                </value>
                <value>
                    <fullName>Rejected-No Customer Response</fullName>
                </value>
                <value>
                    <fullName>Rejected-Duplicate</fullName>
                </value>
                <value>
                    <fullName>Rejected-No Valid Project</fullName>
                </value>
                <value>
                    <fullName>Closed-Order Through Stock</fullName>
                </value>
                <value>
                    <fullName>Closed-Order Through Disti</fullName>
                </value>
                <value>
                    <fullName>Closed-Order Through Cisco</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/prmLeadService_Test.cls
@isTest
public class prmLeadService_Test {
	public static testMethod void testProcessEdittedAssignedLeads(){
        Lead oldLead = new Lead();
        Lead udpatedLead = new Lead();
        
        udpatedLead.Partner_Lead_Status__c = Partner360Utils.PARTNER_STATUS_PARTNER_ASSIGNED;
        udpatedLead.Estimated_Product_Amount_USD__c = 123.9;
        udpatedLead.Estimated_Service_Amount_USD__c = 123.9;
        udpatedLead.Expected_Product_List_Amount__c = 123.9;
        udpatedLead.Expected_Service_List_Amount__c = 123.9;
        
        prmLeadService.processEdittedAssignedLeads(oldLead, udpatedLead);     
    }
}