objects/ObjectRecordTypeIds__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is used to store the record type ids of account and contact objects.</description>
    <label>Object Record Type Ids</label>
</CustomObject>

objects/Org_Constant_CS__c.object
<CustomObject>
    <fields>
        <fullName>Non_Production_Value__c</fullName>
        <label>Non Production Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Production_Value__c</fullName>
        <label>Production Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>Org Constant CS</label>
</CustomObject>

objects/Org_Constants__c.object
<CustomObject>
    <label>Org Constant</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Org Constants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProfileID__c.object
<CustomObject>
    <fields>
        <fullName>Cisco_PSS__c</fullName>
        <description>This field stores the id of the Cisco PSS Profile</description>
        <label>Cisco_PSS</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cisco_Renewals__c</fullName>
        <defaultValue>'00e34000001CQnp'</defaultValue>
        <description>00e34000001CQnp</description>
        <inlineHelpText>00e34000001CQnp</inlineHelpText>
        <label>Cisco_Renewals</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is used to store the profile ids for all the available profiles.</description>
    <label>Profile ID</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Additional_User_Permissions__c</fullName>
        <description>Allows permission for additional functionality which are based on User and not by profile.
1)AccountCreateByTerritory: New SBC functionality which allows SBC based on Geo Rules
2)Enable EndUser ACCTCreation : Can Create End-User accounts
3)Enable Lead Conversion : Can Convert leads
4)Enable PDR ACCTCreation : Can Create End-User Account during CCW deal conversion
5)Request Resource : Allows AMs to access SE functionality
6)SE User : Allows SEs to access SE Functionality
7)2028 Visibility:Users that will be refreshed by 2028 black box process
8)NBM Approver : User can set status field of NBM records to 'Screen 3' Approval status</description>
        <label>Additional User Permissions</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>2028 Visibility</fullName>
                </value>
                <value>
                    <fullName>AccountCreateByTerritory</fullName>
                </value>
                <value>
                    <fullName>AcquisitionUser</fullName>
                </value>
                <value>
                    <fullName>Activate Sales Account View</fullName>
                </value>
                <value>
                    <fullName>CCE Enabled</fullName>
                </value>
                <value>
                    <fullName>DSEC360</fullName>
                </value>
                <value>
                    <fullName>DSEC360SAV</fullName>
                </value>
                <value>
                    <fullName>DSEContactIntelligence</fullName>
                </value>
                <value>
                    <fullName>DSECRinSFDC</fullName>
                </value>
                <value>
                    <fullName>DSEFA</fullName>
                </value>
                <value>
                    <fullName>DSEGA</fullName>
                </value>
                <value>
                    <fullName>DSENotification</fullName>
                </value>
                <value>
                    <fullName>DSESWSS</fullName>
                </value>
                <value>
                    <fullName>DSETAC</fullName>
                </value>
                <value>
                    <fullName>Einstein Opportunities</fullName>
                </value>
                <value>
                    <fullName>Enable_ePSS</fullName>
                </value>
                <value>
                    <fullName>Enable_VSS</fullName>
                </value>
                <value>
                    <fullName>Enable EndUser ACCTCreation</fullName>
                </value>
                <value>
                    <fullName>Enable Lead Conversion</fullName>
                </value>
                <value>
                    <fullName>Enable PDR ACCTCreation</fullName>
                </value>
                <value>
                    <fullName>Enable Target Prospect Creation</fullName>
                </value>
                <value>
                    <fullName>GSPO_BDM</fullName>
                </value>
                <value>
                    <fullName>GSSO HD Forecast User</fullName>
                </value>
                <value>
                    <fullName>MCP Prospect Engage</fullName>
                </value>
                <value>
                    <fullName>MCP Prospect Profiler</fullName>
                </value>
                <value>
                    <fullName>NBM Approver</fullName>
                </value>
                <value>
                    <fullName>NextGen Forecasting Pilot User</fullName>
                </value>
                <value>
                    <fullName>QIJanACVPilotUser</fullName>
                </value>
                <value>
                    <fullName>RAE SEP Enabled</fullName>
                </value>
                <value>
                    <fullName>Request Resource</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deployment_No__c</fullName>
        <label>Deployment No</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Position_1__c</fullName>
        <label>Forecasting Positions</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/Product_UI_Redirect_Skip_Stage1_CTE_Test.cls
@isTest
public class Product_UI_Redirect_Skip_Stage1_CTE_Test
{
    public static testMethod void testInsert()
    {
        List < sObject > objRecTypeData = Test.loadData(ObjectRecordTypeIds__c.sObjectType,'GlobalTestObjectRecordTypeIds');
        List < sObject > osCSData = Test.loadData(Org_Constants__c.sObjectType,'OrgConstants');
        Org_Constant_CS__c ocs = new Org_Constant_CS__c();
        ocs.name = 'Exclude From PUI and Competitor Popup';
        ocs.Non_Production_Value__c = 'Cisco_ADMIN';
        ocs.Production_Value__c = 'Cisco_ADMIN';
        insert ocs;
        
        String testProfile = null;
        List<String> pieces = new List<String>();
 
        /*User opptyOwner = [Select id,name from user where profile.name='Cisco_ADMIN' and  IsActive = True AND  Additional_User_Permissions__c != 'Enable_ePSS' limit 1];
        opptyOwner.Position_1__c = 'test12345\n\rjdnkjsankjd';
        opptyOwner.Deployment_No__c  = 'SKIP';
        update opptyOwner;*/
        ProfileID__c pf = new ProfileID__c();
    pf.Cisco_Renewals__c = '00ec0000000QmlF';
    pf.Cisco_PSS__c = '00e30000000rrZw'; 
    insert pf;
    
    User opptyOwner = CEE_TestUtility.getUser('admin', true);
 
        test.startTest();
        System.runAs(opptyOwner){
            Opportunity oppty = new Opportunity(OwnerId=opptyOwner.Id,Position__c = '',Opportunity_Owner_AM__c=opptyOwner.Id,name='abc',StageName='2 - Qualification',CloseDate= system.today(), skipValidations__c = true);
            insert oppty;
            update oppty;
 
            Apexpages.StandardController stdController = new Apexpages.StandardController(oppty); // here oppty is the opportunity instance
            Test.setCurrentPage(new PageReference(''));
            testProfile = Utilities.getConstant_CS('CEE Outlook URL');
            pieces = testProfile.split(',');
            
            PageReference pageRef = Page.pdrDown;
            Test.setcurrentpage(pageRef);
            Apexpages.currentpage().getparameters().put('isdtp','mn'); 
            Product_UI_Redirect_Skip_Stage1_CTE puiRedirect = new Product_UI_Redirect_Skip_Stage1_CTE (stdController);
        }
        test.stopTest();
    }
    public static testMethod void testInsert1()
    {
        List < sObject > objRecTypeData = Test.loadData(ObjectRecordTypeIds__c.sObjectType,'GlobalTestObjectRecordTypeIds');
        List < sObject > osCSData = Test.loadData(Org_Constants__c.sObjectType,'OrgConstants');
        Org_Constant_CS__c ocs = new Org_Constant_CS__c();
        ocs.name = 'Exclude From PUI and Competitor Popup';
        ocs.Non_Production_Value__c = 'Cisco_PSS';
        ocs.Production_Value__c = 'Cisco_PSS';
        insert ocs;
        
        String testProfile = null;
        List<String> pieces = new List<String>();
        
        /*User opptyOwner = [Select id,name from user where profile.name='Cisco_ADMIN' and  IsActive = True AND  Additional_User_Permissions__c != 'Enable_ePSS' limit 1];
        opptyOwner.Position_1__c = 'test12345\n\rjdnkjsankjd';
        opptyOwner.Deployment_No__c  = 'SKIP';
        update opptyOwner;*/
        ProfileID__c pf = new ProfileID__c();
    pf.Cisco_Renewals__c = '00ec0000000QmlF';
    pf.Cisco_PSS__c = '00e30000000rrZw'; 
    insert pf;
    
    User opptyOwner = CEE_TestUtility.getUser('admin', true);
        
        test.startTest();
        System.runAs(opptyOwner){
            
            Opportunity oppty = new Opportunity(OwnerId=opptyOwner.Id,Position__c = '',Opportunity_Owner_AM__c=opptyOwner.Id,name='abc',StageName='2 - Qualification',CloseDate= system.today(), skipValidations__c = true);
            insert oppty;
            update oppty;
            
            Apexpages.StandardController stdController = new Apexpages.StandardController(oppty); // here oppty is the opportunity instance
            
            Test.setCurrentPage(new PageReference(''));
            testProfile = Utilities.getConstant_CS('CEE Outlook URL');
            pieces = testProfile.split(',');
            PageReference pageRef = Page.pdrDown;
            Test.setcurrentpage(pageRef);
            Apexpages.currentpage().getparameters().put('isdtp','mn'); 
            Product_UI_Redirect_Skip_Stage1_CTE puiRedirect = new Product_UI_Redirect_Skip_Stage1_CTE (stdController);
            
        }
        test.stopTest();  
    }
 
    public static testMethod void testInsert2()
    {
        List < sObject > objRecTypeData = Test.loadData(ObjectRecordTypeIds__c.sObjectType,'GlobalTestObjectRecordTypeIds');
        List < sObject > osCSData = Test.loadData(Org_Constants__c.sObjectType,'OrgConstants');
        Org_Constant_CS__c ocs = new Org_Constant_CS__c();
        ocs.name = 'Exclude From PUI and Competitor Popup';
        ocs.Non_Production_Value__c = 'Cisco_PSS';
        ocs.Production_Value__c = 'Cisco_PSS';
        insert ocs;
        
        String testProfile = null;
        List<String> pieces = new List<String>();
        
        /*User opptyOwner = [Select id,name from user where profile.name='Cisco_ADMIN' and  IsActive = True AND  Additional_User_Permissions__c != 'Enable_ePSS' limit 1];
        opptyOwner.Position_1__c = 'test12345\n\rjdnkjsankjd';
        opptyOwner.Deployment_No__c  = 'SKIP';
        update opptyOwner;*/
        ProfileID__c pf = new ProfileID__c();
    pf.Cisco_Renewals__c = '00ec0000000QmlF';
    pf.Cisco_PSS__c = '00e30000000rrZw'; 
    insert pf;
    
    User opptyOwner = CEE_TestUtility.getUser('admin', true);
 
        test.startTest();
        System.runAs(opptyOwner){
            Opportunity oppty = new Opportunity(OwnerId=opptyOwner.Id,Position__c = '',Opportunity_Owner_AM__c=opptyOwner.Id,name='abc',StageName='1 - Prospect',CloseDate= system.today(), skipValidations__c = true);
            insert oppty;
            update oppty;
 
            Apexpages.StandardController stdController = new Apexpages.StandardController(oppty); // here oppty is the opportunity instance
            Test.setCurrentPage(new PageReference(''));
            testProfile = Utilities.getConstant_CS('CEE Outlook URL');
            pieces = testProfile.split(',');            
            PageReference pageRef = Page.pdrDown;
            Test.setcurrentpage(pageRef);
            Apexpages.currentpage().getparameters().put('isdtp','mn'); 
            Product_UI_Redirect_Skip_Stage1_CTE puiRedirect = new Product_UI_Redirect_Skip_Stage1_CTE (stdController);
        }
        test.stopTest(); 
    }
    public static testMethod void testStateInitialization(){
        List < sObject > objRecTypeData = Test.loadData(ObjectRecordTypeIds__c.sObjectType,'GlobalTestObjectRecordTypeIds');
        List < sObject > osCSData = Test.loadData(Org_Constants__c.sObjectType,'OrgConstants');
        Org_Constant_CS__c ocs = new Org_Constant_CS__c();
        ocs.name = 'Exclude From PUI and Competitor Popup';
        ocs.Non_Production_Value__c = 'Cisco_PSS';
        ocs.Production_Value__c = 'Cisco_PSS';
        insert ocs;
        
        String testProfile = null;
        List<String> pieces = new List<String>();
        
       /* User opptyOwner = [Select id,name from user where profile.name='Cisco_ADMIN' and  IsActive = True AND  Additional_User_Permissions__c != 'Enable_ePSS' limit 1];
        opptyOwner.Position_1__c = 'test12345\n\rjdnkjsankjd';
        opptyOwner.Deployment_No__c  = 'SKIP';
        update opptyOwner; */
        ProfileID__c pf = new ProfileID__c();
            pf.Cisco_Renewals__c = '00ec0000000QmlF';
            pf.Cisco_PSS__c = '00e30000000rrZw';       
            insert pf;

        User opptyOwner= CEE_TestUtility.getUser('admin', true);
        
        test.startTest();
        System.runAs(opptyOwner){
            Opportunity oppty = new Opportunity(OwnerId=opptyOwner.Id,Position__c = '',Opportunity_Owner_AM__c=opptyOwner.Id,name='abc',StageName='1 - Prospect',CloseDate= system.today(), skipValidations__c = true);
            insert oppty;
            update oppty;

            Apexpages.StandardController stdController = new Apexpages.StandardController(oppty); // here oppty is the opportunity instance
            Test.setCurrentPage(new PageReference(''));
            testProfile = Utilities.getConstant_CS('CEE Outlook URL');
            pieces = testProfile.split(',');            
            PageReference pageRef = Page.pdrDown;
            Test.setcurrentpage(pageRef);
            Apexpages.currentpage().getparameters().put('isdtp','mn'); 
            Product_UI_Redirect_Skip_Stage1_CTE puiRedirect = new Product_UI_Redirect_Skip_Stage1_CTE (stdController);
            puiRedirect.ProductRedirect1 = '';
            String redirect = puiRedirect.ProductRedirect1;
            puiRedirect.PUI_URL1 = '';
           String puiUrl = puiRedirect.PUI_URL1;
            puiRedirect.FP_URL1 = '';
            String fpUrl = puiRedirect.FP_URL1;
            puiRedirect.ProductRedirect = false;
            Boolean redirectProd = puiRedirect.ProductRedirect;
            puiRedirect.ForcastRedirect = false;
            Boolean redirectForcast = puiRedirect.ForcastRedirect;
            puiRedirect.ForcastRedirect1 = 'false';
            String redirectForcast1 = puiRedirect.ForcastRedirect1;
            puiRedirect.ProductRedirect1 = 'false';
            String redirectProd1 = puiRedirect.ProductRedirect1;
           /* puiRedirect.PUI_URL = '';
            String puiUrl1 = puiRedirect.PUI_URL;
            puiRedirect.FP_URL = '';
            String fpUrl1 = puiRedirect.FP_URL; */
        }
        test.stopTest(); 
        
    }
    
    
}