objects/ObjectRecordTypeIds__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Renewal_RecordTypeId__c</fullName>
        <defaultValue>'01234000000Boc4'</defaultValue>
        <description>Opportunity Renewal RecordTypeId</description>
        <label>Opportunity Renewal RecordTypeId</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This is used to store the record type ids of account and contact objects.</description>
    <label>Object Record Type Ids</label>
</CustomObject>

objects/Renewals_Portfolio__c.object
<CustomObject>
    <fields>
        <fullName>Default_Timeline__c</fullName>
        <label>Default Timeline</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <label>Products</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Services__c</fullName>
        <label>Services</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stages__c</fullName>
        <label>Stages</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Timelines__c</fullName>
        <label>Timelines</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Renewals Portfolio page list of values</description>
    <label>Renewals Portfolio</label>
</CustomObject>

classes/RenewalsATRBEDataTest.cls
//Unit test Class for RnewalsATRBEData controller
@isTest
private class RenewalsATRBEDataTest {
    
    	static testMethod void testGetAtrDonutChartData() {
            RenewalsATEBEData obj=new RenewalsATEBEData();
            list<Id>accountIds=new list<Id>();
          	accountIds.add('0013400001Vz64lAAB');
            accountIds.add('00180000016nwUjAAI');
            list<string>businessEntityList=new list<string>();
            businessEntityList.add('Mobility');
            businessEntityList.add('Data Center Networking');
            businessEntityList.add('Collaboration');
            businessEntityList.add('Computing Systems');
            businessEntityList.add('AS-S');
            businessEntityList.add('TS-S');
            String dateValue='This Fiscal Year';
            ObjectRecordTypeIds__c ob=new ObjectRecordTypeIds__c();
            ob.Opportunity_Renewal_RecordTypeId__c='01234000000Boc4 ';
            insert ob;
        	Renewals_Portfolio__c renewalPortfolio = new Renewals_Portfolio__c();
            renewalPortfolio.products__c = 'product1';
            renewalPortfolio.services__c = 'service1';
            renewalPortfolio.Default_Timeline__c = 'default';
            renewalPortfolio.Stages__c = 'stage1';
            renewalPortfolio.Timelines__c = 'timeline';
            insert renewalPortfolio;
            AggregateResult[] queryResult =RenewalsATEBEData.getAtrDonutChartData(accountIds,dateValue,businessEntityList,true);
            AggregateResult[] barQueryResult =RenewalsATEBEData.getAtrByBeGroupings(accountIds,dateValue,true);
            Map<String,Object> funnelQueryResult =RenewalsATEBEData.getAtrFunnelChartData(accountIds,dateValue,businessEntityList,true);
            System.assertEquals(0,queryResult.size());
            System.assertEquals(0,barQueryResult.size());
            System.assertEquals(2,funnelQueryResult.size());
        }

}