objects/Org_Constant_CS__c.object
<CustomObject>
    <fields>
        <fullName>Production_Value__c</fullName>
        <label>Production Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>Org Constant CS</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Additional_User_Permissions__c</fullName>
        <description>Allows permission for additional functionality which are based on User and not by profile.
1)AccountCreateByTerritory: New SBC functionality which allows SBC based on Geo Rules
2)Enable EndUser ACCTCreation : Can Create End-User accounts
3)Enable Lead Conversion : Can Convert leads
4)Enable PDR ACCTCreation : Can Create End-User Account during CCW deal conversion
5)Request Resource : Allows AMs to access SE functionality
6)SE User : Allows SEs to access SE Functionality
7)2028 Visibility:Users that will be refreshed by 2028 black box process
8)NBM Approver : User can set status field of NBM records to 'Screen 3' Approval status</description>
        <label>Additional User Permissions</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>2028 Visibility</fullName>
                </value>
                <value>
                    <fullName>AccountCreateByTerritory</fullName>
                </value>
                <value>
                    <fullName>AcquisitionUser</fullName>
                </value>
                <value>
                    <fullName>Activate Sales Account View</fullName>
                </value>
                <value>
                    <fullName>CCE Enabled</fullName>
                </value>
                <value>
                    <fullName>DSEC360</fullName>
                </value>
                <value>
                    <fullName>DSEC360SAV</fullName>
                </value>
                <value>
                    <fullName>DSEContactIntelligence</fullName>
                </value>
                <value>
                    <fullName>DSECRinSFDC</fullName>
                </value>
                <value>
                    <fullName>DSEFA</fullName>
                </value>
                <value>
                    <fullName>DSEGA</fullName>
                </value>
                <value>
                    <fullName>DSENotification</fullName>
                </value>
                <value>
                    <fullName>DSESWSS</fullName>
                </value>
                <value>
                    <fullName>DSETAC</fullName>
                </value>
                <value>
                    <fullName>Einstein Opportunities</fullName>
                </value>
                <value>
                    <fullName>Enable_ePSS</fullName>
                </value>
                <value>
                    <fullName>Enable_VSS</fullName>
                </value>
                <value>
                    <fullName>Enable EndUser ACCTCreation</fullName>
                </value>
                <value>
                    <fullName>Enable Lead Conversion</fullName>
                </value>
                <value>
                    <fullName>Enable PDR ACCTCreation</fullName>
                </value>
                <value>
                    <fullName>Enable Target Prospect Creation</fullName>
                </value>
                <value>
                    <fullName>GSPO_BDM</fullName>
                </value>
                <value>
                    <fullName>GSSO HD Forecast User</fullName>
                </value>
                <value>
                    <fullName>MCP Prospect Engage</fullName>
                </value>
                <value>
                    <fullName>MCP Prospect Profiler</fullName>
                </value>
                <value>
                    <fullName>NBM Approver</fullName>
                </value>
                <value>
                    <fullName>NextGen Forecasting Pilot User</fullName>
                </value>
                <value>
                    <fullName>QIJanACVPilotUser</fullName>
                </value>
                <value>
                    <fullName>RAE SEP Enabled</fullName>
                </value>
                <value>
                    <fullName>Request Resource</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GCS_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>GCS_Enabled</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/EloquaEngage_CTE.cls
public with sharing class EloquaEngage_CTE {

    public String value {get;set;}

    public EloquaEngage_CTE(ApexPages.StandardController controller) {
         List<User> ulist=[Select Additional_User_Permissions__c, GCS_Enabled__c from User where Id=: UserInfo.getUserId() Limit 1];
       
         if (ulist[0].GCS_Enabled__c){
             value = Org_Constant_CS__c.getInstance('Eloqua_Engage_GCS').Production_Value__c;
         } else {
            value = Org_Constant_CS__c.getInstance('Eloqua_Engage_Global').Production_Value__c;
         }
    }


}