objects/Org_Constant_CS__c.object
<CustomObject>
    <fields>
        <fullName>Non_Production_Value__c</fullName>
        <label>Non Production Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Production_Value__c</fullName>
        <label>Production Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>Org Constant CS</label>
</CustomObject>

objects/Quote__c.object
<CustomObject>
    <fields>
        <fullName>CCW_Deal_Status_MQ__c</fullName>
        <label>CCW Deal Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DM_Quote_ID__c</fullName>
        <description>ID of the quotes from DM</description>
        <externalId>true</externalId>
        <label>Quote ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote_Summary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the associated Quote Summary on Partner Quote</description>
        <label>Quote Summary</label>
        <referenceTo>Quote_Summary__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Partner_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>Quote Header information.  Used in related lists.  Quote details stored in PDR.</description>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Quote_ID__c</fullName>
        <formula>Partner_Quote__r.DM_Quote_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Quote ID</label>
        <type>Text</type>
    </fields>
    <description>Used to create a Link on related lists.  Also stores the Deal ID which is required in the punch out to PDR.</description>
    <label>Quote Summary</label>
    <nameField>
        <label>Quote Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/QuoteSummary_CTE.cls
// ****************** Change History *******************
// kikamara - WR-01662 05/13/2016 - Replaced getOrgConstant object to getConstant_CS Custom setting
//    Removed the test method and moved to QuoteSummary_CTE_TEST
// ****************** Change History *******************

public class QuoteSummary_CTE {
    
    String Constant;
   
    public QuoteSummary_CTE(ApexPages.StandardController controller) {
    }
       
    public String getConstant() {    
        Org_Constant_CS__c oc = [SELECT Production_Value__c , Non_Production_Value__c FROM Org_Constant_CS__c WHERE Name = 'PDR URL'];
        return oc.Production_Value__c + ',' + oc.Non_Production_Value__c;
    } 
    
    public String getBaseUrl()
    {    
        return Utilities.getConstant_CS('PDR URL');
    }
    
    String QuoteStatus;
    String PdrDown;
    
    public String getPdrDown(){            
        
       return Utilities.getConstant_CS('PDR Down');
    } 
    public Boolean getprofilecheck(){
        String PdrSkipUser =Utilities.getConstant_CS('PDR_Skip_Users');
        List<String> skipuser = PdrSkipUser.split(',');
        set<string> PdrSkipUsers = new set<string>(skipuser); 
        Boolean profilecheck;
        if(pdrskipusers.contains(userinfo.getUserid().substring(0,15))){ 
            System.debug('INSIDE');
            profilecheck = false;
        }else{
            profilecheck = true;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,System.Label.Quoting_unavailable+' '+System.Label.Quoting_capabilities+' Please try later'));
        }
       return profilecheck; 
    }
    
    public String getQuoteStatus(){
     Id quoteSummaryId= ApexPages.currentPage().getParameters().get('id');
     Quote_Summary__c quoteId = [SELECT Quote_ID__c FROM Quote_Summary__c WHERE id= :quoteSummaryId];
         Quote__c q = [SELECT CCW_Deal_Status_MQ__c FROM Quote__c WHERE DM_Quote_ID__c= :quoteId.Quote_ID__c];
        return q.CCW_Deal_Status_MQ__c;
    }    
}