objects/Partner_Customer_Deployment_Tracking_SF__c.object
<CustomObject>
    <fields>
        <fullName>Partner_PSS_Sales_Cycle__c</fullName>
        <description>Qualification-The purpose of the Qualification Stage is for Cisco to decide whether an eligible partner can successfully deliver both PSS foundation (in case converted from CBR) and smart services.2-Awareness-The purpose of this Stage is to socialize the partner with PS and smart. It is important that an executive sponsor will be identified.3-Foundation Services Readiness-This is an optional Stage for partner moving from CBR to PSS and that have concerns regarding their capability to deliver collaborative service and maximize the PSS rebates.4-Smart-Purpose of this step is to implement the collector/portal and take the outputs of the test drive and apply them to the partners "as-is" operations.5-Pilots-The purpose of this Pilot Stage is to detail the process of customer pilot described in the "Smart" Stage.6-Deployment</description>
        <inlineHelpText>Stage 1 - 6:

1 - Qualification
2 - Awareness
3 - Foundation Services Readiness
4 - Smart
5 - Pilots
6 - Deployment</inlineHelpText>
        <label>Partner PSS Sales Cycle</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1-Qualification</fullName>
                </value>
                <value>
                    <fullName>2-Awareness</fullName>
                </value>
                <value>
                    <fullName>3-Foundation Services Readiness</fullName>
                </value>
                <value>
                    <fullName>4-Smart</fullName>
                </value>
                <value>
                    <fullName>5-Pilots</fullName>
                </value>
                <value>
                    <fullName>6-Deployment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>To analyze Partner data</description>
    <label>Partner Customer Deployment Tracking</label>
    <nameField>
        <displayFormat>PCDT-{0}</displayFormat>
        <label>Partner Tracking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Customer Deployment Trackings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_PartnerCustomerDT.cls
/**
   @Author sfdc config
   @name <Test_PartnerCustomerDT>
   @CreateDate <3/28/2014>
   @Description Test class for UpdatecustomDateFields 
   @Version <1.0>
  */
@istest(seealldata=true)
private  class Test_PartnerCustomerDT {
    private static testMethod void unitTest(){
        Partner_Customer_Deployment_Tracking_SF__c  pdt =new Partner_Customer_Deployment_Tracking_SF__c();      
        pdt.Partner_PSS_Sales_Cycle__c  = '1-Qualification';       
        insert pdt;
        pdt.Partner_PSS_Sales_Cycle__c   = '2-Awareness';        
        update pdt;
                
        Partner_Customer_Deployment_Tracking_SF__c  pdt1 =new Partner_Customer_Deployment_Tracking_SF__c();        
        pdt1.Partner_PSS_Sales_Cycle__c = '4-Smart';
        insert pdt1;       
        pdt1.Partner_PSS_Sales_Cycle__c   = '6-Deployment';
        update pdt1;
        
        Partner_Customer_Deployment_Tracking_SF__c  pdt2 =new Partner_Customer_Deployment_Tracking_SF__c();        
        pdt2.Partner_PSS_Sales_Cycle__c = '1-Crawl';
        insert pdt2;       
        pdt2.Partner_PSS_Sales_Cycle__c   = '4-Sprint';
        update pdt2;
        
        Partner_Customer_Deployment_Tracking_SF__c  pdt3 =new Partner_Customer_Deployment_Tracking_SF__c();        
        pdt3.Partner_PSS_Sales_Cycle__c = '2-Awareness';
        insert pdt3;       
        pdt3.Partner_PSS_Sales_Cycle__c   = '1-Qualification';
        update pdt3;
        
        Partner_Customer_Deployment_Tracking_SF__c  pdt4 =new Partner_Customer_Deployment_Tracking_SF__c();        
        pdt4.Partner_PSS_Sales_Cycle__c = '5-Pilots';
        insert pdt4;       
        pdt4.Partner_PSS_Sales_Cycle__c   = '3-Foundation Services Readiness';
        update pdt4;
        
        Partner_Customer_Deployment_Tracking_SF__c  pdt5 =new Partner_Customer_Deployment_Tracking_SF__c();        
        pdt5.Partner_PSS_Sales_Cycle__c = '3-Run';
        insert pdt5;       
        pdt5.Partner_PSS_Sales_Cycle__c = '2-Walk';
        update pdt5;
        
        Partner_Customer_Deployment_Tracking_SF__c  pdt6 =new Partner_Customer_Deployment_Tracking_SF__c();        
        pdt6.Partner_PSS_Sales_Cycle__c = '3-Foundation Services Readiness';
        insert pdt6;       
        pdt6.Partner_PSS_Sales_Cycle__c   = '4-Smart';
        update pdt6;
        
        Partner_Customer_Deployment_Tracking_SF__c  pdt7 =new Partner_Customer_Deployment_Tracking_SF__c();        
        pdt7.Partner_PSS_Sales_Cycle__c = '4-Sprint';
        insert pdt7;       
        pdt7.Partner_PSS_Sales_Cycle__c   = '5-Pilots';
        update pdt7;
        
        Partner_Customer_Deployment_Tracking_SF__c  pdt8 =new Partner_Customer_Deployment_Tracking_SF__c();        
        pdt8.Partner_PSS_Sales_Cycle__c = '3-Run';
        insert pdt8;       
        pdt8.Partner_PSS_Sales_Cycle__c   = '4-Sprint';
        update pdt8;
        
        
       
        
    }

}