objects/PEPE_Event_Day__c.object
<CustomObject>
    <fields>
        <fullName>Training_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Training Event</label>
        <referenceTo>PEPE_Training_Event__c</referenceTo>
        <relationshipName>Day_Session_Slots</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>This object us used for Session Slots Even Day grouping. Each Day can have multiple calendar session slots.</description>
    <label>Event Day</label>
    <nameField>
        <label>Day Session Slots Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PEPE_Training_Request__c.object
<CustomObject>
    <fields>
        <fullName>Address_1__c</fullName>
        <description>Country host enters details against main event for address 1 proposal.</description>
        <inlineHelpText>Please insert full address in one line divided by commas. Eg: 30 &amp; 31 Floors, Millennium Tower, Handelskai 94 - 96, VIENNA, WIEN A-1200, AUSTRIA</inlineHelpText>
        <label>Address 1</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CI_CVENT_Session_Name__c</fullName>
        <description>this field is for fetching data from Cvent for the record purpose</description>
        <label>CVENT Session Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CLP_flag__c</fullName>
        <label>CLP Eligible?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cisco_Location__c</fullName>
        <description>Please insert "Country [City], eg Netherlands [Amsterdam]”</description>
        <inlineHelpText>Please insert "Country [City], eg Netherlands [Amsterdam]”</inlineHelpText>
        <label>Cisco Location</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City value is entered here</description>
        <label>City (Do not use)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <formula>Training_Offering_Id__r.End_Date_Time__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Time_Zone__c</fullName>
        <description>Created part of May FY15 release to use in PEPE BLP Java application</description>
        <formula>TEXT(Training_Offering_Id__r.Event_Time_Zone__c)</formula>
        <label>Event Time Zone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Geography__c</fullName>
        <description>Geography</description>
        <label>Geography</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>EMEAR</fullName>
                    <default>true</default>
                    <label>EMEAR</label>
                </value>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>APJC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PTP_flag__c</fullName>
        <inlineHelpText>Displays the button to “Register” to the event if this field value is set to “Yes” or Displays the button to “Request” (send email) if this field values is set to “No” + Publish to Calendar? is set to “Yes”</inlineHelpText>
        <label>Registration open for all</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Publish_to_Calendar__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <formula>TEXT(Training_Offering_Id__r.Platform__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Platform</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Focus__c</fullName>
        <description>For Cvent Integration , read Primary Focus from TE</description>
        <formula>Text(Training_Offering_Id__r.Primary_Focus__c)</formula>
        <label>Primary Focus</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <description>The training Program which the training was set for</description>
        <formula>TEXT(Training_Offering_Id__r.Program__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publish_to_Calendar__c</fullName>
        <description>Created this field part of Mar 2015 release</description>
        <inlineHelpText>Displayed in Salesconnect Hub and/or Community Calendar, when this field value is set to “Yes”</inlineHelpText>
        <label>Publish to Calendar?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <formula>Training_Offering_Id__r.Start_Date_Time__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Training execution status. Certain statuses are auto-updated and certain statuses are manually updated by Logistics and Operations team based on the stage of the event</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Added into cart</fullName>
                    <default>true</default>
                    <label>Added into cart</label>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Requestor Cancellation</fullName>
                </value>
                <value>
                    <fullName>Request Rejected</fullName>
                </value>
                <value>
                    <fullName>Event Cancelled</fullName>
                </value>
                <value>
                    <fullName>Instructor being contacted</fullName>
                </value>
                <value>
                    <fullName>Learning Partner being contacted</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Awaiting Requestor's confirmation</fullName>
                </value>
                <value>
                    <fullName>More info Needed</fullName>
                </value>
                <value>
                    <fullName>Event Approved</fullName>
                </value>
                <value>
                    <fullName>Logistics Confirmed</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Event Cancelled but Paid</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Training_Event_Name__c</fullName>
        <description>This is the name of the Training Event.</description>
        <formula>Training_Offering_Id__r.Training_Event_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Training Event Name</label>
        <type>Text</type>
    </fields>
    <description>The desired Training Request selected by Regional Leads from the Training Curriculum. Regional Leads inserts the date required; Country; Language for individual Training Request.</description>
    <label>Training Request</label>
    <nameField>
        <displayFormat>TR-{0000000000}</displayFormat>
        <label>Training Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>PVT</fullName>
        <active>true</active>
        <description>Select for PVT Training Participation Requests</description>
        <label>PVT</label>
    </recordTypes>
</CustomObject>

objects/PEPE_Training_Sessions_Requested__c.object
<CustomObject>
    <fields>
        <fullName>Event_Day__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Event day lookup</description>
        <inlineHelpText>Please use this hyperlink to see the agenda for this event day</inlineHelpText>
        <label>Event Day</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND 3 AND 4</booleanFilter>
            <filterItems>
                <field>PEPE_Event_Day__c.Training_Event__r.Platform__c</field>
                <operation>equals</operation>
                <value>PVT</value>
            </filterItems>
            <filterItems>
                <field>PEPE_Event_Day__c.Training_Event__r.RecordTypeId</field>
                <operation>equals</operation>
                <value>Calendar Published RT</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>PVT</value>
            </filterItems>
            <filterItems>
                <field>PEPE_Event_Day__c.Name</field>
                <operation>contains</operation>
                <valueField>PEPE_Event_Day__c.Name</valueField>
            </filterItems>
            <infoMessage>PLEASE enter TRAINING EVENT ID to see/search for the list of EVENT DAYS available.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PEPE_Event_Day__c</referenceTo>
        <relationshipLabel>Event Day Selection Request</relationshipLabel>
        <relationshipName>Event_Day_Selection_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Training_Event_Name__c</fullName>
        <formula>Training_Request__r.Training_Offering_Id__r.Training_Event_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Training Event Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Training_Request__c</fullName>
        <description>Looks up to training request. Requestor uses this for session slots or event day subscriptions</description>
        <label>Training Request</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 5) OR (3 AND 4 AND 5)</booleanFilter>
            <errorMessage>Choose the actual request id you created for the event day selection.</errorMessage>
            <filterItems>
                <field>PEPE_Training_Request__c.PEPE_Record_Type__c</field>
                <operation>equals</operation>
                <value>Calendar</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>PVT</value>
            </filterItems>
            <filterItems>
                <field>PEPE_Training_Request__c.PEPE_Record_Type__c</field>
                <operation>equals</operation>
                <value>Architecture</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Architecture</value>
            </filterItems>
            <filterItems>
                <field>PEPE_Training_Request__c.Owner:User.Id</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <infoMessage>Make sure you selecting the correct training request id for your request</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>PEPE_Training_Request__c</referenceTo>
        <relationshipLabel>Training Sessions Requests</relationshipLabel>
        <relationshipName>Training_Sessions_Booked</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <description>This acts a junction object between TR and Event Day objects for PVT TE Events(Calendar based).

Also acts as junction object between TR and Session Slots for PP/Arch TE Events(Catalogue based).</description>
    <label>Training Sessions Requested</label>
    <nameField>
        <displayFormat>Requests - {00000}</displayFormat>
        <label>Training Sessions Requested Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Sessions Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>PVT</fullName>
        <active>true</active>
        <description>PVT based session requests</description>
        <label>PVT</label>
    </recordTypes>
</CustomObject>

classes/VFCntrl_PVT_TR_TSR_PEPE_Test.cls
/*Name    : VFCntrl_PVT_TR_TSR_PEPE_Test
Author  : Sathish Selvaraj
Purpose :   
Created Date: Mar 26 2015

Modification History:
Version  Date            Modified By     Description
--------------------------------------------------------------------------------------
 
*/

@isTest(SeeAllData=true)
private class  VFCntrl_PVT_TR_TSR_PEPE_Test {

    public static PEPE_Training_Request__c testTRObj;
    public static PEPE_Training_Event__c testTEObj;
    public static RecordType testRTObj;
    public static RecordType testRTObjTR;
    public static RecordType testRTPPObjTR;
    public static list<PEPE_Training_Sessions_Requested__c> testLstTSR = new list<PEPE_Training_Sessions_Requested__c>();
        
    static testMethod void myUnitTest(){
        Test.startTest();                
 
        createData();
        PageReference  pr=new PageReference('/apex/PVT_TR_TSR_PEPE?RecordType='+testRTObjTR.Id+'&Id='+testTRObj.Id+'&index=2');
        Test.setCurrentPage(pr);
        VFCntrl_PVT_TR_TSR_PEPE controller = new  VFCntrl_PVT_TR_TSR_PEPE(new ApexPages.StandardController(testTRObj));
        controller.TR_Id = testTRObj.Id;
        controller.RecTypeIdFromURL = testRTObjTR.Id;
        controller.redirectToPage();
        controller.showTSRRecInViewPage();
        controller.cancel();
        controller.saveTR(testTRObj);
        controller.saveTSR(testLstTSR);
        controller.removingRow();
        controller.saveTRAndTSR();
        testTRObj.Status__c = null;
        testTRObj.Geography__c = null;
        testTRObj.Cisco_Location__c = null;
        testTRObj.Address_1__c = null;
        testTRObj.City__c = null;
        controller.TRObj = testTRObj;
        controller.saveTRAndTSR();
        controller.TR_Id = null;
        controller.RecTypeNameFromURL = 'PVT';
        controller.initialize();
        PageReference  pr1=new PageReference('/apex/PVT_TR_TSR_PEPE?CF00N80000004wuJh='+testTEObj.Name+'&RecordType='+testRTObjTR.Id+'&index=2&RecordTypeName=PVT');
        Test.setCurrentPage(pr1);
        controller.initialize();
        PageReference  pr2=new PageReference('/apex/PVT_TR_TSR_PEPE?CF00N80000004wuJh='+testTEObj.Name+'&RecordType='+testRTPPObjTR.Id+'&index=2&RecordTypeName=Partner Plus');
        Test.setCurrentPage(pr2);
        controller.redirectToPage();
       Test.stopTest(); 
    }
    
    public static void createData(){
        
        
        list<PEPE_Event_Day__c> lstEDToInsert = new list<PEPE_Event_Day__c>();
        
        
        testRTObj = [select Id, Name from RecordType where Name = 'PVT' and SobjectType = 'PEPE_Training_Event__c' limit 1];
        RecordType TECalPubRTDtls = [select Id, Name from RecordType where Name = 'Calendar Published RT' and SobjectType = 'PEPE_Training_Event__c' limit 1];
        
        testTEObj = new PEPE_Training_Event__c(Status__c = 'Created',Internal_or_Partners__c='Internal Only',CLP_flag__c='No',PTP_flag__c='No',Report_Sent_Y_N__c='Country Enablement', Platform__c = 'PVT', Publish_to_Calendar__c='Yes', Training_Event_Name__c = 'Test PVT Event'
                     ,Event_Time_Zone__c = '(GMT-12:00) Dateline', Primary_Focus__c = 'Operations', Program__c = 'Partner Updates', Language_Coverage__c = 'Arabic'
                     ,Send_Notification__c = 'No', Start_Date_Time__c = system.Today(), End_Date_Time__c = system.Today()+5, Location_Name__c = 'Test Location'
                     ,Address_1__c = 'Test Address', Zip_Postal_Code__c = '0000000', RecordTypeId =testRTObj.Id);
        insert testTEObj;
        system.debug('--->>>>>>>>>>>>     CREATE  DATA HERE TC   '+testTEObj);
        
        testTEObj.RecordTypeId = TECalPubRTDtls.Id;
        
        update testTEObj;
        testTEObj = [Select Id, Name,Internal_or_Partners__c,CLP_flag__c,PTP_flag__c,Report_Sent_Y_N__c, Status__c, Platform__c, Publish_to_Calendar__c, Training_Event_Name__c, Event_Time_Zone__c, Primary_Focus__c, 
        Program__c, Language_Coverage__c, Send_Notification__c, Start_Date_Time__c, End_Date_Time__c, Location_Name__c, Address_1__c, Zip_Postal_Code__c, RecordTypeId 
        from PEPE_Training_Event__c where Id=:testTEObj.Id];
        
        testRTObjTR = [select Id, Name from RecordType where Name = 'PVT' and SobjectType = 'PEPE_Training_Request__c' limit 1];
        
        testRTPPObjTR = [select Id, Name from RecordType where Name = 'Partner Plus' and SobjectType = 'PEPE_Training_Request__c' limit 1];
                     
        testTRObj = new PEPE_Training_Request__c(RecordTypeId = testRTObjTR.Id,Status__c = 'Added into cart',CI_CVENT_Session_Name__c='Test Cvent Session Name', Cisco_Location__c = 'Test Location', Address_1__c = 'Test Address', City__c = 'Test City', Training_Offering_Id__c = testTEObj.Id);
                     
        insert testTRObj;
       
        for(Integer i=0;i<2;i++) {
            PEPE_Event_Day__c ed = new PEPE_Event_Day__c(Name = 'Test Event Day'+i, Training_Event__c = testTEObj.Id);
            lstEDToInsert.add(ed);
        }
        insert lstEDToInsert;
        system.debug('--->>>>>>>>>>>>     CREATE  DATA HERE TTR List   '+lstEDToInsert);
        
        RecordType tsrPVTRTDtls = [select Id from RecordType where Name='PVT' and SobjectType ='PEPE_Training_Sessions_Requested__c'];
        if(lstEDToInsert != null && lstEDToInsert.size() > 0) {
          
            for(PEPE_Event_Day__c edObj: lstEDToInsert) {
                PEPE_Training_Sessions_Requested__c tsrObj = new PEPE_Training_Sessions_Requested__c();
                tsrObj.Event_Day__c = edObj.Id;
                tsrObj.Training_Request__c = testTRObj.Id;
                tsrObj.TP_Room_Name__c = 'Test TP Room';
                tsrObj.Room_Capacity__c = 100;
                tsrObj.Host_Name__c = 'Test Host Name';
                tsrObj.Host_Email__c = 'test@test.com';
                tsrObj.RecordTypeId = tsrPVTRTDtls.Id;
                testLstTSR.add(tsrObj);
            }
            if(testLstTSR != null && testLstTSR.size() > 0) {
                insert testLstTSR;
             system.debug('@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ MAHESH @@@@@@@@@@@@@@@@@@lstEDToInsert###' + lstEDToInsert.size());  
            }
        }      
         
    
    }
}