objects/POV_eStar_Lineitem__c.object
<CustomObject>
    <fields>
        <fullName>Ext_Price__c</fullName>
        <label>Ext. Price($)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Item_Path__c</fullName>
        <label>Item Path</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_Number__c</fullName>
        <label>Line Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ordrered_Quantity__c</fullName>
        <label>Ordrered Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Proof_of_Value__c</fullName>
        <description>Proof of Value</description>
        <inlineHelpText>Proof of Value</inlineHelpText>
        <label>Proof of Value</label>
        <referenceTo>Proof_of_Value__c</referenceTo>
        <relationshipLabel>POV eStar Lineitems</relationshipLabel>
        <relationshipName>POV_eStar_Lineitems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Session_ID__c</fullName>
        <label>Session ID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_Set_Number__c</fullName>
        <label>Ship Set Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_List_Price__c</fullName>
        <label>Unit List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <description>POV eStar Lineitem</description>
    <label>POV eStar Lineitem</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POV eStar Lineitems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Proof_of_Value__c.object
<CustomObject>
    <fields>
        <fullName>CRCountry__c</fullName>
        <formula>Supporting_Opportunity__r.Account.CRCountry__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CRCountry</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <formula>TEXT(Supporting_Opportunity__r.Account.Country__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>POV_Approval_Status__c</fullName>
        <description>Shows the current approval state of this POV</description>
        <inlineHelpText>Shows the current approval state of this POV</inlineHelpText>
        <label>POV Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SE Manager Approved</fullName>
                </value>
                <value>
                    <fullName>SAM Work in Progress</fullName>
                </value>
                <value>
                    <fullName>SAM Submitted</fullName>
                </value>
                <value>
                    <fullName>RM Approved</fullName>
                </value>
                <value>
                    <fullName>OD Approved</fullName>
                </value>
                <value>
                    <fullName>SE Manager Rejected</fullName>
                </value>
                <value>
                    <fullName>RM Rejected</fullName>
                </value>
                <value>
                    <fullName>OD Rejected</fullName>
                </value>
                <value>
                    <fullName>Lead SE Approved</fullName>
                </value>
                <value>
                    <fullName>Lead SE Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PoV_Order_Category__c</fullName>
        <label>PoV Order Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>POV Security</fullName>
                    <default>true</default>
                    <label>POV Security</label>
                </value>
                <value>
                    <fullName>POV Security Partner-Led</fullName>
                </value>
                <value>
                    <fullName>POV Collaboration</fullName>
                </value>
                <value>
                    <fullName>POV Assurance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>This object is to provide the Proof of Value form</description>
    <label>Proof of Value</label>
    <nameField>
        <label>Proof of Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proof of Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/POVlineitem.cls
/**
   @Author :Jay Dash
   @name :POVlineitem 
   @CreateDate : 9/11/2014
   @Description :Getting POV and LineItem details from object<POV_eStar_Lineitem__c> after data received from estar through webservice
   @Version :1.0
   
       *********** Change History ***********
    9/11 - Remvoed the DLP URL hardcoding and using the custom setting value via domainUrl variable.
  */
  
  public with sharing class POVlineitem {
    string povId ;
    string povName ;    
    string povcrcountry ;
    string povordercategory ; 
    public string domainUrl;
    
    public string getDomainUrl(){       
        return Utilities.getConstant_CS('dlpDomainUrl');
    }
    public String getMySessionID(){
        return UserInfo.getSessionID();
    }
    public POVlineitem (ApexPages.StandardController controller) {
        Proof_of_Value__c pv =  (Proof_of_Value__c)controller.getRecord();
        povId = pv.id;
        povName = pv.Name;        
        povcrcountry = pv.CRCountry__c;
        povordercategory = pv.PoV_Order_Category__c;        
    }
    public List<string> getDlpPage(){
        return new List<string>();
    } 
    Public boolean getIsDisable() {
        //boolean isDisable=false;
        List<Proof_of_Value__c > povls=[ SELECT id,name,country__c,CRCountry__c,PoV_Order_Category__c,POV_Approval_Status__c FROM Proof_of_Value__c WHERE id=:povId ];
        if(!povls.isEmpty()){
            if(povls[0].POV_Approval_Status__c  !='SAM Work in Progress')
            if(povls[0].POV_Approval_Status__c  !='SE Manager Rejected')
            if(povls[0].POV_Approval_Status__c  !='RM Rejected')
            if(povls[0].POV_Approval_Status__c  !='OD Rejected')
                 {return true;}
            else 
                 {return false;}
        } 
         return false;
    }
    
    public List<POV_eStar_Lineitem__c> getValuesfromdlp()
    {    
        List<POV_eStar_Lineitem__c> lstDlp = [SELECT id,Name,Ship_Set_Number__c,Line_Number__c,Item_Path__c,Ordrered_Quantity__c,Unit_List_Price__c,Ext_Price__c,Session_ID__c,Proof_of_Value__c 
                                              FROM POV_eStar_Lineitem__c WHERE proof_of_Value__c =:povId order by Line_Number__c]; 
        return lstDlp; 
    } 
    public PageReference redirect(){
         String cfField = Utilities.getConstant_CS('povcustomfieldname');
         String cfFieldid = Utilities.getConstant_CS('povcustomfieldid');
         string optyName = ApexPages.currentPage().getParameters().get(cfField);
         string optyid = ApexPages.currentPage().getParameters().get(cfFieldid);       
         if(optyName == null){
             PageReference pgr;    
             pgr = new PageReference('/apex/POVListView');        
             pgr.setRedirect(true);
             return pgr; 
         }else{
            string objId = Proof_of_Value__c.SObjectType.getDescribe().getKeyPrefix();
            PageReference prEdit;
            prEdit = new Pagereference('/' + objId + '/e');
            prEdit.getParameters().put('nooverride','1');
            prEdit.getParameters().put(cfField,optyName);
            prEdit.getParameters().put(cfFieldid,optyid);
            prEdit.getParameters().put('retURL',optyid);
            prEdit.getParameters().put('cancelURL',optyid);
            prEdit.getParameters().put('saveURL',povId);           
            prEdit.setRedirect(true);
            return prEdit.setRedirect(true);        
         }
         return null;             
    }
 
 }