objects/Proof_of_Value__c.object
<CustomObject>
    <fields>
        <fullName>Decision_Date__c</fullName>
        <description>Decision Date</description>
        <inlineHelpText>When will the decision be made on the project?</inlineHelpText>
        <label>Decision Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expected_Bookings__c</fullName>
        <inlineHelpText>Estimation of bookings revenue from this POV</inlineHelpText>
        <label>Expected Bookings ($000s)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Lead_SE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lead Security Engineer</description>
        <inlineHelpText>This is the lead SE for the POV execution (usually the Security CSE or SE Specialist)</inlineHelpText>
        <label>Lead SE</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Proof_of_Value</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POV_Approval_Status__c</fullName>
        <description>Shows the current approval state of this POV</description>
        <inlineHelpText>Shows the current approval state of this POV</inlineHelpText>
        <label>POV Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SE Manager Approved</fullName>
                </value>
                <value>
                    <fullName>SAM Work in Progress</fullName>
                </value>
                <value>
                    <fullName>SAM Submitted</fullName>
                </value>
                <value>
                    <fullName>RM Approved</fullName>
                </value>
                <value>
                    <fullName>OD Approved</fullName>
                </value>
                <value>
                    <fullName>SE Manager Rejected</fullName>
                </value>
                <value>
                    <fullName>RM Rejected</fullName>
                </value>
                <value>
                    <fullName>OD Rejected</fullName>
                </value>
                <value>
                    <fullName>Lead SE Approved</fullName>
                </value>
                <value>
                    <fullName>Lead SE Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>POV_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PoV Contact</description>
        <inlineHelpText>The customer contact that will receive and be responsible for execution of the POV</inlineHelpText>
        <label>POV Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Proof of Values</relationshipLabel>
        <relationshipName>Proof_of_Value</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POV_Description__c</fullName>
        <description>Describe the overall value a successful Eval will have to Sourcefire</description>
        <inlineHelpText>Document relevant information of the sales opportunity to help review the POV. Include reasons for POV, relevant background information, qualification information, etc.</inlineHelpText>
        <label>POV Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>POV_Duration_Days__c</fullName>
        <defaultValue>90</defaultValue>
        <description>Proof of value Duration (Days)</description>
        <inlineHelpText>Expected duration of POV should be 90 days</inlineHelpText>
        <label>POV Duration (Days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>POV_Start_Date__c</fullName>
        <description>Proof of value Start Date</description>
        <inlineHelpText>Estimated POV start date. NOTE: Once POV has initiated set this date to the day of the POV kick-off or the first day of license enablement.</inlineHelpText>
        <label>POV Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>POV_Type__c</fullName>
        <description>Proof of value Type</description>
        <inlineHelpText>TACTICAL: Lower value opp., lacks biz drivers, used for discovery. STRATEGIC: High value opp., clear biz drivers. C-POC: High value opp., perform in Cisco lab. SOFTWARE ONLY: No HW reqs. VM solution, license for current equipment, or SW only POV.</inlineHelpText>
        <label>POV Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Tactical</fullName>
                </value>
                <value>
                    <fullName>Strategic</fullName>
                </value>
                <value>
                    <fullName>Partner Executed</fullName>
                </value>
                <value>
                    <fullName>C-POC</fullName>
                </value>
                <value>
                    <fullName>Software Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Plan_to_Win__c</fullName>
        <description>Describe the sales team’s plan to both successfully execute the POV and achieve both a technical win and a closed deal</description>
        <inlineHelpText>Describe the sales team’s plan to both successfully execute the POV and achieve both a technical win and a closed deal</inlineHelpText>
        <label>Plan to Win</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PoV_Order_Category__c</fullName>
        <label>PoV Order Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>POV Security</fullName>
                    <default>true</default>
                    <label>POV Security</label>
                </value>
                <value>
                    <fullName>POV Security Partner-Led</fullName>
                </value>
                <value>
                    <fullName>POV Collaboration</fullName>
                </value>
                <value>
                    <fullName>POV Assurance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <description>Product</description>
        <inlineHelpText>Select the product types / capabilities that will be used for the POV</inlineHelpText>
        <label>Products</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>--None--</fullName>
                </value>
                <value>
                    <fullName>AMP for Endpoints</fullName>
                </value>
                <value>
                    <fullName>AMP for ESA/WSA/CWS</fullName>
                </value>
                <value>
                    <fullName>AMP for FirePower/ASA</fullName>
                </value>
                <value>
                    <fullName>AMP Private Cloud</fullName>
                </value>
                <value>
                    <fullName>AMP Threat Grid</fullName>
                </value>
                <value>
                    <fullName>ASA</fullName>
                </value>
                <value>
                    <fullName>ASA-High</fullName>
                </value>
                <value>
                    <fullName>CDO-Cisco Defense Orchestrator</fullName>
                </value>
                <value>
                    <fullName>CWS</fullName>
                </value>
                <value>
                    <fullName>Cyber Threat Defence</fullName>
                </value>
                <value>
                    <fullName>ESA</fullName>
                </value>
                <value>
                    <fullName>FP Killbox</fullName>
                </value>
                <value>
                    <fullName>ISE</fullName>
                </value>
                <value>
                    <fullName>NGFW</fullName>
                </value>
                <value>
                    <fullName>NGIPS</fullName>
                </value>
                <value>
                    <fullName>Stealthwatch</fullName>
                </value>
                <value>
                    <fullName>TrustSec</fullName>
                </value>
                <value>
                    <fullName>WSA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Security_AM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Security AM</description>
        <inlineHelpText>The Security Account Manager that is associated with this parent opportunity of the POV</inlineHelpText>
        <label>Security AM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Proof_of_Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_to_Address__c</fullName>
        <label>Ship to Address</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Ship_to_Contact_Email__c</fullName>
        <label>Ship to Contact Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Ship_to_Contact_Name__c</fullName>
        <label>Ship to Contact Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Contact_Phone__c</fullName>
        <label>Ship to Contact Phone</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Supporting_Opportunity__c</fullName>
        <description>Supporting Opportunity</description>
        <inlineHelpText>Auto-populated: Sales Opportunity specific to this POV</inlineHelpText>
        <label>Supporting Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proof of Values</relationshipLabel>
        <relationshipName>Evaluations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <description>This object is to provide the Proof of Value form</description>
    <label>Proof of Value</label>
    <nameField>
        <label>Proof of Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proof of Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/POVlineitem_Test.cls
/**
   @Author <Lakshmisetty.Suresh>
   @name <POVlineitem_Test>
   @CreateDate <11/10/2014>
   @Description <Testclass for Povlineitem>
   @Version <1.0>
  */
  @isTest(seealldata=true)
 private class POVlineitem_Test{
 static testmethod void unitTest(){
    List<user> us = [SELECT Id from user where isactive=true Limit 1]; 
    Contact cnt = GenericStaticTestData.gettestEndUserContactRecord();
    Opportunity opt = GenericStaticTestData.gettestParentOpportunityRecord();
    Proof_of_Value__c povr = new Proof_of_Value__c();     
    povr.Name ='TestMon11';
    povr.Ship_to_Address__c ='Test Addresss';
    povr.Ship_to_Contact_Email__c= 'test@gmail.com';  
    povr.Ship_to_Contact_Name__c= 'Test User';
    povr.Ship_to_Contact_Phone__c= '1223456673';
    povr.POV_Description__c= 'Testing';
    povr.Products__c='AMP';
    povr.PoV_Order_Category__c='POV Security';
    povr.POV_Type__c='strategic';    
    povr.POV_Start_Date__c =system.Today();
    povr.Decision_Date__c =system.Today();
    povr.POV_Duration_Days__c = 45;
    povr.Expected_Bookings__c= 1;
    povr.Lead_SE__c =us[0].id;
    povr.Security_AM__c =us[0].id;
    povr.POV_Contact__c =cnt.id; 
    povr.Plan_to_Win__c =us[0].id;     
    povr.Supporting_Opportunity__c = opt.id;
    povr.POV_Approval_Status__c = 'SAM Work in Progress';
    String cfField = Utilities.getConstant_CS('povcustomfieldname');
    Test.startTest();
    insert povr;
    ApexPages.StandardController povltobj= new ApexPages.StandardController(povr);
    PageReference pageRef = Page.POVeStarLineItem;
    pageRef.getParameters().put(cfField,opt.name);
    Test.setCurrentPage(pageRef);
    POVlineitem plt = new POVlineitem(povltobj);
    plt.getValuesfromdlp();
    plt.getIsDisable();
    plt.getDlpPage();
    plt.redirect();
    plt.getMySessionID();      
    Test.stopTest();     
   }
    
 static testmethod void unitTest1(){
    List<user> us = [SELECT Id from user where isactive=true Limit 1]; 
    Contact cnt = GenericStaticTestData.gettestEndUserContactRecord();
    Opportunity opt = GenericStaticTestData.gettestParentOpportunityRecord();
    Proof_of_Value__c povr = new Proof_of_Value__c();     
    povr.Name ='TestMon11';
    povr.Ship_to_Address__c ='Test Addresss';
    povr.Ship_to_Contact_Email__c= 'test@gmail.com';  
    povr.Ship_to_Contact_Name__c= 'Test User';
    povr.Ship_to_Contact_Phone__c= '1223456673';
    povr.POV_Description__c= 'Testing';
    povr.Products__c='AMP';
    povr.PoV_Order_Category__c='POV Security';
    povr.POV_Type__c='strategic';    
    povr.POV_Start_Date__c =system.Today();
    povr.Decision_Date__c =system.Today();
    povr.POV_Duration_Days__c = 45;
    povr.Expected_Bookings__c= 1;
    povr.Lead_SE__c =us[0].id;
    povr.Security_AM__c =us[0].id;
    povr.POV_Contact__c =cnt.id; 
    povr.Plan_to_Win__c =us[0].id;     
    povr.Supporting_Opportunity__c = opt.id; 
    povr.POV_Approval_Status__c = 'SE Manager Rejected';
    Test.startTest();
    insert povr;
    ApexPages.StandardController povltobj= new ApexPages.StandardController(povr);
    POVlineitem plt = new POVlineitem(povltobj);
    plt.getValuesfromdlp();
    plt.getIsDisable();
    plt.getDlpPage();
    plt.redirect();
    plt.getMySessionID();      
    Test.stopTest();
   }
}