objects/QIJobSettings__c.object
<CustomObject>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Settings for the Quote Integration Jobs</description>
    <label>QI Job Settings</label>
</CustomObject>

objects/Quote_Integration_Job__c.object
<CustomObject>
    <fields>
        <fullName>Is_Processing__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Processing</label>
        <type>Checkbox</type>
    </fields>
    <description>Master jobs table for tracking currently in-progress Quote Integrations for Opportunity CCW BOM integration.</description>
    <label>Quote Integration Job</label>
    <nameField>
        <displayFormat>QI-{00000000}</displayFormat>
        <label>Quote Integration Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Integration Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/QI_Job_Scheduler.cls
/************************************************************************************************************************************
Name    : QI_Job_Scheduler 
Author  : Eric Pesch (epesch)
Purpose : This class is the scheduler for the Batchable cleaning jobs for the Quote Integration Jobs
Created Date: 12/09/2017
Modification History: 

*************************************************************************************************************************************/
global class QI_Job_Scheduler implements Schedulable {
	private static String TAG = '[QI_Job_Scheduler] - ';
	
	/*Schedule using the following in Developer Console
	QI_Job_Scheduler job = new QI_Job_Scheduler();
	String cron1 = '0 0 * * * ?';
	String cron2 = '0 15 * * * ?';
	String cron3 = '0 30 * * * ?';
	String cron4 = '0 45 * * * ?'; 
	
	System.schedule('QICleaningJob 00:00',cron1,job);
	System.schedule('QICleaningJob 00:15',cron2,job);
	System.schedule('QICleaningJob 00:30',cron3,job);
	System.schedule('QICleaningJob 00:45',cron4,job);
	*/
	
	global void execute(SchedulableContext ctx){
		//TransactionLogSettings__c.getInstance('PurgeAfterDays').Value__c;
		String unlockMin = QIJobSettings__c.getInstance('UnlockJobsAfterMin').Value__c;
		String cleanDays = QIJobSettings__c.getInstance('PurgeJobsAfterDays').Value__c;
		
		Datetime compDate = system.now().addMinutes(Integer.valueOf(unlockMin));
		
		//Queue reprocess job
		QI_Job_ReprocessBatch bReprocess = new QI_Job_ReprocessBatch();
		bReprocess.query = 'SELECT Id, LastModifiedDate, Is_Processing__c FROM Quote_Integration_Job__c'
						+' WHERE Is_Processing__c = true'
						+' AND LastModifiedDate  <= ' + compDate.formatGmt('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'');
		System.debug(TAG + 'Query - ' + bReprocess.query);
		ID batchId1 = Database.executeBatch(bReprocess);
		System.debug(TAG + 'Batch Process - ' + batchId1);
		
		//Queue cleaning job
		QI_Job_CleanBatch bDel = new QI_Job_CleanBatch();
		bDel.query = 'SELECT Id, LastModifiedDate FROM Quote_Integration_Job__c WHERE LastModifiedDate < LAST_N_DAYS:' 
							+ cleanDays;
		
		ID batchId2 = Database.executeBatch(bDel);
		System.debug(TAG + 'Batch Process - ' + batchId2);
	}
}