objects/Quote__c.object
<CustomObject>
    <fields>
        <fullName>DM_Quote_ID__c</fullName>
        <description>ID of the quotes from DM</description>
        <externalId>true</externalId>
        <label>Quote ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <description>Displays the Opportunity Name for the associated Partner Quote</description>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Partner_Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity_Status__c</fullName>
        <description>Displays the Opportunity Status for the associated Partner Quote</description>
        <formula>CASE(Opportunity_Name__r.Opportunity_Status__c, 'Active', 'Active','')</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote_Summary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the associated Quote Summary on Partner Quote</description>
        <label>Quote Summary</label>
        <referenceTo>Quote_Summary__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Partner_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>Quote Header information.  Used in related lists.  Quote details stored in PDR.</description>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Partner_Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the associated Partner Quote with the Quote Summary</description>
        <label>Partner Quote</label>
        <referenceTo>Quote__c</referenceTo>
        <relationshipLabel>Quote Summary</relationshipLabel>
        <relationshipName>Quote_Summary1</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>Used to create a Link on related lists.  Also stores the Deal ID which is required in the punch out to PDR.</description>
    <label>Quote Summary</label>
    <nameField>
        <label>Quote Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/QuoteSummary_CTE_TEST.cls
@isTest(SeeAllData=TRUE)
public class QuoteSummary_CTE_TEST{
    
    private static testMethod void QuoteSummary_CTE(){
        Test.setCurrentPageReference(new PageReference('QuoteSummary'));
        Opportunity o = new Opportunity(name='Test',StageName='2 - Qualified',CloseDate=System.today() - 50,Expected_Product__c=10.0,error_description__c='error',DealID__c='1',Opportunity_Status__c='Active'); 
        insert o;
        Quote__c qt = new Quote__c();
            qt.Opportunity_Name__c = o.ID;
            qt.DM_Quote_ID__c = o.DealID__c;
            insert qt;
        
        Quote_Summary__c qs = new Quote_Summary__c();
            qs.Partner_Quote__c = qt.id;
            insert qs;
            System.debug('QS ID --- '+qs.id);
            
        PageReference pr = Page.QuoteSummary;
        Test.setCurrentPageReference(pr);
        pr.getParameters().put('id', qs.Id);
        ApexPages.StandardController sc = new ApexPages.StandardController(qs); 
        QuoteSummary_CTE controller = new QuoteSummary_CTE(sc);
        controller.getBaseUrl();
        controller.getPdrDown();
        controller.getQuoteStatus();
         controller.getprofilecheck();
    }    
}