objects/Quote__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <description>Displays the Opportunity Name for the associated Partner Quote</description>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Partner_Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <description>Quote Header information.  Used in related lists.  Quote details stored in PDR.</description>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/lxQuoteNewOverride.cls
public class lxQuoteNewOverride {
	@AuraEnabled
	public static String getQueryString(String sObjectId) {
        String queryString = '';
        String fieldSfId = 'CF';
        String recordName = '';
        
        if(String.isNotBlank(sObjectId) && String.isNotEmpty(sObjectId) && sObjectId != null) {
            system.debug('sobjectId: '+ sObjectId);
            Opportunity oOppty = [SELECT Name FROM Opportunity WHERE Id = :sObjectId];
            recordName = EncodingUtil.urlEncode(oOppty.Name, 'UTF-8');
        }
        
        String durableId = [ SELECT DurableId FROM FieldDefinition WHERE EntityDefinition.QualifiedApiName = 'Quote__c' AND QualifiedApiName = 'Opportunity_Name__c'].DurableId.substringAfter('.');            
        fieldSfId += durableId;
        //Added mode=lgt to send to CCW for navigation back and forth
        queryString = '?' + fieldSfId + '=' + recordName + '&' + fieldSfId + '_lkid=' + sObjectId + '&scontrolCaching=1&retURL=%2F' + sObjectId + '&sfdc.override=1&mode=lgt'; 
        
        return queryString;
    }
}