objects/Resource_Request_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Resource_Status__c</fullName>
        <description>This field defines the status of the Requested Resource.</description>
        <label>Resource Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Declined - Approved</fullName>
                </value>
                <value>
                    <fullName>Declined - Pending</fullName>
                </value>
                <value>
                    <fullName>Direct Assignment</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>This object is used to store SE Requests and SE Assignments from the SE Workspace</description>
    <label>Resource Request/Assignment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Resource Request/Assignments Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Requests and Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Additional_User_Permissions__c</fullName>
        <description>Allows permission for additional functionality which are based on User and not by profile.
1)AccountCreateByTerritory: New SBC functionality which allows SBC based on Geo Rules
2)Enable EndUser ACCTCreation : Can Create End-User accounts
3)Enable Lead Conversion : Can Convert leads
4)Enable PDR ACCTCreation : Can Create End-User Account during CCW deal conversion
5)Request Resource : Allows AMs to access SE functionality
6)SE User : Allows SEs to access SE Functionality
7)2028 Visibility:Users that will be refreshed by 2028 black box process
8)NBM Approver : User can set status field of NBM records to 'Screen 3' Approval status</description>
        <label>Additional User Permissions</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>2028 Visibility</fullName>
                </value>
                <value>
                    <fullName>AccountCreateByTerritory</fullName>
                </value>
                <value>
                    <fullName>AcquisitionUser</fullName>
                </value>
                <value>
                    <fullName>Activate Sales Account View</fullName>
                </value>
                <value>
                    <fullName>CCE Enabled</fullName>
                </value>
                <value>
                    <fullName>DSEC360</fullName>
                </value>
                <value>
                    <fullName>DSEC360SAV</fullName>
                </value>
                <value>
                    <fullName>DSEContactIntelligence</fullName>
                </value>
                <value>
                    <fullName>DSECRinSFDC</fullName>
                </value>
                <value>
                    <fullName>DSEFA</fullName>
                </value>
                <value>
                    <fullName>DSEGA</fullName>
                </value>
                <value>
                    <fullName>DSENotification</fullName>
                </value>
                <value>
                    <fullName>DSESWSS</fullName>
                </value>
                <value>
                    <fullName>DSETAC</fullName>
                </value>
                <value>
                    <fullName>Einstein Opportunities</fullName>
                </value>
                <value>
                    <fullName>Enable_ePSS</fullName>
                </value>
                <value>
                    <fullName>Enable_VSS</fullName>
                </value>
                <value>
                    <fullName>Enable EndUser ACCTCreation</fullName>
                </value>
                <value>
                    <fullName>Enable Lead Conversion</fullName>
                </value>
                <value>
                    <fullName>Enable PDR ACCTCreation</fullName>
                </value>
                <value>
                    <fullName>Enable Target Prospect Creation</fullName>
                </value>
                <value>
                    <fullName>GSPO_BDM</fullName>
                </value>
                <value>
                    <fullName>GSSO HD Forecast User</fullName>
                </value>
                <value>
                    <fullName>MCP Prospect Engage</fullName>
                </value>
                <value>
                    <fullName>MCP Prospect Profiler</fullName>
                </value>
                <value>
                    <fullName>NBM Approver</fullName>
                </value>
                <value>
                    <fullName>NextGen Forecasting Pilot User</fullName>
                </value>
                <value>
                    <fullName>QIJanACVPilotUser</fullName>
                </value>
                <value>
                    <fullName>RAE SEP Enabled</fullName>
                </value>
                <value>
                    <fullName>Request Resource</fullName>
                </value>
                <value>
                    <fullName>SE User</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/lxOpptyUpdateOnResourceAssignmentTest.cls
/**************************************
Author          : R.Hari Krishna(ratharik) 
Release         : May Release
Created         : April 22,2019
Functionality   : Test class

Modification History:
Itrack#        Date        		Author              		Change  
****************************************************************************
US290188    April 22,2019      Hari Krishna(ratharik)    Initial Draft
**********************************************/
@isTest
public class lxOpptyUpdateOnResourceAssignmentTest {
	//helps us to setUp dummy data
    @testSetup static void setup() {
        lxTestDataFactory.createCustomSettings();
    }
    
    @isTest
    static void testSEStatusUpdateOnOppty() { 
        Utilities.setIsTestMethod(true);
        Utilities.setValidationSkip(true);
        User userForTesting = [SELECT Id FROM User WHERE Additional_User_Permissions__c ='SE User' AND isActive= True LIMIT 1];
        //mkella
        // skip all validation rules
        /*    
            Utilities.setSkip(true);   
            Utilities.setValidationSkip(true);
            Utilities.setSkipFuture(true);
		*/
        //mkella
        User testUser = lxTestDataFactory.getLoggedInUser();
        Opportunity testOpty = lxTestDataFactory.createSingleOppty();
        insert testOpty;
        
        Resource_Request_Assignment__c testResrReqAssignmnt = lxTestDataFactory.createSingleResourceRqstAssgmnt(testOpty.Id,testUser.Id);
        testResrReqAssignmnt.Resource_Status__c = 'Assigned';
        
        system.runAs(userForTesting) {
            insert testResrReqAssignmnt;
			update testResrReqAssignmnt;
			delete testResrReqAssignmnt;            
        }
    }   
}