objects/Technology_Profile__c.object
<CustomObject>
    <fields>
        <fullName>FK_Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Technology Profiles (Account)</relationshipLabel>
        <relationshipName>R00N30000000gclUEAQ</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <description>Contains Technology Profile/Install Base information</description>
    <label>Technology Profile</label>
    <nameField>
        <displayFormat>TP-{0}</displayFormat>
        <label>Technology Profile ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Technology Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TechnologyProfile_AccountHelper.cls
public with sharing class TechnologyProfile_AccountHelper
{
    
    public static void createTechnologyProfile(List<Account> lstAccounts)
    {
   
        List<Technology_Profile__c> lstTechprofile = new List<Technology_Profile__c>();
        List<Recordtype> recordId = [select id,Name from Recordtype where name = 'End-User' LIMIT 1];
                
        for(Account account:lstAccounts) {        
        if (account.RecordtypeId == recordId[0].Id) {
        Technology_Profile__c techprofile = new Technology_Profile__c();
        system.debug('here1-->'+account.Id);
        techprofile.FK_Account__c = account.Id;
        lstTechprofile.add(techprofile);
        }
        }
        system.debug('here2-->'+lstTechprofile.size());
        if(lstTechprofile.size() > 0) {
            insert lstTechprofile;
        }
        
        
    }
    
}