objects/User.object
<CustomObject>
    <fields>
        <fullName>Additional_User_Permissions__c</fullName>
        <description>Allows permission for additional functionality which are based on User and not by profile.
1)AccountCreateByTerritory: New SBC functionality which allows SBC based on Geo Rules
2)Enable EndUser ACCTCreation : Can Create End-User accounts
3)Enable Lead Conversion : Can Convert leads
4)Enable PDR ACCTCreation : Can Create End-User Account during CCW deal conversion
5)Request Resource : Allows AMs to access SE functionality
6)SE User : Allows SEs to access SE Functionality
7)2028 Visibility:Users that will be refreshed by 2028 black box process
8)NBM Approver : User can set status field of NBM records to 'Screen 3' Approval status</description>
        <label>Additional User Permissions</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>2028 Visibility</fullName>
                </value>
                <value>
                    <fullName>AccountCreateByTerritory</fullName>
                </value>
                <value>
                    <fullName>AcquisitionUser</fullName>
                </value>
                <value>
                    <fullName>Activate Sales Account View</fullName>
                </value>
                <value>
                    <fullName>CCE Enabled</fullName>
                </value>
                <value>
                    <fullName>DSEC360</fullName>
                </value>
                <value>
                    <fullName>DSEC360SAV</fullName>
                </value>
                <value>
                    <fullName>DSEContactIntelligence</fullName>
                </value>
                <value>
                    <fullName>DSECRinSFDC</fullName>
                </value>
                <value>
                    <fullName>DSEFA</fullName>
                </value>
                <value>
                    <fullName>DSEGA</fullName>
                </value>
                <value>
                    <fullName>DSENotification</fullName>
                </value>
                <value>
                    <fullName>DSESWSS</fullName>
                </value>
                <value>
                    <fullName>DSETAC</fullName>
                </value>
                <value>
                    <fullName>Einstein Opportunities</fullName>
                </value>
                <value>
                    <fullName>Enable_ePSS</fullName>
                </value>
                <value>
                    <fullName>Enable_VSS</fullName>
                </value>
                <value>
                    <fullName>Enable EndUser ACCTCreation</fullName>
                </value>
                <value>
                    <fullName>Enable Lead Conversion</fullName>
                </value>
                <value>
                    <fullName>Enable PDR ACCTCreation</fullName>
                </value>
                <value>
                    <fullName>Enable Target Prospect Creation</fullName>
                </value>
                <value>
                    <fullName>GSPO_BDM</fullName>
                </value>
                <value>
                    <fullName>GSSO HD Forecast User</fullName>
                </value>
                <value>
                    <fullName>MCP Prospect Engage</fullName>
                </value>
                <value>
                    <fullName>MCP Prospect Profiler</fullName>
                </value>
                <value>
                    <fullName>NBM Approver</fullName>
                </value>
                <value>
                    <fullName>NextGen Forecasting Pilot User</fullName>
                </value>
                <value>
                    <fullName>QIJanACVPilotUser</fullName>
                </value>
                <value>
                    <fullName>RAE SEP Enabled</fullName>
                </value>
                <value>
                    <fullName>Request Resource</fullName>
                </value>
                <value>
                    <fullName>SE User</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reporting_Manager_Level_1_cec__c</fullName>
        <label>Reporting Manager Level 1 cec</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/lxMultiSelectPicklist.cls
public class lxMultiSelectPicklist {
 @AuraEnabled
    public static List < forCheck > fetchLookUpValues(String ObjectName,String field) {
        system.debug('ObjectName-->' + ObjectName);
       // String searchKey ='%'+ searchKeyWord + '%';
        String fields= field;
        //System.debug('field' + field);
         System.debug('>>Shivi');
        List < forCheck > returnList = new List < forCheck > ();
      
        // Create a Dynamic SOQL Query For Fetch Record List with LIMIT 5 
        String userId=(userInfo.getUserName()).substringBefore('@');
//String conditoin Reporting_Manager_Level_1_cec__c=:userId.toUpperCase() AND Additional_User_Permissions__c includes ('SE User')]; 
          String var='('+'\''+'SE User'+'\''+')';
        String sQuery =  'select id,'+field+' from ' +ObjectName + ' where '+ 'Reporting_Manager_Level_1_cec__c='+ '\''+userId.toUpperCase()+'\''+' AND isActive=true AND Additional_User_Permissions__c includes '+ var;
        System.debug(sQuery);

        List < sObject > lstOfRecords = Database.query(sQuery);
    	//adding logged In user
        forCheck fcheck=new forCheck();
        fcheck.label=UserInfo.getName();
        fcheck.value=UserInfo.getUserId();
        returnList.add(fcheck);
        
        for (sObject obj: lstOfRecords) {
            forCheck fc=new forCheck();
            fc.label= string.valueOf(obj.get(fields));
            fc.value= string.valueOf(obj.id);
            returnList.add(fc);
        }
       
        System.debug('>>'+returnList);
        return returnList;
    }
    public class forCheck{
        @AuraEnabled
        public String label{get; set;}
        @AuraEnabled
        public string value{get; set;}
    }
    @AuraEnabled
    public static List<forCheck> getReportees(){
        String userId=(userInfo.getUserName()).substringBefore('@');
        List<User> reporteeLst=[Select id,Name from User where Reporting_Manager_Level_1_cec__c=:userId.toUpperCase() AND Additional_User_Permissions__c includes ('SE User') AND isActive=true];
        
         List < forCheck > returnList = new List < forCheck > ();
        forCheck fcheck=new forCheck();
        fcheck.label=UserInfo.getName();
        fcheck.value=UserInfo.getUserId();
        returnList.add(fcheck);
         for (User obj: reporteeLst) {
            forCheck fc=new forCheck();
            fc.label= obj.Name;
            fc.value= obj.Id;
            returnList.add(fc);
        }
        return returnList;
    }

}